jitsi/jitsi-meet

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/org/jitsi/meet/MainApplication.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiInitializer.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiReactNativeHost.java
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java

Android greenfield

---

react/features/toolbox/components/native/styles.js

fix(toolbox) fixed toolbox safeareaview on mobile

---

react/features/calendar-sync/components/CalendarList.native.js
react/features/mobile/navigation/components/welcome/components/WelcomePageTabs.js

fix(calendar-sync) fixed pull to refresh on Calendar List mobile

---

patches/react-native-dialog+9.2.1.patch
react/features/base/ui/Tokens.js
react/features/lobby/components/native/LobbyModeSwitch.js
react/features/lobby/components/native/styles.js
react/features/welcome/components/native/settings/components/SettingsView.js
react/features/welcome/components/native/settings/components/styles.js

1. Patch that fixes Container dark and light background color on Android.
2. Lighten up switch track color.

fix(mobile-ui) dialog background color, switch track color

---

react/features/base/ui/Tokens.js
react/features/conference/components/native/styles.js
react/features/display-name/components/native/styles.js
react/features/filmstrip/components/native/Thumbnail.js

1. Added some padding for display name label
2. Removed ColorPalette from display name native styles
3. Fixed hide youAreAlone text in tile view

fix(mobile-ui) ui fixes

---

react/.eslintrc.js
react/features/shared-video/components/web/YoutubeVideoManager.js

fix(lint) don't check for Flow types on files without the annotation

---

react/features/facial-recognition/facialExpressionsWorker.js
react/features/facial-recognition/functions.js

TF 3.0 supports getting an ImageBitmap in fromPixels: https://js.tensorflow.org/api/3.0.0/#browser.fromPixels

fix(facial-recognition) avoid image data conversion

---

react/features/filmstrip/components/native/Filmstrip.js
react/features/filmstrip/components/native/styles.js
react/features/toolbox/components/native/styles.js

https://user-images.githubusercontent.com/26413496/155514131-51e56bda-c99b-4320-b49e-0d93fbf42415.mp4

fix(filmstrip/toolbox) filmstrip and toolbox mobile ui adjustments

---

react/features/base/i18n/i18next.js

fix(i18n) fix some country names

---

react/features/filmstrip/components/web/ThumbnailWrapper.js

Show border on the pinned participant in the vertical filmstrip grid view

fix(thumbnail) Fix pinned participant in the resizable filmstrip

---

css/_video-preview.scss

fix(video-devices) Fix video devices not scrollable

---

react/features/deep-linking/components/DeepLinkingMobilePage.web.js
react/features/invite/components/dial-in-summary/web/DialInSummary.js

Adds missing url prop to DialInSummary and safeguard the URL creation.

fix: Fixes loading web on mobile browser.

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example

Enable polls for breakout rooms by default.

---

react/features/base/react/components/web/Text.js

[features/base/app] <APP.componentDidCatch>:  TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Indexed property setter is not supported.

fix: Fixes recording dialog web rendering.

---

react/features/dynamic-branding/functions.any.js

extract fqn from path when the meeting is public

fix: extract fqn from public meeting

---

react/features/display-name/components/web/index.js

feat(display-name) remove DisplayNameLabel web

---

android/gradle.properties
ios/app/broadcast-extension/Info.plist
ios/app/src/Info.plist
ios/app/watchos/app/Info.plist
ios/app/watchos/extension/Info.plist

chore(rn,versions) bump app versions

---

resources/prosody-plugins/mod_token_verification.lua

Set it as the highest priorities, if denying access, better do it earlier.

fix: Updates token verification hooks priority.

---

modules/UI/videolayout/VideoContainer.js

Fix width when the filmstrip is resized

fix(screensharing) Fix screensharing container width

---

css/premeeting/_premeeting-screens.scss

Fixes : https://github.com/jitsi/brave-tracker/issues/72

fix(prejoin) Fix layout on reduced height

---

config.js
react/features/toolbox/actions.web.js

feat(toolbar) add flag for autohiding while chat open

---

react/features/filmstrip/actionTypes.js
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/reducer.js
react/features/shared-video/components/web/SharedVideo.js

Calculate shared video width with the filmstrip width
Make resizable filmstrip mouseup event work with shared video iframe

fix(filmstrip) Fix resizable filmstrip with shared video

---

react/features/video-menu/components/web/ParticipantContextMenu.js

Fix ask to unmute

---

css/_participants-pane.scss
react/features/base/ui/constants.js

This is a commit cherry picked from #11079 to support RTL layout.

refactor(participnats-pane) move participant-avatar to commmonStyles

---

config.js
css/filmstrip/_tile_view.scss
css/filmstrip/_vertical_filmstrip.scss
react/features/base/config/configWhitelist.js
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/constants.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/subscriber.native.js
react/features/filmstrip/subscriber.web.js
react/features/video-layout/functions.js

feat(tile-view): Optimize grid dimnsions.

---

lang/main.json
react/features/base/ui/Tokens.js
react/features/conference/components/native/AlwaysOnLabels.js
react/features/dynamic-branding/functions.any.js
react/features/recording/actions.native.js
react/features/recording/components/Recording/native/HighlightButton.js
react/features/recording/components/Recording/native/HighlightDialog.js
react/features/recording/components/Recording/native/index.js
react/features/recording/components/Recording/styles.native.js
react/features/recording/functions.js

If necessary I will change the extractFqnFromPath to work on native.

add(highlights): mobile flow

---

patches/react-native-dialog+9.2.1.patch

patch(react-native-dialog) - replaced PlatformColor with hardcoded colors on Android

---

react/features/settings/components/web/SettingsDialog.js

Fixes crash when the participant becomes moderator while the dialog is open

fix(settings-dialog) Fix crash

---

config.js

Update config.js with new e2eping properties.

---

react/features/mobile/navigation/components/styles.js

When we first create and join a room there is a white background color appearing in the bottom of the Connecting screen

fix(mobile/navigation) - fixed bottom color glitch

---

react/features/overlay/components/web/UserMediaPermissionsOverlay.js

fix(overlay) fix not showing the correct gUM helper text

---

resources/prosody-plugins/mod_reservations.lua

Added option to enable integration of reservations plugin with mod_muc_max_occupants. This opens up possibility of per-room occupancy limits.
When enabled, API payload can contain optional "max_occupants" field which will override max_occupants value for that specific room. mod_muc_max_occupants will also have to be enabled for this to work.
If `reservations_enable_max_occupants` module config not enabled, there should be no change to existing behaviour.

feat(reservations) add integration with mod_muc_max_occupants

---

react/features/recording/components/Recording/StartRecordingDialogContent.js
react/features/recording/components/Recording/native/StartRecordingDialog.js
react/features/recording/components/Recording/web/StartRecordingDialog.js

fix(recording) start is no longer disabled when dropbox upload is enabled

---

react/features/participants-pane/components/native/CollapsibleList.js
react/features/participants-pane/components/native/MeetingParticipantList.js
react/features/participants-pane/components/native/ParticipantsPane.js
react/features/participants-pane/components/native/styles.js

https://user-images.githubusercontent.com/26413496/160089143-a6aef5d3-0300-44ab-8a81-e6c56e5ece92.mp4

feat(participants/native) - updated container styles

---

react/features/recording/components/Recording/AbstractHighlightButton.js
react/features/recording/components/Recording/web/HighlightButton.js

fix(highlight) implement custom notification for highlight start recording

---

react/features/recording/components/Recording/native/StartRecordingDialog.js

fix(rn,recording) fix recording dialog state not updating

---

lang/main-fr.json

CLA already signed in this [PR](https://github.com/jitsi/jitsi-meet/pull/8728#issuecomment-790589534)

fix(lang): update french translation

---

debian/control

fix(debian) support installing the prosody-0.12 upstream package

---

react/features/base/app/components/BaseApp.js

NOTE: It can get slow due to how large our state is.

fix(redux) fix not working with Redux Devtools

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example

feat: Adds a hint for cors headers in default prosody config.

---

react/features/lobby/functions.js
react/features/participants-pane/components/breakout-rooms/components/native/styles.js
react/features/participants-pane/components/native/MeetingParticipantList.js

1. Fix moderator joining a breakout room and leaving main room without any participants.
2. Fix moderator joining a breakout room while lobby participants are waiting to be admitted.

feat(participants/native) - fix joining breakout room

---

react/features/video-layout/middleware.any.js

fix(video-layout) fix incorrect import of isStageFilmstripEnabled

---

modules/UI/UI.js
react/features/conference/components/web/Conference.js

In order to get the desired opacity, body and the 2 div's need to have the configured alpha set.
Also enabled opacity config for mobile browsers

fix(background-alpha) Fix setting background opacity

---

resources/prosody-plugins/mod_external_services.lua
resources/prosody-plugins/mod_jiconop.lua

changeset ede9682c2022
https://hg.prosody.im/prosody-modules/file/ede9682c2022/mod_external_services/mod_external_services.lua

feat: Updates external-services.lua to latest.

---

lang/main-fa.json

Hi again, I sign your CLA.
Sorry for yesterday I forgot to change my branch and then commit some other irrelevant code

Add missing key to Persian lang file

---

ios/sdk/sdk.xcodeproj/project.pbxproj

https://github.com/jitsi/jitsi-meet/issues/11188

fix(ios): Cycle in dependancies

---

react/features/base/color-scheme/defaultScheme.js
react/features/base/participants/components/ParticipantView.native.js
react/features/filmstrip/components/native/PinnedIndicator.js
react/features/filmstrip/components/native/Thumbnail.js
react/features/filmstrip/components/native/TileView.js
react/features/filmstrip/components/native/styles.js

Remove tint for participant in large view
Change pinned indicator from border to icon
On stage view move screen sharing indicator from top to bottom
On stage view show pinned indicator instead of moderator indicator

feat(rn, thumbnail) Updated indicators on native

---

lang/main.json
react/features/base/conference/middleware.any.js
react/features/conference/middleware.js
react/features/salesforce/actions.js
react/features/salesforce/functions.js
react/features/salesforce/index.js
react/features/toolbox/components/native/LinkToSalesforceButton.js
react/features/toolbox/components/web/LinkToSalesforceButton.js
react/features/toolbox/components/web/Toolbox.js

Removed the salesforce integration from the breakout rooms + added some fine tuning around the feature.

fix(salesforce) use salesforce only in the main room

---

android/sdk/src/main/java/org/jitsi/meet/sdk/BaseReactView.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetFragment.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
android/sdk/src/main/res/layout/activity_jitsi_meet.xml

Switch to JitsiMeetView

---

conference.js
package-lock.json
package.json
react/features/base/conference/actionTypes.js
react/features/base/conference/actions.js
react/features/base/participants/actionTypes.js
react/features/base/participants/actions.js
react/features/connection-indicator/statsEmitter.js
react/features/rtcstats/RTCStats.js
react/features/rtcstats/middleware.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/1973.

Pushes e2e pings to rtcstats

---

config.js

feat(multi-stream) Update config.js.

---

react/features/recording/components/Recording/AbstractHighlightButton.js

fix(highlight) allow highlighting moments if recording is running

---

react/features/participants-pane/components/breakout-rooms/components/native/CollapsibleRoom.js
react/features/participants-pane/components/native/MeetingParticipantList.js
react/features/participants-pane/components/native/ParticipantsPane.js

feat(participants-pane/native) adjusted styles for participants container

---

react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/components/web/PinnedIndicator.js

Fix pinned indicator to be displayed only for pinned participants

fix(filmstrip) Fix resizing on chat toggle

---

ios/Podfile.lock
ios/sdk/sdk.xcodeproj/project.pbxproj
package-lock.json
package.json

chore(deps) update react-native-webrtc to 1.100.0

---

react/features/base/config/configWhitelist.js

feat(multi-stream) Whitelist config flags for multi-stream.

---

package-lock.json
package.json

update ljm 1649110698

---

lang/main.json
package-lock.json
package.json
react/features/base/conference/middleware.any.js
react/features/conference/middleware.js
react/features/salesforce/actions.js
react/features/salesforce/functions.js
react/features/salesforce/index.js
react/features/toolbox/components/native/LinkToSalesforceButton.js
react/features/toolbox/components/web/LinkToSalesforceButton.js
react/features/toolbox/components/web/Toolbox.js

Reverts jitsi/jitsi-meet#11286

Revert "fix(salesforce) use salesforce only in the main room"

---

package-lock.json

chore(deps) npm audit fix

---

css/_atlaskit_overrides.scss
react/features/base/components/context-menu/ContextMenu.js
react/features/base/components/context-menu/ContextMenuItem.js
react/features/base/toolbox/components/AbstractButton.js
react/features/base/toolbox/components/ToolboxItem.web.js
react/features/toolbox/components/web/OverflowMenuButton.js
react/features/toolbox/components/web/Toolbox.js

refactor overflow menu to use ContextMenu component
refactor toolboxItem to use ContextMenuItem when needed

ref(overflow-menu) Use ContextMenu component

---

package-lock.json
package.json

chore(deps) update lib-jitsi-meet

---

react/features/base/participants/functions.js
react/features/filmstrip/components/web/ThumbnailWrapper.js
react/features/filmstrip/middleware.web.js

fixes bug in stage filmstrip view when sourceNameSignaling is enabled

fix(multi-stream) support screenshare tile in stage filmstrip

---

lang/main-pt.json

Fix Portuguese translation

---

react/features/filmstrip/middleware.web.js

Was breaking DisableSelfViewTest.

fix: Adds undefined check to avoid error.

---

lang/main.json
react/features/filmstrip/actionTypes.js
react/features/filmstrip/actions.web.js
react/features/filmstrip/constants.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/reducer.js
react/features/follow-me/middleware.js
react/features/follow-me/subscriber.js
react/features/settings/actions.js
react/features/settings/components/web/MoreTab.js
react/features/settings/components/web/SettingsDialog.js
react/features/settings/functions.js

The user can set the max number of participants that can be displayed on stage
Send the number on follow me to all participants

feat(stage-filmstrip) Added user configurable max

---

ios/Podfile.lock

chore(ios) sync Podfile.lock

---

react/features/speaker-stats/components/AbstractSpeakerStatsList.js

Give face expressions in dependency array for useEffect with the reaload interval and for getSpeakerStats callback.

fix(speaker-stats): get realtime local face expressions

---

react/features/chat/components/web/ChatInput.js

Second Fix for https://github.com/jitsi/brave-tracker/issues/78

feat(chat/web) fixed 2 byte char duplication

---

modules/API/API.js
modules/API/external/external_api.js
react/features/face-landmarks/actions.js

Documentation updated here
https://github.com/jitsi/handbook/pull/301

feat(face-landmarks) add API event for providing face landmark data

---

react/features/video-quality/subscriber.js

fix(multi-stream) use highest video quality for screenshare

---

ios/Podfile.lock
package-lock.json
package.json

Upstream made a release in npm, we no longer need to link to a commit.

chore(rn,deps) react-native-default-preference@1.4.4

---

react/features/base/avatar/functions.js

This reverts commit 6085220bfcadecd4def6a22a7a7ede6eeeaf245a.
Breaks initials in avatars.

Revert "fix(avatar): add ZWNJ between initials of letter avatars"

---

react/features/base/components/context-menu/ContextMenuItem.js
react/features/notifications/components/web/Notification.js
react/features/participants-pane/components/web/LobbyParticipantItems.js

Needed to revive the lobby tests.

fix: Adds testId for context menu items and ids to some components.

---

react/features/app/actions.native.js

fix(rn,config) fix loading config due to broken import

---

react/features/security/components/security-dialog/AbstractSecurityDialogButton.js

fix(security) hide button if the enabled flag is set to false

---

conference.js
react/features/base/participants/actionTypes.ts
react/features/base/participants/actions.js
react/features/base/participants/functions.js
react/features/base/participants/reducer.js
react/features/base/tracks/middleware.js
react/features/display-name/components/web/StageParticipantNameLabel.js
react/features/filmstrip/subscriber.any.js

Update local and remote screenshare display names when a user changes their name

fix(multi-stream) update screenshare display name

---

modules/API/API.js
modules/API/external/external_api.js
react/features/always-on-top/AudioMuteButton.js
react/features/toolbox/components/AudioMuteButton.js
react/features/toolbox/functions.any.js

fix(start-silent) Disable AOT mic and unmute notif when start silent

---

react/features/filmstrip/functions.web.js

fix(stageFilmstrip) Disable stage filmstrip by default.

---

react/features/filmstrip/actions.web.js
react/features/filmstrip/functions.web.js
react/features/video-layout/functions.js

Dynamic-max-columns

---

lang/main.json
react/features/base/participants/functions.js

Follow up to https://github.com/jitsi/jitsi-meet/pull/11376 to add screenshare display name to i18n

fix(multi-stream) add screenshare display name to i18n

---

react/features/toolbox/components/web/Toolbox.js

fix(hangup-button) Add to notify toolbar button clicked

---

debian/control
debian/jitsi-meet-tokens.postinst

Debian prosody improvements

---

react/features/video-layout/functions.any.js
react/features/video-layout/functions.native.js
react/features/video-layout/functions.web.js

fix video-layout functions imports 

---

modules/API/API.js
modules/API/external/external_api.js
react/features/subtitles/actionTypes.ts
react/features/subtitles/actions.js
react/features/subtitles/middleware.js
react/features/subtitles/reducer.js

Adds a toggle subtitle command in the external API.

feat(external-api): add toggle subtitles command

---

react/features/base/modal/components/JitsiScreen.js
react/features/conference/components/native/Conference.js
react/features/lobby/components/native/LobbyChatScreen.js
react/features/lobby/components/native/LobbyScreen.js
react/features/lobby/components/native/index.js
react/features/lobby/components/native/styles.js
react/features/mobile/navigation/components/RootNavigationContainer.js
react/features/mobile/navigation/components/conference/components/ConferenceNavigationContainer.js
react/features/mobile/navigation/components/lobby/LobbyNavigationContainerRef.js
react/features/mobile/navigation/components/lobby/components/LobbyNavigationContainer.js
react/features/mobile/navigation/functions.js
react/features/mobile/navigation/middleware.js
react/features/mobile/navigation/routes.js
react/features/mobile/navigation/screenOptions.js

1. Created LobbyNavigationContainer.
2. Added LobbyScreen and LobbyChatScreen to LobbyNavigationContainer.
3. Added LobbyNavigationContainer to the ConferenceNavigationContainer.
4. Ask to join button is transparent and disabled if the knocking participant doesn't enter a display name.
5. When knocking participants have their access rejected, they navigate back to the welcome page.

feat(lobby/native) - New lobby screen

---

modules/API/API.js
modules/API/external/external_api.js
react/features/always-on-top/AudioMuteButton.js
react/features/toolbox/functions.any.js

fix(always-on-top) Fix audio mute button disabled status

---

config.js

- Update lib-jitsi-meet.
- Add testing.setScreenSharingResolutionConstraints to config.js.

Add testing.setScreenSharingResolutionConstraints to config.js, bump ljm

---

react/features/filmstrip/subscriber.web.js

fix(tile-view):Recalculate on window height change

---

config.js

fix(config) add a link to config options docs

---

debian/control

fix: Fixes breaks apache2.

---

react/features/stream-effects/virtual-background/index.js

If downloading the model tiemouts, it may succeed in the (near) future,
don't just give up.

fix(virtual-background) don't treat timeout as fatal failure

---

react/features/base/dialog/actions.js
react/features/base/dialog/components/AbstractDialogContainer.js
react/features/base/dialog/components/web/DialogContainer.js
react/features/base/dialog/reducer.js

fix(dialog) remove obsolete prop no longer used in web

---

react/features/speaker-stats/components/AbstractSpeakerStatsList.js

fix(rn,speakerstats) fix not rendering stats

---

react/features/lobby/components/native/LobbyScreen.js
react/features/lobby/components/native/styles.js
react/features/mobile/navigation/components/lobby/components/LobbyNavigationContainer.js
react/features/mobile/navigation/screenOptions.js

Alternative / complement to https://github.com/jitsi/jitsi-meet/pull/11472

RN lobby screen header

---

package-lock.json
package.json
react/features/toolbox/components/native/OverflowMenu.js
react/features/toolbox/components/native/ScreenSharingButton.tsx

fix(rn,screen-sharing) don't disable button when in audio-only mode

---

ios/scripts/release-sdk.sh

Also, stop bundling WebRTC, it's now a dependency in CocoaPods.

fix(ios) build SDK releases with bitcode

---

react/features/e2ee/middleware.js
react/features/participants-pane/components/web/MeetingParticipants.js

fix(participant-pane) Do not show virtual SS as a separate participant.

---

resources/load-test/load-test-participant.js

Refactor load-test so multiple load-test clients can be run from the same browser tab.

Make it possible to start multiple load-test clients from the same tab.

---

react/features/filmstrip/functions.web.js
react/features/filmstrip/reducer.js
react/features/settings/components/web/MoreTab.js
react/features/settings/functions.js

Change default to 1
Hide max selector if feature is disabled

fix: Stage filmstrip

---

ios/scripts/release-sdk.sh

fix(ios) download WebRTC with bitcode when making an SDK release

---

react/features/reactions/components/native/RaiseHandButton.js

fix(rn,reactions) don't show raise hand button in menu if disabled

---

react/features/notifications/components/AbstractNotification.js
react/features/notifications/components/native/Notification.js

fix(notifications) remove unused isDismissAllowed prop

---

react/features/filmstrip/middleware.web.js

fix(stage-tile-view): crash when pinning

---

lang/main.json

Update main.json Syntax Correction

---

config.js
react/features/base/config/configWhitelist.js
react/features/base/participants/functions.js

Should I whitelist the version I'm deprecating or rather remove it altogether from the config?

feat(config) add gravatar config object

---

conference.js

fix(audio-share): mix newly created audio track with screen audio

---

react/features/filmstrip/subscriber.web.js

fix(stage-filmstrip): resize.

---

react/features/video-menu/components/native/ConnectionStatusComponent.js

fix(video-menu/native) wrong import path

---

react/features/mobile/navigation/screenOptions.js

feat(mobile/navigation) changed navigation container background color

---

ios/Podfile.lock
package-lock.json
package.json

chore(deps) react-native-webrtc@1.100.1

---

react/features/chat/components/native/Chat.js
react/features/chat/components/native/PrivateMessageButton.js

fix(chat/native) we need to dispatch close and open chat to control private messages

---

css/filmstrip/_tile_view.scss

The scrollbar size was changing while scrolling.

fix(tile-view): scrollbar size.

---

react/features/conference/components/web/Conference.js

fix(filmstrip) DO not render filmstrip on prejoin/lobby

---

react/features/rtcstats/RTCStats.js
react/features/rtcstats/middleware.js

With this PR meet will send the video type (screensharing or camera) of remote video tracks.

send video type to rtcstats

---

react/features/notifications/components/native/Notification.js

fix(native-notifications) Show notifications on max 2 lines

---

package-lock.json
package.json

https://github.com/jitsi/lib-jitsi-meet/compare/v1435.0.0+66080c68...v1436.0.0+d5c46952

update ljm 1652891037

---

react/features/face-landmarks/FaceLandmarksHelper.ts
react/features/face-landmarks/faceLandmarksWorker.ts

Using facade pattern for human logic, and add FaceLandmarkHelper interface in case human will be changed in the future.

ref(face-landmarks): move human logic into separate class

---

config.js
react/features/av-moderation/functions.js
react/features/base/config/configWhitelist.js
react/features/participants-pane/components/native/ContextMenuMore.js
react/features/participants-pane/components/native/ParticipantsPane.js
react/features/participants-pane/components/web/FooterContextMenu.js
react/features/participants-pane/components/web/ParticipantsPane.js
react/features/participants-pane/functions.js
react/features/settings/functions.js
react/features/video-menu/components/web/ParticipantContextMenu.js

Breakout Rooms + AV Moderation 🤯

---

ios/sdk/src/picture-in-picture/DragGestureController.swift
ios/sdk/src/picture-in-picture/PiPViewCoordinator.swift

clip to bounds to avoid ui glitch when entering or exiting pip mode
remove old comment
address code review comments

fix ios pip resizing and positioning

---

react/features/av-moderation/middleware.js

Only dispatch raise hand if hand was not already raised

fix(raise-hand) Fix multiple raise hand from notification

---

config.js
css/premeeting/_prejoin.scss
react/features/base/config/configWhitelist.js
react/features/prejoin/components/Prejoin.js
react/features/prejoin/functions.js

feat(prejoin) allow hiding prejoin display name edit field

---

react/features/base/react/components/native/Button.js
react/features/base/react/components/native/index.js

Mea culpa, I messed up when I deleted some unused native components.

fix(recording/native) Button import missing

---

ios/sdk/src/AudioMode.m

Fixes: https://github.com/jitsi/jitsi-meet/issues/11563

fix(ios) fix not using the loudspeaker by default

---

react/features/base/premeeting/components/web/InputField.js

Fix auto focus on menu open
Fix unable to use space in input

fix(giphy-integration) Fix input issues

---

package.json

Ref: https://github.com/jitsi/jitsi-meet/issues/11611

feat(build) make sure we error out if patch-package fails

---

android/gradle.properties
ios/app/broadcast-extension/Info.plist
ios/app/src/Info.plist
ios/app/watchos/app/Info.plist
ios/app/watchos/extension/Info.plist
ios/sdk/src/Info.plist

chore(rn,versions) bump sdk and app versions

---

package-lock.json
package.json

Bump rtcstats to a newer version which includes some dependencies cleanup.

chore(deps): bump rtcstats  9.0.1. to 9.2.0

---

css/premeeting/_prejoin.scss
react/features/prejoin/components/Prejoin.js

fix(prejoin) fix styling of avatar

---

config.js
react/features/face-landmarks/FaceLandmarksHelper.ts
react/features/face-landmarks/actions.js

Added max faces detected config. Default is set to 4.

add(face-landmarks): max faces detected config and default value

---

react/features/base/config/configWhitelist.js
react/features/toolbox/components/DownloadButton.js
react/features/toolbox/components/HelpButton.js

feat(deployment-urls): Whitelist deploymentUrls; remove JaaS restriction

---

resources/prosody-plugins/mod_speakerstats_component.lua

Fix: Speaker stats are not delivered for the breakout rooms

---

css/premeeting/_prejoin.scss

fix(prejoin) fix avatar centering

---

react/features/face-landmarks/FaceLandmarksHelper.ts
react/features/face-landmarks/constants.ts

Filter face detections based on score. 
Add a threshold score as a constant.

fix(face-landmarks): filter face detections based on detection score

---

react/features/recording/components/Recording/LocalRecordingManager.web.ts

fix(local-recordings) fix for browsers not supporting MediaRecorder

---

react/features/mobile/navigation/screenOptions.js

feat(mobile/navigation): added screen orientation based on Platform

---

react/features/mobile/audio-mode/components/AudioRoutePickerDialog.js
react/features/recent-list/components/RecentListItemMenu.native.js
react/features/video-menu/components/native/ConnectionStatusComponent.js
react/features/video-menu/components/native/LocalVideoMenu.js
react/features/video-menu/components/native/RemoteVideoMenu.js
react/features/video-menu/components/native/SharedVideoMenu.js

I somehow missed all other usages of the ColorSchemeRegistry.

fix(rn,bottom-sheet) fix styling after refactor

---

react/features/dynamic-branding/middleware.native.js

Rn dynamic branding more

---

react/features/filmstrip/actions.web.js
react/features/recording/components/Recording/LocalRecordingManager.web.ts

Fix error when pressing a number bigger than the number of participants
Fix local recording issue

fix(keyboard-shortcut) Fix error on number keypress

---

react/features/rtcstats/RTCStats.js
react/features/rtcstats/middleware.js

feat(RTC): report conference start timestamp through rtcstats

---

config.js
lang/main.json
react/features/chrome-extension-banner/components/ChromeExtensionBanner.web.js

feat(extension-banner) Show edge extension when edge browser detected

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java
react/features/mobile/external-api/middleware.js

Start with audio muted not reflected in ongoing notification

---

react/features/base/modal/components/JitsiKeyboardAvoidingView.js
react/features/base/modal/components/JitsiScreen.js
react/features/chat/components/native/Chat.js
react/features/chat/components/native/styles.js
react/features/conference/components/native/carmode/Conference.tsx
react/features/invite/components/add-people-dialog/native/AddPeopleDialog.js
react/features/polls/components/native/PollCreate.js
react/features/polls/components/native/styles.js

feat(mobile/navigation): updated screens that have footer

---

config.js
react/features/face-landmarks/FaceLandmarksHelper.ts
react/features/face-landmarks/actions.js
react/features/face-landmarks/faceLandmarksWorker.ts

Face centering and expression work only if one face is detected.
Remove previously added config flag for max faces detected.

fix(face-landmarks): work only when one face is detected

---

package-lock.json
package.json
react/features/mobile/navigation/components/RootNavigationContainer.js
react/features/mobile/navigation/components/SDKNavigationContainer.tsx
react/features/mobile/navigation/components/welcome/components/WelcomePageNavigationContainer.js
react/features/mobile/navigation/rootNavigationContainerRef.js
react/features/mobile/navigation/routes.js

feat(mobile/navigation): Sdk native navigation error

---

react/features/conference/components/native/carmode/TitleBar.tsx
react/features/conference/components/native/carmode/styles.js
react/features/connection-indicator/components/AbstractConnectionIndicator.js
react/features/connection-indicator/components/native/ConnectionIndicator.js
react/features/mobile/navigation/screenOptions.js

fix(carmode) Force portrait mode, add connection indicator

---

react/features/filmstrip/components/web/PinnedIndicator.js
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.js
react/features/video-menu/components/web/ParticipantContextMenu.js

Hide Pin to Stage button while screensharing
Fix pin indicator while screensharing

fix(pinning) Fix pinning

---

connection.js
modules/UI/authentication/AuthHandler.js
react/features/authentication/middleware.native.js
react/features/authentication/middleware.web.js

Fixes login dialog under FF

---

react/features/conference/components/native/Conference.js
react/features/dynamic-branding/components/native/BrandingImageBackground.tsx
react/features/lobby/components/native/LobbyScreen.js
react/features/prejoin/components/Prejoin.native.tsx
react/features/prejoin/components/styles.js

feat(dynamic-brandind): added background image url to prejoin and lobby

---

react/features/invite/functions.js

feat(invite) Consider SHARING_FEATURES on the email invites

---

config.js
package-lock.json
package.json
react/features/analytics/functions.js
react/features/base/conference/actionTypes.ts
react/features/base/conference/actions.js
react/features/base/conference/functions.js
react/features/base/conference/reducer.js
react/features/rtcstats/middleware.js

PR adds option to send the obfuscated room name to our analytics handlers.

feat(analytics): obfuscate room name

---

android/sdk/src/main/java/org/jitsi/meet/sdk/PictureInPictureModule.java
react/features/base/conference/middleware.native.js
react/features/conference/components/native/Conference.js
react/features/conference/components/native/carmode/Conference.tsx
react/features/dropbox/functions.native.js
react/features/mobile/picture-in-picture/functions.js
react/features/prejoin/components/Prejoin.native.tsx

Disable pip on prejoin screen

---

react/features/base/modal/components/JitsiKeyboardAvoidingView.js
react/features/base/modal/components/JitsiScreen.js
react/features/conference/components/native/Conference.js
react/features/lobby/components/native/LobbyScreen.js
react/features/lobby/components/native/styles.js
react/features/mobile/navigation/functions.js
react/features/prejoin/components/Prejoin.native.tsx
react/features/prejoin/components/styles.js
react/features/prejoin/functions.js

Keyboard dismissed when tapping outside.
Input, video distance adjustments.
Start knocking if display name is set.
Inputs placeholder text color.

feat(lobby/prejoin): updates

---

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastAction.java
android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java
android/sdk/src/main/java/org/jitsi/meet/sdk/ExternalAPIModule.java
ios/sdk/src/ExternalAPI.h
ios/sdk/src/ExternalAPI.m
ios/sdk/src/JitsiMeetView.h
ios/sdk/src/JitsiMeetView.m
react/features/mobile/external-api/middleware.js

feat(mobile, external_api) exposes setClosedCaptionsEnabled

---

react/features/authentication/actions.any.js

It's not necessary to perform a full join, sending a conference IQ is
enough.

fix(auth) simplify auth-and-upgrade procedure

---

react/features/conference/components/native/Conference.js

fix(rn, pip) enables PiP on conference mounted

---

interface_config.js
react/features/settings/components/web/SettingsDialog.js

Added abilty to hide more tab under settings
For feature request https://github.com/jitsi/jitsi-meet/issues/11678

feat(more-settings)

---

react/features/prejoin/functions.js

feat(prejoin/web): updated shouldAutoKnock helper

---

webpack.config.js

fix(build,dev) fix source map generation in development mode

---

package-lock.json
package.json
react/features/chat/components/web/MessageContainer.js

Added a fix for when there are more messages in the chat than a screen could display on safari.

fix(chat-scroll) Fix scrolling chat in safari

---

react/features/polls/components/native/PollCreate.js
react/features/polls/components/web/PollCreate.js
react/features/polls/constants.js

Don't allow questions/answers larger than 500 chars and more than 255 answers.

fix(polls) Update limits

---

react/features/filmstrip/functions.native.js

Increase number of max columns to 4

fix(tile-view, rn) Fix tile view in landscape

---

react/features/base/ui/Tokens.js
react/features/chat/components/native/ChatAndPolls.js
react/features/chat/components/native/styles.js
react/features/mobile/navigation/screenOptions.js
react/features/polls/components/native/PollAnswer.js
react/features/polls/components/native/PollCreate.js
react/features/polls/components/native/PollResults.js
react/features/polls/components/native/PollsList.js
react/features/polls/components/native/PollsPane.js
react/features/polls/components/native/styles.js

feat(polls/native): New polls screen

---

react/features/gifs/components/native/GifsMenu.js
react/features/gifs/components/native/styles.js

feat(gifs/native): fixed gify search input

---

lang/main.json
react/features/recording/components/Recording/AbstractStartRecordingDialog.js
react/features/recording/components/Recording/StartRecordingDialogContent.js
react/features/recording/components/Recording/web/StartRecordingDialog.js
react/features/recording/functions.js
react/features/recording/middleware.js

Show Start rec button if local rec is enabled but fileRecordings is disabled
Add warning for users to stop the recording

fix(local-recording) Improvements

---

react/features/dynamic-branding/actions.any.js
react/features/dynamic-branding/actions.native.js
react/features/dynamic-branding/functions.any.js

feat(dynamic-branding): get branding data from state

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java

Those using the view API may want to integrate iit in their own
Activity.

fix(android) make ongoing service public

---

react/features/dynamic-branding/functions.any.js

On mobile we don't want to look in window.location.

fix(rn,dynamic-branding) fix extracting fqdn from URL

---

react/features/etherpad/components/native/SharedDocument.js
react/features/mobile/navigation/screenOptions.js

feat(etherpad/native): fixed header left close button

---

react/features/base/config/reducer.ts

Looks like a transform error of some sort, it chokes on the ??=
shorthand syntax.

fix(rn) fix mobile build

---

ios/sdk/src/ExternalAPI.m

fix(ios) removes scope from sendEvent parameter in ExternalAPI

---

react/features/conference/components/native/Conference.js

feat(conference/native): disabled PiP on WelcomePage

---

react/features/etherpad/components/native/SharedDocument.js
react/features/etherpad/components/native/styles.js

https://user-images.githubusercontent.com/26413496/177324986-4562bb49-901c-466c-b2f5-c074bc75dd21.mp4

feat(etherpad): ui fixes

---

package-lock.json
package.json
react/features/base/modal/components/JitsiKeyboardAvoidingView.js
react/features/base/modal/components/JitsiScreen.js
react/features/conference/components/native/styles.js
react/features/mobile/navigation/components/HeaderNavigationButton.js
react/features/mobile/navigation/components/RootNavigationContainer.js
react/features/mobile/navigation/components/conference/components/ConferenceNavigationContainer.tsx
react/features/mobile/navigation/components/lobby/components/LobbyNavigationContainer.js
react/features/mobile/navigation/screenOptions.js
react/features/polls/components/native/PollCreate.js
react/features/polls/components/native/styles.js

feat(mobile/navigation): replaced native with stack navig and ui fixes

---

react/features/conference/components/native/carmode/CarMode.tsx
react/features/conference/components/native/carmode/CarModeFooter.tsx
react/features/mobile/navigation/components/conference/components/ConferenceNavigationContainer.tsx

1. Renamed Conference.tsx -> CarMode.tsx
2. Created CarModeFooter component.

feat(conference/native): created CarModeFooter

---

react/features/gifs/components/native/GifsMenu.js
react/features/gifs/components/native/GifsMenuFooter.tsx
react/features/gifs/components/native/styles.js

feat(gifs/native): created GifsMenuFooter

---

package-lock.json
package.json
react/features/app/components/App.native.js
react/features/base/modal/components/JitsiKeyboardAvoidingView.js
react/features/base/modal/components/JitsiScreen.js
react/features/conference/components/native/styles.js
react/features/mobile/navigation/components/HeaderNavigationButton.js
react/features/mobile/navigation/components/RootNavigationContainer.js
react/features/mobile/navigation/components/conference/components/ConferenceNavigationContainer.tsx
react/features/mobile/navigation/components/lobby/components/LobbyNavigationContainer.js
react/features/mobile/navigation/screenOptions.js
react/features/polls/components/native/PollCreate.js
react/features/polls/components/native/styles.js

1. Switched from natieStackNavigator -> stackNavigator.
2. Removed dependency.
3. Added TransitionPresets.
4. Removed nativeStackNavigator specific options.
5. Updated HeaderNavigationButton styles.
6. Fixed JitsiKeyboardAvoidinView.
7. Removed iOS specifc FullWindowOverlay.

feat(mobile/navigation): revert to stack navigator

---

react/features/conference/components/native/carmode/CarModeFooter.tsx
react/features/gifs/components/native/GifsMenuFooter.tsx
react/features/participants-pane/components/native/ParticipantsPane.js
react/features/participants-pane/components/native/ParticipantsPaneFooter.tsx

1. Updated description comments for every footer component.
2. Created ParticipantsPaneFooter.

feat(conf/gifs/participants): created ParticipantsPaneFooter and updated comments

---

react/features/base/react/components/native/styles.js
react/features/conference/components/native/styles.js

feat(base): fixed height for buttons

---

react/features/security/components/security-dialog/native/SecurityDialog.js
react/features/security/components/security-dialog/native/styles.js

feat(security/native): replaced security dialog buttons with new button

---

debian/jitsi-meet-tokens.postinst
doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example

fix: Fixes tokens debian package configuration. Fixes #11702.

---

lang/main-ru.json

Change Russian wording for "Moderator"

fix(lang) update Russian translation

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
doc/debian/jitsi-meet/jitsi-meet.example
resources/prosody-plugins/mod_muc_password_check.lua
resources/prosody-plugins/token/util.lib.lua
resources/prosody-plugins/util.lib.lua

Used from dialplan from jigasi for handling passwords in IVR.

feat: Adds room info http endpoint jwt protected.

---

react/features/settings/components/web/SettingsDialog.js

fix(more-tab) fix crash when quickly selecting settings more tab

---

patches/react-native-screens+3.13.1.patch

react-native-screens patch

---

react/features/base/ui/Tokens.ts
react/features/base/ui/types.ts
react/features/display-name/components/web/DisplayNameBadge.tsx
react/features/participants-pane/components/breakout-rooms/components/web/RoomParticipantContextMenu.tsx
react/features/reactions/components/web/ReactionsMenu.tsx

Update typography Tokens
Use the new Theme interface

feat(theme) Add TS interface for Theme

---

react/features/base/modal/components/JitsiKeyboardAvoidingView.js
react/features/base/modal/components/JitsiScreen.js
react/features/chat/components/native/Chat.js

feat(base-chat): conditioned should set responder on chat screen

---

react/features/base/participants/functions.js
react/features/filmstrip/functions.any.js

fix(filmstrip) Make dominant speaker visible at all times

---

config.js

It has been supported in JS since ES5 and it helps users not make syntax
errors by uncommenting lines which are not comma terminated.

feat(config) allow dangling comma

---

android/sdk/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
react/features/base/config/functions.native.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/11759

fix(android) exclude the Giphy SDK from the libre build

---

react/features/lobby/components/native/LobbyScreen.js
react/features/lobby/components/native/styles.js
react/features/prejoin/components/styles.js

PREJOIN 
LOBBY before
LOBBY after

feat(prejoin-lobby): ui fixes

---

react/features/filmstrip/actionTypes.ts
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/web/ScreenshareFilmstrip.js
react/features/filmstrip/components/web/ThumbnailWrapper.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/reducer.js
react/features/filmstrip/subscriber.web.js

On click on a screenshare pin that to stage (allows users to choose between multiple screenshares)

fix(screenshare-filmstrip) Fix pin screenshare

---

config.js

Add 'noisesuppression' to 'toolbarButtons'

---

react/features/base/config/configWhitelist.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/11760#issuecomment-1201049861

fix(config) add recordingService to the whitelist

---

react/features/base/conference/middleware.web.js
react/features/base/participants/functions.js
react/features/participants-pane/components/web/MeetingParticipants.js
react/features/screenshot-capture/actions.js
react/features/screenshot-capture/index.js

fix(screenshot-capture): Impl screenshot capture in multi-stream mode.

---

react/features/base/media/components/native/VideoTransform.js
react/features/base/media/components/native/styles.js

feat(base/media): removed max offset value for wide view screen sharing

---

ios/app/app.entitlements

fix(ios) add missing entitlement

---

react/features/prejoin/components/Prejoin.web.js

fix(lobby) fix not being able to type password

---

react/features/base/ui/components/_.native.ts
react/features/base/ui/components/_.web.ts
react/features/base/ui/components/index.ts
react/features/base/ui/components/native/index.ts
react/features/base/ui/components/web/index.ts
react/features/base/ui/index.ts
react/features/recording/components/Recording/StartRecordingDialogContent.js
react/features/recording/components/Recording/styles.native.js

feat(recording/native): added new Button component

---

css/_polls.scss
css/modals/screen-share/_share-audio.scss
package-lock.json
package.json
react/features/desktop-picker/components/DesktopPickerPane.js
react/features/polls/components/web/PollAnswer.tsx
react/features/screen-share/components/ShareAudioDialog.tsx

Remove atlaskit/checkbox dependency

ref(ui-components) Replace all Checkboxes with new component

---

config.js
doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example

Breakout rooms and tokens

---

ios/sdk/src/AudioMode.m
ios/sdk/src/callkit/CallKit.m

In preperation for the ReactNative SDK the Loggers in AudioMode and Callkit are now using RCTLog. Tested locally.

ref(ios) Changed Logger to RCTLog

---

react/features/base/conference/middleware.web.js

Fixes https://github.com/jitsi/jitsi-meet/issues/11916.

fix(external-api) Fix toggleShareScreen in multi-stream mode.

---

react/features/noise-suppression/actions.ts
react/features/noise-suppression/functions.ts

fix(noise-suppression): remove no track warning on share audio flow

---

react/features/base/conference/middleware.web.js
react/features/base/tracks/actions.js
react/features/remote-control/actions.js

fix(remote-control): fix remote-control when multi-stream is enabled.

---

react/features/av-moderation/reducer.ts
react/features/base/avatar/constants.ts
react/features/base/avatar/functions.ts
react/features/base/participants/actions.ts
react/features/base/participants/functions.ts
react/features/base/participants/logger.ts
react/features/base/participants/reducer.ts
react/features/conference/components/native/carmode/TitleBar.tsx
react/features/display-name/components/native/DisplayNameLabel.tsx
react/features/lobby/components/web/LobbySection.tsx
react/features/participants-pane/components/breakout-rooms/components/web/RoomParticipantContextMenu.tsx
react/features/prejoin/components/Prejoin.native.tsx
react/features/reactions/components/web/ReactionsMenu.tsx
react/features/reactions/functions.any.ts
react/features/reactions/middleware.ts
react/features/security/components/security-dialog/web/SecurityDialog.tsx
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.tsx
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.tsx

ref: Convert base/participants to TS

---

debian/jitsi-meet-web-config.postinst

feat: Adds a jaas reference when installing.

---

config.js

Add missing 'notify.videoMutedRemotelyTitle'.

fix: Adds missing notification in example config.

---

react/features/recording/components/Recording/StartRecordingDialogContent.js

fix(dropbox) fix signing out when switching rec providers

---

react/features/base/participants/middleware.js

feat: Updates the local stats to match remote for 'connected to'.

---

modules/UI/videolayout/LargeVideoManager.js
react/features/base/conference/middleware.web.js
react/features/base/tracks/reducer.ts

Add debugging for SS streaming issues.

---

react/features/stream-effects/virtual-background/index.js

There is no need to fetch and apply the model every time we want to
createe the effect since it doesn't change.

fix(virtual-backgrounds) cache loaded model

---

react/features/noise-suppression/components/NoiseSuppressionButton.tsx

fix(noise-suppression): ignore ts on noise-suppression button

---

react/features/analytics/functions.js
react/features/base/config/middleware.js
react/features/base/config/reducer.ts
react/features/base/known-domains/reducer.ts
react/features/base/redux/PersistenceRegistry.ts
react/features/recent-list/reducer.js

Remove legacy code

---

react/features/recording/components/Recording/AbstractHighlightButton.js
react/features/recording/components/Recording/web/HighlightButton.js

fix(highlight) check for JaaS features before opening the dialog

---

react/features/base/ui/components/native/buttonStyles.ts
react/features/base/ui/components/native/inputStyles.ts
react/features/participants-pane/components/native/MeetingParticipantList.js
react/features/recording/components/Recording/styles.native.js
react/features/security/components/security-dialog/native/SecurityDialog.js
react/features/security/components/security-dialog/native/styles.js

1. Fixed text color inside new Input component.
2. Fixed Dropbox message alignment.
3. Fixed secondary button disabled label contrast.
4. Fixed Add password text.
5. Replaced TextInput with new Input inside SecurityDialog.

native ui fixes

---

react/features/participants-pane/components/native/MeetingParticipantItem.js

feat(participants-pane/native): fixed undefined error

---

react/features/base/media/components/native/styles.js

feat(media): added extra percentage padding right to screen share view fit

---

react/features/base/jwt/middleware.js

fix: Jwt context.features to work without context.user. Fixes #12005

---

conference.js
react/features/prejoin/actions.js

fix(logging) Add more info logs for device switching.

---

css/premeeting/_premeeting-screens.scss
react/features/base/premeeting/components/web/PreMeetingScreen.js
react/features/prejoin/components/Prejoin.web.js

feat(prejoin) add room name to premeeting screen

---

modules/API/API.js
modules/API/external/external_api.js
react/features/screen-share/middleware.js
react/features/shared-video/middleware.any.js

Added logs and emit iframe event for video and audio sharing

feat (screen-share) Added logs and emit iframe event for video and audio sharing

---

react/features/settings/components/native/styles.js

feat(settings): changed switch enabled track color

---

react/features/lobby/components/native/LobbyScreen.js
react/features/lobby/components/native/styles.js
react/features/prejoin/components/Prejoin.native.tsx
react/features/prejoin/components/styles.js

feat(lobby/prejoin): added room name title

---

conference.js
react/features/base/audio-only/actions.ts
react/features/base/media/actions.js
react/features/base/media/middleware.any.js
react/features/toolbox/components/VideoMuteButton.js

fix(audio-only) Do not enable video automatically when audio-only is disabled

---

debian/control

fix: Adds missing dependency of lua-inspect.

---

conference.js
react/features/base/conference/constants.js
react/features/base/conference/middleware.any.js
react/features/breakout-rooms/actions.js

Send leave reason for:
- user switches rooms (main room -> breakout room, breakout room -> main room)
- user leaves from an uncoverable error

feat(JitsiConference) Send leave reasons on switching room and when errors

---

react/features/participants-pane/constants.tsx

fix(ts) fix build

---

css/_toolbars.scss
css/_variables.scss
doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
lang/main-ar.json
lang/main-ca.json
lang/main-de.json
lang/main-hsb.json
lang/main-it.json
lang/main-pt.json
lang/main.json
react/features/base/conference/actions.js
react/features/base/conference/middleware.any.js
react/features/conference/components/native/carmode/EndMeetingButton.tsx
react/features/toolbox/actionTypes.ts
react/features/toolbox/actions.web.js
react/features/toolbox/components/HangupButton.js
react/features/toolbox/components/native/HangupMenu.tsx
react/features/toolbox/components/native/HangupMenuButton.tsx
react/features/toolbox/components/native/Toolbox.js
react/features/toolbox/components/native/styles.js
react/features/toolbox/components/web/EndConferenceButton.tsx
react/features/toolbox/components/web/HangupMenuButton.tsx
react/features/toolbox/components/web/HangupToggleButton.tsx
react/features/toolbox/components/web/LeaveConferenceButton.tsx
react/features/toolbox/components/web/Toolbox.tsx
react/features/toolbox/reducer.js
resources/prosody-plugins/mod_end_conference.lua
resources/prosody-plugins/mod_muc_breakout_rooms.lua

This PR adds a feature which allows moderators to end the conference for all participants.
It depends on PR https://github.com/jitsi/lib-jitsi-meet/pull/1859.

feat(toolbox): add end conference

---

react/features/settings/components/native/SettingsView.js
react/features/settings/components/native/styles.js

feat(settings/native): updated placeholder and placeholder text color

---

react/features/security/components/security-dialog/native/SecurityDialog.js

feat(security/native): options available only if participant is moderator

---

react/features/polls/components/native/PollsPane.js

https://user-images.githubusercontent.com/26413496/187208070-8baf90e6-08a2-472a-b5dd-342fb05ec357.mp4

feat(polls/native): fixed scroll inside screen

---

conference.js
modules/API/API.js
modules/API/external/external_api.js
react/features/always-on-top/AlwaysOnTop.js
react/features/always-on-top/VideoMuteButton.js
react/features/base/premeeting/components/web/Preview.js
react/features/toolbox/actions.any.js
react/features/toolbox/components/VideoMuteButton.js

feat(aot-prejoin) Add support for showing AOT on prejoin

---

config.js
interface_config.js
react/features/base/config/configType.ts
react/features/base/config/reducer.ts
react/features/base/react/components/web/Watermarks.js

ref(config) move defaultLogoUrl to config object

---

react/features/filmstrip/middleware.web.js
react/features/large-video/actions.any.js

Pinning participant was not working for stage filmstrip and
screen sharing filmstirp layouts

fix(stage-filmstrip): Pinning

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
android/sdk/src/main/java/org/jitsi/meet/sdk/RNConnectionService.java
config.js
ios/app/broadcast-extension/SocketConnection.swift
lang/main-te.json
lang/main.json
react/features/base/jwt/functions.js
react/features/base/util/uri.ts
react/features/face-landmarks/constants.ts
react/features/face-landmarks/functions.js
react/features/filmstrip/components/web/Thumbnail.tsx
react/features/large-video/components/ScreenSharePlaceholder.web.tsx
react/features/participants-pane/components/native/CollapsibleList.js
react/features/stream-effects/noise-suppression/NoiseSuppressorWorklet.ts
react/features/stream-effects/presenter/JitsiStreamPresenterEffect.js
react/features/toolbox/components/AbstractToolbarButton.js
react/features/toolbox/functions.web.js
resources/prosody-plugins/poltergeist.lib.lua
resources/prosody-plugins/token/util.lib.lua
twa/app/build.gradle
webpack.config.js

Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix some typos (found by codespell)

---

ios/Podfile.lock
package-lock.json
package.json
react/features/prejoin/components/Prejoin.native.tsx

Fix for #11831
https://user-images.githubusercontent.com/26413496/187484636-929d5738-2467-4a2f-bc96-3af2dd7168d4.mp4

feat(prejoin/native): update react-native-video dep and unmount LargeVideo if Prejoin isn't focused

---

lang/main.json
react/features/base/i18n/i18next.ts
react/features/base/i18n/index.js
react/features/base/toolbox/components/AbstractButton.js
react/features/base/toolbox/components/AbstractToolboxItem.js
react/features/subtitles/actionTypes.ts
react/features/subtitles/actions.js
react/features/subtitles/components/AbstractClosedCaptionButton.js
react/features/subtitles/components/ClosedCaptionButton.web.js
react/features/subtitles/components/LanguageList.tsx
react/features/subtitles/components/LanguageListItem.tsx
react/features/subtitles/components/LanguageSelectorDialog.web.tsx
react/features/subtitles/middleware.js
react/features/subtitles/reducer.js

feat(translation) enable cc translation

---

resources/prosody-plugins/mod_muc_breakout_rooms.lua

fix(breakout-rooms) fix broadcast timer

---

modules/UI/videolayout/VideoContainer.js
react/features/filmstrip/components/web/ScreenshareFilmstrip.js
react/features/filmstrip/functions.native.js
react/features/filmstrip/functions.web.js
react/features/large-video/actionTypes.ts
react/features/large-video/actions.any.js
react/features/large-video/reducer.ts
react/features/video-layout/functions.any.js
react/features/video-layout/middleware.native.js
react/features/video-quality/actionTypes.ts
react/features/video-quality/actions.js
react/features/video-quality/constants.ts
react/features/video-quality/functions.js
react/features/video-quality/reducer.ts
react/features/video-quality/subscriber.js

ref(receiver-constraints): Refactor and fixes.

---

react/features/lobby/components/web/LobbyScreen.js

fix(lobby) fix opening lobby chat after API change

---

modules/API/API.js
modules/API/external/external_api.js
react/features/base/conference/functions.js
react/features/base/participants/actions.ts
react/features/base/participants/middleware.js
react/features/base/participants/subscriber.js
react/features/breakout-rooms/functions.js
react/features/external-api/middleware.js
react/features/shared-video/middleware.any.js

- fix number of participants in meeting from all rooms (includes breakout rooms as well)
- add `roomsInfo` API, https://github.com/jitsi/handbook/pull/365

fix(external_api): Fix number of participants in meeting

---

modules/UI/videolayout/VideoLayout.js
react/features/large-video/components/LargeVideo.web.js
react/features/large-video/subscriber.web.js

This fixes an issue where screenshare appears on the thumbnail but not on the large-video.

fix(large-video) Update large-video when the streamingStatus of the attached track changes

---

ios/scripts/release-sdk-lite.sh

fix(ios) fix lite SDK release process

---

modules/API/API.js
modules/API/external/external_api.js
react/features/base/conference/functions.js
react/features/base/participants/actions.ts
react/features/base/participants/middleware.js
react/features/base/participants/subscriber.js
react/features/breakout-rooms/functions.js
react/features/external-api/middleware.js
react/features/shared-video/middleware.any.js

- cherry-picked merge commit 5f62acc67c4b11daa444f3a40130369a1f4a4031

fix(external_api): Fix number of participants in meeting (#12052)

---

react/features/base/conference/functions.js
react/features/base/premeeting/components/web/PreMeetingScreen.js

fix(prejoin) Fix roomname showing for 3rd party prejoin app

---

react/features/base/premeeting/components/web/PreMeetingScreen.js

fix(prejoin) Hide conference name based on config

---

modules/API/API.js
modules/API/external/external_api.js
react/features/filmstrip/actionTypes.ts
react/features/filmstrip/actions.web.js
react/features/filmstrip/middleware.web.js

- add logic command resize filmstrip
- needs also this PR https://github.com/jitsi/jitsi-meet-spot/pull/922

feat(Filmstrip) add logic command resize filmstrip

---

react/features/conference/components/native/Conference.js
react/features/subtitles/actions.any.js
react/features/subtitles/actions.native.js
react/features/subtitles/actions.web.js

Looks like Metro is confused by these imports.

fix(rn,conference) fix mobile build

---

react/features/base/config/functions.native.ts

fix(rn) fixes typo in functions.native

---

conference.js
react/features/base/media/middleware.web.ts
react/features/base/media/subscriber.ts
react/features/base/redux/StateListenerRegistry.ts
react/features/toolbox/functions.any.ts
react/features/toolbox/middleware.js
react/features/toolbox/subscriber.ts

fix(external-api) Fix notify audio muted/audio available

---

debian/jitsi-meet-prosody.postinst
debian/jitsi-meet-web-config.postinst

fix: Set default choice for jaas, keeps old behavior.

---

conference.js
react/features/base/conference/actions.js
react/features/base/participants/actionTypes.ts
react/features/base/participants/actions.ts
react/features/base/participants/middleware.js
react/features/external-api/middleware.js
react/features/filmstrip/middleware.web.js
react/features/large-video/middleware.js
react/features/rtcstats/middleware.ts
resources/prosody-plugins/mod_speakerstats_component.lua

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/2107

feat: Handle dominant speaker silence

---

config.js
react/features/base/config/middleware.ts
react/features/base/settings/reducer.ts
react/features/filmstrip/actionTypes.ts
react/features/filmstrip/actions.web.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/reducer.ts
react/features/follow-me/middleware.js
react/features/follow-me/subscriber.js
react/features/settings/actions.js
react/features/settings/functions.js

Add config for stage participants number
Enable stage filmstrip by default

fix(filmstrip) Save stage filmstrip number in settings

---

react/features/base/config/middleware.ts

The whole object might be undefined.

fix(config) fix check for filmstrip property

---

react/features/settings/components/web/MoreTab.tsx

fix(settings) fix not storing maxStageParticipants

---

react/features/base/premeeting/components/web/InputField.js
react/features/gifs/components/web/GifsMenu.tsx

Remove ref focus from InputField component
Replace input component in GifsMenu and add ref focus

fix(prejoin) Fix focus stealing in settings

---

react/features/e2ee/middleware.js

fix(e2ee) check if e2ee is supported before playing the sound

---

react/features/base/testing/functions.js
react/features/filmstrip/components/web/Thumbnail.tsx

fix(testing): Fixes for multi-stream torture tests to work.

---

android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
ios/Podfile
ios/Podfile.lock
ios/app/app.xcodeproj/project.pbxproj
ios/fastlane/Fastfile
ios/scripts/release-sdk-lite.sh
ios/scripts/release-sdk.sh
ios/sdk/sdk.xcodeproj/project.pbxproj
package-lock.json
package.json

These 2 changes need to be made together because Xcode 14 removes bitcode support, so I made the M106 build without bitcode but with embedded dSYMs.
See the individual commits.

WebRTC 106 + Xcode 14

---

react/features/filmstrip/middleware.web.js

Use new settings action to determine when max has been reduced

fix(filmstrip) Fix stage filmstrip

---

config.js
react/features/base/config/functions.any.ts

feat(multi-stream) Enable multi-stream by default (if not disabled explicitly)

---

debian/jitsi-meet-web-config.postinst
resources/register-jaas-account.sh

feat: Adds automatic jaas account creation.

---

debian/jitsi-meet-web-config.postinst

fix: Fixes postinst after pull/12213.

---

debian/jitsi-meet-web-config.postinst
debian/jitsi-meet-web-config.templates
resources/install-letsencrypt-cert.sh
resources/register-jaas-account.sh

fix: Fixes LE script on existing cert.

---

android/sdk/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
android/settings.gradle
ios/Podfile.lock
ios/app/src/AppDelegate.m
ios/sdk/src/JitsiMeet.h
ios/sdk/src/JitsiMeet.m
package-lock.json
package.json
react/features/conference/components/native/carmode/CarMode.tsx

fix(carmode) Force portrait when in carmode

---

android/scripts/logcat.sh

feat(android) add logcat helper script

---

modules/API/API.js

Check recording is enabled before start

fix(external-api) Fix start recording

---

react/features/recording/components/AbstractRecordingLabel.js

fix(carmode) Don`t show rec/live labels after rec/ls finished

---

debian/jitsi-meet-web-config.postinst
debian/jitsi-meet-web-config.templates

feat: Set LE as default choice when installing.

---

react/features/face-landmarks/middleware.ts

fix(face-landmarks) Do not start detection on muted tracks

---

modules/API/API.js
react/features/filmstrip/components/web/PinnedIndicator.tsx

Make pin function work with stage filmstrip

fix(external-api) Fix pin function

---

react/features/base/lib-jitsi-meet/middleware.ts

fix(ts,build) fix TS error in web build

---

package-lock.json
package.json

chore(deps,eslint) update eslint-config-jitsi to 4.1.4

---

config.js

fix(config) Update link to to UI tokens

---

conference.js
react/features/base/media/functions.ts

fix(audio-configs) Fix startWithAudioMuted overrriding startSilent

---

react/features/invite/components/add-people-dialog/web/DialInNumber.js
react/features/invite/components/add-people-dialog/web/InviteByEmailSection.js
react/features/invite/components/add-people-dialog/web/LiveStreamSection.js
react/features/recording/actions.any.js

- fix warning error "export 'copyText' (imported as 'copyText') was not found in..."
- related change PR https://github.com/jitsi/jitsi-meet/pull/12242/files

fix(import): fix copyText import file

---

package-lock.json
package.json

chore(deps) update js-utils

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
resources/prosody-plugins/mod_room_metadata.lua
resources/prosody-plugins/mod_room_metadata_component.lua

feat(room-metadata) add module for generic room metadata storage

---

package-lock.json
package.json
react/features/feedback/components/FeedbackDialog.web.js

Remove @atlaskit/field-text-area dep

ref(feedback) Use new Input component

---

config.js

fix(config) drop debug lefover

---

resources/prosody-plugins/mod_polls.lua

Fix polls 

---

lang/main.json
react/features/mobile/navigation/components/welcome/components/WelcomePageTabs.js

1. Added translations for welcome page bottom tabs.
2. Removed unused translation.

feat(mobile/navigation/welcome): welcome page tabs translations

---

.github/workflows/ci.yml
react/features/base/lib-jitsi-meet/middleware.ts

feat(ci) run GHA also on macOS

---

lang/main.json
react/features/mobile/navigation/components/conference/components/ConferenceNavigationContainer.tsx
react/features/mobile/navigation/components/settings/components/SettingsNavigationContainer.js
react/features/security/components/security-dialog/web/SecurityDialog.tsx

feat(mobile/navigation): updated translations for screen headers

---

react/features/base/i18n/index.js

fix (translation) remove unused i18n import

---

react/features/polls/components/web/PollsList.js

Fixes https://github.com/jitsi/brave-tracker/issues/98

fix(polls) Fix autoscroll for polls causing layout issues

---

.github/workflows/ci.yml

This allows it to run in parallel, and should make the overall run faster.

feat(ci) move linting to its own step

---

react/features/app/middlewares.web.js
react/features/base/dialog/middleware.web.ts
react/features/base/dialog/reducer.ts
react/features/base/ui/components/web/Dialog.tsx
react/features/base/ui/components/web/DialogContainer.tsx
react/features/chat/components/AbstractChatPrivacyDialog.tsx
react/features/chat/components/web/ChatPrivacyDialog.tsx
react/features/display-name/components/web/DisplayNamePrompt.tsx
react/features/embed-meeting/components/EmbedMeetingDialog.tsx
react/features/keyboard-shortcuts/components/web/KeyboardShortcutsDialog.tsx

Improve Dialog component to auto close on cancel or on submit
Change logic to determine whether a dialog is using the new component
Convert some files to TS

ref(ui-components) Update some dialogs to use the new component

---

react/features/polls/actions.ts
react/features/polls/functions.ts
react/features/polls/middleware.ts
react/features/polls/types.ts

ref(polls) Convert files to TS

---

react/features/base/jwt/constants.ts
react/features/base/jwt/functions.ts
react/features/jaas/constants.ts
react/features/recording/components/LiveStream/AbstractLiveStreamButton.js
react/features/recording/components/Recording/AbstractHighlightButton.js
react/features/recording/components/Recording/AbstractRecordButton.js
react/features/recording/components/Recording/web/HighlightButton.tsx
react/features/subtitles/components/AbstractClosedCaptionButton.js
react/features/toolbox/components/web/Toolbox.tsx
react/features/toolbox/functions.any.ts

feat(toolbar-buttons) Hide buttons disabled through JWT

---

ios/sdk/src/callkit/JMCallKitEmitter.m

fix(ios,callkit) make sure the start call action is fulfilled

---

debian/jitsi-meet-prosody.postinst

fix: Workaround failure to install jitsi-meet-prosody Fixes #12300

---

debian/control

feat: Updates prosody dependency to be at least 0.11.7.

---

debian/jitsi-meet-web-config.postinst

fix: Fixes cert choice when pre-set in automations.

---

README.md

fix(doc) update README

---

react/features/prejoin/components/Prejoin.native.tsx

fix(rn) adds debounce on onJoin function

---

react/features/mobile/navigation/components/welcome/components/WelcomePageTabs.js
react/features/settings/components/native/SettingsView.tsx
react/features/welcome/components/WelcomePage.native.js

Android hardware back puts app in background.

feat(mobile/navigation): disabled bottom tab navigator backBehavior

---

debian/jitsi-meet-web-config.postinst

We need that for mobile clients that are not updated.

fix: Switches by default mutli-stream and through config.js.

---

globals.d.ts
react/features/base/conference/reducer.ts
react/features/base/config/configType.ts
react/features/base/jwt/reducer.ts
react/features/base/settings/reducer.ts
react/features/chat/middleware.ts
react/features/chat/reducer.ts
react/features/display-name/actions.ts
react/features/display-name/middleware.ts
react/features/dynamic-branding/functions.any.ts
react/features/e2ee/functions.ts
react/features/e2ee/logger.ts
react/features/e2ee/middleware.ts
react/features/e2ee/sounds.ts
react/features/feedback/actions.ts
react/features/feedback/functions.ts
react/features/feedback/logger.js
react/features/feedback/logger.ts
react/features/jaas/functions.ts
react/features/jaas/logger.ts
react/features/subtitles/actions.any.ts

ref(TS) Convert some files to TS

---

css/modals/feedback/_feedback.scss
css/modals/screen-share/_share-audio.scss
react/features/base/dialog/middleware.web.ts
react/features/base/tracks/actions.ts
react/features/base/ui/components/web/Dialog.tsx
react/features/feedback/components/FeedbackDialog.web.js
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.tsx
react/features/jaas/components/web/PremiumFeatureDialog.tsx
react/features/recording/components/LiveStream/web/StartLiveStreamDialog.js
react/features/recording/components/LiveStream/web/StopLiveStreamDialog.js
react/features/recording/components/Recording/web/StartRecordingDialog.js
react/features/recording/components/Recording/web/StopRecordingDialog.js
react/features/room-lock/components/PasswordRequiredPrompt.web.js
react/features/screen-share/components/ShareAudioDialog.tsx

ref(ui-components) Use new Dialog component

---

react/features/base/ui/components/native/buttonStyles.ts

feat(base/ui/native): centered button label

---

react/features/base/conference/functions.ts

fix(prejoin) show subject in prejoin if available

---

react/features/base/modal/components/JitsiScreen.js
react/features/settings/components/native/SettingsView.tsx

JitsiScreens don't have scroll available, only if their children are FlatLists or other scroll based components.

feat(base/modal): enable scroll for jitsi screen component

---

resources/prosody-plugins/mod_reservations.lua

Skip reservation checks for breakout rooms by default since it's going to be hard for external API endpoints to validate randomly generated breakout room names.
Also added a flag to allow people to fallback to previous behaviour.
Related community post: https://community.jitsi.org/t/breakout-room-issue-with-reservation-system/117952/2

fix(reservations): skip reservations check for breakout rooms

---

react/features/mobile/navigation/screenOptions.js
react/features/prejoin/components/Prejoin.native.tsx
react/features/prejoin/components/styles.js

1. Added screen title.
2. Moved room name inside LargeVideoContainer.

feat(prejoin/native): ui updates

---

css/premeeting/_lobby.scss
react/features/base/ui/constants.ts
react/features/lobby/components/web/LobbyScreen.js
react/features/prejoin/components/dialogs/DialInDialog.tsx
react/features/prejoin/components/dialogs/DialOutDialog.tsx

ref(ui-components) Use new Button on prejoin

---

react/features/app/actions.native.js
react/features/prejoin/components/Prejoin.native.tsx

feat(prejoin/native): clear notifications when joining

---

react/features/large-video/components/LargeVideo.native.js

fix(rn,large-video) don't render video for the local SS

---

ios/sdk/src/callkit/JMCallKitProxy.m

fix(ios) fix mute "ping-pong"

---

react/features/conference/components/native/carmode/CarModeFooter.tsx
react/features/conference/components/native/carmode/styles.js

feat(conference/native): adjusted carmode ui

---

lang/main.json
react/features/chat/components/web/NewMessagesButton.tsx
react/features/chat/functions.ts

1. Fixed unread messages counter.
2. Fixed New messages button styles on web.

feat(chat): fixed chat counter

---

react/features/app/actions.web.js

(fix) redirect to about blank when close meeting opened in iframe

---

ios/sdk/sdk.xcodeproj/project.pbxproj

chore(ios) sync project file

---

debian/jitsi-meet-prosody.templates
debian/jitsi-meet-turnserver.templates
debian/jitsi-meet-web-config.templates
debian/po/templates.pot

feat: Updates deb install texts.

---

config.js
modules/keyboardshortcut/keyboardshortcut.js
react/features/base/config/configType.ts
react/features/base/config/configWhitelist.ts
react/features/base/config/reducer.ts
react/features/conference/components/web/ParticipantsCount.js
react/features/speaker-stats/functions.js
react/features/toolbox/components/native/OverflowMenu.js
react/features/toolbox/components/web/Toolbox.tsx

feat(config) add ability to hide speaker stats for web/mobile 

---

react/features/video-layout/functions.any.js

fix(video-layout) Fix auto-pinning latest screenshare.

---

package-lock.json
package.json

update ljm 1666047993

---

react/features/base/dialog/middleware.web.ts
react/features/base/ui/components/web/Dialog.tsx
react/features/salesforce/components/web/SalesforceLinkDialog.tsx

ref(salesforce) Use new Dialog component

---

react/features/keyboard-shortcuts/components/web/KeyboardShortcutsDialog.tsx

Use makeStyles instead of withStyles
Fix style

ref(keyboard-shortcuts) Change Dialog to function component

---

react/features/display-name/components/web/DisplayName.tsx

Use makeStyles instead of withStyles

ref(display-name) Change to function component

---

react/features/toolbox/components/web/OverflowMenuButton.tsx

Use makeStyles instead of withStyles

ref(overflow-menu-button) Change to function component

---

react/features/toolbox/actions.any.ts
react/features/toolbox/actions.native.ts
react/features/toolbox/actions.web.ts
react/features/toolbox/functions.native.ts
react/features/toolbox/middleware.ts

ref(toolbox) Convert feature to TS

---

react/features/participants-pane/components/web/ParticipantsPane.tsx

Use makeStyles instead of withStyles

ref(participants-pane) Change to function component

---

react/features/chat/components/web/KeyboardAvoider.js

ref(keyboard-avoider) Don't use styled components

---

.github/workflows/ci.yml
package.json

ref: Update npm scripts

---

react/features/filmstrip/functions.any.js
react/features/filmstrip/subscriber.native.js

Couldn't repro this but I've seen it happen a number of times. Took the defensive approach, WDYT?

rn fix double tiles

---

react/features/base/conference/reducer.ts
react/features/screen-share/actions.ts
react/features/screen-share/logger.ts
react/features/screen-share/middleware.ts
react/features/settings/actions.ts
react/features/settings/functions.ts
react/features/settings/logger.ts
react/features/settings/middleware.web.ts

ref(TS) Convert some features to TS

---

resources/update-mobile-sdk-version.sh

fix(ios) also bump the lite SDK version when bumping versions

---

package-lock.json
package.json

fix(deps) update xmldom@0.7.6

---

config.js
react/features/base/config/configType.ts
react/features/filmstrip/components/web/Filmstrip.tsx
react/features/filmstrip/components/web/ThumbnailWrapper.js
react/features/filmstrip/functions.any.js

ref(filmstrip) Remove the option to disable thumbnail re-ordering.

---

react/features/filmstrip/subscriber.native.js

fix(rn,filmstrip) fix dropping tiles on conference join

---

react/features/conference/components/web/ParticipantsCount.js

fix(label) Fix Participants Count label color

---

react/features/base/popover/components/Popover.web.tsx
react/features/base/popover/components/index.js
react/features/base/toolbox/components/web/ToolboxButtonWithIconPopup.js
react/features/connection-indicator/components/web/ConnectionIndicator.tsx
react/features/toolbox/components/web/OverflowMenuButton.tsx
react/features/toolbox/components/web/Toolbox.tsx
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.tsx
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.tsx

Convert Popover to TS
Update OverflowMenu to use Popover instead of InlineDialog

ref(popover) Update Popover to support click trigger

---

css/_variables.scss
css/themes/_light.scss

ref(SCSS) Remove some unused SASS variables

---

react/features/base/ui/components/web/Input.tsx

Use theme background on autofill Firefox

fix(input) Fix background color

---

config.js
react/features/base/config/configType.ts
react/features/filmstrip/components/web/Thumbnail.tsx
react/features/gifs/components/native/GifsMenu.js
react/features/gifs/components/web/GifsMenu.tsx
react/features/gifs/constants.ts
react/features/gifs/function.any.ts

Should the default remain pg-13?

feat(gif) Support rating config + show display name over gif tile

---

react/features/settings/components/web/audio/AudioSettingsPopup.js

ref(audio-popup) Replace InlineDialog with Popover

---

react/features/base/ui/components/native/Input.tsx
react/features/base/ui/components/types.ts
react/features/base/ui/components/web/Dialog.tsx
react/features/base/ui/components/web/Input.tsx
react/features/embed-meeting/components/EmbedMeetingDialog.tsx
react/features/keyboard-shortcuts/components/web/KeyboardShortcutsDialog.tsx

ref(dialog) Update some dialogs' styles

---

react/features/base/ui/components/web/Dialog.tsx

If onSubmit opens a new dialog, we'd be hiding it otherwise.

fix(dialog,web) fix opening dialogs in succession

---

lang/main-hr.json

- update according to the current "main.json" file

Update Croatian translation

---

react/features/base/react/components/native/Switch.js
react/features/base/ui/components/native/IconButton.tsx
react/features/base/ui/components/native/index.ts
react/features/participants-pane/components/native/ParticipantsPaneFooter.tsx
react/features/toolbox/components/native/HangupMenuButton.tsx

1. Removed unused Switch from base/react/components/native.
2. Removed index file from base/ui/components/native.
3. Moved IconButton from base/react/components/native -> base/ui/components/native.

feat(base/ui/native): removed unused files and updated imports

---

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioDeviceHandlerConnectionService.java
android/sdk/src/main/java/org/jitsi/meet/sdk/AudioModeModule.java

These refactoring changes are necessary for the React Native SDK.
Other changes that are needed for the SDK and could be handled in this MR:
-  Substituting ReactInstanceHandler with e.g. Broadcasting in ConnectionService.java
-  Refactoring of DropboxModule.java
-  Making BuildConfig not null when in React Native in AppInfoModule.java

ref(remove ReactInstanceHolder from AudioModule)

---

modules/API/API.js
modules/API/external/external_api.js

Add the ability to specify video type when in multistream mode.

fix(iframeAPI): pinParticipant & setLargeVideo

---

react/features/base/ui/components/web/Switch.tsx
react/features/recording/components/Recording/AbstractStartRecordingDialogContent.tsx
react/features/recording/components/Recording/styles.web.js
react/features/recording/components/Recording/web/StartRecordingDialogContent.tsx

fix(recording-dialog) Fix broken dialog content

---

react/features/base/conference/reducer.ts
react/features/base/participants/types.ts
react/features/breakout-rooms/functions.ts
react/features/breakout-rooms/types.ts

Fix get rooms info

---

lang/main-ru.json

minor additions in ru-localization

ru-localization minors

---

react/features/toolbox/components/native/HangupMenu.tsx

this fixes hangup action at mobile (close jitsi meet view)

fix hangup all action at mobile

---

react/features/chat/components/native/index.js
react/features/mobile/navigation/components/chat/components/ChatAndPollsNavigator.tsx
react/features/mobile/navigation/components/conference/components/ConferenceNavigationContainer.tsx

This is a navigator, so the file should be available inside mobile/navigation.

feat(chat/native): moved ChatAndPollsNavigator to mobile/navigation

---

react/features/mobile/navigation/screenOptions.js
react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/styles.js
react/features/welcome/constants.tsx

feat(welcome/native): improved ui

---

config.js

Add "whiteboard" to "toolbarButtons" in config.js file

---

react/features/base/config/configType.ts
react/features/base/config/constants.ts
react/features/connection-indicator/components/web/ConnectionIndicator.tsx

ref(config) Cleanup unused flags related to multi-stream mode.

---

react/features/filmstrip/components/web/Thumbnail.tsx

fix(thumbnail) Open native video context menu

---

react/features/filmstrip/components/web/PinnedIndicator.tsx
react/features/filmstrip/components/web/RaisedHandIndicator.tsx
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.tsx
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.tsx

fix(thumbnail) Fix top indicators sizes

---

react/features/base/modal/components/JitsiKeyboardAvoidingView.js
react/features/base/modal/components/JitsiScreen.js
react/features/base/ui/components/native/Button.tsx
react/features/prejoin/components/native/Prejoin.tsx

feat(base/modal): addBottomPadding default prop for extra padding on JitsiScreen

---

react/features/base/ui/components/web/Button.tsx
react/features/conference/components/web/InsecureRoomNameLabel.js
react/features/filmstrip/components/web/ThumbnailBottomIndicators.tsx
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.tsx
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.tsx

fix(ui) Fix new icons issues

---

react/features/welcome/components/styles.js

fix(welcome/native): fixed room name input placeholder

---

lang/main.json

THere are a bunch of unhandled corner cases involving virtual screen-sharing participants.

ref(StageFilmstrip) mark as experimental

---

react/features/invite/components/add-people-dialog/web/AddPeopleDialog.tsx

Only show warning if the feature is enabled

fix(dial-in) Fix warning

---

ios/sdk/src/JitsiMeet.h

Fix the following error: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

Fix Swift mapping error

---

react/features/prejoin/components/native/Prejoin.tsx
react/features/prejoin/components/styles.js

Removed some extra vertical margins and added some right insets for when screen is in landscape mode.

feat(prejoin/native): updated styles

---

react/features/conference/components/native/carmode/styles.js
react/features/filmstrip/components/native/styles.js
react/features/video-quality/components/styles.js

fix(conference/native): fixed title bar indicators style

---

conference.js
lang/main.json
modules/API/API.js
modules/API/external/external_api.js
react/features/base/conference/actionTypes.ts
react/features/base/conference/actions.ts
react/features/external-api/middleware.ts
react/features/notifications/constants.ts

feat(notification,external-api) notify bridge channel failures

---

react/features/base/ui/components/web/ClickableIcon.tsx
react/features/base/ui/components/web/Dialog.tsx

Remove focus outline for the close icon
Increase max height

fix(dialog) Improvements

---

modules/API/API.js
modules/API/external/external_api.js
package-lock.json
package.json
react/features/rtcstats/RTCStats.ts

feat(rtcstats): report pc connection failure

---

react/features/base/ui/components/native/Button.tsx
react/features/base/ui/components/native/buttonStyles.ts
react/features/chat/components/native/ChatInputBar.js
react/features/chat/components/native/styles.js
react/features/conference/components/native/Labels.js
react/features/conference/components/native/LonelyMeetingExperience.js
react/features/conference/components/native/carmode/TitleBar.tsx
react/features/conference/components/native/styles.js
react/features/prejoin/components/native/Prejoin.tsx
react/features/prejoin/components/styles.js
react/features/toolbox/components/native/styles.js

feat(native): New mobile release UI fixes

---

conference.js

fix(conference) Remove the check for multi-stream mode for web client.

---

android/app/build.gradle
android/build.gradle
package-lock.json
package.json

Native misc fixes

---

android/sdk/src/main/java/org/jitsi/meet/sdk/WebRTCVideoDecoderFactory.java
android/sdk/src/main/java/org/jitsi/meet/sdk/WebRTCVideoEncoderFactory.java
react/features/base/config/middleware.ts
react/features/base/config/reducer.ts

More misc android fixes

---

react/features/base/modal/components/JitsiKeyboardAvoidingView.js
react/features/base/modal/components/JitsiScreen.js
react/features/base/ui/components/native/Button.tsx
react/features/conference/components/native/RaisedHandsCountLabel.js
react/features/conference/components/native/styles.js
react/features/filmstrip/components/native/Thumbnail.js
react/features/mobile/navigation/components/HeaderNavigationButton.js
react/features/mobile/navigation/components/styles.js
react/features/participants-pane/components/native/ParticipantItem.js
react/features/prejoin/components/native/Prejoin.tsx
react/features/prejoin/components/styles.js

feat(native): Last mobile release UI fixes

---

react/features/conference/components/native/styles.js
react/features/mobile/navigation/components/HeaderNavigationButton.js
react/features/mobile/navigation/components/styles.js
react/features/prejoin/components/native/Prejoin.tsx
react/features/prejoin/components/styles.js

fix: Native styles fixes

---

react/features/conference/components/native/styles.js

feat(conference): fixed conference timer container padding

---

lang/main.json
react/features/conference/components/native/Conference.js
react/features/lobby/components/native/KnockingParticipantList.js
react/features/lobby/components/native/LobbyScreen.js
react/features/lobby/components/native/styles.js
react/features/old-client-notification/functions.ts
react/features/participants-pane/components/breakout-rooms/components/native/BreakoutRoomParticipantItem.js
react/features/participants-pane/components/native/LobbyParticipantItem.js
react/features/participants-pane/components/native/LobbyParticipantList.js
react/features/participants-pane/components/native/MeetingParticipantItem.js
react/features/participants-pane/components/native/ParticipantItem.js
react/features/participants-pane/components/native/styles.js
react/features/prejoin/components/native/Prejoin.tsx
react/features/prejoin/components/native/styles.js

feat(lobby/prejoin/native): style updates

---

resources/prosody-plugins/mod_certs_all.lua
resources/prosody-plugins/mod_fmuc.lua
resources/prosody-plugins/mod_muc_meeting_id.lua
resources/prosody-plugins/mod_xxl_conference.lua

Still WIP, uses visitor nodes prosodies where we create the main participants and forward the visitors to watch. Used for huge conferences.

feat: Modules for implementing visitor nodes.

---

resources/prosody-plugins/mod_jiconop.lua
resources/prosody-plugins/token/util.lib.lua
resources/prosody-plugins/util.lib.lua

Caches the parsed values in a rotating table with limited size. Skips constant creating of a stanza with never changing values - create it once and then just clone it.

feat: Several module optimizations to avoid constant parsing of jids.

---

react/features/toolbox/components/web/ToggleCameraButton.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/12628

fix(toolbox) hide drawer after toggling camera

---

package-lock.json
package.json

feat: Update lib-jitsi-meet.

---

css/_polls.scss
react/features/polls/components/web/PollCreate.tsx

This is not useful and we don't have available on native.
Related to #12640 .

feat(polls/web): removed sort options from polls

---

debian/jitsi-meet-web-config.postinst

fix: Fixes undefined error in some cases after patching config.js.

---

package-lock.json
package.json
react/features/shared-video/components/web/AbstractVideoManager.js
react/features/shared-video/components/web/YoutubeVideoManager.js

feat: Prints the error on problem sharing YouTube video.

---

config.js
react/features/app/actions.web.ts
react/features/app/getRouteToRender.web.js
react/features/base/config/configType.ts
react/features/base/config/reducer.ts
react/features/welcome/functions.ts
static/prejoin.html

Cherry pick

---

css/premeeting/_prejoin-third-party.scss

fix(prejoin) fix prejoin app dialogs not being visible

---

ios/Podfile.lock
package-lock.json
package.json
react/features/base/config/reducer.ts
react/features/mobile/polyfills/webrtc.js

RN unified plan improvements

---

lang/main.json
react/features/base/tracks/actions.web.ts

feat(audioOnly): do not disable when SS starts

---

react/features/base/media/actions.ts
react/features/base/media/middleware.any.js
react/features/base/tracks/actions.native.ts
react/features/base/tracks/middleware.any.ts
react/features/toolbox/actions.any.ts
react/features/video-layout/middleware.native.ts
react/features/video-menu/actions.any.ts

Fix set video muted params

---

react/features/welcome/components/AbstractWelcomePage.js
react/features/welcome/components/WelcomePage.web.js

fix(welcome-page) Fix error before joining a meeting from welcome page

---

css/_base.scss
css/_variables.scss
css/_welcome_page.scss
lang/main.json
react/features/base/react/components/web/Watermarks.js
react/features/welcome/components/WelcomePage.web.js

chore(welcome-page) Welcome page redesign

---

react/features/base/tracks/actions.native.ts

Implementing this on mobile in order to match the web implementation.

fix(audio-only):Don't disable on SS started.

---

package-lock.json
package.json
react/features/base/ui/components/native/Button.tsx
react/features/settings/components/native/SettingsView.tsx

Update react native paper dependency to latest

---

react/features/base/config/configType.ts
react/features/base/connection/actions.any.ts

feat: Append ?room= to conferenceRequestUrl.

---

react/features/recording/components/Recording/LocalRecordingManager.web.ts

fix(local-rec) Stop recording properly on size exceeded

---

react/features/base/ui/components/native/buttonStyles.ts
react/features/polls/components/native/PollCreate.js
react/features/polls/components/native/PollResults.js
react/features/polls/components/native/PollsPane.js
react/features/polls/components/native/styles.js
react/features/security/components/security-dialog/native/styles.js

https://user-images.githubusercontent.com/26413496/211816074-9f9dddaf-8274-4a5f-9fc4-a1e3d2fada14.mp4

feat(ui/polls/security/native): style fixes and updates 

---

react/features/app/reducers.native.ts
react/features/app/types.ts
react/features/conference/components/native/LonelyMeetingExperience.js
react/features/conference/components/native/LonelyMeetingExperience.tsx
react/features/share-room/actionTypes.ts
react/features/share-room/actions.ts
react/features/share-room/middleware.ts
react/features/share-room/reducer.ts

feat(share-room): disable Invite Others button when Share is visible

---

ios/Podfile.lock
package-lock.json
package.json

chore(deps): update rn-safe-area-context to latest

---

ios/Podfile.lock
package-lock.json
package.json

feat(rn,deps) update react-native-webrtc to 106.0.2

---

react/features/base/conference/functions.ts

fix: Fix appending URL params.

---

react/features/polls/components/native/styles.js

https://user-images.githubusercontent.com/26413496/212071089-5b134ba4-847a-4ab2-bb6c-9afad86ab7d4.mp4

feat(polls): added marginTop for remove option buttons

---

ios/Podfile.lock
package-lock.json
package.json

Rn webrtc update

---

ios/Podfile.lock
package-lock.json
package.json

feat(rn,deps) update react-native-webrtc to 106.0.4

---

react/features/polls/components/native/PollAnswer.tsx
react/features/polls/components/native/PollCreate.js
react/features/polls/components/native/PollsPane.js
react/features/polls/components/native/styles.js

https://user-images.githubusercontent.com/26413496/212324197-175becb1-6d76-4f29-9b6e-eb0bb096981c.mp4

feat(polls): removed platform check and fixed button arrangement

---

css/_responsive.scss

- enable calendar card and footer on narrow mode

fix(welcome-page) Fix narrow mode

---

config.js
debian/jitsi-meet-web-config.postinst

Fixes: https://github.com/jitsi/jitsi-meet/issues/12788

fix(config,debian) fix multistream backwards compatibility

---

modules/API/external/external_api.js

feat(external-api) sandbox the iframe

---

react/features/base/ui/components/web/Dialog.tsx

fix(dialog) Make sure dialog fits in the available height

---

modules/API/API.js

fix(external-api) Don't check recording service for live streaming

---

react/features/recording/components/Recording/LocalRecordingManager.web.ts

fix(local-rec) Reset max size on recording stop

---

.github/workflows/ci-lua.yml
resources/prosody-plugins/luajwtjitsi.lib.lua
resources/prosody-plugins/mod_auth_token.lua
resources/prosody-plugins/mod_muc_allowners.lua
resources/prosody-plugins/mod_muc_call.lua
resources/prosody-plugins/mod_muc_census.lua
resources/prosody-plugins/mod_reservations.lua
resources/prosody-plugins/mod_roster_command.lua
resources/prosody-plugins/mod_speakerstats_component.lua
resources/prosody-plugins/util.lib.lua

This commit adds a GitHub action which checks Lua codes via `luacheck`.
We (me and @shawnchin) tested this workflow action in [prosody-plugins](https://github.com/jitsi-contrib/prosody-plugins). It seems OK.

workflow: add luacheck as a GitHub action

---

package-lock.json
package.json

update ljm 1674583363

---

conference.js
react/features/base/conference/actions.ts
react/features/base/conference/functions.ts
react/features/base/config/configType.ts
react/features/base/config/constants.ts
react/features/base/config/functions.any.ts
react/features/base/participants/actionTypes.ts
react/features/base/participants/actions.ts
react/features/base/participants/functions.ts
react/features/base/participants/reducer.ts
react/features/base/participants/subscriber.ts
react/features/base/participants/types.ts
react/features/base/tracks/actionTypes.ts
react/features/base/tracks/actions.any.ts
react/features/base/tracks/functions.any.ts
react/features/base/tracks/reducer.ts
react/features/large-video/actions.any.ts
react/features/video-quality/subscriber.ts

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/2192

Feat ssrc rewriting

---

css/_recording.scss

fix(recording-dialog) Fix switch UI

---

react/features/base/lib-jitsi-meet/_.native.js

feat(base/lib-jitsi-meet): fixed build failing from bad import

---

react/features/filmstrip/components/web/Thumbnail.tsx

fix(Thumbnail):limit the size of the avatar to 200

---

modules/API/external/external_api.js

Ref: https://github.com/jitsi/jitsi-meet-electron/issues/837

fix(external-api) fix sending forms after introduction of sandbox

---

modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/VideoContainer.js
react/features/base/settings/functions.any.ts
react/features/filmstrip/actions.web.ts
react/features/filmstrip/components/native/Filmstrip.js
react/features/filmstrip/components/native/TileView.js
react/features/filmstrip/components/web/Filmstrip.tsx
react/features/filmstrip/components/web/ThumbnailWrapper.js
react/features/filmstrip/functions.native.ts
react/features/filmstrip/functions.web.ts
react/features/filmstrip/subscriber.web.ts
react/features/large-video/components/LargeVideo.web.js

fix(disableSelfView) enable disable self view when alone in meeting

---

react/features/chat/components/web/ChatMessage.tsx
react/features/chat/components/web/ChatMessageGroup.tsx

fix(chat) Break long text in multiple lines

---

react/features/polls/components/native/styles.js

feat(polls/native): changed remove option button color to match web

---

css/premeeting/_prejoin.scss
css/premeeting/_premeeting-screens.scss
react/features/base/premeeting/components/web/ConnectionStatus.tsx
react/features/base/premeeting/components/web/PreMeetingScreen.tsx
react/features/base/ui/Tokens.ts
react/features/base/ui/components/web/Input.tsx
react/features/base/ui/constants.web.ts
react/features/prejoin/components/web/Prejoin.tsx
react/features/prejoin/components/web/preview/DeviceStatus.tsx

feat(prejoin) Update design

---

react/features/toolbox/components/web/Toolbox.tsx

fix(context-menu) Fit the overflow menu on small heights

---

react/features/follow-me/subscriber.ts

fix: Fixes follow-me when there is a screenshare.

---

react/features/large-video/middleware.ts

fix: Fixes follow-me on the side that is screen sharing.

---

lang/main.json
react/features/recording/components/Recording/LocalRecordingManager.web.ts
react/features/recording/middleware.ts

fix(local-rec) Handle no mic permission

---

css/_settings-button.scss
css/_toolbars.scss
css/_variables.scss
react/features/base/ui/constants.web.ts
react/features/participants-pane/components/web/ParticipantsCounter.tsx

fix(toolbar) Fix styles

---

ios/Podfile.lock
package-lock.json
package.json

Brings back Metal rendering and other SDP negotiation improvements.

chore(rn,deps) react-native-webrtc@latest

---

react/features/connection-indicator/components/web/ConnectionIndicator.tsx
react/features/connection-indicator/components/web/ConnectionIndicatorIcon.js
react/features/filmstrip/components/web/Filmstrip.tsx
react/features/filmstrip/components/web/Thumbnail.tsx
react/features/filmstrip/components/web/styles.ts

fix(filmstrip) Minor style fixes

---

css/_popup_menu.scss
css/themes/_light.scss
react/features/base/ui/components/web/ContextMenu.tsx
react/features/base/ui/components/web/ContextMenuItem.tsx
react/features/base/ui/components/web/ContextMenuItemGroup.tsx
react/features/participants-pane/components/web/FooterContextMenu.tsx
react/features/toolbox/components/web/Toolbox.tsx
react/features/video-menu/components/web/VolumeSlider.tsx

fix(context-menu) Minor style fixes

---

react/features/participants-pane/actions.native.ts

feat(participants-pane): removed unused action

---

react/features/remote-control/keycodes.ts

fix(remote-control) Add some missing key codes for numpad

---

react/features/chat/components/web/ChatMessageGroup.tsx

Issue: https://github.com/jitsi/jitsi-meet/issues/12890

fix: keep avatar width inside flex container

---

android/sdk/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java

fix: Drop unused dependency.

---

ios/Podfile.lock
package-lock.json
package.json

chore(rn) updates react-native-gesture-handler

---

react/features/base/dialog/middleware.web.ts
react/features/room-lock/components/PasswordRequiredPrompt.web.tsx

ref(password-required) Update component to use new Dialog

---

css/_audio-preview.scss
css/_video-preview.scss
lang/main.json
react/features/base/media/components/Video.web.ts
react/features/base/ui/components/web/ContextMenu.tsx
react/features/settings/components/web/video/VideoSettingsContent.tsx
react/features/settings/components/web/video/VideoSettingsPopup.tsx
react/features/toolbox/components/web/Toolbox.tsx

Convert some files to TS
Implement redesign
Add Virtual background and Flip video to picker menu

feat(video-picker) Redesign

---

react/features/participants-pane/components/web/ParticipantsCounter.tsx

fix(participants-counter) Style fix

---

react/features/notifications/components/web/NotificationsContainer.tsx

fix(notifications) remove dead code

---

react/features/base/config/middleware.ts
react/features/base/config/reducer.ts

fix(rn) makes the preferredCodec vp8 on mobile and enables p2p

---

modules/API/API.js

fix(external-api) Unpin all participants when participant id is null

---

resources/prosody-plugins/mod_muc_meeting_id.lua

feat: Avoids joining participants before jicofo is in the room.

---

package-lock.json
package.json

ref(deps) Remove atlaskit/tabs

---

react/features/recording/actions.any.ts

chore(recording-notif) Show sticky notif for copy recording link

---

react/features/toolbox/components/web/Toolbox.tsx

Toolbar: More actions #12932 
Fixed the toolbar width issue.

Removed width from toolbar

---

react/features/lobby/middleware.ts

feat(lobby): deleted knocking participant api event

---

react/features/notifications/components/native/Notification.tsx
react/features/notifications/components/native/styles.js

https://user-images.githubusercontent.com/26413496/220666640-43b3743a-021f-45fe-8516-39ddde6d1a4f.mp4

feat(notifications): small ui updates

---

ios/Podfile.lock
package-lock.json
package.json

Fixes to SDP negotiation and transceiver lifetime.

deps(rn) react-native-webrtc@106.0.6

---

react/features/virtual-background/components/VirtualBackgroundDialog.tsx

Even when images are provided via dyamic branding.

fix(virtual-background) don't disable uploads

---

react/features/base/dialog/components/native/ConfirmDialog.js
react/features/base/dialog/components/native/PageReloadDialog.tsx

https://user-images.githubusercontent.com/26413496/221147969-a5bbc9e5-94a8-4864-bdd1-d5d772f4b014.mp4

feat(base/dialog): visibility control for  PageReloadDialog

---

conference.js
config.js
lang/main.json
react/features/app/middlewares.any.ts
react/features/app/reducers.any.ts
react/features/app/types.ts
react/features/base/config/actions.ts
react/features/base/config/constants.ts
react/features/base/connection/actions.any.ts
react/features/base/settings/functions.any.ts
react/features/conference/components/constants.ts
react/features/conference/components/native/AlwaysOnLabels.js
react/features/conference/components/native/constants.js
react/features/conference/components/web/ConferenceInfo.js
react/features/participants-pane/components/native/MeetingParticipantList.tsx
react/features/participants-pane/components/native/styles.js
react/features/participants-pane/components/web/MeetingParticipants.tsx
react/features/toolbox/components/native/Toolbox.js
react/features/toolbox/components/web/Toolbox.tsx
react/features/visitors/actionTypes.ts
react/features/visitors/actions.ts
react/features/visitors/components/native/VisitorsCountLabel.tsx
react/features/visitors/components/web/VisitorsCountLabel.tsx
react/features/visitors/functions.ts
react/features/visitors/middleware.ts
react/features/visitors/reducer.ts

First pass of visitors UI changes

---

react/features/conference/components/native/Conference.js
react/features/filmstrip/components/native/Filmstrip.js
react/features/notifications/components/native/NotificationsContainer.js
react/features/notifications/components/native/styles.js

feat(notifications): moved notifications to the bottom of the screen

---

react/features/visitors/middleware.ts

fix: Fixes visitors count when the data is missing.

---

modules/API/API.js
modules/API/external/external_api.js
react/features/notifications/actions.ts

feat(notifications) trigger iframe api event when a notification occurs

---

react/features/always-on-top/AlwaysOnTop.js

fix(always-on-top) Show participant`s avatar

---

react/features/base/ui/components/web/Checkbox.tsx
react/features/settings/components/web/SoundsTab.tsx
react/features/settings/functions.any.ts

fix(sound-settings) Disable checkbox for disabled sounds

---

css/_audio-preview.scss
react/features/base/ui/components/web/ContextMenuItem.tsx
react/features/base/ui/components/web/TextWithOverflow.tsx
react/features/base/ui/constants.any.ts
react/features/settings/components/web/audio/MicrophoneEntry.tsx
react/features/settings/components/web/audio/SpeakerEntry.tsx

https://user-images.githubusercontent.com/1556279/221856842-d0462ee4-fbe7-4090-a5a8-23b1682c957f.mov

feat(devices) scroll overflow devices texts on hover

---

package-lock.json
package.json

chore(deps) Upgrade eslint

---

package-lock.json
package.json

update ljm 1677710751

---

lang/main.json
react/features/settings/actions.ts
react/features/settings/components/web/MoreTab.tsx
react/features/settings/components/web/ProfileTab.tsx
react/features/settings/components/web/SettingsDialog.tsx
react/features/settings/functions.any.ts
react/features/settings/middleware.web.ts
react/features/subtitles/components/LanguageSelectorDialog.web.tsx

Implement redesign
Move some options from More to this tab

feat(profile-tab) Update Profile tab in Settings Dialog

---

modules/UI/UI.js
modules/UI/videolayout/VideoLayout.js
react/features/base/lastn/middleware.ts
react/features/base/participants/functions.ts
react/features/base/participants/middleware.ts
react/features/base/participants/reducer.ts
react/features/e2ee/actionTypes.ts
react/features/e2ee/actions.ts
react/features/e2ee/components/AbstractE2EELabel.ts
react/features/e2ee/functions.ts
react/features/e2ee/middleware.ts
react/features/e2ee/reducer.ts
react/features/filmstrip/components/web/Filmstrip.tsx
react/features/speaker-stats/middleware.ts
react/features/transcribing/middleware.ts

Participant join/update optimizations

---

lang/main.json
react/features/settings/components/web/MoreTab.tsx
react/features/settings/components/web/SettingsDialog.tsx

ref(more-tab) Update design on SettingsDialog More tab

---

lang/main.json
modules/API/API.js
react/features/base/ui/components/web/DialogWithTabs.tsx
react/features/settings/actions.ts
react/features/settings/components/web/SettingsDialog.tsx
react/features/settings/components/web/VirtualBackgroundTab.tsx
react/features/settings/components/web/video/VideoSettingsContent.tsx
react/features/settings/constants.ts
react/features/settings/functions.any.ts
react/features/virtual-background/components/UploadImageButton.tsx
react/features/virtual-background/components/VideoBackgroundButton.js
react/features/virtual-background/components/VirtualBackgroundPreview.tsx
react/features/virtual-background/components/VirtualBackgrounds.tsx
react/features/virtual-background/components/index.js

feat(virtual-background) Move dialog to SettingsDialog tab

---

.github/workflows/ci.yml

This will help catch bugs such as bogus imports that would trigger a mobile bundle failure.

feat(ci) build mobile bundles as part of the CI

---

react/features/settings/functions.any.ts
react/features/settings/functions.native.ts
react/features/settings/functions.web.ts

fix(native) Move function to web file

---

react/features/virtual-background/components/VirtualBackgrounds.tsx

fix(virtual-background) Style fix

---

react/features/overlay/middleware.ts

fix(overlay): fixed undefined error on web

---

lang/main-fi.json

Updating and adding a few finnish translations.

Update Finnish translations

---

react/features/settings/components/web/CalendarTab.tsx
react/features/settings/components/web/NotificationsTab.tsx
react/features/settings/components/web/ProfileTab.tsx
react/features/settings/components/web/SettingsDialog.tsx

Remove unused styles
Move some styles to their tab
Convert CalendarTab to TS
Fix mobile styles

ref(settings-dialog) Refactor styles

---

lang/main.json
react/features/base/react/components/native/NavigateSectionListItem.js
react/features/base/react/components/native/styles.js
react/features/conference/middleware.ts

feat(conference): calendar updates

---

package-lock.json
package.json
react/features/base/react/components/web/LoadingIndicator.js
react/features/base/ui/components/web/Spinner.tsx
react/features/calendar-sync/components/CalendarList.web.js
react/features/desktop-picker/components/DesktopPickerPane.js
react/features/recording/components/LiveStream/web/StartLiveStreamDialog.js
react/features/recording/components/Recording/web/StartRecordingDialogContent.tsx
react/features/salesforce/components/web/SalesforceLinkDialog.tsx
react/features/settings/components/web/CalendarTab.tsx
react/features/virtual-background/components/VirtualBackgroundPreview.tsx
react/features/virtual-background/components/VirtualBackgrounds.tsx

Replace atlaskit Spinner with the new component
Remove @atlaskit/spinner

feat(ui-components) Create Spinner component

---

ios/Podfile.lock
package-lock.json
package.json

Fixes a bug setting encoding parameters so layer bitrate can be adjusted.

deps(rn) update react-native-webrtc to 106.0.7

---

package-lock.json
package.json

update ljm 1678479039

---

react/features/google-api/components/GoogleSignInButton.native.js
react/features/google-api/components/styles.js
react/features/recording/components/LiveStream/native/StreamKeyForm.js
react/features/recording/components/LiveStream/native/styles.js

feat(recording/LiveStream): native ui updates

---

react/features/base/ui/components/native/buttonStyles.ts
react/features/conference/components/native/styles.js
react/features/mobile/navigation/components/HeaderNavigationButton.js
react/features/mobile/navigation/components/styles.js
react/features/settings/components/native/SettingsView.tsx
react/features/settings/components/native/styles.js

fix(base/ui): Buttons fix for accessibility large text

---

css/premeeting/_prejoin-third-party.scss
css/premeeting/_premeeting-screens.scss

fix(prejoin) Fix prejoin toolbar buttons

---

react/features/filmstrip/components/native/styles.js

feat(filmstrip): fix indicators size

---

react/features/filmstrip/components/web/Thumbnail.tsx

Fixes a regression introduced by https://github.com/jitsi/jitsi-meet/commit/466a36dc93bb19cbc66ed788427e5efb3130ba33

fix(thumbnail) Fix broken video for thumbnail.

---

react/features/base/avatar/components/web/StatelessAvatar.tsx
react/features/filmstrip/components/web/Thumbnail.tsx
react/features/speaker-stats/components/web/SpeakerStatsItem.tsx
react/features/speaker-stats/components/web/SpeakerStatsList.tsx

feat(avatar) Update design

---

lang/main.json
react/features/conference/actionTypes.ts
react/features/conference/actions.native.ts
react/features/conference/actions.web.ts
react/features/conference/middleware.ts

1.  Added meeting title to the notification.
2. Created action that dismisses calendar notification.
https://user-images.githubusercontent.com/26413496/225306944-87901384-67ec-444f-b34b-84b4b3e79e7f.MOV

feat(conference): dismiss calendar notification

---

css/_responsive.scss
css/_variables.scss
css/_welcome_page.scss
react/features/welcome/components/WelcomePage.web.js

fix(welcome-header) Fix and improve welcome page header

---

config.js
react/features/base/config/configType.ts
react/features/noise-suppression/actions.ts
react/features/stream-effects/noise-suppression/NoiseSuppressionEffect.ts

feat(noise-suppression) add support for Krisp

---

react/features/mobile/navigation/components/styles.js

feat(mobile/navigation): fixed close button size

---

css/_audio-preview.scss

fix(audio-picker) Fix max height

---

react/features/notifications/components/web/Notification.tsx

When displaying a long URL break it into multiple lines

fix(notification) Fix overflow issue

---

react/features/conference/components/ConferenceTimer.tsx

Show meeting time after returning from breakout room

fix(conference-timer) Show correct time

---

react/features/conference/components/web/SpeakerStatsLabel.tsx

fix(speaker-stats) Change icon

---

react/features/connection-indicator/components/native/ConnectionIndicator.tsx
react/features/display-name/components/native/styles.js
react/features/filmstrip/components/native/RaisedHandIndicator.js
react/features/filmstrip/components/native/Thumbnail.js
react/features/filmstrip/components/native/styles.js

feat(filmstrip): thumbnail indicators ui updates

---

react/features/remote-control/actions.ts

fix(remote-control):Pin the control participant SS

---

lang/main-uk.json

Updated Ukrainian translation.

lang: update Ukrainian translation

---

react/features/prejoin/components/native/styles.js

feat(prejoin): decreased height for bottom container

---

react/features/polls/components/web/PollAnswer.tsx
react/features/polls/components/web/PollResults.tsx

fix(polls) Fix style issue

---

react/features/base/toolbox/components/AbstractButton.tsx
react/features/base/toolbox/components/AbstractToolboxItem.tsx
react/features/base/toolbox/components/ToolboxItem.native.tsx
react/features/base/toolbox/components/ToolboxItem.web.tsx
react/features/base/ui/components/web/ContextMenuItem.tsx

ref(abstract-button) Convert to TS

---

react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/WelcomePage.web.js

fix(welcome-page) Fix function name

---

react/features/base/avatar/components/Avatar.tsx
react/features/base/avatar/components/index.native.js
react/features/base/avatar/components/index.native.ts
react/features/base/avatar/components/index.web.js
react/features/base/avatar/components/index.web.ts
react/features/base/avatar/components/native/index.js
react/features/base/avatar/components/web/index.js
react/features/chat/components/web/ChatMessageGroup.tsx
react/features/filmstrip/components/web/Thumbnail.tsx
react/features/participants-pane/components/breakout-rooms/components/web/RoomParticipantContextMenu.tsx
react/features/participants-pane/components/native/RoomParticipantMenu.tsx
react/features/participants-pane/components/web/LobbyParticipants.tsx
react/features/participants-pane/components/web/ParticipantItem.tsx
react/features/prejoin/components/web/Prejoin.tsx
react/features/prejoin/components/web/dialogs/CallingDialog.tsx
react/features/settings/components/native/SettingsView.tsx
react/features/settings/components/web/ProfileTab.tsx
react/features/speaker-stats/components/web/SpeakerStatsItem.tsx
react/features/video-menu/components/native/ConnectionStatusComponent.tsx
react/features/video-menu/components/web/FakeParticipantContextMenu.tsx
react/features/video-menu/components/web/ParticipantContextMenu.tsx

Fix imports
Remove unnecessary @ts-ignore

ref(avatar) Convert to TS

---

react/features/conference/components/native/Conference.js

feat(conference): hide status bar on android devices if full screen enabled

---

react/features/base/tooltip/components/Tooltip.tsx

fix(tooltip) Don't show on small screens

---

css/modals/screen-share/_share-audio.scss
react/features/screen-share/components/web/ShareAudioDialog.tsx

fix(share-audio) Fix dialog max-height

---

react/features/base/media/components/AbstractAudio.ts
react/features/base/media/components/AbstractVideoTrack.tsx
react/features/base/react/components/AbstractPage.ts
react/features/base/testing/components/AbstractTestHint.ts
react/features/conference/components/AbstractConference.ts
react/features/lobby/components/AbstractLobbyScreen.tsx
react/features/notifications/components/index.native.ts
react/features/notifications/components/index.web.ts
react/features/notifications/components/native/index.ts
react/features/notifications/components/web/index.ts
react/features/recent-list/components/AbstractRecentList.tsx
react/features/recording/components/Recording/AbstractHighlightButton.ts
react/features/recording/components/Recording/web/HighlightButton.tsx
react/features/shared-video/components/native/AbstractVideoManager.ts
react/features/subtitles/components/AbstractCaptions.ts
react/features/subtitles/reducer.ts

ref(TS) Convert some Abstract classes to TS

---

css/_videolayout_default.scss
modules/UI/videolayout/VideoContainer.js

ref(jQuery) Replace some jQuery with JS

---

react/features/chat/components/AbstractMessageRecipient.ts
react/features/chat/components/web/MessageRecipient.tsx
react/features/device-selection/components/DeviceSelector.web.tsx
react/features/e2ee/components/ParticipantVerificationDialog.tsx
react/features/notifications/components/web/NotificationsContainer.tsx
react/features/reactions/components/web/ReactionsMenu.tsx
react/features/settings/components/web/SettingsDialog.tsx
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.tsx
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.tsx
react/features/video-menu/components/web/VerifyParticipantButton.tsx

Replace withStyles with makeStyles

ref: Convert some class components to function components

---

conference.js
lang/main.json
react/features/base/conference/functions.ts
react/features/base/conference/middleware.any.js
react/features/base/lib-jitsi-meet/actions.ts
react/features/conference/components/native/Conference.js
react/features/notifications/components/native/NotificationsContainer.tsx
react/features/notifications/components/native/styles.js
react/features/toolbox/components/native/Toolbox.js
react/features/video-menu/components/native/RemoteVideoMenu.js
react/features/visitors/components/native/VisitorsCountLabel.tsx
react/features/visitors/components/web/VisitorsCountLabel.tsx
react/features/visitors/middleware.ts
react/features/visitors/reducer.ts

feat(visitors): Updates mobile to handle redirected conf error.

---

react/features/app/components/AbstractApp.ts
react/features/base/app/components/BaseApp.tsx
react/features/base/config/configType.ts
react/features/base/util/helpers.ts
react/features/google-api/components/AbstractGoogleSignInButton.ts
react/features/invite/components/add-people-dialog/AbstractAddPeopleDialog.ts
react/features/invite/functions.ts
react/features/invite/types.ts
react/features/notifications/types.ts
react/features/video-quality/components/AbstractVideoQualityLabel.ts
react/features/video-quality/components/VideoQualityLabel.native.js
react/features/video-quality/components/VideoQualityLabel.web.js

ref(TS Convert all Abstract classes to TS

---

resources/extra-large-conference/pre-configure.sh
resources/prosody-plugins/mod_visitors.lua
resources/prosody-plugins/mod_visitors_component.lua

feat: Updates visitors component with new iq messages.

---

config.js
react/features/base/config/configType.ts
react/features/base/config/configWhitelist.ts
react/features/base/config/functions.any.ts

Always enable unified plan support on Chromium endpoints.

fix(config) Ignore enableUnifiedOnChrome config flag.

---

resources/prosody-plugins/mod_fmuc.lua
resources/prosody-plugins/mod_muc_max_occupants.lua

Visitors stats

---

react/features/conference/middleware.ts
react/features/notifications/components/native/styles.js

fix(notications): increased notification max height for buttons to fit

---

modules/API/external/external_api.js

fix(external-api): Set ifame.src before adding it.

---

doc/debian/jitsi-meet/jitsi-meet.example
index.html

This PR allows for loading the pwa-worker.js from directories other than /

feature: support loading pwa-worker from subdir

---

lang/main.json
react/features/connection-stats/components/ConnectionStatsTable.tsx

- moves e2ee verified into "Show More" section of the connection table popup
- Changes the values to yes/no

feat(connection-table): e2ee verified changes

---

react/features/conference/components/native/TitleBar.js
react/features/conference/components/native/carmode/TitleBar.tsx
react/features/filmstrip/components/native/Thumbnail.js
react/features/toolbox/components/native/Toolbox.js

https://user-images.githubusercontent.com/26413496/229564991-302b7cf7-2915-4396-bad9-413d426b944f.mp4

fix(titlebar, toolbox): stop onpress bubbling for components underneath 

---

css/_popover.scss
react/features/base/components/themes/participantsPaneTheme.json
react/features/base/ui/components/web/Button.tsx
react/features/base/ui/components/web/ContextMenu.tsx
react/features/base/ui/components/web/ListItem.tsx
react/features/base/ui/constants.web.ts
react/features/participants-pane/components/breakout-rooms/components/web/AddBreakoutRoomButton.tsx
react/features/participants-pane/components/breakout-rooms/components/web/AutoAssignButton.tsx
react/features/participants-pane/components/breakout-rooms/components/web/CollapsibleRoom.tsx
react/features/participants-pane/components/breakout-rooms/components/web/LeaveButton.tsx
react/features/participants-pane/components/breakout-rooms/components/web/RoomList.tsx
react/features/participants-pane/components/web/LobbyParticipantItems.tsx
react/features/participants-pane/components/web/MeetingParticipants.tsx
react/features/participants-pane/components/web/ParticipantItem.tsx
react/features/participants-pane/components/web/ParticipantsPane.tsx

feat(participants-pane) Design update

---

react/features/base/ui/components/native/Input.tsx
react/features/polls/components/native/PollCreate.js
react/features/polls/components/native/PollsPane.js

feat(polls): answer and question inputs native updates

---

conference.js
react/features/base/conference/functions.ts
react/features/base/conference/middleware.any.js
react/features/base/config/reducer.ts
react/features/visitors/middleware.ts
react/features/visitors/reducer.ts

fix: Handles max occupants errors for visitor nodes

---

resources/prosody-plugins/mod_fmuc.lua

Will destroy room immediately when there are no main participant, cause anyway the main room will be destroyed and jicofo will leave this room. Visitors will reload when seeing jicofo leaving.
When there are no visitors we give 15 seconds for them to connect and after that we destroy the room.

fix: Updates the rules for visitor room destroy.

---

conference.js

fix(visitors): Fixes large video and pinning.

---

css/_audio-preview.scss
css/_popover.scss
css/_video-preview.scss
react/features/base/popover/components/Popover.web.tsx
react/features/base/toolbox/components/web/ToolboxButtonWithIcon.tsx
react/features/toolbox/components/web/AudioSettingsButton.tsx
react/features/toolbox/components/web/VideoSettingsButton.tsx

fix(popover) Fix close popover from toggle button

---

react/features/base/media/components/web/AudioTrack.tsx
react/features/base/media/components/web/VideoTrack.tsx
react/features/base/react/Platform.web.ts
react/features/base/tracks/loadEffects.web.ts
react/features/calendar-sync/actions.web.ts
react/features/connection-indicator/components/web/ConnectionIndicator.tsx
react/features/connection-indicator/components/web/ConnectionIndicatorIcon.tsx
react/features/deep-linking/components/DeepLinkingMobilePage.web.tsx
react/features/deep-linking/functions.ts
react/features/deep-linking/openDesktopApp.ts
react/features/filmstrip/components/web/AudioTracksContainer.tsx
react/features/filmstrip/components/web/Thumbnail.tsx
react/features/filmstrip/components/web/VirtualScreenshareParticipant.tsx
react/features/google-api/actions.ts
react/features/invite/components/dial-in-summary/web/DialInSummary.tsx
react/features/invite/components/dial-in-summary/web/NumbersList.tsx
react/features/prejoin/components/web/Prejoin.tsx
react/features/prejoin/components/web/dialogs/CallingDialog.tsx
react/features/prejoin/components/web/dialogs/DialInDialog.tsx
react/features/prejoin/components/web/dialogs/JoinByPhoneDialog.tsx
react/features/recent-list/components/AbstractRecentList.tsx
react/features/recording/components/LiveStream/web/StartLiveStreamDialog.tsx
react/features/remote-control/actions.ts
react/features/remote-control/components/RemoteControlAuthorizationDialog.tsx
react/features/stream-effects/virtual-background/JitsiStreamBackgroundEffect.ts
react/features/stream-effects/virtual-background/TimerWorker.ts
react/features/stream-effects/virtual-background/index.ts
react/features/virtual-background/actions.ts
react/features/virtual-background/reducer.ts
tsconfig.native.json

ref(TS) Convert some components to TS

---

resources/prosody-plugins/mod_muc_meeting_id.lua

feat(visitors): Updates meeting id for visitor rooms.

---

resources/prosody-plugins/mod_visitors.lua
resources/prosody-plugins/util.lib.lua

feat(visitors): Fix creating breakout rooms for promoted visitor.

---

react/features/toolbox/components/web/AudioSettingsButton.tsx
react/features/toolbox/components/web/VideoSettingsButton.tsx

fix(device-picker) Close picker when another is open

---

react/features/settings/components/web/SettingsDialog.tsx

fix(notifications-tab) Fix sounds settings

---

react/features/prejoin/components/web/dialogs/DialInDialog.tsx

fix(dial-in) Make text selectable

---

react/features/toolbox/components/web/Toolbox.tsx

Some helpers and components weren't correctly imported.

fix(toolbox): imports

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
resources/prosody-plugins/mod_muc_auth_ban.lua
resources/prosody-plugins/mod_muc_end_meeting.lua
resources/prosody-plugins/mod_muc_filter_access.lua
resources/prosody-plugins/mod_muc_flip.lua
resources/prosody-plugins/mod_muc_hide_all.lua
resources/prosody-plugins/mod_muc_jigasi_invite.lua
resources/prosody-plugins/mod_muc_kick_jigasi.lua
resources/prosody-plugins/mod_rate_limit.lua

Adds few lua modules for handling various use cases

---

ios/Podfile.lock
package-lock.json
package.json

Updates the Google SignIn SDK to the latest.

chore(deps) react-native-google-signin@latest

---

.npmrc
package-lock.json
package.json

chore(deps) update xmldom to the latest version

---

resources/prosody-plugins/mod_turncredentials_http.lua

feat: Module to expose turn credentials via http endpoint.

---

resources/prosody-plugins/mod_muc_limit_messages.lua

feat: Adds a module for restricting number of messages in a room.

---

resources/prosody-plugins/mod_auth_token.lua
resources/prosody-plugins/mod_av_moderation_component.lua
resources/prosody-plugins/mod_filter_iq_rayo.lua
resources/prosody-plugins/mod_fmuc.lua
resources/prosody-plugins/mod_muc_breakout_rooms.lua
resources/prosody-plugins/mod_muc_limit_messages.lua
resources/prosody-plugins/mod_speakerstats_component.lua
resources/prosody-plugins/mod_token_verification.lua
resources/prosody-plugins/mod_visitors_component.lua

Fix visitors messages and limits

---

react/features/app/actions.web.ts
react/features/base/config/configType.ts

feat: Adds an option to disable iframeAPI.

---

react/features/base/config/reducer.ts

feat(base/config): commented out mobile codecs override

---

css/main.scss
css/modals/_dialog.scss
css/modals/invite/_add-people.scss
css/modals/invite/_invite_more.scss
react/features/base/react/components/web/InlineDialogFailure.tsx
react/features/base/react/components/web/MultiSelectAutocomplete.tsx
react/features/base/ui/components/types.ts
react/features/base/ui/components/web/ContextMenu.tsx
react/features/base/ui/components/web/Input.tsx
react/features/base/ui/components/web/MultiSelect.tsx
react/features/invite/components/add-people-dialog/AbstractAddPeopleDialog.tsx
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.tsx
react/features/invite/components/add-people-dialog/web/InviteContactsForm.tsx
react/features/invite/components/add-people-dialog/web/InviteContactsSection.tsx
react/features/invite/types.ts
react/features/toolbox/constants.ts

ref(invite): add people form

---

react/features/base/modal/components/JitsiScreen.js
react/features/base/participants/functions.ts
react/features/base/react/types.ts
react/features/conference/components/native/LonelyMeetingExperience.tsx
react/features/invite/actions.native.ts
react/features/invite/components/add-people-dialog/AbstractAddPeopleDialog.tsx
react/features/invite/components/add-people-dialog/native/AddPeopleDialog.tsx
react/features/invite/components/add-people-dialog/native/styles.js
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.tsx
react/features/invite/functions.ts
react/features/mobile/navigation/components/HeaderNavigationButton.tsx
react/features/mobile/navigation/components/styles.ts
react/features/participants-pane/components/native/MeetingParticipantList.tsx

https://user-images.githubusercontent.com/26413496/233379779-e0b15f13-39b7-4679-a490-72ca8dbc09cc.mp4

feat(invite/native): add people dialog fixes

---

react/features/conference/components/native/Conference.js
react/features/conference/components/native/styles.js

feat(conference): fixed raisedhandcountlabel and filmstrip conflict

---

conference.js
react/features/base/conference/middleware.any.ts

When gUM resolves after the user has joined as a visitor, skip adding the local tracks to the conference.

fix(visitor): Do not add media tracks in visitor mode.

---

react/features/toolbox/components/web/Toolbox.tsx

fix(toolbar) Remove focus on hide

---

lang/main.json
react/features/app/actions.web.ts
react/features/conference/constants.ts
react/features/conference/extraConstants.ts
react/features/conference/middleware.ts

It will give a timeout of 5 mins for the conference, before navigating away from it.

fix: Updates the option for disabling iframe to show a warning.

---

css/modals/invite/_info.scss
react/features/invite/components/dial-in-summary/web/ConferenceID.tsx

fix(dial-in) Make text selectable on Dial In page

---

modules/API/API.js
modules/API/constants.js
modules/API/external/external_api.js
react/features/base/conference/reducer.ts

Linked to [#2253](https://github.com/jitsi/lib-jitsi-meet/pull/2253)

feat(external-api) support assumed bandwidth bps config and command

---

react/features/base/conference/actions.ts

fix(visitors) Do not add tracks in redux to conference.

---

config.js
package-lock.json
package.json
react/features/base/conference/functions.ts

feat: Disables sending localstats in visitor mode.

---

react/features/chat/components/web/ChatInput.tsx

fix(chat) Focus input on chat open

---

resources/prosody-plugins/mod_measure_message_count.lua

feat: Implements amplitude events for messages count.

---

modules/UI/UI.js

fix: Fixes unresolved function.

---

css/_videolayout_default.scss

fix(dialog) Fix close animation moves whole body

---

react/features/settings/components/web/video/VideoSettingsContent.tsx

fix: Hide virtual background for unsupported browsers from vide preview.

---

react/features/conference/middleware.ts

feat: Shows html in notification warning.

---

resources/prosody-plugins/mod_measure_message_count.lua

feat: Adds conference duration to the amplitude stat.

---

css/_chat.scss
react/features/chat/components/web/ChatMessage.tsx

Chat panel update

---

react/features/base/toolbox/components/ToolboxItem.web.tsx

fix(keyboard-a11y) Remove space from click trigger

---

resources/extra-large-conference/prosody.cfg.lua.visitor.template
resources/prosody-plugins/mod_fmuc.lua
resources/prosody-plugins/mod_visitors.lua
resources/prosody-plugins/mod_visitors_component.lua

feat(visitors): Handles locked rooms for visitors.

---

css/_chat.scss
react/features/chat/components/web/ChatMessage.tsx
react/features/chat/components/web/MessageRecipient.tsx

Revert color change of scroll corner

fix(chat) Fix name overflows chat bubble

---

react/features/base/ui/components/web/Checkbox.tsx

fix(checkbox) Fix misalign when label has multiple lines

---

ios/fastlane/Fastfile

fix(ios) avoid rejecting builds in progress in TestFlight

---

resources/prosody-plugins/mod_visitors.lua
resources/prosody-plugins/mod_visitors_component.lua

fix: Fix room locking without visitors.

---

react/features/chat/components/web/ChatMessage.tsx
react/features/chat/components/web/ChatMessageGroup.tsx

fix(chat) Fix horizontal scroll

---

react/features/invite/components/add-people-dialog/web/DialInNumber.tsx

fix(dial-in) Place PIN on a new line

---

react/features/invite/components/add-people-dialog/web/DialInNumber.tsx

fix(dial-in) Place PIN on a new line (#13309)

---

react/features/base/config/constants.ts
react/features/device-selection/components/AudioDevicesSelection.web.tsx
react/features/settings/components/web/ProfileTab.tsx
react/features/settings/components/web/SettingsDialog.tsx
react/features/settings/functions.any.ts

feat: Audio output settings in visitor mode.

---

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioDeviceHandlerGeneric.java

feat(android) add support for Hearing Aid devices

---

react/features/base/toolbox/components/AbstractButton.tsx
react/features/video-menu/components/native/RemoteVideoMenu.tsx
react/features/video-menu/components/native/VolumeSlider.tsx
react/features/video-menu/constants.ts

feat(video-menu): native track volume control updates

---

react/features/invite/functions.ts
react/features/recording/components/LiveStream/AbstractLiveStreamButton.ts
react/features/recording/functions.ts

fix(toolbar-buttons) Hide rec and livestream buttons for non-moderators

---

modules/API/external/external_api.js

Add optional "sandbox" option to the external API which will be applied to the iframe.

feat(external-api) optional sandbox

---

react/features/recording/components/Recording/AbstractStartRecordingDialogContent.tsx
react/features/recording/components/Recording/web/StartRecordingDialogContent.tsx
react/features/recording/functions.ts

fix(local-recording) Enable local rec for non-moderators

---

lang/main.json
react/features/app/actions.native.ts
react/features/app/reducers.web.ts
react/features/app/types.ts
react/features/base/config/configType.ts
react/features/base/premeeting/actionTypes.ts
react/features/base/premeeting/actions.web.ts
react/features/base/premeeting/components/web/PreMeetingScreen.tsx
react/features/base/premeeting/components/web/UnsafeRoomWarning.tsx
react/features/base/premeeting/reducer.web.ts
react/features/base/premeeting/types.ts
react/features/base/tooltip/actions.tsx
react/features/base/tooltip/components/Tooltip.tsx
react/features/base/ui/Tokens.ts
react/features/base/util/contants.ts
react/features/base/util/getUnsafeRoomText.native.ts
react/features/base/util/getUnsafeRoomText.web.ts
react/features/conference/components/native/InsecureRoomNameExpandedLabel.ts
react/features/conference/components/native/InsecureRoomNameExpandedLabel.tsx
react/features/conference/components/web/InsecureRoomNameLabel.tsx
react/features/mobile/navigation/components/RootNavigationContainer.tsx
react/features/mobile/navigation/routes.ts
react/features/mobile/navigation/screenOptions.ts
react/features/prejoin/components/native/UnsafeRoomWarning.tsx
react/features/prejoin/components/native/styles.ts
react/features/prejoin/components/web/Prejoin.tsx
react/features/welcome/components/WelcomePage.native.tsx
react/features/welcome/components/WelcomePage.web.tsx
react/features/welcome/components/styles.native.ts

can be tested at: https://cdumitru.jitsi.net

feat(prejoin): unsafe room name warning

---

globals.d.ts
react/features/always-on-top/AlwaysOnTop.tsx
react/features/always-on-top/AudioMuteButton.tsx
react/features/always-on-top/HangupButton.tsx
react/features/always-on-top/Toolbar.tsx
react/features/always-on-top/ToolbarButton.tsx
react/features/always-on-top/VideoMuteButton.tsx
react/features/always-on-top/index.tsx
tsconfig.native.json
webpack.config.js

ref(TS) Convert always-on-top to TS

---

react/features/settings/actions.web.ts
react/features/settings/components/web/MoreTab.tsx
react/features/settings/components/web/ProfileTab.tsx
react/features/settings/functions.any.ts
react/features/settings/middleware.web.ts

ref(self-view) Move Hide self view to General tab

---

lang/main-pt.json

Portuguese translation update

---

resources/prosody-plugins/mod_fmuc.lua
resources/prosody-plugins/mod_muc_lobby_rooms.lua
resources/prosody-plugins/mod_visitors.lua

fix: Do not allow visitors while lobby is enabled.

---

globals.native.d.ts
react/features/base/color-scheme/ColorSchemeRegistry.ts
react/features/base/conference/actions.ts
react/features/base/conference/middleware.any.ts
react/features/base/lib-jitsi-meet/functions.any.ts
react/features/base/react/components/web/Watermarks.tsx
react/features/base/sounds/components/SoundCollection.ts
react/features/chat/middleware.ts
react/features/mobile/call-integration/reducer.ts
react/features/recording/components/Recording/LocalRecordingManager.web.ts
react/features/room-lock/actions.ts
react/features/salesforce/actions.ts
react/features/security/actions.ts
react/features/shared-video/actions.any.ts
react/features/videosipgw/middleware.ts

ref(TS) Improve TS

---

conference.js
package-lock.json
package.json

The finally was causing the disconnect to be executed after the connect method.

fix(visitors): Leave and disconnect before connecting.

---

resources/prosody-plugins/mod_visitors.lua

fix: Adds visitor messages to the room history.

---

doc/jaas/index-jaas.html
doc/jaas/nginx-jaas.conf

feat(jaas-example): Uses conf-id generated from token generator.

---

react/features/web-hid/middleware.ts

fix(web-hid): Fully disable from config

---

.github/workflows/ci.yml
package.json

Reverts the ESLint part of https://github.com/jitsi/jitsi-meet/pull/13360/files . Because of incorect file list (the first file is ignored) and also warning when the changed file is part of .eslintignore

fix(CI): Eslint warning for testing ignored files.

---

modules/API/API.js

fix(API)setLargeVideoParticipant ensure stage view

---

resources/prosody-plugins/mod_muc_meeting_id.lua

fix: Fix matching user affiliation.

---

resources/extra-large-conference/README.md
resources/extra-large-conference/prosody.cfg.lua.visitor.template
resources/prosody-plugins/mod_certs_s2soutinjection.lua
resources/prosody-plugins/mod_s2sout_override.lua
resources/prosody-plugins/s2sout_override.patch
resources/prosody-plugins/s2sout_override1.patch
resources/prosody-plugins/s2sout_override2.patch
resources/prosody-plugins/stanza_router_no-log.patch

fix(visitors): Fixes leaking s2s connections.

---

css/_toolbars.scss
react/features/filmstrip/components/web/ThumbnailBottomIndicators.tsx
react/features/toolbox/actionTypes.ts
react/features/toolbox/actions.any.ts
react/features/toolbox/components/web/Toolbox.tsx
react/features/toolbox/reducer.ts
react/features/toolbox/subscriber.ts

Check toolbox and tile names overlap and move toolbox accordingly

feat(toolbox) Shift up to make tile name visible

---

react/features/settings/actions.web.ts
react/features/settings/components/web/MoreTab.tsx
react/features/settings/components/web/ProfileTab.tsx
react/features/settings/functions.any.ts

chore(settings) Move language to general tab

---

conference.js

Also, log an error when when the application fails to switch to the selected audio output device.

fix(device-selection): Do not create multiple tracks for the same deviceId.

---

react/features/keyboard-shortcuts/actions.web.ts

fix(visitors): Ignore push-to-talk shortcut.
