react/features/always-on-top/AudioMuteButton.js, react/features/always-on-top/HangupButton.js, react/features/always-on-top/ToolbarButton.js, react/features/always-on-top/VideoMuteButton.js
This reduces the bundle size by about 100KB
It also decouples the AOT buttons from the classes that are used to implement other features
=> ref(AOT) Change buttons to not use abstract classes

conference.js
In audio-only screenshare mode when there is no local audio track from mic present, do not add the audio track from screenshare to redux. Adding the track to redux will sync the track mute state to that of /base/media and show that the mic is unmuted even when that is not the case. Fixes https://github.com/jitsi/jitsi-meet/issues/10706.
=> fix(conference) Do not add audio track from screenshare to redux.

package-lock.json, package.json
- fix(rn,remote-video-menu) fix import after refactor
- feat(breakout-rooms) add breakout-rooms
- fix(build) fix make dev with facial recognition worker
- fix(config) fix incorrect option name and whitelist it
- feat(video-quality): Always prioritize SS in tile view.
- fix(lang) update french translation
- fix(lang) update German translation
- fix(lang) update Arabic translation
- fix(lang) update Occitan translation
- fix(lang) update Russian translation
- fix(prejoin) Fix prejoin app
- fix(rn,welcome-page) don't create video track unnecessarily
- fix(Avatar): Display correctly any emoji/special character in a avatar initials
- fix(rn,sdk) remove deprecated color scheme prop
- fix(rn,sdk) drop deprecated option …
=> update ljm 1649325751

ios/app/broadcast-extension/SampleHandler.swift
It creates a compilation warning because it forces linking with the SDK.
=> fix(ios,broadcast-extension) remove unused import

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java
If we attempt to start it while in the background we'll get a crash. A
more elegant fix would be to wait until the app transitions to the
foreground to start it, but the crash is hurting us now.
=> fix(android) fix crash when starting foreground service

react/features/base/avatar/functions.js
Some languages have a separate representation for characters based on their context, placement in a word. The form of a character may be different if it is an isolated character, an initial character, a medial character, or a final character. See this [link](https://en.wikipedia.org/wiki/Persian_alphabet#Overview_table) showing different forms of a Persian character based on its context.
Usually for initials, the isolated form is displayed. This pull request adds a zero-width non-joiner between the initials, so the isolated form is rendered.
=> fix(avatar): add ZWNJ between initials of letter avatars

react/features/filmstrip/actionTypes.ts, react/features/filmstrip/actions.web.js, react/features/filmstrip/components/web/Thumbnail.js, react/features/filmstrip/components/web/ThumbnailWrapper.js, react/features/filmstrip/functions.web.js, react/features/filmstrip/middleware.web.js, react/features/video-menu/components/web/TogglePinToStageButton.js
Fix dominant speaker not removed on leave
Fix video not shown in vertical filmstrip when a remote screensharing was on
Refactor pin/ unpin. Add click to unpin
Remove from stage on unpin, except dominant (just change pin state)
Fix local shows video on both stage and vertical filmstrip
Don't reorder on stage based on queue (sort all by id)
=> fix(stage-filmstrip) Fix issues

react/features/base/tracks/middleware.js
In case of conference failed as max number of occupants reached, we should skip clearing the local tracks to keep state of pre-join screen. Otherwise, on join we will join muted even though on prejoin screen it was unmuted on the initial attempt.
=> fix: Skips clearing tracks on conference failed.

react/features/base/participants/middleware.js, react/features/notifications/middleware.js
Do not show join notifications or play sounds when the fake participant tile for Screenshare is added or removed with multi-steam mode.
=> fix(multi-stream) Do not show join notifications for SS tiles.

debian/jitsi-meet-tokens.postinst, resources/prosody-plugins/token/util.lib.lua
This PR updates the Prosody token authentication plugin to use luajwtjitsi 3.0, mitigating the risk relating to [this](https://github.com/jitsi/jitsi-meet/security/advisories/GHSA-45ff-37jm-xjfx) recent jitsi-meet security advisory. See also the related PR: https://github.com/jitsi/luajwtjitsi/pull/3.
The main changes are:
* Update luajwtjitsi from version 2.0 to 3.0
* Removed `Util:verify_issuer`, `Util:verify_audience`, `Util:verify_token` as these are now part of luajwtjitsi. Note that the check for `room` claims is preserved.
* Added a `signatureAlgorithm` option to follow best practices of the server dictating the signature algorithm for use. 
* Slight refactor in how a symmetric signing key is set.
=> Refactor token authentication plugin to use new luajwtjitsi version

react/features/device-selection/functions.js
It seems that showing the device selection dialog on ios Safari will
leads to not working audio. This is temporary fix until we find out
better solution.
=> fix(prejoin):Disable device selection on iosSafari

react/features/base/lastn/middleware.js
If last N goes down to 1 it will be stuck there since it's > 0 and will
be our `lastNSelected`. When limits are applied we'll take the minimum,
so it will end up being 1.
Once can end up in last N being 1 by several means, the more obvious one
by entering Picture-in-Picture mode on mobile.
Fix it by not using the previous last N value for the current
calculation, at all.
Fixes: https://github.com/jitsi/jitsi-meet/issues/10257
Closes: https://github.com/jitsi/jitsi-meet/pull/10491
=> fix(lastN) fix last N getting stuck on 1

package-lock.json, package.json, react/features/device-selection/actions.js, react/features/device-selection/functions.js
With https://bugs.webkit.org/show_bug.cgi?id=179363 being fixed, we should now be able to switch between devices in call. Also, before the webkit fix, we were able to continue to use the old track when a new track was created for preview in device settings before joining the call. This doesn't work anymore after the fix. Therefore, always replace the track in redux even if the selected device hasn't changed. Depends on https://github.com/jitsi/lib-jitsi-meet/pull/1993.
=> fix(device-selection) Enable device selection on mobile Safari.

resources/install-letsencrypt-cert.sh
It fails when certbot is not installed and exits with an error without installing anything.
=> fix: Fixes Let's Encrypt script.

react/features/base/premeeting/components/web/PreMeetingScreen.js, react/features/toolbox/components/web/Toolbox.js
- if hiddenPremeetingButtons is undefined, toolbarButtons overwrite decides what buttons to show
- if hiddenPremeetingButtons is empty array, all buttons are show on premeeting screen regardless of toolbarButtons
- if hiddenPremeetingButtons hides some buttons, only those buttons will be hidden regardless of toolbarButtons overwrite
=> fix(premeeting) Detach premeeting toolbar buttons visibility

react/features/base/avatar/components/web/StatelessAvatar.js
=> fix(avatar) Center phone icon in participants pane avatars

debian/control, debian/jitsi-meet-turnserver.postinst, debian/jitsi-meet-turnserver.postrm
We used to multiplex the ports in nginx, but we dropped that at some point, so now coturn is on its own listening and nginx dependency is no longer needed. Our turnserver config can be used with nginx | apache2.
=> feat: Drops nginx dependency for turnserver config.

config.js, react/features/breakout-rooms/functions.js, react/features/participants-pane/components/breakout-rooms/components/web/RoomList.js, react/features/participants-pane/components/native/ParticipantsPane.js, react/features/participants-pane/components/native/styles.js, react/features/participants-pane/components/web/ParticipantsPane.js, react/features/participants-pane/functions.js, react/features/settings/functions.js
- hideAutoAssignButton
- hideFooterMenu
- hideModeratorSettingsTab
- hideMoreActionsButton
- hideMuteAllButton
=> feat(external-api) add breakout room configs to hide auto assign and footer menu buttons

react/features/authentication/middleware.web.js
Since all the auth logic is not ported to React on the web,
`_isWaitingForOwner` will always return `false` because the
`waitForOwner()` action is not (yet) used there.
THis fix always tries to hide the dialog no matter what, which is not a
Bad Thing to do anyway.
There is a related bug remaining, however: if one pressed "I am the
host" and then cancel, it doesn't goo back to the previous dialog, but
it completely kils the meeting. This is a compromise we'll have to live
with for a bit longer.
=> fix(auth) fix WaitForOwnerDialog not vanishing

react/features/base/ui/Tokens.js, react/features/invite/components/add-people-dialog/native/styles.js, react/features/mobile/navigation/components/HeaderNavigationButton.js, react/features/mobile/navigation/screenOptions.js
Skip the welcome page for now, until we can remove the audio / video
toggle.
=> feat(rn,ui) use dark gray for screen headers

conference.js
Now that screenshare is permitted when a user is in audio-only mode, do not create a new video track if it doesn't exist when audio-only mode is automatically disabled. New track creation should only be prompted by user action such as camera unmute or start screenshare. Fixes https://github.com/jitsi/jitsi-meet/issues/11460.
=> fix(audio-only) Do not create a new track for audio-only changes.

react/features/invite/components/dial-in-summary/native/DialInSummary.js, react/features/mobile/navigation/components/RootNavigationContainer.js, react/features/mobile/navigation/screenOptions.js
Only havee the screen in the hierarchy if we have a welcome page, since
it's the only way to access it.
Use goBack() from the navigator directly and avoid duplicating all props
to the screen.
=> fix(rn,dialin-summary) simplify navigation

react/features/base/participants/functions.js
With multi-stream support, when a presenter that is still screen sharing leaves a conference, they will see a `Cannot read properties of undefined (reading 'name')` error in the logs. This is a race condition where the local screenshare participant hasn't been removed yet by the state listener.
Use the `getParticipantDisplayName` selector, which also handles defaults, for getting the owner's name to always ensure there is a value.  This also handles the corner case when a presenter edits their name to "" while screen sharing.
=> fix(screenshare) use selector for getting screenshare owner display name

react/features/av-moderation/constants.js, react/features/av-moderation/middleware.js
This way only one will be shown at a time.
=> fix(av-moderation) use a consistent UID for ask to unmute notifications

react/features/chat/components/native/Chat.js, react/features/chat/components/native/PrivateMessageButton.js
Regarding the fact that Chat is a screen right now and we navigate, we don't need to dispatch openChat  or closeChat.
=> fix(chat/native) private message replies

react/features/toolbox/functions.web.js
This small change enables the audio settings menu on the mic button for Firefox > 100. As Firefox 101 finally supports multiple open microphones the audio input settings menu becomes available for these users.
=> feat: enable audio settings menu for Firefox

config.js, react/features/base/config/configWhitelist.js, react/features/notifications/actions.js
This works together with the broader "notifications" config option. One
might choose to leave the existing option unespecified *thus allowing
all notifications) and then use this new one to be explicit about which
ones to disable.
=> feat(notifications) add ability to disable specific notifications

config.js, react/features/analytics/functions.js, react/features/base/jitsi-local-storage/setup.web.js, react/features/base/util/iframeUtils.ts, react/features/recent-list/middleware.js
Due to local storage limitations we might end up making the URL huge
when we save the state there. Avoid the issue at the root by never
storing URLs in that case.
Closes: https://github.com/jitsi/jitsi-meet/issues/11567
=> fix(recent-list) do not store room when inside an iframe

react/features/device-selection/actions.js, react/features/device-selection/functions.js
On iOS Safari when the tracks for the previews are created the old ones
are auto destroyed which leads many issues like stop sending media while
the devie selectioin is displayed, error messages, etc.
=> fix(device-selection):iOS Safari disable previews

react/features/device-selection/actions.js, react/features/device-selection/functions.js, react/features/prejoin/actions.js, react/features/settings/actions.js, react/features/settings/components/web/SettingsButton.js, react/features/settings/components/web/SettingsDialog.js, react/features/welcome/components/WelcomePage.web.js
The device selection initialization on the prejoin use case was handled
like the welcome page. This was introducing issues with selecting the
stored devices and not the ones used, enabling the device selection when
it will fail and others.
=> fix(device-selection): Handle properly on prejoin

react/features/base/participants/functions.js, react/features/filmstrip/components/native/Thumbnail.js, react/features/filmstrip/components/web/Thumbnail.js
This is needed for switching between video and avatar when the track's streaming status changes in source-name signaling mode.
=> fix(filmstrip) Add handlers for track streaming status on RN.

react/features/filmstrip/components/native/Thumbnail.js, react/features/large-video/components/LargeVideo.native.js
Fixes an issue where video on large-video is not being rendered when there is no filmstrip, i.e., there is only 1 remote participant in the call with source-name signaling enabled. Also do not show the screensharing indicator on the camera thumbnail when a virtual SS tile is created for the local screenshare.
=> fix(multi-stream) RN Add listeners for track streaming status updates on large-video.

android/app/src/main/res/values/styles.xml
They "force" a dark mode but we already have a dark palette, so avoid
the system overriding the base colors.
Before:
After:
=> fix(android) fix incorrect colors on MIUI devices

react/features/base/conference/middleware.web.js
When there is a password and lobby enabled, participants cannot enter password as the display name is stealing the focus.
When there is just password set the same field steals the focus from the password prompt.
=> feat: Fix display name in prejoin stealing focus.

lang/main.json
A minor wording change to prevent confusion: On logout one is asked whether to stop the conference but the conference is only left by the participant.
=> fix(lang): logout question asks to stop the conference

react/features/base/dialog/components/native/BottomSheet.js, react/features/base/dialog/components/native/styles.js, react/features/toolbox/components/native/OverflowMenu.js
In the past we used a PanResponder to detect user gestures in the sheet
to show a reduced version or a full-height version of it, and also to
close it.
There is an obvious conflic between the gestures and scrolling, which
didn't work all that great, but we could live with it.
After reactions were introduced we no longer rendered the 2 different
heights, so that functionaligy stopped being used but the PanResponder
still remained there.
This commit removes it completely and sets a max height of 75% on any
BottomSheet, so any tap outside will close it.
=> fix(rn,bottom-sheet) fix scroll

react/features/video-layout/functions.any.js
The documented behavior is that it would disable auto-switching to it,
but users would still be available to toggle it.
This change restores that behavior. If the user has selected a layout
that will be preferred before cheching for this setting.
Ref: https://community.jitsi.org/t/how-to-disable-titleview/115093
=> fix(video-layout) fix usage of disableTileView

react/features/base/util/parseURLParams.js
After https://github.com/jitsi/jitsi-meet/pull/11607 we might call it
with a string. Be nice and accept that in addition to URL objects.
=> fix(util) fix parsing strings in parseURLParams

conference.js
If the audio-only mode is automatically disabled when user starts a screenshare while in audio-only mode, do not unmute the camera track.
=> fix(audio-only) Do not unmute camera when SS is in progress.

lang/main.json, react/features/base/settings/reducer.js, react/features/lobby/middleware.js, react/features/settings/actions.js, react/features/settings/components/web/SoundsTab.js, react/features/settings/functions.js
This adds the option to mute the knocking sound effect when a user enters the lobby on the SoundsTab.
=> feat(settings): add option to mute lobby knocking sounds

conference.js, react/features/external-api/subscriber.js
Specifically: display-name, email and avatar. These are the most common
ones, and the ones currently used by Spot for example.
=> fix(external-api) fix error if setting some options too early

react/features/rtcstats/middleware.js
This PR prevents sending the video type for audio tracks. Why does this happen? because audio tracks sometimes have their videoType set to 'camera' (the default value for video type) and this ends up in the rtcstats redshift database as 'audio/camera' polluting our data.
=> fix: Do not send the videoType for audio tracks

connection.js, modules/UI/authentication/AuthHandler.js, react/features/authentication/middleware.native.js, react/features/base/conference/middleware.web.js, react/features/prejoin/components/Prejoin.js
Fix the focus issue by disabling autofocus in case an auth (login, ait
for owner or password) dialog is shown.
Fixes: https://github.com/jitsi/docker-jitsi-meet/issues/1336
=> fix(prejoin) don't hide during auth

react/features/conference/components/native/Conference.js
Conference is now a navigation screen and we hide it when we navigate to a different screen. 
Only if we leave the conference room, we unmount it.
Based on that, we need to check if the screen is focused or not. This helps us enable or disable PiP.
=> feat(conference): disabled pip if not in conference room

react/features/toolbox/components/web/Toolbox.js, react/features/virtual-background/components/VirtualBackgroundDialog.js
In multi-stream mode, both camera and desktop streams are available at the same time. Virtual backgrounds can be applied to the camera stream while screensharing is in progress.
=> fix(Toolbox) Render the virtual background button in multi-stream mode.

react/features/base/react/components/native/Button.tsx, react/features/base/react/constants.js, react/features/participants-pane/components/breakout-rooms/components/native/AutoAssignButton.js, react/features/participants-pane/components/breakout-rooms/components/native/styles.js
1. react-native-paper button has a really bad underlay color when it's pressed and there is no way of escaping it. 
2. For TERTIARY type, we now return a TouchableRipple that has no ripple color when pressed. 
https://user-images.githubusercontent.com/26413496/177955952-db0bd5ff-fcdc-442b-96e0-9eff25423c4d.mp4
=> feat(base/native/button): TERTIARY type rework

debian/jitsi-meet-tokens.postinst, debian/jitsi-meet-tokens.postrm, doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example, resources/prosody-plugins/mod_auth_jitsi-anonymous.lua
jitsi-anonymous adds by default handling of previd url param, which allows websocket resumption.
=> feat: Moves to use jitsi-anonymous by default.

react/features/conference/components/native/styles.js
When pressed, ripple background didn't fill button's container because of the extra padding.
=> feat(conference): removed padding from invite button

react/features/etherpad/components/SharedDocumentButton.web.js
Specially when we oopen it, mouse tracking will no longer work, so it
would remain open.
=> fix(etherpad) close menu when opening / closing document

react/features/dynamic-branding/functions.any.js
The configuration is not stored in Redux by the time we try to fetch it,
so use the global on Window, which will.
=> fix(dynamic-branding) fix loading on web

react/features/base/participants/actions.js, react/features/base/participants/subscriber.js
With multi-stream enabled, we shouldn't hear a "participant left" sound when the presenter stops sharing. 
Ref: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/participants/middleware.js#L258 
Add `isVirtualScreenshareParticipant` field to the `PARTICIPANT_LEFT` action and ensure it is passed as `true` when a virtual screenshare participant is scheduled to be removed.
=> fix(screenshare) disable sound when presenter stops sharing

doc/debian/jitsi-meet/jitsi-meet.example
Add mime.type mapping for wav files so Firefox supports playback of these sounds.
Addresses issue: #11860
=> Add mime.type mapping for wav files.

config.js
The current version of the client supports it, the flag is meant just to recognize older versions.
=> feat: Always enable receiveMultipleVideoStreams.

react/features/base/participants/functions.js, react/features/filmstrip/functions.any.js
This fixes a case where duplicate SS tile appears when SS ep is the dominant speaker and all the active speakers are currently visisble.
=> fix(filmstrip): Remove SS ep from list of active speakers.

react/features/old-client-notification/functions.js
Bumped to catch old macOS versions which were not signed and thus did
not have autoupdater working (ie. everything older than
https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2021.11.2)
=> feat(old-client-notification) bump notice for anything older than 2022

package-lock.json, package.json, react/features/base/jitsi-local-storage/setup.web.js
In certain scenarios(when the iframe's domain is the same as the parent page)
the jitsiLocalStorage key from local storage is
included in the serialized local storage and then
propagaded to the parent page. This way we end up with recursion which
grows the localStorage infinitely.
Depends on https://github.com/jitsi/js-utils/pull/58!
=> fix(externalStorage): Infinitely growing.

ios/Podfile.lock, package-lock.json, package.json
This fixes the Android build because the old version depended on fbjs
wiithout actually listing it as a dependency.
=> chore(deps) react-native-watch-connectivity@latest

react/features/base/modal/components/JitsiKeyboardAvoidingView.js, react/features/base/modal/components/JitsiScreen.js, react/features/base/modal/components/JitsiScreenWebView.js, react/features/chat/components/native/Chat.js
1. Renamed prop that takes care of dismissing keyboard inside navigation screens.
2. Fixes #11931
=> feat(base/modal): renamed prop and fixed scroll inside webview

modules/API/API.js, modules/API/external/external_api.js, react/features/notifications/actions.js
This allows IFrame API users to push custom notifications. Example usage:
```javascript
api.executeCommand("showNotification", {
title: "Recording still in progress",
description: "Please stop the recording before leaving the room in order to save it.",
});
```
or with custom notification type and timeout:
```javascript
api.executeCommand("showNotification", {
title: "Recording still in progress",
description: "Please stop the recording before leaving the room in order to save it.",
type: "warning",
timeout: "sticky",
});
```
Example use case: https://community.jitsi.org/t/questions-regarding-the-new-localrecording-feature/115339/14?u=shawn
=> feat(external-api) Add command to show custom in-meeting notification

react/features/base/conference/middleware.web.js, react/features/screen-share/actions.js, react/features/screen-share/functions.js
ShareAudioDialog passes undefined when the user hits continue in the share audio demo modal. Toggle state of audio-share based on the current state of audio share in that case.
=> fix(audio-share): Fix audio-only SS in multi-stream mode.

react/features/base/config/reducer.ts, react/features/recording/components/Recording/StartRecordingDialogContent.js
Overwrite the new flag with the old one only if the new one is not set
Fix hideStorageWarning config
=> fix(config) Fix recording config backwards compatibility

react/features/base/react/components/web/Switch.tsx
The additional component is needed because the dialog is shared between native and web
=> ref(ui-components) Replace Recording dialog switch with new component

react/features/base/conference/middleware.web.js, react/features/base/tracks/middleware.js
Guests trying to screenshare see the notification but also the dialog for choosing content.
=> fix: Applies AV moderation checks on screen sharing with multistream on.

react/features/remote-control/subscriber.js
The remote control controller events were sent for the camera
participant instead of the screen sharing one.
=> fix(remote-control): when multistream is enabled

react/features/settings/components/web/SettingsDialog.js
It used to only contain 3 sets of options, so we'd check if any of them
were set before showing it, but it now contains more options, so always
show it if the user requested it.
=> fix(settings) fix not showing the more tab

react/features/face-landmarks/createImageBitmap.js
The polyfill returns an Image object instead of an ImageBitmap. The
latter has a close method, however, which we call.
Make sure we provide a dummy close method to avoid errors.
=> fix(face-landmarks) fix createImageBitMap polyfill on Safari 14

react/features/recording/components/Recording/StartRecordingDialogContent.js
The web and mobile Button components are not implemented the same way
and this came to bite us.
This is a stopgap fix, the real fix needs to be to make them have
exactly the same shared props and behavior.
=> fix(dropbox) fix incorrect button labels and click on web

react/features/participants-pane/components/breakout-rooms/components/native/AddBreakoutRoomButton.tsx, react/features/participants-pane/components/breakout-rooms/components/native/AutoAssignButton.tsx, react/features/participants-pane/components/breakout-rooms/components/native/LeaveBreakoutRoomButton.tsx, react/features/participants-pane/components/breakout-rooms/components/native/styles.js
Additionally refactoring to TypeScript and using the new button component. Also refactoring the add breakout room and auto assign buttons to TypeScript.
=> fix(participants-pane): leave breakout room button appearance

react/features/base/participants/functions.ts
Fixes a case where re-sorting doesn't happen even when dominant speaker is currently not visible.
=> fix(fimstrip): Do not re-sort the active speakers if dominant speaker is visible.

config.js
There is a missing comma in `toolbarButtons`  in `config.js`. Normally this line is commented but when it's uncommented, the UI fails.
=> fix: add a missing comma in json list

config.js, react/features/base/config/configType.ts, react/features/rtcstats/middleware.js
This PR fixes two typos in the poll interval variable names.
Additionally it increases the default value from 1s to 10s to avoid frequent polling if the default fallback value is used.
=> fix(rtcstats): Fix rtcstats poll interval typo and increase default value

config.js
Updated the rtcstats poll intervalls in the comments of config.js, as I overlooked that suggestion in PR12024 before merging it.
=> update(rtcstats): adjusted poll intervals in comments to match default value

react/features/rtcstats/middleware.js
As pointed out in PR12024 I forgot to update yet another default value in the comments in PR12031.
Hopefully I got them all now.
=> update(rtcstats): fix one more left over comment around poll intervall

react/features/video-layout/subscriber.js
The remote screen shares stored in redux were not updated when follow
me is active. Therefore the receiver constraints were not correct.
=> fix(follow-me): SS not visible

react/features/polls/components/native/PollAnswer.tsx
For some reason, on this screen, Switch thumbColor takes the default android green color.
Changed it to white to match the other screens where it is used.
=> feat(polls/native): added thumbColor for android

react/features/base/premeeting/components/web/PreMeetingScreen.js, react/features/lobby/components/native/LobbyScreen.js, react/features/prejoin/components/Prejoin.native.tsx
The room name could be a UUID and the conference display name an actual
name, using the subject.
=> fix(prejoin) use the conference display name instead of the room name

config.js, react/features/base/logging/JitsiMeetLogStorage.ts, react/features/rtcstats/RTCStats.js
With this commit JS console logs can optionally be sent to the RTCstats server
for storage and processing.
The functionality is off by default and can be enabled by setting to `true` the
config.js option
config.analytics.rtcstatsStoreLogs: false // off by default
Obviously, if rtcstats is disabled/not configured nothing will be sent to the
rtcstats backend, even if this setting is set to `true`.
This commit also adds a config.js option that can be used to disable sending the
logs back to callstats:
config.callstatsStoreLogs: true // on by default
Obviously, if callstats is disabled nothing would be sent in the first place,
but if callstats is enabled and this new configuration parameter is set to
`false`, then callstats will be kept active but no logs will be sent to callstats.
=> feat(logging): Store JS console logs in RTCStats.

config.js, react/features/rtcstats/RTCStats.js, react/features/rtcstats/middleware.js
This PR exposes RTCstats sendSdp option via config.js.
Only if rtcstats is enabled via config.js this setting will take affect. It allows to decide if SDP from all API calls on the endpoints to be send to the rtcstats-server, or not if bandwidth and storage space are a concern.
The default value is: false - which means by default SDP does not get send to the rtcstats-server.
=> feature(rtcstats): expose sendSdp as config option

resources/prosody-plugins/mod_av_moderation_component.lua, resources/prosody-plugins/mod_conference_duration_component.lua, resources/prosody-plugins/mod_speakerstats_component.lua
When using directly log( the log lines come from `general` not from the module itself.
`Aug 29 19:38:08 general	info	Starting speakerstats for conference...`
=> fix: Fixes lua log lines.

react/features/video-layout/functions.any.js
In adcd9a501bfec5b75a6081ee73f845748351179a a call to getCurrentLayout
was introduced, which is not mobile-friendly :-(
=> fix(rn,video-layout) fix mobile

webpack.config.js
Skip type checking, only do it in prod builds (the CI will check those).
Main bundle build times:
- Before: 255101ms
- After: 58463ms
=> fix(build) speed up webpack dev build by 4x 

config.js, react/features/base/logging/JitsiMeetLogStorage.ts
289ece42df8425d9a516df8333fe8ff346898b3a adds a redundant config.js parameter called `callstatsStoreLogs`. The pre-existing configuration option that was not listed in the config.js. This PR removes the redundant config.js parameter and adds the pre-existing configuration parameter in config.js
=> ref(callstats): Removes redundant config.js option.

modules/API/API.js
Add support for local recording to `startRecording` and `stopRecording` commands.
(`recordingStatusChanged` event already supports `mode: "local"`)
=> feat(external-api) start/stop local recording

react/features/large-video/actions.any.js
This is helpful in live streaming scenarios when AUTO_PIN_LATEST_SCREEN_SHARE is disabled and multi-stream is enabled. Dominant speaker's SS tile (if available) will be on stage instead of their camera tile. Fixes https://github.com/jitsi/jitsi-meet/issues/10869.
=> feat(large-video) Show SS on large-video instead of camera tile.

resources/prosody-plugins/mod_muc_lobby_rooms.lua, resources/prosody-plugins/mod_persistent_lobby.lua, resources/prosody-plugins/mod_reservations.lua
@damencho As briefly discussed in DM, I'm attempting to add support for enabling lobby from reservations.
Enabling lobby programmatically brings about 2 complications:
1.  Moderator needs a way to get into the room to admit others, hence the additional support for setting passwords
* password support is optional. Users could also use something like [token_lobby_bypass](https://github.com/jitsi-contrib/prosody-plugins/tree/main/token_lobby_bypass)
2. It is now possible to have lobby enabled with nobody in the main room, and empty rooms get deleted automatically thus terminating the lobby too. I've added the logic to handle this as a separate module (mod_persistent_lobby) because:
a. It is non trivial and makes the reservations module harder to follow
b. It is reasonably standalone and …
=> feat(reservations) start lobby and set password from reservation

react/features/speaker-stats/actionTypes.ts, react/features/speaker-stats/actions.any.js, react/features/speaker-stats/components/AbstractSpeakerStatsList.js, react/features/speaker-stats/functions.js, react/features/speaker-stats/middleware.js, react/features/speaker-stats/reducer.ts
I've noticed a bug where the speaker stats is not sorted in the correct order. We are currently using the `objectSort` function to sort an object by a given callback function. However, insertion order is not always preserved https://stackoverflow.com/a/23202095. 
```
e.g.
const speakers = {
aaaa1234: "Adam",
zzzz1234: "Joey",
12345678: "Larry",
bbbb1234: "Richard",
cccc1234: "Wilson"
}
calling Object.keys(speakers) returns ['12345678', 'aaaa1234', 'zzzz1234', 'bbbb1234', 'cccc1234']
```
The fix is to decouple the state used for sorting from the state that is holding the new speaker stats from LJM. This change will still use the same compareFunction that was originally used for getSortedSpeakerStats.
=> fix(speaker-stats) decouple sort order from speaker stats

Makefile
- when doing "make" fixes issue of "FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory"
=> fix(build) - increase heap size node for build

react/features/base/ui/components/types.ts, react/features/base/ui/components/web/Button.tsx, react/features/chat/components/web/Chat.js, react/features/polls/components/web/PollsPane.tsx
After we press the chat tab, chat input gets automatically focused. 
This isn't the case for when we press the polls tab. Create a Poll button doesn't get focused.
1. Added autoFocus prop to UI Button component.
2. Set autoFocus default prop to false.
3. Added autoFocus = true to Create a Poll button.
=> feat(base/ui/web): added autofocus prop to button component

ios/Podfile, ios/Podfile.lock, ios/app/app.xcodeproj/project.pbxproj, package-lock.json, package.json
Last to support Plan B.
The method to embed WebRTC has changed to use CocoaPods.
=> chore(deps) react-native-webrtc@1.106.1

config.js
Added config option for enabling Opus DTX flag which used for reduction in the audio traffic, when a participant is silent then the audio packet won’t be transmitted.
=> ref(config): add enableOpusDtx flag

react/features/base/config/configType.ts, react/features/base/config/reducer.ts
VP9 is too resource intensive.
H.264 might be coming back for P2P but we need to fix support for Android first, since it's not available with the default software codec factory.
=> feat(rn,config) default to VP8 on mobile

react/features/base/tracks/actions.ts
Fixes an issue where camera video doesn't get requested by RN clients when the remote ep starts SS first before turning on their camera.
=> fix(multi-stream): Set mediaType to screenshare on SS tracks.

lang/main.json, react/features/base/settings/reducer.ts, react/features/conference/components/native/Conference.js, react/features/conference/components/native/carmode/CarMode.tsx, react/features/settings/components/native/SettingsView.tsx, react/features/toolbox/components/native/AudioOnlyButton.js
1. Added 'Start car mode in low bandwidth mode' switch to Settings screen.
2. And the switch is checked and 'Join in low bandwidth mode' button inside Prejoin screen is pressed, the participant goes straight to Carmode screen.
=> feat(settings/native): start car mode in low bandwidth mode

react/features/base/conference/middleware.web.js
Fixes an issue when external cam as screensharing source fails on Spot with multi-stream enabled.
=> fix(screenshare): Pass _desktopSharingSourceDevice as shareOptions when available

modules/API/API.js, react/features/base/participants/functions.ts, react/features/base/tracks/subscriber.ts
Fixes an issue where 'contentSharingParticipantsChanged' event and 'getContentSharingParticipants' API continue to list IDs of the participants that have already stopped their screenshares.
=> fix(external-api) Remove muted SS tracks from the list of participants currently screensharing

react/features/base/ui/components/native/Button.tsx, react/features/base/ui/components/native/buttonStyles.ts
When tapping one of our native buttons, the transparent active background doesn't cover the full content of its parent.
=> feat(base/ui): fixed native button active style

resources/prosody-plugins/mod_end_conference.lua
From `general error No muc_component specified` to `endconference.meet.damencho.net:end_conference error No muc_component specified`
=> fix: Fix log message.

react/features/base/label/components/web/Label.tsx
Fixes issue where Label styles would take precedence over parent styles (raised hand counter would be gray instead of yellow)
=> ref(label) Convert to function component

react/features/base/dialog/components/native/styles.js, react/features/chat/components/native/MessageRecipient.js, react/features/conference/components/native/styles.js, react/features/mobile/audio-mode/components/AudioRoutePickerDialog.js, react/features/mobile/audio-mode/components/styles.js, react/features/toolbox/components/native/styles.js
1. When toolbox or title bar buttons are pressed, there is an annoying underlay color flickering.
2. Updated colors for audio route picker dialog.
3. First element in audio route picker dialog, when highlighted, must have a border radius just like its container aka bottom sheet modal.
4. Removed underlay color from message recipient cancel icon.
=> feat(toolbox/conference/audio-mode/chat/native): UI fixes and updates

react/features/base/modal/components/JitsiScreen.js, react/features/base/modal/components/styles.js, react/features/mobile/navigation/components/settings/components/SettingsNavigationContainer.js, react/features/settings/components/native/SettingsView.tsx
1. Reverted scrollEnabled check inside JitsiScreen.
2. Removed 'Modal' ColorSchemeRegistry because it is no longer used.
3. Disabled forced keyboard dismiss inside SettingsView.
4. Removed extra bottom padding from SettingsView when it is rendered inside WelcomePage.
5. Enabled scroll bounce for SettingsView if it's rendered inside WelcomePage( the other tabs have the same behaviour ).
=> feat(settings/native): fixed scroll inside screen

react/features/base/jwt/functions.ts, react/features/toolbox/functions.web.ts
- if no JWT - screen share is enabled
- if JWT but no features mentioned- screen share is enabled
- if JWT has some features but does not contain 'screen-sharing' - screen share is enabled
- if JWT contains an explicit true/false/"true"/"false" value, the value will be considered.
=> fix(screenshare-jwt) Disable screen share based on jwt

react/features/conference/components/web/ParticipantsCount.js
Currently, it is white background with white icon.
Before:
After:
=> fix: Drops participants count white background.

resources/prosody-plugins/mod_persistent_lobby.lua
Main room was not being properly destroyed -- it was only artificially triggering the "muc-room-destroyed" event :(
Did a quick test with mod_lobby_autostart and it now appears to do the right thing.
Related community post: https://community.jitsi.org/t/new-prosody-module-to-automatically-start-lobby-and-to-bypass-lobby-with-jwt/116517/46?u=shawn
=> fix(persistent_lobby): properly destroy main room when empty

react/features/recording/middleware.js
Show the start recording notification on jicofo update only. This way
the initiator will be available and we will be able to fetch and display
recording link and send iframe API event.
=> fix(recording): recording link.

ios/Podfile.lock, package-lock.json, package.json
We need @react-native-async-storage at least at 1.17.3 for the React Native SDK to not have peer dependency issues. This is also the version that is actually supporting React Native 0.68
=> chore(deps) @react-native-async-storage 1.17.3

react/features/stream-effects/noise-suppression/NoiseSuppressorWorklet.ts
Disconnecting the input node to the worklet causes the worklet to crash. Adding a guard clause for empty input prevents this.
=> Exit out early if no input data to NoiseSuppressorWorklet

lang/main-ca.json
There is a misspelling in the "joiningTitle" label. "S'està demanat per a entrar a la reunió...", should be "S'ha demanat per a entrar a la reunió..."
=> Misspelling. Update main-ca.json

package-lock.json, package.json
Updated rtcstats to version 9.4.0 to include fixes for SDP logging.
=> chore(deps) @jitsi/rtcstats 9.4.0

react/features/base/flags/constants.ts, react/features/base/settings/components/native/SettingsButton.tsx
`settings.enabled` allows to hide `settings button` in `overflow menu`
=> flag to hide settings button in overflow menu

package-lock.json, package.json
Bumping rtcstats to version 9.4.1 to include a bug fixed needed for SDP logging.
=> chore(deps) @jitsi/rtcstats 9.4.1

debian/control, debian/jitsi-meet-web-config.postinst, debian/jitsi-meet-web-config.postrm, resources/install-letsencrypt-cert.sh
This PR adds suppot for users to use [OpenResty](https://openresty.org) as web-server and don't duplicate "nginxes" by installing additional NginX copy on the user system.
OpenResty, if any, is a bundle of nginx+lua-module+luajit+bunch of lua libraries and so on.
It is very usable for high customisation, so I personally prefer to use it instead of "base" nginx.
(also, if any, I am not connected with openresty organisation, just an user)
=> (feat) OpenResty Support

react/features/base/flags/constants.ts, react/features/mobile/picture-in-picture/components/PictureInPictureButton.js
show picture-in-picture button while share screen to allow compact JitsiMeetView
(significant when SDK is embedded in some host app)
=> show picture-in-picture button while share screen 

react/features/recording/components/Recording/LocalRecordingManager.web.ts
Starting chrome 107, the recorder does not record any data if the audio stream has no tracks
To fix this we create a track for the local user (muted track)
=> fix(recording) Fix local recording

ios/fastlane/Fastfile
Since we no longer use bitcode we need to upload them when we build the app.
=> fix(ios) fix uploading symbols to Crashlytics

react/features/connection-stats/components/ConnectionStatsTable.tsx
=> fix(connection-stats) Do not display max enabled resolution on SS tile.

config.js, react/features/base/config/configType.ts, react/features/toolbox/components/web/EndConferenceButton.tsx, react/features/toolbox/components/web/HangupContextMenuItem.tsx, react/features/toolbox/components/web/HangupMenuButton.tsx, react/features/toolbox/components/web/LeaveConferenceButton.tsx, react/features/toolbox/components/web/Toolbox.tsx
The previous hangup button used to trigger `toolbarButtonClicked` when 'hangup' is specified in `buttonsWithNotifyClick` config, but this no longer happens when using the new hangup menu buttons.
This change adds support for that to on new variant of the button. 
~~For simplicity and consistency with the other hangup mode, the event is currently triggered on hangup menu button in the toolbar (not on the actual End/Leave Meeting buttons in the popup since that requires a much bigger change).~~ (Click events for buttons within hangup menu now also implemented)
Related community post: https://community.jitsi.org/t/new-end-leave-meeting-buttons-not-covered-by-buttonswithnotifyclick/117283?u=shawn
=> feat(toolbox) notify click for new hangup menu button

resources/prosody-plugins/mod_end_conference.lua
Fixes https://github.com/jitsi/jitsi-meet/issues/12562 
At present, a single lua file is used as both the host module and the component implementation. This means that:
1. `module:add_identity` is called twice, once correctly and the second with the wrong name i.e. `endconference.endconference.meet.domain.com`
2. The remaining logic is also called twice with one of the runs terminating early and triggering the confusing "no muc_component specified" error.
This PR works around this by using the presence of `end_conference_component` var to distinguish between the two runs. This resolves the confusing error, but also makes it more obvious what is going on.
The downside to this approach is that the feature will not work if someone forgets to add `end_conference_component` to Virtualhost :( …
=> refactor(end-conference): distinguish component vs host module logic

react/features/base/participants/functions.ts, react/features/base/participants/middleware.ts, react/features/base/participants/types.ts
We only really want to know if a participant is Jigasi for displaying a specific icon, for all other intents and purposes it's a normal participant.
=> fix(participants) don't treat Jigasi like a fake participant

react/features/base/ui/components/web/Dialog.tsx, react/features/base/ui/components/web/DialogTransition.tsx, react/features/remote-control/components/RemoteControlAuthorizationDialog.js, react/features/shared-video/components/web/SharedVideoDialog.tsx
Since we unmount the dialog after a timeout because of an animation we
need to cancel the timeout in case we need to render new dialog.
Otherwise the actual hiding can be executed after we render the new
dialog.
=> fix(dialog): cancel hide timeout on openDialog

react/features/filmstrip/components/web/Thumbnail.tsx, react/features/filmstrip/components/web/VirtualScreenshareParticipant.js
- show black tile over thumbnail in filmstrip when participant is pinned (staged) or is on large screen and current layout is not TILE view
- [] define final value for opacity (now set to 0.8)
=> feat(thumbnail,filmstrip) - show tile blackend thumbnail for staged participant

ios/sdk/src/picture-in-picture/PiPViewCoordinator.swift
Currently, when using PiP mode, the initial position (`initialPositionInSuperView`) cannot be changed, which is a regression compared to the previous behaviour.
Fixes #12446
=> Changes initialPositionInSuperView constant to variable.

react/features/subtitles/middleware.ts
This PR fixes transcriptions not being displayed.
As of version 2.0.7830 of Jitsi, one can choose the transcription source language when enabling subtitles.
Jigasi would send transcriptions in that source language, by specifying a `language` key in the result JSON.
However, there is a check that makes sure the Jitsi interface is the same language as the transcription result.
This causes an issue where, if the user chooses a transcription language that is not the same as their UI language, the subtitles will not show up, without any error message.
This PR removes the language check, which fixes the display of subtitles.
Please let me know if there is anything I can improve.
This PR is part of a project with @openfun to improve the accessibility of its videoconference platforms.
=> fix: always display transcription

.devcontainer/devcontainer.json, webpack.config.js
Say you need to do a quick UI fix / test. Use a code space!
Just create one with no options, the good defaults are set.
After is has fully booted and npm is done installing all you need to do is `make dev`
From the ports tab (or the notification that shows up) you can open the public URL which has a redirected port.
Voila!
=> misc(GitHub) add dev container config

conference.js
I've noticed in the case of pressing the "v" shortcut or camera button in rapid succession, we call `muteVideo` multiple times. https://bbgithub.dev.bloomberg.com/bb-room/jitsi-meet/blob/develop/conference.js#L1053 
If the local video hasn't been created yet, https://bbgithub.dev.bloomberg.com/bb-room/jitsi-meet/blob/develop/conference.js#L1091 will try to create another local track while one is already in progress. 
**From a user perspective, if two local camera tracks are created, they might still see their device's camera light on even though visual indicators show it is muted.**  
---
Flow of pressing the "v" shortcut to toggle camera:
VideoMuteButton#_onKeyboardShortcut -> AbstractButton#_onClick -> AbstractVideoMuteButton#_handleClick -> VideoMuteButton#setVideoMuted -> …
=> fix(video-mute) prevent multiple camera track creation

react/features/e2ee/middleware.ts
When hanging up, the conference transitions to undefined, so we should skip all processing related to setting up listeners for a new conference.
=> fix(e2ee) avoid running middleware when there is no conference

package-lock.json, package.json
Bumping rtcstats dependency to version 9.5.1 to include fixes throwing exceptions when SDP logging is turned on.
=> chore(deps): bumped rtcstats 9.5.0 -> 9.5.1

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
This commit allow to override integer configuration like this one:
```
JitsiMeetConferenceOptions options =
new JitsiMeetConferenceOptions.Builder()
.setConfigOverride("resolution", 1080)
.build();
```
=> fix(config) allow to override integer config

react/features/base/config/middleware.ts, react/features/base/config/reducer.ts
We're getting some no-video problems after the migration to Unified Plan (before it was only working for same plan clients FWIW).
It was already disabled on Android, so the same in iOS while we figure this out.
=> fix(rn) temporarily disable P2P

react/features/face-landmarks/FaceLandmarksDetector.ts
Previously the face-landmarks would not work on browsers that do not support ImageCapture
=> fix(face-landmarks): check for track state only if image capture is not polyfill

react/features/base/participants/functions.ts, react/features/filmstrip/actions.web.ts
Add SS tiles to the number of participants in scroll calculations. This
fixes an issue where the scroll is not displayed if there is a SS tile
and only part of 1 tile is overflowing.
=> fix(filmstrip): scroll

.github/workflows/ci.yml
Warning is: Node.js 12 actions are deprecated. For more information
see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: actions/checkout@v2
=> chore(ci): update to checkout@v3 to fix node12 warnings

react/features/base/lastn/middleware.ts, react/features/base/participants/reducer.ts, react/features/video-layout/actionTypes.ts, react/features/video-layout/actions.any.ts, react/features/video-layout/middleware.any.ts, react/features/video-layout/reducer.ts
The action type used in multi-stream mode is `VIRTUAL_SCREENSHARE_REMOTE_PARTICIPANTS_UPDATED` and `sortedRemoteVirtualScreenshareParticipants` has the updated list of shares.
=> ref(participants) Remove sortedRemoteScreenshares used by legacy SS.

config.js, react/features/base/config/configType.ts
capScreenshareBitrate and setScreenSharingResolutionConstraints are no longer valid.
=> fix(config): Remove unused config values.

config.js, react/features/base/config/configType.ts
Client (receiver constraints)  and bridge use the new b/w allocation strategy by default.
=> fix(config) Delete deprecated config.

css/_subject.scss
Use "monospace" digits in the `.subject-timer`. 
Given fonts that support this, the browser renders '1' and '8' at the same width.
The effect is that the ticking seconds stop resizing the timer on screen: ":21" and ":22"  take up the same space instead of wobbling 1+ pixel.
Before:
https://user-images.githubusercontent.com/59080/212181023-5b78419a-aa76-412a-a3f9-e5fab2f2f340.mov
After:
https://user-images.githubusercontent.com/59080/212181034-5785ea78-05fa-4ac5-a693-7869d82c66a5.mov
=> fix: stop ticking timer resizing its container

react/features/toolbox/components/web/Toolbox.tsx
Closes https://github.com/jitsi/jitsi-meet/issues/12739
This happens on smaller machines, the fix/hack I've added is to restrict the height of the popover and add scroll to it.
=> Fixed overflow of popover

modules/API/external/external_api.js
Fix local recording saving not working after IFrame sanbox introduciton. The allow-downloads flag was missing.
=> Fix local recording after IFrame sandboxing

react/features/toolbox/components/web/Toolbox.tsx
endConferenceSupported check now also takes into account moderator status.
Ref: https://community.jitsi.org/t/end-conference-unnecessary-dialog-for-non-moderator/120873?u=shawn
=> fix(toolbox): do not show hangup menu for non-moderators

css/_toolbars.scss, css/_variables.scss
Use same color for hangup button and hangup menu button (https://github.com/jitsi/jitsi-meet/pull/12850#issuecomment-1413442663).
=> fix(toolbox): consistent color for hangup buttons

react/features/participants-pane/components/web/ParticipantsCounter.tsx
close issue: https://github.com/jitsi/jitsi-meet/issues/12878
This occurs when the screen width and height become smaller than 368 x 619 or badge number become two or more digits, causing the badge value to overflow the badge container. To address this issue, I made the badge more responsive for larger numbers and smaller devices.
Before: 
After fix:
=> Fixed style of participant badge

ios/sdk/src/JitsiMeetView.m
UIView has 2 designated initializers: initWithFrame and initWithCoder, which means either of them is going to be called, whatever the constructor.
THus overriding init will cause creating new (and unnecessary) observers.
Ref: https://community.jitsi.org/t/duplicate-delegate-calls/121051/6
Fixes: https://github.com/jitsi/jitsi-meet/issues/12892
=> fix(ios) avoid getting duplicated SDK events

react/features/base/ui/components/web/ContextMenu.tsx, react/features/virtual-background/components/UploadImageButton.tsx, react/features/virtual-background/components/VirtualBackgroundDialog.tsx
Before context menu
After
Before select background dialog
After
if you merge this please rebase the commits do not squash them!
Peace ✌️
=> Small height screen fixes

react/features/video-quality/subscriber.ts
When mulltiple videos are pinned to the stage filmstrip, the expectation is that the bridge will forward all the videos even if they are of lower quality. For this, the video sources need to be added to selectedSources instead of onStageSources.
=> fix(video-quality) Add pinned participants to selectedSources.

react/features/participants-pane/components/web/ParticipantsCounter.tsx
Before (Badge is not circular)
changed the padding top from '2px' to '1px' to make the badge circular.
After
=> ParticipantsCounter badge Style Changed

react/features/authentication/actions.any.ts, react/features/authentication/components/web/LoginDialog.tsx
As proposed in #11144 fixes: when the reservation system returns http 403 no error is displayed, just "obtaining session-id" is displayed in the dialog box.
=> fix(reservations): fixes errors not being displayed when reservation system returns error.

lang/main.json, react/features/base/components/participants-pane-list/ListItem.tsx, react/features/base/label/components/web/Label.tsx, react/features/base/popover/components/Popover.web.tsx, react/features/base/react/components/web/MeetingsList.js, react/features/base/toolbox/components/ToolboxItem.web.js, react/features/base/toolbox/components/web/OverflowMenuItem.js, react/features/base/toolbox/components/web/ToolboxButtonWithIconPopup.js, react/features/base/toolbox/components/web/ToolboxItem.js, react/features/base/ui/components/web/BaseDialog.tsx, react/features/base/ui/components/web/ContextMenu.tsx, react/features/base/ui/components/web/ContextMenuItem.tsx, react/features/conference/components/web/ConferenceInfo.js, react/features/connection-indicator/components/web/ConnectionIndicator.tsx, react/features/filmstrip/components/web/Thumbnail.tsx, react/features/filmstrip/components/web/styles.ts, react/features/settings/components/web/audio/AudioSettingsPopup.tsx, react/features/settings/components/web/video/VideoSettingsPopup.tsx, react/features/toolbox/components/web/Drawer.tsx, react/features/toolbox/components/web/HangupMenuButton.tsx, react/features/toolbox/components/web/OverflowMenuButton.tsx, react/features/toolbox/components/web/Toolbox.tsx, react/features/video-menu/components/web/LocalVideoMenuTriggerButton.tsx, react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.tsx
Hello,
Here is a pull request to globally improve keyboard navigation:
- the PR improves navigation when popovers, drawers, and dialogs open and hide. For example, now when a Dialog closes, it tries to put back focus on the button that triggered it. I feel we could talk about it more because 1) there is still room for improvement, and 2) maybe my ideas to fix them are debatable :) For example I'm not entirely satisfied with my Popover focus trap solution. I will elaborate more on that soon,
- the PR tries to make every interactive element in Jitsi Meet reachable via keyboard. I'm sure I missed some stuff as I don't fully know the app, but there is already lots of stuff that are improved.
The list of improved stuff for keyboard users:
- Popovers are focused directly on open (instead of …
=> Make (most) UI elements reachable via keyboard

react/features/base/media/components/web/AudioTrack.js
Audio playback for a remote participant doesn't happen when the browser fires an error event on the audio element that the audio track is attached to. 
'[modules/RTC/JitsiRemoteTrack.js] <._containerEventHandler>:  error handler was called for a container with attached RemoteTrack' 
Log an error when that happens and try to re-attach the audio track and execute play on it as a potential fix.
=> fix(AudioTrack): Reattach the track to the audio element on error.

lang/main.json, react/features/chat/components/web/ChatHeader.js, react/features/conference/components/web/Conference.js, react/features/filmstrip/components/web/Filmstrip.tsx, react/features/participants-pane/components/web/MeetingParticipants.tsx, react/features/whiteboard/components/web/Whiteboard.tsx
This doesn't change anything for sighted users, but it can make a noticeable difference for users using a screen reader. Because a screen reader has keyboard shortcuts to jump from heading to heading, a user can quickly scan the content of a webpage or quickly navigate from one part to the other thanks to them.
I didn't add any heading to the "video space" central part of the UI (except when the whiteboard is shown), because I'm not sure there is actual content to announce to screen reader users in this part, but maybe I'm wrong?
Below is a screenshot with the headings list popup of NVDA, a free and open source screen reader on Windows, to show the benefits of adding this. Before this PR, the headings list only contained the headings from Excalidraw when the whiteboard was shown.
_Related …
=> Add headings across the app for easier screen reader navigation

react/features/rtcstats/functions.ts
The previous code was copy/pasted from some other part of the app and didn't include the statisticsDisplayName in the rtcstats display name. This PR fixes the issue.
=> feat: Sends the statisticsDisplayName to rtcstats.

lang/main-es.json
"Parlantes" is not the right translation for "Speakers" in Spanish when referring to the usual electronic audio output device (at least in the non-Latin-American Spanish variants).
Note that the singular "Altavoz" was already correct.
=> fix(lang) update Spanish translation

css/_welcome_page.scss, react/features/base/ui/components/web/Button.tsx, react/features/base/ui/components/web/ClickableIcon.tsx, react/features/base/ui/components/web/ContextMenuItem.tsx, react/features/base/ui/components/web/Dialog.tsx, react/features/base/ui/components/web/DialogWithTabs.tsx, react/features/base/ui/components/web/Tabs.tsx, react/features/video-quality/components/Slider.web.tsx
_Related to https://github.com/jitsi/jitsi-meet/issues/12379_
This takes advantage of the `:focus-visible` polyfill that is already used in the app.
For focus styles that we know we only want to trigger when using the keyboard, use the `.focus-visible` class instead the `:focus` pseudo class.
This allows us to [stop hiding focus styles on dialog close buttons](https://github.com/jitsi/jitsi-meet/commit/a00b534767aaf26fba5199365eff6d039da46a10), something that was not great when navigating via keyboard.
See the new behavior in video, first when using keyboard, then when using the mouse:
https://user-images.githubusercontent.com/221253/221629521-c20a20a0-7ca8-4eb6-a742-1a7477886593.mp4
=> Use focus-visible for some focus styles to fix a11y issues

resources/prosody-plugins/mod_muc_rate_limit.lua
If any handler returns a value (that isn't nil) then processing will halt and that value will be returned.
=> fix: Fixes muc rate limit to fire occupant-pre-join.

conference.js
The broken use-case: 1 moderator (& 1 guest), enables video moderation. A new guest joins and tries to video unmute. A notification is shown and after clicking raise hand we actually create local track and try to unmute server-side (sending iq to jicofo and getting error not-allowed) and everything goes out of sync and when we are allowed to unmute, we send video but the bridge is not forwarding it as we are still muted in jicofo's point of view.
=> fix: Fixes video unmuting in case of av moderation.

conference.js
Fixes a crash which happens after GUM fails without any track previosuly created.
Steps to reproduce:
1. Join a meeting without camera.
2. Disable camera access permissions in the browser.
3. Try to use the camera button.
=> fix(useVideoStream): a crash after GUM failure

react/features/base/participants/functions.ts, react/features/filmstrip/components/web/Thumbnail.tsx
- remove tint on thumbnail if the participant is sharing the screen, in order to be visible for the others and see who is sharing the screen.
=> feat(thumbnail,filmstrip) - remove tint from owner screenshare participants

modules/API/external/external_api.js
Solves #12948
- added parameter to iframe allowing linking to the Jitsi mobile app with user interaction
Currently users will hit an error when trying to click on the button to go to the mobile app when clicking within an iframe.
=> Adding additional parameter to iframe in order to link to the Jitsi mobile application

react/features/base/participants/subscriber.ts
There are cases when participant is left and still we receive a track added. In this occasions for screensharing sources a virtual participant is created for non-existing participant.
=> fix: Returns source names only for existing participants.

react/features/filmstrip/components/native/Thumbnail.js
=> fix(filmstrip): hide screenshare indicator if not screen sharing

react/features/filmstrip/components/native/Thumbnail.js
https://user-images.githubusercontent.com/26413496/228790258-a0c44024-39ee-44de-acf2-bb9e58952eff.mp4
=> fix(filmstrip): show video for screen-share participant in tile view

modules/API/external/external_api.js
By using a sample JaaS example for the IframeApi, there was an error that showed up in the logs on chrome related to webhid.
This is due to the permissions policy in the iframe https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy. By adding hid it will solve this issue and the error won't show up anymore instead this will be the log: `[features/hid] <D4.listenToConnectedHid>:  No hid device found.` 
This error only appears on chrome and other browsers that support webhid, safari for example won't have this problem.
=> fix(webhid, external_api) webhid error showing up in iframe

lang/readme.md
This will help display proper syntax highlight in the codeblocks
=> Set proper language for codeblocks in lang/readme.md

react/features/base/flags/constants.ts, react/features/prejoin/components/native/Prejoin.tsx
Add feature flag to hide the participant name editing field on the prejoin page.
=> feat(react-native-sdk) Add feature flag prejoinpage.hideDisplayName

react/features/conference/components/native/TitleBar.js, react/features/conference/components/native/carmode/TitleBar.tsx, react/features/toolbox/components/native/Toolbox.js
Rethink #13158 
We used to apply pointerEvents, 'box-none', to parent views, this means subviews can be targeted by touch events.
=> feat(conference, toolbox): removed pointer events from parent views

resources/prosody-plugins/mod_jitsi_session.lua
Somewhere along a double encoding for the room names occurred, thus
currently moderation does not work for rooms names which contain non-
ascii charaters like ä etc.
This essentially reverts a6bc51cff1566a8afb5cb29eb74a72da89fc74e5
=> fix: breakout rooms with non-ascii room names

react/features/desktop-picker/components/DesktopPicker.tsx
Fix bug introduced via #12994 where id was changed and "-tab" was appended. Due to this the selected tab was not anymore working and empty object was returned here: https://github.com/dudumanbogdan/jitsi-meet/blob/05da37b56de391e3f67d5919a751a81a4e803d73/react/features/desktop-picker/components/DesktopPicker.tsx#L270
Originally part of #13096 by @dudumanbogdan, but pulled ahead to fix application
window sharing via Electron desktop app.
Fixes: jitsi/jitsi-meet-electron#857
=> fix(desktop-picker): Populate list of desktop app windows to share

ios/app/src/AppDelegate.m
It doesn't actually work on the simulator but it never caused trouble... until iOS 16.4 (or maybe earlier). Disable it.
=> fix(ios) disable CallKit when running in the simulator

react/features/google-api/components/styles.js
=> fix(google-api): native sign out button label on smaller devices

Makefile
Also generalize the lib-jitsi-meet files rule so it can also work with development (unminimized) builds.
Depends on: https://github.com/jitsi/lib-jitsi-meet/pull/2234
=> fix(build) drop unused file

react/features/base/config/functions.web.ts, react/features/base/config/reducer.ts
Local and remote audio levels will automatically be disabled on RN since receiver stats and local audio stats are not supported there.
=> fix(mobile) Do not disableAudioLevels on RN since it uses feature detection now

react/features/rtcstats/RTCStats.ts, react/features/rtcstats/middleware.ts
The mobile app does not exit after the user has left the meeting. This means we need to re-initialize rtcstats every time a user joins a call to be sure we are using the correct deployment information.
=> fix: Reinitialize rtcstats when the config changes

.npmrc, package-lock.json, package.json
lib-jitsi-meet does not bundle xmldom anyway, and we are providing it here. strophe seems to be stuck in a slightly old version which creates spurious security warnings.
=> fix(deps) override xmldom dependency from strophe.js

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
When we refactored the external API to use broadcast actions leave() was changes to use the hangup broadcast action.
This mechanism does not seem to work while onDestroy is getting executed, however.
There is another way to accomplish the same, for the particular case of hangup: to pass empty props to the running RN application. This was the previous behavior too.
This PR introduces a new abort() method on JitsiMeetView, which does exactly that, passes empty props to RN. This allows cleanup to happen and the meeting properly ends when the activity is swipped from the recents list.
Fixes: https://github.com/jitsi/jitsi-meet/issues/13175
=> fix(android) fix JitsiMeetActivity.onDestroy not leaving the room

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
The case where the main room is locked and everyone leaves it to a breakout room and then coming back allows jicofo entering without a password.
=> fix: Allows jicofo entering rooms without requiring a password.

android/build.gradle
Some of our dependencies (most notably WebRTC) have dropped it and we can no longer claim to support API level 23).
=> feat(android) bump minimum API level to 24

ios/Podfile.lock
Fix a crash in Metal rendering: https://github.com/jitsi/webrtc/commit/0c9cc420259790034b308ed2ec1f34a27da56847
=> fix(ios) bump WebRTC version to fix crash

modules/API/API.js, modules/API/external/external_api.js, react/features/whiteboard/actions.any.ts, react/features/whiteboard/functions.ts, react/features/whiteboard/middleware.ts, react/features/whiteboard/types.ts
Hi,
The new API call is added to jitsi "toggleWhiteboard". This API is available only for moderator participants in a meeting. When this method is called, jitsi sends a notification on the whiteboard status change (listen to whiteboardStatusChanged to get these notifications). There are four notifications currently: 
Instantiated - when the whiteboard is instantiated for the first time in a meeting.
Shown - when the whiteboard is shown to a participant user
Hidden - when the whiteboard is closed by a participant user
Reset - when the participant user has left the whiteboard.
=> add toggleWhiteboard to Jitsi API

react/features/base/conference/functions.ts, react/features/base/conference/middleware.any.ts
In case a visitor is promoted to main room and want to join an empty breakout room we want to send conference iq to jicofo.
=> fix: Restore old config for promoted visitors.

conference.js, react/features/base/tracks/functions.web.ts, react/features/prejoin/reducer.ts
If initial gUM fails, retry with 2 separate gUM calls if needed and display the appropriate message in the prejoin page.
=> ref(conference) Simplify track creation.

package-lock.json, package.json, react/features/base/popover/components/Popover.web.tsx, react/features/base/ui/components/web/BaseDialog.tsx, react/features/base/ui/functions.web.ts, react/features/toolbox/components/web/Drawer.tsx
When the toolbox is hidden and due to a ReactFocusLock instance the
focus is returned to the toolbox the whole page scrolls to the toolbox
which is positioned outside of the viewport in the bottom.
Then when the animation for displaying the toolbox is started the
scenario looks like the large video is jumping.
Now we don't return the focus from ReactFocusLock to elements which are
not part of the viewport.
=> fix(large-video): Attempt to fix jumping.

resources/prosody-plugins/mod_measure_message_count.lua
This just counts messages and should not block processing messages. Breaks visitor messages coming from s2s and no session params are available.
=> fix: Fix measure messages.

resources/prosody-plugins/mod_visitors.lua, resources/prosody-plugins/mod_visitors_component.lua
It may happen we receive the disconnect iq after the main room is already destroyed. We now send disconnect on destroy to all vnodes or when receiving disconnect iq per vnode.
=> fix: Fixes notifying vnodes to destroy rooms.

react/features/base/ui/components/web/DialogWithTabs.tsx, react/features/settings/actions.web.ts, react/features/settings/components/web/SettingsDialog.tsx, react/features/settings/components/web/VirtualBackgroundTab.tsx, react/features/settings/functions.any.ts, react/features/settings/functions.web.ts, react/features/virtual-background/components/VirtualBackgroundPreview.tsx, react/features/virtual-background/components/VirtualBackgrounds.tsx
In the case when the user selects a new video device then goes to Virtual Background without saving first, use the newly selected device for the virtual background preview instead of the saved one
=> fix(virtual-background) Use correct video device

ios/Podfile.lock
Regarding the fact that we updated to react native 0.69.9, we also need to update pod dependencies.
=> feat(ios): podfile.lock update

.github/workflows/ci.yml, package.json
Only run lang steps (sort and jsonlint) if there is at least one changed lang file
Run eslint only on the changed files (.js, .ts, .tsx)
=> feat(CI) Improve CI

react/features/base/tooltip/components/Tooltip.tsx, react/features/reactions/components/web/ReactionsMenuButton.tsx
- tooltip was reopening in an inconsistent state(without the tooltip text visible), taking the focus from the reactions popup
- removed duplicate store prop from ReactionsMenuButton
=> fix(reactions-popup) Fix tooltip not closing correctly

react/features/toolbox/actions.web.ts
- clicking toolbox button was keeping focus on toolbox even after mouse move(as focus would only be changed when clicking on some other element), so .toolbox-content-items:focus-within selector was returning a value even when mouse was moved from toolbox
- .filmstrip:focus-within did not seem to ever activate, I replaced with :hover since the intent was probably to keep the toolbox open while filmstrip is hovered
=> fix(toolbox-visible) Fix hiding toolbox

ios/Podfile.lock, package-lock.json, package.json
GCM ciphers are now enabled by default.
=> chore(deps) react-native-webrtc@111.0.1

resources/prosody-plugins/mod_rate_limit.lua
Rate limit to ignore outgoing sessions, otherwise it fails to discover ip and fails with an error.
=> fix(visitors): Fixes rate limit module.

conference.js, lang/main.json, react/features/base/media/actionTypes.ts, react/features/base/media/actions.ts, react/features/base/media/middleware.any.ts, react/features/base/media/reducer.ts, react/features/base/media/types.ts, react/features/base/toolbox/components/AbstractButton.tsx, react/features/base/tracks/actions.any.ts, react/features/base/tracks/functions.any.ts, react/features/base/tracks/functions.web.ts, react/features/base/tracks/middleware.any.ts, react/features/base/ui/components/web/Spinner.tsx, react/features/toolbox/components/AudioMuteButton.tsx, react/features/toolbox/components/VideoMuteButton.tsx, react/features/toolbox/components/web/AudioSettingsButton.tsx, react/features/toolbox/components/web/VideoSettingsButton.tsx, react/features/toolbox/constants.ts, react/features/toolbox/functions.any.ts, react/features/toolbox/functions.web.ts
Adds a spinner to the audio/video mute buttons when there is a pending GUM operation for unmute or the initial track creation:
=> feat(unmute/track creation): pending indicator.

react/features/av-moderation/middleware.ts, react/features/base/tracks/actions.web.ts
When video moderation is on and the participant tries to share their screen show a notification saying the screen sharing is blocked
=> fix(moderation) Show Screensharing blocked notification

conference.js, modules/API/API.js, modules/API/external/external_api.js
Added new nonParticipantMessageReceived event for the iFrame API.
This enables custom messages from prosody to meeting participants using iFrame.
=> feat(external-api) Forward non participant message to iframe

react/features/base/ui/components/web/DialogWithTabs.tsx, react/features/settings/actions.web.ts, react/features/settings/components/web/SettingsButton.ts
=> fix(settings-dialog) On mobile open on the correct tab

modules/UI/videolayout/Filmstrip.js
Fixes the following JS error which prevents the whole page from
rendering:
TypeError: Cannot read properties of null (reading 'offsetHeight')
=> fix(horizontal-filmstrip): JS error.

react/features/base/util/parseURLParams.ts
- `getPropertyValue` calls `parseUrlParam` with the connection URL from store, which is not yet defined
=> fix(prejoin) Check for valid url for prejoin

react/features/recent-list/reducer.ts
In oder to not store the token with the conference in the recent conferences list, store only the "clean" conference URL.
Fixes jitsi/jitsi-meet#13313
=> store only "clean" URLs in recent-list

react/features/chat/components/web/ChatButton.tsx, react/features/embed-meeting/components/EmbedMeetingButton.ts, react/features/feedback/components/FeedbackButton.web.ts, react/features/keyboard-shortcuts/components/web/KeyboardShortcutsButton.ts, react/features/participants-pane/components/web/ParticipantsPaneButton.tsx, react/features/reactions/components/web/RaiseHandButton.ts, react/features/reactions/components/web/RaiseHandContainerButtons.tsx, react/features/reactions/components/web/ReactionsMenuButton.tsx, react/features/screen-share/components/web/ShareAudioButton.ts, react/features/speaker-stats/components/web/SpeakerStatsButton.tsx, react/features/toolbox/actions.web.ts, react/features/toolbox/components/web/FullscreenButton.ts, react/features/toolbox/components/web/LinkToSalesforceButton.ts, react/features/toolbox/components/web/ProfileButton.ts, react/features/toolbox/components/web/ShareDesktopButton.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/functions.web.ts, react/features/toolbox/types.ts, react/features/video-quality/components/VideoQualityButton.web.ts, react/features/virtual-background/components/VideoBackgroundButton.ts, react/features/whiteboard/components/web/WhiteboardButton.tsx
Move visibility logic inside each button
Move click functionality inside each button
Extract getButtons function from Toolbox components to functions file
=> ref(toolbar) Move getButtons to functions

resources/prosody-plugins/mod_muc_meeting_id.lua
=> fix: Drop events if conn is closed while waiting for jicofo.

react/features/base/styles/functions.any.ts, react/features/conference/components/native/styles.ts
This should no longer be necessary since we added it for Android 6 devices a long time ago but we no longer support those.
Fixes: https://github.com/jitsi/jitsi-meet/issues/13514
=> fix(android) remove no longer needed view clipping hack

resources/prosody-plugins/mod_muc_meeting_id.lua, twa/app/src/main/res/xml/shortcuts.xml
https://prosody.im/doc/modules/mod_muc
> Limit on number of rooms in-memory
> Prosody keeps recently active rooms cached in memory for faster access. The size of this cache defaults to 100 rooms and can be configured like this:
> 
> muc_room_cache_size = 100 -- the default
> When a room is pushed out of this cache by other more recently active rooms, its complete state is serialized to storage and removed from memory.
> 
> Public servers may want to monitor and possibly increase this setting if rooms are moved in and out of memory very often.
When room is serialized to storage, room.jicofo_lock is not saved.
https://github.com/bjc/prosody/blob/master/plugins/muc/muc.lib.lua#L1671-L1675
When the room is activated again, jicofo_lock is null and remains locked.
I fixed to save jicofo_lock.
=> Fix jicofo_lock is null when restored from storage

inlang.config.js
> let me know if there is something to be changed in order to merge
I added the `inlang` [IDE extension](https://inlang.com/documentation/apps/ide-extension) to Jitsi Meet. That should make the life of devs easier while developing (extracting and inline annotations).
Extract Messages (translations) via the `Inlang: Extract Message` code action.
See translations directly in your code. No more back-and-forth looking into the translation files themselves.
=> feat: add i18next compatible IDE-extension for i18n handling

resources/prosody-plugins/mod_visitors_component.lua
=> feat: Ignores list of domains when checking for visitors and promotion.

react/features/app/actions.web.ts, react/features/authentication/components/native/LoginDialog.tsx, react/features/base/config/configType.ts, react/features/base/lib-jitsi-meet/functions.web.ts
Loading the config can never fail since it uses SSI and it's checked before page even loads.
=> fix(app) simplify appNavigate on web

modules/UI/videolayout/VideoContainer.js
There was an issue with the screen share in which after changing the virtual background the screen share video tag had a scale with a -1 value, I edited this and added the `!isScreenShare()` condition before it. Now the issue doesn't exists anymore :)
=> #13480 :bug: solved the flip bug in screen share video

react/features/mobile/background/actionTypes.ts, react/features/mobile/background/actions.ts, react/features/mobile/background/middleware.native.ts, react/features/mobile/background/reducer.ts, react/features/mobile/react-native-sdk/middleware.js
=> sdk(react-native-sdk): error fixes

resources/prosody-plugins/mod_auth_jitsi-shared-secret.lua
The same as username and password but ignoring the username. Useful for jigasi and jibri where the instances can use different usernames, but the same shared secret/password.
=> feat: New prosody auth module using shared secret.

android/app/build.gradle
Fix for this crash:
~~~
Fatal Exception: java.lang.IllegalArgumentException: org.jitsi.meet: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
at android.app.PendingIntent.checkFlags(PendingIntent.java:377)
at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:460)
at android.app.PendingIntent.getActivity(PendingIntent.java:446)
at android.app.PendingIntent.getActivity(PendingIntent.java:410)
at com.google.android.gms.common.GoogleApiAvailabilityLight.getErrorResolutionPendingIntent(GoogleApiAvailabilityLight.jav …
=> fix(android) fix crash when pending intent is created without flags

react-native-sdk/android/build.gradle, react-native-sdk/jitsi-meet-rnsdk.podspec
Copy sounds file 
- Add Copy Sounds step to build.gradle
- Include copy sounds step in podspec
_May not be the best solution, but the changes allow to copy the sound files as a part of build/installation process when integrated with a react-native host app._
=> feat(rnsdk) copy sounds files

config.js, modules/API/API.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/base/config/functions.web.ts, react/features/base/toolbox/components/AbstractButton.tsx, react/features/participants-pane/components/breakout-rooms/components/web/RoomParticipantContextMenu.tsx, react/features/toolbox/components/web/Toolbox.tsx, react/features/video-menu/components/web/AskToUnmuteButton.tsx, react/features/video-menu/components/web/ConnectionStatusButton.tsx, react/features/video-menu/components/web/FakeParticipantContextMenu.tsx, react/features/video-menu/components/web/FlipLocalVideoButton.tsx, react/features/video-menu/components/web/GrantModeratorButton.tsx, react/features/video-menu/components/web/HideSelfViewVideoButton.tsx, react/features/video-menu/components/web/KickButton.tsx, react/features/video-menu/components/web/LocalVideoMenuTriggerButton.tsx, react/features/video-menu/components/web/MuteButton.tsx, react/features/video-menu/components/web/MuteEveryoneElseButton.tsx, react/features/video-menu/components/web/MuteEveryoneElsesVideoButton.tsx, react/features/video-menu/components/web/MuteVideoButton.tsx, react/features/video-menu/components/web/ParticipantContextMenu.tsx, react/features/video-menu/components/web/PrivateMessageMenuButton.tsx, react/features/video-menu/components/web/RemoteControlButton.tsx, react/features/video-menu/components/web/SendToRoomButton.tsx, react/features/video-menu/components/web/TogglePinToStageButton.tsx, react/features/video-menu/components/web/VerifyParticipantButton.tsx, react/features/video-menu/constants.ts, react/features/video-menu/types.ts
https://github.com/jitsi/jitsi-meet/issues/13446
* `participantMenuButtonClick` should now listen to the buttons defined here https://github.com/jitsi/jitsi-meet/blob/6e816cafc4f1537f0e0d1f55f3f1aa97d666d71e/react/features/video-menu/constants.ts#L19 on top of the custom ones
* `participantMenuButtonsWithNotifyClick` config should work as its toolbar counterpart, enabling click prevention
=> feat(external-api) extend event to listen to system buttons and add config to prevent execution

modules/API/constants.js
Parsing the API ID happens at import time, which is not great because it also runs when loading the external API file.
In sites with weird URL patterns, such as Angular this will throw an exception.
Ignore parsing errors so it's left undefined. When modules/ is refactored we should look into making this a getter of some sort.
Fixes: https://github.com/jitsi/jitsi-meet/issues/11565
=> fix(api) fix parsing API ID

resources/prosody-plugins/mod_muc_lobby_rooms.lua
Skip any lobby check when the occupant is jicofo.
In case of serverside turn on lobby on room creation we do not check and allow jicofo to join. We check for resource and no is_admin as in default configuration admins is set only for the main muc component.
=> fix: Skips lobby check for jicofo.

ios/app/src/AppDelegate.m, ios/sdk/src/AppInfo.m, react/features/app/components/App.native.tsx
It doesn't work and causes weird failures. We used to disable it in the iOS app, but it's better to move it to JS since any SDK will benefit from it.
=> fix(ios) disable CallKit when running in a simulator

react/features/conference/components/native/Conference.tsx
=> feat(conference): hide lonely meeting exp in tile view

react-native-sdk/index.tsx
The following code is producing TS compilation errors because `flags` is expecting an array.
```
<JitsiMeeting flags={{'recording.enabled': false}} meetingOptions={...} />
```
=> fix(react-native-sdk): Declare JitsiMeeting `flags` prop as an object instead of an array

react-native-sdk/index.tsx
Hello
the problem is that the call remains active if the parent component is destroyed... in my case I need jitsi to manage autonomously the resources no longer needed when the component is closed and then close everything.
Sincerely
=> Rn jitsi sdk component unmount close

react-native-sdk/index.tsx
=> (react-native-sdk) Makes `flags` and `eventListeners` props optional

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastEvent.java, react-native-sdk/index.tsx, react/features/base/conference/actionTypes.ts, react/features/conference/components/native/Conference.tsx, react/features/mobile/external-api/middleware.ts, react/features/mobile/react-native-sdk/middleware.js
This allows us to perform actions when the user focuses/blurs the conference. For example, navigating to the chat or participants list will send `CONFERENCE_BLURRED`. Navigating back to the conference will trigger `CONFERENCE_FOCUSED`.
This is useful, for example, if you want to lock the app screen orientation to Portrait except when the conference screen is in focus.
=> (react-native-sdk) Adds `CONFERENCE_FOCUSED` and `CONFERENCE_BLURRED` events to the external and RN api

react/features/conference/components/AbstractInsecureRoomNameLabel.tsx, react/features/prejoin/components/web/Prejoin.tsx, react/features/prejoin/functions.ts, react/features/welcome/components/AbstractWelcomePage.ts
Wrap the logic in a function that also checks the existence of a feature flag on mobile in addition to the config value.
Ref: https://github.com/jitsi/jitsi-meet/issues/13603#issuecomment-1662086531
=> feat(unsafe-room-name) unify logic

react/features/app/actions.native.ts
- Create the tracks early, or there will be on audio on iOS on the first unmute this includes the unsafe room name screen
- Skip the unsafe room screen if prejoin is disabled, like web
=> fix(rn, appNavigate) make sure tracks are created before prejoin

config.js, react/features/base/config/configType.ts, react/features/base/ui/constants.web.ts, react/features/filmstrip/functions.any.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/video-layout/actions.any.ts, react/features/video-layout/functions.any.ts
- show fixed number of toolbar buttons in toolbar (including custom buttons) instead of sending to overflow menu
before:
after:
=> chore(tileview) Add config for disabling tileview

react-native-sdk/jitsi-meet-rnsdk.podspec
Fix for Issue #13705 causing the "Copy Sound Files" Phase to fail with a nonzero exit code when attempting to Archive a project.
=> Fix: Issue #13705 - "Copy Sound Files" Phase failing on iOS Archive

react/features/base/jitsi-local-storage/setup.web.ts
When using useHostPageLocalStorage on the iframe api and local storage
is not throwing error we were writting the passed data to the original
local storage and then switching to the dummy local storage from
jitsiLocalStorage.
=> fix(jitsi-local-storage):Is empty after reload

package-lock.json, package.json, react/features/base/i18n/i18next.ts
i18next-xhr-backend is not maintained any more and [superseded](https://github.com/i18next/i18next-xhr-backend/issues/348#issuecomment-663060275) by i18next-http-backend.
=> fix(i18next): use i18next-http-backend and fix ts-ignore

react/features/base/tracks/loadEffects.native.ts, react/features/base/tracks/loadEffects.web.ts
This PR fixes a typos in JSDOC comments.
=> docs: fix typo in jsdoc comment

modules/UI/videolayout/VideoLayout.js, react/features/filmstrip/middleware.web.ts
- fixed case when localFlipX was taken from store on it`s value update, before the new value was set into store - so always taking the previous value instead of updated one
=> fix(localFlipX) Fix localFlipX for large video

react/features/video-menu/components/native/RemoteVideoMenu.tsx
This matches the logic in video-menu/components/web/ParticipantContextMenu.tsx (see also https://github.com/jitsi/jitsi-meet/commit/d655acd)
=> fix(video-menu) hide Grant Moderator inside breakout rooms on native

modules/API/external/external_api.js
New functions to allow for devs to query for array of commands/events that is supported in current version of the API.
Also makes it possible to programmatically check for support of a command and fallback to some alternative if not yet supported.
Related discussion: https://github.com/jitsi/jitsi-meet/issues/11985#issuecomment-1208018962
=> feat(external-api) Add functions to query supported commands/events

resources/prosody-plugins/util.lib.lua
Fix closing of identity tag opened at line 215.
It was closed only if `creator_user` was present. This caused any prosody module following `mod_presence_identity` to add children nodes to `identity` instead of the root `presence` node (in the absence of the `creator_user` property).
=> Fix missing closing tag for identity node in presence stanza

react/features/conference/components/native/Conference.tsx
The auto-knock process is started by the lobby middleware.
=> fix(rn,conference) avoid starting to knock twice

config.js
Example config is invalid JS due to typo and could confuse new users. E.g https://community.jitsi.org/t/problem-with-lobby/126890?u=shawn
=> fix(config): missing colon in example for lobby config

css/_reactions-menu.scss, css/_videolayout_default.scss, css/_welcome_page.scss, css/deep-linking/_mobile.scss, react/features/base/ui/constants.web.ts, react/features/chat/components/web/Chat.tsx, react/features/deep-linking/components/DeepLinkingMobilePage.web.tsx, react/features/invite/components/dial-in-summary/web/DialInSummary.tsx, react/features/participants-pane/components/web/ParticipantsPane.tsx, react/features/settings/components/web/audio/AudioSettingsContent.tsx, react/features/settings/components/web/video/VideoSettingsContent.tsx, react/features/toolbox/components/web/Drawer.tsx, react/features/toolbox/components/web/OverflowMenuButton.tsx, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/constants.ts
This PR fixes a number of layout issues with the "Chrome for Android" browser. The issue comes from a lot of the UI using `vh` unit to determine window height. This works for all desktop browsers, but on "Chrome for Android" there's an address bar too. As you can see in the screenshots below, this doesn't calculate well and causes issues such as this https://github.com/jitsi/jitsi-meet/issues/13808 .
The fix (since this is now properly supported in browsers) is to use `dvh` instead, which takes the address bar into account.
This seems to work well from what I can see, but as this is my first PR (hurray!), perhaps a quick test would be in order (by someone other than me). 
<details>
<summary>Screenshots of the (now fixed) problem here:</summary>
</details>
<details>
<summary>Screenshot of …
=> fix: Mobile browser fixes (Chrome for Android), changing "vh" to "dvh" for all layout

android/app/src/main/java/org/jitsi/meet/MainActivity.java, react/features/app/components/App.native.tsx
Our app has had it disabled for quite a while, it makes sense the SDKs do that too.
Fixes: https://github.com/jitsi/jitsi-meet/issues/13800
=> feat(android) disable ConnectionService by default

ios/Podfile, ios/Podfile.lock
We get JitsiWebRTC transitively through the react-native-webrtc Pod now.
=> fix(ios) remove duplicate dependency

resources/prosody-plugins/token/util.lib.lua
This allows mod_token_verification to be used with token missing room claim (firebase) and jitsi tokens with the claim.
=> feat: Updates for jwt when room claim is not required.

resources/prosody-plugins/mod_muc_flip.lua, resources/prosody-plugins/mod_muc_lobby_rooms.lua
An issue where a livestreaming is started for a second time in a meeting with lobby turned on.
=> fix: Fixes skipping the lobby for two times in a row for jibri.

resources/prosody-plugins/mod_muc_breakout_rooms.lua
When timer is set by breakout_room_jid, if breakoutroom is removed, earlier set timer can not find mainroom. And mainroom's broadcast_timer is never set to nil. Then no other message can be broadcasted, since broadcast checks whether a timer has been already set. 
If all timer functionality is set by main_room_jid, mainroom can still be found.
=> #13914 BreakoutRoom Raise Condition In Timer

lang/main-tr.json
The Turkish translation of the "adjust for" is "ayarla". It was misspelled as "ayala".
=> correction of incorrect translation of the word ayarla

conference.js, modules/UI/UI.js, react/features/base/tracks/functions.any.ts, react/features/base/tracks/middleware.web.ts
=> feat(track-state): Log on add/remove/mute/owner.

react/features/base/participants/actionTypes.ts, react/features/base/participants/actions.ts, react/features/base/participants/reducer.ts, react/features/conference/middleware.any.ts
Fixes: https://github.com/jitsi/jitsi-meet-sdk-samples/issues/175
=> fix(conference) clear raised hands when conference changes

config.js
Following the discussion from https://github.com/jitsi/jitsi-meet-react-sdk/issues/36, `defaultLanguage` does work when passed from the configOverwrite object, although it's whitelisted, but it would be best to use `lang` instead.
=> fix(language/config) deprecate defaultLanguage

react/features/mobile/navigation/screenOptions.ts, react/features/settings/components/native/SettingsView.tsx
=> feat(settings/native/android): Fixed scroll inside conference settings screen

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/base/connection/actions.any.ts
There might be cases where we'd want to enforce it.
=> feat(config) add ability to prefer BOSH over WebSocket

react/features/whiteboard/functions.ts
A simple modification in the Whiteboard Room id computation to avoid using the jwt parameter value.
It's a fix for this issue : https://github.com/jitsi/jitsi-meet/issues/13921
=> Change Whiteboard room id generation

resources/prosody-plugins/mod_visitors.lua
When a participant in the main room is kicked while visitor mode is on, visitors cannot get this info and still see the kicked participants as if they are still in the meeting.This commit hooks the kick message and forwards it to vnodes.
=> fix(visitors): informs visitor nodes when a participant is kicked.

resources/prosody-plugins/mod_visitors.lua
Sep 22 22:06:01 mod_bosh        error   Traceback[bosh]: /usr/share/jitsi-meet/prosody-plugins/mod_visitors.lua:305: attempt to index field '?' (a nil value)
stack traceback:
/usr/share/jitsi-meet/prosody-plugins/mod_visitors.lua:305: in function '?'
/usr/share/lua/5.2/prosody/util/events.lua:81: in function </usr/share/lua/5.2/prosody/util/events.lua:77>
=> fix: Adds a nil check in visitors module.

react/features/chat/components/native/Chat.tsx, react/features/chat/components/native/ChatInputBar.tsx, react/features/chat/components/native/styles.ts
Fixes #13748.
1. Iphone 14 
2. Iphone 14 PRO Max 
3. Iphone SE
=> feat(chat/native): fixed keyboard overlapping chat input bar

react/features/app/components/App.native.tsx
On Android we support RestrictionManager, but that already sets it, so make sure we always save it on the settings.
Editing will be restricted in the Settings dialog if changing it is restricted anyway.
Fixes: https://github.com/jitsi/jitsi-meet/issues/13994
=> fix(rn) allow default server URL to be set from native

react/features/large-video/components/LargeVideo.web.tsx, react/features/large-video/components/ScreenSharePlaceholder.web.tsx
Fixes #13968 
The initial size of screen share self view was wrong because, we conditionally rendered the ScreenSharePlaceHolder and the Video inside the largeVideoWrapper, It caused to not set the correct sizing until resized. 
I moved the ScreenSharePlaceHolder outside the largeVideoWrapper and styled it correctly to show in top of the video.
=> fix: Self view of screen sharing sized correctly initially

resources/prosody-plugins/mod_room_metadata.lua
Without this room_metadata will silently discard all room metadata client requests assuming that they didn’t come from Jitsi meet clients.
Fixes #14001
Detailed description in that issue.
=> fix: Make room_metadata Prosody module depend on the required jitsi_session module

css/_welcome_page.scss, react/features/welcome/components/WelcomePage.web.tsx
The meeting name input field has already validation but this info was not accessible and could only be visible to the user on hover or unless the user clicks enter or  "start meeting". so we had to show another info message on typing any character that violates the validations. this info is also accessible (tap-able and readable by screen reader).
https://github.com/jitsi/jitsi-meet/assets/52747422/38b6bda1-84fc-456c-81a7-d716c1394299
=> Accessibility: add validation warning on room name

react/features/base/modal/components/JitsiKeyboardAvoidingView.tsx, react/features/base/modal/components/JitsiScreen.tsx, react/features/chat/components/native/Chat.tsx, react/features/lobby/components/native/LobbyChatScreen.tsx, react/features/lobby/components/native/styles.ts, react/features/polls/components/native/PollsPane.tsx
Some screens don't have tab navigators and, generally speaking, this is more related to the header height.
=> feat(base/modal): changed hasTabNavigator to hasExtraHeaderHeight

react/features/base/toolbox/components/AbstractButton.tsx, react/features/base/toolbox/components/ToolboxItem.web.tsx, react/features/toolbox/components/web/OverflowMenuButton.tsx
All button in the toolbar has an aria-pressed (true, false) but to make it properly accessible and readable from the screen reader the button that open menu should have aria-expanded (true, false).
=>  Accessibility: give the menu button in the toolbar attribute (aria-expended)

react/features/base/ui/components/native/buttonStyles.ts
Native buttons have an extra unneeded lineHeight value that when zooming or using other languages, have their labels cut.
We already take from bodyShortBold object a lineHeight of 20, no need for an extra one.
Fixes #14039
=> feat(base/ui): removed unneeded lineHeight value

react/features/polls/components/native/PollResults.tsx
In the jitsi web app, the poll creator is displayed for all published votes whereas in the native app the current username of the participant has been displayed for all polls regardless of the creator
In order to fix this issue I simply copied the creatorName parameter as show in the [web app implementation](https://github.com/jitsi/jitsi-meet/blob/6fda5924a3bf5bec1000b2cc6f7412bcc3c0c8b7/react/features/polls/components/web/PollResults.tsx#L115)
=> fix(native app): Display poll creator name

react-native-sdk/index.tsx, react/features/base/conference/actionTypes.ts, react/features/mobile/external-api/middleware.ts, react/features/mobile/react-native-sdk/middleware.js, react/features/toolbox/components/native/AudioMuteButton.tsx, react/features/toolbox/components/native/VideoMuteButton.tsx
Adding two event listeners to `rnSdkHandlers` to notify about audio and video muted state changes.
I tested both on iOS and Andriod with something like: 
```
const onAudioMutedChanged = React.useCallback((muted) => {
console.log('onAudioMutedChanged', muted);
}, []);
const onVideoMutedChanged = React.useCallback((muted) => {
console.log('onVideoMutedChanged', muted);
}, []);
const eventListeners = React.useMemo(
() => ({
onAudioMutedChanged,
onVideoMutedChanged,
}),
[onAudioMutedChanged, onVideoMutedChanged]
);
return (
<JitsiMeeting
... 
eventListeners={eventListeners}
/>
);
```
=> feat(rnsdk): add audio and video muted state changed

react/features/base/conference/actionTypes.ts, react/features/mobile/external-api/middleware.ts, react/features/mobile/react-native-sdk/middleware.js, react/features/toolbox/components/native/AudioMuteButton.tsx, react/features/toolbox/components/native/VideoMuteButton.tsx
Removing redundant `AUDIO_MUTED_CHANGED` and `VIDEO_MUTED_CHANGED` actions.
=> refactor(rnsdk): remove redundant audio and video actions

react/features/base/ui/components/web/ContextMenu.tsx
This PR fixes double click issue with context menu when it is closed with ESC key: currently user has to click twice the menu button in order to show the menu if it was closed with ESC key before.
https://github.com/jitsi/jitsi-meet/assets/9369306/6a848421-19f4-43d3-8f4d-380f1de0e8f7
https://github.com/jitsi/jitsi-meet/assets/9369306/d82e1a68-6c78-427e-bd64-06a08de9f2a6
=> Fix context menu double click behaviour if closed with ESC

css/_base.scss, css/_welcome_page.scss, react/features/base/react/components/web/Watermarks.tsx
This PR refactors the watermark styles, moving the `maxWidth` and `maxHeight` to the .scss file instead. Some light refactoring too. 
It will also resolve https://github.com/jitsi/jitsi-meet/issues/8604.
Thank you! 🙌
=> refactor(watermark): Move static styles into stylesheet, refactor a bit

ios/Podfile.lock, package-lock.json, package.json
Latest version contains the fix for Android 14.
1. Add: Add vs2022 support. Remove unnecessary reference
2. Fix: Change WindowsTargetPlatformVersion to 10.0
3. Fix: added check for broadcast receiver being registered and unregistered to avoid IllegalArgumentException
4. Fix: RN-0.73 change Android configs for RN 0.73 compatibility
5. Fix: Add RECEIVER_EXPORTED/RECEIVER_NOT_EXPORTED to support Android 14
=> chore(rn-orientation-locker, version): bump to latest

react/features/base/config/configType.ts, react/features/jaas/functions.ts, react/features/rtcstats/RTCStats.ts, react/features/rtcstats/middleware.ts
Fetch the customer id for jaas and 8x8 tenants and report them to rtcstats. This depends on: 
https://github.com/jitsi/lib-jitsi-meet/pull/2393
=> feat(rtcstats): fetch conference creator id and send to rtcstats

android/app/src/main/res/xml/app_restrictions.xml, ios/app/src/AppDelegate.m, react/features/app/components/App.native.tsx, react/features/settings/components/native/ConferenceSection.tsx
Fixes #14079 
We already get a DEFAULT_SERVER_URL if a custom address is not set.
=> fix(sdk): custom server url is overwritten by sdk default url option value

conference.js, react/features/base/settings/middleware.web.ts
This fixes the issue when starting the conference with video muted, after unmuting it the cameraDeviceId would stay undefined.
=> ref(settings): listen to TRACK_ADDED to set the input devices id

react/features/base/settings/middleware.web.ts, react/features/device-selection/functions.web.ts
Avoid returning undefined for device if there is a user selected device id and not a device id when calling `getCurrentDevices` on the api and when selecting video device in settings.
=> fix(devices): return user selected device id if there is no device id

react/features/conference/actions.web.ts, react/features/prejoin/components/web/PrejoinApp.tsx
- on 3rd party prejoin, we did not setup the initial devices, resulting in always creating tracks for default device for camera and mic regardless of settings, and for both meeting and 3rd party prejoin to not set the audio output device at all
=> fix(media-devices) Fix configuring media devices on init

debian/jitsi-meet-web.install
We reference the favicon from index as svg directly from the images folder.
=> fix(debian): No svg available in root folder.

resources/prosody-plugins/mod_muc_breakout_rooms.lua, resources/prosody-plugins/mod_persistent_lobby.lua, resources/prosody-plugins/mod_room_destroy.lua
ref: https://github.com/jitsi/jitsi-meet/pull/13939#issuecomment-1807140392
Created a common module to handle room destroy, because the alternative would be for both modules to send their own events and have handlers to deal with event sent by other module. Using different events per module has some disadvantages:
1. each module needs to have knowledge of the other module
2. it gets extremely really messy to add yet another module that needs to keep main room alive since every module needs to know of all other module that does that.
=> fix(breakout-rooms, persistent-lobby): support running both modules together

resources/prosody-plugins/mod_muc_census.lua
We saw recently two occasions with rooms with participants but no prosody.full_sessions for those participants and when everyone leaves the meeting it never ends.
=> feat: Adds detection of occupants with no connection.

modules/API/API.js
Events such as "mouse-move", "mouse-leave" and "face-landmark-detected"
reach this code and pollute the logs. It's probably worth investigating
why this is the case and fixing it if necessary, but for now just remove
the log message.
=> fix: Do not log unknown commands.

react/features/prejoin/components/web/Prejoin.tsx, react/features/toolbox/components/web/Drawer.tsx
=> fix(ui) style prejoin drawer

react/features/toolbox/components/web/OverflowMenuButton.tsx, react/features/toolbox/subscriber.web.ts
- fix reactions menu not visibile on FF when in drawer mode
- fix subscriber for tileview
=> fix(reactions-firefox) Fix drawer menu not scrollable on FF

package-lock.json, package.json, react/features/base/i18n/dateUtil.ts
Issue: When lobby mode is active, the ui showing the elapsed time gives an error when it comes to the screen. Moment just released a new update and moment-duration-format plugin is not compatible with this version. This plugin will always try to install itself on the root.moment instance, if it exists. [source](https://github.com/jsmreese/moment-duration-format?tab=readme-ov-file#usage)
Solution: Used the moment version of jitsi-meet instead of root. [No problem with version 2.29.4](https://github.com/moment/moment/blob/develop/CHANGELOG.md)
=> fix: moment duration format error

react/features/base/participants/reducer.ts
Updates the remoteVideoSources set only when neccessary when participant is leaving . This fixes an endless recursion when visitor is promoted or left and there is a screen sharing.
=> fix(remote-sources): update only when neccessary

resources/prosody-plugins/mod_muc_census.lua
Fixes the census module reporting nil values to the metrics handler, causing failures in openmetrics rendering
=> fix: census lua init to 0 to avoid openmetrics errors

lang/main.json, modules/API/API.js, modules/API/external/external_api.js, react/features/notifications/constants.ts, react/features/transcribing/actionTypes.ts, react/features/transcribing/actions.ts, react/features/transcribing/middleware.ts, react/features/transcribing/reducer.ts
=> Transcription improvements

lang/main-eo.json, lang/main.json
Ran `update-translations.js`, and added all the missing Esperanto translations. 
Also fixed a few minor spelling/grammar errors (there are probably more, but these are the ones that caught my eye).
=> Updated Esperanto Translations.

react/features/base/conference/actions.ts, react/features/base/connection/actions.any.ts
This was resulting some colibri websockets reconnects as the state of the previous JitsiConference was not cleaned up.
=> fix: Fixes leaving the visitor's meeting on promotion.

android/sdk/src/main/res/values-ru/strings.xml, lang/main-ru.json
Added some prases for ru locale which is necessary for using in mobile sdk.
=> Updated Russian translations

config.js, react/features/base/config/configType.ts, react/features/base/config/functions.web.ts, react/features/base/config/reducer.ts, react/features/deep-linking/openDesktopApp.ts
As we have the jitsi-meet-electron app, lets allow deployments to use it.
Allow deployments to enable desktop deeplinking without the need to re-implement _openDesktopApp()
Disable it by default to keep the current behaviour (deeplinking on mobile on, on desktop off)
This feature is meant as purely opt-in.
Signed-off-by: Christoph Settgast <csett86_git@quicksands.de>
=> feat(deeplinking): Desktop deeplinking configurable (default off) and using jitsi-meet-electron

config.js, lang/main-de.json, lang/main.json, react/features/base/config/configType.ts, react/features/base/config/functions.web.ts, react/features/base/react/Platform.web.ts, react/features/deep-linking/components/DeepLinkingDesktopPage.web.tsx
Offer the default app, but make it configurable for own branded
desktop clients
Signed-off-by: Christoph Settgast <csett86_git@quicksands.de>
=> feat(deeplinking): offer electron app for download, configurable

react/features/base/config/functions.web.ts
before this, if you did not specify desktop, ios or android, the whole block
would be undefined and then create deeplinks like
intent://testjitsi/test#Intent;scheme=undefined;package=undefined;end
now the config behaves that you can partially override eg. desktop
and leave everything else to default.
=> fix(deeplinking): allow partial config of deeplinking and defaults for the remaining

react/features/visitors/reducer.ts
We were modifying DEFAULT_STATE and later the request magically appears after the state is cleared, like joining and leaving breakout rooms.
=> fix(visitors): Fixes clearing promotion requests.

resources/prosody-plugins/mod_visitors_component.lua
If not handled an error is returned that the stanza is not handled (service-unavailable error) and displayed in UI.
=> fix(visitors): Handles promotion rejection msg.

resources/prosody-plugins/mod_room_metadata_component.lua
Send a message to jicofo with a status code 104 (config update) to make it re-read the MUC configuration form when room_metadata changes
=> feat: Notify jicofo when room_metadata changes the config form.

config.js, lang/main.json, react/features/base/config/configType.ts, react/features/base/premeeting/components/web/PreMeetingScreen.tsx, react/features/base/premeeting/components/web/RecordingWarning.tsx, react/features/prejoin/components/native/Prejoin.tsx, react/features/prejoin/components/native/RecordingWarning.tsx, react/features/prejoin/components/native/styles.ts, react/features/prejoin/components/web/Prejoin.tsx
Web
With enableInsecureRoomNameWarning true:
Mobile
With roomNameEnabled false:
=> feat(prejoin) display recording warning

config.js, react/features/base/config/configType.ts, react/features/base/flags/constants.ts, react/features/conference/components/native/TitleBar.tsx, react/features/participants-pane/components/web/ParticipantsPaneButton.tsx, react/features/participants-pane/functions.ts, react/features/toolbox/hooks.web.ts
1. config.js participantsPane.enabled defaults to true.
2. Create isParticipantsPaneEnabled.
3. Use for mobile and web.
=> feat(config/flags): participants visibility control through config and flag

react/features/recording/actions.any.ts, react/features/recording/components/AbstractRecordingLabel.ts, react/features/recording/components/web/RecordingLabel.tsx, react/features/recording/functions.ts
Display only livestreaming label when the livestreaming and the transcribtions are on.
=> fix(recording/livestreaming):  labels

react/features/recording/actions.any.ts, react/features/recording/components/AbstractRecordingLabel.ts, react/features/recording/components/LiveStream/AbstractLiveStreamButton.ts, react/features/recording/components/Recording/AbstractStartRecordingDialog.ts, react/features/recording/components/Recording/AbstractStopRecordingDialog.ts, react/features/recording/components/native/RecordingExpandedLabel.ts, react/features/recording/functions.ts, react/features/recording/middleware.ts, react/features/subtitles/reducer.ts, react/features/transcribing/functions.ts, react/features/transcribing/middleware.ts, react/features/transcribing/subscriber.ts
Until this commit we didn't make difference between transcriptions from the recording dialog and subtitles. Now subtitles are not considered recording anymore and only the transcriptions started from recording dialog are considered recording.
=> feat(recorder-transcription): Handle correctly in the UI.

react-native-sdk/android/build.gradle
When newArchEnabled=true. Refers to a non-existent category. This prevents the application from building
https://github.com/jitsi/jitsi-meet/blob/5be616a224d315df22a17efce2a59bbdb1a91f04/react-native-sdk/android/build.gradle#L136
RN: 0.72.11
jitsi: 1.0.3
```
> Task :jitsi_react-native-sdk:generateCodegenSchemaFromJavaScript FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
17 actionable tasks: 3 executed, 14 up-to-date
info 💡 Tip: Make sure that you have set up your development environment correctly, by …
```
=> fix(build.gradle): When newArchEnabled=true. Refers to a non-existent category

react/features/base/config/configType.ts, react/features/base/config/constants.ts, react/features/base/config/functions.web.ts, react/features/base/config/reducer.ts, react/features/base/premeeting/components/web/PreMeetingScreen.tsx, react/features/filmstrip/components/web/Filmstrip.tsx, react/features/filmstrip/components/web/MainFilmstrip.tsx, react/features/filmstrip/components/web/StageFilmstrip.tsx, react/features/reactions/functions.web.ts, react/features/recording/components/LiveStream/web/LiveStreamButton.ts, react/features/recording/components/Recording/web/RecordButton.ts, react/features/toolbox/actionTypes.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/constants.ts, react/features/toolbox/functions.web.ts, react/features/toolbox/hooks.web.ts, react/features/toolbox/middleware.web.ts, react/features/toolbox/reducer.ts, react/features/toolbox/types.ts
The previous version of getToolbarButtons function was actually adding the custom buttons on every call to the config toolbarButtons array, effectively creating dublicates of every custom button. The PR fixes this issue.
Also now we will be running the getToolbarButtons calculation only when needed.
=> fix(toolbarButtons): Store all buttons in redux.

react/features/base/config/constants.ts, react/features/base/config/functions.web.ts, react/features/base/premeeting/components/web/PreMeetingScreen.tsx, react/features/participants-pane/components/web/MeetingParticipants.tsx, react/features/reactions/functions.web.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/constants.ts, react/features/toolbox/functions.web.ts, react/features/toolbox/hooks.web.ts, react/features/toolbox/middleware.web.ts
Filters the toolbarButtons in redux depending on the visitor state instead of filtering them every time in mapStateToProps. This will prevent unnecessary rerenders of the toolbar.
Additionally:
- Moves visitor buttons const from features/config in features/toolbox.
- Removes dublicate functions isButtonEnabled and isToolbarButtonEnabled.
- Adds more buttons to the visitor allowed buttons which functionality has been any way accessible trough shortcuts or somewhere else.
- Enables customButtons to be visible for visitors.
=> fix(toolbarButtons): filter visitor buttons in redux.

react/features/recording/functions.ts
=> fix: decouple local recording from needing a valid jwt

resources/prosody-plugins/mod_visitors_component.lua
Replacement only on the host part of the jid.
The problem is having a room like:
[meet-jit-si-shard]someroomname@conference.meet.jit.si and replacing with 'meet.jit.si', the dots match the -.
=> fix(visitors): Fixes replacing visitor domain.

react/features/base/conference/reducer.ts
Reset subject when setting a new room name.
=> fix(conference) fix incorrect meeting name in CallKit

react/features/base/react/components/web/Message.tsx
Matrix user ids all start with an @, so lets skip these for the
smiley renderer (same as we already do for any url-like strings).
I did not use "contains @ and :", as also the :@ (shorthand for :rage:)
contains that and would have broken it...
Fixes: #10936
=> fix(chat) dont emojify matrix ids

react/features/feedback/components/FeedbackDialog.web.tsx
Ich sage:If the user enters a longer text and then moves to the right to the end of the input area, then the user uses the <Return> key for the next input. However, this always leads to the feedback being sentfeedback (and therefore to an incomplete description)
I fixed the code. It will not define a default button that is triggered by Return. The user should always explicitly click on the <OK> button to submit their rating.
=> disable: automatical send funtion by clicking 'enter' in feedback 

react/features/filmstrip/functions.any.ts, react/features/filmstrip/middleware.native.ts, react/features/filmstrip/middleware.web.ts, react/features/filmstrip/subscriber.any.ts
Fixes #14491.
When a screensharing participant leaves and is unmuted or sharing the tab audio, there is a dominant speaker changed event which stores wrong values in filmstrip state. And because we skip reordering when there is no filmstrip scroll and no screensharers to avoid reordering on every dominant speaker event for small meetings, we fail to evaluate that the screensharere is actually gone and we still show it.
This will not happen if the one sharing is not dominant speaker (muted) or if there are more participants in the meeting (there is a scroll).
=> fix: Fixes showing left participants in the pane under certain conditions.

react/features/video-quality/subscriber.ts
When screensharing source is the first source to be added with ssrc-rewriting enabled, constraints for the camera tile don't get updated when its pinned. Fixes https://github.com/jitsi/jitsi-meet/issues/14501
=> fix(video-quality): Correctly pin camera tile.

react/features/participants-pane/functions.ts
Fixed multi words search on participants pane #14529 
The issue has been fixed according to expected behavior:
=> fix(participants-pane): multi words search

react/features/authentication/functions.any.ts
The URL.hash returns the # sign, and so we always ignore the first parameter.
=> fix: Fixes parsing hash params to be passed to tokenAuthUrl.

package-lock.json, package.json, react/features/base/config/functions.any.ts, react/features/base/connection/actions.any.ts
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/2495.
=> fix(config): Enable ssrc-rewriting by default.

react/features/mobile/navigation/components/RootNavigationContainer.tsx, react/features/mobile/navigation/components/conference/components/ConferenceNavigationContainer.tsx, react/features/mobile/navigation/screenOptions.ts, react/features/whiteboard/actions.native.ts, react/features/whiteboard/components/native/Whiteboard.tsx, react/features/whiteboard/middleware.any.ts, react/features/whiteboard/middleware.native.ts
1. Fixed screen go back handler.
2. Moved screen to ConferenceNavigationContainer.
3. Fixed screen options.
4. Fixed navigation routes.
=> feat(whiteboard/native): ui fixes

modules/UI/videolayout/LargeVideoManager.js
In the case where we switch from jvb to p2p when we need to switch the p2p and jvb track, they will be with the same source name. In order to add the streaming status listener we need to check if the isP2P flag is different. Without this check we won't have the correct stream status listener for the track. Normally the Thumbnail and ConnectionIndicator components will update the streaming status the same way and this may mask the problem. But if for some reason the update from the Thumbnail and ConnectionIndicator components don't happen this may lead to showing the avatar instead of the video because of the old track inactive streaming status.
=> fix(LargeVideo): use correct track for streaming status.

react/features/lobby/reducer.ts
Fixes a case where participant is not entering lobby when trying the second time after being rejected.
=> fix: Clear up knocking state on error.

resources/prosody-plugins/mod_av_moderation_component.lua, resources/prosody-plugins/mod_conference_duration_component.lua, resources/prosody-plugins/mod_jibri_session.lua, resources/prosody-plugins/mod_muc_breakout_rooms.lua, resources/prosody-plugins/mod_muc_census.lua, resources/prosody-plugins/mod_muc_jigasi_invite.lua, resources/prosody-plugins/mod_muc_kick_jigasi.lua, resources/prosody-plugins/mod_muc_lobby_rooms.lua, resources/prosody-plugins/mod_muc_password_check.lua, resources/prosody-plugins/mod_muc_size.lua, resources/prosody-plugins/mod_polls.lua, resources/prosody-plugins/mod_reservations.lua, resources/prosody-plugins/mod_room_metadata_component.lua, resources/prosody-plugins/mod_speakerstats_component.lua, resources/prosody-plugins/mod_turncredentials_http.lua, resources/prosody-plugins/mod_visitors_component.lua
=> Jibri session data and cjson

react/features/invite/components/add-people-dialog/web/DialInNumber.tsx, react/features/invite/components/add-people-dialog/web/InviteByEmailSection.tsx
Fixed (Fix invite People copy number UI) https://github.com/jitsi/jitsi-meet/issues/14551
New copy number button behavior:
- It has a tooltip that shows what it does
- when clicked the icon converted to IconCheck for 2500ms like other copy icons then returns back to the IconCopy
New Copy Invitation button behavior:
- when clicked the icon converted to IconCheck for 2500ms like other copy icons then returns back to the IconCopy
https://github.com/jitsi/jitsi-meet/assets/59124058/f29162ee-3145-4430-b525-a397d3cf9590
=> fix(DialInNumber,InviteByEmailSection):Copy Button Ui

.github/workflows/ci-lua.yml, .github/workflows/ci.yml
See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
=> ci: move to node 20 based GH actions as current ones are deprecated

debian/jitsi-meet-prosody.postinst
In certain cases (lib-unbound not found message from lua) we can detect that jvb account is not existing, and we will re-create causing jvb to not able to connect, as password is changed only in prosody.
=> fix: Updates jvb user account check.

resources/prosody-plugins/mod_system_chat_message.lua
=> fix: allow multiple jids to be specified for sending system messages

react/features/authentication/functions.any.ts
Fixes #14672.
When passing url param config.subject="Example%20Title" we will send config.subject%22%3A%22%2522Example%2520Title%2522%22 which is double quotes.
=> fix: Parse/decode the URL params before constructing the url.

modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/VideoContainer.js, package-lock.json, package.json, react/features/base/participants/functions.ts, react/features/base/tracks/actionTypes.ts, react/features/base/tracks/actions.any.ts, react/features/base/tracks/middleware.web.ts, react/features/base/tracks/reducer.ts, react/features/participants-pane/components/native/MeetingParticipantItem.tsx, react/features/participants-pane/components/web/MeetingParticipantItem.tsx, react/features/video-quality/subscriber.ts
When ssrc-rewriting is enabled, LJM doesn't fire TRACK_OWNER_CHANGED events; it will instead fire TRACK_REMOVED followed by TRACK_ADDED event.
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/2509
=> fix(tracks): Remove code that handles TRACK_OWNER_CHANGED event.

android/sdk/src/main/AndroidManifest.xml, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java
Android app currently mutes when it's in the background or loses focus, which wasn't an issue in previous versions.
This PR fixes the issue and restoring the ability to use the microphone in the background.
(Maybe) Fixes https://github.com/jitsi/jitsi-meet/issues/14615
Since Android 14, it appears to require more explicit permissions for foreground services.  ( Reference : https://medium.com/@domen.lanisnik/guide-to-foreground-services-on-android-9d0127dc8f9a )
Currently, the app lacks the required permission, causing app to lose access to microphone in the background. This behavior maybe relates `targetSdkVersion`.
Added the `FOREGROUND_SERVICE_MICROPHONE` permission to the app's manifest and configured it to be used by the `JitsiMeetOngoingConferenceService`.
- SONY Xperia 5 V SO-53D …
=> fix(android) Keep microphone enabled when app is in background

.github/workflows/ci.yml
The macOS-13 image runners are x64, but macOS-14 are arm64.
=> feat(ci) run CI also on macOS on arm64

resources/prosody-plugins/mod_auth_token.lua
This change allows the prosody auth token systems to accept a client JWT via the Authorization header preferentially.
=> feat: allow client JWT in Authorization header

conference.js, react/features/base/conference/actions.any.ts, react/features/base/conference/actions.native.ts, react/features/base/conference/actions.web.ts, react/features/base/tracks/actions.web.ts, react/features/base/tracks/types.ts, react/features/notifications/constants.ts
Before we were using setAudioMuted and setVideoMuted which was effectively using separate GUM calls for audio and video. This was problematic in the case where GUM permissions prompt was displayed because two separate prompts were displayed.
=> fix(visitors): Use single GUM for enabling media on promotion.

conference.js, modules/API/API.js, modules/API/external/external_api.js
Added a new conference-created-timestamp event for the iFrame API, forwarding the JitsiConferenceEvents.CONFERENCE_CREATED_TIMESTAMP event.
=> feat(external-api) Forward CONFERENCE_CREATED_TIMESTAMP to iframe

lang/main-fr.json
:wave: Here a couple changes on french translations. The unmute/mute string changes are quite important, as for now, french screen reader users don't get the info about the current state. The button is vocalized as "Mute/unmute mic", but you don't get the info about if it's muted on press, or on unpressed. **So this tiny translation change has a huge impact for french screen reader users.**
The changes explained in details:
- settings string contained a string saying "show / hide settings", but we should match the english string saying only "show settings" as the button is only used to show the settings (its a dialog you can't go out of, so there is no way to go back to the settings button to close, the "hide" case doesn't exist)
- use "Activer" instead of "Rétablir" and "Démarrer" for …
=> fix(lang) (a11y) update screen reader related french translation

react/features/prejoin/functions.ts
Fixes https://github.com/jitsi/jitsi-meet/issues/14735
Updated logic = room name enabled if feature flag enable **and** conference subject not hidden.
=> fix hideConferenceSubject not hiding subject on prejoin page

react/features/base/jwt/functions.ts, react/features/base/util/uri.ts
This updates the external API to send the JWT both as a URL hash parameter as well as a query string for backwards compatibility.  The JWT parsing function now prefers the hash value over the query string value.
=> feat: move jwt to URL hash from search parameters

debian/control
Out build process does not actually require nodejs. We assume node/npm is installed on the machine. Dropping it so we can use just nvm to control the versions via .npmrc.
=> fix: Drop nodejs build dependency.

lang/main.json, react/features/polls/actionTypes.ts, react/features/polls/actions.ts, react/features/polls/components/AbstractPollAnswer.tsx, react/features/polls/components/AbstractPollCreate.tsx, react/features/polls/components/AbstractPollResults.tsx, react/features/polls/components/native/PollAnswer.tsx, react/features/polls/components/native/PollCreate.tsx, react/features/polls/components/native/PollItem.tsx, react/features/polls/components/native/PollsList.tsx, react/features/polls/components/native/PollsPane.tsx, react/features/polls/components/web/PollAnswer.tsx, react/features/polls/components/web/PollCreate.tsx, react/features/polls/components/web/PollItem.tsx, react/features/polls/components/web/PollsList.tsx, react/features/polls/components/web/PollsPane.tsx, react/features/polls/functions.ts, react/features/polls/middleware.ts, react/features/polls/reducer.ts, react/features/polls/types.ts
1. Save poll.
2. Edit poll.
3. Save edited poll.
4. Send poll to other participants.
=> feat(polls): rework

react/features/invite/functions.ts
Removes the JWT from URL query parameter, moving it to the Authorization header.
=> feat(invite): move JWT to Authorization header for invite and search endpoints

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/toolbox/actionTypes.ts, react/features/toolbox/actions.web.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/constants.ts, react/features/toolbox/functions.web.ts, react/features/toolbox/middleware.web.ts, react/features/toolbox/reducer.ts, react/features/toolbox/types.ts
As part of the PR, it also fixes:
- Removes button aliases
- Unifies the keys in the object returned by getAllToolboxButtons and the button keys
- Makes sure that the number of buttons displayed are always the same as the number of buttons specified in the thresholds and removes the exception for not filling up the main toolbar with buttons from overflow menu when reactions button is disabled.
- Introduces a priority for buttons that will be used to fill empty spaces in the main toolbar.
=> Toolbox-custom-order

config.js, react/features/base/config/configType.ts, react/features/base/connection/actions.any.ts
This aligns mobile and web. WS has been the default on meet.jit.si and beta.meet.jit.si for quite a while now.
=> feat(rn,config) use WebSockets for XMPP by default on mobile

react/features/base/ui/hooks/useContextMenu.web.ts
The menu with Rename and Close for the breakout rooms.
=> fix(breakout-rooms): Closes menu after clicking on it.

react/features/base/responsive-ui/actions.ts, react/features/base/responsive-ui/middleware.web.ts
- on iOS safari and chrome, in case we show eg a spinner until we get the videoConferenceJoined event, all `clientResize` are done with size 0 for width/height
- on iOS we never get a `clientResize` call with correct values, except if we force a call by eg opening/closing the chat window
=> fix(iOS-responsive-ui) Attempt fix iOS responsive ui issue

react/features/remote-control/keycodes.ts
- this was causing a crash on the controlled meeting instance
=> fix(remote-control) Fix caps lock key name

modules/API/API.js, react/features/conference/components/native/AlwaysOnLabels.tsx, react/features/recording/components/AbstractRecordingLabel.ts, react/features/recording/components/LiveStream/AbstractLiveStreamButton.ts, react/features/recording/functions.ts, react/features/recording/middleware.ts, react/features/transcribing/subscriber.ts
=> feat(external_api) include transcription state in recordingStatusChanged

react/features/breakout-rooms/components/native/BreakoutRoomNamePrompt.tsx
The option to rename breakout rooms was not working for moderators on native devices.
=> Rename breakout rooms on native

conference.js, package-lock.json, package.json, react/features/base/conference/actions.any.ts, react/features/base/conference/middleware.any.ts, react/features/base/conference/reducer.ts, react/features/base/participants/middleware.ts, react/features/base/participants/types.ts, react/features/participants-pane/functions.ts, react/features/video-menu/components/native/RemoteVideoMenu.tsx, react/features/video-menu/components/web/ParticipantContextMenu.tsx
A fix for this issue I submitted earlier: https://github.com/jitsi/jitsi-meet/issues/14559
Not sure if this is the way you'd want to go about resolving this problem, but this is how we handled it.
Depends on this PR in the lib-jitsi-meet repo: https://github.com/jitsi/lib-jitsi-meet/pull/2534
=> feat(silent): hide unmute if participant joined without audio

resources/prosody-plugins/mod_visitors_component.lua
The metadata initialization is skipped for healthcheck rooms.
=> fix(visitors): Adds a nil check for metadata.

lang/main.json, react/features/base/tracks/constants.ts, react/features/conference/middleware.any.ts, react/features/participants-pane/components/native/ContextMenuMore.tsx, react/features/participants-pane/components/web/FooterContextMenu.tsx, react/features/video-menu/components/native/LowerHandButton.tsx, react/features/video-menu/components/native/RemoteVideoMenu.tsx, react/features/video-menu/components/web/LowerHandButton.tsx, react/features/video-menu/components/web/ParticipantContextMenu.tsx, react/features/video-menu/constants.ts
Dear reviewer,
I have implemented functionality to lower a participant's hand and lower all hands for the meeting moderator. There are also some remaining code sections related to creating notifications for the next speaker. I have commented out notification-related listeners as these features are not yet fully implemented. I look forward to receiving your comments and advice on these updates.
All the best,
Mengyuan
=> Lower hand

react/features/keyboard-shortcuts/actions.web.ts
We are ending up in incorrect mute state (unmuted) if the initial press event is resulting in a new track creation and the release event happens before the track is created.
=> fix(push2talk): incorect state on release because a new audio track is beening created.

config.js
When uncommenting full video quality block it breaks cause of this comma
=> Update config.js, missing comma

lang/main.json, react/features/app/middlewares.any.ts, react/features/app/reducers.any.ts, react/features/app/types.ts, react/features/base/conference/functions.ts, react/features/polls-history/actionTypes.ts, react/features/polls-history/actions.ts, react/features/polls-history/middleware.ts, react/features/polls-history/reducer.ts, react/features/polls/actionTypes.ts, react/features/polls/actions.ts, react/features/polls/components/AbstractPollAnswer.tsx, react/features/polls/components/AbstractPollCreate.tsx, react/features/polls/components/AbstractPollResults.tsx, react/features/polls/components/native/PollAnswer.tsx, react/features/polls/components/native/styles.ts, react/features/polls/components/web/PollAnswer.tsx, react/features/polls/components/web/PollsList.tsx, react/features/polls/middleware.ts, react/features/polls/reducer.ts
features/poll-history controls saving, editing and removing polls from local storage.
=> feat(polls-history): control polls inside local storage 

lang/main-eo.json
There is a small error in the Esperanto translation. In Esperanto "al" no accusative. Thus the phrase is "Aliĝu al la kunveno" with out the accusative marker "-n".
=> Correct accusative error in Esperanto translation

lang/main-he.json
This PR addresses the following typos in the Hebrew language file:
1. **`notify.connectedOneMember`**:
- **Before**: `{{name}} הצטרף למפדש`
- **After**: `{{name}} הצטרף למפגש`
2. **`addPeople.noResults`**:
- **Before**: `לא נמצאו תואצות מתאימות`
- **After**: `לא נמצאו תוצאות מתאימות`
3. **`chat.fieldPlaceHolder`**:
- **Before**: `הקלד הודעתך כאו`
- **After**: `הקלד הודעתך כאן`
These corrections improve the clarity and accuracy of the text in the application.
**Fixes Issue:** #14927
=> Hebrew Typo Fix for Issue #14927

react/features/etherpad/middleware.ts
Allows overriding or augmenting the default values set by the Jitsi Meet web app using the config parameter.
Use case when using EtherPad may be (in config): 
`etherpad_base = "https://hostname/etherpad/extraordinaryparameterstiekindly?useMonospaceFont=true",`
=> Merge query string parameters in `etherpad_base` with app values

react-native-sdk/index.tsx
Added setAudioOnly for the component ref functions. Thus we can easily control the audio only behavior by this feature.
=> feat(react-native-sdk): added setAudioOnly to the ref props

lang/main.json, react/features/base/config/functions.any.ts, react/features/base/participants/actionTypes.ts, react/features/base/participants/reducer.ts, react/features/base/participants/subscriber.ts, react/features/video-menu/actions.any.ts
Hi reviewer,
This pull request added the next speaker notification feature to the web application. However, the variable naming is a problem. If you have good ideas about the naming, please let me know.
=> feat(next speaker notification)

android/scripts/release-sdk.sh, ios/scripts/release-sdk-lite.sh, ios/scripts/release-sdk.sh
Adding GIT_TAG in jenkins, so we no longer need to set one in the release scripts.
=> feat(android/ios/sdk): removed tagging from release scripts

resources/prosody-plugins/mod_presence_identity.lua
=> feat: Presence identity module to support other auth mechanisms.

react/features/chat/components/native/ChatMessage.tsx, react/features/chat/constants.ts, react/features/notifications/components/native/Notification.tsx
On older devices, rendering big messages containing emojis might affect performance. In order to prevent some of these cases, we need to set a character limit for when we linkify messages or replace non unicode messages.
=> feat(chat/native): set limit for linkifying and replacing non unicode messages

Makefile
It prevents the bundle analyzer from working because the stats files are placed in the build dir.
Clean *before* building instead.
=> fix(build) don't run clean after compilation

react/features/base/lastn/middleware.ts
There is no point in ever setting lastN to anything other than 0 when in the background because we are not rendering anything.
When in PiP mode, the app state is not background, which might have deceived us into adding that check there way back when.
=> fix(lastN) simplify lastN calculation when in background

react/features/authentication/functions.any.ts
During authentication cycle the iceServers URL params are not passed through the various redirects. The result is that the when we finally return back to the conference page authenticated and with the JWT token the iceServers URL param is lost.
=> fix(auth): Preserve iceServers URL params

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
If the readyToClose event was fired there is no need to "leave" the meeting, it just circles back to the app unnecessarily, potentially creating another readyToClose event.
=> fix(android) fix joining meetings in quick succession

react/features/base/participants/subscriber.ts, react/features/visitors/components/web/JoinMeetingDialog.tsx
- fix(visitors): Do not show reactions icon in visitors join dialog.
- fix(visitors): Visitors raise hand to be promoted, skip notification for speak line.
=> Visitors UI fixes

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java
=> fix(android) fix crash when staring ongoing notification

react/features/dynamic-branding/middleware.native.ts
On mobile (React-Native) the sharedVideoAllowedURLDomains property from dynamic branding was filtered and therefore the allow list from the branding was not reaching redux and was ignored.
=> fix(RN/shared-video): sharedVideoAllowedURLDomains prop from branding.

react/features/participants-pane/components/web/MeetingParticipantItem.tsx, react/features/shared-video/actions.any.ts, react/features/shared-video/functions.ts, react/features/shared-video/middleware.any.ts
- feat(participants-pane): Fixes actions menu when sharing video.
- feat(shared-video): Fixes showing thumb on the sharer side.
=> shared video local participant

resources/prosody-plugins/mod_fmuc.lua
=> feat(visitors): Adds option to turn off auto promotion with token.

react/features/base/tracks/actions.any.ts, react/features/device-selection/components/VideoDeviceSelection.web.tsx, react/features/device-selection/functions.web.ts, react/features/settings/actions.web.ts, react/features/settings/components/web/video/VideoSettingsContent.tsx
Some parts of the ui still showed the setting for flipping the video, even if the flag indicated otherwise Also fixes the case where setting a virtual background ignores the stored localFlipX setting
=> fix: correct inconsistencies between disableLocalVideoFlip flag and UI

resources/prosody-plugins/mod_muc_breakout_rooms.lua
When reporting the real jid, nothing matches in jicofo internals and we miss to match the room.
=> fix(breakout-rooms): Fixes reporting virtual jid of main room.

debian/jitsi-meet-prosody.postinst
Testing clean install on Ubuntu 24.04 seems to end up with jicofo not connected due to the certificate not being validated.
=> fix(deb): Restart jicofo on new install.

debian/control
When testing on 24.04 fails to create let's encrypt successfully because the webserver(nginx) is not installed completely.
=> fix: Fixes installing let's encrypt on clean system.

react/features/settings/components/native/ModeratorSection.tsx, react/features/settings/components/web/ModeratorTab.tsx
Does not allow toggling both follow me and follow me recorder. And make when locally enabled show correct status when follow me recorder is selected.
=> fix(follow-me): Small UI fixes.

react/features/base/config/functions.any.ts, react/features/settings/components/web/audio/AudioSettingsContent.tsx, react/features/settings/components/web/video/VideoSettingsContent.tsx, react/features/toolbox/components/web/DialogPortal.ts
**Description:** When user use the keyboard navigation and open video or audio settings under menu the focus should move and stay in the under menu till the under menu closed.
**Actual Behavior:** 
1- After opening the menu using keyboard navigation, user have navigate with tap on all toolbar buttons to reach it.
2- The keyboard focus with tap move to other elements (buttons) even if the menu is open.
3- If the menu is open and the focus on other element press ESC doesn't close it. 
**Expected Behavior:** 
1- After opening the menu using keyboard navigation, the focus should move directly to the menu.
2- The focus should stay in inside the menu.
3- By clicking ESC closed the menu and move the focus back to the button.
Before:
https://github.com/user-attachments/assets/f26bd5c8-47b9-44e3-a7 …
=> Accessibility: keyboard navigation on the toolbar (Context menu)

react/features/display-name/components/web/StageParticipantNameLabel.tsx, react/features/display-name/functions.ts, react/features/subtitles/components/web/Captions.tsx, react/features/toolbox/functions.web.ts
=> feat(stage-name-label): Don't show for SS when toolbar is hidden

react/features/filmstrip/components/web/Thumbnail.tsx
- large video does not adhere to the same restriction when it comes to the flip mode, it simply respects the last cached state or the `doNotFlipLocalVideo` flag if it was provided
=> fix: flip mode can be unsynced between tileview and large video

react/features/conference/components/native/Conference.tsx
Fixes error where incoming call is answered while app is in background.
=> feat(conference): render reduced ui when app is in background

react/features/face-landmarks/FaceLandmarksDetector.ts
This fixes an issue where a user gets stuck on lobby page when they have a muted video track after the user is accepted.
=> fix(face-landmarks) Ignore muted tracks while starting detection.

react/features/base/jwt/functions.ts, react/features/invite/functions.ts, react/features/recording/actions.any.ts, react/features/recording/components/LiveStream/AbstractLiveStreamButton.ts, react/features/recording/components/Recording/AbstractStartRecordingDialogContent.tsx, react/features/recording/functions.ts, react/features/recording/hooks.web.ts, react/features/subtitles/middleware.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/functions.any.ts, react/features/transcribing/functions.ts
Fixes an issue where we were showing cc button for visitors that does not have features in the token.
=> fix(jwt): Use isJwtFeatureEnabled the same way in all places.

conference.js, react/features/keyboard-shortcuts/actions.native.ts, react/features/keyboard-shortcuts/actions.web.ts, react/features/keyboard-shortcuts/middleware.ts, tsconfig.native.json
Currently we add keyboard listeners on conference join but never remove them. In the cases where we have multiple join events during a call (visitors promotion, breakout rooms), there are multiple keyboard handlers added and the shortcuts are executed multiple times on a single press.
=> fix(KbShortcuts): remove listeners on leave.

react/features/toolbox/components/web/Toolbox.tsx
**Description:** when user use the keyboard navigation and have the focus on the toolbar. this focus should stay till the user tab out of the toolbar.
**Actual Behavior:** Toolbar menu disappear after a certain time even with the focus on it.
**Expected Behavior:**  Toolbar should stay visible on focus (and closed on blur) and on mouse hover (and closed on mouse out).
before: 
https://github.com/user-attachments/assets/3590ca27-efe5-41d6-b120-c8a9c5ef3979
after:
https://github.com/user-attachments/assets/fd8ac3d2-0d41-4b1a-9dcf-e33db4c70518
issue jitsi community:  https://community.jitsi.org/t/accessibility-keyboard-navigation/133334
=> Accessibility: keyboard navigation on the toolbar

react/features/base/jwt/functions.ts
The backend initializes them as all missing, this way we sync backend and UI.
=> fix(jwt): Fix initial value of features in jaas mode.

resources/prosody-plugins/mod_auth_token.lua
PR fixes the typo. `params` should be checked before getting `params.token`,
not `query` which is already checked before this `if` clause.
=> fix(auth_token): check params before getting its property

config.js, lang/main.json, react/features/base/config/configType.ts, react/features/base/premeeting/actionTypes.ts, react/features/base/premeeting/actions.web.ts, react/features/base/premeeting/components/web/ConnectionStatus.tsx, react/features/base/premeeting/components/web/PreMeetingScreen.tsx, react/features/base/premeeting/constants.ts, react/features/base/premeeting/functions.ts, react/features/base/premeeting/reducer.web.ts, react/features/base/premeeting/types.ts
Adds the possibility of enabling a pre-call test to run on the pre-meeting screen. Depends on https://github.com/jitsi/lib-jitsi-meet/pull/2578
Screenshots of how this looks:
---
---
--- 
---
=> feat(premeeting): pre-call connection test

conference.js, react/features/prejoin/actions.web.ts
It was possible that join can be executed before conference.init have even started or we haven't reached the point ot create the initialGUMPromise. This was causing the following issues:
- users stuck on the prejoin screen
- participants join 2+ times in the call (we have been creating more than 1 local participants from a single page).
=> fix(conference): Make sure join waits for confernce.init.

react/features/connection-indicator/components/web/ConnectionIndicatorContent.tsx, react/features/connection-stats/components/ConnectionStatsTable.tsx
It shows all the time otherwise, confusing users who haven't even enabled it.
=> fix(e2ee) don't display E2EE verified field until final

react/features/mobile/background/middleware.native.ts
Because there is no change taking place when the app mounts, we need to force registering the appState status.
Related to #15167
=> chore(appState): default empty string state does not check conditions

react/features/mobile/call-integration/middleware.ts
The will-join event happens before we actually try to join and things
would go wrong, whereas join-in-progress happens when it's guaranteed
that joining will be successful.
=> fix(rn,call-integration) use a more reliable event for starting

react/features/base/media/constants.ts, react/features/base/tracks/actions.native.ts, react/features/toolbox/functions.native.ts
With the advancements in layer suspension it should now be ok to do. Users can still mute the camera themselves if they so desire.
Having the camera enabled while in the background is a separate effort.
=> feat(rn,screen-sharing) allow sharing the screen and camera on mobile

react/features/base/conference/reducer.ts, react/features/lobby/actions.any.ts, react/features/lobby/middleware.ts, react/features/lobby/reducer.ts, react/features/notifications/middleware.ts
Fixes several issues:
- The error on lobby deny is not sticky
- When preJoin is not enabled we were showing conference UI and showing the error, while the participant is denied to enter the meeting.
- There was inconsistent state (after deny we were keeping membersOnly conference state) and when being approved on re-try while being in the meeting, no remote thumbnails are shown although media is flowing.
The scenario is enabling lobby and tryintg to join, denying the first attempt and approving the second one.
=> fix(lobby): Inconsistent state after deny and then approve.

css/_chat.scss
Navigating via keyboard to the chat container enables scrolling via arrow keys. No focus is visible on the container.
This adds the focus according to [WCAG v2.2 Criterion 2.4.7 Focus Visible](https://www.w3.org/TR/WCAG22/#focus-visible).
=> fix(chat): show focus on chat

lang/main.json, react/features/base/ui/components/native/buttonStyles.ts, react/features/polls/components/native/styles.ts
It seems that react-native-paper Button no longer needs force capitalisation on its label.
Right now only the first word gets capitalised.
Fixes #15224.
=> feat(base/ui): remove force capitalize from button labels

lang/main.json, react/features/prejoin/components/web/preview/DeviceStatus.tsx, react/features/prejoin/functions.any.ts, react/features/prejoin/reducer.ts
- don't show the indicator if disableInitialGUM=true
- Change the text.
- Change the pending state color.
=> fix(prejoin): Device indicator.

react/features/base/media/components/web/Video.tsx, react/features/device-selection/components/VideoInputPreview.web.tsx, react/features/settings/components/web/video/VideoSettingsContent.tsx, react/features/virtual-background/components/VirtualBackgroundPreview.tsx
- Do not throw the error. This results in unhandled rejection promise.
- Add proper logging so that we can figure out from which video element the error occured.
=> feat(Video): Handle .play() errors.

.github/workflows/ci.yml
We need Xcode 16 and that version is now only available on macOS 15 action runners: https://github.com/actions/runner-images/issues/10703
=> fix(ci) use macOS 15 to run iOS tests

react/features/conference/components/native/Conference.tsx
There seems to be an issue related to FlatList component. It was introduced after we updated to a newer version of React Native. Transitioning the app from background to foreground triggers re-renders that affect the visible remote participants, at least in tile view, by sometimes removing them from the list.
=> feat(conference): revert fix for background app state

react/features/prejoin/actionTypes.ts, react/features/prejoin/components/native/Prejoin.tsx
I am not sure what was the reason behind that implementation, but I see no reason to keep it.
It breaks joining a meeting from external/calendar link while in another meeting.
=> feat(prejoin): fix join meeting from external/calendar link while in another meeting

react/features/subtitles/actionTypes.ts, react/features/subtitles/actions.any.ts, react/features/subtitles/middleware.ts, react/features/subtitles/reducer.ts
If a non final transcript was displayed and then hidden and then we receive a final transcript we remove the part that has already been shown before. If the final transcript is the same as the non final that was already displayed we don't show the final.
=> feat(subtitles): Don't show delayed final

modules/API/API.js, modules/API/external/external_api.js
(closes old issue: https://github.com/jitsi/jitsi-meet/issues/9399)
New API command to change the virtual background with a custom base64 image.
```javascript
// Command
api.executeCommand('setVirtualBackground', false, 'data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==');
// Function
api.setVirtualBackground(true, 'data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==');
```
=> feat(external_api) add function to toggle virtual background

react/features/external-api/middleware.ts
We cannot look up the name as the meeting is left and data has been cleaned up already. The value is coming from ljm and the reported actor: JitsiParticipant.
=> feat(external-api): Fix reporting kicker display name.

react/features/base/config/extraInterfaceConfigWhitelist.ts, react/features/base/config/interfaceConfigWhitelist.ts, react/features/base/react/components/web/InlineDialogFailure.tsx, react/features/base/react/functions.ts, react/features/dynamic-branding/middleware.native.ts, react/features/dynamic-branding/reducer.ts, react/features/notifications/components/web/Notification.tsx
=> fix(supportURL): Override true dynamic branding only.

android/app/build.gradle, android/build.gradle, android/scripts/release-sdk.sh, android/sdk/build.gradle, android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java, ios/Podfile, ios/Podfile.lock, ios/app/app.xcodeproj/project.pbxproj, ios/scripts/release-sdk-lite.sh, ios/scripts/release-sdk.sh, ios/sdk/sdk.xcodeproj/project.pbxproj
=> feat(react-native): enable hermes engine

config.js, react/features/base/config/configType.ts, react/features/recording/actions.any.ts
\+ have it disabled by default
=> feat(config) add option to show recording link

react/features/toolbox/components/web/Toolbox.tsx
=> feat(toolbox): adapt toolbox and hang up menu visibility to mobile web

android/build.gradle, android/sdk/build.gradle
=> feat(android): hermes and react native are synced

react/features/visitors/middleware.ts
Make sure there are several connects before slowing down the visitor trying to join. This slow down is handling the case where the meeting was live few minutes ago, but ended.
=> fix(visitors): Fixes slowing down after meeting becomes live.

react/features/whiteboard/functions.ts
selecting a particular shard messes up the collab
=> fix(whiteboard) simplify room hash generation to cover custom region shards

resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_visitors.lua
Features that depend on presence and moderator role will start working for visitors (like follow-me).
=> feat(visitors): Propagate moderator role to visitor nodes.

react/features/base/flags/constants.ts, react/features/base/tracks/actions.native.ts, react/features/mobile/picture-in-picture/components/PictureInPictureButton.ts
=> feat(base/tracks): removed pip limitation while screensharing

modules/API/API.js, modules/API/external/external_api.js, react/features/always-on-top/Toolbar.tsx, react/features/external-api/middleware.ts, react/features/toolbox/functions.any.ts
=> feat(always-on-top): Updates buttons for visitors.

react/features/base/conference/functions.ts, react/features/base/i18n/middleware.ts, react/features/dynamic-branding/reducer.ts
It will be used as the default if specified.
=> feat(dynamic-branding) support setting transcription language

react/features/base/config/middleware.ts, react/features/dynamic-branding/middleware.native.ts
Adds new options that are cloning URL options from the config.
=> feat(dynamic-branding): New options for URLs in config

lang/main-de.json
A small change to the German language file so that “Kamera-Einstellungen” is the same spelling as “Ton-Einstellungen”
=> change german language (main-de.json) videoSettings from Kameraeinstellungen to Kamera-Einstellungen

lang/main.json, react/features/conference/actions.native.ts, react/features/conference/middleware.web.ts, react/features/external-api/middleware.ts, resources/prosody-plugins/mod_muc_kick_jigasi.lua, resources/prosody-plugins/mod_muc_kick_participant.lua
Extend jigasi kick endpoint to accept participantId param which allows for kicking any participant from a session.
=> feat(prosody): extend jigasi kick endpoint to work for any participant

react/features/shared-video/components/web/SharedVideo.tsx
It fixes an issue where people can see ads from YouTube, allowing them to click the Skip Ad button. If you by mistake pause, the next time sync will unpuase it.
=> fix(shared-video): Removes disable pointer for non moderators.

resources/prosody-plugins/mod_polls.lua
=> fix(polls): Returns an error on duplicate poll.

package-lock.json, package.json, tests/helpers/Participant.ts, tests/helpers/participants.ts, tests/helpers/types.ts, tests/pageobjects/ChatPanel.ts, tests/pageobjects/Toolbar.ts, tests/specs/3way/codecSelection.spec.ts, tests/specs/alone/chatPanel.spec.ts, tests/wdio.conf.ts, tests/wdio.firefox.conf.ts
=> feat(tests): Adds chat panel and codec selection tests.

react/features/analytics/functions.ts
=> feat(URL-overrides): Add metrics.

tests/env.example, tests/helpers/Participant.ts, tests/pageobjects/Filmstrip.ts, tests/pageobjects/InviteDialog.ts, tests/pageobjects/SettingsDialog.ts, tests/pageobjects/Toolbar.ts, tests/specs/2way/fakeDialInAudio.spec.ts, tests/specs/3way/followMe.spec.ts, tests/specs/alone/dialInAudio.spec.ts, tests/specs/alone/invite.spec.ts, tests/specs/helpers/DialIn.ts
=> feat(tests): Adds follow-me and invite dialog test.

package-lock.json, package.json, webpack.config.js
Updates the rnnoise-wasm version to use the newest release model.
Note,  @jitsi/rnnoise-wasm uses the newest model for actual noise suppression, however it still uses the old model for noise detection, and talk while muted detection as ljm heuristics need to be recalibrated.
=> feat(rnnoise): update rnnoise-wasm version

modules/API/external/external_api.js
The new format (using an options object) was introduced 7 years ago. It's about time.
=> fix(external_api) drop legacy constructor arguments

react/features/subtitles/middleware.ts
If we are not requesting any transcription, `language` will be `null` so take that into consideration when checking if we should stop processing a transcription message after firing the API event.
Fixes: https://github.com/jitsi/docker-jitsi-meet/issues/1997
=> fix(subtitles) fix skipping transcription messages

android/build.gradle, android/sdk/src/main/java/org/jitsi/meet/sdk/AudioDeviceHandlerConnectionService.java, android/sdk/src/main/java/org/jitsi/meet/sdk/AudioDeviceHandlerGeneric.java, android/sdk/src/main/java/org/jitsi/meet/sdk/AudioModeModule.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ConnectionService.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java, android/sdk/src/main/java/org/jitsi/meet/sdk/OngoingNotification.java, android/sdk/src/main/java/org/jitsi/meet/sdk/PictureInPictureModule.java, android/sdk/src/main/java/org/jitsi/meet/sdk/RNConnectionService.java, react-native-sdk/README.md
There is a 1.2% cummulative usage change according to [0] and it allows us to simplify some code going forward.
[0]: https://apilevels.com/
=> feat(android) bump minimum required version to 26 aka Oreo

.gitignore, react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/JMOngoingConferenceModule.java, react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/JMOngoingConferenceService.java, react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java, react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/JitsiMeetReactNativePackage.java, react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/RNOngoingNotification.java, react-native-sdk/package.json, react/features/mobile/react-native-sdk/middleware.js
=> feat(react-native-sdk/android): force permissions approval in order to launch RNOngoingNotification

modules/API/API.js
There is no `info` type in `showNotificantion` IFrame API command.
https://github.com/jitsi/jitsi-meet/blob/9846228210d99122710a4a2144aba03478df5775/react/features/notifications/constants.ts#L26
=> Removed info type

react/features/shared-video/components/web/SharedVideo.tsx, react/features/shared-video/functions.ts
Fixes two issues:
- disabling mouse for all large video types, including local shared desktop and prevents clicking link to show content
- as z-index is on top of everything does not allow local shared video to be shared when thumbnail is clicked
=> fix(share-video): Hide element when not shown on large.

react/features/base/premeeting/components/web/PreMeetingScreen.tsx
Previously the there was no tooltip to be shown when the room name was too long
this PR solves the issue
**shows tooltip when text is elided**
https://github.com/user-attachments/assets/714949cb-f7cf-4802-9eac-4ffd23396690
**Doesn't show tooltip when text is not elided**
https://github.com/user-attachments/assets/5791abfd-c6de-4455-ba41-d22722d8fd0f
=> Added tooltip when roomname is elided in the pre meeting screen

react/features/device-selection/components/VideoDeviceSelection.web.tsx, react/features/device-selection/functions.web.ts
Screen-sharing is not supported there.
=> fix(device-selection) hide framerate selection on mobile browsers

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, ios/app/src/AppDelegate.m, ios/app/src/ViewController.m, ios/sdk/src/JitsiMeet.m, ios/sdk/src/JitsiMeetViewDelegate.h, react/features/base/config/configWhitelist.ts, react/features/mobile/external-api/middleware.ts, react/features/toolbox/actionTypes.ts, react/features/toolbox/actions.native.ts, react/features/toolbox/components/native/CustomOptionButton.tsx, react/features/toolbox/components/native/OverflowMenu.tsx, react/features/toolbox/components/native/Toolbox.tsx, react/features/toolbox/components/native/styles.ts
=> feat(toolbox): use custom buttons inside toolbox

react/features/lobby/reducer.ts
Fixes the case when someone enters a wrong password to access the meeting and then clicks back to continue knocking and not showing the knocking state, while still in the Lobby room. The problem was introduced in 721bb4e, on access denied we are being kicked out of lobby room and then knocking state should be cleared.
=> fix(lobby): Fixes wrong password going back to knocking.

react/features/virtual-background/components/UploadImageButton.tsx
The returned object is not an array but array-like. That is, it checks truthy, while having a length of 0.
=> fix(virtual-backgrounds) fix handling empty file list

react/features/toolbox/components/native/CustomOptionButton.tsx, react/features/toolbox/components/native/OverflowMenu.tsx, react/features/toolbox/components/native/Toolbox.tsx, react/features/toolbox/components/native/styles.ts
Yellow button is an SVG data uri
https://github.com/user-attachments/assets/002ab02b-9dc4-4980-8480-b43b0e9746f0
=> feat(toolbox): Fixed background color prop custom buttons

package-lock.json, package.json, react/features/mobile/polyfills/browser.js
Reverts jitsi/jitsi-meet#15557
Try as I may, the situation is f***ed up, because Hermes provies a partial native implementation, but then the `promise` npm package is used a partial polyfill and somehow that doesn't play well with core-js. I give up.
=> Revert "fix(rn,polyfills) use core-js for promise polyfills"

android/build.gradle
=> feat(android): use fresco 3.2.0 in order to fix animation for gifs

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastAction.java, android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ExternalAPIModule.java, ios/sdk/src/ExternalAPI.h, ios/sdk/src/ExternalAPI.m, ios/sdk/src/JitsiMeetView.h, ios/sdk/src/JitsiMeetView.m, react/features/mobile/external-api/middleware.ts, react/features/notifications/constants.ts
=> feat(android/ios): Native API events for show/hide notification

conference.js, react/features/base/conference/middleware.any.ts, react/features/base/tracks/actions.any.ts, react/features/base/tracks/actions.web.ts, react/features/invite/components/add-people-dialog/AbstractAddPeopleDialog.tsx, react/features/noise-suppression/actions.ts, react/features/notifications/actions.ts, react/features/old-client-notification/middleware.tsx, react/features/prejoin/actions.web.ts, react/features/recording/actions.any.ts, react/features/recording/components/Recording/AbstractStartRecordingDialog.ts, react/features/recording/middleware.ts, react/features/room-lock/middleware.ts, react/features/transcribing/middleware.ts, react/features/videosipgw/middleware.ts
There are many cases where the error disappears and users easily miss the information.
=> feat(notifications): Make all error notifications sticky.

react/features/conference/components/web/Conference.tsx
When navigating via keyboard (tab key) the empty conference info is focus able and will be focused before getting to the name input.
The creation of the component is disabled if the prejoin or lobby screen is active, so navigation can jump right to the name field. 
This is related to [WCAG Success Criterion 2.4.7 Focus Visible](https://www.w3.org/TR/WCAG22/#focus-visible).
=> fix(prejoin): do not show conference info in prejoin or lobby

react/features/room-lock/components/PasswordRequiredPrompt.web.tsx
Fixes the following: Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
Detected due to failure while moving locked room test.
=> fix: Fixes wrong state in password dialog.

conference.js, modules/API/API.js, modules/API/external/external_api.js, react/features/base/tracks/actions.web.ts, react/features/desktop-picker/components/DesktopPicker.tsx
In order to use gDM in Electron the flow is somewhat reversed. It starts from the Electron main process, so we need an API in the external_api that can trigger the builtin picker. The picker is still necessary.
=> feat(external_api) facilitate gDM Electron

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastAction.java, android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ExternalAPIModule.java, ios/sdk/src/ExternalAPI.h, ios/sdk/src/ExternalAPI.m, ios/sdk/src/JitsiMeetView.h, ios/sdk/src/JitsiMeetView.m, react/features/mobile/external-api/middleware.ts
=> feat(android/ios): start/stop recording events for native

react/features/base/tracks/actions.any.ts
Fixes an issue where p2p peer stops rendering remote video when the mobile client toggles camera. This happens only when the peer starts video muted.
=> fix(tracks) Replace the tracks directly on camera toggle.

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/filmstrip/components/web/Thumbnail.tsx
Add a new parameter in config.js to disable camera tint foreground of focused user
Linked to https://github.com/jitsi/jitsi-meet/issues/15513
Handbook PR : https://github.com/jitsi/handbook/pull/559/files
Contributors guide: https://github.com/jitsi/jitsi-meet/blob/master/CONTRIBUTING.md
=> Feature : Add config to disable camera tint foreground

modules/API/API.js
setRequestingSubtitles requires the last parameter in certain format.
=> fix(iframeAPI): Fix setSubtitles command language param.

package.json, tests/env.example, tests/helpers/browserLogger.ts, tests/helpers/participants.ts, tests/helpers/types.ts, tests/pageobjects/LargeVideo.ts, tests/pageobjects/Notifications.ts, tests/pageobjects/ParticipantsPane.ts, tests/pageobjects/SecurityDialog.ts, tests/specs/3way/audioVideoModeration.spec.ts, tests/specs/3way/avatars.spec.ts, tests/specs/3way/lobby.spec.ts, tests/wdio.conf.ts, tests/wdio.firefox.conf.ts, tests/wdio.grid.conf.ts, tests/wdio.grid.firefox.conf.ts
Will be working on some PR-testing changes.
=> Test improvements

react/features/conference/components/native/LonelyMeetingExperience.tsx
Hiding this button if add people feature flag is disabled or if there are > 1 participants in the meeting
=> feat(conference/native): hide LonelyMeetingExperience button

react/features/base/react/components/web/Message.tsx, react/features/chat/components/web/ChatMessage.tsx
When using a screen reader the chat is not easily perceivable.
This is related to [WCAG Success Criterion 1.3.1 Info and Relationships](https://www.w3.org/TR/WCAG22/#info-and-relationships).
- Move screen reader helper text in the message to link it  to the message
- Messages in paragraphs
- Reactions in paragraphs
=> fix(chat): restructure chat messages

tests/helpers/Participant.ts, tests/helpers/participants.ts, tests/helpers/types.ts, tests/specs/alone/invite.spec.ts
We have few options:
- iframeAPI tests generating tokens via jwtPrivateKeyPath
- tests that just use provided JWT_ACCESS_TOKEN for the first participant to avoid deployments where initial authentication is required
- tests that does not use iframeAPI, but want to use the jwtPrivateKeyPath for a meeting (invite test as JWT_ACCESS_TOKEN does not satisfy some services)
=> feat(tests): Fixes the checks when to use token.

css/_meetings_list.scss
Hi, this fixes issue #15693
The delete button now shows up for smaller screens
=> fixes issue #15693

css/_base.scss, css/_variables.scss
The `z-index` of the `PremeetingScreen` is `252` while the watermarks  only have the `z-index` of `2` or `100` for the "powered by". This hides the watermarks behind the content panel.
If the watermarks are hidden by design here, they should be conditionally excluded from the DOM, as they can be navigated to via keyboard. This breaks the sequential navigation required for accessibility.
I opted to bring the Watermarks to the top, as determining which view is currently active (prejoin, lobby or active conference) and bringing this information down to `Watermarks` (`Conference -> LargeVideo -> Watermarks`) seems a lot more hassle, but can be implemented that way, too.
=> fix(watermarks): bring watermarks to the top

modules/API/API.js, modules/API/external/external_api.js
As there is a Jicofo option to use a random name in the Jitsi embedded Etherpad, it could be nice to be able to get it from the iframe API.
So, I propose to add a getSharedDocumentUrl function in the external API to get it.
Regards
=> External api expose shared document url

react/features/base/tracks/actions.any.ts, react/features/base/tracks/actions.web.ts
Mobile web browsers may not allow opening multiple cameras at the same time, this is a limitation coming from the underlying paltform. As such, avoid createing a new track before we have disposed the previous one.
This does introduce a _slight_ fade to back effect, but the alternative is an exception, so I'll take it! To make matters worse, this is not necessarily a problem with all devices. It has been observed in a Samsung S24, at least.
=> fix(tracks) fix toggleCamera on mobile web browsers

tests/specs/3way/codecSelection.spec.ts
=> fix(test): VP9 is enabled in Firefox 136.

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java, ios/sdk/src/JitsiMeetView.m, react/features/base/ui/Tokens.ts
Avoids a "flicker" effect when the SDK is launched and assets are being loaded.
=> fix(android,ios) set native view background matching JS

lang/main.json
changed the text 
**allow attendees to start their video** ---> **allow non-moderators to start their video** 
this fix was proposed by @Calinteodor in pr #15764
=> changes video permission text for non-moderators 

react/features/settings/components/web/NotificationsTab.tsx
Regarding [WCAG Success Criterion 1.3.1 Info and Relationships](https://www.w3.org/TR/WCAG22/#info-and-relationships) groups of checkboxes should be contained in a `fieldset` and be labeled by a `legend`, for assistive technologies. A `fieldset` should further be part of a `form` element.
=> fix(settings): notification tab restructure

tests/specs/3way/audioVideoModeration.spec.ts
Avoids a race in the participants pane.
=> fix(test) use filmstrip to audio mute in av moderation

tests/helpers/Participant.ts, tests/specs/2way/mute.spect.ts
This is caused by the redirect we do during hangup.
=> fix(test): Fixes failing to hangup a participant.

package.json, react-native-sdk/package.json
The dependency is now gone from strophe.js so we don't need to override it.
=> fix(deps) remove xmldom override

react/features/welcome/components/WelcomePage.web.tsx
This PR fixes an issue where external links (e.g., App Store, Google Play, and F-Droid links) were opening in the same tab instead of a new one.
Added target="_blank" to open external links in a new tab.
Included rel="noopener noreferrer" for security and performance improvements.
(from [meet.jit.si](https://meet.jit.si/))
=> Fix External Links Opening in Same Tab

tests/wdio.conf.ts
In newer versions of wdio this is handled, but now in case of error at this level the test is missing from the result xmls.
=> fix(tests): Avoid error after tests.

android/app/build.gradle
Fixes #15827 
Added applicationIdSuffix = ".debug" to the debug build, allowing both release and debug APKs to be installed simultaneously.
=> chore(android): add build type separation and debug app

ios/sdk/src/JitsiAudioSession.m
We don't really rely on this and it may play nicer with those using RTCAudioSession at the same time as a conference.
=> fix(ios) skip check for manual audio in (de)activateWithAudioSession

react/features/settings/components/web/audio/MicrophoneEntry.tsx, react/features/settings/components/web/audio/SpeakerEntry.tsx
The used `aria-posinset` and `aria-setsize` combination is based on a starting count of 1, but the used index is based on a 0 starting count.
With 3 devices:
Device 0 out of 3.
Device 1 out of 3.
Device 2 out of 3.
The index gets one added to correct to:
Device 1 out of 3.
Device 2 out of 3.
Device 3 out of 3.
=> fix(audio-devices): fix index as pos in set

react/features/base/config/configType.ts, react/features/base/config/functions.native.ts, react/features/base/logging/JitsiMeetLogStorage.ts, react/features/base/logging/middleware.ts
Attach LogCollector rtcstats storage to the ljm rtcstats service lifecycle.
Logs will only get sent once the trace connection is available, otherwise they will be cached.
Add a configurable max cache size, so that we don't miss out on any logs in between flush intervals.
=> feat(rtcstats): attach LogCollector storage to rtcstats lifecycle

react/features/base/react/components/native/SlidingView.tsx, react/features/conference/components/native/Conference.tsx, react/features/prejoin/components/native/Prejoin.tsx
Removes BackHandler.removeEventListener to support react-native 0.77+.
Resolves https://github.com/jitsi/jitsi-meet/issues/15864.
=> Removes BackHandler.removeEventListener

react/features/virtual-background/components/UploadImageButton.tsx
Add the `button` role to `<input type="file">` for image upload. Most browsers render this type of input as a button, but there is no default role for this. As the `UploadImageButton` is a button, this role makes the most sense.
=> fix(UploadImageButton): add accessibility role

react/features/overlay/components/web/PageReloadOverlay.tsx, react/features/prejoin/components/web/preview/DeviceStatus.tsx
Items with `role="heading"` were missing the mandatory complementary attribute `aria-level`.
=> fix(overlay|prejoin) Added level to items with heading role

react/features/desktop-picker/components/DesktopPicker.tsx
If the desktop picker window is closed before we load the sources, a JS error is thrown. From there the app goes into a broken state where when the screen sharing button is pressed nothing happens.  Explanation:
When the error from the _onCloseModal handler is thrown we don't reach the line to call the onSourceChoose callback. The result is that we never call the callback received by setDisplayMediaRequestHandler. It seems that when this happens on subsequent gDM calls electron won't call the setDisplayMediaRequestHandler and therefore we don't display the desktop picker.
=> fix(DesktopPicker): Stops displaying if closed too fast.

resources/prosody-plugins/util.lib.lua
This was broken and was passing as room_node as room_name even for tenant meetings.
=> fix(prosody): Fixes extracting domain when more cases.

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
The fix allows Jibri to work through websocket.
See [the related topic](https://community.jitsi.org/t/possible-bug-bosh-doesnt-work-by-default/138391/12) in forum for more details.
=> fix(prosody): Add consider_websocket_secure into Prosody config

package-lock.json, package.json, react/features/rtcstats/RTCStats.ts
We either expose those events in LJM or live with strings since they match standard WebRTC states, but depending on the package just for 3 events is just not right.
=> fix(rtcstats) drop unnecessary dependency

resources/prosody-plugins/mod_polls.lua
We need to return something other than nil in order to halt the processing of the event.
https://prosody.im/doc/developers/moduleapi#modulehook_event_name_handler_priority
=> fix(polls) halt processing of malformed polls

lang/main-de.json
The German translation didn't announce the participants count in the accessibility label. This is now more in line with the English source.
=> fix(participants): fix dynamic participants count in german translation

package-lock.json, package.json, react/features/recording/components/Recording/LocalRecordingManager.native.ts, react/features/recording/components/Recording/LocalRecordingManager.web.ts, react/features/recording/functions.ts
Use the `showSaveFilePicker` File System Access API to pre-select the file for download and stream the contents there. The browser uses a temporary file as the buffer, thus not requiring us to buffer the contents in memory.
Also change the container to MP4, since we have no way to fix the seeking problem since we don't have the file in memory. Good news is that it's supported since Chrome 126 and we can feature detect it!
Finally, add a helper `isSupprted` method which feature-detects everything we need to make this work.
Ref: https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker
Ref: https://groups.google.com/a/chromium.org/g/blink-dev/c/p1OMVj1FrMI/m/6FdLk7rZAQAJ
=> feat(local-recordings) remove recording time limit

resources/prosody-plugins/mod_filter_iq_rayo.lua
Make sure we add string values to the stanza.
=> fix(prosody): Fixes filter rayo message when int id is used.

react/features/recording/actionTypes.ts, react/features/recording/actions.any.ts, react/features/recording/functions.ts, react/features/recording/middleware.ts, react/features/recording/reducer.ts
A given recording should only trigger a single consent request.
The mechanism to notify about recording status updates may fire multiple
times since it's tied to XMPP presence and may send updates such as when
the live stream view URL is set.
Rather than trying to handle all possible corner cases to make sure we
only show the consent dialog once, keep track of the recording session
IDs for which we _have_ asked for consent and skip the dialog in case we
have done it already.
=> fix(recording) prevent multiple consent requests

config.js, react/features/base/config/configType.ts, react/features/dynamic-branding/reducer.ts, react/features/recording/functions.ts
When turned on, the consent dialog won't be displayed for the users who
are already in the meeting, it will only be displayed to those who join
after the recording was started.
=> feat(recording) add ability to skip consent in-meeting

react/features/settings/components/web/audio/SpeakerEntry.tsx
The reason I extracted the `Test` button from the radio is because we can't have nested interactive elements.
=> Extracted Test button outside the radio button

react/features/base/responsive-ui/actions.ts, react/features/base/responsive-ui/middleware.web.ts, react/features/base/responsive-ui/reducer.ts, react/features/base/ui/components/web/DialogWithTabs.tsx, react/features/filmstrip/actions.web.ts, react/features/filmstrip/components/web/Filmstrip.tsx, react/features/filmstrip/components/web/MainFilmstrip.tsx, react/features/filmstrip/components/web/StageFilmstrip.tsx, react/features/filmstrip/functions.web.ts, react/features/filmstrip/middleware.web.ts, react/features/filmstrip/subscriber.web.ts, react/features/gifs/components/web/GifsMenu.tsx, react/features/settings/components/web/audio/AudioSettingsPopup.tsx, react/features/settings/components/web/video/VideoSettingsPopup.tsx, react/features/shared-video/components/web/SharedVideo.tsx, react/features/speaker-stats/components/web/SpeakerStats.tsx, react/features/toolbox/components/web/DialogPortal.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/subscriber.web.ts, react/features/video-layout/functions.web.ts, react/features/whiteboard/components/web/Whiteboard.tsx
Currently the clientWidth is not representing the window width but it is representing the available video space width since we are subtracting the width of the participants pane and chat area.
=> ref(responsive-ui): rename clientWidth to videoSpaceWidth.

react/features/base/ui/Tokens.ts, react/features/base/ui/components/web/ContextMenu.tsx, react/features/base/ui/functions.native.ts, react/features/base/ui/functions.web.ts, react/features/subtitles/components/web/Captions.tsx
There are still many places where theme.spacing is expected to be number. Reverting parts of https://github.com/jitsi/jitsi-meet/commit/057dc0e4d251cd8a51e1b711db936adcb71e2a53 .
=> ref(theme): revert spacing to number and not rem.

react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/base/util/spot.ts, react/features/large-video/components/LargeVideo.web.tsx, react/features/recording/functions.ts
Setting the UA string in Electron doesn't propagate the change to the
iframe where the meeting is loaded (:facepalm:).
Thus make it more resilient by trying different things:
- A freshly introduced "iAmSpot" config option, similar to Jibri
- The app ID is present in the UA string, so we can test for that
- As a last-ditch effort, check if the display name is the default
"Meeting Room"
=> fix(spot) make Spot TV detection more resilient

config.js, react/features/base/config/configType.ts, react/features/notifications/actions.ts
Spot is non-interactive, so it will override a timeout.
=> feat(notifications) make sticky notifications duration configurable

package-lock.json, package.json, react/features/recording/components/Recording/LocalRecordingManager.web.ts
After a lot of back and forth, WebM seems to be the only option we really have. In terms of containers and codecs, here is the rundown:
- WebM, any codec: the resulting file is not seekable
- MKV, any codec: the resulting file is not seekable
- MP4, vp9 + opus: video artifacts and audio clipping, file is seekable
- MP4, av1 + AAC: all good, but not supported on Linux :-/
MP4 looked very promising but there is no combination that leads to something that works reliably everywhere, oh well. In addition, MP4 files can be opened with QuickTime on macOS, but not with the codec combination we'd use, so that is somewhat a disadvantage.
So, we are back to where we started: WebM with VP8 and opus. But we need to fix the duration in a potentially long file... the trick is to _only_ fix the duration. …
=> fix(local-recordings) back to WebM format, fix duration

react/features/file-sharing/middleware.web.ts
Stay at 99% completion while we wait for the final reply to the request.
=> fix(file-sharing) don't mark upload as complete until response

tests/specs/2way/iFrameApiTranscriptions.spec.ts, tests/specs/3way/breakoutRooms.spec.ts, tests/specs/alone/iFrameApiRecording.spec.ts, tests/specs/helpers/DialIn.ts
Fixes an issue where breakout tests were hitting the wrong shard.
Waits more for the events after jibri leaves.
=> fix(tests): Tests improvements.

react/features/base/util/loadScript.web.ts
Hi,
Since this commit — [ https://github.com/jitsi/lib-jitsi-meet/commit/e7bed00e84e9958d6e9d9dc8ce0a1c9f1cee68b3](url) — and the migration of the JitsiMeetJS.util.ScriptUtil.loadScript function to TypeScript, the scriptURLs feature in analytics is broken.
The loadScript function signature has changed and now expects an object implementing the ILoadScriptOptions interface, rather than a list of parameters.
This patch updates the code accordingly to restore the expected behavior.
Best regards,
Damien Fetis
=> Fix analytics loadscript call to match new function signature

react/features/file-sharing/constants.ts, react/features/file-sharing/middleware.web.ts, react/features/file-sharing/reducer.ts
Rework sync so uploading multiple files at once or several moderators uploading files simultaneously doesn't break synchronization.
The current room metadata plugin operates on <key,value> pairs and we were using a generic "files" key and using a nested object as our value. Since with every operation the entire object is replaced it's easy to get out of sync because one needs to be sure to have the full state before overwriting it.
This is not realistic.
We'll look into making the metadata plugin more flexible in order to support add / delete operations also on nested objects, but for the time being the following will suffice:
Use a key prefix, so each file has en entry in the room metadata, like so: "files.<the file ID> -> file metadata". This means that when a file is deleted we just …
=> fix(file-sharing) rework sync

react/features/base/config/functions.any.ts, webpack.config.js
Webpack will replace the code so the added condition because `if (true)` in dev mode, which helps when one wants to override anything for testing.
=> feat(build,config) disable config whitelist in dev mode

react/features/subtitles/functions.any.ts
Disable the new CC tab when transcription.enable flag is false in config.
=> fix(CC): Disable when config.transcription.enable=false

react/features/settings/functions.any.ts
When a participant gets kicked out of the meeting, the conference object becomes undefined, so the app crashes and throws 
E  [features/base/app] Error(TypeError){“message”:“Cannot read property ‘getMetadata’ of undefined\nThe error may be correlated with this previous error:\nTypeError: Cannot read property ‘getMetadata’ of undefined\n    at anonymous
=> fix(settings): trying to access getMetadata() of undefined

react/features/base/i18n/dateUtil.ts
Replaces `h` in the `format` call found in `getLocalizedDurationFormatter` with `H` so that the conference timer correctly shows hours instead of `undefined` (see https://day.js.org/docs/en/durations/format for more information).
=> fix(conference): show hours in duration instead of undefined

android/sdk/build.gradle
=> fix(android) drop old JSC dependency

resources/prosody-plugins/mod_muc_meeting_id.lua
Missing namespace can interfere with polls logic.
=> feat(polls): Make sure we check for json messages with no namespace.

react/features/toolbox/constants.ts, react/features/toolbox/hooks.native.ts, react/features/toolbox/types.ts
We need to have the same name for screen share button on both web and native to reduce confusion when config options related to toolbox are changed.
=> feat(toolbox): use the same name for screen share button

android/app/build.gradle
It's only used by really old Chromebooks, and we provide a TWA for those anyway.
=> feat(android) drop support for x86 architecture

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiVideoDecoderFactory.java, android/sdk/src/main/java/org/webrtc/JitsiPlatformVideoDecoderFactory.java
We have observed terrible framerates due to the decoder getting constantly restarted. Surprisingly, this only happens when using the JVB, it does not happen when using P2P with Chromium as the other endpoint.
We shall look into that from the bridge side.
At any rate, I'm disabling the HW video decoder for AV1, which means we will be using dav1d, the software video decoder.
=> fix(android) disable HW AV1 codec

react/features/chat/components/web/Chat.tsx
=> fix: layout issue when only chat tab is visible

react/features/file-sharing/middleware.web.ts
Actually implement what the comment says: we want to cap the progress at 99% so we wait for the request to complete with 200 before going to 100%.
=> fix(file-sharing) fix computing file sharing percentage

resources/prosody-plugins/mod_filesharing_component.lua
In case of file failing to upload we try to remove it, but there was nothing indicated as added before that.
=> feat(filesharing): Adds a nil check.

lang/main.json, react/features/participants-pane/components/web/VisitorsList.tsx, react/features/visitors/VisitorsListWebsocketClient.ts, react/features/visitors/middleware.ts, react/features/visitors/websocket-client.ts
- make sure we don't loose any updates for the visitors list between the time we receive the initial list and suibscribe for updates.
-  fixes an issue where a shared instance of the stomp client was used for the visitors list and the visitors queue. now we use 2 different stomp clients.
- Resolves UI issue that the "Viewers" label appears twice - One for the VisitorsList component (promotion request list) and one for the CurrentVisitorsList component (the list with visitors). Now only one of the labels will be displayed!
=> Visitor list fixes.

config.js, react/features/base/config/configType.ts, react/features/recording/functions.ts
Spot now has support for interacting with the recording consent dialog, so we can remove the flag that prevented it from showing up in a spot room.
=> feat(recording): enable consent dialog on spot

react/features/base/util/embedUtils.native.ts
For all intents and purposes 8x8 apps are integrating the SDK as a 3rd party.
Yes, we are a 1st party of sorts, but that's ok because 8x8.vc allows embedding.
=> fix(rn,embed) remove 8x8 apps from isEmbedded check

android/sdk/build.gradle
Execution failed for task ':app:preBaseDebugBuild'.
The following Android dependencies are set to compileOnly which is not supported:
com.google.j2objc:j2objc-annotations:2.8
=> chore(android/sdk): fix compileOnly set dependency related to rn-video

react/features/visitors/reducer.ts
We were comparing if the number of waiting participants have changed with the wrong property from the state - the number of visitors. The result was that we won't update the state when the new waiting value matches the number of visitors already in the state. Most of the times this will be 0 and we would never go to 0.
=> fix(go-live): waiting not updated correctly.

resources/prosody-plugins/mod_av_moderation_component.lua, resources/prosody-plugins/mod_room_metadata_component.lua, resources/prosody-plugins/util.lib.lua
When setting startMuted we are sending two metadata updates.
=> fix: Avoids sending two metadata updates.

react/features/participants-pane/components/web/CurrentVisitorsList.tsx
• Fix visitor display names showing as blank when names are empty or undefined
• Use configured `defaultRemoteDisplayName` or "Fellow Jitster" as fallback
=> fix(visitors): Add fallback display names for empty visitor names

react/features/base/ui/components/web/ContextMenuItem.tsx, react/features/base/ui/components/web/ContextMenuItemGroup.tsx, react/features/settings/components/web/audio/AudioSettingsContent.tsx, react/features/settings/components/web/audio/MicrophoneEntry.tsx, react/features/settings/components/web/audio/SpeakerEntry.tsx
By using `menu`, `group` and `menuitemradio` we have a more clearly and valid structured html. 
Previously
=> Created valid structure for audio menu

react-native-sdk/README.md, react-native-sdk/android/build.gradle, react-native-sdk/android/src/main/AndroidManifest.xml
- Move namespace declaration to correct location in build.gradle
- Remove deprecated package attribute from AndroidManifest.xml
- Update README with gradle plugin version requirement
- Fix Android namespace configuration for React Native SDK
These changes resolve installation and build errors when integrating the Jitsi Meet React Native SDK into new projects.
Fixes: SDK installation failures on Android with newer Gradle versions
=> fix(react-native-sdk): resolve Android build configuration issues

tests/helpers/Participant.ts, tests/helpers/types.ts, tests/pageobjects/Notifications.ts, tests/pageobjects/PasswordDialog.ts, tests/specs/alone/dialInAudio.spec.ts, tests/specs/alone/iFrameApiInvite.spec.ts, tests/specs/alone/iFrameApiRecording.spec.ts, tests/specs/helpers/DialIn.ts, tests/specs/helpers/jaas.ts, tests/specs/jaas/joinMuc.spec.ts, tests/specs/jaas/passcode.ts, tests/wdio.conf.ts
- **ref: Don't use global context for local state.**
- **ref: Don't use global context to store the pin.**
- **feat: Add a test for setting passcode via settings provisioning.**
- **Use local state.**
- **Remove "data" from context.**
- **ref: Rename a function.**
- **test: Fail quick when join muc fails, assert specific errors (e.g. "token expired").**
=> Add a test for jaas passcode, refactor tests.

react/features/base/config/functions.any.ts, react/features/base/config/reducer.ts
It's still possible to disable it, but when not in an iframe, audio and video tracks will not be created.
When in an iframe, it's ok to let it happen, since the host sit is the one where permissions need to be granted, thanks to permission delegation.
Fixes: https://github.com/jitsi/jitsi-meet/issues/16262
Ref: https://zimzi.substack.com/p/jitsi-privacy-flaw-that-enables-one
=> fix(prejoin) no initial tracks when using URL override to disable it

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/base/config/functions.any.ts, react/features/base/config/reducer.ts
This was causing prejoinPageEnabled to overwrite settings provided by the tests on deployments that still use the legacy config.
=> fix(config): Drops legacy config prejoinPageEnabled.

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
Update regarding #16282 and #16340 
Once we started targeting SDK 35 on a device running Android 15 or higher, by default, we display edge-to-edge.
We can handle overlaps by using insets.
https://developer.android.com/develop/ui/views/layout/edge-to-edge#handle-overlaps
=> chore(android): add top and bottom margin insets for API 35

react/features/recording/functions.ts
It is not available due to cross-origin or not able to start setCaptureHandleConfig in iframe. error 1: Failed to execute 'showSaveFilePicker' on 'Window': Cross origin sub frames aren't allowed to show a file picker. error 2: Failed to execute 'setCaptureHandleConfig' on 'MediaDevices': Can only be called from the top-level document.
=> fix(localrecording): Local recording is not supported in embedded mode.

resources/prosody-plugins/mod_visitors_component.lua
moderator_id can have a user id or a group id, that will make all users from that group be moderators.
=> fix(visitors): Fixes checking for group.

resources/prosody-plugins/mod_muc_end_meeting.lua
=> fix: check if asapKeyServer is empty string

react/features/participants-pane/components/web/FooterContextMenu.tsx
- Fixes text truncation in participants pane footer context menu items (three-dot menu)
- Menu items now wrap to maximum of 2 lines instead of being truncated mid-word
- Improves readability for languages with longer translations (e.g., French)
- Added multiline text wrapping styles to `FooterContextMenu` component
- Styles applied specifically to menu items within the footer context menu only
The fix targets only the participants pane footer context menu (the three-dot menu at the bottom of the participants pane) to avoid affecting other context menus. The multiline wrapping is applied using CSS with:
- `display: -webkit-box`
- `WebkitLineClamp: 2`
- `word-break: break-word`
This ensures text wraps to a maximum of 2 lines with proper word breaking.
=> fix(participants-pane): Allow multiline text in footer context menu

resources/prosody-plugins/mod_muc_lobby_rooms.lua, resources/prosody-plugins/mod_muc_meeting_id.lua, resources/prosody-plugins/mod_muc_rate_limit.lua
In very rare cases a participant can request a room and jicofo join there, but the participant don't show up (waiting for host) so jicofo leaves and in the mean time if someone tries to use the room instance just before and after the room is being destroyed, strange things can occur like web connected and joined to a stale room where nothing is received exchanged compared to the live meeting room.
=> fix(prosody): Avoid using stale room instances.

react/features/base/conference/functions.ts, react/features/base/conference/middleware.native.ts, react/features/base/conference/middleware.web.ts, react/features/base/connection/actions.any.ts, resources/prosody-plugins/mod_muc_end_meeting.lua
Uses the end_meeting endpoint to trigger a silent reconnect by destroying the current conference and passing its jid.
=> feat(conference): Adds option to silently reconnect.

react/features/base/ui/components/web/Tabs.tsx
=> fix(ui): improve tab badge styling

modules/UI/videolayout/VideoLayout.js, react/features/large-video/actions.any.ts, react/features/large-video/functions.ts, react/features/large-video/subscriber.any.ts, react/features/large-video/subscriber.native.ts, react/features/large-video/subscriber.web.ts, tests/pageobjects/Filmstrip.ts, tests/specs/3way/activeSpeaker.spec.ts, tests/specs/3way/codecSelection.spec.ts
Optimizes performance by preventing unnecessary large video updates when the large video container is hidden via CSS in multiple layout modes:
- **Tile view** - Large video is completely hidden
- **Stage filmstrip with 2+ participants** - Large video is hidden, stage participants shown instead
- **Etherpad editing** - Large video is covered by etherpad overlay (z-index)
Previously, `scheduleLargeVideoUpdate()` would trigger expensive operations even when the large video container was not visible, including:
- Setting video streams and managing track listeners
- Updating avatar displays
- Running show/hide animations
- Processing video quality changes
1. **New centralized check** (`react/features/large-video/functions.ts`):
- Added `shouldHideLargeVideo()` function that checks all hidden …
=> fix(large-video): Prevents unnecessary updates when container is hidden
