resources/prosody-plugins/mod_fmuc.lua
=> fix(visitors): Fixes delivering visitors presence to jicofo.

react/features/toolbox/actions.web.ts
=> fix(toolbar) Fix auto-hide toolbar in tileview

react/features/toolbox/actions.web.ts
=> fix(toolbar) Fix auto-hide toolbar in tileview (#13424)

resources/prosody-plugins/mod_rate_limit.lua
=> feat: Adds a stat for limited ips.

package-lock.json, package.json, react/features/base/conference/middleware.web.ts, tsconfig.web.json
=> feat(screen-lock): request on conference join.

react/features/chat/components/web/ChatInput.tsx
=> fix(chat-input) Autofocus when sending private message

resources/prosody-plugins/mod_muc_meeting_id.lua, resources/prosody-plugins/mod_s2s_whitelist.lua
=> fix(visitors): Move some logs to debug.

config.js, react/features/base/config/configType.ts, react/features/base/config/reducer.ts, react/features/e2ee/components/E2EELabel.tsx, react/features/e2ee/components/E2EESection.tsx
=> fix(e2ee) fix config migration of e2eeLabels

react/features/base/devices/functions.web.ts, react/features/base/sounds/functions.web.ts, react/features/base/sounds/middleware.any.ts, react/features/base/sounds/middleware.native.ts, react/features/base/sounds/middleware.web.ts
=> fix(notif-sounds) Set correct audio output device for notifs

react/features/base/toolbox/components/BaseAudioMuteButton.ts, react/features/base/toolbox/components/BaseVideoMuteButton.ts, react/features/lobby/components/native/LobbyScreen.tsx, react/features/prejoin/components/native/Prejoin.tsx, react/features/toolbox/components/AbstractAudioMuteButton.tsx, react/features/toolbox/components/AbstractVideoMuteButton.tsx, react/features/toolbox/components/native/AudioMuteButton.tsx, react/features/toolbox/components/native/Toolbox.tsx, react/features/toolbox/components/native/VideoMuteButton.tsx, react/features/toolbox/components/web/AudioMuteButton.tsx, react/features/toolbox/components/web/AudioSettingsButton.tsx, react/features/toolbox/components/web/VideoMuteButton.tsx, react/features/toolbox/components/web/VideoSettingsButton.tsx
=> fix(RN): broken build after AV pending changes.

react/features/recording/components/Recording/LocalRecordingManager.web.ts
=> fix(local-rec) Fix audio only recording (self)

react/features/toolbox/middleware.web.ts, react/features/toolbox/subscriber.web.ts
These are web files, no need to check if APP is undefined.
=> fix(toolbox) drop unneeded checks

react/features/base/conference/middleware.web.ts
- Add debug logs.
- Re-request wake lock if it is released by the OS because of page visibility.
=> fix(screenLock): Improve.

react/features/base/devices/functions.web.ts, react/features/base/sounds/functions.web.ts, react/features/base/sounds/middleware.any.ts, react/features/base/sounds/middleware.native.ts, react/features/base/sounds/middleware.web.ts
=> fix(notif-sounds) Set correct audio output device for notifs (#13436)

react/features/base/ui/components/web/Input.tsx, react/features/security/components/security-dialog/web/PasswordForm.tsx
Fixes: https://github.com/jitsi/brave-tracker/issues/101
=> fix(password) use the numeric input mode when only digits are required

.gitignore
=> sdk(react-native-sdk): added generated folders to gitignore

react/features/base/media/components/native/VideoTransform.tsx
https://github.com/jitsi/jitsi-meet/assets/26413496/834aed39-c432-407f-9559-9ea77262f9d4
=> feat(base/media): fixed movement inside zoomed screenshare

react/features/conference/middleware.ts
=> fix: Adds one more check for iframes.

resources/prosody-plugins/mod_token_verification.lua
=> feature: allowlist checking for token verification module

modules/API/external/external_api.js
=> fix(iframe): Add allow screen-wake-lock.

ios/sdk/src/callkit/JMCallKitProxy.m
Fixes: https://github.com/jitsi/jitsi-meet/issues/12716
=> fix(ios) fix UUID comparison

lang/main.json, react/features/settings/components/native/SettingsView.tsx
This helps us know it at a glance, from applications using it, without having to look at any logs.
=> feat(rn,settings) add field with SDK version

react/features/base/ui/components/web/BaseDialog.tsx
=> fix(dialog) Fix close on backdrop

ios/Podfile.lock, package-lock.json, package.json
Fixes not receiving video in P2P mode when the mobile user starts with video muted and is also the offerer.
=> deps(rn) update react-native-webrtc to 111.0.2

react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/hooks.web.ts
=> ref(toolbar) Convert to function component

react/features/keyboard-shortcuts/utils.ts
=> fix(keyboard-shortcuts) Check modifier key

ios/Podfile.lock, package-lock.json, package.json
Fixes an issue where the transceiverf mid wasn't set.
=> deps(rn) update react-native-webrtc to 111.0.3

react/features/base/jwt/middleware.ts
=> fix(jwt) fix not processing features if avatar, name, email are missing

react-native-sdk/package.json, react-native-sdk/sdk_instructions.js, react-native-sdk/update_dependencies.js
=> sdk(react-native-sdk): added script that updates app dependencies

react-native-sdk/update_dependencies.js
=> sdk(react-native-sdk): fixes

ios/Podfile.lock, package-lock.json, package.json
I propose this update because it was needed while testing RNSDK.
Nothing suspicious on both android and ios.
=> deps(react-native-screens): updated to latest

react/features/base/i18n/BuiltinLanguages.native.ts
Fixes jitsi-meet/[Mobile SDKs] Ukrainian language #13401
=> fix: add Ukrainian lang to builtinLanguages native

react-native-sdk/README.md
=> sdk(react-native-sdk): update README file

react/features/settings/components/web/SettingsDialog.tsx
Fixes: https://github.com/jitsi/jitsi-meet/issues/13461
=> fix(settings) fix when devices tab is not visible

patches/react-native-immersive+2.0.0.patch
=> deps(patch/react-native-immersive): replaced removeListener deprecated method

lang/main.json, react/features/base/conference/middleware.any.ts, react/features/base/connection/actions.web.ts
=> fix(local-rec) Download recording on end meeting

react/features/app/actions.native.ts, react/features/base/flags/constants.ts, react/features/mobile/navigation/components/RootNavigationContainer.tsx, react/features/prejoin/functions.ts
=> feat(base/flags): created flag to control unsafe room warning

react/features/feedback/components/FeedbackDialog.web.tsx
=> ref(feedback) Convert dialog to function component

react/features/base/conference/middleware.any.ts
The dispatches were not ordered and sometimes disconnect was executed just after connect and you end up in disconnected state.
=> fix: Fixes joining visitor.

react-native-sdk/README.md
=> fix(rnsdk) update README

css/_base.scss, react/features/settings/components/web/MoreTab.tsx
=> fix(css) fix cut off borders and barely visible scrollbars

react-native-sdk/README.md
=> add Syntax highlighting to README

config.js, react/features/base/config/configType.ts, react/features/settings/components/web/SettingsDialog.tsx, react/features/virtual-background/components/VideoBackgroundButton.ts, react/features/virtual-background/functions.ts
Add an option in config file to disable virtual background feature #13495
=> New config disable feature virtual background

react/features/authentication/components/web/LoginDialog.tsx, react/features/base/conference/middleware.any.ts, react/features/prejoin/actions.web.ts
=> fix(authentication): Fixes web login dialog to connect and join.

react/features/notifications/components/NotificationsTransition.tsx
=> fix(notifications) Show correct info on updated notification

lang/main.json, react/features/base/tracks/loadEffects.web.ts, react/features/noise-suppression/actions.ts, react/features/noise-suppression/functions.ts, react/features/noise-suppression/reducer.ts
=> feat(noise-suppression): persist noise suppression setting

react/features/display-name/components/native/styles.ts
=> feat(display-name): fixed display name label

conference.js, config.js, package-lock.json, package.json, react/features/authentication/actions.native.ts, react/features/authentication/actions.web.ts, react/features/authentication/middleware.ts, react/features/base/conference/actions.ts, react/features/base/conference/middleware.any.ts, react/features/base/config/configType.ts, react/features/base/jwt/middleware.ts, react/features/lobby/middleware.ts, resources/prosody-plugins/mod_muc_lobby_rooms.lua, resources/prosody-plugins/mod_muc_wait_for_host.lua, resources/prosody-plugins/mod_persistent_lobby.lua, resources/prosody-plugins/token/util.lib.lua, resources/prosody-plugins/util.lib.lua
Adds few modifications(prosody and UI) to the jwt handling which can be used with firebase tokens.
=> Adds waiting for host prosody module

react/features/mobile/external-api/middleware.ts
=> feat(mobile/external-api): fixed screenshare event toggle tracking

react/features/authentication/middleware.ts
=> fix: Fixes redirect to auth url, set_room can be undefined.

react/features/base/connection/actions.web.ts
=> fix(connection): Dispatch _connectInternal.

react/features/app/getRouteToRender.web.ts, react/features/app/middleware.ts, react/features/authentication/functions.ts, react/features/authentication/middleware.ts, react/features/base/app/actionTypes.ts, react/features/base/app/actions.ts, resources/extra-large-conference/prosody.cfg.lua.visitor.template
=> fix: Fixes redirect to token auth URL from welcome page

react-native-sdk/index.tsx, react/features/mobile/picture-in-picture/actions.ts, react/features/mobile/react-native-sdk/middleware.js
Allows the host app to respond to Picture-in-Picture action.
=> (react-native-sdk): Adds `onEnterPictureInPicture` handler prop to JitsiMeeting component

react/features/mobile/react-native-sdk/middleware.js
=> sdk(react-native-sdk): alpha sort actionTypes

react-native-sdk/index.tsx, react/bootstrap.native.js, react/features/app/components/App.native.tsx, react/index.native.js
=> feat(rnsdk) share bootsrap code with app

react-native-sdk/package.json
=> sdk(react-native-sdk): revert version to 0.0.0

resources/update-mobile-rnsdk-version.sh
=> sdk(resources): update-mobile-rnsdk-version script

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastAction.java, android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ExternalAPIModule.java, ios/sdk/src/ExternalAPI.h, ios/sdk/src/ExternalAPI.m, ios/sdk/src/JitsiMeetView.h, ios/sdk/src/JitsiMeetView.m, react/features/mobile/external-api/middleware.ts
add **toggleCamera** action to be able to toggle Camera Facing Mode programmatically
=> feat(api): add toggleCamera action

react/features/participants-pane/components/web/InviteButton.tsx
https://github.com/jitsi/jitsi-meet/issues/13647
=> fix(external-api) extend buttonsWithNotifyClick effect to participants pane invite button

react/features/participants-pane/components/native/ParticipantsConter.tsx, react/features/participants-pane/components/native/ParticipantsPaneButton.tsx, react/features/participants-pane/components/native/styles.ts
=> feat(participants, rn): add count badge to participants buttons

react/features/toolbox/hooks.web.ts
=> fix(shortcuts) toggle value based on current state

config.js, react/features/base/config/configType.ts, react/features/base/toolbox/components/AbstractButton.tsx, react/features/base/toolbox/components/ToolboxItem.web.tsx, react/features/base/ui/components/web/ContextMenuItem.tsx, react/features/toolbox/components/web/CustomOptionButton.tsx, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/functions.web.ts
=> feat(toolbar-buttons) Add optional background color

react/features/base/util/isInsecureRoomName.ts
Consider long room names secure.
=> feat: Caches is secure room checks.

lang/main.json, react/features/authentication/components/index.native.ts, react/features/authentication/components/index.web.ts, react/features/authentication/components/web/LoginQuestionDialog.tsx, react/features/authentication/middleware.ts, react/features/settings/functions.any.ts
=> Authentication updates

react/features/chat/middleware.ts
=> fix(chat) Only display private message dialog for active participants

react/features/authentication/middleware.ts
We were showing the dialog and when waiting for host is shown on prejoin screen.
=> fix: Shows login warning for leaving only when in conference.

react/features/app/getRouteToRender.web.ts, react/features/authentication/actions.any.ts, react/features/authentication/actions.native.ts, react/features/authentication/actions.web.ts, react/features/authentication/components/index.native.ts, react/features/authentication/components/index.web.ts, react/features/authentication/components/native/WaitForOwnerDialog.tsx, react/features/authentication/functions.ts, react/features/authentication/middleware.ts, react/features/base/util/uri.ts, react/features/mobile/navigation/functions.tsx
Supersedes https://github.com/jitsi/jitsi-meet/pull/13686
=> Native authentication alternative

lang/main.json
=> fix(WaitForOwner) tweak copy

react/features/prejoin/actions.web.ts, react/features/prejoin/middleware.web.ts
=> fix: Fixes password authentication on prejoin. Fixes #13721.

react/features/base/i18n/i18next.ts
Thanks @hamletmun for the solution.
=> fix: Fixes i18next trying to fetch non-existing files. Fixes #13716.

react/features/base/media/middleware.any.ts
=> fix: Fixes start A/V muted after going to welcome page. Fixes #11393.

lang/main.json, react/features/authentication/components/native/WaitForOwnerDialog.tsx, react/features/authentication/components/web/WaitForOwnerDialog.tsx, react/features/base/conference/reducer.ts, react/features/lobby/components/AbstractLobbyScreen.tsx, react/features/lobby/components/native/LobbyScreen.tsx, react/features/lobby/components/web/LobbyScreen.tsx, react/features/settings/actions.web.ts
=> Authentication fixes

react/features/base/jitsi-local-storage/setup.web.ts
=> fix(jitsi-local-storage): remove debug log.

react/features/settings/actions.web.ts
It was hanging up and canceling visiting the logout page.
=> feat(authentication): Fixes logging out on web.

react/features/authentication/components/native/WaitForOwnerDialog.tsx
=> feat(authentication): Fix normal authentication

react/features/video-menu/components/native/RemoteVideoMenu.tsx
OG PR #13732 merged in the mobile branch first instead of master.
=> fix(video-menu) hide Grant Moderator inside breakout rooms on native

config.js, react/features/base/config/configType.ts, react/features/conference/components/web/Conference.tsx, react/features/filmstrip/functions.web.ts
=> feat(filmstrip) Add config for disabling vertical filmstrip

config.js, react/features/base/config/configType.ts, react/features/conference/components/web/Conference.tsx, react/features/filmstrip/functions.web.ts
=> feat(filmstrip) Add config for disabling vertical filmstrip (#13752)

react/features/chat/components/AbstractMessageRecipient.ts
=> feat(chat): fixed action import for abstract component

modules/UI/videolayout/VideoContainer.js, package-lock.json, package.json, react/features/base/media/components/web/AudioTrack.tsx, react/features/base/media/components/web/Video.tsx
=> fix: Attempt to fix setSinkId failures.

package-lock.json, package.json, react/features/base/conference/actions.ts, react/features/base/conference/functions.ts, react/features/base/conference/middleware.any.ts, react/features/base/connection/actionTypes.ts, react/features/base/connection/actions.any.ts
=> Sends conference request over http before connecting to xmpp

react/features/mobile/full-screen/functions.ts, react/features/mobile/full-screen/middleware.ts
=> Android full screen fixes

config.js, react/features/analytics/functions.ts, react/features/analytics/handlers/AbstractHandler.ts, react/features/analytics/handlers/AmplitudeHandler.ts, react/features/base/config/configType.ts
=> feat(amplitude): Add amplitude UTM tracking option

react/features/conference/components/web/Conference.tsx, react/features/filmstrip/components/web/Filmstrip.tsx
- there was a problem with pinning the participants from the Participants pane with the previous approach
=> fix(disable-filmstrip) Fix disabling filmstrim through config

modules/API/external/external_api.js, package-lock.json, package.json, react/features/base/connection/actions.any.ts, react/features/base/connection/reducer.ts, react/features/base/connection/types.ts, react/features/base/lib-jitsi-meet/functions.any.ts, react/features/base/util/uri.ts
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/2348
=> feat(iframe-api): replace ice servers

react/features/base/conference/reducer.ts, react/features/settings/actions.native.ts, react/features/settings/actions.web.ts
=> fix(authentication) fix moderator logout

react/features/app/actions.native.ts, react/features/base/conference/reducer.ts
=> feat(app/native): rework appNavigate so callkit video button does not end the call

react/features/prejoin/components/native/Prejoin.tsx, react/features/prejoin/components/native/UnsafeRoomWarning.tsx
I think this is because react hooks are used inside that helper function which is declared outside these components.
=> feat(prejoin/native): fixed screen header hooks warning

ios/Podfile
Fixes: https://github.com/jitsi/jitsi-meet/issues/13274
=> fix(ios) fix compilation with Xcode 14.3

resources/prosody-plugins/mod_muc_wait_for_host.lua
=> fix: Fixes missing import in wait for host module.

react-native-sdk/package-lock.json, react-native-sdk/package.json
=> Update RnSDK deps

debian/jitsi-meet-tokens.postinst
=> Also check single quote

conference.js, modules/devices/mediaDeviceHelper.js, react/features/base/devices/actions.web.ts, react/features/base/devices/constants.ts, react/features/base/devices/functions.web.ts, react/features/base/devices/middleware.web.ts, react/features/base/settings/functions.web.ts
=> Ignore MS Teams virtual device.

react/features/app/actions.any.ts, react/features/app/actions.native.ts, react/features/app/actions.web.ts, react/features/base/jwt/functions.ts
It may happen that the jwt had expired while being in the meeting and there is a network issue requiring to reload.
=> feat: Check jwt expiration and redirects to auth url if any.

react/features/mobile/polyfills/bundler.js, react/features/mobile/polyfills/index.js
Fixes: https://github.com/jitsi/jitsi-meet/issues/13807
=> fix(rn,polyfills) remove no longer needed polyfill

react/features/base/conference/middleware.any.ts, react/features/base/dialog/components/native/InputDialog.tsx, react/features/base/ui/components/web/BaseDialog.tsx, react/features/base/ui/components/web/Dialog.tsx, react/features/display-name/actions.ts, react/features/display-name/components/native/DisplayNamePrompt.tsx, react/features/display-name/components/web/DisplayNamePrompt.tsx, react/features/display-name/types.ts, react/features/prejoin/components/native/Prejoin.tsx, react/features/prejoin/components/native/styles.ts, react/features/prejoin/components/web/Prejoin.tsx, react/features/prejoin/utils.ts
...particularly the scenario where prejoinConfig.hideDisplayName and requireDisplayName are both true
=> fix(prejoin) improve display name handling relative to configs

resources/prosody-plugins/mod_muc_allowners.lua, resources/prosody-plugins/mod_muc_wait_for_host.lua, resources/prosody-plugins/util.lib.lua
The correct place to check for tenant value is jitsi_meet_domain and not jitsi_meet_context_group.
=> fix: Fixes wait for host to respect moderated tenants.

react/features/app/actions.any.ts, react/features/app/getRouteToRender.web.ts, react/features/authentication/functions.any.ts, react/features/authentication/functions.native.ts, react/features/authentication/functions.web.ts, react/features/authentication/middleware.ts
=> fix: Fixes passing the hash params in state for token auth URL.

react/features/always-on-top/AudioMuteButton.tsx, react/features/always-on-top/HangupButton.tsx, react/features/always-on-top/VideoMuteButton.tsx
=> fix(aot) fix icons creating deps to store (#13901)

react/features/shared-video/components/native/VideoManager.tsx
=> feat(shared-video/native): use local logger

react/features/always-on-top/AlwaysOnTop.tsx, react/features/base/avatar/components/Avatar.tsx, react/features/base/avatar/components/web/StatelessAvatar.tsx, react/features/base/avatar/types.ts, react/features/speaker-stats/components/web/SpeakerStatsItem.tsx
=> fix(aot) remove dependency to store

react/features/always-on-top/AlwaysOnTop.tsx, react/features/base/avatar/components/Avatar.tsx, react/features/base/avatar/components/web/StatelessAvatar.tsx, react/features/base/avatar/types.ts, react/features/speaker-stats/components/web/SpeakerStatsItem.tsx
=> fix(aot) remove dependency to store (#13910)

config.js
This PR updates `config.js` and
- add the missing keys into the notification list
- removes unused keys from the notification list
- fixes the alphabetical order of keys
See [this post](https://community.jitsi.org/t/missing-keys-in-the-notification-list/127400)
=> fix(config): add the missing keys into the notification list

react/features/notifications/components/web/Notification.tsx
Fixes https://github.com/brave/brave-talk/issues/1247
=> fix(notifications) Fix case when description is react component instance

resources/update-mobile-rnsdk-version.sh
=> Rnsdk script fixes

react-native-sdk/README.md, react-native-sdk/package.json
=> sdk(react-native-sdk): update readme and dependencies

doc/debian/jitsi-meet/jitsi-meet.example
Enable http2 for nginx as we do it for apache.
=> feat: Enable http2

lang/main.json, react/features/conference/middleware.any.ts
This will allow us to remove translation overrides from branded repo
=> i18n: change iframe disabled message based on current hostname

react/features/prejoin/components/native/Prejoin.tsx
=> feat(prejoin/native): fix display name input on prejoin

package-lock.json
=> fix(deps) run npm audit fix

package-lock.json, package.json, react/features/base/connection/actions.any.ts, react/features/base/connection/reducer.ts, react/features/base/jwt/middleware.ts
=> feat(visitors): Adds an option to request to be visitor based on jwt.

config.js, package-lock.json, package.json, react/features/base/config/configWhitelist.ts
=> ref(config) Drop forceJVB121Ratio from config.js

resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_muc_meeting_id.lua
Filters initial msg for <subject/>.
=> fix(visitors): Fixes filtering initial msgs to main participants.

lang/main-sv.json
=> Fix typos in Swedish localization

package-lock.json, package.json
Fixes: https://github.com/jitsi/jitsi-meet/issues/13998
=> fix(android) fix crash on Android 14

resources/prosody-plugins/mod_muc_allowners.lua
=> fix(moderated): Fixes moderators in moderated rooms without tenant.

modules/API/API.js, modules/API/external/external_api.js
Please read the commit messages.
=> External API ready event

react/features/invite/components/add-people-dialog/AbstractAddPeopleDialog.tsx, react/features/invite/functions.ts
=> feat: Adds region parameter to dial out authorize requests.

resources/prosody-plugins/mod_muc_rate_limit.lua
=> feat: Adds leave rate limit to muc_rate_limit.

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/base/media/middleware.any.ts, react/features/base/tracks/actions.any.ts, react/features/base/tracks/functions.any.ts, react/features/base/tracks/functions.native.ts, react/features/base/tracks/functions.web.ts
=> feat(facing-mode) add config for initial camera facing mode

react/features/recent-list/middleware.ts
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'conference[_$$_REQUIRE(_dependencyMap[8], "../base/conference/constants").JITSI_CONFERENCE_URL_KEY]'
=> feat(recent-list): fix undefined error that breaks visitor joining

resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_muc_allowners.lua, resources/prosody-plugins/mod_muc_breakout_rooms.lua, resources/prosody-plugins/mod_muc_flip.lua, resources/prosody-plugins/mod_muc_lobby_rooms.lua, resources/prosody-plugins/mod_speakerstats_component.lua, resources/prosody-plugins/token/util.lib.lua
=> Clean up prosody modules with some extra checks

modules/API/API.js, modules/API/external/external_api.js, react/features/subtitles/middleware.ts
=> feat(external_api) add event with transcription chunks

react/features/filmstrip/components/native/Thumbnail.tsx, react/features/filmstrip/components/native/styles.ts, react/features/participants-pane/components/native/styles.ts
Visitors
Indicators
https://github.com/jitsi/jitsi-meet/assets/26413496/883b9e8c-f8ef-457b-9175-d9f3870dc8ee
=> feat(participants-pane/filmstrip): latest native UI fixes

resources/prosody-plugins/token/util.lib.lua
Add `jitsi_meet_context_room` into parameter list as a comment
=> fix(token): add jitsi_meet_context_room into the param list

conference.js
Currently we are waiting for the user to submit feedback dialog in order to leave the room. Now the leave and showing the dialog are executed in parallel.
=> fix(conference-hangup): Leave room in parallel.

package-lock.json, package.json
=> chore(package.jsom): Update LJM

react/features/feedback/actions.web.ts, react/features/feedback/functions.web.ts
=> feat(feedback): show even if callstats is disabled

react/features/screenshot-capture/ScreenshotCaptureSummary.tsx
=> fix(pr-test): For LJM

react/features/feedback/components/FeedbackButton.web.ts, react/features/feedback/functions.web.ts
=> fix(FeedbackButoon): display for JaaS meetings.

config.js
=> fix(config): Add the optional screenshare settings.

react/features/app/actions.any.ts, react/features/app/getRouteToRender.web.ts, react/features/authentication/functions.any.ts, react/features/authentication/functions.native.ts, react/features/authentication/functions.web.ts, react/features/authentication/middleware.ts
=> feat(authentication): group config options inside an object param

react/features/authentication/actions.web.ts
=> fix: Fixes login button in profile settings.

config.js
=> fix(config): Add the new codec settings

react/features/base/config/configWhitelist.ts
=> Whitelist config.bridgeChannel.

react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/JMOngoingConferenceModule.java, react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java, react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/RNOngoingNotification.java
=> sdk(react-native-sdk/android): replaced activityContext with currentActivity

react/features/base/i18n/i18next.ts
=> fix(i18n): Fixes retrieving correct countries i18n file.

react/features/mobile/navigation/components/settings/components/SettingsNavigationContainer.tsx, react/features/settings/components/native/SettingsView.tsx, react/features/settings/functions.any.ts
=> feat(settings): make settings screen functional component

react/features/mobile/react-native-sdk/middleware.js
=> feat(react-native-sdk): null error fix for ios

lang/main-es.json
The Spanish translation of mute all was confused with mute everyone else
=> Update spanish translation

debian/jitsi-meet-web.install
=> fix(ci) Fix favicon

.github/workflows/ci.yml
=> feat(ci) test debian packages build

modules/API/API.js
=> feat: Log all API commands.

resources/prosody-plugins/mod_filter_iq_rayo.lua
This can prevent outgoing calls due to error.
=> fix: When host is loaded muc module maybe still be nil in rayo filter.

react/features/mobile/call-integration/middleware.ts
TypeError: undefined is not an object (evaluating 'action.conference.callUUID') _conferenceLeft
=> feat(mobile): fixed undefined is not an object

app.js, react/features/analytics/functions.ts, react/features/analytics/middleware.ts, react/features/base/conference/actions.ts, react/features/visitors/reducer.ts, react/index.web.js
=> feat(analytics): add visitor,prejoin,lobby props

react/features/settings/components/native/ProfileView.tsx
=> feat(settings/native): hide login/logout for 8x8.vc on profile screen

react/features/room-lock/components/PasswordRequiredPrompt.native.tsx
=> fix(rn,room-lock) use numeric input for password dialog if appropriate

modules/API/API.js, react/features/base/i18n/i18next.ts, react/features/mobile/external-api/middleware.ts, react/features/subtitles/actionTypes.ts, react/features/subtitles/actions.any.ts, react/features/subtitles/actions.web.ts, react/features/subtitles/components/AbstractCaptions.tsx, react/features/subtitles/components/AbstractClosedCaptionButton.tsx, react/features/subtitles/components/AbstractLanguageSelectorDialog.tsx, react/features/subtitles/components/native/ClosedCaptionButton.tsx, react/features/subtitles/components/web/ClosedCaptionButton.tsx, react/features/subtitles/middleware.ts, react/features/subtitles/reducer.ts
=> ref(transcriptions): refactor transcriptions api 

react/features/mobile/call-integration/middleware.ts
Changes related to troubles regarding visitors. 
In the end, the problem was with some beta stage configurations.
=> feat(call-integration): revert changes related to visitors

react/features/subtitles/actions.any.ts
=> fix(transcript) duplicated namespace

react/features/toolbox/subscriber.web.ts
fixes https://github.com/jitsi/jitsi-meet/issues/14148
=> fix(toolbox) prevent toolbox shift up on stage view

README.md
It appears https://meet.jit.si no longer allows for starting a meeting anonymously. I've proposed a README update to reflect that.
Very sad.
=> Update README: meet.jit.si no longer anonymous

react/features/toolbox/subscriber.web.ts
=> feat(toolbox): fixed undefined for previous layout type

resources/prosody-plugins/mod_visitors_component.lua
=> feat: Adds a nil check for occupants joining as moderators.

react/features/invite/components/add-people-dialog/native/AddPeopleDialog.tsx, react/features/invite/components/add-people-dialog/native/styles.ts, react/features/security/components/security-dialog/native/SecurityDialog.tsx
https://github.com/jitsi/jitsi-meet/assets/26413496/20224b70-dfeb-4961-8e66-7dc659edf1da
1. FIxed share icon position against safe area view and native keyboard.
2. Fixed Enable lobby mode Switch thumb UI glitch.
=> feat(invite/security):  Brave issues fixes

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts
It is not supported by Jicofo anymore.
=> fix(config): Remove enableLipSync config.

react/features/analytics/actionTypes.ts, react/features/analytics/actions.ts, react/features/analytics/functions.ts, react/features/analytics/middleware.ts, react/features/analytics/reducer.ts, react/features/prejoin/components/native/Prejoin.tsx
=> fix(analytics): Update permanent props.

config.js
=> fix(config): Add testing flag for Av1 support.

react/features/subtitles/middleware.ts
Even if the user is not requesting them.
=> feat(transcriptions) alway send the transcriptionChunkReceived event

android/app/proguard-rules.pro
update pro guard rules from RN source;
https://github.com/facebook/react-native/blob/v0.69.12/ReactAndroid/proguard-rules.pro
=> Update proguard-rules.pro for RN 0.72.*

config.js, react/features/base/config/configType.ts, react/features/subtitles/middleware.ts
=> feat(config,transcriptions) add option to skip interim transcriptions

react/features/base/config/configWhitelist.ts
=> feat(configWhitelist): add disableVirtualBackground

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts
=> fix(config) drop no longer existing option

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
=> feat: Drop unused module from prosody config.

react/features/base/conference/actions.ts
=> feat(base/conference): check conference status when leaving

react/features/base/config/functions.any.ts, react/features/base/media/middleware.any.ts, react/features/base/participants/subscriber.ts, react/features/base/tracks/actions.any.ts, react/features/base/tracks/functions.any.ts, react/features/base/tracks/middleware.any.ts, react/features/screen-share/functions.ts, react/features/screenshot-capture/actions.ts, react/features/virtual-background/components/VideoBackgroundButton.ts, react/features/virtual-background/components/VirtualBackgrounds.tsx
Since plan-b mode will no longer be supported, check for unified plan support is not needed anymore.
=> fix: Make multi-stream mode the default mode.

ios/app/app.xcodeproj/project.pbxproj
=> feat(ios): add missing config to .xcodeproj

react/features/face-landmarks/middleware.ts
=> feat: Drops sending facelandmarks to speakerstats.

react/features/face-landmarks/FaceLandmarksDetector.ts
=> feat(face-landmarks) disable on mobile web browsers

lang/main-de.json
=> lang: typo in German translation

ios/Podfile.lock, react/features/base/flags/constants.ts, react/features/invite/functions.ts, react/features/share-room/middleware.ts
=> feat(rn,invite) add ability to disable dial-in options

.github/workflows/ci.yml
=> feat(ci,ios) check if Pod file is in sync when running CI

resources/prosody-plugins/mod_filter_iq_rayo.lua
=> fix: Updates checking for granted feature.

doc/jaas/move-to-jaas.sh, resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_muc_rate_limit.lua, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
=> Prosody modules updates

react/features/base/participants/middleware.ts
Should probably fix https://github.com/jitsi/jitsi-meet/issues/14249 
PS I was thinking about adding "isConfigLoaded" property to fix this once and for all, but it seems to be quite dramatic change and I'm not very familiar with a code to make it properly, so rather just follow advice of @saghul and checking for a key which is known as mandatory
=> fix(participant) prevent gravatar request during loading of config

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioDeviceHandlerGeneric.java
=> feat(android) list HDMI connections as speakers

modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/VideoContainer.js, modules/UI/videolayout/VideoLayout.js
=> Large Video: Attempt a fix for black large video on iOS Safari & logging

lang/main-tr.json
I added the translation for Turkish for the new button:
`WaitingForHostButton`
=> Add Turkish translation: WaitingForHostButton

react/features/deep-linking/functions.ts
otherwise we are stuck in a loop inside the desktop app
Signed-off-by: Christoph Settgast <csett86_git@quicksands.de>
=> fix(deeplinking): skip deeplinking within electron

react/features/recording/components/Recording/AbstractHighlightButton.ts
=> fix(visitors): hide highlight button.

resources/prosody-plugins/mod_fmuc.lua
=> fix(visitors): Lowers visitor's hand on leave.

resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_measure_message_count.lua, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/token/util.lib.lua
=> fix: Fixes promoting the only moderator in a non vpass meeting.

react/features/chat/middleware.ts, react/features/subtitles/middleware.ts
=> Transcription fixes v3

css/_reactions-menu.scss, react/features/conference/components/web/Conference.tsx, react/features/keyboard-shortcuts/actions.any.ts, react/features/reactions/components/web/RaiseHandContainerButtons.tsx, react/features/reactions/components/web/ReactionsAnimations.tsx, react/features/reactions/components/web/ReactionsMenuButton.tsx, react/features/reactions/functions.any.ts, react/features/reactions/functions.web.ts, react/features/settings/functions.any.ts, react/features/toolbox/components/native/OverflowMenu.tsx, react/features/toolbox/components/native/Toolbox.tsx, react/features/toolbox/components/web/OverflowMenuButton.tsx, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/hooks.web.ts, resources/prosody-plugins/mod_measure_message_count.lua
=> Hide reactions for visitors

resources/prosody-plugins/mod_visitors.lua
=> feat: Adds indication for visitors messages to event.

resources/prosody-plugins/mod_filter_iq_rayo.lua, resources/prosody-plugins/mod_muc_auth_ban.lua, resources/prosody-plugins/mod_muc_flip.lua, resources/prosody-plugins/mod_muc_password_check.lua, resources/prosody-plugins/mod_muc_password_whitelist.lua, resources/prosody-plugins/mod_s2soutinjection.lua, resources/prosody-plugins/mod_secure_interfaces.lua, resources/prosody-plugins/mod_token_verification.lua, resources/prosody-plugins/token/util.lib.lua, resources/prosody-plugins/util.lib.lua
=> feat: Drops some debug prints.

resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
=> feat(visitors): Whitelist trusted domains when promoting.

react/features/lobby/actions.any.ts, react/features/lobby/functions.ts, react/features/security/components/security-dialog/native/SecurityDialog.tsx, react/features/security/components/security-dialog/web/SecurityDialog.tsx, react/features/visitors/functions.ts
=> fix(lobby): Hide enable option if there is a visitor

react/features/notifications/constants.ts, react/features/visitors/actions.ts, react/features/visitors/middleware.ts
=> feat(visitors): Adds notification for promotion requests.

config.js
=> fix(config): Fix the typo in Av1 support flag.

conference.js, react/features/base/conference/actionTypes.ts, react/features/base/conference/actions.ts, react/features/chat/middleware.ts, react/features/conference/middleware.web.ts, react/features/face-landmarks/middleware.ts, react/features/lobby/middleware.ts, react/features/mobile/external-api/middleware.ts, react/features/polls/middleware.ts, react/features/subtitles/actionTypes.ts, react/features/subtitles/actions.any.ts, react/features/subtitles/middleware.ts, react/features/visitors/middleware.ts
It's used for a myrias of things, not just subtitles.
=> fix(conference) move endpointMessageReceived action

react/features/conference/components/native/Conference.tsx
=> feat(conference): remove one2one check for diplaying participants name

react/features/recording/actions.any.ts, react/features/recording/components/Recording/AbstractStartRecordingDialog.ts, react/features/recording/middleware.ts, react/features/transcribing/middleware.ts
=> Transcriptions fixes v4

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example, package-lock.json, package.json, resources/extra-large-conference/prosody.cfg.lua.visitor.template, resources/prosody-plugins/mod_av_moderation_component.lua, resources/prosody-plugins/mod_conference_duration.lua, resources/prosody-plugins/mod_conference_duration_component.lua, resources/prosody-plugins/mod_filter_iq_rayo.lua, resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_muc_breakout_rooms.lua, resources/prosody-plugins/mod_muc_flip.lua, resources/prosody-plugins/mod_muc_jigasi_invite.lua, resources/prosody-plugins/mod_muc_lobby_rooms.lua, resources/prosody-plugins/mod_muc_password_check.lua, resources/prosody-plugins/mod_muc_wait_for_host.lua, resources/prosody-plugins/mod_reservations.lua, resources/prosody-plugins/mod_room_metadata_component.lua, resources/prosody-plugins/mod_speakerstats_component.lua, resources/prosody-plugins/mod_visitors.lua, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
- feat: Moves common process_host_module to util.
- feat: Use room data form for conference duration.
- feat: Adds conference duration for the visitors.
=> duration visitors

react/features/base/config/configWhitelist.ts, react/features/recording/actionTypes.ts, react/features/recording/actions.any.ts, react/features/recording/middleware.ts, react/features/recording/reducer.ts
Initial implementation did not account for cases where participants become moderators
=> fix(recording) fix recording suggestion not being shown in some cases

resources/prosody-plugins/mod_auth_jitsi-anonymous.lua
=> fix: Use same format for anonymous jids as token module.

react/features/base/premeeting/components/web/PreMeetingScreen.tsx, react/features/conference/components/native/TitleBar.tsx, react/features/prejoin/components/native/Prejoin.tsx, react/features/prejoin/functions.ts
=> feat(premeeting/prejoin): Control roomname visibility

.github/workflows/ci.yml
=> fix(ci) use the right CocoaPods version

react/features/whiteboard/middleware.any.ts
=> fix(whiteboard) handle metadata being null

config.js, react/features/base/config/configType.ts, react/features/subtitles/middleware.ts
=> feat(transcript) add ability to dump transcript for debugging

react/features/polls/middleware.ts
=> fix: Fixes polls parsing.

android/build.gradle, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetMediaProjectionService.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java, android/sdk/src/main/java/org/jitsi/meet/sdk/OngoingNotification.java, react/features/base/tracks/actions.native.ts
=> feat(android): fixed screen sharing for Android 33

lang/main.json, react/features/base/premeeting/components/web/PreMeetingScreen.tsx, react/features/base/premeeting/components/web/RecordingWarning.tsx, react/features/prejoin/components/native/Prejoin.tsx, react/features/prejoin/components/native/RecordingWarning.tsx, react/features/prejoin/components/native/styles.ts
Web (width > 720)
Web (width < 720)
Mobile
hidden for now
=> fix(prejoin) adjust recording warning

resources/prosody-plugins/mod_muc_lobby_rooms.lua
=> Multiple items set

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetMediaProjectionService.java, android/sdk/src/main/java/org/jitsi/meet/sdk/MediaProjectionNotification.java
=> feat(android): update media projection notification build

config.js, react/features/lobby/middleware.ts, react/features/mobile/navigation/functions.tsx, react/features/prejoin/functions.ts, react/features/settings/components/native/GeneralSection.tsx, react/features/settings/functions.any.ts
=> feat(prejoin) default to enabled

react/features/conference/components/native/AlwaysOnLabels.tsx, react/features/recording/components/native/RecordingExpandedLabel.ts
=> feat(conference/recordin): Fix always on labels

resources/prosody-plugins/mod_auth_token.lua, resources/prosody-plugins/mod_filter_iq_jibri.lua, resources/prosody-plugins/mod_filter_iq_rayo.lua, resources/prosody-plugins/mod_token_verification.lua, resources/prosody-plugins/token/util.lib.lua
=> Adds some stats around token validation

resources/prosody-plugins/token/util.lib.lua, resources/prosody-plugins/util.lib.lua
=> fix: Handles few more cases for updating cached tokens.

resources/prosody-plugins/mod_rate_limit.lua
=> fix: Change whitelist to support only domains.

resources/prosody-plugins/mod_auth_jitsi-shared-secret.lua
=> Add a second shared secret to allow rotation if necessary.

resources/prosody-plugins/mod_rate_limit.lua, resources/prosody-plugins/token/util.lib.lua
=> fix: Fixes initializing cached keys.

conference.js
=> feat(conference): Add init debug log

conference.js
=> fix(gumPending): Handle ignored muted tracks.

react/features/app/middlewares.any.ts, react/features/app/middlewares.web.ts, react/features/dynamic-branding/middleware.native.ts
=> feat(dynamic-branding): fix label customisation

package-lock.json, package.json, react/features/base/config/functions.any.ts
=> feat: Enable ssrc-rewriting by default.

conference.js, react/features/base/conference/actions.ts
=>  fix(visitors): gum pending on promotion.

react/features/recording/components/AbstractRecordingLabel.ts
=> fix(Livestreaming): label

config.js
A typo in the comment, took me a bit to realize it.
=> fix(Typo in comment)

react/features/base/ui/components/web/ContextMenuItem.tsx
=> fix(overflow-menu): disabled buttons styles

react/features/recording/components/Recording/AbstractStopRecordingDialog.ts
=> fix(recording) set transcribing metadata when stopping

react/features/base/tracks/actions.native.ts
=> feat(tracks): disable pip in screen-share based on flag value

resources/prosody-plugins/mod_room_metadata_component.lua
Include the room jid in the message.
=> feat: Send room_metadata updates to jicofo.

ios/Podfile.lock, package-lock.json, package.json
Adds UVC camera support to Android.
=> feat(rn,deps) update react-native-webrtc@118.0.1

package-lock.json, package.json
temporarily disable mobile exports
=> chore(deps) update excalidraw version

ios/Podfile.lock, package-lock.json, package.json
=> chore(deps, rn-webrtc): updated to 118.0.2

resources/prosody-plugins/mod_rate_limit.lua
=> Rate limits update

react/features/lobby/actions.any.ts, resources/prosody-plugins/mod_muc_lobby_rooms.lua
=> feat(lobby): Approve multiple participants.

config.js, lang/main.json, react/features/base/conference/middleware.any.ts, react/features/base/config/configType.ts, react/features/base/connection/actionTypes.ts, react/features/base/connection/actions.any.ts, react/features/base/connection/reducer.ts, react/features/participants-pane/components/native/MeetingParticipantItem.tsx, react/features/video-menu/components/index.native.ts, react/features/video-menu/components/index.web.ts, react/features/video-menu/components/native/DemoteToVisitorButton.ts, react/features/video-menu/components/native/DemoteToVisitorDialog.tsx, react/features/video-menu/components/native/LocalVideoMenu.tsx, react/features/video-menu/components/native/RemoteVideoMenu.tsx, react/features/video-menu/components/web/DemoteToVisitorButton.tsx, react/features/video-menu/components/web/DemoteToVisitorDialog.tsx, react/features/video-menu/components/web/HideSelfViewVideoButton.tsx, react/features/video-menu/components/web/LocalVideoMenuTriggerButton.tsx, react/features/video-menu/components/web/ParticipantContextMenu.tsx, react/features/video-menu/constants.ts, react/features/visitors/actionTypes.ts, react/features/visitors/actions.ts, react/features/visitors/logger.ts, react/features/visitors/middleware.ts, react/features/visitors/reducer.ts, resources/prosody-plugins/mod_visitors_component.lua
=> Demote a visitor

ios/sdk/sdk.xcodeproj/project.pbxproj
=> fix(ios) sync SDK and Lite SDK building commands

react/features/visitors/middleware.ts, resources/prosody-plugins/mod_muc_lobby_rooms.lua
Moderators receive all demote messages so they can show notification if we need to.
=> fix(visitors): Fixes demoting correct participant.

.gitignore, react-native-sdk/android/src/main/java/org/jitsi/meet/sdk/JitsiMeetReactNativePackage.java
=> react-native-sdk(android): readded react native package

react-native-sdk/prepare_sdk.js
=> react-native-sdk(chore/overrides): update prepare_sdk script to take care of overrides

package-lock.json, package.json
=> chore(deps, i18next-http-backend): removed caret

config.js, react/features/base/config/configType.ts, react/features/recording/components/Recording/AbstractStartRecordingDialog.ts
If recordings.recordAudioAndVideo is set to false don't record audio-video by default.
=> feat(recording) add ability to change recording defaults

ios/Podfile.lock, package-lock.json, package.json
Fixes spurious exceptions on Android 14.
=> chore(deps) react-native-webrtc@118.0.3

conference.js, react/features/base/conference/actions.ts
=> fix(conference): Do not remove muted tracks at join time when ssrc-rewriting is enabled

react/features/security/components/security-dialog/web/PasswordSection.tsx
=> fix(PasswordSection): Add button not working.

lang/main-lv.json
Updated Latvian language translation strings.
I have already signed CLA.
=> fix (lang): Update Latvian translation

react/features/large-video/components/LargeVideo.web.tsx, react/features/recording/functions.ts, react/features/whiteboard/functions.ts
please don't squash when merging
=> Whiteboard & auto transcribing fixes

resources/prosody-plugins/util.lib.lua
=> Support multiple sip jibri prefixes.

react/features/breakout-rooms/functions.ts, react/features/participants-pane/functions.ts
=> fix(kick): JS error when participant pane is open.

react/features/base/premeeting/components/web/PreMeetingScreen.tsx, react/features/conference/components/native/carmode/TitleBar.tsx, react/features/prejoin/functions.ts
=> feat(premeeting/conference/prejoin): fix hiding meeting subject helper

resources/prosody-plugins/token/util.lib.lua
=> fix: define local vars in public key handler

react/features/polls/components/AbstractPollCreate.tsx
=> fix: poll answer editing bug causing unintended removal 

resources/prosody-plugins/mod_muc_lobby_rooms.lua
=> fix: Updates lobby password.

modules/API/API.js, modules/API/external/external_api.js
=> feat(external-api) Expose meeting session id

lang/main-tr.json
new changes are applied for the tr-translations
=> fix(lang): added new tr translations

config.js, doc/debian/jitsi-meet/jitsi-meet.example, resources/extra-large-conference/README.md, resources/prosody-plugins/mod_visitors_component.lua
=> feat(visitors): Updates docs for promotion.

react/features/polls/components/native/styles.ts
=> fix(polls): fix poll button overflow

package-lock.json, package.json, react/features/base/config/functions.any.ts
=> fix(flags): Don't assume ssrc-rewriting enabled by default.

react/features/chat/components/web/PrivateMessageButton.tsx
added translation frunction to Private Message Button  https://github.com/jitsi/jitsi-meet/issues/14570
=> fix(chat): added translation function

react/features/security/components/security-dialog/web/PasswordForm.tsx, react/features/security/components/security-dialog/web/PasswordSection.tsx, react/features/security/components/security-dialog/web/SecurityDialog.tsx
=> ref(PasswordSection): Functional copmonents.

ios/Podfile.lock, package-lock.json, package.json
=> chore(rn,deps) update react-native-webrtc to 118.0.5

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastEvent.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, ios/app/src/ViewController.m, ios/sdk/src/JitsiMeetViewDelegate.h, react/features/mobile/external-api/actionTypes.ts, react/features/mobile/external-api/actions.ts, react/features/mobile/external-api/middleware.ts, react/features/toolbox/components/native/CustomOptionButton.tsx, react/features/toolbox/components/native/OverflowMenu.tsx, react/features/toolbox/components/native/styles.ts
=> feat(toolbox/native): custom overflow menu buttons

resources/prosody-plugins/mod_muc_domain_mapper.lua
=> feat: Adds option to print not-allowed errors we sent back to client.

react/features/base/conference/actions.ts, react/features/base/config/configWhitelist.ts, react/features/base/config/reducer.ts
=> feat(visitors-config): Enable media on promotion.

ios/Podfile.lock, package-lock.json, package.json
Fixes duplicated audio on iOS.
=> chore(rn,deps) react-native-webrtc@118.0.6

conference.js
=> fix(conference): use up to date state in useVideoStream.

resources/prosody-plugins/mod_visitors_component.lua
=> fix(visitors): Fixes promote all.

react/features/toolbox/components/native/CustomOptionButton.tsx, react/features/toolbox/components/native/styles.ts
=> feat(toolbox/native): fix for custom toolbar button icon

react/features/base/config/configWhitelist.ts
=> feat(base/config): whitelist customToolbarButtons

android/sdk/src/main/AndroidManifest.xml
=> feat(android): list media projection permission in manifest file

react-native-sdk/README.md
=> feat(react-native-sdk): update readme file

react/features/chat/components/web/MessageContainer.tsx
improved new message visibility for local participants https://github.com/jitsi/jitsi-meet/issues/14561
https://github.com/jitsi/jitsi-meet/assets/43909097/2dbfa7a3-e4ad-4996-94b2-8ad9a1d73e5c
=> fix(chat): enhanced the new message visibility for local participants

react-native-sdk/README.md
=> react-native-sdk: fix Readme descriptions

lang/main-lv.json
Updated missing Latvian language translation string.
I have already signed CLA.
=> fix(lang): Update missing Latvian lang translation

android/sdk/src/main/AndroidManifest.xml, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java
=> feat(android): list post notifications permission

.github/workflows/ci.yml, ios/app/app.xcodeproj/project.pbxproj, ios/sdk/sdk.xcodeproj/project.pbxproj
=> fix(ios) Xcode 15.2 updates

resources/prosody-plugins/mod_muc_flip.lua
=> fix: Skip flip processing for password when there is no room password.

resources/prosody-plugins/mod_visitors_component.lua
When a vpaas visitor tries to join a room that has not been created and there are no main participants, we deny access.
=> fix: Disallow visitor joining directly to main room.

react/features/base/conference/middleware.any.ts
=> fix(base/conference): save recording when connection fails

react/features/base/config/configWhitelist.ts
Signed-off-by: Christoph Settgast <csett86_git@quicksands.de>
=> feat(config) allow overriding desktop deeplinking toggle

ios/app/app.xcodeproj/project.pbxproj
This look like a copy/paste error.
Perhaps it should be 8x8 instead?
=> Use the correct organization name

resources/prosody-plugins/mod_filter_iq_rayo.lua, resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_muc_kick_jigasi.lua, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
=> Jigasi visitor

resources/prosody-plugins/mod_visitors_component.lua
=> fix(visitors): Stops processing pre-join on error reply.

resources/cloud-api.swagger
=> fix: Fixes swagger syntax.

react/features/base/conference/middleware.any.ts
=> fix(visitors): Drop use of APP, breaks mobile.

react/features/base/jwt/functions.ts, react/features/base/util/uri.ts
Fixes incorrect parsing of the JWT in the hash of the URL, to expect a JSON string.
=> fix(jwt): Fixes parsing JWT in hash as JSON instead of a string

resources/prosody-plugins/mod_room_metadata_component.lua
=> fix: Fix room_jid in room_metadata message when a tenant is set.

react/features/polls/components/native/styles.ts
=> fix(polls): add vertical margin to create poll button (android)

react/features/base/ui/components/native/Input.tsx, react/features/base/ui/components/native/inputStyles.ts, react/features/polls/components/native/PollCreate.tsx, react/features/polls/functions.ts
=> feat(polls/web/native): fixed identical answers verification

react/features/conference/middleware.any.ts, react/features/notifications/components/native/Notification.tsx, react/features/notifications/components/native/styles.ts
=> feat(notifications/native): ui fixes

react/features/base/jwt/functions.ts, react/features/base/participants/types.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/functions.any.ts, react/features/toolbox/functions.web.ts
=> ref(Toolbox): replace mapStateToProps with hooks.

react/features/base/participants/types.ts
=> fix(participant-features): Add missing properties in the type.

ios/Podfile.lock, package-lock.json, package.json
=> chore(deps) update react-native-webrtc@124.0.0

react-native-sdk/update_dependencies.js
=> feat(rnsdk): exclude adding metro dep if already available

android/gradle.properties
=> fix(android) fix build with Java 17

ios/fastlane/Fastfile
=> fix(ios) don't pretty-print build output with Fastlane

react/features/notifications/components/native/Notification.tsx, react/features/notifications/components/native/styles.ts
=> feat(notifications/native): minor ui refurbishment

android/app/src/main/java/org/jitsi/meet/MainActivity.java, ios/app/src/AppDelegate.m
Layer suspension now works on mobile, let's give this a try once again.
=> feat(rn) remove 360p resolution limitation

react/features/app/actions.native.ts, react/features/app/actions.web.ts, react/features/base/conference/actions.any.ts, react/features/base/conference/functions.ts, react/features/base/conference/reducer.ts, react/features/base/config/actions.ts, react/features/prejoin/components/web/PrejoinApp.tsx
=> fix(subject) Fix setting and broadcasting subject

resources/prosody-plugins/luajwtjitsi.lib.lua, resources/prosody-plugins/mod_auth_token.lua, resources/prosody-plugins/mod_jitsi_session.lua
=> feat(jwt): Adds more logs when jwt is expired.

react/features/breakout-rooms/components/native/BreakoutRooms.tsx, react/features/notifications/components/native/styles.ts, react/features/participants-pane/components/native/ParticipantsPane.tsx, react/features/polls/components/native/PollAnswer.tsx, react/features/polls/components/native/PollCreate.tsx, react/features/polls/components/native/PollItem.tsx, react/features/polls/components/native/PollResults.tsx, react/features/polls/components/native/PollsList.tsx, react/features/polls/components/native/PollsPane.tsx, react/features/polls/components/native/styles.ts, react/features/settings/components/native/styles.ts, react/features/video-menu/components/native/ConnectionStatusButton.ts, react/features/video-menu/components/native/LocalVideoMenu.tsx
1. Notifications ui arrangements.
2. Local video menu connection status button onClick fix.
3. Polls create full screen scroll, re-rendering and button labels fix.
4. Created renderListHeaderComponent for Participants Pane and Breakout Rooms.
5. Renamed chatStyles to pollsStyles.
=> feat(base/native): Fixes around UI

resources/prosody-plugins/mod_fmuc.lua
=> fix(system_chat_message): Fixes delivering system messages to visitors.

react/features/base/lib-jitsi-meet/index.ts, react/features/base/testing/functions.ts, react/features/base/testing/middleware.ts, react/features/base/tracks/actions.any.ts, react/features/base/tracks/types.ts, react/features/connection-indicator/statsEmitter.ts, react/features/video-quality/constants.ts
Also add helper functions for torture tests.
=> fix(tracks): Update the codec for local tracks in redux.

react/features/embed-meeting/hooks.ts, react/features/etherpad/hooks.ts, react/features/feedback/hooks.web.ts, react/features/keyboard-shortcuts/hooks.web.ts, react/features/participants-pane/hooks.web.ts, react/features/reactions/hooks.web.ts, react/features/recording/components/LiveStream/AbstractLiveStreamButton.ts, react/features/recording/functions.ts, react/features/recording/hooks.web.ts, react/features/security/components/security-dialog/AbstractSecurityDialogButton.ts, react/features/security/functions.ts, react/features/security/hooks.web.ts, react/features/speaker-stats/hooks.web.ts, react/features/subtitles/hooks.web.ts, react/features/toolbox/components/index.native.ts, react/features/toolbox/components/index.web.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/functions.web.ts, react/features/toolbox/hooks.web.ts, react/features/toolbox/types.ts, react/features/video-layout/hooks.ts, react/features/virtual-background/hooks.ts, react/features/whiteboard/hooks.ts
Currently if a button in the main toolbar is not visible, the button is
not replaced by another button from the overflow menu.
=> fix(MainToolbar): replace hidden buttons.

android/sdk/build.gradle, ios/Podfile, ios/Podfile.lock
=> feat(android/ios/sdk): Update logging dependencies

Makefile
Ref: https://github.com/jitsi/jitsi-meet/issues/14842
=> fix(build) compile the frontend before making a source package

react/features/base/environment/utils.ts, react/features/base/react/Platform.web.ts, react/features/toolbox/hooks.web.ts
=> feat(toolbox): enable full screen button for ipad browsers

resources/prosody-plugins/mod_room_metadata_component.lua
=> feat(prosody): Add handling of a room-metadata-changed event.

resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_visitors.lua, resources/prosody-plugins/mod_visitors_component.lua
=> feat(visitors): Force promote works for all moderators.

config.js
=> fix(config) Add 'screenshareCodec' and 'mobileScreenshareCodec'.

lang/main-lv.json
Updated Latvian language translation.
I have already signed CLA.
=> fix(lang): Update Latvian language translation

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/video-menu/components/native/LocalVideoMenu.tsx, react/features/video-menu/components/web/LocalVideoMenuTriggerButton.tsx
=> feat(visitors): Adds option to disable self-demote button.

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
=> feat(android/sdk): fixed enterpictureinpicture method call

android/build.gradle, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java
=> feat(android): check for microphone permission so ongoing service can start

react/features/base/participants/middleware.ts
=> fix raise hand queue

react-native-sdk/package.json
This is used for visitors feature.
=> feat(react-native-sdk): add stompjs to peerDependencies

android/settings.gradle, ios/Podfile.lock, package-lock.json, package.json, react-native-sdk/package.json, react/features/base/util/copyText.native.ts, react/features/polls/components/native/PollCreate.tsx
=> deps(react-native-gesture-handler/@react-native-clipboard/clipboard): Updates related to RN 0.73.8

react/features/visitors/middleware.ts
=> fix(visitors): Check for preferVisitor from redux.

react/features/conference/components/native/styles.ts, react/features/notifications/components/native/styles.ts
https://github.com/jitsi/jitsi-meet/assets/26413496/e1d0a848-c4a9-4d8e-9a8b-4a610501d165
=> feat(notifications/native): some UI arrangements for smaller devices

ios/Podfile.lock, package-lock.json, package.json
=> dep(react-native-webrtc): update to latest

ios/Podfile.lock, package-lock.json, package.json
=> deps(react-emoji-render/@amplitude/react-native): update to latest

react/features/toolbox/components/web/JitsiPortal.tsx
=> feat(toolbox/web): fix You seem to be using a value for content without quotes error log

react/features/base/connection/reducer.ts, react/features/base/jwt/functions.ts, react/features/visitors/middleware.ts, react/features/visitors/websocket-client.ts, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/token/util.lib.lua
=> fix(visitors): Fixes going live when the meeting is created.

react/features/keyboard-shortcuts/actions.web.ts
Come over for a fun story, dear reader!
Here is a not-so-fun difference in behavior, observed in macOS:
- The builtin keyboard doesn't seem to send the same key over and over again while it's being held.
- On the contrary, a USB keyboard does.
That means that for some keyboards PTT has been broken. We get keydown/keyup pairs in quick successing.
One would think that KeyboardEvent.repeat would solve that, but it doesn't seem to, in practice. See: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat
So, in order to solve this, delay handling the keyup event by 50ms. This way, if a new keydown comes before the keyup has been handled we'll cancel it and act as it never happened, restoring PTT functionality.
While we're at it, use window.addEventListener rather than …
=> fix(keyboard-shortcuts) fix PTT on keyboards which send repeated keys

lang/main.json, react/features/base/ui/components/web/Dialog.tsx, react/features/reactions/components/native/RaiseHandButton.tsx, react/features/reactions/components/web/RaiseHandButton.ts, react/features/visitors/components/index.native.ts, react/features/visitors/components/index.web.ts, react/features/visitors/components/native/JoinMeetingDialog.tsx, react/features/visitors/components/native/styles.ts, react/features/visitors/components/web/JoinMeetingDialog.tsx, react/features/visitors/middleware.ts
=> feat(visitors) add info dialog

react/features/rtcstats/middleware.ts
=> feat(rtcstats): move conference start time to ljm

modules/API/API.js
=> feat(external-api) add deployment information to ready event

modules/API/API.js, react/features/base/participants/actions.ts, react/features/external-api/middleware.ts
Depends on: https://github.com/jitsi/lib-jitsi-meet/pull/2549
=> Fix kicked event

react/features/base/participants/reducer.ts
=> feat(base/participants): fix max callstack error

modules/API/API.js
Reverts jitsi/jitsi-meet#14956
=> Revert "feat(external-api) add deployment information to ready event"

index.html, react/index.web.js
=> feat(window.loaded): Add new metric.

react/features/base/participants/reducer.ts, react/features/base/participants/subscriber.ts
=> feat(participants): check for raisedHandsQueue length before notifying participant to speak

react/features/chat/components/native/ChatInputBar.tsx, react/features/chat/components/web/ChatInput.tsx, react/features/chat/constants.ts, react/features/notifications/components/native/Notification.tsx, react/features/notifications/components/native/styles.ts
=> feat(chat/notifications): UI fixes

react/features/base/i18n/customNavigatorDetector.ts
=> fix(i18n): Ignore case when normalizing  languages.

react/features/chat/components/native/ChatInputBar.tsx, react/features/chat/components/web/ChatInput.tsx, react/features/chat/constants.ts
=> feat(chat): revert char_limit for input

resources/prosody-plugins/mod_presence_identity.lua
This reverts commit a6457db8191ec010cf85301e7a8eef038430bbce.
=> Revert "feat: Presence identity module to support other auth mechanisms."

ios/scripts/release-sdk-lite.sh, ios/scripts/release-sdk.sh
=> feat(ios): readded git tag for release sdk scritps

lang/main.json, react/features/base/participants/middleware.ts, react/features/base/participants/subscriber.ts
Hi reviewer,
This is a GSoC task. I added a 'View participants' action to the 'xxx would like to speak' notification. Feel free to let me know which part is inappropriate.
=> feat(view-participants-button-to-raiseHand-notification)

ios/scripts/release-sdk-lite.sh, ios/scripts/release-sdk.sh
- Run script with tracing
- Allow empty commits (we might need a rebuild)
- Fix tag name in lite SDK
=> fix(ios) SDK release script fixes

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/base/config/functions.any.ts, react/features/base/config/reducer.ts, react/features/base/participants/subscriber.ts, react/features/conference/middleware.any.ts
Hi reviewer,
This is a GSoC task. I added a raisedHands object in config.js and added its corresponding selectors. Feel free to let me know which part is inappropriate.
Thanks,
Mengyuan
=> create a raisedHands object in config.js

resources/prosody-plugins/mod_polls.lua
- Prevent creation of too many polls
- Discard absurdly large payloads
=> fix(polls) improve message validation

react/features/mobile/external-api/actionTypes.ts, react/features/mobile/external-api/actions.ts, react/features/mobile/external-api/middleware.ts, react/features/toolbox/actionTypes.ts, react/features/toolbox/actions.native.ts, react/features/toolbox/components/native/OverflowMenu.tsx
Fixed custom native button pressed event naming diff and moved to appropriate feature.
Linked to https://github.com/jitsi/jitsi-meet-sdk-samples/issues/245
=> feat(toolbox): moved action to apropriate feature and fixed event naming

lang/main-pt.json
=> Translation into Portuguese from Portugal

android/scripts/run-packager-helper.command, ios/scripts/run-packager-helper.command
=> fix(android/ios/scripts): updated react native packager script path

lang/main.json, react/features/base/participants/components/ParticipantView.native.tsx, react/features/shared-video/actions.any.ts, react/features/shared-video/components/index.native.ts, react/features/shared-video/components/index.web.ts, react/features/shared-video/components/web/SharedVideo.tsx, react/features/shared-video/constants.ts, react/features/shared-video/functions.ts, react/features/shared-video/hooks.ts, react/features/shared-video/middleware.any.ts, react/features/shared-video/middleware.web.ts, react/features/toolbox/components/native/OverflowMenu.tsx, react/features/toolbox/hooks.web.ts
=> feat(shared-video): Allow only whitelisted URLs.

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
=> feat(android/sdk): removed blank space from jitsiview join call

ios/Podfile.lock, package-lock.json, package.json
The issue was fixed in RN WebRTC.
=> fix(rn) fix audio loss when switching to the bridge

lang/main-de.json
Added all missing translations for German and removed all unused ones using the `update-translation.js` script.
=> Update german translation

react/features/base/lastn/middleware.ts, react/features/base/react/components/web/MultiSelectAutocomplete.tsx, react/features/chat/components/web/MessageContainer.tsx, react/features/filmstrip/components/web/Thumbnail.tsx, react/features/mobile/external-api/functions.ts, react/features/mobile/external-api/middleware.ts, react/features/notifications/actions.ts, react/features/shared-video/components/native/AbstractVideoManager.ts, react/features/shared-video/components/web/AbstractVideoManager.ts, react/features/video-quality/subscriber.ts
We are fully using lodash-es now.
=> chore(deps) remove remaining lodash dependencies

react-native-sdk/prepare_sdk.js, react-native-sdk/update_sdk_dependencies.js, resources/update-mobile-rnsdk-version.sh
Make sure alll dependencies are updated when we run it.
=> fix(rn) improve rnsdk version script

android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
=> fix(android) remove unused method

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java, react/features/conference/components/native/Conference.tsx, react/features/mobile/picture-in-picture/actions.ts, react/features/mobile/picture-in-picture/components/PictureInPictureButton.ts, react/features/mobile/picture-in-picture/functions.ts
Fixes: https://github.com/jitsi/jitsi-meet/issues/15014
=> fix(android) fix default value for pip.enabled

react-native-sdk/package.json
=> feat(rnsdk): moved deps that dont require linking

react/features/base/participants/actions.ts
=> fix(participants): Handles kicker undefined on participantKicked.

config.js, modules/API/API.js, react/features/base/config/configType.ts, react/features/dynamic-branding/reducer.ts, react/features/shared-video/actionTypes.ts, react/features/shared-video/actions.any.ts, react/features/shared-video/components/AbstractSharedVideoDialog.tsx, react/features/shared-video/components/native/SharedVideoDialog.tsx, react/features/shared-video/components/web/SharedVideoDialog.tsx, react/features/shared-video/constants.ts, react/features/shared-video/functions.ts, react/features/shared-video/middleware.any.ts, react/features/shared-video/reducer.ts
=> fix(shared-video): Lint errors.

react/features/base/participants/components/ParticipantView.native.tsx
=> fix(RN-video): Video not showing if disableThirdPartyRequests is true.

react/features/shared-video/middleware.any.ts
=> fix(shared-video): Fix skip showing confirm dialog for YouTube links.

react/features/base/react/components/web/Message.tsx, react/features/chat/components/native/GifMessage.tsx, react/features/chat/middleware.ts, react/features/gifs/function.any.ts
=> fix(gifs): trim the message before extracting the URL.

react/features/display-name/components/web/StageParticipantNameLabel.tsx, react/features/subtitles/components/web/Captions.tsx, react/features/toolbox/functions.web.ts
=> feat(subtitles): Move with toolbar.

react/features/subtitles/components/web/Captions.tsx
=> fix(subtitles): positioning and padding

resources/prosody-plugins/mod_visitors_component.lua
=> fix(visitors): When metadata or flag live is missing, consider live.

react/features/base/settings/functions.web.ts
=> fix(devices): Do not select stored devices that are not available.

react/features/base/jwt/constants.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/constants.ts, react/features/toolbox/functions.any.ts, resources/prosody-plugins/mod_filter_iq_rayo.lua, resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_visitors.lua, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
=> feat(visitors): Transcriptions for visitors.

lang/main.json, react/features/base/conference/actionTypes.ts, react/features/base/conference/actions.any.ts, react/features/base/conference/reducer.ts, react/features/follow-me/actions.ts, react/features/follow-me/functions.ts, react/features/follow-me/middleware.ts, react/features/follow-me/reducer.ts, react/features/follow-me/subscriber.ts, react/features/settings/actions.web.ts, react/features/settings/components/native/ModeratorSection.tsx, react/features/settings/components/web/ModeratorTab.tsx, react/features/settings/components/web/SettingsDialog.tsx, react/features/settings/functions.any.ts
=> feat(follow-me): Adds option to limit it for recorder only.

react-native-sdk/jitsi-meet-rnsdk.podspec
=> feat(react-native-sdk): update podspec file

modules/API/API.js
=> feat(follow-me): Adds iframeAPI to activate recorder follow me.

resources/prosody-plugins/mod_av_moderation_component.lua
The exception we see in jicofo: IllegalArgumentException: Value is not a list We were encoding empty array for media types as {} where it should be [].
=> fix(av-moderation): Fix wrong json format for empty array.

resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_muc_breakout_rooms.lua, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
=> Fix breakout rooms and visitors

.github/workflows/ci.yml, ios/app/app.xcodeproj/project.pbxproj, ios/sdk/sdk.xcodeproj/project.pbxproj
=> feat(ios) use Xcode 16 as the new baseline

ios/Podfile.lock, ios/app/app.xcodeproj/project.pbxproj, patches/@giphy+react-native-sdk+2.3.0.patch
Fix for https://github.com/jitsi/jitsi-meet-flutter-sdk/issues/89
=> fix(ios) update giphy SDK

resources/prosody-plugins/mod_fmuc.lua
=> fix(visitors): Skips a log if room is being destroyed.

resources/prosody-plugins/luajwtjitsi.lib.lua, resources/prosody-plugins/mod_auth_token.lua
=> feat(jwt): Adds some more logs around expiration.

conference.js, react/features/authentication/components/web/LoginDialog.tsx, react/features/base/conference/actions.any.ts, react/features/lobby/actions.any.ts, react/features/prejoin/actions.web.ts, react/features/prejoin/components/web/Prejoin.tsx, react/features/visitors/actions.ts, react/features/visitors/middleware.ts
=> feat(connect): Add logging before every connect.

react/features/base/toolbox/components/ToolboxItem.native.tsx, react/features/base/ui/components/native/IconButton.tsx
=> feat(base): minor syntax and ts types fixes

react/features/participants-pane/components/native/ParticipantsPaneButton.tsx
=> feat(participants-pane/native): match accessibility label with web

lang/main-ru.json
=> fix(lang) fix Russian lang

resources/prosody-plugins/mod_polls.lua
=> fix(polls) add extra check when creating polls

react/features/app/types.ts, react/features/base/lastn/middleware.ts, react/features/calendar-sync/middleware.ts, react/features/conference/components/native/Conference.tsx, react/features/mobile/background/logger.ts, react/features/mobile/background/middleware.native.ts, react/features/mobile/background/reducer.ts, react/features/mobile/call-integration/logger.ts, react/features/mobile/call-integration/middleware.ts, react/features/mobile/full-screen/middleware.ts
=> feat(mobile/background): use reducedUI only when app is not active and log appState

react/features/chat/middleware.ts
=> fix(chat) make reactions processing more resilient

config.js, react/features/base/config/configType.ts, react/features/subtitles/middleware.ts, react/features/transcribing/subscriber.ts
=> feat(subtitles): Adds an option to automatically enable subtitles when transcriber is available.

react/features/base/premeeting/components/web/PreMeetingScreen.tsx
=> fix(premeeting): remove console log

config.js, react/features/base/config/configType.ts
=> feat(e2ee) add flag to disable the feature

package-lock.json, package.json, react/features/base/connection/actions.any.ts, react/features/base/lib-jitsi-meet/functions.any.ts
Reloads when this fatal error occurs.
=> feat(connection): Handles the new connection error CONFERENCE_REQUEST_FAILED.

android/build.gradle
=> chore(android): update rnVersion

android/gradle.properties, android/sdk/build.gradle, android/sdk/src/main/java/org/jitsi/meet/sdk/AppInfoModule.java
=> fix(android) add SDK version information

globals.native.d.ts, react/features/base/lib-jitsi-meet/actions.ts, react/features/mobile/polyfills/browser.js
Add SDK version in addition to OS and RN versions.
Example: "JitsiMeetSDK/0.0.0 (android/34) react-native/0.75.4"
=> feat(rn) improve UA string

android/sdk/build.gradle
=> fix(android) fix bundle script path

conference.js, react/features/base/devices/actions.web.ts, react/features/base/tracks/actions.web.ts, react/features/base/tracks/functions.web.ts, react/features/base/tracks/loadEffects.web.ts, react/features/base/util/helpers.ts, react/features/conference/actions.web.ts, react/index.web.js
Adds logs and analytics events with time measurements for the different stages of conference.init execution.
=> feat(metrics): related to conference.init execution.

react/features/mobile/polyfills/browser.js
Make sure all the parts are "something/something-else" similar to how
browsers do it.
=> fix(rn) tweak UA string

react/features/base/icons/components/Icon.tsx
Warning: Icon: Support for defaultProps will be removed from function components in a future major release.
=> fix(base/icons): error regarding default props

resources/prosody-plugins/mod_fmuc.lua
=> fix(visitors): Fixes detection of turning of subtitles by visitor.

lang/main-tr.json
1. Corrected minor translation inconsistencies.
2. Update: Added Turkish translation for "joinAudioByPhone"
I have already signed CLA.
=> lang: Update Turkish translations

react/features/base/participants/middleware.ts, react/features/base/participants/types.ts
=> fix(local-recording) handle repeated values

react/features/base/conference/reducer.ts, react/features/settings/actions.web.ts, react/features/settings/components/native/LanguageSelectView.tsx
Depends on: https://github.com/jitsi/lib-jitsi-meet/pull/2600
=> fix(conference) update transcription language with meeting language

react/features/base/participants/actions.ts
=> fix(iframeAPI): Fix role changed event to work not only for local user.

.github/workflows/ci.yml
- Run Android and iOS on macOS (same as our release process)
- Simplify checking for Podfile changes
- Add CI for building the native iOS SDK
=> feat(ci) improve mobile CI

package-lock.json, package.json, webpack.config.js
=> chore(webpack-dev-server): Updates webpack-dev-server to latest.

react/features/analytics/functions.ts
Add temporary metrics for  interfaceConfig.SUPPORT_URL and config.salesforceUrl url overwrites.
=> feat(URL): Add metrics for config overwrites.

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example, resources/extra-large-conference/prosody.cfg.lua.visitor.template
=> feat(prosody): Enables connection resumption for jicofo and jvb.

android/build.gradle
=> feat(android): removed jsc related code

react/features/settings/components/native/GeneralSection.tsx
=> feat(settings/native): fix prejoin settings

config.js
=> fix(config): Add missing config options

react/features/toolbox/components/native/CustomOptionButton.tsx, react/features/toolbox/components/native/OverflowMenu.tsx
=> feat(toolbox/native): update CustomOptionButton props

.github/workflows/ci.yml
=> feat(ga): Adds a syntax check for config.js.

ios/Podfile.lock, package-lock.json, package.json
We might need it 
https://github.com/react-native-clipboard/clipboard/issues/239#issuecomment-2439112708
if we want to 
https://github.com/jitsi/jitsi-meet/pull/15391
=> dep(@react-native-clipboard/clipboard): update to 1.14.3

conference.js, react/features/base/tracks/actions.web.ts, react/features/base/tracks/functions.native.ts, react/features/base/tracks/functions.web.ts, react/features/base/tracks/types.ts
=> ref(tracks) Remove gUM option that is no longer supported

resources/prosody-plugins/mod_fmuc.lua
=> fix(visitors): Fix a check that can result missing main participants.

package-lock.json, package.json, react/features/base/ui/components/native/IconButton.tsx
=> chore(deps) update TypeScript

react/features/base/devices/constants.ts
I haven't seen any particular problem with it, but it's of no use anyway...
=> fix(devices) filter out Zoom audio device

tests/helpers/Participant.ts, tests/helpers/participants.ts, tests/pageobjects/AVModerationMenu.ts, tests/pageobjects/BaseDialog.ts, tests/pageobjects/BasePageObject.ts, tests/pageobjects/BreakoutRooms.ts, tests/pageobjects/Filmstrip.ts, tests/pageobjects/IframeAPI.ts, tests/pageobjects/Notifications.ts, tests/pageobjects/ParticipantsPane.ts, tests/pageobjects/Toolbar.ts, tests/specs/2way/audioOnly.spec.ts, tests/specs/3way/breakoutRooms.spec.ts, tests/wdio.conf.ts, tests/wdio.dev.conf.ts, tests/wdio.firefox.conf.ts, tests/wdio.grid.conf.ts
=> feat(tests): Adds breakout tests.

config.js
=> fix(config): Fixes wrong file location.

resources/prosody-plugins/mod_filter_iq_jibri.lua
=> fix(prosody): Adds another condition to the filter.

css/_meetings_list.scss
#15430 
Screen recording:
https://github.com/user-attachments/assets/c7dd8704-6e42-4a00-b0ec-f82daed38e2a
=> changed the fill colour of the trash icon in meeting list item

react/features/chat/components/web/ChatMessage.tsx
#15434
**Before:**
https://github.com/user-attachments/assets/348e02fe-9b15-4d49-b1bf-1b573924f665
**After:**
https://github.com/user-attachments/assets/dcaa214f-a66a-42c1-ade7-49f99e54d64c
=> Removed unnecessary re render of the reactions component

react/features/base/ui/components/web/Input.tsx
#15445
**Before:**
https://github.com/user-attachments/assets/03a2c64f-1a8b-4551-8d45-db9447a585fd
**Result:**
https://github.com/user-attachments/assets/4623ee12-03da-48cb-b690-dbf4e811ad75
=> Fixed the input overlapping issue when clearable icon is present

react/features/notifications/components/web/Notification.tsx
#15436
**Recording:**
https://github.com/user-attachments/assets/37ea66ff-e46e-4a65-84f8-13edf561df8f
=> Added tabIndex to close Icon in the notification Item

tests/helpers/Participant.ts, tests/helpers/participants.ts, tests/helpers/types.ts, tests/pageobjects/Filmstrip.ts, tests/pageobjects/Notifications.ts, tests/pageobjects/SettingsDialog.ts, tests/pageobjects/Toolbar.ts, tests/specs/2way/displayName.spec.ts, tests/specs/2way/endConference.spec.ts, tests/specs/2way/selfView.spec.ts, tests/wdio.conf.ts
=> feat(tests): Adds self view, display name and end conference tests.

react/features/base/conference/middleware.any.ts
=> fix(connection): Adds default tenant value on error.

lang/main.json
=> Fix typo in unsecure room name warning

tests/pageobjects/Toolbar.ts, tests/specs/4way/desktopSharing.spec.ts, tests/wdio.conf.ts, tests/wdio.firefox.conf.ts, tests/wdio.grid.conf.ts
=> feat(tests): Adds desktop sharing test.

react/features/polls/middleware.ts
=> fix(polls) limit maximum amount of answers

lang/main.json, react/features/base/dialog/actions.ts, react/features/conference/components/web/SpeakerStatsLabel.tsx, react/features/visitors/functions.ts
=> Various visitor updates

config.js, react/features/base/config/configWhitelist.ts
=> fix(config): Allow only enableMediaOnPromote from visitors config to be overriden.

ios/.xcode.env
=> fix(ios) fix node path in scripts

ios/scripts/release-sdk-lite.sh, ios/scripts/release-sdk.sh
=> feat(ios): fixed path from where we take hermes.xcframework

react/features/toolbox/components/native/styles.ts
=> feat(toolbox): reactions menu native ui adjustments

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioModeModule.java, ios/sdk/src/AudioMode.m, ios/sdk/src/JitsiAudioSession.m, react/features/base/tracks/actions.any.ts, react/features/mobile/audio-mode/middleware.ts
=> feat(rn) implement startSilent

react/features/polls/middleware.ts
=> fix(polls): Fixes send/receive polls and processing answers.

resources/prosody-plugins/mod_fmuc.lua
Sometimes jicofo may leave before the disconnect iq reaches the visitor prosody, that will cause a reload for all visitors instead of a dialog for conference ended.
=> fix(visitors): Destroy visitors room earlier on main=0.

package-lock.json, package.json, resources/prosody-plugins/mod_jitsi_session.lua, resources/prosody-plugins/mod_muc_meeting_id.lua
=> feat: Reads region from http headers and set it in presence.

resources/prosody-plugins/util.lib.lua
=> fix(prosody): Fixes jibri util check to support occupant and jid.

tests/resources/fakeAudioStream_license.txt
=> fix(tests): Adds missing audio file.

modules/API/API.js
=> feat(api): Adds a print about overwritten config via iframeAPI.

Makefile, app.js
webpack + babel-loader + core-js should've take care of it, but they somehow don't and I couldn't finesse the webpack config enough.
This is a stop-gap.
Fixes: https://github.com/jitsi/jitsi-meet/issues/15539
=> fix(web) polyfill Promise.withResolvers

resources/prosody-plugins/util.lib.lua
=> fix: Adds nil check in some util methods.

lang/main-sv.json
Updated Swedish translation to 100%
=> fix: update Swedish translation

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastEvent.java
=> feat(android/sdk): custom button pressed event name updated

app.js, modules/API/index.js, package-lock.json, package.json, react/features/app/components/AbstractApp.ts, react/features/recording/components/Recording/web/StopRecordingDialog.tsx, react/features/stream-effects/virtual-background/index.ts, react/features/stream-effects/virtual-background/vendor/tflite/tflite-simd.js, react/features/stream-effects/virtual-background/vendor/tflite/tflite.js, react/features/video-menu/components/web/GrantModeratorDialog.tsx, tsconfig.web.json, webpack.config.js
Includes take 1, see each individual commit.
=> Improve polyfills, take 2

resources/prosody-plugins/util.lib.lua
=> fix: Fixes is_jibri check.

package-lock.json, package.json, react/features/mobile/polyfills/browser.js
We use the same on the web, on browsers that don't support them.
=> fix(rn,polyfills) use core-js for promise polyfills

ios/app/src/AppDelegate.m, ios/sdk/src/JitsiMeet.h, ios/sdk/src/JitsiMeet.m
It allows for full control over the audio handling.
=> feat(ios) add ability to inject a custom RTCAudioDevice implementation

react/features/base/devices/functions.web.ts
=> feat(base/devices): removed unused helper

tests/wdio.conf.ts
=> fix(tests): wdio.cong ffExcludes undefined error.

tests/specs/3way/audioVideoModeration.spec.ts
=> fix(av-moderation-test): random timing failures.

package-lock.json, package.json, react/features/mobile/polyfills/browser.js
=> fix(rn) remove Pomise.allSettled polyfill

tests/helpers/Participant.ts, tests/helpers/participants.ts, tests/pageobjects/Filmstrip.ts, tests/pageobjects/LargeVideo.ts, tests/pageobjects/SettingsDialog.ts, tests/specs/3way/activeSpeaker.spec.ts, tests/specs/3way/avatars.spec.ts, tests/specs/3way/followMe.spec.ts, tests/specs/3way/startMuted.spec.ts, tests/specs/4way/desktopSharing.spec.ts, tests/specs/4way/lastN.spec.ts
=> feat(tests): Add start muted test.

react/features/analytics/functions.ts
=> fix(analytics): remove overwritesWatchRTC* props

resources/prosody-plugins/mod_muc_meeting_id.lua, resources/prosody-plugins/mod_polls.lua, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
Optimizes json parsing of incoming messages. Now we do it in centralized place and firing an event.
=> feat(prosody): Introduces events for json messages and transcripts.

ios/app/src/AppDelegate.m, react/features/app/middlewares.native.ts, react/features/base/devices/functions.web.ts, react/features/base/premeeting/components/web/PreMeetingScreen.tsx, react/features/chat/components/web/MessageContainer.tsx, react/features/filmstrip/components/native/Filmstrip.tsx, react/features/filmstrip/components/web/Filmstrip.tsx, react/features/reactions/components/native/RaiseHandContainerButtons.tsx, react/features/toolbox/actions.any.ts, react/features/toolbox/actions.native.ts, react/features/toolbox/actions.web.ts, react/features/toolbox/components/native/CustomOptionButton.tsx, react/features/toolbox/components/native/HangupContainerButtons.tsx, react/features/toolbox/components/native/OverflowMenu.tsx, react/features/toolbox/components/native/OverflowMenuButton.ts, react/features/toolbox/components/native/Toolbox.tsx, react/features/toolbox/components/native/styles.ts, react/features/toolbox/constants.ts, react/features/toolbox/functions.any.ts, react/features/toolbox/functions.native.ts, react/features/toolbox/functions.web.ts, react/features/toolbox/hooks.native.ts, react/features/toolbox/hooks.web.ts, react/features/toolbox/middleware.native.ts, react/features/toolbox/middleware.web.ts, react/features/toolbox/reducer.ts, react/features/toolbox/types.ts
#15529 needs to be merged before this one.
=> feat(toolbox/native): reorganizing buttons in the toolbox and overflow menu

tests/pageobjects/Notifications.ts, tests/pageobjects/PreMeetingScreen.ts
=> fix(tests): add more time for getNotificationText.

tests/specs/alone/dialInAudio.spec.ts, tests/specs/helpers/DialIn.ts
=> feat(tests): Small improvements to dial-in test.

package.json, tests/helpers/Participant.ts, tests/helpers/participants.ts, tests/helpers/types.ts, tests/pageobjects/Filmstrip.ts, tests/pageobjects/ParticipantsPane.ts, tests/pageobjects/PasswordDialog.ts, tests/pageobjects/SecurityDialog.ts, tests/specs/2way/grantModerator.spec.ts, tests/specs/2way/lockRoom.spec.ts, tests/specs/2way/mute.spect.ts, tests/specs/3way/audioVideoModeration.spec.ts, tests/specs/4way/desktopSharing.spec.ts, tests/specs/alone/lockRoomDigitsOnly.spec.ts
=> Lock room, mute and grant moderator tests.

tests/helpers/Participant.ts, tests/helpers/participants.ts, tests/pageobjects/Filmstrip.ts, tests/pageobjects/IframeAPI.ts, tests/pageobjects/LargeVideo.ts, tests/pageobjects/PreMeetingScreen.ts, tests/specs/2way/displayName.spec.ts, tests/specs/2way/grantModerator.spec.ts, tests/specs/3way/audioVideoModeration.spec.ts, tests/specs/3way/breakoutRooms.spec.ts, tests/specs/3way/codecSelection.spec.ts, tests/specs/3way/lobby.spec.ts, tests/specs/3way/startMuted.spec.ts, tests/specs/4way/desktopSharing.spec.ts, tests/specs/alone/lockRoomDigitsOnly.spec.ts, tests/specs/helpers/DialIn.ts
=> feat(tests): Print error on execute failure.

react/features/settings/components/native/ProfileView.tsx
Fixes #15617 
Added `hasBottomTextInput `to true
=> Fix: Ensure Apply Button Remains Visible When Keyboard Appears

resources/prosody-plugins/mod_av_moderation_component.lua
=> fix(avmoderation): Fix actor jid.

react/features/polls/components/native/PollCreate.tsx
**Fixes:**
Fixes #15629
**Approach:**
Implemented `setTimeout` with `scrollToEnd`
https://github.com/user-attachments/assets/9a69f6b4-9967-4317-8d30-a3136bd4d0e5
=> Fix:Auto-Scroll Issue in Poll Screen After Adding an Option

config.js, react/features/base/config/configType.ts, react/features/notifications/actions.ts, react/features/notifications/constants.ts, react/features/recording/actions.any.ts
=> fix(recordings) increase duration for recording prompt notification

resources/prosody-plugins/mod_fmuc.lua
=> fix(fmuc): Updates auto-promote case checks.

resources/extra-large-conference/README.md
=> fix(docs): Updates the extra large conf docs.

lang/main-it.json
Fixes Pr lint - Update main-it.json #14754
=> lint : Update main-it.json pr#14754

modules/API/API.js, modules/API/external/external_api.js
=> feat: allow specifying actions in custom notifications

react/features/recent-list/functions.native.ts
=> fix:Yesterday’s Timing Not Displaying on Android 

react/features/conference/components/native/Conference.tsx, react/features/large-video/components/LargeVideo.web.tsx
=> feat(conference): hide display name label based on config

android/app/src/main/java/org/jitsi/meet/MainActivity.java, android/sdk/build.gradle, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiVideoDecoderFactory.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiVideoEncoderFactory.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
In addition, add the ability to initialize custom video encoder / decoder factories.
=> feat(android) use hardware video decoders by default

ios/app/app.xcodeproj/project.pbxproj, ios/sdk/sdk.xcodeproj/project.pbxproj, ios/sdk/src/ExternalAPI.h, ios/sdk/src/ExternalAPI.m, ios/sdk/src/JitsiMeetView.h, ios/sdk/src/JitsiMeetView.m
=> fix(ios) fix exporting JitsiMeetView.{start,stop}Recording to Swift

css/_meetings_list.scss, css/_variables.scss, css/_welcome_page.scss
- Add padding to the header of the welcome page in small screens.
- Fix the tab content in the welcome page, because there was an ugly overflow.
- Add a nice hover effect to the welcome page button
=> fix: padding in the welcome page and overflow of in small screens

tests/env.example, tests/helpers/Participant.ts, tests/helpers/participants.ts, tests/helpers/types.ts, tests/pageobjects/LobbyScreen.ts, tests/pageobjects/PasswordDialog.ts, tests/pageobjects/PreMeetingScreen.ts, tests/specs/2way/audioOnly.spec.ts, tests/specs/2way/iFrameApiParticipantsPresence.spec.ts, tests/specs/2way/lockRoom.spec.ts, tests/specs/3way/audioVideoModeration.spec.ts, tests/specs/3way/avatars.spec.ts, tests/specs/3way/breakoutRooms.spec.ts, tests/specs/3way/lobby.spec.ts, tests/specs/3way/startMuted.spec.ts, tests/specs/alone/invite.spec.ts, tests/wdio.conf.ts
=> Some more tests improvements and new features

tests/helpers/participants.ts
=> fix: Fix invite tests and force generate token.

conference.js, config.js, react/features/base/conference/middleware.native.ts, react/features/base/conference/middleware.web.ts, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/base/connection/actions.web.ts, react/features/conference/middleware.native.ts, react/features/conference/middleware.web.ts
=> feat(base/config): notify user on conference destruction option

react/features/recording/components/Recording/native/RecordingConsentDialog.tsx, react/features/recording/functions.ts
=> fix(rn,recording) fix closing the consent dialog

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastAction.java, android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ExternalAPIModule.java, ios/sdk/src/ExternalAPI.h, ios/sdk/src/ExternalAPI.m, ios/sdk/src/JitsiMeetView.h, ios/sdk/src/JitsiMeetView.m, react/features/mobile/external-api/middleware.ts
=> feat(android/ios): Native API to overwrite config

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastEvent.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, ios/app/src/ViewController.m, ios/sdk/src/JitsiMeetViewDelegate.h, react/features/mobile/external-api/middleware.ts
=> feat(android/ios): add CONFERENCE_UNIQUE_ID_SET event

config.js, react/features/base/config/configType.ts, react/features/base/jwt/middleware.ts
There are cases where if tenant doesn't match features are ignore in the backend via prosody and session.jitsi_meet_tenant_mismatch.
=> feat(jwt): Adds an option to match tenant.

react/features/base/participants/middleware.ts, react/features/base/util/uri.ts
=> fix: Ignores disableThirdPartyRequests when using data url.

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastEvent.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, ios/app/src/ViewController.m, ios/sdk/src/JitsiMeetViewDelegate.h, react/features/mobile/external-api/middleware.ts
=> feat(android/ios): Recording status changed event

webpack.config.js
=> feat(dev) make webpack-dev-server listen on all interfaces

lang/main.json, react/features/participants-pane/components/native/ContextMenuMore.tsx, react/features/participants-pane/components/web/FooterContextMenu.tsx
=> fix(av-moderation): Skip hiding AV moderation menu.

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastAction.java, android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java, android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastReceiver.java, ios/sdk/src/JitsiMeetView.h, react/features/mobile/external-api/middleware.ts
=> feat(android): simplify BroadcastAction

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, ios/sdk/src/JitsiMeetView.h, ios/sdk/src/JitsiMeetView.m
=> feat(ios): Update data types for events

ios/sdk/src/ExternalAPI.m
=> fix(ios): overwriteConfig payload structure

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastReceiver.java
=> feat(android): fix case where actions have no data

package-lock.json, package.json, react/features/base/logging/middleware.ts, tests/specs/2way/mute.spect.ts
=> feat(logging): Let ljm handle its logging to rtcStats.

react/features/chat/functions.ts
Added missing types for typescript format.
=> Annotate with type

resources/prosody-plugins/mod_filter_iq_rayo.lua, resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_muc_allowners.lua, resources/prosody-plugins/mod_muc_flip.lua, resources/prosody-plugins/mod_muc_meeting_id.lua, resources/prosody-plugins/mod_muc_wait_for_host.lua, resources/prosody-plugins/mod_speakerstats_component.lua, resources/prosody-plugins/mod_token_verification.lua, resources/prosody-plugins/mod_visitors.lua, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
This is in support of the new prosody 13 that will be released.
=> Prosody is_admin

.github/workflows/ci.yml
=> fix(ci) fix action branch name

debian/jitsi-meet-prosody.postinst, doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
=> Fixes jitsi-meet installation with prosody 13.0.0

react/features/recording/functions.ts
=> fix(recordings) skip consent for jibri participant

tests/helpers/Participant.ts, tests/specs/2way/lockRoom.spec.ts, tests/specs/3way/lobby.spec.ts, tests/specs/3way/startMuted.spec.ts
=> Tests improvements

CONTRIBUTING.md
##Changes
- Added Forum Link in contributing.md
- Make some words Bold in order to increase Readability
=> Added Forum Link in CONTRIBUTING.md

react/features/base/jwt/middleware.ts
=> fix(jwt): Fix tenant matching for features when tenant is missing.

tests/specs/2way/iFrameApiParticipantsPresence.spec.ts
=> feat(tests): Adds check for name on join/leave webhooks.

react/features/mobile/external-api/middleware.ts
=> fix(mobile/external-api): check types for recording error, initiator, terminator

resources/extra-large-conference/pre-configure.sh, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
=> fix(visitors): Fixes using table for moderators. 

react/features/base/ui/utils.ts
=> fix(base/ui): fallback to og value if not found in allTokens

package-lock.json, package.json, react/features/base/logging/reducer.ts
=> fix(logging): Logger names changed, adjusting.

resources/prosody-plugins/mod_visitors_component.lua
=> fix(visitors): Updates promotion path for non jaas meetings.

tests/helpers/WebhookProxy.ts, tests/helpers/participants.ts, tests/helpers/types.ts, tests/pageobjects/IframeAPI.ts, tests/specs/2way/iFrameApiTranscriptions.spec.ts, tests/wdio.firefox.conf.ts
=> Transcription tests

config.js
=> fix(config) Update the codec preference order

react/features/base/jwt/functions.ts, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/functions.any.ts, resources/prosody-plugins/mod_jitsi_permissions.lua
=> fix(features): Allow checking features when jwt is not available.

tests/helpers/Participant.ts, tests/helpers/participants.ts, tests/helpers/types.ts, tests/specs/2way/iFrameApiParticipantsPresence.spec.ts, tests/specs/2way/lockRoom.spec.ts, tests/specs/alone/dialInAudio.spec.ts, tests/wdio.conf.ts
=> Invite tests

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
=> fix(prosody): Enables websocket in default config.

config.js, package-lock.json, package.json, resources/prosody-plugins/mod_jitsi_permissions.lua, resources/prosody-plugins/mod_muc_lobby_rooms.lua, resources/prosody-plugins/mod_room_metadata_component.lua
=> feat(metadata): Converts presence startMuted to metadata.

react/features/toolbox/actions.any.ts, react/features/toolbox/constants.ts, react/features/toolbox/functions.native.ts, react/features/toolbox/reducer.ts, react/features/toolbox/types.ts
=> feat(toolbar): Enable 9th and 10th button

react/features/base/ui/Tokens.ts, react/features/base/ui/components/web/ContextMenu.tsx, react/features/base/ui/functions.native.ts, react/features/base/ui/functions.web.ts
For rem to be used in react native, we need to convert values to px
=> feat(base/ui/native): Convert rem to px 

react/features/base/util/spot.ts, react/features/large-video/components/LargeVideo.web.tsx, react/features/recording/functions.ts
=> fix(recording) skip consent dialog on Spot TV

config.js, tests/specs/3way/codecSelection.spec.ts
=> fix(codecSelection): test

react/features/base/avatar/functions.ts, react/features/invite/components/add-people-dialog/native/AddPeopleDialog.tsx
For the case of AddPeopleDialog, isCORSAvatarURL takes url param as a function aka an Icon component, thus we need it to return false.
=> fix(invite/add-people-dialog): isCorsAvatarURL update

tests/specs/3way/codecSelection.spec.ts
=> fix(test): Fix codec selection test

resources/prosody-plugins/util.lib.lua
=> fix(prosody): Adds a nil check for ends_with utility.

conference.js, modules/API/external/external_api.js, modules/API/external/functions.js, react/features/base/devices/actions.web.ts, react/features/device-selection/functions.web.ts
=> feat(external_api,devices) drop use of isDeviceListAvailable

tests/env.example, tests/helpers/participants.ts, tests/pageobjects/IframeAPI.ts, tests/specs/alone/dialInAudio.spec.ts, tests/specs/alone/iFrameApiInvite.spec.ts, tests/specs/helpers/DialIn.ts, tests/wdio.firefox.conf.ts
Tests dial-in, dial-out and inviting sip-jibri.
=> feat(tests): Adds invite test.

tests/specs/alone/dialInAudio.spec.ts
=> feat(tests): Prefer to generate token for dial in.

react/features/base/conference/actions.any.ts
isReplaced return a number from ljm, until next update.
https://github.com/jitsi/lib-jitsi-meet/pull/2773
=> feat(base/conference): add isReplaced param for KICKED conference event

tests/env.example, tests/helpers/utils.ts, tests/wdio.conf.ts
=> feat(tests): Use more predictable room names.

react/features/base/ui/functions.any.ts, react/features/base/ui/functions.native.ts, react/features/base/ui/functions.web.ts, react/features/base/ui/types.ts, react/features/display-name/components/web/StageParticipantNameLabel.tsx, react/features/display-name/components/web/styles.ts, react/features/subtitles/components/web/Captions.tsx
- Fixes the issue where the subtitles appear at the center of the screen.
- Fixes the issue with the size of the display name badge on stage is small and not scalable.
=> Subtitles position & Stage name badge size fixes

react/features/base/popover/components/Popover.web.tsx, react/features/base/ui/components/web/ContextMenuItem.tsx, react/features/base/ui/components/web/ContextMenuItemGroup.tsx, react/features/settings/components/web/video/VideoSettingsContent.tsx, react/features/settings/components/web/video/VideoSettingsPopup.tsx
This was accessible for the keyboard, but it had some issues regarding HTML validity. Now it also gives better context to screen readers.
=> Make the video menu HTML valid for accessibility

tests/env.example, tests/helpers/participants.ts, tests/pageobjects/IframeAPI.ts, tests/specs/alone/iFrameApiRecording.spec.ts, tests/wdio.firefox.conf.ts
=> feat(tests): Recording and live-streaming tests.

tests/helpers/utils.ts, tests/specs/2way/iFrameApiChat.spec.ts, tests/wdio.firefox.conf.ts
=> feat(tests): Chat iframeApi tests.

resources/prosody-plugins/mod_room_metadata_component.lua
=> feat(metadata): Pushes metadata early before join.

conference.js, package-lock.json, package.json, react/features/base/conference/actions.any.ts, react/features/base/conference/middleware.any.ts, react/features/base/conference/reducer.ts, react/features/base/conference/subscriber.ts, tests/specs/3way/startMuted.spec.ts
=> fix(conference) Mute user when startMuted policy update is received in conference meta data

react/features/base/conference/functions.ts, react/features/base/connection/actions.native.ts, react/features/base/connection/actions.web.ts, react/features/participants-pane/components/web/VisitorsList.tsx, react/features/visitors/components/web/VisitorsQueue.tsx, tests/helpers/Participant.ts, tests/helpers/WebhookProxy.ts, tests/helpers/participants.ts, tests/helpers/types.ts, tests/pageobjects/Visitors.ts, tests/specs/2way/iFrameApiVisitors.spec.ts, tests/specs/2way/iFrameApiVisitorsLive.spec.ts
=> Visitors tests

config.js, lang/main.json, react/features/app/middlewares.web.ts, react/features/app/reducers.web.ts, react/features/app/types.ts, react/features/base/conference/reducer.ts, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/base/icons/components/Icon.tsx, react/features/base/ui/components/types.ts, react/features/base/ui/components/web/Tabs.tsx, react/features/base/ui/types.ts, react/features/chat/components/web/Chat.tsx, react/features/chat/components/web/ChatHeader.tsx, react/features/chat/constants.ts, react/features/file-sharing/actionTypes.ts, react/features/file-sharing/actions.ts, react/features/file-sharing/components/web/FileSharing.tsx, react/features/file-sharing/constants.ts, react/features/file-sharing/functions.any.ts, react/features/file-sharing/logger.ts, react/features/file-sharing/middleware.web.ts, react/features/file-sharing/reducer.ts, react/features/file-sharing/types.ts, resources/file-sharing.yaml
=> feat(file-sharing/web): Enable file sharing in meeting

react/features/file-sharing/middleware.web.ts
=> fix(file-sharing) middleware is not async

lang/main-it.json
-Implemented Italian translation for file sharing
=> lang: Update Italian translation

react/features/file-sharing/components/web/FileSharing.tsx, react/features/file-sharing/middleware.web.ts
=> File sharing fixes

tests/specs/3way/startMuted.spec.ts
=> fix(test) Add media checks for startMuted test.

react/features/file-sharing/components/web/FileSharing.tsx
1. Added vertical scroll.
2. Fixed drag and drop when container is populated.
3. Fixed share file button, populated container and scroll interaction.
4. Centered fileItemDetails.
=> feat(file-sharing): ui fixes

react/features/file-sharing/components/web/FileSharing.tsx
=> feat(file-sharing): sort shared files

config.js, react/features/base/config/configType.ts, react/features/base/config/configWhitelist.ts, react/features/chat/components/AbstractMessageContainer.ts
=> Disable reactions in chat

config.js
=> doc(config): Add docs for  transcription.disableClosedCaptions

react/features/file-sharing/components/web/FileSharing.tsx, react/features/file-sharing/middleware.web.ts, react/features/file-sharing/types.ts
=> feat(file-sharing): added author display name

react/features/file-sharing/reducer.ts
=> fix(file-sharing) fix handling undefined metadata

resources/prosody-plugins/mod_jitsi_permissions.lua
If backend modify permissions can force sending those on the initial presence.
=> fix(permissions): Adds an option to force-send permissions.

config.js, modules/API/API.js, react/features/base/config/configType.ts, react/features/mobile/external-api/middleware.ts, react/features/recording/actions.any.ts, react/features/recording/components/Recording/AbstractStartRecordingDialog.ts, react/features/subtitles/actions.any.ts, react/features/subtitles/middleware.ts
=> feat(transcribing): Adds config to skip inviting jigasi on transcribing.

resources/prosody-plugins/mod_filter_iq_rayo.lua
=> feat(prosody): Allow filter_rayo to be loaded in other virtual hosts.

config.js, react/features/base/config/configType.ts, react/features/base/jwt/middleware.ts
=> feat(jwt): New option to control user info check.

webpack.config.js
=> feat(webpack): rewrite CDN urls when proxying with webpack

conference.js, react/features/base/conference/middleware.any.ts, react/features/base/tracks/middleware.any.ts, react/features/recording/components/Recording/native/RecordingConsentDialog.tsx, react/features/recording/components/Recording/web/RecordingConsentDialog.tsx, react/features/stream-effects/audio-mixer/AudioMixerEffect.ts
=> fix(recordings) create missing local tracks when unmuting after consent

react/features/transcribing/subscriber.ts
=> feat(iframeAPI): Fires transcribing events when subtitles are on.

android/app/build.gradle
Reverts jitsi/jitsi-meet#16149
=> Revert "feat(android) drop support for x86 architecture"

resources/prosody-plugins/mod_jitsi_permissions.lua
=> fix(permissions): Fixes grant owner for participant with token.

lang/main.json, react/features/polls/components/native/PollsPane.tsx, react/features/polls/components/web/PollsPane.tsx
=> fix: hide create poll button rather than disabling it

lang/main.json, react/features/chat/components/native/ChatInputBar.tsx, react/features/chat/components/native/styles.ts, react/features/chat/components/web/ChatInput.tsx
=> fix: hide chat controls and show disabled notice instead

android/settings.gradle, ios/Podfile.lock, package-lock.json, package.json, react-native-sdk/package.json, react/features/analytics/handlers/AmplitudeHandler.ts, react/features/analytics/handlers/amplitude/fixDeviceID.native.ts, react/features/analytics/handlers/amplitude/fixDeviceID.web.ts, react/features/analytics/handlers/amplitude/lib.native.ts, react/features/analytics/handlers/amplitude/lib.web.ts
Replaced amplitude dependencies with https://github.com/amplitude/Amplitude-TypeScript
=> dep(@amplitude/react-native): replace with @amplitude/analytics-react-native

react/features/file-sharing/middleware.web.ts, react/features/file-sharing/utils.ts
=> fix(file-sharing) Keep original filename on file download

package-lock.json, package.json, react/features/visitors/middleware.ts, resources/prosody-plugins/mod_visitors_component.lua, resources/prosody-plugins/util.lib.lua
=> fix(visitors): Checks mainMeetingParticipants array to allow joins.

react/features/file-sharing/functions.any.ts
=> fix(file-sharing) hide upload button for visitors

react/features/analytics/handlers/AmplitudeHandler.ts, react/features/analytics/handlers/amplitude/fixDeviceID.native.ts, react/features/analytics/handlers/amplitude/fixDeviceID.web.ts
Note the use of jitsiLocalStorage since we also need to consider the case when local storage is performed in the host page when in an iframe.
=> fix(amplitude) sync device ID on web too

react/features/visitors/actions.ts
=> fix(visitors): Avoid go live to overwrite other settings.

resources/prosody-plugins/mod_av_moderation_component.lua
Handle av_can_unmute flag when first moderator joins
=> feat(av_moderation): handle av_can_unmute policy

resources/prosody-plugins/mod_av_moderation_component.lua
There are some startMuted policies we set when starting it.
=> fix(av-moderation): Fixes auto starting av moderation.

config.js, react/features/analytics/functions.ts, react/features/analytics/handlers/AbstractHandler.ts, react/features/analytics/handlers/AmplitudeHandler.ts, react/features/analytics/handlers/amplitude/lib.native.ts, react/features/analytics/handlers/amplitude/lib.web.ts, react/features/base/config/configType.ts
Ref: https://amplitude.com/docs/sdks/analytics/browser/migrate-from-javascript-sdk-to-browser-sdk-2-0
=> fix(amplitude) adjust to new SDK API changes

react/features/base/conference/middleware.any.ts
When you see the error, you may click join on pre-join again, which may succeeded, so clear previous errors.
=> feat(conference): Clears any error from previous attempts.

resources/file-sharing.yaml, resources/prosody-plugins/mod_filesharing_component.lua, resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_visitors.lua, resources/prosody-plugins/util.lib.lua
=> feat(visitors): Adds showing shared files in the meeting.

resources/prosody-plugins/mod_muc_allowners.lua, resources/prosody-plugins/mod_muc_displayname.lua
Options to hide it for non-moderators and for all.
=> feat: Adds a room option to hide display name.

react/features/lobby/components/native/styles.ts, react/features/visitors/components/native/VisitorsQueue.tsx, react/features/visitors/components/web/VisitorsQueue.tsx
=> feat(visitors-queue) Add leave meeting button

react/features/visitors/middleware.ts
Currently we don't close the socket for the participants in the queue when the page is closed.
=> fix(go-live): Disconnect on page close.

react/features/visitors/VisitorsListWebsocketClient.ts, react/features/visitors/websocket-client.ts
Add unsubscribe from topics - called automatically on close if not called before
=> fix(go-live): unsubscribe from topics before closing if not done already

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiInitializer.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
Initialise ReactInstanceManagerHolder during application startup, making it ready before onCreate() is called.
=> feat(android): init RIMHs app before on create

resources/prosody-plugins/util.lib.lua
Was checking only for added or removed keys, but not for modified values.
=> fix: Fixes table equals.

react/features/analytics/handlers/amplitude/fixDeviceID.web.ts
=> chore(analytics) Add getter for amplitude deviceId

react/features/filmstrip/components/native/Filmstrip.tsx
=> fix for iOS locked screen call

config.js
=> doc(config): disablePrivateChat visitor value

tests/helpers/Participant.ts, tests/specs/2way/mute.spect.ts, tests/specs/3way/startMuted.spec.ts, tests/specs/4way/lastN.spec.ts, tests/specs/helpers/DialIn.ts, tests/specs/iframe/visitors.spec.ts, tests/specs/iframe/visitorsLive.spec.ts
This allows the logs to show which one definitely failed.
=> test: Check for send/receive independently.

resources/prosody-plugins/mod_room_metadata_component.lua
=> feat(metadata): Adds logging when metadata is modified or sent.

react/features/recording/components/Recording/native/RecordButton.ts
Explicitly set RecordButton visible prop to a true or false value like web does.
=> feat(recording/native): explicitly set button visible prop to a true or false value 

lang/main.json, package-lock.json, package.json, react/features/calendar-sync/web/microsoftCalendar.ts, react/features/chat/components/AbstractMessageRecipient.ts, react/features/chat/components/native/ChatMessage.tsx, react/features/chat/components/web/ChatMessage.tsx, react/features/chat/functions.ts, react/features/chat/middleware.ts, react/features/chat/reducer.ts, react/features/chat/types.ts, react/features/visitors/functions.ts, resources/prosody-plugins/README.md, resources/prosody-plugins/mod_fmuc.lua, resources/prosody-plugins/mod_muc_displayname.lua, resources/prosody-plugins/mod_visitors.lua
=> Display name updates

lang/main.json
=> fix: Fixes missing string for shortcut.

resources/prosody-plugins/mod_room_metadata_component.lua
=> fix: Fixes log message about meeting id.

react-native-sdk/package.json
=> feat(react-native-sdk): add react-native-worklets-core as a peer dep

.github/workflows/ci.yml
=> .github: fix CI iOS SDK step

package-lock.json, package.json, react/features/base/conference/middleware.any.ts, resources/prosody-plugins/mod_muc_max_occupants.lua
=> feat(visitors): Retries as a visitor when max occupants reached.

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
=> chore(android): apply edge to edge if supported or enforced

resources/prosody-plugins/mod_muc_displayname.lua
=> fix(muc_displayname): Handles few more cases for missing nick element.

react/features/mobile/polyfills/browser.js, react/features/mobile/polyfills/querySelectorPolyfill.js
=> feat(RN): Add querySelector polyfill.

CLAUDE.md, package.json
=> feat(CLAUDE.md): Add

.github/workflows/ci.yml
=> .github(workflows): add clean Xcode step

resources/prosody-plugins/token/util.lib.lua
=> feat(token_verification): Adds more token failure reasons on verify room.

modules/API/API.js, react/features/base/conference/actionTypes.ts, react/features/base/conference/actions.any.ts, react/features/base/conference/reducer.ts, react/features/follow-me/actionTypes.ts, react/features/follow-me/actions.ts, react/features/follow-me/reducer.ts, react/features/follow-me/subscriber.ts, react/features/settings/actions.web.ts, react/features/settings/components/native/ModeratorSection.tsx, react/features/settings/functions.any.ts
=> fix(follow-me): Moves follow-me state to its feature.

react/features/chat/middleware.ts
=> fix(chat): Fixes sending message after system message.

tests/specs/3way/startMuted.spec.ts
=> fix(tests): Fixes randomly failing start muted test.

resources/prosody-plugins/mod_short_lived_token.lua
=> fix(shot_lived_token): Handles case with empty string for tenant.
