libs/app.bundle.js, modules/xmpp/JingleSession.js, package.json
We need to queue attempts to call modifySources to prevent errors in setLocalDescription when streams are ended and started close together (such as when appshare ends and a user starts streaming their camera again). We need to let the asynchronous function flow in modifySources finish before we kick off another set of function calls to setRemoteDescription/createAnswer/setLocalDescription.
I found the easiest way to do this safely was to use the async module's queue methods, but I'm open to implementing some other solution as well.
This seems to help address issue #248
=> Fix stream end/start race condition

config.js, modules/RTC/RTCUtils.js, modules/statistics/CallStats.js, modules/xmpp/strophe.jingle.js
now fully supported by jitsi-videobridge and all browsers which we
support (and if we need to enable them conditionally because of browser
compatibility in the future, we should do it based on run-time browser
detection.)
I'll merge this in a few days unless there are objections.
=> Removes the useBundle and useRtcpMux options from config.js. These are

package.json
.. to avoid warnings during installing npm dependencies
=> Use valid SPDX license identifier for Jitsi-Meet NPM package description

modules/RTC/RTC.js, modules/RTC/RTCUtils.js, modules/statistics/CallStats.js, modules/statistics/statistics.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/TraceablePeerConnection.js, service/RTC/RTCEvents.js
Use CallStats to report errors in `getUserMedia`, `addIceCandidate` and [others.](http://www.callstats.io/api/#enumeration-of-wrtcfuncnames)
=> Callstats error reporting

modules/UI/videolayout/VideoLayout.js
Fixes issues in the client when the focus user has been renamed from "focus" on the jitsi-meet server.
In client console one may see:
function ()  - error -  TypeError: remoteVideos[resourceJid] is undefined
Other issues possibly solved include the focus user not granting the first web client user moderator privileges and the video not coming back to the first web client in the large video window.
=> Use member.isFocus to decide whether a given member is the focus user

config.js, css/contact_list.css, index.html, modules/UI/avatar/Avatar.js
A step toward making third party javascript able to be disabled with a config entry.
It does not address the gravatar requests which are still present. [EDIT: commit 895bb3f helps remove these requests]
The approach in this request seems to work for the callstats requests, I am unsure if it is working exactly correctly for GA.
=> Load 3rd party JavaScript if config.enableThirdPartyRequests true

JitsiMeetJS.js
Stop using the polyfill when you are assign the es6-promise after that anyway
The es6-promise.polyfill() is broken for Chrome atm and replaces the native Promise and swallows unhandled errors. https://github.com/jakearchibald/es6-promise/issues/70
=> Stop using the polyfill when assigning it anyway

modules/RTC/JitsiLocalTrack.js, modules/RTC/RTC.js
Add `deviceId` which was used to create `JitsiLocalTrack` to the object to re-use it when unmuting the track
Fixes the issue that when creating local tracks with specific devices after unmuting the new tracks were created with default devices again.
=> Add `deviceId` used to create `JitsiLocalTrack` to the track object

conference.js, modules/UI/videolayout/RemoteVideo.js
When we click on small video of remote user then user should be pinned.
Currently when moderator clicks on popup menu of remote user, that user also becomes pinned (even if moderator just want to mute him).
PR fixes this issue.
=> Do not pin participant if moderator clicked item in remote user menu

.jshintignore, modules/UI/UI.js, modules/UI/videolayout/LargeVideo.js, modules/UI/videolayout/LocalVideo.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/SmallVideo.js, modules/UI/videolayout/VideoLayout.js
This PR ensures that we hide large video if stream is muted.
It fixes issue on Safari when after muting desktop stream there is desktop image covered by avatar instead of avatar on black background.
Also it fixes remaining jshint errors.
=> Fix screensharing mute on safari

conference.js, css/chat.css, modules/UI/UI.js, modules/UI/side_pannels/SidePanelToggler.js, modules/UI/side_pannels/chat/Chat.js, modules/UI/side_pannels/contactlist/ContactList.js, modules/UI/side_pannels/settings/SettingsMenu.js, modules/UI/util/MessageHandler.js, modules/UI/util/UIUtil.js, modules/UI/videolayout/LocalVideo.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/VideoLayout.js, modules/settings/Settings.js
* ensure that we escape nicknames before adding them to the DOM. 
* improve nickname management 
* remove redundant `inputDisplayNameHandler` methods from `VideoLayout` and `LocalVideo` and use `UIEvents.NICKNAME_CHANGED` instead
* ensure that we hide chat when local user empties his nickname
=> Escape nicknames before displaying them

conference.js
Uses the Promise returned on mute/unmute, just prints when calls were canceled due to operation in progress.
=> Syncs mute/unmute calls.

nwjs-integration/index.html, nwjs-integration/package.json
example NW.js app with user agent and desktop sharing function expected by lib-jitsi-meet
depends on https://github.com/jitsi/lib-jitsi-meet/pull/33
=> example NW.js app

config.js
In conjunction with corresponding commits in lib-jitsi-meet and jicofo
this enables adaptive simulcast whenever simulcast is enabled.
=> Enable adaptive simulcast by default

modules/UI/side_pannels/chat/Chat.js, modules/UI/side_pannels/contactlist/ContactList.js, modules/UI/side_pannels/settings/SettingsMenu.js, modules/UI/util/UIUtil.js
After some investigation I found that the jquery call of  is(":visible") have problems on Chrome and may return inconsistent results even with "display" property set to "none". I'm now using document.getElementById, which should much faster and then checking the offsetParent of the element.
=> Fix the black stripe (another try)

prosody-plugins/mod_auth_token.lua, prosody-plugins/token/util.lib.lua
Adjusts log messages and informs about missing 'room' claim.
=> Improve token error reporting in Prosody JWT plugin

config.js
Jicofo uses pubsub and discoinfo to configure the bridge.
=> Nukes the pre-configured bridge from the config file.

index.html
This is meant to support adding a <base> attribute by replacing base.html with a user-provided file
This also removes the separate round-trip for config.js, instead including its values directly into the rendered index.html
=> SSI inclusion of config.js

modules/UI/side_pannels/chat/Chat.js
allows for better override using base href, otherwise the image fails to load when base href is overridden
=> make the chatArrow image reference relative

conference.js, lang/main.json, modules/UI/UI.js, modules/UI/side_pannels/settings/SettingsMenu.js, nwjs-integration/index.html
This PR is a 'clone' of https://github.com/jitsi/jitsi-meet/pull/661 into the jitsi organization repository where I have (1) push access and (2) automatic PR testing.
@tsareg wrote:
Show dialog with error when GUM calls fail, also fix some minor bugs related to enabling webcam icon or restoring correct <select> state when failed to change camera/mic/audio output.
=> Tsareg handle create local tracks errors better

external_api.js
When accessing via `http://` when the url is prefix is `//` you get this error.
So it needs to be set to `https://` to prevent this error.  
```
JitsiMeetExternalAPI(domain, room_name, width, height, parentNode,
configOverwrite, interfaceConfigOverwrite, ssl)
```
ssl optional param to force the url to https
=> Switch to https on iframe creation

index.html
Make FF stop complaining about the character encoding of the HTML document
not being declared.
=> Defines the document encoding.

conference.js
call to createLocalTracks may resolve with single argument, so "videoTracks" argument might be undefined in this case
=> Fix TypeError when one of audioTracks or videoTracks was undefined

debian/control
Used to minimize strophe-plugins which were inside the source tree and now npm handles them.
=> Removes unused dependency.

modules/UI/UI.js, modules/UI/util/MessageHandler.js, modules/devices/mediaDeviceHelper.js
To make sure we a showing only one device error dialog at a time, we close the previous one every time.
It's better to be merged together with https://github.com/jitsi/lib-jitsi-meet/pull/139, though it's not mandatory.
=> Fixing various edge-cases when two gUM error dialogs might be shown and other possible bugs

Makefile, README.md
Executes npm update before making, in order to update latest version of packages like lib-jitsi-meet which are updated from git. The npm install method is supposed to only resolve dependencies and not update to latest versions.
=> Executes npm update before making.

package.json
Using "compatible version" as ^... matches latest version 1.12.0 and not 1.10.5 (matches >=1.10.5 < 2.0.0) and this prevents it building from source with latest nodejs on clean environment.
=> Match the exact version of jquery-ui.

connection.js, modules/UI/authentication/AuthHandler.js
Integrates external login service which provides JWT token once the user authenticates.
Add 'tokenAuthUrl' to config.js:
tokenAuthUrl: "https://login.service.net/login.html?room={room}&roleUpgrade={roleUpgrade}"
{room} - name of the conference room
{roleUpgrade} - indicates if it's a role upgrade scenario where user logs in from a popup, then the service should send the JWT token using postMessage JS method and pass it as { jwtToken: 'the token' }. In regular scenario the service should append the token as 'jwt' param and redirect user back to the meet app. Example URL:
https://meet.jit.si/someroom?jwt=ba53db68....cb68a4d93
=> Jwt login service 2

modules/keyboardshortcut/keyboardshortcut.js
KeyboardEvent is a mess.
KeyboardEvent.which gives you, in theory, a decimal representation of the key pressed.
"r" or "R" gives you 82, which is "R", you can look at KeyboardEvent.shiftKey,
but you don't have access to capslock...
Maybe you want to use numbers, but of course NumPad will not give you the same than
"normal" numbers ...
Now if you use something else than letter, for exemple "?",
on a QWERTY keyboard "/" and "?" gives you 191,
on a AZERTY keyboard "," and "?" gives you 188, so we have to stick to letters.
This was for keydown and keyup events, keypressed event return the real char
(lower "a", "/", "?", ...) but it fails in some cases
The only non broken property is KeyboardEvent.key,
but it's only supported since Chrome 51, Opera 38, and not supported by Safari …
=> Improve keyboard shortcut handling

modules/UI/videolayout/RemoteVideo.js
Handles the case where the remote track is with initial value of camera and no further events are received for video type changed.
=> Uses videoType from the video track for the initial value.

prosody-plugins/token/util.lib.lua
This is not currently a vulnerability because the upstream `jwt` package does not support `none` in the `alg` claim at all, however, in case they ever do add support in the future we don't want to become vulnerable to downgrade attacks, so let's check the alg claim ourselves as well.
=> Check for "none" alg in JWT signing

modules/UI/UI.js
This PR removes query arguments like JWT token from the invite URL. It also cleans up the URL visible to the user.
=> Remove query string

debian/jitsi-meet-tokens.postinst, prosody-plugins/token/util.lib.lua
We need to switch back to the 'luajwt' library which is capable to work with other libraries(the old lib converts raw signature to hash string which makes it not RFC compliant), provides better error messages and actually works once installed through luarocks.
Temporarily reference 'luajwtjitsi' luarock for immediate deployment until our changes with RS256 support eventually get merged with the master.
=> Switch back to 'luajwt' in order to fix broken JWT

modules/UI/UI.js, modules/UI/ring_overlay/RingOverlay.js
After this PR is merged, the toolbar will no longer be displayed when the "ring overlay" is shown.
=> Hide the toolbar when the the ring overlay is displayed

modules/UI/UI.js
IE 10 does not support "window.location.origin"
=> Fix broken invite URL on IE10

modules/UI/side_pannels/settings/SettingsMenu.js
When the Temasys plugin is not installed we have to wait for the WebRTC stack to be ready before checking if listing devices is supported or not.
Requires https://github.com/jitsi/lib-jitsi-meet/pull/199
=> Fix a crash on IE/Safari when plugin is not installed

css/jitsi_popover.css, css/popup_menu.css, css/videolayout_default.css, modules/UI/videolayout/RemoteVideo.js
Some browsers don't render the object-fit: cover property correctly and the thumbnail video isn't clipped to fit the boundaries of its parent. So, we introduce a fix by adding a second property overflow:hidden to the parent elements containing the thumbnail video.
This however introduced a side effect. The remote participant menu (shown for moderators only) has disappeared. It was an element added directly to the DOM which parent was the container with the new overflow:hidden property. So, the new property was preventing anything to be shown out of the boundaries of the thumbnail. I've fixed this by refactoring the menu to be shown through the JitsiPopover. Thus making it almost identical to the implementation we have for the ConnectionIndicator for example.
=> Object fit fix and refactoring around it

index.html
We have removed toolbar separators in the top toolbar, so this change is to make bottom toolbar consistent with the top toolbar.
=> Remove bottom toolbar button separators

modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/VideoLayout.js
There was a bug that the handlers for menuItem for mute and kick are added for all remote participants. When clicked multiple handlers are executed and the action will be executed for all remote participants.
=> Fixes muting particular remote participant.

css/keyboard-shortcuts.css, index.html, modules/UI/toolbars/BottomToolbar.js, modules/UI/toolbars/Toolbar.js, modules/UI/util/UIUtil.js, modules/keyboardshortcut/keyboardshortcut.js
Shortcuts are now registered dynamically through the toolbar button they represent. Only enabled buttons would register a shortcut. Thus only the registered shortcuts will appear in the help menu. I have also added an "unregisterShortcut" method, which isn't currently used. So an open question is, do we need to unregister a shortcut at some point, keeping in mind that we cannot currently enable/disable a feature (toolbar button) during runtime.
=> Attach keyboard shortcuts to features

modules/keyboardshortcut/keyboardshortcut.js
Performs some checks on the shortcut attribute in order to prevent wrong shortcuts appearing in the tooltips of buttons without shortcut.
=> Fix shortcut appearing in tooltip of wrong buttons

modules/UI/videolayout/LocalVideo.js, modules/UI/videolayout/VideoLayout.js
Moves local video thumb initializations where they belong in the local video constructor. Fixes a problem when there is no video device, then audio levels and gsm bars are missing. We were doing this initializations every time a video device is changed.
=> Moves local video thumb initializations where they belong.

prosody-plugins/mod_auth_token.lua
/cc @paweldomas I apparently didn't stage everything earlier before I comitted; this version has proper encoding.
I went ahead and fixed a log message which was wrong as part of this PR too since it was small and doesn't make the review too much more complicated.
=> Use valid path for HTTP token fetches

css/videolayout_default.css
In this PR I fixed the problem with moving the last video preview down when user resizes window of jitsi-meet app. I changed displaying behavior of `videocontainer`s to `flexbox`. It allows us to render them along one row and resize ones automatically.
=> Fix problem with last video preview

modules/UI/UI.js, modules/UI/toolbars/BottomToolbar.js
The problem was in that when we hide filmstrip `VideoLayout` is not being resized. I extracted common handler (`UI.handleToggleFilmStrip`) for this behaviour and set it for hiding the filmstrip via shortcut and via clicking on the button on toolbar
__Little demo:__
=> Fix problem with resizing

css/_toolbars.scss
Rule "display: -moz-box;" was located after "display: flex;" and that caused left toolbar to be stretched by width.
=> Fix for left toolbar (FireFox)

modules/UI/side_pannels/chat/Chat.js
Receiving messages docks the toolbar to be able to see number of unread messages. We need to undock it when we read the messages. We skip undocking if we are not in video mode (on large), cause stuff like youtube video share is docking/undocking the toolbar.
=> Fixes hiding toolbar.

conference.js, modules/settings/Settings.js
Skips storing device ids in localstorage if the user hasn't selected a device to use, and keeps using system defaults. Removes calls to private library method for setting initial realDeviceIds, as this had been added to the library.
=> Device selection rework

lang/main.json, modules/UI/side_pannels/contactlist/ContactList.js
There is sometimes problems with cache and late loading of the translations, this commit avoids showing translation key in the contactlist title, by moving the parameter into the code.
=> Moves the number in the code, not as a translation parameter.

css/_base.scss, css/_variables.scss, css/_videolayout_default.scss, index.html
Reverts https://github.com/jitsi/jitsi-meet/commit/388f86816517b0f112c3f9a5fdf86a442d15afeb because this commit puts the toolbar under the ring overlay and fixes the issue with the tooltips by adding z-index:901.
=> fix(toolbar): Issue with toolbar is positioned under the ring overlay

modules/UI/ring_overlay/RingOverlay.js
The absolute path is not working for some cases. That's why we are changing it to relative.
=> fix(ringoverlay): Path of the ogg file

modules/UI/feedback/FeedbackWindow.js
Call the callback even when clicking outside the dialog, or escaping to close it.
=> Makes sure we always resolve(call the callback) in feedback dialog.

conference.js, modules/UI/shared_video/SharedVideo.js, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/VideoContainer.js, modules/UI/videolayout/VideoLayout.js
When ICE disconnects we blur the video image and show a message on top of it. This Rr fixes 2 problems with displaying it:
1. the filter was not applied if the event arrived while Etherpad or Youtube video was displayed
2. should not be shown on top of the Etherpad nor shared YouTube video
=> Fix notification about network issues not displayed when expected

conference.js, css/_videolayout_default.scss, index.html, lang/main.json, modules/UI/UI.js, modules/UI/shared_video/SharedVideo.js, modules/UI/videolayout/ConnectionIndicator.js, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/LocalVideo.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/SmallVideo.js, modules/UI/videolayout/VideoContainer.js, modules/UI/videolayout/VideoLayout.js
This PR implements the UI for https://github.com/jitsi/lib-jitsi-meet/pull/259 which adds the notifications about participant's media connection status changes(indicates problems with the connection between the peer and jvb).
When the user is having problem we will try to apply greyscale filter on top of the frozen video either on the "large video" or on the thumbnail, but only if such image is available. If not then the user's avatar will be displayed in greyscale. In addition to that there will be a message saying that "the user is having connectivity issues" displayed on the large video and a "disconnected GSM bars" icon will be shown on the thumbnail.
=> Adds participant connection status notifications

css/_videolayout_default.scss
=> Removed initial animation of the video thumbnail

conference.js, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/RemoteVideo.js, prosody-plugins/mod_token_verification.lua
Room names used inside prosody are all lower case, when verify with room name from token make sure we use the room name in lower case.
=> Prosody tokens case insensitive room name

modules/UI/UI.js, modules/UI/util/UIUtil.js
Provided changes:
1) Fixed issue when tooltip become visible permanently
2) Improved memory management - one instance of the plugin handles all the tooltips
3) Improved management of the tooltips - they are created and destroyed automatically for the nodes with "data-tooltip" and "content" attributes
=> Global handler for tooltips

.babelrc, .jshintignore, Makefile, package.json, webpack.config.babel.js
1. Since the library lib-jitsi-meet does not publish its binaries, it has
always been necessary to produce the binaries i.e. lib-jitsi-meet.js and
lib-jitsi-meet.js as part of the npm install step. Which means that any
modifications to the devDependencies of lib-jitsi-meet's package.json
always have to be reflected in jitsi-meet's package.json. Because
Webpack replaced Browserify in lib-jitsi-meet, Webpack has to become a
devDependency of jitsi-meet. Browserify is replaced by Webpack in https://github.com/jitsi/lib-jitsi-meet/pull/255.
2. Switches jitsi-meet from Browserify to Webpack.
=> Switch from Browserify to Webpack

modules/UI/util/UIUtil.js
Destroy is just hiding current tooltip, we also need to remove other attributes to stop showing the tooltip.
=> Remove tooltip update

modules/UI/UI.js
Currently, when hiding the filmstrip during a desktop sharing session, Meet resizes the desktop to fullscreen. This only works when hiding from the toolbar button though and not from the "F" shortcut.
The fix, makes it also work for the shortcut.
=> Fixes desktop expansion on filmstirp shortcut hide.

conference.js, modules/UI/avatar/Avatar.js
Simplifies the logic.
The Feedback dialog is now displayed immediately after pressing hangup and doesn’t depend on room.leave. Now we are executing room.leave in parallel and when both operations are done we proceed with disconnect and redirecting.
=> Refactor hangup

modules/UI/invite/Invite.js
We're already checking if the invite dialog view isn't created when the person clicks on invite and we need to open the dialog, so this initialisation at the beginning of the call is not correct. In addition this dialog was initialised so early in the call that often we wouldn't get translations by this point and will end up with empty title. The translation problem is a bigger one though and will be addressed in a separate fix.
=> Initialise the invite dialog on user action

css/_chat.scss
Changes the margin from % to px. The margin value was % of the side panel with but it is always 200px. So the margin in px should be always 8-9 px.
=> fix(chat): Issue with position of chat messages

modules/UI/util/UIUtil.js
Fixes issue of method 'setTooltip' in modules/UI/util/UIUtil.js: Excluded 'Uncaught TypeError':
```
UIUtil.js:134 Uncaught TypeError: Cannot read property 'setAttribute' of null
```
=> Fixes issue of method 'setTooltip'

css/_videolayout_default.scss
For small window sizes and many video thumbnails the message may appear on top of the thumbnails.
=> Reduce the z index of the connection problems message

404.html, css/404.scss, css/main.scss
404.html error page added
User can go to meeting with "meeting-name" name by mistake. In this case we are showing nginx 404 error. I think we should rewrite this page and show error page with button for redirection on home page
Logic:
jitsi.net/                                  --> WelcomePage
jitsi.net/lettersOrNumbers     --> VideoPage
jitsi.net/letters-test                --> 404 ErrorPage
But we should setup our server after merge this PR.
=> error layout added

modules/UI/videolayout/SmallVideo.js
The tooltip became frozen because there were multiple calls to Translation API.
Before:
After:
=> Prevent tooltips from frozen state

css/input-control/_input-control.scss
Fixed issue with shifted buttons in input control containers:
=> Button shifted

css/_animations.scss, css/_toolbars.scss, modules/UI/UI.js, modules/UI/toolbars/Toolbar.js, modules/util/helpers.js
Changed the animation of the main toolbar from Slide in/out to fade in/out. Also added debounce method in helpers for optimization of mousemove event handler in `UI.js`. Show toolbar handler was being invoked for every change of mouse coordinate - updated to invocation no more than once in __100ms__. Also used delay of __300ms__ for fade in/out animation because of strange blinking bug in webkit when animating opacity.
=> Change main toolbar animation; optimize mousemove handler

css/_videolayout_default.scss
Previously the z-index was introduced in order to have the avatar
visible on top of the black video element, but now we're always hiding
the video element when the avatar is displayed, so it's no longer
required.
=> Do not display avatar on top of the connection problem messages

interface_config.js, modules/translation/translation.js
Fixed the problem with automatic language detection. Added new option to interface config `LANG_DETECTION`. When it's enabled then we allow 18n to detect the language of user agent otherwise we're setting default language (which is English).
=> Add detect translation freeze in interface config

index.html
This PR adds an error listener which will replace the document body with an error message if any of the files required for the app to be displayed correctly fails to load.
=> Prevent from displaying broken page

modules/UI/videolayout/LargeVideoManager.js
The "data-i18n-options" attribute value is stored in jQuery cache and
at the time when i18-next tries to access it to do the translation
it gets the old value from the cache and the message is not updated
correctly. Passing the "msgOptions" explicitly to "translateElement"
fixes the problem by avoiding jQuery cache.
=> fix(LargeVideoManager): frozen displayname in a msg

conference.js, modules/UI/reload_overlay/PageReloadOverlay.js
The event was not logged in case when the page reload overlay was shown on XMPP connection dropped event:
https://github.com/jitsi/jitsi-meet/blob/master/conference.js#L564
=> Log the page reload from one place

conference.js, css/_chat.scss
The local and remote display names are limited to 50 chars.  Any additional chars are cut when the remote display name is received or the local is entered. 
Displaying long nicknames in the chat panel is improved.
=> Limit long display names

modules/UI/shared_video/SharedVideo.js
We used to stop player updates on self presence received, so between stop and self presence we can send a playing update which will provoke adding the video again to other participants.
=> Stops player update before sending stopping of shared video.

modules/UI/toolbars/Toolbar.js, modules/UI/videolayout/FilmStrip.js
In this PR is moved initialization of toggle filmstrip shortcut from extended toolbar to filmstrip module. Also, delete corresponding button from extended toolbar in order to remove duplications.
=> Moved keyboard initialization to filmstrip toolbar

css/_mixins.scss, css/_videolayout_default.scss
In this PR I fixed the problem of resizing small video avatars. Now the maximum size for them is __60px__. But for small sized they have __50%__ size of their containers.
=> Fixed problem with resizing thumb avatars

package.json
because older versions don't work with our .jslintrc file
=> chore: Only uses jslint 3+

css/_base.scss, modules/UI/UI.js, modules/UI/feedback/Feedback.js, modules/UI/recording/Recording.js, modules/UI/side_pannels/chat/Chat.js, modules/UI/toolbars/Toolbar.js, modules/UI/util/UIUtil.js, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/SmallVideo.js, modules/UI/videolayout/VideoLayout.js
Do not change element styles directly, use css classes instead. It helps to:
* keep JS code clean;
* override styles;
* avoid long css selectors;
* increase performance of the application.
=> Fix clean js from styles 1

modules/UI/videolayout/FilmStrip.js, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/VideoContainer.js
In desktop streaming mode the desktop screen show area wasn't calculated correctly and was appearing behind the video thumbnails. This PR fixes that problem.
=> fix: desktop streming screen size

conference.js
It looks weird when the page reload overlay appears and the conference
continues in the background (the connection to the JVB remains active).
The library will not recover and the conference can not continue without
the signalling, so the room should be left and media stopped.
=> Stop the media when XMPP connection is dropped

modules/UI/side_pannels/chat/Chat.js
textarea shouldn't be focused during animation
After fix:
=> Chat animation fix

modules/UI/videolayout/FilmStrip.js
The desktop sharing was resized properly if you press the shortcut for hiding the filmstrip but not when you press the button.
=> Fixes issue with not resizing properly if SS is on and the filmstrip is hidden

modules/UI/UI.js, modules/UI/util/MessageHandler.js
Prevents the close button to take focus while user clicks tab in the page, which will privent the toast to be closed.
=> Makes close button non-focusable.

modules/UI/videolayout/VideoLayout.js
If we:
- pin a remote and click it, unpin is signalled.
- pin a remote and the click another remote, the new one is pinned and signalled.
- pin a remote and then click local. UI pins local, but unpinning remote is not signaled, fix addressed with this commit.
- pin/unpin local, nothing is signalled.
=> Sending unpin after clicking local video and unpinning remote.

.jshintignore
If build directory is not ignored, then one will not be able to commit anything while using "webpack --watch" incremental builds.
=> Add 'build' dir to jshintignore

app.js, react/features/welcome/components/WelcomePage.web.js
The React-based rewrite looks whether there's a room name (in the
window's location) in order to choose between WelcomePage and
Conference. But app.js expects Conference to be rendered before it
builds a room name if WelcomePage is disabled and there's no room name.
A quick and dirty workaround is to render Conference within WelcomePage
so that the rendered result closely resembles index.html before the
React-based rewrite.
=> Fix disabled Welcome page broken with the introduction of React

conference.js, logging_config.js, modules/UI/UI.js, modules/UI/reload_overlay/PageReloadOverlay.js, package.json
Distinguishes between network and infrastructure (or other) failures that can trigger the page reload overlay.
Requires https://github.com/jitsi/lib-jitsi-meet/pull/324
=> Add 'isNetworkFailure' argument to PageReloadOverlay

app.js, package.json
Since https://github.com/jitsi/lib-jitsi-meet/pull/333 we don’t need strophe-caps plugin anymore.
=> Remove strophe-caps dependancy

react/features/welcome/components/WelcomePage.native.js
This prevents the keyboard from showing up right when the app opens.
=> [RN] Disable autofocus on the welcome screen

css/_variables.scss, package.json, react/features/app/components/AbstractApp.js, react/features/app/components/App.native.js, react/features/app/components/App.web.js, react/features/app/functions.native.js, react/features/base/conference/actions.js, react/features/base/conference/reducer.js, react/features/base/connection/actions.web.js, react/features/base/lib-jitsi-meet/native/RTCPeerConnection.js, react/features/base/media/components/native/Video.js, react/features/base/react/Platform.native.js, react/features/base/react/Platform.web.js, react/features/base/react/index.js, react/index.web.js
A bug was discovered in d17cc9f which would raise a failure to push
into the browser's history if a base href was defined. Fix the failure
by removing react-router. Anyway, the usage of react-router was
incorrect because the app must hit the server infrastructure when it
enters a room because the server will choose the very app version then.
=> Fix d17cc9fa

react/features/base/media/actionTypes.js, react/features/base/media/actions.js, react/features/base/media/middleware.js, react/features/base/media/reducer.js, react/features/base/tracks/middleware.js, react/features/largeVideo/actionTypes.js, react/features/largeVideo/actions.js, react/features/largeVideo/reducer.js
Redux actions which represent "commands" should be imperative, and those
representing events should use the past tense.
=> Name Redux actions consistently

package.json
Starting version 4.x clean-css is split into two packages and we should depend on clean-css-cli for versions 4 and above. Tested it and we have currently some problem with it like fonts and images got referenced under css folder. So sticking version to 3.x for now.
=> Stick to clean-css version 3.x.

ConferenceEvents.js, app.js, conference.js, css/_filmstrip.scss, css/_popup_menu.scss, lang/main.json, modules/API/API.js, modules/UI/UI.js, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/VideoLayout.js, modules/keyboardshortcut/keyboardshortcut.js, modules/keycode/keycode.js, modules/remotecontrol/Controller.js, modules/remotecontrol/Receiver.js, modules/remotecontrol/RemoteControl.js, modules/remotecontrol/RemoteControlParticipant.js, modules/tokendata/TokenData.js, react/features/app/functions.web.js, service/UI/UIEvents.js, service/remotecontrol/Constants.js
The PR is still WIP. Currently implemented:
- capturing keyboard and mouse events on the controller side
- sending captured events to the receiver side
- listening for controller events on the receiver side and sending them trough the iframe API to external application that will execute them on the receiver side.
- Announce remotecontrol support from the receiver side to all participants
- Implements request for remote control permissions.
Depending on:
https://github.com/jitsi/lib-jitsi-meet/pull/341
=> Implement remote control support

config.js, doc/manual-install.md
It makes for a bad first-time experience for users, since the desktop sharing
button will be visible, but it will never work.
Also get rid of the now deprecated `desktopSharingChromeMethod` option.
=> cleanup: Remove default Chrome extension ID

react/features/app/components/AbstractApp.js, react/features/app/components/App.web.js, react/index.native.js, react/index.web.js
The files react/index.native.js and react/index.web.js ended up having
very similar source code related to initializing the Redux store. Remove
the duplication.
Additionally, I always wanted the App React Component to be consumed
without the need to provide a Redux store to it.
=> Remove duplication

react/features/base/connection/reducer.js, react/features/base/lib-jitsi-meet/reducer.js, react/features/base/util/interceptComponent.js, react/features/film-strip/components/FilmStrip.js, react/features/film-strip/components/Thumbnail.js, react/features/toolbar/components/AbstractToolbar.js, react/features/toolbar/components/Toolbar.native.js, react/features/unsupported-browser/actionTypes.js, react/features/unsupported-browser/actions.js, react/features/unsupported-browser/components/UnsupportedMobileBrowser.js, react/features/unsupported-browser/reducer.js, react/features/welcome/components/AbstractWelcomePage.js
The desired behavior of the button 'Start a conference' / 'Join the
conversation' is to launch the mobile app if installed; otherwise, do
nothing i.e. continue to display UnsupportedMobileBrowser.
Anyway, we may change our minds about allowing the user to continue in a
supported mobile browser so preserve the source code that enables that
but give it more appropriate naming.
=> Remove obsolete UnsupportedMobileBrowser functionality

prosody-plugins/mod_muc_allowners.lua, prosody-plugins/muc_owner_allow_kick.patch
Added a prosody plugin for making all users into muc owners in prosody
Included a patch to prosody-trunk which allows owners to kick each other
Missing here is instructions on how best to use the plugin.  It is a module that should be placed into the prosody modules directory (/usr/lib/prosody/modules) and then needs to be enabled through prosody.conf inside the muc component modules_enabled command.
=> prosody plugin to make all users owners/moderators

package.json
0.7.2 causes a ReferenceError: jQuery is not defined in autosize.
=> Stick to expose-loader 0.7.1

android/app/build.gradle, android/app/src/main/java/org/jitsi/meet/MainApplication.java, android/settings.gradle, ios/jitsi-meet-react.xcodeproj/project.pbxproj, package.json, react/features/base/lib-jitsi-meet/native/polyfills-browser.js
Turns out React Native's timers (setTimeout / setInterval) don't run while the
app is in the background: https://github.com/facebook/react-native/issues/167
This patch replaces the global timer functions with those from the
react-native-background-timer package, which work in the background.
These timers won't magically make an application work in the background, but
they will run if an application already happens to run in the background. That's
our case while in a conference, so these timers will run, allowing XMPP pings to
be sent and the conference to stay up as long as the user desires.
=> [RN] Fix running timers in the background

config.js
The feature has been replaced so the option no longer applies.
=> cleanup: remove adaptive las N config option

config.js
It's time we use 720p by default so people see each other in glorious HD.
=> doc: document resolution config option and set it to 720 by default

react/features/app/actions.js, react/features/app/components/AbstractApp.js
The mobile app remembers the domain which hosted the last conference. If
the user specified a full URL first and specified a room name only the
second time, it was not obvious that the second conference would be
hosted on the domain of the first conference.
=> [RN] Use a default host when only a room name is specified

react/features/app/components/AbstractApp.js, react/features/base/conference/middleware.js
On RN we don't use the global APP object, so don't save the store there unless
it's defined, which is the case in the current web version. Also, check for
undefined explicitly, since a "if (!APP)" check will throw a ReferenceError.
=> [RN] Fix use of undefined APP 

react/features/toolbar/components/Toolbar.native.js
It doesn't work properly and gives a very bad user experience. Disble it until
all underlying issues in react-native-webrtc are ironed out.
=> [RN] Temporarily disable camera toggling button

react/features/full-screen/middleware.js
Fixes an issue where immersive mode would be enabled when coming back from the
background on the welcome screen.
Re-fixes c57e713, which was not correct.
=> [RN] Fix Android immersive mode when coming from the background

react/features/base/react/components/Container.native.js
This solves the issue of view clipping on Android, plus it seems to be the RN
convention unless the views are very large and memory hungry.
Includes https://github.com/jitsi/jitsi-meet/pull/1332 because it was needed for testing. I'll rebase when it lands.
=> [RN] Avoid rendering Container if not visible

react/features/welcome/components/WelcomePage.web.js
When rendering using a for loop each child whould have a key prop.
=> Fix warning about missing key prop

config.js
Starting with firefox 52, no extension is required for screensharing.
=> config: Don't require an extension for firefox >=52.

index.html
Adds a placeholder which allows to write a plugin for executing some code after the "load error handler" is triggered. A function named "postLoadErrorHandler" should be defined in one of
the "#include virtual" files.
=> Post load error handler

lang/main.json
Firefox (at least) renders it verbatim.
=> lang: don't use "&nbsp;" for the default policy text

debian/jitsi-meet-web-config.postinst, debian/jitsi-meet-web-config.templates, debian/jitsi-meet-web.install, debian/po/templates.pot, resources/install-letsencrypt-cert.sh
The script looks for nginx, apache2 or jetty configuration and edits the first one found. Nginx and apache2 will be reloaded, while jvb will be stopped, configured and started again.
=> Adds a script which install certificates from let's encrypt.

Makefile
- we now use pinned dependencies, so there is no need to run npm update
- AFAICT the node-sass workaround is no longer needed
=> build: remove no longer needed Makefile rule

modules/UI/side_pannels/settings/SettingsMenu.js
Strings are not translated when opening the settings side panel. It was that we were creating settings panel html after i18n library had loaded and had translated the rest of the html.
The element selecting the current language was also not translated, which end up with no selection in the UI for the current language.
=> Fixes settings panel translation.

css/_base.scss, css/_filmstrip.scss, css/_jitsi_popover.scss, css/_jquery.contextMenu.scss, css/_keyboard-shortcuts.scss, css/_notice.scss, css/_popover.scss, css/_side_toolbar_container.scss, css/_toolbars.scss, css/_variables.scss, css/_videolayout_default.scss, css/_welcome_page.scss
All z-indexes found in css files have been moved into css
variables. If the z-index is used only once, the variable
name will be the same as the selector it is used in. If
the z-index is used multiple times, then the plain name
of $zindex# was used. This allowed a more confident
moving down of the toolbar so that the new modal dialog,
with z-index 500, could display on top of it.
=> Catalog all z-indexes and move toolbar down

.flowconfig, package.json
@atlaskit components will all require styled-components in the
future. Including it now will remove the unmet peer
dependency warning during npm install and prevent future build
breakages that might occur from using a new @atlaskit component
that requires it.
=> deps: include styled-components package for @atlaskit components

app.js, package.json, webpack.config.js
It's no longer needed for building since Node >= 6 already has the minimum
required ES6 syntax. In addition, drop it from app.js since we use Webpack with
the Babel loader to transpile ES5 to ES6.
=> build: drop dependency on babel-pollyfill

conference.js, modules/UI/UI.js, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/VideoLayout.js
Checks for interrupted state of peer connection and shows appropriate messages. In case of inactive or restoring state a message is show to user that video was stopped on purpose. Removes some unused parameters from the event handlers about peer connection status change.
=> Uses new peer connection statuses to check and show different user msgs.

lang/main.json, modules/UI/videolayout/ConnectionIndicator.js
Moves the P2P indication next to the remote IP address and rewords it from "(direct)" to "(p2p)".
=> fix: P2P address indication

package.json, webpack.config.js
babel does not modify existing builtins by default. That means
some newer methods, such as Array.prototype.includes, may not
be available unless babel-polyfill is used.
=> deps: re-add babel-polyfill as a dependency

react/features/base/tracks/middleware.js
The functionality to use the react-native-webrtc custom API for fast switching
cameras was moved to JitsiLocalTrack in lib-jitsi-meet. Use that.
Ref: https://github.com/jitsi/lib-jitsi-meet/pull/444
=> [RN] Use _switchCameras provided by lib-jitsi-meet

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/jitsi/meet/MainApplication.java, android/app/src/main/java/org/jitsi/meet/proximity/ProximityModule.java, android/app/src/main/java/org/jitsi/meet/proximity/ProximityPackage.java, ios/app/Proximity.m, ios/jitsi-meet-react.xcodeproj/project.pbxproj, react/features/app/components/App.native.js, react/features/mobile/proximity/index.js, react/features/mobile/proximity/middleware.js
The behavior can be triggered with the toggleAudioOnly action, which is
currently fired with a button.
The following aspects of the conference will change when in audio only mode:
- local video is muted
- last N is set to 0 (effectively muting remote video)
- full-screen mode is exited
- audio mode is set to "audio chat" (default output is the earpiece)
- the wake lock is disengaged
One aspect not handled in this patch is disabling the video mute button while in
audio only mode. The user should not be able to turn back video on in that case.
=> [RN] Audio-only mode

react/features/base/media/components/native/Video.js, react/features/base/media/components/native/styles.js
It's now natively supported:
https://github.com/oney/react-native-webrtc/pull/244
=> [RN] Remove workaround for video mirroring on iOS

modules/UI/side_pannels/profile/Profile.js
Strings are not translated when opening the profile side panel on FF. It was that we were creating profile panel html after i18n library had loaded and had translated the rest of the html.
=> Fixes profile panel translation.

css/_filmstrip.scss, css/_toastr.scss, css/_toolbars.scss, css/_variables.scss, modules/UI/UI.js, modules/UI/side_pannels/SideContainerToggler.js, modules/UI/videolayout/FilmStrip.js, react/features/toolbox/actions.web.js, react/features/toolbox/components/PrimaryToolbar.web.js, react/features/toolbox/components/SecondaryToolbar.web.js, react/features/toolbox/components/Toolbar.web.js, react/features/toolbox/components/ToolbarButton.web.js, react/features/toolbox/components/Toolbox.web.js, react/features/toolbox/defaultToolbarButtons.js, react/features/toolbox/functions.js, react/features/toolbox/reducer.js
Some fixes and additions have been needed in order to make the toolbox and inner toolbars filmstrip-only mode compatible. This PR is about providing a filmstrip-only mode of the toolbar. Currently only 3 buttons support filmstrip only and the idea is in the future to make this configurable and flexible and remove the property from the defaultToolbarButtons initialisation list.
=> Filmstrip-only toolbar

react/features/base/participants/components/Avatar.native.js, react/features/base/participants/components/styles.js, react/features/filmstrip/components/Thumbnail.js, react/features/filmstrip/components/styles.js
I couldn't test on iOS on Friday, so the previous attempt was pretty lame. This time around it's working on both platforms. I tweaked the style a bit more and moved it to the right place too.
Android requires a workaround (this has started to become a very annoying pattern) because images of size < 80 don't work ok. Read the commit description.
=> [RN] Display avatars as circles in thumbnails

react/features/toolbox/components/Toolbox.native.js, react/features/toolbox/components/styles.js
@yanas Can you PTAL at the image?
=> [RN] Use a handset icon for audio-only mode button

conference.js, modules/API/API.js
If toggle audio or video is executed too early and the local
tracks don't exist we fail to execute the operation. Now we store
the mute state and we are executing it after the tracks are
created
=> fix(iframe_api): toggle audio/video race condition

css/_variables.scss, css/modals/_dialog.scss, react/features/base/dialog/components/Dialog.web.js
Atlaskit at times will have localized styling for font-size and
sometimes will not. The button component will inherit its
font-size whereas selectors have localized font-size of 14px. For
consistency, the cancel/submit buttons on the atlaskit modals
will also have 14px. The atlaskit story book examples also use
buttons with 14px font-size.
=> fix: set button font-size for modals

Makefile, connection_optimization/.eslintrc.js, connection_optimization/do_external_connect.js, index.html, webpack.config.js
Illya Daynatovich/@BeatC processed do_external_connect.js through webpack in https://github.com/jitsi/jitsi-meet/pull/1472 but I want it out of there because it's a standalone, logical piece that makes sense and can be accomplished without any connection to supporting JWT support on mobile.
=> Process do_external_connect.js through webpack

logging_config.js
Reduces the log level for the CallStats module to 'info', because recent changes are adding a lot of debug logs.
=> CallStats log level 'info'

conference.js, modules/UI/UI.js, modules/UI/side_pannels/settings/SettingsMenu.js, react/features/device-selection/actions.js, react/features/device-selection/index.js
Move logic to open device selection outside of SettingsMenu so it can be called independently by either SettingsMenu or by the settings button itself if no other settings but devices will be displayed.
Note: this change is done on top of device-selection implementation.
=> fix: open device selection if it is the only available setting

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example, doc/example-config-files/prosody.cfg.lua.example, doc/manual-install.md
Jitsi Meet doesn't seem to work with `c2s_require_encryption` set to `true`. `c2s_require_encryption` is `false` by default. However it is possible that in some Prosody configurations it is overriden by a global config to be `true`. In that case Jitsi Meet might not work out-of-box. So let's set it explicitly to be sure it is correct.
=> Explicitly set c2s_require_encryption to false

lang/main.json, react/features/device-selection/components/VideoInputPreview.js
Device Selection re-uses the local video track for its preview.
When displaying Device Selection while video muted, the text
"muted" displays within the video preview, but some translations
may mistake this to mean audio muted. The text has been changed
to be explicit about video mute. This is a temporary solution;
at some point Device Selection should not re-use the local track
except for IE, the one browser that cannot get multiple tracks
from the same video input.
=> fix: change string displayed when previewing a muted video input

ios/app/Info.plist
It will render as white in dark backgrounds. This is what FaceTime does and what
we already do on Android. The problem with the default look (black text) is
noticeable in audio only mode, since the background is dark.
Sample:
=> [RN] Set iOS status bar style to light

css/modals/device-selection/_device-selection.scss
On certain modal dimensions, the black background of the video
preview could peek through, making it look like the video has a
black line. The change is to remove the black background from
showing by default and having it only display when the video is
muted. Also, the video preview dimension stylings have been
changed to facilitiate smoother size adjusting with modal size
changes.
=> fix(device-selection): show black background only when video muted

css/_base.scss
Safari will prevent proper input behavior when user-select none
is applied. It prevents such actions as putting in a room lock
password or setting a room lock password. Other browsers allow
selecting on inputs while user-select is none.
=> fix: do not apply user-select none to inputs

css/modals/device-selection/_device-selection.scss, package.json, react/features/device-selection/components/DeviceSelector.js
AtlasKit Dropdown was recently updated to support fitting the
width of its container. However, AtlasKit Button, the trigger
element currently used for the dropdowns, does not fit the width
of AtlasKit Dropdown and stll has text overflowing out of its
button when there is an iconBefore prop passed in. Instead of
using AtlasKit Button, use a div and mimic the button look. This
allows the "button" to fit the container width and can display
ellipsized text within itself.
=> fix(device-selection): convert trigger element to a div

react/features/base/react/components/Watermarks.web.js
Both watermarks can be used to link to an external site, by providing an URL for each.
However, this URL is optional. When it is not set, the watermark should not be 'clickable'.
This prevents users from reloading the room by clicking on the logo (caused by an empty
html ancher element).
=> Watermarks should not be clickable when they have no links

css/modals/device-selection/_device-selection.scss, lang/main.json, react/features/device-selection/components/DeviceSelector.js
AtlasKit DropdownMenu cannot be disabled, unlike Single Select.
The result is the isDisabled prop was not being honored. The
workaround is returning only the trigger element for the dropdown
and styling it to look like the dropdown is disabled. The text
for disabled device selection was changed along the way to fit
into the trigger.
=> fix(device-selection): do not create a dropdown menu if disabled

css/modals/invite/_invite.scss, lang/main.json, react/features/invite/actionTypes.js, react/features/invite/actions.js, react/features/invite/components/DialInNumbersForm.js, react/features/invite/components/InviteDialog.js, react/features/invite/index.js, react/features/invite/reducer.js
Create a new React Component for displaying a list of dial-in
numbers. The Component will fetch the numbers from a new
numberRetreviewUrl key/value set in config. If not present in
config, the Component will not be displayed.
=> feat(invite): include dial-in numbers in the invite modal

react/features/toolbox/actions.native.js, react/features/toolbox/actions.web.js, react/features/toolbox/functions.native.js, react/features/toolbox/functions.web.js
toolbox/functions has functions that are specific only to web,
specifically defaultToolbarButtons. This has caused the native
build to attempt to bring in a web dependency which leads to a
build error. The fix for now is splitting web functions from
native functions to resolve the build error.
=> fix(toolbox): move default toolbox buttons logic to web only

css/_inlay.scss
In the filmstrip inlay, the avatar container holds the avatar
image. The image is set to 100% height, so it displays entirely
in the container. However, this does not adjust the horizontal
space created by the image in firefox, leaving whitespace to the
right of the avatar. The fix is to set the container height to
100% so that all its content will fit inside, automatically
adjusting the space created by the image width.
=> fix(filmstrip): Set avatar container height within inlay

resources/prosody-plugins/mod_auth_token.lua, resources/prosody-plugins/mod_muc_size.lua, resources/prosody-plugins/mod_token_verification.lua, resources/prosody-plugins/token/util.lib.lua
Opening a second PR about jwt changes.
Moves all the jwt token verification logic inside token/util so it can be reused.
Adds domain name verification and multidomain support. 
Updates room size API to work with multiple domains.
=> jwt updates

conference.js, react/features/toolbox/actions.web.js, resources/prosody-plugins/mod_filter_iq_rayo.lua
Adds a prosody module to filter rayo incoming iqs if user is not authenticated using jwt. Hides the button in the UI if roles evaluation is enabled in config and the user is guest.
Depends on https://github.com/jitsi/jitsi-meet/pull/1548
=> Filter rayo module

config.js
Starting with Firefox 51 the extension is no longer mandatory, so make sure the
feature is not desabled by default.
=> fix(screen-sharing) Enable it by default on Firefox

debian/jitsi-meet-tokens.postinst, resources/prosody-plugins/token/util.lib.lua
Room name verification crashes when we have a configured anonymousdomain as it doesn't have any token extracted data. It is safe to skip this check as room creation is verified by jicofo and we have the option restrict_room_creation to admin users.
Removes obsolete print when updating jitsi-meet-tokens.
=> Fixes crashing jwt util for anonymous domains.

config.js, modules/UI/UI.js, modules/UI/videolayout/ConnectionIndicator.js, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/VideoContainer.js, modules/UI/videolayout/VideoLayout.js, react/features/conference/components/Conference.web.js
In its current implementation, the VideoStatusLabel shows HD based on peer
connection stats. These stats will be available on temasys browsers soon but
will remain unavailable on Firefox, which does not collect height/width stats.
To support VideoStatusLabel showing cross-browser, move the high-definition
detection out of stat sniffing and instead check the video element itself using
an interval in LargeVideoManager. (An interval was used because the temasys
video object does not support the onresize event.) Also, add a cleanup path from
conference.web to LargeVideoManager to remove the interval.
This change relies on https://github.com/jitsi/lib-jitsi-meet/pull/486.
=> fix(video-label): Display based on video dimensions in LargeVideoManager

css/modals/invite/_invite.scss, lang/main.json, react/features/invite/actionTypes.js, react/features/invite/actions.js, react/features/invite/components/DialInNumbersForm.js, react/features/invite/components/InviteDialog.js, react/features/invite/index.js, react/features/invite/middleware.js, react/features/invite/reducer.js
DialInNumbersForm has been modified to display a conference id to be used for
dialing into the conference. The changes include:
- Requesting the conference id and adding the conference id to the redux store
- Displaying the conference id in DialInNumbersForm
- Modifying the copy behavior to support copying the new message to clipboard
- DialInNumbersForm does not display until all ajax requests have completed
successfully. This eliminates the need for the REQUESTING state.
=> feat(invite): Add conference id to dial-in numbers display

css/_videolayout_default.scss
- Change z-index so any tooltips that display over the label,
particularly in vertical filmstrip mode, actually hide the label.
- Change the cursor to be a pointer so the label looks clickable.
- Remove unused audio-only-label styling.
=> fix(video-label): modify z-index and cursor

conference.js, css/_vertical_filmstrip_overrides.scss, modules/UI/recording/Recording.js, modules/UI/videolayout/VideoLayout.js, react/features/filmstrip/actionTypes.js, react/features/filmstrip/actions.js, react/features/filmstrip/middleware.js, react/features/filmstrip/reducer.js, react/features/video-status-label/components/VideoStatusLabel.js
Instead of one timing for sliding the video status label left and right,
have different timings depending on the filmstrip state. To facilitate
triggering the different animations, add more classes to the labels
that need to move that specify the filmstrip state.
- Faster transition if focusing on self-view with videos present so
the label does not overlap videos transitioning from 0 opacity.
- Transition delay when de-focusing on self-view with videos present
so videos have time to go away before the label moves over them.
- Maintain no movement if there are no videos, regardless of
filmstrip toggle state.
- Different delays for when the filmstrip is being toggled visible
and hidden if there are remote videos visible.
=> fix(vertical-filmstrip): different label animations for filmstrip states

modules/UI/videolayout/VideoLayout.js
Currently no video switch happens if a user joins audio and video
muted. For example, User A is in a call and User B joins with no
mic and camera. User A will keep seeing local video on large video.
The fix is to set a timeout, of a somewhat arbitrary 3 seconds, to
show User B on large video.
Note: this issue occurs outside of 1-on-1 mode but becomes more
apparent in 1-on-1 mode.
=> fix(large-video): trigger update after timeout for 1-on-1 calls

modules/UI/side_pannels/chat/Chat.js
Fixes a TypeError: Cannot set property 'innerHTML' of undefined
at o (Chat.js:61)
at Object.updateChatConversation (Chat.js:271)
that is thrown when joining a conference with messages already set to the chat. The error used to remove a strophe handler and chat was not working at all for those seeing the error.
=> Fixes chat when on join we receive messages.

react/features/app/actionTypes.js, react/features/base/conference/actionTypes.js, react/features/base/config/actionTypes.js, react/features/base/connection/actionTypes.js, react/features/base/devices/actionTypes.js, react/features/base/dialog/actionTypes.js, react/features/base/lib-jitsi-meet/actionTypes.js, react/features/base/logging/actionTypes.js, react/features/base/media/actionTypes.js, react/features/base/participants/actionTypes.js, react/features/base/react/Symbol.js, react/features/base/react/index.js, react/features/base/tracks/actionTypes.js, react/features/desktop-picker/actionTypes.js, react/features/dial-out/actionTypes.js, react/features/filmstrip/actionTypes.js, react/features/invite/actionTypes.js, react/features/jwt/actionTypes.js, react/features/large-video/actionTypes.js, react/features/mobile/background/actionTypes.js, react/features/overlay/actionTypes.js, react/features/share-room/actionTypes.js, react/features/toolbox/actionTypes.js, react/features/unsupported-browser/actionTypes.js, react/index.native.js
We might use it in other dependencies, polyfill it globally so we don't need to
import it explicitly.
It's necessary to do this very early on, so do it in index.native.js, which is
as early as it gets.
=> [RN] Polyfill Symbol

app.js, modules/API/API.js, modules/keyboardshortcut/keyboardshortcut.js, react/features/app/actions.js, react/features/app/components/AbstractApp.js, react/features/app/components/App.web.js, react/features/app/functions.web.js, react/features/app/index.js, react/features/base/config/parseURLParams.js, react/features/base/i18n/index.js, react/features/base/i18n/middleware.js, react/features/base/logging/middleware.js, react/features/jwt/functions.js, react/features/jwt/index.js, react/features/jwt/middleware.js
The counterpart of the external API in the Jitsi Meet Web app uses the
search URL param jwt to heuristically detect that the Web app is very
likely embedded (as an iframe) and, consequently, needs to forcefully
enable itself. It was looking at whether there was a JSON Web Token
(JWT) but that logic got broken when the JWT support was rewritten
because the check started happening before the search URL param jwt was
parsed.
=> Fix the initialization of the (external) API

modules/UI/videolayout/VideoLayout.js
This handles the case where User A and B are in a call and B has no audio or video. Then B leaves. User A would see User B left on large video. Instead, User A should see self view on large.
This change is branched from https://github.com/jitsi/jitsi-meet/pull/1599, which needs to be merged in first.
=> fix(large-video): ensure switch to local video when all others leave 

modules/UI/videolayout/VideoContainer.js
When using onplay in firefox, the event fires before data is flowing,
which can cause videoHeight and videoWidth to be 0 during resizing.
By using onplaying, there is some assurance data is being received,
so videoHeight and videoWidth should be set.
=> fix(video): use onplaying to ensure video height and width are set

conference.js
Both conference.changeLocalEmail and conference.changeLocalAvatarUrl
are exposed in the external api. It is possible for users to then
pass in non-string values. To make it more visibly obvious of the
error and to prevent script errors, convert whatever is passed in
into a string.
=> fix(conference): ensure avatar url and email changes act on strings

css/_variables.scss
Currently, the JitsiPopover z-index will cause it to display below
any toast notifications so this changes modifies the z-index
values so JitsiPopover is higher than the notification toasts.
=> fix(popover): z-index should be greater than toasts

css/_filmstrip.scss, css/_vertical_filmstrip_overrides.scss
- For horizontal mode, remove extra spacing created by borders
around local video and remote videos.
- For vertical mode, ensure remote videos grow only to fill the
parent height (Firefox issue)
=> fix(filmstrip): adjust filmstrip remote videos positioning

modules/UI/videolayout/RemoteVideo.js
In RemoteVideo, creation of the RemoteVideoMenu (popover) is
skipped if in filmstrip only mode. However, updateRemoteVideoMenu
is called by other components, and that tries to access popover
and will error.
Add a defensive check for now as filmstrip is being rewritten
for react.
=> fix(remote-video): update remote video menu if it exists

modules/UI/util/JitsiPopover.js, modules/UI/videolayout/RemoteVideo.js, react/features/remote-video-menu/components/KickButton.js, react/features/remote-video-menu/components/MuteButton.js, react/features/remote-video-menu/components/RemoteControlButton.js, react/features/remote-video-menu/components/RemoteVideoMenu.js, react/features/remote-video-menu/components/RemoteVideoMenuButton.js, react/features/remote-video-menu/components/VolumeSlider.js, react/features/remote-video-menu/components/index.js, react/features/remote-video-menu/index.js
- Create new React Components for RemoteVideoMenu
- Remove existing menu creation from RemoteVideo
- Refactor RemoteVideo so all function binding happens once in
the constructor, removing the need to rebind when updating
the RemoteVideoMenu
- Allow popover to append and remove React Components from itself
- Refactor popover so post popover creation calls are broken out and
remove behavior is all done in one function.
=> feat(remote-video): convert remote video menu to react

modules/UI/videolayout/Filmstrip.js
Vertical filmstrip has a scrollbar to scroll through all remote
video thumbnails instead of scaling width and height to force all
thumbnails to display on screen. The scaling is not necessary in
vertical filmstrip mode and instead causes some UI spacing issues
with the video status label.
Also addressed a typo in "removeVideoWidth" near the area of the
changed logic.
=> fix(vertical-filmstrip): prevent scaling based on video count

react/features/device-selection/components/AudioInputPreview.js
TraceablePeerConnection argument is lib-jitsi-meet internal and the app
does not need to care.
=> fix(AudioInputPreview): do not care about TPC

ios/app/app.xcodeproj/project.pbxproj, ios/scripts/fixup-frameworks.sh, ios/sdk/sdk.xcodeproj/project.pbxproj
Before, Jitsi Meet (the app) would only link with JitsiMeet.framework, which in
turn embedded WebRTC.framework. While possible, Apple doesn't allow apps with
nested frameworks to be submitted to the store. Now the app will link with
WebRTC.framework directly so there is no framework nesting.
A potential improvement here is to build WebRTC as a static library so it can
then be embedded in JitsiMeet.framework and completely hidden from the app.
=> [iOS] Link with WebRTC.framework at the top level

css/_jitsi_popover.scss, modules/UI/util/JitsiPopover.js, modules/UI/videolayout/ConnectionIndicator.js, modules/UI/videolayout/RemoteVideo.js, react/features/connection-stats/components/ConnectionStatsTable.js, react/features/connection-stats/components/index.js, react/features/connection-stats/index.js
The commit "feat(connection-stats)" takes the connection stats display from ConnectionIndicator and converts it into a React Component.
The commit "feat(popover)" modifies JitsiPopover to re-render its contents instead of tearing down its html and recreating on each update.
These changes are built on top of the commit "feat(remote-video)", https://github.com/jitsi/jitsi-meet/pull/1631. That commit must be merged in first.
=> feat(connection-stats): convert connection stats display to react

conference.js, modules/UI/UI.js, modules/UI/shared_video/SharedVideo.js, modules/UI/videolayout/LocalVideo.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/SmallVideo.js, react/features/base/participants/actionTypes.js, react/features/base/participants/actions.js, react/features/base/participants/constants.js, react/features/base/participants/middleware.js, react/features/display-name/components/DisplayName.js, react/features/display-name/components/index.js, react/features/display-name/index.js, react/features/filmstrip/components/Filmstrip.web.js
- Create a new React Component for displaying and updating display
names on small videos.
- The updating of the Component is defined in the parent class
SmallVideo, which children will get access to through prototype
copying.
- Create a new actionType and middleware so name changes that occur
in DisplayName can be propogated to outside redux.
=> feat(display-name): convert to React

config.js, react/features/base/conference/actions.js
~Note: this PR sits atop #1710~
Rebased.
=> feat(p2p): enable H.264 for P2P by default

css/_vertical_filmstrip_overrides.scss, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/SmallVideo.js, react/features/filmstrip/components/_.web.js, react/features/filmstrip/components/index.js, react/features/filmstrip/components/web/AudioMutedIndicator.js, react/features/filmstrip/components/web/BaseIndicator.js, react/features/filmstrip/components/web/ModeratorIndicator.js, react/features/filmstrip/components/web/VideoMutedIndicator.js, react/features/filmstrip/components/web/index.js
Move display of audio muted, video muted, and moderator icons,
which make up the elements of the small video toolbar, into React
Components.
jitsi-meet-torture tests had to be updated as the icons are now
removed from the dom when they should be hidden instead of
visibility being set to hidden. https://github.com/jitsi/jitsi-meet-torture/pull/86
=> feat(small-video): convert the "toolbar" to react

css/_vertical_filmstrip_overrides.scss
Icons on the thumbnails can flicker when scrolling through videos.
To give rendering a bit more power, and thereby help with rendering
icons without flickering, force hardware acceleration.
=> fix(vertical-filmstrip): enable hardware acceleration for icons

css/_filmstrip.scss, css/_toolbars.scss, css/_vertical_filmstrip_overrides.scss, react/features/conference/components/Conference.web.js, react/features/filmstrip/components/Filmstrip.web.js, react/features/toolbox/components/Toolbox.web.js
Use top 50% to position the toolbar's top at the vertical center
of the iframe. Then use transform 50% to move the toolbar itself
up 50% so its middle matches the middle of the iframe.
=> fix(filmstrip-only): vertically align center the toolbar

react/features/base/conference/actionTypes.js, react/features/base/conference/actions.js, react/features/base/conference/reducer.js, react/features/base/connection/actionTypes.js, react/features/base/connection/actions.native.js, react/features/base/connection/reducer.js
Keep track of the connection and conference objects so we can leave and / or
disconnect early, before the connection is established or the conference joined.
Leftover(s) of https://github.com/jitsi/jitsi-meet/pull/1741.
=> [RN] Fix disconnecting before the connection was established

react/features/invite/functions.js
Chrome has deprecated line breaks in requests. The template
literal used for the searchPeople url has a line breaks. Instead
of line breaking the request url, concatenate it together.
=> fix(add-people): remove line break from searchPeople request

resources/prosody-plugins/token/util.lib.lua
stick user and group from token context into session if available
=> use "sub" instead of "aud" to confirm tenant domain settings

react/features/base/tracks/actions.js
Listeners were set for when a track muted or changed its video
type, but the listeners were never removed. This would could
cause events to keep firing on the removed tracks, which would
cause redux to fire and error because the tracks were no longer
known. That the tracks still fire events after removal is
another issue...
=> fix(tracks): remove mute and type change listeners on track remove

resources/prosody-plugins/token/util.lib.lua
default audience and issuer checks to validate only appId
added missing documentation lines from previous PR for context_user and context_group session values
=> added checks for audience and issuer values

react/features/conference/route.js, react/features/jwt/components/CallOverlay.js
New token scheme has slightly simplified field names, so use them if available
=> accept 'avatar' as well as 'avatarUrl' for avatar field

conference.js, config.js, interface_config.js, modules/UI/util/UIUtil.js, react/features/toolbox/actions.web.js, react/features/toolbox/components/ToolbarButton.web.js, react/features/toolbox/functions.web.js
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/548
config.disableDesktopSharing - when set to false will disable desktop
sharing
interfaceConfig.DESKTOP_SHARING_BUTTON_DISABLED_TOOLTIP - when value is
assigned, will not hide the desktop sharing button completely, but show
as disabled with this value used as the tooltip text.
=> feat: add option to disable desktop sharing

android/build.gradle, android/sdk/build.gradle, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, react/features/base/media/reducer.js
This reverts commit c9a29153ddf55fb9021000696e71b4e4f04b302b.
Now that react-native-webrtc supports the permissions system in 23, use it since
it provides a more pleasant experience to users.
In addition, fix a bug in the previous code: the React Native view must be
loaded after we have acquired the permission to draw on top of other apps,
otherwise our app may crash while we accept the permission, since React may try
to draw.
=> [Android] Use target API 23

react/features/app/middleware.js, react/features/base/tracks/middleware.js
The end goal of this patch was to avoid opening the camera when there is no
welcome page.
In order to achieve this, the logic for creating the local tracks was
refactored:
Before this patch local tracks were created when lib-jitsi-meet was initialized,
and destroyed when it was deinitialized. As a side note, this meant that when a
conference in a non-default domain was joined, local tracks were destroyed and
recreated in quick succession.
Now, local trans are created and destroyed based on what the next route will be,
and this happens when the target room has been decided. This allows us to create
local tracks the moment we need to render any route, and destroy them when there
is no route to be rendered. As an interesting byproduct, this refactor also
avoids the destruction + recreation …
=> [RN] Don't open the camera on startup when there is no welcome page

android/sdk/src/main/AndroidManifest.xml
This was already an implicit requirement, as it's the only version implemented
in libwebrtc.
The reason to add this is to (defensively) try to filter old devices which may
not implement it.
WebRTC's own Android demo app defines this.
=> [Android] Require OpenGL ES 2.0

react/features/app/middleware.js, react/features/base/config/reducer.js
navigator.product is read-only, so we don't run into the risk of it being
changed.
=> [RN] Use a more resilient way for testing if we are on React Native

modules/UI/videolayout/VideoLayout.js
This broke because the method names changed when the top icons of the thumbnail got reactified. This likely broke because either I just missed it during initial development or missed the change while redoing the changes due to conflicts.
This mainly affected when someone got kicked out of the conference. That's when the indicators are hidden. However, another script error occurs when getting kicked out, and its origin is  seemingly unrelated to the indicator.
=> fix(connection-indicator): rename calls to hiding the indicator

conference.js, modules/UI/UI.js, modules/UI/videolayout/LocalVideo.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/SmallVideo.js, modules/UI/videolayout/VideoLayout.js, react/features/connection-indicator/components/ConnectionIndicator.js, react/features/connection-indicator/index.js, react/features/connection-indicator/statsEmitter.js
Instead of passing stats through UI then VideoLayout then the
SmallVideo, pass stats directly to what uses it--ConnectionIndicator.
This also bypasses adding the stats to the store, as they do not
seem to be something that needs to be shared or stored app-wide
just yet.
=> ref(stats): process stats through one pub/sub

react/features/dial-out/components/DialOutNumbersForm.web.js, react/features/invite/components/DialInNumbersForm.js
With the upgarde of @atlaskit/icon to 7.0.0, the size prop
essentially became required to maintain its appearance in the
jitsi app, otherwise it'll unexpectedly try to take up the
available space and cause minor display issues.
=> fix(icons): set a size prop for AtlasKit icons

css/themes/_light.scss, interface_config.js, react/features/toolbox/components/PrimaryToolbar.web.js, react/features/toolbox/components/Toolbar.web.js
The primary toolbar splitter isn't used anymore and only adds complexity to the code.
=> Remove primary toolbar splitter

react/features/base/react/components/AbstractContainer.js, react/features/base/react/components/native/Container.js, react/features/base/react/components/web/Container.js, react/features/base/styles/functions.js
This PR fixes view clipping (at least on the devices I could test with) and stops destroying the filmstrip (or any other container, for that matter) when it's hidden.
See the individual commits for more details.
=> [RN] Filmstrip fixes (I)

conference.js, react/features/base/media/middleware.js, react/features/base/tracks/functions.js, react/features/base/tracks/middleware.js
Because on web video track is stored both in redux and in 'localVideo'
field, video is attempted to be unmuted twice when turning off the audio
only mode. This will crash the app with 'unmute operation is already in
progress'. This commit will prevent from taking action from the web
world if the video track already exists and will make the redux side
rollback unmuted status in case unmute fails.
=> fix(AudioOnly+web): crash when untoggle audio only

android/README.md, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java, ios/README.md, ios/app/src/ViewController.m, ios/sdk/src/JitsiMeetView.h, ios/sdk/src/JitsiMeetView.m, react/features/app/components/AbstractApp.js, react/features/app/reducer.js, react/features/base/util/uri.js
Introduces `loadURLObject` in JitsiMeetView on Android and iOS which accepts a `Bundle` and `NSDictionary`, respectively, similar in structure to the JS object accepted by the constructor of Web's ExternalAPI. At this time, only the property `url` of the bundle/dictionary is supported. However,  it allows the public API of `loadURLObject` to be consumed. The property `url` will be made optional in the future and other properties will be supported from which a URL will be constructed.
=> [RN] Alternative to JitsiMeetView.loadURL w/o URL

ios/sdk/src/JitsiMeetView.m
We must not pass nil as the URL, that will translate to null and we won't be
able to load the initial URL which is passed as the launch parameters.
=> [iOS] Fix loading initial URL when app is closed

react/features/base/react/components/native/Container.js
Whatever I've tried so far ends up failing in really weird ways, so let's admit
defeat, for now. Destroy containers only on Android.
This shall be revisited when we update RN to version >= 0.43 and we have
"display: 'none'" available.
=> [Android] Destroy containes when they are not visible

android/README.md, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
In iOS this is automagically done in the view destructor, bunt we don't have
that luxury in Java we have to do it manually.
The new disponse() method MUST be called when the Activity holding the view is
going to be destroyed, typically in the onDestroy() handler.
=> [Android] Fix resource leak when JitsiMeetView is destroyed

css/_dial-out.scss, react/features/dial-out/components/DialOutNumbersForm.web.js
- Swap the telephone input with FieldText.
- Swap the dropdown trigger input with FieldText for styling
consistency with the telephone input.
- Wrap the dropdown trigger so it can be modified with jitsi css.
- Use flexbox to have the trigger and input align horizontally
but have the input take up width if the trigger is not displayed.
=> ref(dial-out): use AtlasKit FieldText for inputs

react/features/dial-out/actions.js, react/features/dial-out/components/DialOutDialog.web.js, react/features/dial-out/components/DialOutNumbersForm.web.js, react/features/dial-out/reducer.js, react/features/invite/actions.js
Hides the UI component showing dialout codes and uses the dial input without validating it.
Skips printing error when dial-in numbers is not configured.
=> Handles disabled dial-out codes.

conference.js, css/_filmstrip.scss, css/_videolayout_default.scss, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/VideoContainer.js, react/features/base/participants/actions.js, react/features/large-video/components/LargeVideo.web.js, react/features/presence-status/components/PresenceLabel.js, react/features/presence-status/components/index.js, react/features/presence-status/index.js
- Create a React Component for displaying presence. It currently
connects to the store for participant updates but in the future
should not be as smart once more reactification occurs.
- Modify filmstrip css so the presence status displays horizontal
center and below the avatar.
- Modify videolayout css so the presence status displays horizontal
centered and with a rounded background.
- Dispatch presence updates so the participant state can be update.
- Update message position on large video update to ensure message
positioning is correct.
=> feat(presence): display status in thumbnail and large video

conference.js, lang/main.json, modules/UI/UI.js, modules/UI/recording/Recording.js, modules/UI/util/MessageHandler.js, modules/devices/mediaDeviceHelper.js, package.json, react/features/conference/components/Conference.web.js, react/features/notifications/actionTypes.js, react/features/notifications/actions.js, react/features/notifications/components/NotificationWithToggle.web.js, react/features/notifications/components/NotificationsContainer.web.js, react/features/notifications/components/index.js, react/features/notifications/reducer.js, react/features/overlay/components/OverlayContainer.js
- Create a notification component for displaying a toggle.
- Create an action for showing the component if allowed by
the local storage setting and for saving the setting to
local storage.
- Remove all notifications having a timeout by default so the
device error notification must be dismissed manually.
- Split the camera and mic error dialog into two separate
notifications.
=> feat(device-errors): move device error dialogs to notifications

react/features/base/lib-jitsi-meet/native/polyfills-browser.js
Currently lib-jitsi-meet looks there in case the `anonymousdomain` config option
was specified.
While this commit alone doesn't add support for authenticated deployments, it
avoids a failure if `anonymousdomain` was set, regardless of authentication being
turned on or not.
Fixes: https://github.com/jitsi/jitsi-meet/issues/1858
=> [RN] Polyfill window.location.search

react/features/base/conference/actions.js
Sometimes it will be suboptimal to add local tracks to the conference,
after the room has been joined. It may slow down the session initiation
process by having to send unnecessary 'source-add' notifications.
=> Add local tracks before joining the conference

debian/jitsi-meet-tokens.postinst, resources/prosody-plugins/mod_auth_token.lua, resources/prosody-plugins/mod_muc_size.lua
Adds some debug messages when token verification fails for some reason.
=> Installs required basexx when token package is installed. Fixes #1870.

conference.js, modules/FollowMe.js, modules/UI/shared_video/SharedVideo.js, modules/UI/videolayout/VideoLayout.js, react/features/base/conference/middleware.js, react/features/base/participants/functions.js, react/features/base/participants/reducer.js, react/features/jwt/middleware.js
- Re-use the native redux pinning implementation for web
- Remove pinning logic from conference.js
- To the native pinning add a check for sharedVideo so
youtube videos do not send a pin event
- Add shared videos as a participant to enable pinning and
so they can eventually get added to the filmstrip
=> feat(pinning): move web pinning logic into redux

css/_filmstrip.scss, css/_variables.scss, css/_vertical_filmstrip_overrides.scss, modules/UI/videolayout/Filmstrip.js
With AtlasKit InlineDialog, the filmstrip z-index in vertical
filmstrip mode was adjusted as it had to be set to fixed position
for the dialogs to automagically be position fixed. This left
behind a regression where the filmstrip z-index was the same as
the video quality label, but came later in the dom, so the label
was not clickable. This commit modifies the z-index of the
vertical filmstrip to account for clicking of the video quality
label.
This commit pretty much signs me up even more for css
cleanup of the filmstrip, which isn't too far fetched if I am
to continue its react-ification and redux-ification.
=> fix(video-quality-label): adjust z-indexing clashes with filmstrip

react/features/video-quality/components/VideoQualityLabel.web.js
This will prevent the quality dialog from closing when changing
desired quality level.
=> fix(video-quality): change click handler location on label

css/modals/invite/_invite.scss, react/features/dial-out/components/DialOutNumbersForm.web.js, react/features/invite/components/AddPasswordForm.js, react/features/invite/components/DialInNumbersForm.js, react/features/invite/components/ShareLinkForm.js
- Convert button to AK Button.
- Convert password and meeting link inputs to AK FieldText.
- Convert dial-in dropdown to SingleSelect.
=> ref(invite): use AtlasKit for invite modal buttons and inputs

css/_vertical_filmstrip_overrides.scss
Filmstrip cannot be higher than tooltip-z or else it'll cover up tipsy tooltip. The z-index change wasn't even needed. What was I doing?
=> fix(filmstrip): re-adjust z-indexes for tooltip display

css/modals/video-quality/_video-quality.scss, react/features/video-quality/components/VideoQualityDialog.web.js
Instead of removing and appending the p2p warning, make it always
appended but toggle visibility so it always takes up space. This
should prevent resizing when the warning appears. Margin and
padding were adjusted to account for the empty space displayed
by a hidden p2p warning.
=> fix(quality-slider): prevent resizing by making p2p warning hidden

conference.js, modules/UI/UI.js, modules/UI/videolayout/Filmstrip.js, react/features/filmstrip/components/Filmstrip.web.js, react/features/filmstrip/reducer.js, react/features/video-quality/components/VideoQualityLabel.web.js
- Remove non-redux paths for hiding and showing remote videos.
- Hook web filmstrip to redux to know when to hide remote videos.
This works, even though VideoLayout is handling RemoteVideo
appending, because react is only monitoring filmstrip's declared
JSX which does not change except for attributes (css classes).
=> ref(filmstrip): hook filmstrip to redux for 1-on-1 mode

conference.js, modules/UI/UI.js, react/features/base/media/functions.js, react/features/base/media/middleware.js, react/features/base/tracks/actions.js, react/features/base/tracks/functions.js, react/features/base/tracks/middleware.js, react/features/toolbox/defaultToolbarButtons.js, react/features/toolbox/functions.native.js, react/features/toolbox/middleware.js
This PR fixes an issue where turning off audio only mode will not unmute local video (on Web).
Gets rid of flags in conference.js and figures out muted status based on redux track's state.
Next step would be to get rid of 'localAudio' and 'localVideo' fields in conference.js.
=> Get rid of 'audioMuted' and 'videoMuted' flags in conference.js

react/features/base/config/functions.js
Iterate over objects and copy over primitives and arrays
instead of using _.merge, as merge will not replace a config
entry completely. For arrays in a target object, the arrays
will have its indices replaced. This means if a source array
is empty, the target array will be left alone. Similarly,
if the target array is longer than a source array, there
will be indices not touched in the target array.
This commit fixes #1863.
=> fix(config): override config values instead of merging

android/sdk/src/main/java/org/jitsi/meet/sdk/AndroidSettingsModule.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java, react/features/app/components/App.native.js, react/features/app/functions.native.js, react/features/app/middleware.js, react/features/base/conference/middleware.js, react/features/base/media/actions.js, react/features/base/tracks/actionTypes.js, react/features/base/tracks/actions.js, react/features/base/tracks/middleware.js, react/features/conference/components/Conference.native.js, react/features/mobile/permissions/functions.js, react/features/mobile/permissions/index.js, react/features/mobile/permissions/middleware.js, react/features/toolbox/components/Toolbox.native.js, react/features/welcome/components/BlankWelcomePage.js, react/features/welcome/components/WelcomePage.native.js, react/features/welcome/components/index.js, react/features/welcome/route.js
~~**NOTE**: this sits atop https://github.com/jitsi/jitsi-meet/pull/1896 and https://github.com/jitsi/jitsi-meet/pull/1904 so it's probably a good idea to review this PR as a whole thing.~~
Caveat emptor: there are 2 issues I'm still trying to address.
- On iOS the app is restarted when a permission is granted / revoked from settings. This is great, except when you followed a deep-link, which is now lost.
- On Android the app is restarted when a permission is revoked from settings (great!) but we don't know if a permission is granted (what?!).
=> [RN] Alert the user when they need to manually grant a permission

css/_popover.scss, css/_vertical_filmstrip_overrides.scss, css/_videolayout_default.scss, css/main.scss, css/modals/video-quality/_video-quality.scss, react/features/base/popover/components/Popover.web.js, react/features/base/popover/components/index.js, react/features/base/popover/index.js, react/features/connection-indicator/components/ConnectionIndicator.js, react/features/remote-video-menu/components/RemoteVideoMenuTriggerButton.js, react/features/video-quality/components/VideoQualityLabel.web.js
Note: this commit removes hiding the remote menu automatically on mute and kick because it felt like it would be awkward to keep supporting.
=> fix(inline-dialog): reimplement popover display on mouse move

modules/UI/UI.js, modules/util/helpers.js
The current custom debounce function sets a timeout and ensures
additional calls are not executed while the timeout is pending.
Regulating the call of a function while also ensuring it gets
called at a certain time is a throttle.
=> ref(toolbar): replace custom debounce with lodash throttle

conference.js, react/features/filmstrip/actionTypes.js, react/features/filmstrip/actions.js, react/features/filmstrip/components/Filmstrip.web.js, react/features/filmstrip/functions.js, react/features/filmstrip/index.js, react/features/filmstrip/reducer.js, react/features/recording/components/RecordingLabel.web.js, react/features/video-quality/components/VideoQualityLabel.web.js
Derive whether or not remote videos should display using a selector
to look across different states. A selector was chosen over using
memoized selectors (reselect) or subscribers as a first step
approach, avoiding additional mutations caused by a subscriber
updating the filmstrip state and avoiding additional api overhead
introduced by reselect.
This commit was made on top of https://github.com/jitsi/jitsi-meet/pull/1915. This commit will rely on the lib-jitsi-changes from that pull request, and tests will fail until those lib changes are merged in.
=> ref(1-on-1): move remote video visibility to a selector

package.json, react/features/base/config/reducer.js, react/features/base/lib-jitsi-meet/native/polyfills-browser.js
The global.performance.now polyfill is removed since it's polyfilled by
react-native-callstats.
=> [RN] Add support for callstats on mobile

react/features/toolbox/components/ToolbarButton.web.js
The torture tests were looking for the anchor tag within each
button. However, that anchor could get blown away from a react
re-render. So instead, expose a way for the torture tests
to find the root node of the button.
=> ref(toolbar): add wrapper around buttons for torture tests

modules/API/external/external_api.js, react/features/base/util/loadScript.web.js
We broke external_api.min.js by `import`ing react/features/util which
`import`ed react/features/base/lib-jitsi-meet.
1. To reduce the risks of such a breakage until we add
external_api.min.js to the torture tests, `import` as little as
possible in modules/API/external/external_api.js.
2. Use the global `JitsiMeetJS` on Web in react/features/base/util.
=> Reduce the dependencies of the Web ExternalAPI

modules/API/external/external_api.js
In Chrome M63 a warning is shown, permissions won't be automatically allowed
afterwards. Reference:
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes
Setting this early makes us future proof, while working with current versions
too: Chrome < 63 gives an error because it doesn't understand the option and
Firefox seems to ignore it, so both continue to work as before.
=> feat(external_api): set permissions for cross-origin iframe

react/features/base/media/components/AbstractVideoTrack.js, react/features/base/media/components/web/Video.js, react/features/base/media/components/web/VideoTrack.js, react/features/device-selection/components/VideoInputPreview.js
Filmstrip only mode displays a device selection dialog that
does not have access to the redux/connect. However, the current
VideoTrack extends from AbstractVideoTrack, which assumes a
redux connection. The fix is to move video display logic into
a separate component and have device selection use that, while
the existing VideoTrack remains connected to redux but
uses the new video display component.
=> fix(device-selection): use non-connect video preview

conference.js
Without dominant speaker in redux, the wrong user will be
selected after an unpin event.
=> fix(dominant-speaker): update dominant speaker in redux

android/sdk/src/main/java/org/jitsi/meet/sdk/DefaultHardwareBackBtnHandlerImpl.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
If the JS side chooses to not handle the back button press call 'super.onBackPressed()' to close the app.
=> Android: implement DefaultHardwareBackBtnHandler

modules/UI/UI.js, react/features/toolbox/actions.web.js, react/features/toolbox/components/ProfileButton.web.js, react/features/toolbox/components/StatelessToolbarButton.js, react/features/toolbox/components/Toolbar.web.js, react/features/toolbox/components/ToolbarButton.web.js, react/features/toolbox/defaultToolbarButtons.web.js
Refactors the profile button. 
Fixes the issues with profile button to be unclickable when jwt is provided (removes the tooltip and changes the style of the cursor).
=> fix(profile_button): unclickable

react/features/toolbox/components/ToolbarButtonWithDialog.web.js
The implementation of ToolbarButtonWithDialog expects a
constructor function for now, not the object returned
from calling a constructor function.
=> fix(toolbar): fix proptype warning

modules/util/JitsiLocalStorage.js
Fixes an issue with Jitsi Meet when the local storage is disabled. 
Accessing `window.localStorage` was causing an error which was stopping the JS execution before anything on the page was loaded.
=> fix(JitsiLocalStorage): Handle local storage error

css/_contact_list.scss, css/components/_form-control.scss, lang/main.json, react/features/contact-list/components/ContactListPanel.web.js
Removing becuase there is already a toolbar button dedicated
to opening the invite dialog. Now the contact list focuses
on showing current participants.
While I was changing things, I unintentionally obscured the intent of this pr by adding an import of the PropTypes package and changing how interfaceConfig is accessed.
=> ref(contact-list): remove invite functionality

css/modals/invite/_info.scss, react/features/invite/actionTypes.js, react/features/invite/actions.js, react/features/invite/components/InfoDialog.web.js, react/features/invite/components/InfoDialogButton.web.js, react/features/invite/reducer.js, react/features/toolbox/components/ToolbarButton.web.js, react/features/toolbox/components/ToolbarButtonWithDialog.web.js, react/features/toolbox/constants.js, react/features/toolbox/index.js
I'm not confident about the implementation here but it meets the absolute bare minimum of the happy flow working.
A couple things bothering me:
- I'm still not sure a good way to abstract a toolbar/box button with an inline dialog.
- The inline dialogs don't dock the toolbar and I'm not sure if that's good or bad.
- The relationship between toolbox and these other features seems off to me, maybe the features are circularly dependent but at least on different files.
=> feat(info): automatically show the info dialog

react/features/connection-indicator/statsEmitter.js
This is more of a principle change than a necessary one.
In lib-jitsi-meet, when a getStats call finishes, the
stats are processed and first emitted (and received by
jitsi-meet) and then processed again for sending to
remote participants. Modifying the stats in place changes
the structure of stats before the second processing,
which maybe be unexpected.
=> ref(stats): do not modify stats object from lib

react/features/toolbox/defaultToolbarButtons.web.js
Fixes exception when trying to unmute in the scenario, where someone else is sharing a video with you.
=> fix(defaultToolbarButtons): Fixes mute popup warning

react/features/mobile/full-screen/middleware.js
HIDE_DIALOG happens between WILL_JOIN and JOINED so get the joining conference
from the state instead of the action.
=> [RN] Fix setting full-screen when joining a conference

conference.js
If we join in a conference and there are messages from user who left before us joining(or they do not have display name set, missing nick extenasion in presence), now we see this:
This PR fixes like this:
It adds the resource of the user that sent the message, cause there may be multiple people who left/rejoined and we need to at least see the difference between messages, like:
=> Fixes display name for incoming chat messages, sender doesn't have nick.

react/features/base/jwt/middleware.js, react/features/base/participants/constants.js, react/features/base/participants/reducer.js
Recently/as part of the work on taking into account the user defined by
JWT, the local participant (on mobile) started telling the remote
participants that he/she had the display name "me". Obviously, that's
incorrect. Do not store the default display name in redux. While it may
be argues that redux is the place for all states, base/participants and
the name property of Participant is not meant to be that display name
because that is being sent to remote participants, the default name
needs to be internationalized, etc. So it's better to not store the
default display name at this time at all because it's not used by mobile
anyway and Web already deals with remote participants who don't share
their display names.
=> [RN] Don't tell everyone we're called "me"

conference.js, react/features/base/tracks/actions.js
Fixes:
- unplugging devices mutes current use mic and video, even if they are not used
- changing locally used devices unmutes you if you are muted audio or video
- stops desktop sharing if we change locally used video device
=> Fixes few changes around changing devices

android/build.gradle
Android Studio won't build the app otherwise. Since the gradle plugin 3.0 beta7,
the minimum supported build tools version is 26.0.2, so set it to that. Also
bump compileSdkVersion to 26 since they need to match (in the major number, that
is).
The target API is still 25. Android Oreo (26) brought some changes in overlay
permissions which I haven't figured out yet.
=> [Android] Specify build tools version

modules/UI/authentication/LoginDialog.js
By default impromptu uses the first state as the default one to show.
=> Moves login state of dialog to be first, to be the initial state.

config.js, react/features/base/conference/constants.js, react/features/base/tracks/functions.js
The lib will accept new style constraints and use those
to capture audio/video. By defining the constraints in
config, there is greater flexibility for defining
and changing constraints.
Relies on https://github.com/jitsi/lib-jitsi-meet/pull/617.
=> feat(1080p): pass new-style constraints to createLocalTracks

react/features/base/react/components/native/Container.js
No, it still doesn't work properly on Android, sigh.
=> [iOS] use display: 'none' to hide elements

modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/VideoLayout.js
Removes hasRemoteVideoMenu from RemoteVideo.
In some cases where mod_muc_allowners is enabled we do not see the remote video menu. The problem was in the order of initialization of remote video component.
RemoteVideo#constructor -> Remotevideo#addaddRemoteVideoContainer -> Remotevideo#addRemoteVideoMenu  -> RemoteVideo#hasRemoteVideoMenu = true
Then in VideoLayout#showModeratorIndicator -> !remoteVideo.hasRemoteVideoMenu -> remoteVideo.addRemoteVideoMenu().
=> Fixes a problem not showing remote video menu in case of all moderators.

modules/UI/videolayout/LocalVideo.js, react/features/filmstrip/components/Filmstrip.web.js
Instead of targetting a div that contains multiple elements
and risking the elements appearing out of order, create a
specific div for local video to append to.
=> fix(filmstrip): create a specific target for local video appending

react/features/video-quality/components/VideoQualityLabel.web.js
The minimum resolution needed to show the HD label should be
720, not 1080. However, the requested video quality for
high quality should be 1080.
=> fix(1080p): video quality label shows hd at 720

react/features/app/components/App.native.js, react/features/base/aspect-ratio/actionTypes.js, react/features/base/aspect-ratio/actions.js, react/features/base/aspect-ratio/components/AspectRatioAware.js, react/features/base/aspect-ratio/components/AspectRatioDetector.native.js, react/features/base/aspect-ratio/components/index.js, react/features/base/aspect-ratio/components/styles.js, react/features/base/aspect-ratio/constants.js, react/features/base/aspect-ratio/index.js, react/features/base/aspect-ratio/reducer.js, react/features/base/react/components/native/Container.js, react/features/conference/components/Conference.native.js, react/features/conference/components/styles.js, react/features/filmstrip/components/Filmstrip.native.js, react/features/filmstrip/components/styles.js, react/features/toolbox/components/Toolbox.native.js, react/features/toolbox/components/styles.js
Adds the ability to detect app area's aspect ratio on react-native
through the features/base/aspect-ratio.
Makes conference, filmstrip and toolbox react to the aspect ratio
changes and display filmstrip on the shorter side of the screen.
<hr/>
=> Mobile: display filmstrip on the short side

analytics.js
Alternatively the file could be run through webpack but I went with this first because it's less work.
=> fix(analytics): use string concatenation for ie11

webpack.config.js
I'm not sure if there is a better way to apply the polyfill in the webpack config, as currently with this change the adding of the polyfill is duplicated for both app.js and external_api.js. The polyfill itself is needed right now so external_api can get String.prototype.startsWith and to protect against future changes that could introduce es6 that is not supported by IE11.
=> fix(external-api): build with polyfill for IE11

package.json, react/features/base/dialog/components/StatelessDialog.web.js, react/features/base/react/components/web/InlineDialogFailure.js
That standalone ButtonGroup package has been deprecated.
The deprecation warning says to use the ButtonGroup component
from the Button package.
=> fix(button-group): use ButtonGroup from the Button package

modules/UI/shared_video/SharedVideo.js
The YouTube api removed player#getVideoData years ago.
I am completely baffled as to how the feature kept working.
The title of the video is no longer obtainable through
the player itself, so instead call the bot participant
"YouTube."
=> fix(shared-video): hardcode shared video name

.gitignore, ios/Podfile.lock, react/features/base/conference/actions.js, react/features/base/tracks/actionTypes.js, react/features/base/tracks/actions.js, react/features/base/tracks/functions.js, react/features/base/tracks/reducer.js, react/features/mobile/permissions/middleware.js, react/features/remote-video-menu/components/MuteRemoteParticipantDialog.web.js
Still to be rebased and may need more testing.
'createDesiredLocalTracks' in 'base/tracks/actions' contains the logic which checks whether or not tracks for audio/video media type exist and then decides to create tracks for those media for which there is no track yet. The problem is that if you call this method twice and trackAdded is not emitted, before the second call it will make an attempt to create track for given media twice. That's because track is not added to redux until GUM callback succeeds and trackAdded action is sent.
We're hitting similar scenario if JitsiMeet app does not exist in the background and you try to join conference by clicking on Jitsi Meet compatible URL. First it will create video track from 'audio only turned to off' and 'ensureTrack' flag and then from the …
=> [PREVIEW|RN]: Handle getUserMedia in progress

css/_welcome_page.scss
Overflow on body was set to hidden, likely because of
various tricks used to hide elements off screen in the
SPA. Overflow hidden also has the benefit of hiding
scroll bounce when using a MacBook touchpad. The
welcome page is the exception that needs scrolling,
so style welcome page to scroll.
A couple others had made pull requests to addrses this issue
but there hasn't been follow up.
=> fix(welcome-page): allow scrolling

app.js, modules/UI/side_pannels/chat/Chat.js, package-lock.json, package.json
After looking at the jquery-ui documentation, I believe it
is being used only in one place, when toggling the smiley
menu. That toggling has been quickly replaced with a normal
jquery call.
Note: @atlassian/aui also uses jquery-ui but killing that
off will be more difficult due to its CSS being used.
=> ref(deps): remove jquery-ui

package-lock.json, package.json, react/features/base/tracks/functions.js
Refs: https://github.com/jitsi/lib-jitsi-meet/pull/648
It's possible for a track to be disposed but still on the redux store, before
the reducer removed it.
=> [RN] Ignore mute error if track is disposed

conference.js, react/features/base/connection/actions.web.js
Initializing UI features, like keyboard shortcuts, by chaining
onto APP.conference.init is not safe because init can fail,
skipping the initializing of UI features. This can happen when
the room is locked and then a failure event is dispatched into
middleware. I couldn't find a place to properly chain onto
in the APP.conference.init promise chain, primarily due
to the flow continued within middleware, so instead I
leveraged an existing listener for CONFERENCE_JOINED.
=> fix(conference): initialize UI features on CONFERENCE_JOINED

react/features/notifications/constants.js, react/features/notifications/reducer.js
I'm not sure how this should be implemented so here's one shot that shows the concept working. It converts appearance to a priority and inserts the notification based on appearance. This PR is built on top of another PR, which has to go in first to avoid some bugs.
=> spike: feat(notifications): prioritize based on type (appearance)

modules/UI/UI.js, package-lock.json, package.json
When participant joins and there is an initial status we show it, instead of the connected notification. If initial status is missing proceed with the default user connected notification.
=> On adding participant show the initial status text if any.

react/features/base/conference/reducer.js, react/features/base/jwt/components/CallOverlay.js, react/features/base/lib-jitsi-meet/functions.js, react/features/overlay/components/AbstractPageReloadOverlay.js, react/features/overlay/components/AbstractSuspendedOverlay.js, react/features/overlay/components/AbstractUserMediaPermissionsOverlay.js, react/features/overlay/components/FilmstripOnlyOverlayFrame.js, react/features/overlay/components/OverlayContainer.js, react/features/overlay/components/OverlayFrame.js, react/features/overlay/components/PageReloadFilmstripOnlyOverlay.js, react/features/overlay/components/PageReloadOverlay.js, react/features/overlay/components/SuspendedFilmstripOnlyOverlay.js, react/features/overlay/components/SuspendedOverlay.js, react/features/overlay/components/UserMediaPermissionsFilmstripOnlyOverlay.js, react/features/overlay/components/UserMediaPermissionsOverlay.js, react/features/overlay/reducer.js
Refactor how overlays are selected. This work is required before porting them to mobile. The plan is to make each overlay self-contained and the container just a holder for the current one.
I intentionally didn't change PropTypes for Flow Props to avoid too much churn, I'll address that when adding mobile overlays.
=> Refactor overlays

react/features/device-selection/popup.js
AtlasKit is not fully compatible with React 16. One problem
is PropTypes will not be defined on the React object. So,
add the prop-types shim to the popup bundle.
=> fix(device-selection): add proptypes shim for popup

react/features/base/dialog/components/Dialog.native.js
75bf7638b353cf09c4fc35bb071b6ecb69fc2b14 introduced this regression, state must
be assigned as an object, even though one would think it's automagically
initialized to an object. Oh well!
=> [RN] Fix assigning Dialog state

app.js, conference.js, css/_side_toolbar_container.scss, modules/UI/UI.js, modules/UI/side_pannels/settings/SettingsMenu.js, modules/translation/translation.js, package.json, react/features/base/conference/actionTypes.js, react/features/base/conference/actions.js, react/features/base/conference/reducer.js, react/features/settings-menu/components/DeviceSelectionButton.web.js, react/features/settings-menu/components/LanguageSelectDropdown.web.js, react/features/settings-menu/components/ModeratorCheckboxes.web.js, react/features/settings-menu/components/SettingsMenu.web.js, react/features/settings-menu/components/index.js, react/features/settings-menu/index.js, service/UI/UIEvents.js
The goal is to reduce usage on atlassian/aui. New components
have been created to display the settings panel. Language
selection will reach into i18n for state whereas moderator
options will keep state in redux.
Relies on https://github.com/jitsi/jitsi-meet-torture/pull/104.
=> ref(settings): convert panel to react

css/_vertical_filmstrip_overrides.scss, modules/UI/videolayout/Filmstrip.js
The UX implication is that on Chrome and Safari, new remote videos thumbnails appear to get put on the top of existing remote videos and scrolling starts from the bottom of the filmstrip. On IE11, Edge, and Firefox, the videos appear to get put below the existing remote videos and scrolling starts from the top of the filmstrip. Let's make sure this is acceptable or if more changes are needed.
=> fix(vertical-filmstrip): Firefox scrolling issues

css/_welcome_page.scss
With current Spanish translations, some alignments on the welcome page are off. The alignment with the feature holders was off and I'll be honest I didn't bother figuring out the cause because float doesn't need to be used anyway when inline block puts the feature holders in a row. Removing the float fixed it so I moved on. The longer description titles were also misaligned as the top alignment was being set with padding, but the titles are already in a table-cell which supports vertical-alignment setting.
=>  fix(welcome-page): fix alignment issues

android/sdk/build.gradle, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java, android/settings.gradle, ios/Podfile, ios/Podfile.lock, package-lock.json, package.json
Upstream lacked a CocoaPods podspec file, PR:
https://github.com/DylanVann/react-native-locale-detector/pull/3
=> [RN] Build react-native-locale-detector

react/features/filmstrip/components/Filmstrip.native.js
When in wide aspect ratio,, show it with the local participant on top, and the
remote ones after, sorted by join order.
=> [RN] Adjust filmstrip ordering based on aspect ratio

react/features/base/participants/components/ParticipantView.native.js, react/features/base/participants/components/styles.js, react/features/base/participants/functions.js, react/features/base/react/components/native/TintedView.js, react/features/base/react/components/native/index.js, react/features/conference/components/Conference.native.js, react/features/conference/components/styles.js, react/features/large-video/components/LargeVideo.native.js, react/features/welcome/components/LocalVideoTrackUnderlay.native.js, react/features/welcome/components/styles.js
PR early, PR often!
I'm seeking some early feedback, this PR has some rough edges (I'll make a self-review highlighting them). 
Here is how it looks:
=> [RN] Show gray overlay when participant's connection is interrupted

react/features/base/conference/actions.js
Make sure participants in the redux store have updated names.
This will be needed for showing avatars with user initials.
=> fix(display-name): listen for display name changes

modules/UI/videolayout/SmallVideo.js
Shared video (youtube videos) do not have indicator icons about
dominant speaker and raised hand. Add a check to see if the
indicator icon container exists before trying to attach react
icons to it. The error thrown didn't seem to be causing any
UI issues though.
While this truthy check before doing ReactDOM.render seems
like it should be a general practice, I'm hesistatnt to make
the change broadly because it hasn't been a problem so far.
=> fix(filmstrip): prevent error on updating indicators for shared video

react/features/base/participants/functions.js
Relies on https://github.com/jitsi/jitsi-meet/pull/2289 to have web passing in names to get initials. Relies on https://github.com/jitsi/jitsi-meet/pull/2309 to have mobile updating redux when display names change.
The URL for the initials service is such: https://{base}/{hash for color}/{initials}/{size}/{filename}
The hash looks like it can be arbitrary although docs say to use a hashed email. The size specified in the pull request is the one currently used for gravatars. The filename can be whatever but the service returns a png.
A couple decisions to agree on:
- What to do when there is no name. Currently a space is used so that the api at least does not error and returns an image with color and no initials.
- How complex to the make parsing the initials. Currently it is done simple …
=> feat(avatars): use initials service for getting images

css/_toolbars.scss, react/features/toolbox/components/StatelessToolbarButton.js, react/features/toolbox/components/ToolbarButton.web.js
The inline classes for the toolbars were re-arranged
to fix non-rounded corners in the always-on-top window's
toolbar. However, those classes were also used by the
torture tests as a way to find stable elements that will
not get blown away by a react re-render. So re-wrap the
buttons with a div that will not get blown away,
add back the inline classes to those divs, and change
the CSS to round the corners in the always-on-top
window's toolbar.
=> ref(toolbar): re-wrap buttons for torture tests

react/features/base/participants/functions.js
There is more avatar work coming down the line for mobile,
which should also affect web, assuming the same getAvatarURL
helper will be used. As such, instead of continuing to
support the initials service and tweaking UI, revert to
make way for the future avatar work.
This reverts commit 2ea5ad68a50095302c8142cdf010f04cd3be63f6.
Heads up, @zbettenbuk. All previous work done for using the avatar initials service was to get web using the same path as mobile, which is to pass the redux participant into getAvatarURL. The last bit was simply swapping out the default abotars url with the initials service, and that swap is being reverted.
=> Revert "feat(avatars): use initials service for getting images (#2312)"

react/features/recent-list/functions.js
Adds proper locale support to MomentJS date formatter. Supports all languages that Jitsi Meet supports, except 'oc'. For proper support of locales on Android this pull request may also be needed: https://github.com/jitsi/jitsi-meet/pull/2318
=> [RN] Add proper locale support to MomentJS

react/features/analytics/functions.js
Any failure in analytics should not prevent the natural flow of the code. Shield
the function by catching and logging any exception.
=> feat(analytics): shield sending analytics events

android/README.md, android/app/build.gradle
It was recently introduced in WebRTC, so we we need to enable it project wide.
As for what features are supportd, see:
https://developer.android.com/studio/write/java8-support.html
=> [Android] Enable Java 1.8 compatibility support

react/features/base/media/components/native/VideoTrack.js, react/features/base/media/components/native/styles.js
Android uses a SurfaceView to render video, which is not quite a View, so the
fade-in animation (which varies the opacity) doesn't work.
Instead, add an opaque black view covering the video, which transitions to
transparent. This creates much smoother transitions on Android, while behaving
the same.
In addition, I removed the flip animation for local tracks, which is no longer
used, since the camera is switched without changing tracks.
=> [RN] Make video track fade-in effect cross-platform

react/features/welcome/components/WelcomePage.native.js
Improve the experience when joining a room by removing the need to tap the join
button. The keyboard type has also been set to "go", which translated on the
builtin keyboard button label to be "go" (it's builtin, the operating system
translates it). This works on both Android and iOS.
=> [RN] Join room when pressing "go" on the keyboard

react/features/base/i18n/BuiltinLanguages.native.js, react/features/base/i18n/i18next.js
Only the first commit is necessary to fix the Android crash, but I thought I'd try to add actual internationalization support, hence commit number 2.
I'd like to hear thoughts on the implementation :-)
Here is how it looks like in Spanish screenshot is on Android, but I also tested iOS):
As you can see, dates are not translated, maybe @zbettenbuk can take a look at that.
=> [RN] Fix internationalization on mobile

modules/UI/UI.js
The current notification for starting muted is 2 minutes, which
may seem like "forever" so reduce it to dismiss faster.
For now I've reduced it to 2.5 seconds, which is the default for participant notifications.
=> fix(notifications): reduce duration of initially muted notification

ios/sdk/sdk.xcodeproj/project.pbxproj, ios/sdk/src/LaunchOptions.m, react/index.native.js
Story time.  Currently the app can be started in 4 ways:
- just tapping on the icon
- via a deep link
- via a universal link
- via the phone's recent calls list
The last 3 options will make the app join the specified room upon launch. React
Native's Linking module implements the necessary bits to handle deep or
universal linking, but CallKit is out of its scope.
In order to blend any type of app startup mode, a new LaunchOptions module (iOS
only) exports a getInitialURL function, akin to the one in the Linking module,
but taking CallKit instents into consideration. This function is then used to
make app startup with a URL consistent across all different modes.
=> [RN] Fix app startup from a CallKit intent

doc/quick-install.md
The package jitsi-meet-prosody was missing from the list of packages.
=> Update uninstall documentation.

modules/UI/UI.js, modules/UI/videolayout/LargeVideoManager.js, react/features/base/conference/middleware.js, react/features/conference/components/Conference.web.js
Destroy local tracks and also destroy large video so the
user does not wonder why camera (and mic) are still enabled
even though hangup has been pressed.
There has to be a better way to do this but it's just not coming to mel
=> fix(hangup): destroy local tracks on conference leave

modules/UI/UI.js, modules/UI/videolayout/LargeVideoManager.js, react/features/base/conference/middleware.js, react/features/conference/components/Conference.web.js
This reverts commit 88325aeef26b11f9d6dfe91aaeb550df10b53ad4.
Turns out a conference with a password triggers a failed conference
join. It's going to be tricky to decipher when to do actual
cleanup, and where to shove that code, so reverting is easier for
now.
=> Revert "fix(hangup): destroy local tracks on conference leave (#2502)"

config.js, react/features/base/config/functions.js
This allows the new bandwidth estimation jitsi-meet-torture tests to enable stats gathering (and analysis).
=> feat: Whitelists the gatherStats option.

react/features/base/lib-jitsi-meet/native/polyfills-browser.js
@zbettenbuk, here is one way to get around the issue. This solution was my initial idea, so there's probably a better iteration. The failures on react-native are happening here: https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/src/core/support.js#L14.
This will require your other fixes from what I could tell from manual testing. https://github.com/jitsi/jitsi-meet/pull/2562
=> fix(polyfills): implement createHTMLDocument for jquery

package-lock.json, package.json
Brings the following fix from jitsi/react-native-webrtc into jitsi/jitsi-meet:
WebRTC used to report createAnswer (and createOffer) NSError with key
"error". But now the key's called "NSLocalizedDescription".
Additionally, NSMutableDictionary doesn't accept nil.
=> [iOS] Fix uncaught NSInvalidArgumentException in RTCPeerConnection's createAnswer

android/README.md
The new libwebrtc.jar contains an extra unused class file, when proguard is enabled result in the following warning:
org.chromium.build.BuildHooksAndroidImpl: can't find superclass or interface org.chromium.build.BuildHooksAndroid
=> fix(android): webrtc proguard rule

debian/jitsi-meet-prosody.postinst
In https://github.com/jitsi/jitsi-meet/commit/94813bc0fda4f382f1abe2a095f9f00c4462b154#diff-6e9552c9bd8e61c8f277c21220160234
two local variables got removed (AUTH_KEY_FILE and AUTH_CRT_FILE), which are used by the sed command
below to configure the virtualhost for auth.
=> debian: fix setting the auth domain certificates

react/features/invite/functions.js
Pre-existing logic made it so numbers were assumed as valid
if no validation url was specified. To be consistent with
the validation server, the faked number should include a
+ at the beginning.
=> fix(invite): prefix a + when faking the validation response

modules/UI/videolayout/VideoContainer.js
The animation for toggling filmstrip visibility was lagging on
Safari. Even though the background video is set to hidden, it is
still causing issues. Setting the background to display none
instead does help but might interfere with animations. So instead
do the easy thing and re-use logic used for Firefox to not show
the background video.
=> fix(large-video): do not try to show background on safari with webrtc

css/_filmstrip.scss, css/_vertical_filmstrip_overrides.scss
Hardcoding an offset from the bottom of 32px causes issues in
horizontal filmstrip when there is no invite button, because
then the local video just displays 32px from the bottom as there
is no button to take up space above it. Instead leverage flex
alignments to align the bottom of the video to the bototm of
the filmstrip.
=> fix(filmstrip): fix local video alignment with no invite button

react/features/base/config/actions.js, react/features/base/config/functions.js, react/features/base/config/index.js, react/features/base/config/middleware.js, react/features/base/lib-jitsi-meet/functions.js
Moves the things around to be able to override the config with the URL
params specified in the hash part of the location URI to which the app
is navigating to.
=> ref(config): override config from URL on mobile

react/features/base/config/reducer.js
Do not take legacy property into account if there's non-legacy value.
=> fix(config): no legacy over non-legacy override

lang/main.json, react/features/base/react/components/native/NavigateSectionList.js, react/features/base/react/components/native/styles.js, react/features/calendar-sync/actionTypes.js, react/features/calendar-sync/actions.js, react/features/calendar-sync/components/MeetingList.native.js, react/features/calendar-sync/components/styles.js, react/features/calendar-sync/index.js, react/features/calendar-sync/middleware.js, react/features/calendar-sync/reducer.js, react/features/mobile/permissions/functions.js, react/features/mobile/permissions/index.js, react/features/mobile/permissions/middleware.js, react/features/welcome/components/AbstractPagedList.js, react/features/welcome/components/PagedList.ios.js
This PR reorganizes the was the calendar permission is requested (also how often the calendar is refreshed).
The new flow (only if there is no permission given yet):
- The app asks for a permission once, when the user navigates to the calendar tab
- The app will not ask again for the permission in the same session until the app is closed or is put in the background - unless the user performs a pull-to-refresh operation.
- If the app is started again, or has been brought back from background, and the user navigates to the calendar tab, it'll ask for a permission again.
- On iOS, once denied, we cannot re-ask for a permission so an alert is displayed and the user is navigated to the settings screen to manually approve the permission.
- The calendar is re-synced every time the user navigates …
=> Reorganize calendar access request flow

react/features/base/lib-jitsi-meet/native/polyfills-browser.js
The onPresence parsing was refactored to remove use of jQuery.
This exposed three methods not available in react-native:
ParentNode.children, ChildNode.remove, and
document.querySelectorAll. The querySelectorAll change could
be swapped for the already polyfilled querySelector, but
children and remove had to be added. The polyfills are based
on those supplied by MDN web docs, but modified to pass jitsi
linting.
=> fix(chat): polyfills for lib-jitsi-meet ChatRoom#onPresence

package-lock.json, package.json
This update is explicitly for FF screenshare and
gum retry fixes.
=> chore(deps): update lib-jitsi-meet to 6282e7a8

lang/main.json
Electron generally can bypass having to get permission for
audio and video. In the case it doesn't have it, and the
permission screen is displayed, a string should still display
prompting the user to click allow. Right now the string id
displays.
=> fix(gum): add electron string for requesting gum permissions

react/features/base/conference/actionTypes.js, react/features/base/conference/actions.js, react/features/conference/middleware.js
Being kicked out of the conference will result with a conference failed event with 'conference.kicked' reason and take the user back to the welcome page by navigating to 'undefined'.
=> feat(mobile): handle kicked out of the conference

css/_base.scss
Explicitly allow selecting (cursor highlighting) on inputs as well as textareas. On edge, the explicit declaration of textarea is needed whereas other browsers seem okay with automatically allowing input on editable fields.
=> fix(feedback): modify user-select none declaration for edge

resources/prosody-plugins/ext_events.lib.lua, resources/prosody-plugins/mod_muc_call.lua
When combined with mod_muc_poltergeist mod_muc_call allows
for enabling call features using a proper ext_events.lib.lua
implementation. By default when the module is configured only
stub implementations are used for ext_events.lib.lua as these
are unique between deployments.
=> Adding a prosody module to support sip-style call flows.

package-lock.json, package.json
Note: The commit used is from a forked repo that is not yet merged on the new source for this RN component,  eventually we should be consuming from this repo instead https://github.com/joltup/react-native-fetch-blob
=> Update RNFetchBlob to fixes issues with calling UI API in background thread

modules/UI/shared_video/SharedVideo.js, modules/UI/videolayout/Filmstrip.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/VideoLayout.js
jquery animate during animations sets an element's overflow to
hidden and then back to the overflow declared before the start
of the animation. If multiple animations are fired, then the
overflow could be set to hidden permanently. No calls
to Filmstrip#resizeThumbnails have animate set to true, so the
animate call is not even needed.
=> fix(filmstrip): set SmallVideo styles instead of using animate

react/features/app/actions.js, react/features/base/media/middleware.js, react/features/base/profile/functions.js, react/features/base/profile/index.js
This change separates handling of config and profile and avoids merging it on app navigate. There is a new generic function to retrieve URL/profile/config values with (overridable) precedence.
Question: Where should this function be? Currently it's in base/profile, but I have the feeling it doesn't belong there.
=> Separate handling config and profile with precedence

react/features/base/tracks/actions.js, react/features/base/tracks/functions.js, react/features/base/tracks/middleware.js
The _setMuted method in a corner case was making an attempt to create second video track, because it was not taking pending tracks into account.
=> fix: local track for video already exists

css/_toolbars.scss, react/features/always-on-top/AlwaysOnTop.js, react/features/always-on-top/ToolboxAlwaysOnTop.js, react/features/toolbox/components/ToolbarButton.web.js
Cleanup of CSS and unused old toolbar components to be done in a separate PR immediately after this PR gets merged. At least the following will be removed:
- .toolbar related styling in toolbars.scss
- StatelessToolbar
- StatelessToolbarButton
- ProfileButton.web.js (didn't get removed in previous cleanup passes)
There's probably straggling old toolbar logic and styling that will also need to be tracked down and removed.
=> ref(always-on-top): refactor to stop using old toolbar components

css/modals/invite/_info.scss
The call url is an anchor element so that right clicking it
can bring up the copy link option in the context menu.
Clicking on it does a no-op so the anchor was colored to
look like plain text. Hovering over it right now makes it
look like an anchor due to some atlaskit color, so supress
the coloring.
=> fix(info): hide anchor hover colors for the call url

react/features/recording/components/LiveStream/StartLiveStreamDialog.web.js, react/features/recording/googleApi.js
Only "persistent" broadcasts were being fetched using the
YouTube API. Fetching "all" will get persistent broadcasts
and events. If events use a custom encoder then the stream
key can be obtained. If google hangouts is used for the event
then a stream key will not be obtainable; in those cases
input empty string as the stream key.
=> fix(recording): fetch events also for available broadcasts

react/features/recording/components/LiveStream/StreamKeyForm.web.js
I didn't bother turning off autocomplete. I think it might be useful.
=> fix(recording): do not spell check stream key input

modules/keyboardshortcut/keyboardshortcut.js
When processing keyboard events for keyboard shortcuts,
if the value of an event's "key" attribute is "Unidentified",
the event should be further processed instead of the "key"
being returned to be mapped to a registered keyboard shortcut.
This occurs on edge, where question mark has the key
"Unidentified" but has the proper keyCode of 191.
=> fix(keyboard-shortcuts): process Unidentified keys

css/_toolbars.scss
The chat counter needs to be moved out of the way of the chat
button. The counter started covering the button when all the
toolbar buttons were made smaller. Also, turning off the
counters pointer events should at least make the button
clickable if this ever happens again.
=> fix(toolbar): move chat counter and stop its pointer events

css/_toolbars.scss
There is a slight moment when the recording icon is loading that
its container does not have width. Set the width of the container
so it doesn't collapse. Also, push it a little to the right so
it aligns better with other icons.
=> fix(toolbar): set recording icon size to prevent resizing flash

android/sdk/src/main/java/org/jitsi/meet/sdk/PictureInPictureModule.java, react/features/mobile/picture-in-picture/actions.js
Activity.enterPictureInPictureMode can fail for a couple of reasons
mentioned in the JSDoc:
"The system may disallow entering picture-in-picture in various cases,
including when the activity is not visible, if the screen is locked or
if the user has an activity pinned."
It seems to be safe to assume that those cases will be caught by
a RuntimeException handler (only RuntimeExceptions can be left without
explicit catch block).
Anyway the root cause for problems is the fact that the current process
for going to the picture in picture mode is not synchronised with
Activity's lifecycle. On Activity's "userLeaveHint" callback we dispatch
async task to the JS code which only then after dispatching some more
stuff eventually call native method that enter PiP. In case we spend too
much time on …
=> fix(PictureInPictureModule): prevent IllegalStateException when going PiP

modules/util/JitsiMeetInMemoryLogStorage.js, react/features/base/logging/middleware.js
Enabling it only when config.debug is set, a configuration provided by jitsi-meet-torture.
=> Adds in memory log storage, to be used while testing.

react/features/filmstrip/components/Filmstrip.native.js, react/features/filmstrip/components/LocalThumbnail.js, react/features/filmstrip/components/styles.js
This is a separation of the local thumbnail and the remote thumbnails. The local thumbnail is still rendered inside the filmstrip, but not in the scrollable area, so it can be physically separated in a later stage.
=> Separate local thumbnail in filmstrip

react/features/invite/components/index.js
The app will crash with react complaining about not a component being passed to render method.
=> fix(invite): check Toolbox render method error

react/features/base/lib-jitsi-meet/native/polyfills-browser.js
Native app shows "Can't find variable: DOMParser" in _connect_cb_wrapper in lib-jitsi-meet.min.js when connected to an Openfire server that we established.
Make DOMParser globally to resolve this problem
=> fix error "Can't find variable: DOMParser" in _connect_cb_wrapper

conference.js
When closing and reopening a notebook, the browser will fire
a devicechange event. This event should not be listened to
after hangup because the current listener will call gum if
there is no current audio/video, which is the case after
hangup.
Initially this change was going to be remove all conference
listeners but then I noticed that the listener for devicechange
is set differently. It might be worthwhile future work, although
potentially unnecessary right now, to ensure all listeners
registered in conference.js are properly cleaned up on hangup.
=> fix(hangup): remove device change listener

interface_config.js, modules/UI/videolayout/VideoContainer.js, react/features/large-video/components/LargeVideoBackground.web.js, react/features/large-video/components/LargeVideoBackgroundCanvas.web.js, react/features/large-video/components/index.js
To reduce the amount of motion that has to be blurred, use a canvas
to essentially set the FPS of the video background. This canvas
component is behind a temporary feature flag, as well as being able
to disable the blur, so it can be played around with on deployed
environments.
Also, the intent is not to keep both the video blur and the canvas blur
but to debug and choose which direction to go.
=> feat(large-video): background blur through canvas and feature flag

react/features/always-on-top/ToolboxAlwaysOnTop.js
To be consistent with how the main window toolbar has audio mute,
hangup, and then video mute.
=> fix(always-on-top): change button order

css/_base.scss
I'm unsure why all textareas need overflow hidden. Doing so
essentially overrides what I would expect to be standard textarea
behavior. I would rather remove the reset and fix any areas that
have issues.
=> fix(feedback): remove textarea overflow hiding to allow scrolling

react/features/app/functions.any.js, react/features/app/functions.native.js, react/features/app/functions.web.js, react/features/invite/functions.js, react/features/invite/middleware.native.js, react/features/mobile/external-api/middleware.js, react/features/mobile/picture-in-picture/actions.js, react/features/mobile/picture-in-picture/components/EnterPictureInPictureToolbarButton.js, react/features/welcome/functions.js
If multiple JitsiMeetView instances are created (not necessarily
existing at once), it's possible to hit a TypeError when reading the
React Component props of the currently mounted App. Anyway, in certain
places we're already protecting against that out of abundance of caution
so it makes no sense to not protect everywhere.
=> [Android] Fix possible TypeError in multi-JitsiMeetView SDK consumers

ios/travis-ci/build-ipa.sh
It needs to be global and the old replace seems to escape only the first occurrence.
I've found this on the internet and it handles more cases.
=> fix(ios,build-ipa.sh): lib-jitsi-meet package sed escape

react/features/toolbox/components/Toolbox.web.js
If authenticated using JWT, don't show the profile button but
do show it if a guest.
=> fix(toolbar): show profile button if guest

react/features/base/dialog/components/BottomSheet.native.js
One has to be explicit on iOS, otherwise it seems to be locked to portrait only.
=> [RN] Support landscape and portrait orientations in BottomSheet

ios/sdk/sdk.xcodeproj/project.pbxproj
It significantly speeds up debug builds, putting them on par with Android, where
we also don't bundle the React resources.
=> [iOS] Don't bundle the React resources in Debug mode

react/features/conference/components/styles.js, react/features/toolbox/components/native/Toolbox.js, react/features/toolbox/components/native/styles.js
- add 10px of padding on the sizes of the toolbar
- make the button margin smaller (from 10 to 7)
- increate the secondary button factor to 85%, thus rising the maximum secondary
button size to 50 (from the previous 48)
=> [RN] Adjust toolbar button sizes / margins

css/_videolayout_default.scss, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/VideoLayout.js
Instead of using JS, just use CSS 100% width and height. This
also resolves a jitter that occurs on edge when a modal's
container appends to the body.
=> ref(layout): use css to make video layout containers fit window

react/features/conference/components/Conference.native.js, react/features/toolbox/components/native/Toolbox.js, react/features/toolbox/components/native/styles.js
Wait until the right button size has been calculated before rendering it.
=> [RN] Avoid Toolbox changing size on first render

ios/sdk/sdk.xcodeproj/project.pbxproj
Thsi fixed a regression in https://github.com/jitsi/jitsi-meet/commit/8f75c2e279911f2859eba394cfd84a5068eb8323
The bundler script doesn't do anything (it literally exits right at the top)
when skipping the bundle. This is arguably wrong, because it doesn't generate
"ip.txt", the file with the bundler IP address either!
So, generate that ourselves. While ding this, also drop the need for xip.io,
which has also been removed from RN, since it gives more trouble than it solves.
=> [iOS] Fix running in Debug mode on a device

react/features/base/connection/actions.native.js
After the connection is established, it can either be properly disconnected or
fail. We need to make sure to be listening for events for either.
=> [RN] Fix handling XMPP connection failures

react/features/app/actions.js, react/features/base/config/actionTypes.js, react/features/base/config/actions.js, react/features/base/config/reducer.js, react/features/mobile/external-api/middleware.js
This fix is based on storing the location URL object we are loading the
configuration for in the redux store. Once the config has been loaded (or it has
failed, for that matter!) we'll check if the current "config URL" is the same we
set, and discard the old one if they don't match.
=> [RN] Fix processing outdated loadConfig requests

react/features/base/config/functions.js, react/features/base/media/components/native/VideoTransform.js, react/features/mobile/callkit/middleware.js
Add ability to provide a display name in the configOverwrite object, that when available, it will be used to customize the name of the meeting in callkit screen and recent call list.
=> Callkit use displayName from config

react/features/base/conference/reducer.js
Simplify parts of the logic introduced in
11b7144ad004118a3fa8904458733b3c6c317448.
Specificaly, using all the state change avoiding functions doesn't give us much
since we need to copy the state for sure.
=> ref(base/conference): simplify code

conference.js, react/features/base/conference/actions.js, react/features/base/label/components/AbstractCircularLabel.js, react/features/base/label/components/CircularLabel.native.js, react/features/base/label/components/CircularLabel.web.js, react/features/base/label/components/styles.js, react/features/base/styles/components/styles/ColorPalette.js, react/features/conference/components/Conference.native.js, react/features/conference/components/ConferenceIndicators.native.js, react/features/conference/components/styles.js, react/features/recording/components/AbstractRecordingLabel.js, react/features/recording/components/RecordingLabel.native.js, react/features/recording/components/RecordingLabel.web.js, react/features/recording/components/styles.js, react/features/recording/index.js, react/features/recording/middleware.js, react/features/video-quality/components/AbstractVideoQualityLabel.js, react/features/video-quality/components/VideoQualityLabel.native.js, react/features/video-quality/components/VideoQualityLabel.web.js, react/features/video-quality/components/styles.js
Initial commit covering:
- Generic implementation of CircularLabel that web uses, reusing as much code as possible
- Audio only indicator following web's way of indicators
Please note, further status indicators to come in this PR, hence the general title
=> [RN] Status indicators

resources/prosody-plugins/util.lib.lua
The current poltergeist http api immediately returns
and does not wait for async work in the handler to finish. This
mostly occurs when a public asap key needs to be fetched due
to a cache miss. The fix implements the strategy described at
https://prosody.im/doc/developers/http.html
=> Fixing an issue with asnyc http request handlers.

conference.js, modules/FollowMe.js, modules/UI/UI.js, modules/UI/shared_video/SharedVideo.js, modules/UI/shared_video/SharedVideoThumb.js, modules/UI/videolayout/LocalVideo.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/SmallVideo.js, modules/UI/videolayout/VideoLayout.js, react/features/app/components/App.web.js, react/features/base/participants/middleware.js, react/features/video-layout/index.js, react/features/video-layout/middleware.web.js
This is in an effort to get VideoLayout subscribing to redux updates so that it can have its state retrieved from redux. This way all calls to VideoLayout#updateLargeVideo can happen after redux state has updated and large-video has been selected in redux.
=> ref: remove some direct manipulation of VideoLayout

resources/prosody-plugins/mod_muc_call.lua, resources/prosody-plugins/mod_muc_poltergeist.lua
Previously a new call id was generated for INVITE and CANCEL.
Now the id generated during the initial INVITE will be used for
corresponding CANCEL events. Also, adding the ability to
trigger a call cancel via the poltergeist update api.
=> Properly propagating call id for call response handling.

ios/sdk/src/JitsiMeetView.m, ios/sdk/src/invite/InviteController+Private.h, ios/sdk/src/invite/InviteController.m
The `inviteModule` property is a weak reference and was being cleared after the first time an user joined a call in a JitsiMeetView. This PR fixes this by injecting the RNBridgeWrapper to the `InviteController` and query for the module any time we want access to it instead of passing the module on initialization.
=> [iOS] Fix issue with Invite RNModule being nil after first time joining call

ios/sdk/src/callkit/JMCallKitEmitter.swift, ios/sdk/src/callkit/JMCallKitListener.swift
Adding missing framework version checks for CallKit proxy components in the iOS Jitsi Meet SDK. This will enable the SDK to be able to compile with iOS 9.3 as deployment target again.
=> [iOS] Fix JitsiMeet SDK  to be able to compile with iOS 9.3

resources/prosody-plugins/mod_muc_call.lua, resources/prosody-plugins/mod_muc_poltergeist.lua
We do not want to send a cancel when we are notified of a ringing device. Also, all tags should propagate in a presence stanza when it is updated.
=> Cleaning up call flow presence stanzas and cancel triggers.

lang/main.json, react/features/always-on-top/AudioMuteButton.js, react/features/always-on-top/HangupButton.js, react/features/always-on-top/VideoMuteButton.js, react/features/base/toolbox/components/AbstractAudioMuteButton.js, react/features/base/toolbox/components/AbstractHangupButton.js, react/features/base/toolbox/components/AbstractToolboxItem.js, react/features/base/toolbox/components/AbstractVideoMuteButton.js, react/features/base/toolbox/components/ToolboxItem.native.js, react/features/base/toolbox/components/ToolboxItem.web.js, react/features/invite/components/InfoDialogButton.web.js, react/features/invite/components/InviteButton.native.js, react/features/mobile/audio-mode/components/AudioRouteButton.js, react/features/mobile/picture-in-picture/components/PictureInPictureButton.js, react/features/room-lock/components/RoomLockButton.js, react/features/settings/components/web/SettingsButton.js, react/features/toolbox/components/AudioMuteButton.js, react/features/toolbox/components/HangupButton.js, react/features/toolbox/components/VideoMuteButton.js, react/features/toolbox/components/native/AudioOnlyButton.js, react/features/toolbox/components/native/OverflowMenuButton.js, react/features/toolbox/components/native/ToggleCameraButton.js, react/features/toolbox/components/web/OverflowMenuButton.js, react/features/toolbox/components/web/OverflowMenuLiveStreamingItem.js, react/features/toolbox/components/web/OverflowMenuProfileItem.js, react/features/toolbox/components/web/Toolbox.js, react/features/video-quality/components/OverflowMenuVideoQualityItem.web.js, react/features/welcome/components/WelcomePage.native.js
As accessibility labels are likely to be used by assistive technologies (screen readers, text-to-speech software, speech recognition software, etc), it is desirable to have accessibility labels available in the native language of the end user. As such, their values should be translatable.
This PR replaces most* hard-coded English values for accessibility labels with a lookup through the translation mechanism.
I've rebuild the SDK using this fix, and tested a simple Android app on a device that depends on speech recognition, with very nice results.
\* The always-on-top components are excluded
=> fix(i18n) Accessiblity labels translations

react/features/conference/components/Conference.native.js
This commit hides the conference indicators from the reduced UI. I think the indicators don't belong to the reduced UI, that is only to see a video (or maybe the active speaker).
For later: Extending the thumbnail indicators and render them in PiP may be a good idea, but we don't have thumbnail indicators in PiP mode at all right now.
=> [RN] Hide conference indicators on reduced UI

react/features/base/config/functions.js, react/features/mobile/callkit/middleware.js
Implement a variable in configOverwrite that a consumer of the SDK can provide when in need to customize the handle for CallKit.
=> [RN] Allow to override callHandle for CallKit

css/_toolbars.scss
Maybe there is a case that can be triggered somehow where
the toolbar becomes off center.
=> fix(toolbar): ensure centered toolbar

ios/Podfile.lock, package-lock.json, package.json
Turns out sometimes a calendar is missing the tile and it crashes because nil is
inserted into a NSDictionary. Fix it by applying this pending PR:
https://github.com/wmcmahan/react-native-calendar-events/pull/164
=> [iOS] Fix crash on startup when fetching calendar entries

.gitignore
They are automatically created by precommit-hook:
https://github.com/nlf/precommit-hook/blob/362a2024982af1986ccb4c332b9642b3a58f9672/bin/install#L5-L6
=> misc: ignore jshint files

README.md, package-lock.json, package.json
The new npm version updates the package-lock to a slightly different format that causes unnecessary modifications every time a dev issues "npm install".
Also added the npm engine dependency which does nothing directly, but gives a hint of what's required for the project.
Edit: Also make node engine version match to what the readme says.
=> Update npm version and package-lock

react/features/large-video/middleware.js
In the current middleware logic, when the local participant becomes
dominant speaker, a new participant can be selected to receive
high quality video from. This means large-video could potentially
do a switch to another participant when the local participant
becomes dominant speaker. Prevent such behavior.
=> fix(large-video): do not reselect video on self dominant speaker

ios/app/src/Info.plist, lang/main.json, react/features/base/react/components/native/AbstractPagedList.js, react/features/base/react/components/native/PagedList.android.js, react/features/calendar-sync/actions.js, react/features/calendar-sync/components/MeetingList.native.js, react/features/calendar-sync/components/styles.js, react/features/calendar-sync/reducer.js, react/features/mobile/callkit/middleware.js, react/features/welcome/actionTypes.js, react/features/welcome/actions.js, react/features/welcome/components/WelcomePageLists.js, react/features/welcome/reducer.js
Changes:
- The defaul tab logic is not the other way 'round: if the recent list is empty, the calendar tab is default
- The app persists the user's last tab and will use that as default for later
Requires https://github.com/jitsi/jitsi-meet-torture/pull/192 which deals with the Calendar permission prompt which appears on startup after this PR defaults to the Calendar tab.
=> [RN] Change default WelcomeScreen tab and persist user choice

react/features/base/conference/middleware.js
On web CONFERENCE_FAILED handlers are not setting the 'recoverable' flag thus any middleware which rely on those should not execute on web.
=> fix(base/conference): do not execute leave conference on web

css/_base.scss
This is needed for newer versions of electron that might
use the iframe integration of jitsi-meet. Newer versions
seem to have some kind of regression with setting height
and width to 100%.
=> ref(css): add height/width reset for html tag

ios/sdk/src/callkit/CallKit.m, ios/sdk/src/callkit/JMCallKitEmitter.swift, ios/sdk/src/callkit/JMCallKitProxy.swift, react/features/mobile/callkit/middleware.js
Fix the "mute ping pong" for once and for all. This patch takes a new approach
to the problem: it keeps track of the user generated CallKit transaction ations
and avoids calling the delegate method in those cases.
This results in a much cleaner and easier to understand handling of the flow: if
the delegate method is called it means the user tapped on the mute button. When
we sync the muted state in JS with CallKit the delegate method won't be called
at all, thus avoiding the ping-pong altogether.
=> [iOS] Fix syncing muted state with CallKit

react/features/base/conference/actions.js, react/features/base/media/components/AbstractAudio.js, react/features/base/media/components/native/Audio.js
This is required for "call flows". I added presence state handling, since that is also required and was not being handled.
How to test this:
- join a meeting on Stride
- join that meeting on Jitsi Meet using the URL
- invite someone else using Stride
- hear the looping ringtone
Tested:
=> Mobile looping sounds

modules/UI/videolayout/SmallVideo.js
When in audio only, the video should not be shown and instead the
avatar should display.
=> fix(filmstrip): do not show video for large video speaker in audio only

conference.js, modules/UI/UI.js, modules/UI/videolayout/VideoLayout.js, react/features/video-layout/middleware.web.js
- Instead of having 4 listeners for local connection status
updates and 1 for remote, remove two of the redundant listeners.
- Instead of calling into 4 separate VideoLayout methods to update a
participant's connection status, expose one handler.
=> ref(video-layout): consolidate connection status update handling

react/features/overlay/actionTypes.js, react/features/overlay/actions.js, react/features/overlay/components/AbstractPageReloadOverlay.js, react/features/overlay/components/PageReloadOverlay.native.js, react/features/overlay/index.js, react/features/overlay/middleware.js, react/features/overlay/reducer.js
The only effect of this PR currently will be the catch all role of the reload screen. It will still not appear on the SDK client apps, because the fatal events will go through.
=> [RN] Reload screen a catch all

react/features/calendar-sync/constants.js, react/features/calendar-sync/functions.js, react/features/calendar-sync/index.js, react/features/calendar-sync/reducer.js
This commit adds a state getter that considers checking the enabled/disabled state of the calendar feature, so then other features don’t have to do it manually.
=> Calendar feature disabled state getter

config.js, connection.js, react/features/analytics/AnalyticsEvents.js, react/features/app/actions.js, react/features/base/conference/middleware.js, react/features/base/connection/actionTypes.js, react/features/base/connection/actions.native.js, react/features/base/connection/reducer.js, react/features/overlay/actions.js, react/features/overlay/components/AbstractPageReloadOverlay.js, react/features/overlay/components/PageReloadOverlay.native.js, react/features/overlay/components/ReloadButton.js
There isn't an explicit way to know when a split brain
scenario has happened. It is assumed it arises when an
"item-not-found" connection error is encountered early
on in the conference. So, store when a connection has
happened so it be calculated how much time has
elapsed and if the threshold has not been exceeded
then do an immediate reload of the app instead of
showing the overlay with a reload timer.
=> fix(connection): reload immediately on possible split-brain

modules/UI/videolayout/VideoLayout.js
When replace track is called in JitsiConference, there is no
guarantee a videoType update will come in presence before
the track added event. This can lead to the situation in
LargeVideoManager where an update is called with a track
with an undefined videoType.
=> fix(video-layout): handle undefined video type for large video update

react/features/base/storage/PersistenceRegistry.js
Persistency had a bug that could happen if the redux subtree had some field with default values (e.g. arrays) that we expected in the app to be not null or undefined. If in this case the Persistency layer persisted the subtree, but not that field with a default value, then when it was rehydrated, the default state was not considered and we could run into issues there.
Example: ```'features/recording'``` subtree has a default state
```
{
sessionDatas: []
}
```
Now a new key came in called ```streamKey``` and ```PersistencyRegistry``` was set up to persist with the following config:
```
{
sessionKey: true
}
````
Now when the subtree got hydrated, it only restored the ```sessionKey``` field, and the ```sessionDatas``` became undefined, and caused some type errors.
=> Fix persistency to handle default values too

conference.js
It can be that deviceChangeListener is never defined because
the isDeviceList call never completes. On hangup, that would
cause an error to be thrown within lib-jitsi-meet because of
an attempt to remove an undefined event handler. That is
what happens on Safari right now.
=> fix(hangup): truthy check for deviceChangeListener before removing it

react/features/base/react/components/native/AbstractPagedList.js, react/features/calendar-sync/actionTypes.js, react/features/calendar-sync/actions.js, react/features/calendar-sync/components/MeetingList.native.js, react/features/calendar-sync/middleware.js
This PR changes the way the calendar permission is asked. It now only asks if the calendar refresh is the result of a direct user interaction (e.g. change welcome screen tabs, or refresh calendar list), but will no ask for permission if the calendar tab is rendered default on application startup
=> [RN] Only ask for calendar permission on user interaction

resources/prosody-plugins/ext_events.lib.lua, resources/prosody-plugins/mod_muc_call.lua
There were tabs in ext_events.lib.lua previously that I have cleaned up now.
=> feat(calls): Adding missed call event triggering.

config.js
This needs to go in first: https://github.com/jitsi/lib-jitsi-meet/pull/782
Why this? Well, we switched to 1080 for the new gum flow (which IMHO was a mistake) and then reconfigured all our deployments back to 720p. Let's keep defaults sane and reasonable.
=> config: default to 720p

.flowconfig, ios/Podfile, ios/Podfile.lock, package-lock.json, package.json, react/features/welcome/components/WelcomePage.native.js
It will only be requested if a user joins a meeting or flips the switch from
video to audio and back, but never as the first thing when the welcome page is
mounted.
=> [RN] Don't request camera permission on first launch

package-lock.json, package.json
This version or react-native-webrtc uses a worker queue for all WebRTC operations in iOS.
=> [RN] Update RN webrtc. 

conference.js, modules/UI/videolayout/VideoLayout.js, react/features/large-video/actions.js, react/features/large-video/middleware.js, service/UI/UIEvents.js
Currently native/middleware/redux has its own logic for selecting a participant
on the bridge. To have the logic web respect that logic, a few changes are
needed.
- Web no longer has its own call to selectParticipant.
- To keep in line with web logic selectParticipant action should act even when
there is no track. This makes it so that when a participant does get a track
that the bridge will send high quality. The bridge can already handle when the
selected participant does not have a video track.
- The timing of web is such that on joining an existing conference, a
participant joins and the participant's tracks get updated and then the
conference is joined. The result is selectParticipant does not get fired
because it no-ops when there is no conference. To avoid having to make
uncertain …
=> ref(large-video): combine selectParticipant logic from web

react/features/conference/components/Conference.web.js, react/features/conference/components/Notice.web.js, react/features/conference/components/index.js
* get back the Notice class
* add Notice component in the Conference web view
This patch is partially based in the removed logic included originally
in:
commit 59a74153dc9ec0432cbc6f1fac5ef9c1b3566cd4
(tag: jitsi-meet_1886, tag: jitsi-meet_1885, tag: 1797, tag: 1796)
Author: Ilya Daynatovich <shupuercha@gmail.com>
Date:   Mon Mar 20 11:04:54 2017 -0500
Toolbar notice as React Component
Signed-off-by: Pablo Saavedra <psaavedra@igalia.com>
=> noticeMessage is not shown (refs #3295)

css/filmstrip/_vertical_filmstrip.scss, modules/UI/UI.js, react/features/conference/components/Conference.web.js
Instead of apply the layout class to the body, it can be
applied to Conference. This will allow easier switching
between tile filmstrip and horizontal/vertical filmstrip.
=> ref(filmstrip): apply filmstrip class to Conference root

modules/UI/shared_video/SharedVideoThumb.js, modules/UI/videolayout/RemoteVideo.js, react/features/filmstrip/components/web/Filmstrip.js
This might be necessary for tile view. To support making the
local video display at the end of remote videos while in tile
view, but separateed from scrollable remote videos, moving
the local video might be necessary. By creating an empty
container, there is a target for local video to move to.
=> ref(filmstrip): create an empty container for local filmstrip move

react/features/mobile/audio-mode/middleware.js
When a call is tarted in audio only mode due to the switch on the welcome page,
the wrong audio mode was chosen.
=> [RN] Fix setting audio mode for audio-only calls

conference.js, react/features/base/devices/actionTypes.js, react/features/base/devices/actions.js, react/features/base/devices/middleware.js, react/features/base/devices/reducer.js, react/features/base/dialog/components/DialogWithTabs.web.js, react/features/base/settings/reducer.js, react/features/device-selection/actions.js, react/features/device-selection/components/DeviceSelection.js, react/features/settings/components/web/SettingsDialog.js, react/features/settings/functions.js, react/features/welcome/components/WelcomePage.web.js, service/UI/UIEvents.js
- Create a getter for getting a settings tab's props so the device
selection tab can get updated available devices.
- Be able to call a function from a tab after it has mounted. This is
used for device selection to essentially call enumerateDevices on
the welcome page so the device selectors are populated.
- Remove event UIEvents.AUDIO_OUTPUT_DEVICE_CHANGED. Instead directly call
setAudioOutputDeviceId where possible.
- Fix initialization of the audioOutputDeviceId in settings by defaulting
the audio output device to the one set in settings.
=> feat(welcome-page): be able to open settings dialog

react/features/app/components/App.native.js
The new google-api feature was not referenced anywhere on mobile since the refactor, and opening the start dialog failed when the abstract class tried to access the feature's Redux state
=> [RN] Fix streaming on mobile

react/features/subtitles/middleware.js
Due to e2e also using json messages for sharing stats, this was broken due to merging https://github.com/jitsi/jitsi-meet/pull/3276 .... my bad :(
=> fix: only access nested json values when corrent payload type

conference.js
This changes a log message from “initialized with %s local tracks 2” to “initialized with 2 local tracks”.
=> Log the amount of local tracks properly

css/_transcription-subtitles.scss, react/features/subtitles/components/TranscriptionSubtitles.web.js
- Increase z-index so the subtitles display over tiles.
- Add a background to the subtitle text.
- In general make the subtitles narrower.
=> fix(subtitles): adjust styling for tile view

react/features/app/actions.js
Your truly refactored routing in https://github.com/jitsi/jitsi-meet/pull/3222
and broke it. When a bare room is entered the pathname was not updated when
applying the default URL.
=> Fix processing context root

react/features/base/connection/actions.native.js, react/features/base/connection/reducer.js
If a relative BOSH URL is found (as docker-jitsi-meet does) construct a full URL
based on the location URL and context root.
Also remove some default options since we need the config file anyway, so I see
no point in doing the extra work.
=> [RN] Fix normalizing BOSH URLs

react/features/base/lib-jitsi-meet/native/polyfills-browser.js
- navigator.{platform,plugins} were needed by the no longer existing screenshare
adapter
- document.implementation is already polyfilled by xmldom
=> [RN] Remove no longer needed polyfills

react/features/toolbox/components/web/OverflowMenuProfileItem.js
The current code was splitting it on a space, which made nicknames such as “Link Mauve” appear as “Link”, whereas it gets displayed correctly everywhere else in the UI.
=> Display the correct display name in the menu

conference.js, modules/UI/videolayout/VideoContainer.js, modules/util/TaskQueue.js, modules/util/helpers.js
Multiple replaceLocalTrack calls can be fired at the same time. If no local track is present, then the replaced track will be null, and this can cause multiple local tracks of the same type to be added (because null is being replaced). So queue calls to the method. Two other issues emerged while looking into this issue:
- When local audio/video is created due to the participant having null tracks and plugging in a device, a media track is created, used in the SDP, and then muted, which can cause a flash of the participant being visible/audible. Get around this by muting the track before using it.
- VideoContainer, which is used to display the video element in large video, has an instance variable of isVisible initially set to false, but actually nothing is setting the large video to be …
=> Queue replaceLocalTrack

css/_navigate_section_list.scss
Long meeting titles and urls can force text outside of the
tile.
=> fix(calendar): allow text to wrap and grow tile

react/features/base/react/components/AbstractContainer.js, react/features/base/react/components/native/Container.js, react/features/base/react/components/web/Container.js, react/features/conference/components/Conference.native.js, react/features/filmstrip/components/native/Thumbnail.js, react/features/filmstrip/components/native/TileView.js, react/features/filmstrip/components/native/index.js, react/features/filmstrip/components/styles.js, react/features/large-video/components/LargeVideo.native.js, react/features/toolbox/components/native/OverflowMenu.js, react/features/video-layout/components/TileViewButton.js, react/features/video-layout/functions.js
- Create a tile view component for displaying thumbnails in a
two-dimensional grid.
- Update the existing TileViewButton so it shows a label in the
overflow menu.
- Modify conference so it can display TileView while hiding
Filmstrip.
- Modify Thumbnail so its width/height can be set and to prevent
pinning while in tile view mode.
=> feat(tile-view): initial implementation for mobile

lang/main.json, package-lock.json, package.json, react/features/connection-indicator/components/ConnectionIndicator.js, react/features/connection-indicator/statsEmitter.js, react/features/connection-stats/components/ConnectionStatsTable.js
and the number of (media) servers in the stats panels.
=> Displays the region participants are connected to

.travis.yml
This is a workaround suggested by Travis support to workaround the
"The job exceeded the maximum log length, and has been terminated."
error.
Another option would be to upload the logs somewhere, but actually it
might be more convenient not having to scroll down all those logs. We
can revisit this case if some problems will be encountered (like for
example if there's need to see something in the middle).
=> fix(travis): tail last 500 lines of logs only on failure

.travis.yml, ios/travis-ci/build-ipa.sh
This reduces 'xcodebuild' verbosity and fixed problem with exceeding 4MB of logs size imposed by Travis CI.
=> fix(Travis/iOS): use '-quiet' with 'xcodebuild' commands

doc/quick-install.md
Recent Ubuntus come with only main repositories enabled. See #3427.
=> doc: add ubuntu universe repo note to quickinstall

react/features/conference/components/Conference.native.js
The NotificationsContainer was mounted twice, probably after a merge
=> [RN] Fix duplicated notifications

ios/README.md, ios/sdk/src/JitsiMeetView.h, ios/sdk/src/JitsiMeetView.m
Make sure both methods offer the same behavior and mark the old one as
deprecated so SDK users get a warning.
=> [iOS] Unify openURL methods and mark the old one deprecated

ios/sdk/src/dropbox/Dropbox.m
When a native iOS module implements `constantsToExport` it must define
`requiresMainQueueSetup`. In this case we don't do any UI stuff so it doesn't
need to be initialized in the main thread.
=> [iOS] Fix warning

react/features/recording/components/AbstractRecordingLabel.js, react/features/recording/components/RecordingLabel.web.js
The issue is tackled from 2 directions:
- On web, we now only render when the status is "ON". This is equivalent to the previous mode of operation (this is the actual bugfix)
- On mobile we now have a stale status that makes the labels disappear after a while. This is necessary since we don't have notifications anymore so we need to keep the OFF label visible for a while in order to let the user tap it and learn about the new status update, if he/she wants.
=> Fix sticky recording labels

package-lock.json, package.json
None of the breaking changes seemed to affect current
usage of react-i18next and light testing of features
and language switching did not produce issues.
This update is a pre-requisite for removing deprecated react
lifecycle methods, as older versions of react-i18next
have a higher order component that uses the deprecated
componentWillMount, and that issue has been fixed since 7.8.0.
=> chore(deps): update react-i18next from 4.8.0 to 7.13.0

config.js
Fixes common problem where people following https://github.com/jitsi/jicofo#secure-domain have a syntax error, forgetting the comma after muc definition.
=> Moves muc definition to be last.

react/features/recording/components/Recording/AbstractRecordButton.js
=> Update docs for AbstractRecordButton _mapStateToProps

package-lock.json, package.json
This is required to get rid of a warning after react native update. See related commit in lib.
https://github.com/wmcmahan/react-native-calendar-events/commit/056807286da610d884fb6b4c8ca187a767b261f7
=> [RN] Update react-native-calendar-events lib

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java, ios/sdk/src/JitsiMeetView.m, react/features/always-on-top/AlwaysOnTop.js, react/features/base/dialog/components/AbstractDialog.js, react/features/base/dialog/components/StatelessDialog.web.js, react/features/base/label/components/CircularLabel.native.js, react/features/base/react/components/native/SideBar.js, react/features/base/toolbox/components/AbstractButton.js, react/features/deep-linking/components/DeepLinkingMobilePage.web.js, react/features/desktop-picker/components/DesktopPicker.js, react/features/device-selection/components/AudioInputPreview.js, react/features/device-selection/components/DeviceSelection.js, react/features/invite/components/InfoDialogButton.web.js, react/features/invite/components/info-dialog/InfoDialog.web.js, react/features/invite/components/info-dialog/PasswordForm.web.js, react/features/large-video/components/Labels.web.js, react/features/large-video/components/LargeVideoBackground.web.js, react/features/mobile/audio-mode/components/AudioRoutePickerDialog.js, react/features/recording/components/AbstractRecordingLabel.js, react/features/recording/components/LiveStream/AbstractStreamKeyForm.js, react/features/recording/components/LiveStream/native/StreamKeyForm.js, react/features/recording/components/LiveStream/web/LiveStreamButton.js, react/features/recording/components/LiveStream/web/StreamKeyForm.js, react/features/recording/components/Recording/web/RecordButton.js, react/features/speaker-stats/components/SpeakerStats.js, react/features/toolbox/components/web/Toolbox.js, react/features/welcome/components/AbstractWelcomePage.js, react/features/welcome/components/BlankPage.native.js, react/features/welcome/components/WelcomePage.native.js
The react lifecycle methods componentWillMount, componentWillReceiveProps, and componentWillUpdate are deprecated in newer versions of react. This PR is a first pass at refactoring usages of those lifecycle methods. Many usages remain but they seem trickier to handle or test.
=> Remove some usages of deprecated lifecycle methods

react/features/base/participants/functions.js, react/features/filmstrip/functions.web.js
Filmstrip remote thumbnails display under certain conditions, as
defined in filmstrip/functions.web.js. Previously the raw
participant count was used, which included fake participants.
Using the selector getParticipantCount excludes fake participants,
causing YouTube thumbnails to remain hidden in a 1-on-1 call.
=> fix(filmstrip): show thumbnails in 1-on-1 with a fake participant

android/README.md, android/sdk/build.gradle
Due to a switch to a newer version of JSCore, the jsc-android dependency is now used by the
SDK. As this dependency is not (yet) available in the Jitsi Maven repository, an error like
this is reported when an application is ran that uses the SDK:
com.facebook.react.common.JavascriptException: Can't find variable: Symbol
This commit primarily improves the instructions on how to create a local Maven repository
that contains all required dependencies, including the JSCore dependency that was missing.
This intends to address the issue described in https://github.com/jitsi/jitsi-meet/issues/3399
=> [Android] Add jsc-android to SDK project / improve build docs

modules/UI/videolayout/Filmstrip.js
Video elements may have problems scaling to cover pixel fractions,
so there could be a 1px black border line displaying in the
thumbnail. It's most visible in tile view. Flooring the sizing
calculations hides the border.
=> fix(tile-view): thumbnail videos should cover entire thumbnail

react/features/video-layout/middleware.any.js, react/features/video-layout/middleware.native.js, react/features/video-layout/middleware.web.js
When entering etherpad or pinning, filmstrip mode is displayed with tile view still enabled. Now, disable tile view. For symmetry, hide etherpad and clear pins when entering tile view.
Updated torture tests: https://github.com/jitsi/jitsi-meet-torture/pull/215
=> Tile view toggles some features and some features toggle tile view

react/features/base/media/components/AbstractVideoTrack.js
It doesn't seem like videoTrack needs to be set onto state
if it can be accessed directly from props. Removing the state
automatically removes the deprecated componentWillReceiveProps.
=> ref(video): use videoTrack from props

android/sdk/build.gradle, android/sdk/src/main/java/org/jitsi/meet/sdk/LocaleDetector.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java, android/settings.gradle, ios/Podfile, ios/Podfile.lock, ios/sdk/sdk.xcodeproj/project.pbxproj, ios/sdk/src/LocaleDetector.m, package-lock.json, package.json, react/features/base/i18n/languageDetector.native.js
The upstream package has been unmaintained for 2 years now, and making the litle
changes needed as React Native needs them is getting old. The actual
funcionality is a couple of one-liners plus tons of boliterplate, which gets
reduced by quite a bit if we just embed it. So here it goes.
=> [RN] Drop react-native-locale-detector dependency

android/build.gradle
The dependency was dropped, so it's no longer needed.
=> android: remove no longer needed code

android/build.gradle
Every time the android version that is used changes we need to update the license hash.
=> Auto accept android license on build machines.

ios/jitsi-meet.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Xcode 10 introduced a new build system. Alas, it breaks a number of important
flows, such as creating an archive for the framework (ie SDK) target.
In order to "fix" this, switch back to the former (Xcode 9) build system for the
time being.
=> ios: switch back to the "legacy" build system in Xcode

css/_meetings_list.scss, lang/main.json, react/features/calendar-sync/actionTypes.js, react/features/calendar-sync/actions.web.js, react/features/calendar-sync/components/CalendarList.web.js, react/features/calendar-sync/constants.js, react/features/calendar-sync/functions.web.js, react/features/calendar-sync/reducer.js
I'm not set up anymore to properly test the miscellaneous errors that occur with Microsoft and Google calendar fetch requests. As such I limited the error handling to the two I can consistently reproduce: logging out of Google and not whitelisting localhost in my Google calendar integration. All other errors drop down to a generic error message.
Google app configuration does not allow current site to use it.
Error message when signed out and refreshing the calendar:
Generic error message to catch all other errors. Triggered by not having calendar api permissions in the google app.
=> fix(calendar): show error message if authorization fails on event fetch

package-lock.json, package.json
Brings in a fix for getDisplayMedia being moved onto
navigator.mediaDevices and a hack fix for SDP
interop between Chrome and Firefox.
=> chore(deps): bump lib-jitsi-meet

modules/UI/videolayout/LocalVideo.js
On tile view enter/exit, local video is moved in the DOM (an effect
of not being reactified and moving being easier) and play is called
on its video element. The race condition setup is such: in tile
view with other participants and local video is on large (not
visible in the UI but visible in the app state and pip popout).
The race is such: pin a remote video, large video update is queued,
tile view is exited, local video is moved, play is called,,
onVideoPlaying callback executed, middleware fires mute update,
which checks if local is on large (it is), previous large video
update is cleared, and local is placed on large.
The fix is ensuring the redux representation of local video is
passed in, which holds the boolean videoStarted, which prevents
the onVideoPlaying callback from firing …
=> fix(tile-view): prevent local participant being selected on pin exit

css/_recording.scss, lang/main.json, react/features/recording/components/LiveStream/AbstractStartLiveStreamDialog.js, react/features/recording/components/LiveStream/AbstractStreamKeyForm.js, react/features/recording/components/LiveStream/native/StreamKeyForm.js, react/features/recording/components/LiveStream/native/styles.js, react/features/recording/components/LiveStream/web/StreamKeyForm.js
~~I've avoided implementing this on mobile for now as I had trouble getting the styling right. I'll re-visit soon but decided to make the PR now to get feedback on the copy and design.~~
web
(I did reset the stream key in the gif after capturing the gif.)
mobile
=> Add some live stream key validation

css/_recording.scss, lang/main.json, react/features/recording/components/LiveStream/constants.js, react/features/recording/components/LiveStream/native/StreamKeyPicker.js, react/features/recording/components/LiveStream/web/StartLiveStreamDialog.js, react/features/recording/components/LiveStream/web/StreamKeyForm.js, react/features/recording/components/LiveStream/web/StreamKeyPicker.js
It's possible for the YouTube api to return zero broadcasts
or broadcasts without any streams--streams are what are
associated with stream keys. In this case, instead of showing
an empty selector on web, show an error message with a link
to where the stream key can be obtained. On mobile, there
is no link because the url requires authentication.
Screenshot of web.
Screenshot of android. The error message was synthetically forced to display. There are several steps to get google auth into a local build so I faked it for now; I'll try to get that set up for a real test.
=> fix(live-streaming): show message if no broadcasts are found

package-lock.json, package.json
The avid reader may notice we have switched to using our own fork. That is
indeed the case. The upstream author hasn't maintained the library in months,
and changes to the Android build system are required at this point, hence the
fork.
=> deps: update react-native-sound

react/features/toolbox/components/native/OverflowMenu.js
Apple rejected our app on account of requiring Dropbox not being acceptable. Oh
well! Disable it until we find a way around it. Sigh.
=> ios: disable recording

doc/speakerstats-prosody.md, resources/prosody-plugins/ext_events.lib.lua, resources/prosody-plugins/mod_speakerstats.lua, resources/prosody-plugins/mod_speakerstats_component.lua
Adds the component which receives the messages from client and a module which enabled on a virtual host will start advertising the component. When clients discover the component they will send message to the component with the name of the room where the dominant speaker event happen.
=> Adds server-side speaker stats handling.

package-lock.json, package.json, react/features/base/dialog/components/AbstractDialogContainer.js, react/features/base/dialog/components/index.js, react/features/base/dialog/components/native/DialogContainer.js, react/features/base/dialog/components/native/index.js, react/features/base/dialog/components/web/DialogContainer.js, react/features/base/dialog/components/web/index.js
The package now requires using a ModalTransition component
to handle animations. The existing DialogContainer component
has been split into native and web implementations to support
this change.
=> chore(dep): bump @atlaskit/modal-dialog 6.0.12 to 7.1.2

css/_atlaskit_overrides.scss
WelcomePage used to use @atlaskit/tabs to switch between
recent meetings and calendar meetings. @atlaskit/tabs is
no longer used there so remove the css hacks which made
it look more presentable.
=> ref(welcome-page): remove unused atlaskit overrides

react/features/app/components/AbstractApp.js, react/features/app/components/App.native.js, react/features/base/app/components/BaseApp.js, react/features/mobile/incoming-call/components/IncomingCallApp.js
componentWillMount is a deprecated lifecycle method;
componentDidMount should be used to kick off things
like ajax. In the case of the _App hierarchy, a promise
chain is used to perform initialization, and it is
first started in the constructor by initializing
storage. However, by the time storage is initialized,
resolving the first promise, _App has already mounted.
So, move it all to the componentDidMount lifecycle.
I'm not as confident about this safety of this change but iOS and web were able to get into the meeting view okay and load saved state. If this approach does seem okay, I'll do another PR to rename the action appWillMount.
=> ref(app): move initialization into componentDidMount

css/_atlaskit_overrides.scss, css/_videolayout_default.scss
A CSS override prevents atlaskit theme from setting a
dark background on the top toolbar. With the upgrade
of the theme package the CSS class names changed.
=> fix(thumbnail): re-override atlaskit theme for top toolbar

css/_atlaskit_overrides.scss, package-lock.json, package.json
- Change the existing overrides to move the flags
so the first flag does not cover the toolbar.
- Add a new override to disable the slide in
animation, as it will play for each flag once
it becomes the first flag--instead of playing
only once when the flag queue has items.
With slide in animation
Without slide in animation
=> chore(deps): bump @atlaskit/flag to 9.1.8 from 6.1.0

react/features/filmstrip/components/native/Thumbnail.js
Touch feedback manifests in some ugly black border bleeding out of the thumbnail
itself. Since we already provide feedback (be that by adding the blue border in
case of pinning, or showing the menu in case of long press) the perception is
the same, without the graphical glitch.
=> rn: disable touch feedback on Thumbnail

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/jitsi/meet/MainActivity.java, android/build.gradle, ios/Podfile, ios/Podfile.lock, ios/app/GoogleService-Info.plist, ios/app/app.xcodeproj/project.pbxproj, ios/app/src/AppDelegate.m, ios/app/src/FIRUtilities.h, ios/app/src/FIRUtilities.m, ios/app/src/Info.plist
This is done at the app level, not the SDK.
Currently 2 Firebase services are used:
- Crashlytics
- Dynamic Links
They are enabled in tandem, if the appropriate Google services file
(GoogleService-Info.plist on iOS or google-services.json on Android) is found.
Each service needs to be individually enabled in the Firebase console.
=> rn: add Firebase integration

android/README.md, android/sdk/src/main/java/org/jitsi/meet/sdk/DefaultHardwareBackBtnHandlerImpl.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ReactActivityLifecycleCallbacks.java, react/features/conference/components/Conference.native.js
Provide a default and builtin default implementation which finishes the
Activity, same as before.
What this PR removes is the ability to provide a custom default handler because
applications can already take this decision when calling `onBackPressed`. In
addition, make `onBackPressed` return `void` because it's virtually impossible
for it to return `false` (that would mean that there is no
`ReactInstanceManager`, which means there is no app to begin with).
In addition, remove the use of `BackAndroid` since `BackHandler` contains an iOS
shim now.
=> android: simplify handling of the back button

react/features/settings/components/web/DeviceSelectionPopup.js, react/features/settings/popup.js
This PR just relocates the DeviceSelectionPopup to be in the components folder of the feature. Not sure why it wasn't there originally.
=> Move DeviceSelectionPopup to its right place

react/features/invite/components/InviteButton.native.js
The translate wrapper was missing from this button, which doesn't cause any issues until we start to render the label of this button (currently there is no label)
=> [RN] Fix InviteButton translation

react/features/remote-video-menu/components/web/KickButton.js
The class name is similar to the one used for the mute button and is used by the tests to locate and click the button.
=> Adds specific class name to kick button.

react/features/deep-linking/components/DeepLinkingMobilePage.web.js
When Jitsi Meet is invoked in an iframe (as via our plugin), there is a bug on ios which prevents anything from happening when the buttons are pressed. To duplicate, invoke jitsi in an iframe embedded in a page (so there are 2 iframes, the parent and the Jitsi frame itself). Open page in Safari on an iPhone or iPad. Observe that the buttons are non-functional. This PR fixes it. Tested on ios & Android.
=> nested iframe mobile button fix (for ios)

react/features/base/conference/middleware.js
Analytics is erroring when unpinning because the logged
event sends null for the objectId. The objectId should
be the id of the person getting unpinned.
=> fix(pinning): send a participant id on unpin

conference.js, react/features/base/conference/middleware.js, react/features/base/participants/actions.js, react/features/chat/components/DisplayNameForm.web.js, react/features/display-name/actions.js, react/features/display-name/components/AbstractDisplayNamePrompt.js, react/features/display-name/components/DisplayName.web.js, react/features/display-name/components/DisplayNamePrompt.web.js, react/features/display-name/functions.js
This PR moves handling of the displayname into redux and removes the legacy ```participantDisplayNameChanged```.
Please note, there is a bug possibly in lib-jitsi-meet, when the display name is not updated on the remote side when the user deletes (empties) its display name. That is not related to this PR, it is reproducible on beta too.
=> Move display name handling into redux

react/features/chat/components/native/Chat.js
Per Lenny's comment, if we reverse the chat message list in mapStateToProps we force the component to be re-rendered, as it's never the same array.
=> Chat render improbement

conference.js, config.js, react/features/base/config/functions.js, react/features/base/tracks/functions.js
This feature is intended for spot. Spot can have an
HDMI -> usb adapter hooked up to it. In that case,
attempting to screenshare should use that adapter
as a screensharing source. Jitsi-Meet should pass
a configured screenshare source into lib-jitsi-meet
so it can be used as a source.
lib-jitsi-meet changes: https://github.com/jitsi/lib-jitsi-meet/pull/855
=> feat(screenshare): use camera as a screenshare source

react/features/conference/middleware.js
- unpin participant (if the local one was pinned it would remain)
- close any dialog (except if authentication is pending)
=> rn: add some cleanup tasks when a conference ends / changes

android/app/src/main/res/xml/network_security_config.xml
These values must match these ones in React Native:
https://github.com/facebook/react-native/blob/5939d078a01edc9f83fce102317540ffbcac17c1/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/AndroidInfoHelpers.java#L20-L22
=> android: fix packager in debug mode in API 28

conference.js
Delay removing the room reference. This is in case a
consumer of the API is attempting to submit feedback
after hangup but before redirecting to another page.
If the room reference is removed, feedback submission
will fail during this period.
=> ref(conference): change when the room reference is removed

package-lock.json, package.json
Brings in https://github.com/jitsi/lib-jitsi-meet/commit/10290bbdded5b5ed770316d03dd24c81ab2b7000
=> chore(deps): bump lib for old conference listener cleanup

conference.js, modules/API/API.js, modules/API/external/external_api.js
- Pass events to the ProxyConnectionService so it can
handle establishing a peer connection so a remote
participant, not in the conference, can send a
video stream to the local participant to use as a
local desktop stream.
- Modify the existing start screensharing flow to accept
a desktop stream instead of always trying to create one.
=> feat(screenshare): support remote wireless screensharing

react/features/base/config/functions.js, react/features/local-recording/middleware.js
Config overrides are not set until some time after
APP_WILL_MOUNT has completed and not in the same execution
context as when APP_WILL_MOUNT is called. So instead
choose recording controller initialization at a later time.
The time chosen is after conference join because the
controller needs the conference instance to work.
Fixes #3613.
=> fix(local-recording): allow config override to enable

react/features/base/conference/middleware.js
Dominant speaker events can trigger local participant updates
without a display name. Do not update the name unless there
is an explicit update in the action.
=> fix(participant): update local name only on explicit update

react/features/deep-linking/functions.js
e729f0948cc57102bd8406b40cc1f92125c1603f contained an off-by-one error:
URI_PROTOCOL_PATTERN includes the colon, so after applyting the regex we are
left with something like '//example.com/room' thus we only need to strip the
first 2 characters.
🤦
=> misc: fixx off-by-one error

react/features/base/util/uri.js, react/features/deep-linking/functions.js
This reverts commit 7c911eca96a6034bc96276e0a491774df52bc2cd.
I'm dumb. We need global mode because otherwise lastIndex is not updated in the
regex object, which we rely upon, so this is intentional.
=> Revert "misc: make URL protocol matching regexes non-greedy"

package-lock.json, package.json
Updates LJM to 2e1436e20d4d8fb6020497a87b2714dff38a6c86 which includes the ICE failed notification logic.
=> chore(deps): update LJM to get ICE failed notifications

conference.js, css/_videolayout_default.scss, modules/UI/videolayout/LargeVideoManager.js, modules/UI/videolayout/VideoContainer.js, modules/UI/videolayout/VideoLayout.js, react/features/large-video/components/LargeVideo.web.js
By default the large video dominant speaker avatar
has an empty src, which will result in a broken
image displaying. There is also disconnect with
non-react code trying to set an undefined src.
To prevent such until local avatar generation
work is done in the future, just don't show the
avatar.
=> fix(large-video): do not show avatar if no url

config.js
Both Chrome and Firefox can work without extensions now, so it no longer makes
sense to default to disabling it in Chrome. Moreover, rely on the fact that
undefined is falsey so no actual config needs to be provided.
=> feat(ScreenSharing): use sane defaults

react/features/base/color-scheme/reducer.js
A reducer must always return a state or null to ignore it. When the color scheme
is undefined we should return the previous state.
=> color-scheme: fix React warning

android/build.gradle
They generate a bunch of harmless yet confusing error messages and they are not
really useful.
=> android: don't build javadocs when publishing react-native plugins

react/features/recording/components/Recording/StartRecordingDialogContent.js
Using an array of styles in Firefox causes an error
that triggers jitsi-meet to redirect to a static page.
=> fix(recording): support passing styles in firefox

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
This PR changes the color scheme type to a generic Android object instead of a React specific one
=> [Android] Change the type of the color scheme

react/features/base/config/parseURLParams.js
Not sure if there is a better way to avoid this error. I was also thinking of an early in the forEach loop if there is no value defined.
=> fix(external_api): detect and skip params for hash routers

conference.js
When a conference is started, the currently used
camera device id is saved. I believe this is happening
because lib-jitsi-meet does not use exact device id
matching when calling getUserMedia, so it's possible
to request camera A but get camera B back because
camera A is not available. When config.startScreenSharing
is true, the syncing occurs and saves the desktop
source id. So when screensharing is stopped, jitsi-meet
requests that desktop source id instead of the preferred
camera.
~~There might be a better fix available. I'll look more tomorrow.~~
=> fix(screensharing): do not sync camera device id on start

package-lock.json, package.json
Updates lib-jitsi-meet to get https://github.com/jitsi/lib-jitsi-meet/pull/876 released and available to spot.
=> chore: update LJM to 5a9fc76739bcf0bed50676c7be160f688f3a19b5

doc/api.md, modules/API/external/external_api.js
There are times when a developer would want to take some actions when the api instanced is getting disposed (analogous to when a conference is left - cleanup etc.). Added such an event.
=> feat(external_api): notify when api is disposed

react/features/calendar-sync/functions.native.js
This change avoids adding "undefined" in the calendar invite text
=> [RN] Avoid adding undefined in the invite

package-lock.json, package.json
Bring over two fixes for spot. One is for
identifying the screenshare type when using
a camera for screenshare or when using a proxy
stream. Also bring in a fix to avoid a js error
in chrome ios.
=> deps(chore): bump lib-jitsi-meet to e398584

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioModeModule.java
The android.telecom.CallAudioState class was only added in API level 23 (Android
M), so make sure we don't import it in lower versioned devices.
=> android: fix running on Android < M

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioModeModule.java
If the OS make an Audio Status update, and the device (or route) differs from the selected by the user (or the default for a video call), the SDK does not adapt itself for that change as described: https://github.com/jitsi/jitsi-meet/issues/3912
With this fix, the selected devices will be marked as null when the AudioModule receives an AudioStateChange event related with a change of the Audio Route or Devices.
The selected devices marked as null will provoke that when the Module update the Audio Route, it will set the DEVICE correspondant to that Call type (being the device setted by the OS or not)
=> fix(android-sdk): Recover audio device if the OS changes it

react/features/settings/functions.js
When we use Jitsi-Meet with authentication, the authenticated name is not display in the Settings Profile tab. So this PR propose to remove the Boolean conversion of authLogin string to display the string value instead of 'true'.
=> Fix the authenticated name displayed in Settings Profile tab

lang/main.json, modules/UI/UI.js, react/features/base/participants/middleware.js, react/features/conference/components/AbstractConference.js, react/features/conference/components/native/Conference.js, react/features/conference/components/native/Labels.js, react/features/conference/components/native/NavigationBar.js, react/features/conference/components/native/styles.js, react/features/conference/components/web/Conference.js, react/features/conference/functions.js, react/features/notifications/components/AbstractNotificationsContainer.js, react/features/notifications/components/Notification.native.js, react/features/notifications/components/NotificationsContainer.native.js, react/features/notifications/components/styles.js, react/features/notifications/functions.js, react/features/notifications/index.js
Adds back the in-call notifications on mobile which follow the latest design.
Currently it displays only the title to fit in one line. If there's no title it will use the description. I'm still in the process of reviewing longer notifications across the app, but wanted to show the current structure. I've placed the notifications container inside the navigation bar, because it needs to play well with the bar and the top gradient. I guess eventually the gradient and the notifications container could be moved up to the conference component.
=> Mobile in-call notifications

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetFragment.java
Now that we have both a Fragment and an Activity there are lifecycle methods
that overlap. If a Fragment requests permission by calling requestPermissions
then the result handler will be called on itself. React Native's permissions
module, however, calls ActivityCompat.requestPermissions on the Activity, thus
we need to handle the results at the Activity level and not at the Fragment
level.
=> android: fix getting permission request results

react/features/base/conference/middleware.js
If tracks are created while the conference is in the 'joining' state they will never be added.
=> fix(base/conference): tracks not added to the conference

android/sdk/src/main/java/org/jitsi/meet/sdk/ConnectionService.java
On some Samsung devices the call done with the ConnectionService end up in the native call history which we don't want. That's fixable by marking the Connection as "external" just before the call is disconnected.
Another issue specific to Samsung devices about the audio focus not always being release when that call ends. That's fixable by marking the call as holding just before disconnecting it.
=> fix(ConnectionService): history and audio focus on Samsung devices

react/features/device-selection/functions.js
Devices of different kinds can have the same id, such as speaker
and mic both being default. Using id only can then lead to
incorrectly setting device descriptions in the current devices
object.
=> fix(device-selection): use device kind when getting current devices

react/features/base/devices/actions.js, react/features/base/devices/functions.js, react/features/device-selection/functions.js
Searching for a device (id) by label alone can result in
false results when devices share labels, such as a mic
and speaker having the same label. To prevent such,
specify the device kind to be found instead of iterating
over all device kinds.
=> fix(device-selection): search for device by label and kind

react/features/device-selection/components/AudioOutputPreview.js
The Audio.js setRef callback does not behave like react ref callback
in that the former will not have fired before componentDidMount
but the later will have. So for audio output preview, trying to set
sink id on mount will no-op because it does not have a ref yet to
Audio.js, possibly leading to audio output previews playing on
the default speaker device. This generally has not been a user
visible problem due to coincidence; other re-renders necessary
by the parent of audio output preview will have triggered
componentDidUpdates on the audio out preview, which would then
set the sink id on the Audio.js ref it should have received
by then.
=> ref(device-selection): set audio output sink id after receiving ref

modules/UI/videolayout/LargeVideoManager.js
When a fade in/out animation is in progress, another large
video update can be queued but can try to force itself onto
large video. For example a pin can be in progress and while
the fade in/out animation plays, local video can change its
video type during the animation and forcing an update of
large video. This results in local video getting forcible
updated onto large video while the pinned video is left on
small video only.
=> fix(large-video): respect update in progress when queuing update

css/_chat.scss
The chat icons are different on windows and mac, with
windows icons being bigger. By settings a specific
width on the smiley container, windows would see
part of the smiley cut off.
=> fix(chat): allow smiley opener to expand in width

css/_chat.scss, css/filmstrip/_vertical_filmstrip.scss
For filmstrip and chat. Tweaked chat textarea in the process to avoid a gap in background color.
Old chat placement
New chat placement without text
New chat placement with text
Old filmstrip top
New filmstrip top
Old textarea
New textarea
=> Avoid top of screen

ios/fastlane/Fastfile
While that option should default to true, let's be explicit about it.
=> ios: make sure symbols are uploaded to TestFlight

ios/sdk/src/callkit/JMCallKitEmitter.swift, ios/sdk/src/callkit/JMCallKitProxy.swift
Ever since we switched to handling track events instead of mute actions this has
been dead code. It was also added in the wrong place, since it's responsibility
of the JS code to solve the ping-pong problem.
=> ios: remove no longer needed code

css/_subject.scss, css/_toolbars.scss
Otherwise it can eat clicks on elements it is above,
like YouTube and Etherpad controls.
=> fix(toolbar): let click through gradient

ios/sdk/src/callkit/JMCallKitProxy.swift
When CallKit is enabled / disabled, a new CXProvider must be created in order to
not confuse CallKit (it misbehaves otherwise).
=> ios: fix resetting CallKit's CXProvider

react/features/invite/components/add-people-dialog/native/AddPeopleDialog.js
This PR fixes a keyboard bug that happens on iOS when performing an invite search
=> [RN] Fix iOS keyboard bug on invite search dialog

react/features/base/conference/actions.js, react/features/base/connection/actions.native.js, react/features/base/connection/constants.js, react/features/base/connection/index.js, react/features/conference/components/native/Conference.js, react/features/mobile/external-api/middleware.js
Dear reader, I';m not proud at all of what you are about to read, but sometimes
life just gives you lemons, so enjoy some lemonade!
Joining a conference implies first creating the XMPP connection and then joining
the MUC. It's very possible the XMPP connection was made but there was no chance
for the conference to be created.
This patch fixes this case by artificially genrating a conference terminated
event in such case. In order to have all the necessary knowledge for this event
to be sent the connection now keeps track of the conference that runs it.
In addition, there is an even more obscure corner case: it's not impossible to
try to disconnect when there is not even a connection. This was fixed by
creating a fake disconnect event. Alas the location URL is lost at this point,
but it's …
=> rn: ensure the conference terminated event is always sent

ios/app/src/AppDelegate.m, ios/app/src/FIRUtilities.h, ios/app/src/FIRUtilities.m
- handle some weird bug
(https://github.com/firebase/firebase-ios-sdk/issues/233)
- use a common function to extract the URL off a dynamic link
=> ios: handle some corner cases with Firebase Dynamic Links

conference.js, modules/devices/mediaDeviceHelper.js, react/features/base/devices/actions.js, react/features/base/devices/functions.js, react/features/base/settings/reducer.js, react/features/base/tracks/functions.js, react/features/device-selection/actions.js, react/features/device-selection/functions.js
The state about currently opened devices is filtered and not stored, where we only store when user selects a device preferences.
Also allow changing input devices for Firefox when we are not in a conference.
=> Adds new persistent state for devices user selection.

conference.js
The proper field name is "messageType",
not "type." Also using "type" would
override the actionType.
=> fix(chat): save chat error messages into redux

css/_welcome_page.scss, react/features/welcome/components/WelcomePage.web.js
By making the container 100% height and position relative, that
would cause it to overlap any static-positioned  elements below it.
The 100% makes it so that any watermarks intended for the bottom
of the page show up on the bottom of the page. However, it's not
needed because watermark stylings already try to position the
watermarks at the bottom.
=> fix(welcome-page): remove watermark container to avoid z-index wars

conference.js, modules/devices/mediaDeviceHelper.js, react/features/base/devices/actions.js, react/features/base/devices/functions.js, react/features/base/devices/middleware.js, react/features/base/media/components/AbstractAudio.js, react/features/base/settings/functions.js, react/features/base/settings/reducer.js, react/features/base/tracks/functions.js, react/features/device-selection/actions.js, react/features/device-selection/components/AudioOutputPreview.js, react/features/device-selection/functions.js
This brings back the changes from https://github.com/jitsi/jitsi-meet/pull/3219. Some of the changes were introduced earlier and this adopts the PR using the recently introduced new storage values for user selected device id and adds a label to them.
=> Fall back to using label for preferred devices

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivityDelegate.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
Entering PiP mode while the permissions dialog is display will not only fail, but also mess up the Activity lifecycle on some OS versions. We may end up with two activity/fragment instances and a situation where the onStop callback was not called yet on the instance #1 while the onResume has been already called on instance #2.
=> android fix: do not enter PiP mode when the permissions alert is shown

ios/sdk/src/callkit/CallKit.m
It's possible a CallKit event arrives when the React Bridge has been torn down
and there is an assert that checks this. In order to avoid a crash, just skip
the event.
=> ios: fix CallKit crash in development mode

css/_chat.scss, react/features/chat/components/web/ChatMessageGroup.js
=> fix(chat): ensure really long words can trigger wrapping

modules/UI/videolayout/VideoContainer.js
Stop using special case logic for aligning screenshare videos.
It may be possible to have positioning all done using CSS but that
seems to be a more significant refactoring.
before
after
=> fix(large-video): vertically align center screenshare

css/_chat.scss, package-lock.json, package.json, react/features/chat/components/web/Chat.js, react/features/chat/components/web/ChatInput.js, react/features/chat/components/web/MessageContainer.js
I got lazy and decided not to roll my own implementation. I think it was a good idea considering how easy it was to integrate to the package "react-textarea-autosize."
=> ref(chat): bring in package for text area auto-resizing

interface_config.js
This is a feature implemented for Spot however the desire now is try it out as the default behavior for meet.
=> feat(screenshare): enable auto-pin of latest and last screenshare

react/features/base/devices/actions.js
Currently devices set through the api are stored
as ids, and not user selected. This can cause
other existing user selected devices to take
precedence over the devices passed into the api.
I don't know what the real desired precedence is so this is my initial attempt.
=> fix(api): store passed in devices as user selected

react/features/base/app/actions.js
For the external api to fire update events out of the iframe, it
must first be initialized within the jitsi app. Any invocations
by the app to send updates events before initialization will
cause the api to swallow the events. The chosen fix is to
initialize the api earlier so the first update of app's redux
store fires update events that the api will also fire out of
the iframe.
This change will affect current behavior in that right now
the update event of the initial set of the avatar url is
blocked, but the change will make that event fire out of the
iframe.
=> fix(api): enable the external api before the first redux update

android/sdk/build.gradle, android/settings.gradle
The naming didn't match, so adjust it. @ cannot be used for maven artifact
names.
=> android: fix publishing new async storage package

ios/README.md
There were some mistakes in the documentation regarding the Universal deep linking. Changed `JitsiMeetView` to `JitsiMeet`.
=> Update iOS Readme

android/scripts/release-sdk.sh, ios/scripts/release-sdk.sh
People run these in their own checkout and will run into problems because
tagging will fail.
=> rn: don't tag builds by default

ios/app/src/ViewController.m, react/features/app/actions.js, react/features/base/conference/middleware.js, react/features/base/connection/actions.native.js, react/features/conference/components/native/Conference.js, react/features/toolbox/components/HangupButton.js
This PR changes the logic for connecting / disconnecting conferences. Instead of
doing it in mount / unmount events from the Conference component, it moves the
logic to the appNavigatee action.
This fixes a regression introduced in 774c5ecd when trying to make sure the
conference terminated event is always sent.
By moving the logic to appNavigate we no longer depend on side-effects for
connecting / disconnecting, and the code should be more maintainable moving
forward.
An improvement to this is the concept of sessions, which, while not tackled
here, was taken into consideration.
=> rn: fix losing audio if call is hangup too quickly

modules/UI/UI.js, modules/UI/videolayout/RemoteVideo.js, modules/UI/videolayout/VideoLayout.js, react/features/base/tracks/middleware.js, react/features/video-layout/middleware.web.js
VideoLayout schedules a large video update by passing in
the video stream on the small video instance. When a stream
is removed, the UI is removed from the small video instance
but a reference to the stream is left. So when VideoLayout
schedules the large video update after a stream removal,
the old stream from the small video instance is re-used,
even though it has been removed.
This change also brings balance with RemoteVideo method
"addRemoteStreamElement" which sets the stream on the
small video instance, so now "removeRemoteStreamElement
unsets it.
=> fix(large-video): clear remote video stream on track removal

react/features/base/settings/reducer.js
If a value is not set in localStorage then null is
returned. null should not be converted to an empty
string (via _.escape) because that will then be
stored in localStorage as the user set preference
and will keep overriding any other values set
in localStorage for the displayname.
This is a workaround, a patch, to quickly fix the issue of jibri being unable to join a meeting when config.requireDisplayName is true. To reproduce the issue I opened an incognito window, went to the homepage, set a localStorage value for displayname, and then tried to join a meeting in the same window.
=> fix(settings): do not use non-set localStorage values

lang/main.json, react/features/app/getRouteToRender.js, react/features/base/environment/environment.js, react/features/base/environment/index.js, react/features/base/environment/isBlacklistedEnvironment.js, react/features/deep-linking/components/DeepLinkingDesktopPage.web.js, react/features/unsupported-browser/components/UnsupportedDesktopBrowser.js
Built on top of #4306. ~This PR can supersede it if that's easier.~ Supersedes that PR because this one has gone further with the requirements and it'll just be easier for me to handle comments.
Screenshot of deep-linking page with unsupported browsers not showing a button to launch on web.
Unsupported browser page with Safari removed.
=> feat(unsupported): provide custom blacklist for branding

android/app/src/main/java/org/jitsi/meet/MainActivity.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetUserInfo.java, ios/sdk/sdk.xcodeproj/project.pbxproj, ios/sdk/src/JitsiMeetConferenceOptions.h, ios/sdk/src/JitsiMeetConferenceOptions.m, ios/sdk/src/JitsiMeetUserInfo+Private.h, ios/sdk/src/JitsiMeetUserInfo.h, ios/sdk/src/JitsiMeetUserInfo.m, react/features/app/components/App.native.js
At the moment it includes:
- display name
- email
- avatar URL
This information is used *only* if no token was specified.
=> rn: add SDK API to set user information

react/features/toolbox/components/VideoMuteButton.js
When the video unmute button disabled audio-only, also unmute video. This fixes
a weird case in which the user need to "unmute twice" if they were muted beofre
they enabled audio-only mode. That's ok if the audio-only button was used, but
not if the video-unmute button was used, since the expectation is to have video,
of course.
=> rn: fix video unmuting when disabling audio-only

react/features/calendar-sync/reducer.js
Checking if the calendar support in the reducer is not only useless but wrong,
since we don't have access to the entire store (the calendar support is checked
in the base/config feature). If calendar support is not enabled the actions
being reduced won't be dispatched anyway, so no harm is done by removing the
check.
=> calendar-sync: fix loading calendar entries

css/_videolayout_default.scss
before ![Screen Shot 2019-06-14 at 2 37 46 PM](https://user-images.githubusercontent.com/1243084/59539592-b4ca7200-8eb2-11e9-9862-188939f13d71.png)
after
=> fix(always-on-top): enforce circle avatar

react/features/welcome/components/Tabs.js
In case wrong props are passed in, such as pointing to
an index that does not contain a value in the tabs
array.
=> fix(welcome-page): make Tabs more resilient to bad props

react/features/base/participants/actions.js, react/features/base/participants/middleware.js
Also, use the helper function to get the display name for a participant.
=> participants: skip local participant join notification

android/sdk/src/main/java/org/jitsi/meet/sdk/BaseReactView.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ConnectionService.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetUncaughtExceptionHandler.java, android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
Its main task is to cleanup conferences (specially the connection services
stuff) to make sure the system is left in a working state even when the
unexpected happens.
=> android: add a uncaught exception handler

react/features/base/conference/reducer.js
This was hit on a corner case when ConnectionService will deny the request to start the call. I am not sure, but it could have been that the conference object has been disposed or closed or something else, but the fact is that 'conference.room' was not defined and things crashed. It is not safe to access conference's private field 'room'. It is true JitsiConference doesn't follow the practice of marking this field as private with the underscore '_', but it is not a public field.
=> fix(base/conference/reducer): check if room is defined

android/sdk/src/main/java/org/jitsi/meet/sdk/ExternalAPIModule.java, android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
ENTER_PIP_MODE, for example, does not have it.
=> android: fix exception when sending events without URL

react/features/base/participants/middleware.js
Otherwise the participant will not have been added yet
to state so the participant name will not display in
the notification.
Quick fix for now. Will follow up by moving the notification logic out
of base/participants/middleware.
=> fix(notifications): show notifications after reducers update to get name

react/features/conference/middleware.js
Pretend we have left instead of triggering a call failure. The user was already
told in the dialog.
=> rn: fix CallKit failure screen flash when kicked

conference.js, react/features/notifications/middleware.js
Join notifications are already supressed for the local
participant, so hide the left notification. For now
the notification is not being shown on mobile to keep
the same existing behavior and because a copy change
will be needed, but will be added once batching is
implemented.
=> ref(notifications): do not notify of local participant left

package.json, react/features/calendar-sync/web/microsoftCalendar.js
PR adds possibility to show calendar events from MS api in local timezone.
Issue started in https://community.jitsi.org/t/ms-calendar-events-time-in-gmt-only/18428
=> microsoftCalendar: add showing calendar events in local timezone.

ios/sdk/src/JitsiMeet.h
It causes a compiler error in Xcode 11 beta 2  because it doesn't know how to parse it.
=> Fix spelling mistake on pragma mark

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java
I cannot see a path leading to it being null, but Crashlytics demonstrated it's
possible (so far in a small subset of old devices). Be defensive then.
=> android: fix crash if notification is null

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java
After calling startService we are supposed to have a bit of time before turning
the service into a foreground service, but certain devices seem to be more
spartan and we've seen the following failure:
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=JitsiMeetOngoingConferenceService:START cmp=org.jitsi.meet/.sdk.JitsiMeetOngoingConferenceService }: app is in background uid UidRecord{f6778d5 u0a220 CAC  bg:+1m1s417ms idle change:idle procs:1 proclist:15604, seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon + 1600(ContextImpl.java:1600)
at android.app.ContextImpl.startService + 1546(ContextImpl.java:1546)
at android.content.ContextWrapper.startService + 669(ContextWrapper.java:669)
at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.launch + …
=> android: be explicit about starting a foreground service

react/features/base/conference/functions.js, react/features/deep-linking/components/DeepLinkingMobilePage.web.js, react/features/invite/components/dial-in-info-page/DialInInfoApp.web.js, react/features/invite/components/info-dialog/web/InfoDialog.js, react/features/invite/functions.js, react/features/recent-list/functions.native.js, react/features/recent-list/functions.web.js, react/features/welcome/components/AbstractWelcomePage.js
It would be nice to have someone also test this because for whatever reason my confidence is not high. I called decode near where the room name gets shown in the UI as I, maybe erroneously, felt unsafe storing the decoded version in redux itself.
=> fix(invite): decode the meeting name

lang/main.json, react/features/invite/components/add-people-dialog/native/AddPeopleDialog.js
Note: the Android back button misbehaves with the SlidingView (unlike a Modal). I'm going to try to cover that in a follow up PR.
=> feat: use dialog instead of alert when inviting

modules/UI/videolayout/VideoLayout.js, modules/remotecontrol/RemoteControl.js
Multiple requests for checkUserRemoteControlSupport can be in
flight simultaneously. Order of promise resolution is not
guaranteed. It is possible for Request A and Request B to be
in flight and then Request B's promise chain resolves first.
Request A could have encountered errors and then resolve. Then
what could happen is checkUserRemoteControlSupport returns true
for remote control support due to Request B and the UI updates.
But then checkUserRemoteControlSupport returns false for
remote control support due to Request A's error and the UI
updates to hide remote control.
=> fix(remote-control): do not assume failed query is missing support

react/features/app/components/App.native.js, react/features/base/react/components/native/SlidingView.js, react/features/chat/components/native/Chat.js, react/features/conference/components/native/Conference.js, react/features/invite/components/add-people-dialog/native/AddPeopleDialog.js, react/features/invite/components/dial-in-summary/native/DialInSummary.js, react/features/mobile/back-button/BackButtonRegistry.js, react/features/mobile/back-button/index.js, react/features/mobile/back-button/middleware.js, react/features/remote-video-menu/components/native/RemoteVideoMenu.js, react/features/toolbox/components/native/OverflowMenu.js
Motivation:
Using the```BackHandler``` API directly doesn't let us prioritize a handler higher or lower, however we need to be able to do that for modal-like components.
E.g.: The Conference component registers its listener in ```componentDidMount``` and handles the back button to toggle PiP mode. While modal-like components opened from the ```Conference``` screen need to listen for a back button event to close themselves, their ```componentDidMount``` fire earlier the the one in ```Conference```, so the app goes into PiP before the chain gets to their listener (note: the chain doesn't even get there, since the listener in ```Conference``` returns true, ignoring any other listeners further down in the chain)
=> feat: central back button registry
