index.html
libs/app.bundle.js
modules/RTC/DataChannels.js
modules/RTC/RTC.js
modules/UI/UI.js
modules/xmpp/JingleSession.js
modules/xmpp/moderator.js
modules/xmpp/strophe.emuc.js
modules/xmpp/strophe.jingle.js
modules/xmpp/strophe.moderate.js
modules/xmpp/xmpp.js
service/RTC/RTCEvents.js
service/xmpp/XMPPEvents.js

These changes make the xmpp and RTC modules not depend on the UI module which enables using the xmpp and RTC modules as a library.

Remove UI refs from xmpp and RTC

---

modules/RTC/RTCUtils.js

I'll merge this in a few days unless there are objections.

Re-enables video noise reduction (removes a workaround for M37).

---

doc/api.md
external_api.js
modules/API/API.js

…{Audio,Video}" since what they do is "toggle".
I'll merge this in a few days unless there are objections.

Rename mute to toggle

---

package.json

Npm install wasn't working with the comment in dependencies.

Change the comment to fix npm install

---

modules/config/HttpConfigFetch.js

- use jQuery instead of mid-2000s APIs for XHR
- proper data serialization

Some fixes in dynamic config retrieval

---

index.html
interface_config.js
libs/app.bundle.js
modules/UI/toolbars/BottomToolbar.js
modules/UI/toolbars/Toolbar.js
modules/UI/toolbars/ToolbarToggler.js
modules/UI/util/UIUtil.js

* allow for a list of enabled buttons to be passed as part of interfaceConfig

Allow toolbar buttons to be configurable

---

unsupported_browser.html

https://hacks.mozilla.org/2015/06/firefox-multistream-and-renegotiation-for-jitsi-videobridge/
Thank you George Politis! (and anyone else involved)

Firefox & Jitsi Meet are now working together

---

modules/UI/toolbars/Toolbar.js

There is a spurious eol change. I am using Github web interface so I assume my setting are "right"

Fix a typo

---

config.js
modules/UI/authentication/LoginDialog.js

authdomain2

---

modules/UI/videolayout/LocalVideo.js

Escape html from username to avoid XSS.

escape html from username

---

JitsiMeetJS.js
modules/RTC/RTC.js
modules/RTC/RTCUtils.js

Added 2 functions to `LibJitsiMeet`:
* `isDeviceListAvailable` to check if we can retrieve list of devices
* `enumerateDevices` to receive list of cameras/microphones

Enumerate devices

---

modules/UI/videolayout/SmallVideo.js

There was an error when client on Safari was trying to click on video of client on FF.

fixed switching to large video from FF on Safari

---

modules/xmpp/TraceablePeerConnection.js

Use Object.defineProperty instead of Object.prototype._defineGetter_ to make it work in IE10.

Use Object.defineProperty instead of Object.prototype._defineGetter_

---

JitsiConference.js
JitsiConferenceErrors.js
doc/API.md

This allows moderator to set password for the conference.

Add methods to lock/unlock conference

---

JitsiConference.js
doc/API.md
lib-jitsi-meet.js
modules/RTC/JitsiLocalTrack.js
modules/RTC/JitsiRemoteTrack.js

Few changes to improve lib-jitsi-meet usability.

Improve lib-jitsi-meet usability

---

JitsiConference.js
JitsiConferenceErrors.js
JitsiConferenceEvents.js
doc/API.md
lib-jitsi-meet.js
modules/xmpp/moderator.js

* method to check if external auth is supported
* method to get url for external auth
* method to get conference name
* propagate conference errors through the API

Add methods related to external authentication

---

JitsiConference.js
JitsiConferenceEvents.js
JitsiParticipant.js
doc/API.md
lib-jitsi-meet.js
modules/xmpp/ChatRoom.js
modules/xmpp/xmpp.js

- helper methods to check if auth is enabled
- allow to kick participant
- unset old nickname before setting new one

Lib-jitsi-meet imrovements

---

.gitattributes
app.js
conference.js
libs/lib-jitsi-meet.js
modules/UI/UI.js
modules/UI/side_pannels/settings/SettingsMenu.js
modules/UI/videolayout/VideoLayout.js
modules/desktopsharing/desktopsharing.js
service/xmpp/XMPPEvents.js

implementation of "start muted"

implementation of "start muted"

---

JitsiConference.js

Stop adding `TRACK_REMOVED` listener to the conference every time a track is added
As TRACK_REMOVED are never removed from the conference and add up over time.
Might be better to just remove the tracks listeners inside `JitsiConference.prototype.removeTrack`.

Stop adding TRACK_REMOVED listeners on every JitsiConference.prototype.addTrack

---

modules/UI/avatar/Avatar.js
modules/UI/videolayout/LargeVideo.js
modules/UI/videolayout/VideoLayout.js
modules/util/helpers.js

When user clicks fast enough on few different small videos, it leads to wrong state of small videos and causes issues with Large video fadeIn/fadeOut animations.

Synchronize video "fadeIn/fadeOut" to avoid race conditions in jitsi-meet-new

---

modules/UI/videolayout/LargeVideo.js
modules/UI/videolayout/VideoLayout.js

* use proper context for the function
* remove duplicate line

Minor fixes for jitsi-meet-new

---

conference.js
lang/main.json
modules/UI/UI.js
modules/util/helpers.js

depends on https://github.com/jitsi/lib-jitsi-meet/pull/8

handle FOCUS_LEFT conference error

---

conference.js
css/settingsmenu.css
index.html
lang/main.json
modules/UI/UI.js
modules/UI/side_pannels/settings/SettingsMenu.js
modules/UI/toolbars/Toolbar.js
modules/UI/util/UIUtil.js
modules/UI/videolayout/LocalVideo.js
modules/UI/videolayout/VideoLayout.js
modules/settings/Settings.js
service/UI/UIEvents.js

* adds 2 dropdowns with available audio and video devices to the settings
* stores id of selected device in the local storage
* switches to the new stream when user selects other devices
depends on https://github.com/jitsi/lib-jitsi-meet/pull/11

Allow user to select camera and microphone

---

conference.js

depends on https://github.com/jitsi/lib-jitsi-meet/pull/14

Remove old track from the conference before adding new one

---

conference.js
modules/UI/authentication/AuthHandler.js

fixes https://github.com/jitsi/jitsi-meet/issues/495
depends on https://github.com/jitsi/lib-jitsi-meet/pull/15

fix authentication dialog

---

modules/UI/videolayout/LargeVideo.js

automation test https://github.com/jitsi/jitsi-meet-torture/pull/2

LargeVideo: detach previous stream when attaching new one

---

conference.js

depends on https://github.com/jitsi/lib-jitsi-meet/pull/20

leave the room if focus left

---

conference.js
modules/UI/UI.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js

Handles track removed and removes video elements. When switching on and off desktop sharing video elements number grow under remote video span.

Handles track removed and removes video elements.

---

conference.js
modules/UI/UI.js
modules/UI/authentication/AuthHandler.js
modules/UI/welcome_page/WelcomePage.js
modules/settings/Settings.js

* fixes on-the-fly xmpp auth with jicofo
* updates toobar auth (login/logout) icon on login/logout
* implements (on-the-fly) logout with redirect to the welcome page
depends on https://github.com/jitsi/lib-jitsi-meet/pull/26

Fix login/logout 

---

conference.js
modules/UI/videolayout/LocalVideo.js

Fixes jitsi meet to work with the renamed events and methods in the latest version of lib-jitsi-meet.

Fixes the compatability with lib-jitsi-meet.

---

conference.js
css/settingsmenu.css
index.html
modules/UI/UI.js
modules/UI/side_pannels/SidePanelToggler.js
modules/UI/side_pannels/settings/SettingsMenu.js
modules/settings/Settings.js

* update text fields on Enter and on Blur
* update other fields on chainge (selects, checkboxes)
depends on https://github.com/jitsi/lib-jitsi-meet/pull/27

Apply new settings without clickint "Update" button

---

modules/UI/etherpad/Etherpad.js
modules/UI/videolayout/LargeContainer.js
modules/UI/videolayout/LargeVideo.js
modules/UI/videolayout/VideoLayout.js

Skip switching to dominant speaker when Etherpad is on large.

Fix etherpad

---

conference.js
modules/UI/Feedback.js
modules/UI/UI.js
modules/UI/recording/Recording.js
modules/UI/toolbars/BottomToolbar.js
modules/UI/toolbars/Toolbar.js
modules/UI/toolbars/ToolbarToggler.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js
modules/recorder/Recorder.js

Also refactors Toolbar, BottomToolbar and ToolbarToggler.

Add custom-role to presence and special view for Recorders

---

conference.js

The user is not participating in the call anymore while the feedback form is displayed.

Leaves the call when the hangup button is pressed

---

connection.js

Adds the possibility to predefine id and password in local storage to be used for an authentified launch of the app.

Adds id and password initial login

---

Makefile

Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>

Fix "make source-package"

---

conference.js
lang/main.json
modules/UI/recording/Recording.js
modules/recorder/Recorder.js

Fix recorder error and state handling. Report recorder userinfo in presence.

Fix recorder error and state handling

---

conference.js
index.html
lang/main.json
modules/UI/side_pannels/settings/SettingsMenu.js
modules/settings/Settings.js
service/UI/UIEvents.js

Added dropdown to settings with ability to change audio output device.
This feature can be tried at https://ktsar.jitsi.net

Added ability to change output audio device through settings

---

conference.js
modules/UI/side_pannels/settings/SettingsMenu.js
modules/settings/Settings.js

Support for JitsiMeetJS.events.mediaDevices.DEVICE_LIST_CHANGED event is implemented in https://github.com/jitsi/lib-jitsi-meet/pull/100
Change is deployed to https://ktsar.jitsi.net
Should be tested together with https://github.com/jitsi/lib-jitsi-meet/pull/100

Update devices in settings panel when list of available devices changes

---

conference.js
css/main.css
lang/main.json
modules/UI/UI.js
modules/UI/side_pannels/settings/SettingsMenu.js
modules/UI/toolbars/Toolbar.js
modules/settings/Settings.js

Should be merged together with https://github.com/jitsi/lib-jitsi-meet/pull/103
Local audio and video tracks will be switched when list of available devices changes
Can be tested at https://ktsar.jitsi.net

Switch local audio and video track when list of available devices changes

---

app.js

Use location.href instead of location.pathname to make the URL absolute

Only push to history with present page URL plus room name

---

conference.js
lang/main.json
modules/UI/UI.js
modules/UI/side_pannels/settings/SettingsMenu.js
nwjs-integration/index.html

Show dialog with error when GUM calls fail, also fix some minor bugs related to enabling webcam icon or restoring correct <select> state when failed to change camera/mic/audio output.
Should be tested together with https://github.com/jitsi/lib-jitsi-meet/pull/119

Show dialog with error when GUM calls fail

---

Makefile

Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>

Fix missing base.html in source-package

---

conference.js
modules/FollowMe.js

Adds a fix for follow-me to work without configured etherpad.

Fixes follow-me to work without etherpad

---

modules/UI/Feedback.js
modules/UI/UI.js
modules/UI/authentication/LoginDialog.js
modules/UI/authentication/RoomLocker.js
modules/UI/recording/Recording.js
modules/UI/shared_video/SharedVideo.js
modules/UI/toolbars/Toolbar.js
modules/UI/util/MessageHandler.js

+ Adds the possibility to enable / disable popups
+ Disables popups for recorder participants
+ Uniform way of accessing messageHandler
+ Refactor MessageHandler object to better fit the project syntax

Unifrms messageHandler access and adds enable disable

---

lang/languages.json

And order the existing entries alphabetical by language-code.

Add missing languages from Pootle

---

modules/UI/UI.js

Expose JitsiTrackError through JitsiMeetJS.errorTypes.JitsiTrackError
Should be merged together with https://github.com/jitsi/lib-jitsi-meet/pull/159

Expose JitsiTrackError through JitsiMeetJS.errorTypes.JitsiTrackError

---

modules/UI/recording/Recording.js
modules/UI/shared_video/SharedVideo.js
modules/UI/util/MessageHandler.js

Make sure we have only one dialog instance, so we do not show multiple dialogs of the same type one over another.

Dialogs update

---

package.json

Change reference to lib-jitsi-meet to use full github url

---

conference.js
modules/connectionquality/connectionquality.js

Revert "Changes the connection quality stats to be sent by the data channels"

---

index.html
title.html

Moves favicon into the title html with all metadata for easy overriding. Moves the title html inclusion after all the connection optimisations to avoid downloading the icon to interfere those optimisations.

Moves favicon into the title html.

---

css/unsupported_browser.css

Fixes the path of the unsupported browser images

Fix unsupported browser images

---

analytics.js

Updates statistics implementation, adds optional label.

Updates statistics implementation.

---

prosody-plugins/mod_auth_token.lua
prosody-plugins/token/util.lib.lua

Add support for fetching keys from a server using the key ID to mod_auth_token.
Still testing this, but I fixed a number of issues today and have a small test server setup so I wanted to go ahead and get feedback on the PR.
I threw together a quick server to test this with here: https://gist.github.com/SamWhited/0ceab67b05668e6c6dcf8c05aab1243c

Add support for fetching public keys from a server to mod_auth_token

---

prosody-plugins/mod_auth_token.lua

* Remove unnecessary cjson config
* Add semicolons
* Make import style consistent
/cc @paweldomas

mod_auth_token: Misc minor fixes

---

prosody-plugins/mod_auth_token.lua

* Fix broken caching (actually put keys in the cache)
* Keys on the server are named by the sha256 of the kid claim
/cc @paweldomas

Mod token improvements

---

app.js
conference.js
lang/main.json
modules/UI/side_pannels/settings/SettingsMenu.js
modules/settings/Settings.js
service/UI/UIEvents.js

Removes avatar url from UI and do not store anything when using ring overlay.

Removes avatar url from UI.

---

conference.js

Requires jitsi/lib-jitsi-meet#227

Update lock icon when moderator changes state

---

modules/UI/videolayout/RemoteVideo.js

This reverts commit 76a7c7b426732a6d298c5350c05c05a5a2a12729.

Revert "Temprorary disable kicks hack."

---

lang/main.json
modules/UI/UI.js
modules/UI/side_pannels/contactlist/ContactList.js

Uses the same display names in the contact list as in the thumbnails, for local and remote.

Syncs contactlist display names with thumbnails.

---

modules/UI/util/UIUtil.js
modules/UI/videolayout/LargeVideo.js
modules/UI/welcome_page/WelcomePage.js

When link is missing disable clicking.

Updates handling links on watermarks.

---

css/_videolayout_default.scss
index.html

Prevent tooltips from appearing behind the side toolbar panel

Adjustment for layer order

---

modules/UI/side_pannels/contactlist/ContactList.js

Includes showing 1 when user is alone in the room.

Always show number of participants badge in toolbar.

---

css/_base.scss
css/_toolbars.scss
css/_variables.scss
css/_videolayout_default.scss
modules/UI/audio_levels/AudioLevels.js
modules/UI/side_pannels/chat/Chat.js
modules/UI/side_pannels/contactlist/ContactList.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/VideoLayout.js

- Adjusts the toolbar toggle glow.
- Adjusts video thumbnail pin and hover border.
- Removes duplicate code in AudioLevels.js

Pin hover improvements

---

modules/UI/videolayout/LocalVideo.js

Allow user to edit initial username

---

lang/main.json
modules/UI/toolbars/Toolbar.js

Removed duplicates from keyboard shortcuts

---

css/_toolbars.scss

Fix padding for feedback button

---

css/_chat.scss
css/_contact_list.scss

Removed black line from contact list and message list

---

css/_videolayout_default.scss

border-radius for HD

---

css/main.scss
css/themes/_main.scss

Added main file in `css/themes` where we can now change themes if they will be added.

Add main file for switch theming

---

modules/UI/videolayout/LargeVideoManager.js

Clean up audio level after previous speaker

---

interface_config.js
modules/UI/UI.js
modules/UI/ring_overlay/RingOverlay.js

Now the ringing sound can be disabled by setting the DISABLE_RINGING option to true. It can be set by the URL parameters:
https://example.com/meeting#interfaceConfig.DISABLE_RINGING=true .

Add interfaceConfig option for disabling ringing

---

modules/UI/invite/InviteDialogView.js

By this PR I added possibility to set password via pressing return button instead of default closing the dialog

Add possibilty to set password via return key

---

css/_contact_list.scss

- Fixes long display name appearance
- Fixes left indent compared to other components in the contact list

Some contact list styling adjustments

---

modules/UI/UI.js
modules/UI/util/MessageHandler.js

Fixed toggling shortcut dialog and added method showing if any dialog is opened.

Fix shortcut dialog toggling

---

css/_variables.scss
css/modals/feedback/_feedback.scss

feedback style variables

---

android/app/src/main/AndroidManifest.xml

The MAIN action and LAUNCHER category need to go in a separate intent-filter for the app to appear in the drawer.

Fix Android launcher intent so that app appears in drawer.

---

css/_base.scss
css/_jitsi_popover.scss
css/_variables.scss
css/_videolayout_default.scss
css/connection-info.scss
css/main.scss
css/themes/_light.scss
lang/main.json
modules/UI/UI.js
modules/UI/util/JitsiPopover.js
modules/UI/videolayout/ConnectionIndicator.js

Restyling for connection status:

Connection indicator restyle

---

conference.js
css/_login_menu.scss
css/_side_toolbar_container.scss
css/input-control/_input-control.scss
index.html
interface_config.js
modules/UI/UI.js
modules/UI/authentication/LoginDialog.js
modules/UI/toolbars/Toolbar.js
modules/UI/util/UIUtil.js
service/UI/UIEvents.js

Make auth button in same style like all buttons for extended toolbar
beta:
My PR:

toolbar: authentication button changed

---

css/_connection-info.scss
css/_jitsi_popover.scss
css/_popup_menu.scss
css/_variables.scss
css/themes/_light.scss
modules/UI/util/JitsiPopover.js
modules/UI/videolayout/ConnectionIndicator.js
modules/UI/videolayout/RemoteVideo.js

In this PR I updated styles for remote video menu and did some editions from https://github.com/jitsi/jitsi-meet/pull/1007 according to comments

Menu restyle

---

modules/UI/invite/InviteDialogView.js

This PR is related to that one: https://github.com/jitsi/jitsi-meet/pull/1023

Add JSDoc and rename method

---

css/_recording.scss
css/_toolbars.scss
css/_variables.scss
css/_videolayout_default.scss
index.html

Relocate "HD" label

---

css/_variables.scss
css/aui-components/dropdown.scss

dropdown color changes

---

conference.js
modules/UI/UI.js

The gaol of this PR is to trigger conference reload when XMPP connection dies in the middle of the conference.
Requires https://github.com/jitsi/lib-jitsi-meet/pull/295

Page reloads on BOSH HTTP errors

---

lang/main.json
modules/UI/videolayout/RemoteVideo.js

Implements dialog that asks for confirmation from the user for muting remote participant

Implement warning dialog for muting remote participant

---

css/_mixins.scss
css/_popup_menu.scss
css/_videolayout_default.scss
modules/UI/videolayout/RemoteVideo.js

Fixed alignment of remote video menu, rearranged and BEMificated layout structure

Adjust alignment of remote video menu

---

lang/main.json

New tooltip for contact list

---

404.html
authError.html
close.html
close2.html
conference.js
css/_redirect_page.scss
css/_variables.scss
modules/UI/UI.js
modules/UI/feedback/FeedbackWindow.js

Redirect to different pages depending whether feedback is submitted.

Close page update

---

conference.js
modules/UI/UI.js
modules/keyboardshortcut/keyboardshortcut.js

Fixes closing of shortcuts dialog with escape button.

Esc closes shortcuts dialog

---

css/_toolbars.scss
css/_variables.scss
css/themes/_light.scss
modules/UI/toolbars/Toolbar.js

Restyled toolbar splitter

---

css/_videolayout_default.scss
modules/UI/videolayout/FilmStrip.js

Filmstrip is extended with "Hide" button

---

conference.js
modules/UI/UI.js
modules/UI/side_pannels/SidePanels.js

Adds some safety checks for disabled contactlist.

Disables loading side panels when they are disabled.

---

css/_videolayout_default.scss
index.html
modules/UI/UI.js
modules/UI/videolayout/RemoteVideo.js
modules/keyboardshortcut/keyboardshortcut.js

In this PR I fixed the order of switching between small videos when using keyboard shortcuts for that. (0 for local video, 1 - for the left-most and so on).
Also I fixed a small bug with resizing the thumbnail.

Shortcuts reversed

---

css/_filmstrip.scss
css/_jitsi_popover.scss
css/_toastr.scss
css/_toolbars.scss
css/_videolayout_default.scss
css/main.scss
index.html
modules/UI/util/JitsiPopover.js
modules/UI/videolayout/FilmStrip.js
modules/UI/videolayout/RemoteVideo.js

Fixed some visual bugs related to video thumbnails and filmstrip toolbar.
Updated class structure, extracted filmstrip styles into separate file

Filmstrip button editions

---

modules/UI/videolayout/LocalVideo.js
modules/UI/videolayout/SmallVideo.js

Adds a property to hide display name and disable update view in SmallVideo. Localvideo hides displayName and disabled update view while users is editing its name and resumes normal behaviour when editing finishes.

Adds a property to hide display name and disable update view.

---

modules/UI/videolayout/FilmStrip.js

Spinned from https://github.com/jitsi/jitsi-meet/pull/894 with conflicts resolved.

Thumbnail calculations

---

modules/UI/recording/Recording.js
modules/UI/side_pannels/chat/Chat.js
modules/UI/util/UIUtil.js

In this PR I've done editions from #1111

Editions to "clean css from js"

---

css/_contact_list.scss
css/_filmstrip.scss
css/_side_toolbar_container.scss
css/_toastr.scss
css/_toolbars.scss
css/_variables.scss
css/aui-components/dropdown.scss
css/components/_form-control.scss
css/themes/_light.scss

Fixed some visual bugs in sidebar

Fix visual bugs in sidebar

---

css/_mixins.scss
css/_variables.scss
css/_videolayout_default.scss
modules/UI/util/UIUtil.js
modules/UI/videolayout/FilmStrip.js

In this PR I added resizing of thumbnail indicators:

Thumbnail avatars

---

css/_inlay.scss
css/_jitsi_popover.scss
css/_side_toolbar_container.scss
css/_variables.scss
css/modals/_dialog.scss
css/modals/feedback/_feedback.scss
css/themes/_light.scss

Fix some ui bugs

---

404.html

link class added

---

modules/UI/videolayout/VideoLayout.js

It was not switching and staying on local video on unpinning, after change the last shown video will be used to switch to it.

Fixes unpinning local user which is dominant speaker.

---

conference.js
modules/UI/UI.js
modules/UI/recording/Recording.js
modules/UI/side_pannels/chat/Chat.js
modules/UI/side_pannels/profile/Profile.js
modules/UI/side_pannels/settings/SettingsMenu.js
modules/UI/toolbars/Toolbar.js
modules/UI/util/MessageHandler.js
modules/UI/util/UIUtil.js
modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js

Fixes various UI issues when "XMPP login + guest acees" authentication mode is enabled.

Fix the UI when anonymous domain auth is in use

---

conference.js
modules/UI/UI.js
modules/UI/reload_overlay/PageReloadOverlay.js

Adds reason as the label of the page reload event.

Log more details on page reload

---

android/app/build.gradle
android/gradle.properties

The variables in gradle.properties can be overridden on command line like: -Pversion=1.0.1.

Adds android version variable.

---

index.html

The page will be reloaded if any of the mandatory scripts/resources
fails to load. The reload will be delayed with exponential backoff
starting from 2 seconds. The retry attempt counter is passed as
'rCounter' query attribute.

Reload when resource fails to load

---

react/features/conference/components/Conference.web.js

In this PR I fixed issue with showing/hiding watermarks on the conference page.

Fix issue with watermarks

---

close.html
close.js
close2.html
conference.js

Using sessionStorage to save whether user is guest or not.

Removes guest parameter when navigating to close page.

---

css/_filmstrip.scss
css/_variables.scss
css/_videolayout_default.scss
css/themes/_light.scss

- Adds thumbnail border and border radius, thus resolving the problem with black on black while in a screen sharing session
- Fixes the thumbnail covered by left toolbar
- Fixes the display name touching the audio levels
- Adds border to thumbnail indicators and fixes some sizing there

Fixes and adjustments of UI layout

---

modules/UI/videolayout/LargeVideoManager.js
react/features/base/react/components/Watermarks.web.js
react/features/base/react/components/index.js
react/features/conference/components/Conference.web.js
react/features/welcome/components/WelcomePage.web.js

Recently, we reimplemented the watermarks in React. Unfortunately, we didn't take into account film strip-only mode.

Fix watermarks config

---

react/features/audio-mode/middleware.js
react/features/base/connection/actions.native.js
react/features/base/lib-jitsi-meet/native/RTCPeerConnection.js
react/features/base/media/components/native/VideoTrack.js
react/features/base/media/middleware.js
react/features/base/media/reducer.js
react/features/base/navigator/RouteRegistry.js
react/features/base/participants/reducer.js
react/features/base/redux/MiddlewareRegistry.js
react/features/base/redux/ReducerRegistry.js
react/features/base/tracks/actions.js
react/features/conference/components/Conference.native.js
react/features/conference/components/ParticipantView.native.js
react/features/film-strip/components/FilmStrip.js
react/features/film-strip/components/Thumbnail.js
react/features/large-video/components/LargeVideo.js
react/features/toolbar/components/AbstractToolbar.js
react/features/toolbar/components/Toolbar.native.js
react/features/unsupported-browser/components/UnsupportedMobileBrowser.js
react/features/wake-lock/middleware.js
react/features/welcome/components/AbstractWelcomePage.js
react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/WelcomePage.web.js

It turns out that it is not enough to give lib-jitsi-meet the room name
in lower case. BOSH also needs the room name in lower case.

[RN] Fix room name case sensitivity

---

react/features/base/react/components/Watermarks.web.js
react/features/conference/components/Conference.native.js
react/features/conference/components/Conference.web.js
react/features/feedback/components/FeedbackButton.web.js
react/features/feedback/components/index.js
react/features/feedback/index.js

When callstats is not configured hide the button.

Moves feedback button as a react component.

---

react/features/app/actions.js
react/features/app/components/App.native.js
react/features/app/index.js
react/features/background/actionTypes.js
react/features/background/actions.js
react/features/background/index.js
react/features/background/middleware.js
react/features/background/reducer.js
react/features/base/conference/actions.js
react/features/base/conference/index.js
react/features/base/connection/actions.native.js
react/features/base/connection/actions.web.js
react/features/base/connection/index.js
react/features/base/lib-jitsi-meet/actions.js
react/features/base/lib-jitsi-meet/index.js
react/features/base/lib-jitsi-meet/native/index.js
react/features/base/media/actions.js
react/features/base/media/index.js
react/features/base/participants/actions.js
react/features/base/participants/index.js
react/features/base/tracks/actions.js
react/features/base/tracks/index.js
react/features/full-screen/middleware.js
react/features/large-video/actions.js
react/features/large-video/index.js
react/features/room-lock/actions.js
react/features/room-lock/index.js
react/features/unsupported-browser/actions.js
react/features/unsupported-browser/index.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/352

[RN] Mute local video when app is in the background

---

android/app/build.gradle
android/app/src/main/java/org/jitsi/meet/MainApplication.java
android/settings.gradle
ios/jitsi-meet-react.xcodeproj/project.pbxproj
package.json
react/features/base/conference/functions.js
react/features/base/lib-jitsi-meet/native/polyfills-browser.js

Includes https://github.com/jitsi/jitsi-meet/pull/1321.

Polyfill Element.innerHTML

---

css/_mixins.scss
css/components/_input-slider.scss
css/main.scss
css/themes/_light.scss

Re-styling PR https://github.com/jitsi/jitsi-meet/pull/1314

Re-styles range inputs for Chrome and FF.

---

conference.js
modules/UI/avatar/Avatar.js
react/features/app/components/AbstractApp.js
react/features/base/conference/actions.js
react/features/base/participants/actions.js
react/features/base/participants/components/Avatar.web.js
react/features/base/participants/components/index.js
react/features/base/participants/functions.js
react/features/base/participants/reducer.js

Depends on https://github.com/jitsi/jitsi-meet/pull/1360

Implements avatar web

---

conference.js
modules/settings/Settings.js
react/features/base/conference/actions.js
react/features/base/conference/constants.js
react/features/base/conference/index.js
react/features/base/participants/components/ParticipantView.native.js
react/features/base/participants/functions.js
react/features/base/participants/reducer.js

Fixes the avatars for React Native to follow the implementation from web. 
Depends on https://github.com/jitsi/jitsi-meet/pull/1361

Fix avatars

---

lang/main.json
modules/UI/videolayout/ConnectionIndicator.js

Updates transport type to show multiple values as we do for addresses and ports.

Updates transport type.

---

doc/manual-install.md

This is to help understanding how things are wired.

Add a network schemas

---

CONTRIBUTING.md
README.md

Inspired by the document at jitsi/jitsi.

doc: add information about how to contribute

---

Makefile
debian/jitsi-meet-web.install

Fixes the last commit which creates a broken .deb package

added support of static directory in debian install and Makefile 

---

conference.js
lang/main.json
modules/UI/videolayout/ConnectionIndicator.js
modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/385

Handle last n in the client

---

conference.js
modules/UI/UI.js
modules/UI/videolayout/VideoLayout.js

Changes lastN event params to leaving and entering endpoint IDs.

Last n event change

---

doc/api.md

Rendered: https://github.com/saghul/jitsi-meet/blob/doc-api-params/doc/api.md

doc: improve docs on external API constructor parameters

---

lang/main.json

As requested in https://github.com/jitsi/lib-jitsi-meet/pull/421#issuecomment-289604245

edge: Add userMedia.edgeGrantPermissions in lang/main.json

---

conference.js
modules/API/API.js
modules/UI/UI.js
modules/UI/avatar/Avatar.js
modules/UI/side_pannels/profile/Profile.js
react/features/base/conference/actions.js
react/features/base/participants/actions.js
react/features/base/participants/reducer.js

executeCommand for display name, avatarURL and email was not working if called right after the iframe is created.

Fix executeCommand race condition

---

.flowconfig
modules/UI/UI.js
modules/UI/side_pannels/SidePanels.js
modules/UI/side_pannels/chat/Chat.js
react/features/film-strip/components/FilmStrip.js
react/features/toolbar/components/AbstractToolbarButton.js
react/features/toolbar/components/Notice.js

https://github.com/jitsi/jitsi-meet/pull/1397 (React Toolbar) is huge at
the time of this writing. In order to reduce it, I'm extracting changes
not directly related to React-ifying the Toolbar.

Pieces of https://github.com/jitsi/jitsi-meet/pull/1397 (React Toolbar)

---

react/features/base/media/actionTypes.js
react/features/base/media/actions.js
react/features/base/media/components/AbstractVideoTrack.js
react/features/base/media/reducer.js
react/features/base/tracks/actions.js
react/features/base/tracks/middleware.js
react/features/base/tracks/reducer.js
react/features/toolbox/components/Toolbox.native.js

See the extended descriptions.

[RN] Fix toggling camera

---

react/features/base/conference/actions.js
react/features/base/lib-jitsi-meet/index.js
react/features/base/participants/actions.js
react/features/base/participants/components/ParticipantView.native.js
react/features/base/participants/reducer.js

Extracts the commits in https://github.com/jitsi/jitsi-meet/pull/1445 which are not absolutely specific to audio-only mode.

[RN] Show avatars for participants without received videos

---

react/features/base/conference/actions.js
react/features/base/lib-jitsi-meet/middleware.js

See the individual commits for detailed notes.

[RN] Fix using the server provided config

---

react/features/base/participants/components/styles.js

[RN] Use rounded avatars in the film strip

---

modules/UI/UI.js
modules/UI/recording/Recording.js
modules/UI/util/UIUtil.js
react/features/toolbox/actionTypes.js
react/features/toolbox/actions.native.js
react/features/toolbox/actions.web.js
react/features/toolbox/reducer.js

Saúl Ibarra Corretgé reported that Recording shows an error dialog
stating "There was an error connecting to your camera". Hristo Terezov
and Yana Stamcheva traced that the problem originates in
https://github.com/jitsi/jitsi-meet/commit/da4425b5c0eb8ec06dfa9d350c15a27460f3dec2
and, more specifically, is caused by a different order of execution due
to the move of the invocation of the function Recording.init.
The solution is to bring back the execution location of Recording.init.

Fix Recording regression caused by 'React Toolbar'

---

conference.js
css/_variables.scss
css/modals/_dialog.scss
css/modals/speaker_stats/_speaker_stats.scss
react/features/base/dialog/components/AbstractDialog.js
react/features/base/dialog/components/Dialog.web.js
react/features/base/participants/actions.js

The first 3 commits of https://github.com/jitsi/jitsi-meet/pull/1499 which are small, make sense on their own and can be merged without the 4th commit.

virtuacoplenny-invite-modal

---

config.js

This config option is not used anymore.

fix(config.js): remove unused 'logStats'

---

.jshintignore
app.js
conference.js
modules/API/API.js
modules/API/constants.js
modules/API/external/external_api.js
modules/API/index.js
modules/remotecontrol/Controller.js
modules/remotecontrol/Receiver.js
modules/remotecontrol/RemoteControl.js
modules/remotecontrol/RemoteControlParticipant.js
modules/transport/.eslintrc.js
modules/transport/PostMessageTransportBackend.js
modules/transport/Transport.js
modules/transport/constants.js
modules/transport/index.js
modules/util/helpers.js
react/index.web.js

Implements alternative approach for the abstract transport(see PR #1510 ).
https://github.com/jitsi/jitsi-meet-electron/pull/9 should be merged after this PR.

Abstract transport v2

---

.flowconfig
.jshintignore
conference.js
lang/main.json
modules/remotecontrol/.eslintrc.js
modules/remotecontrol/Controller.js
modules/remotecontrol/Receiver.js
modules/remotecontrol/RemoteControl.js
modules/remotecontrol/RemoteControlParticipant.js
react/features/app/components/AbstractApp.js
react/features/base/dialog/components/AbstractDialog.js
react/features/remote-control/actions.js
react/features/remote-control/components/RemoteControlAuthorizationDialog.js
react/features/remote-control/components/index.js
react/features/remote-control/index.js

The electron part of the PR: https://github.com/jitsi/jitsi-meet-electron/pull/10.
Depends on - https://github.com/jitsi/jitsi-meet/pull/1539

Remote control - display the authorization dialog in meet

---

css/_base.scss
css/_chat.scss

1) Makes the chat scrollbar actually specific for the chat and not global as it was before.
2) Re-styles the default scrollbar used in all components except specified otherwise.

Re-styles scrollbars

---

conference.js
modules/UI/UI.js
modules/UI/ring_overlay/RingOverlay.js
react/features/base/connection/actions.web.js
react/features/conference/components/Conference.native.js
react/features/conference/components/Conference.web.js
react/features/filmstrip/components/Filmstrip.native.js
react/features/filmstrip/components/Filmstrip.web.js
react/features/large-video/components/LargeVideo.native.js
react/features/large-video/components/LargeVideo.web.js
react/features/overlay/components/OverlayContainer.js
react/features/unsupported-browser/components/HideNotificationBarStyle.js

We've had Filmstrip & LargeVideo React Components on mobile/React Native
from the start. We didn't have them on Web (because the rewrite in React
is not complete yet). However, that led to differences in the React
Component Conference on Web and mobile. In an effort to get closer to
merging the React Component Conference on Web and mobile, introduce the
React Components Filmstrip & LargeVideo on Web even if a minimal
render-only form at this time.

Web Filmstrip & LargeVideo React Components

---

modules/UI/videolayout/Filmstrip.js

Needs to be merged with new tests: https://github.com/jitsi/jitsi-meet-torture/pull/83

fix(1-on-1): remove torture test workaround, add new tests

---

index.html
modules/analytics/analytics.js

include all specified local analytics properties in analytics events

include local.html file meant to define local analytics properties

---

flow-typed/npm/redux_v3.x.x.js
react/features/toolbox/actions.native.js
react/features/toolbox/actions.web.js
react/features/toolbox/components/PrimaryToolbar.web.js
react/features/toolbox/components/SecondaryToolbar.web.js
react/features/toolbox/components/Toolbar.web.js
react/features/toolbox/functions.web.js

Based on pr from @BeatC  https://github.com/jitsi/jitsi-meet/pull/1498.

Fixes raise hand toggle state

---

modules/UI/videolayout/SmallVideo.js

Removes ' character which should not be there.

fix(SmallVideo): remove invalid character

---

react/features/toolbox/components/ToolbarButton.native.js

Introduced in
https://github.com/jitsi/jitsi-meet/commit/96e83989a54974499decf6985fd17c8990984db8
as part of a refactor + feature.

[RN] Fix regression handling ToolbarButton onPress

---

.flowconfig
app.js
webpack.config.js

`webpack -p` takes ~2 minutes on my MacBook now (and `webpack` takes ~30 seconds)

Speed webpack up

---

resources/prosody-plugins/mod_token_verification.lua
resources/prosody-plugins/token/util.lib.lua

Allows '*' in jwt to allow connecting to any room.

Handles '*' as room name in jwt.

---

react/features/base/lib-jitsi-meet/native/polyfills-webrtc.js

Required for https://github.com/jitsi/lib-jitsi-meet/pull/460
Do not merge yet !
Will require new version of 'react-native-webrtc':
https://github.com/oney/react-native-webrtc/pull/261

[RN] export RTCIceCandidate

---

conference.js
modules/remotecontrol/Receiver.js

Get rid of global APP.conference.screenSharingPromise.

ref(conference.js): remove global promise

---

modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
react/features/filmstrip/components/Filmstrip.web.js

Related torture tests: https://github.com/jitsi/jitsi-meet-torture/pull/88

feat(avatar): SmallVideo uses the existing Avatar component.

---

modules/UI/recording/Recording.js

Change messageString to msgString in _requestRecordingToken

---

react/features/app/actions.js
react/features/app/components/AbstractApp.js
react/features/app/components/App.native.js
react/features/app/components/App.web.js
react/features/app/middleware.js
react/features/app/reducer.js
react/index.native.js

https://github.com/jitsi/jitsi-meet/pull/1741

[RN] Fix passing url prop to Root and App components

---

conference.js
modules/remotecontrol/Controller.js
modules/remotecontrol/Receiver.js
modules/remotecontrol/RemoteControlParticipant.js
service/remotecontrol/Constants.js

Depends on https://github.com/jitsi/jitsi-meet-electron/pull/13

feat(remotecontrol): multi monitor support

---

css/_videolayout_default.scss
modules/UI/util/UIUtil.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
react/features/filmstrip/components/Filmstrip.web.js
react/features/filmstrip/components/web/AudioMutedIndicator.js
react/features/filmstrip/components/web/BaseIndicator.js
react/features/filmstrip/components/web/DominantSpeakerIndicator.js
react/features/filmstrip/components/web/ModeratorIndicator.js
react/features/filmstrip/components/web/RaisedHandIndicator.js
react/features/filmstrip/components/web/VideoMutedIndicator.js
react/features/filmstrip/components/web/index.js

built on top of https://github.com/jitsi/jitsi-meet/pull/1684 and has some changes from https://github.com/jitsi/jitsi-meet/pull/1681

feat(indicators): move the "top toolbar" indicators to react

---

conference.js
modules/UI/UI.js
modules/UI/videolayout/LargeContainer.js
modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/LocalVideo.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/VideoContainer.js
modules/UI/videolayout/VideoLayout.js
modules/devices/mediaDeviceHelper.js
react/features/base/media/actionTypes.js
react/features/base/media/actions.js
react/features/base/media/reducer.js
react/features/toolbox/actions.native.js
react/features/toolbox/middleware.js

This PR contains few fixes required for the work in progress on "star with screen sharing".

Improvements to the screen sharing flow

---

lang/main.json
react/features/connection-stats/components/ConnectionStatsTable.js

This depends on https://github.com/jitsi/lib-jitsi-meet/pull/539

feat: Adds TURN indication.

---

css/_videolayout_default.scss
modules/UI/videolayout/LocalVideo.js
react/features/base/media/components/AbstractVideoTrack.js
react/features/base/media/components/web/VideoTrack.js
react/features/base/media/components/web/index.js
react/features/device-selection/components/VideoInputPreview.js

torture test updates: https://github.com/jitsi/jitsi-meet-torture/pull/92. The updates cover both the local and remote video element conversion.

feat(local-video): convert to react

---

doc/quick-install.md

Closes #1789 . Add note to clarify serving choices made during quick install.

[Docs] Web server config on install

---

resources/prosody-plugins/mod_auth_token.lua
resources/prosody-plugins/mod_muc_poltergeist.lua
resources/prosody-plugins/mod_muc_size.lua
resources/prosody-plugins/mod_poltergeist_component.lua
resources/prosody-plugins/util.lib.lua

A module to join poltergeist to conference, change their statuses and real user replaces them when joining.
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/550

module-poltergeist

---

conference.js
config.js
lang/main.json
modules/UI/UI.js
service/UI/UIEvents.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/547

Add config.startScreenSharing

---

react/features/toolbox/components/ToolbarButton.native.js
react/features/toolbox/components/Toolbox.native.js
react/features/toolbox/functions.native.js

See the individual commit messages.

[RN] Toolbar button fixes

---

resources/prosody-plugins/mod_muc_poltergeist.lua
resources/prosody-plugins/mod_muc_size.lua
resources/prosody-plugins/util.lib.lua

Updates with cleaning data which we store. Adding a timeout for removing poltergeists. Updating statuses reuses previous presence so we do not lose avatar and name.

Module poltergeist update

---

conference.js
config.js
modules/API/API.js
modules/UI/videolayout/VideoLayout.js
react/features/base/conference/middleware.js

Requires https://github.com/jitsi/lib-jitsi-meet/pull/553

Start in audio only

---

modules/API/external/external_api.js
react/features/app/actions.js
react/features/base/config/parseURLParams.js
react/features/base/media/middleware.js
react/features/base/util/uri.js

Web's ExternalAPI accepts an object with properties as one of its
constructor arguments and from which it generated a URL. Mobile's
JitsiMeetView.loadURLObject is supposed to accept pretty much the same
object.

[RN] Converge with Web's ExternalAPI a bit

---

conference.js
config.js
modules/API/API.js
modules/UI/UI.js
modules/devices/mediaDeviceHelper.js
react/features/base/media/actionTypes.js
react/features/base/media/actions.js
react/features/base/media/reducer.js
react/features/toolbox/actions.native.js
react/features/toolbox/middleware.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/556

Start with audio/video muted

---

react/features/base/conference/actionTypes.js
react/features/base/conference/actions.js
react/features/base/conference/middleware.js
react/features/base/conference/reducer.js
react/features/base/media/actions.js
react/features/base/media/constants.js
react/features/base/media/middleware.js
react/features/base/media/reducer.js
react/features/base/tracks/actions.js
react/features/base/tracks/middleware.js
react/features/mobile/audio-mode/middleware.js
react/features/mobile/background/actionTypes.js
react/features/mobile/background/actions.js
react/features/mobile/background/reducer.js
react/features/mobile/full-screen/middleware.js
react/features/mobile/proximity/middleware.js
react/features/toolbox/components/Toolbox.native.js
react/features/toolbox/functions.native.js

Simplify the code by using a bitfied instead of a couple of boolean flags. This
allows us to mute the video from multiple places and only make the unmute
effective once they have all unmuted.

[RN] Refactor video muting

---

config.js

- Document each option.
- Group options semantically.
- Remove no longer existing options.
- Add some missing options.
- Fix punctuation here and there.
NOTE: This is a first step towards a full configuration overhaul, once it
materializes each of the "semantic sections" will be a JS object.

feat(config): reorganize and thoroughly document config.js

---

doc/cloud-api.md
doc/cloud-api.swagger

includes swagger for conference mapper and phone number list services

new documentation for the services which jitsi meet can consume

---

css/_toolbars.scss
css/_variables.scss
react/features/always-on-top/AlwaysOnTop.js

fix(alwaysontop): change the size of the toolbar

---

react/features/filmstrip/actionTypes.js
react/features/filmstrip/actions.js
react/features/filmstrip/components/Filmstrip.web.js
react/features/filmstrip/functions.js
react/features/filmstrip/reducer.js

Updated torture tests: https://github.com/jitsi/jitsi-meet-torture/pull/95

feat(filmstrip): show thumbnails with toolbar and on hover

---

package.json
webpack.config.js

https://github.com/jitsi/lib-jitsi-meet/pull/587

Webpack with scope hoisting

---

react/features/invite/components/AddPeopleDialog.web.js
react/features/invite/functions.js

Distinguish between 'user' and 'videosipgw' search result items and invite them with using different method.

feat(AddPeopleDialog): invite rooms

---

react/features/authentication/actionTypes.js
react/features/authentication/actions.js
react/features/authentication/components/LoginDialog.native.js
react/features/authentication/middleware.js
react/features/authentication/reducer.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/597

Login dialog fixes

---

flow-typed/npm/lodash_v4.x.x.js
flow-typed/npm/react-redux_v5.x.x.js
flow-typed/npm/redux_v3.x.x.js
flow-typed/npm/uuid_v3.x.x.js
modules/API/API.js
react/features/base/conference/actions.js
react/features/base/util/uri.js
react/features/connection-indicator/statsEmitter.js
react/features/device-selection/popup.js
react/features/dial-out/actions.js
react/features/feedback/actions.js
react/features/invite/actions.js
react/features/invite/components/InviteButton.web.js
react/features/invite/functions.js
react/features/toolbox/functions.web.js

Web's InviteButton was assigning to `this.state` which represents an incorrect state mutation. ESLint was producing an error to that effect.

Fix incorrect React Component state assignment

---

react/features/invite/components/InfoDialog.web.js

openAddPeopleDialog() got removed so instead call openDialog
with the AddPeopleDialog.

fix(info): use openDialog to open AddPeopleDialog

---

react/features/analytics/functions.js
react/features/authentication/components/WaitForOwnerDialog.native.js
react/features/authentication/middleware.js
react/features/base/conference/actionTypes.js
react/features/base/conference/actions.js
react/features/base/conference/middleware.js
react/features/base/conference/reducer.js
react/features/base/dialog/components/AbstractDialog.js
react/features/base/dialog/components/Dialog.native.js
react/features/large-video/actions.js
react/features/mobile/external-api/middleware.js
react/features/overlay/reducer.js
react/features/room-lock/actions.js
react/features/room-lock/components/PasswordRequiredPrompt.native.js
react/features/room-lock/components/PasswordRequiredPrompt.web.js
react/features/room-lock/components/RoomLockPrompt.native.js
react/features/room-lock/components/index.js
react/features/room-lock/middleware.js
react/features/unsupported-browser/middleware.js
react/features/welcome/components/AbstractWelcomePage.js

The Dialogs of room-lock were broken around the time the support for authenticated domains was finalized.

[RN] Fix room-lock

---

debian/jitsi-meet-prosody.postinst

The certificates are generated on new install or upgrade and added to the current configuration and also to the trusted certificates on the local machine.

Updates prosody config to have certificates for the auth. domain.

---

config.js
react/features/base/config/reducer.js

In conjunction with https://github.com/jitsi/lib-jitsi-meet/pull/610

Add ability to disable h264

---

react/features/app/components/AbstractApp.js
react/features/app/components/App.web.js

e09949be9f4c56af909bb6359a1e1f3f98ea6ef5 introduced the dark theme globally, but
it only applies to web, so move the logic to App.web.js

feat(dark-theme): fix breakage on mobile

---

app.js
package.json
react/features/base/lib-jitsi-meet/_.native.js
react/features/base/lib-jitsi-meet/native/polyfills-browser.js
react/features/base/participants/functions.js
webpack.config.js

Everything strophe related is now handled in lib-jitsi-meet project.
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/614

ref(strophe): Remove and cleanup all strophe related code.

---

react/features/desktop-picker/components/DesktopPicker.js

Handle the following scenarios:
- If the screens source is disabled we won't select anything by default.
- Removal of the selected source.
- Tab click.

fix(DesktopPicker): Issues with selection

---

conference.js
css/modals/video-quality/_video-quality.scss
lang/main.json
react/features/base/media/middleware.js
react/features/device-selection/components/DeviceSelectionDialogBase.js
react/features/video-quality/components/VideoQualityDialog.web.js

relies on https://github.com/jitsi/lib-jitsi-meet/pull/629

feat(audio-only): be able to lock a browser into capturing audio only

---

modules/UI/videolayout/LocalVideo.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/VideoLayout.js
react/features/display-name/components/DisplayName.web.js

I am unsure why pinning was prevented for participants without video so I'm unsure what the proposed changes could break. I did a sanity check and didn't encounter new issues, although maybe there is some timing related issue because pinning can happen earlier now.

Allow pinning of participants without video

---

react/features/always-on-top/AlwaysOnTop.js
react/features/authentication/actions.js
react/features/authentication/components/LoginDialog.native.js
react/features/authentication/components/WaitForOwnerDialog.native.js
react/features/authentication/middleware.js
react/features/base/dialog/components/AbstractDialog.js
react/features/base/dialog/components/Dialog.native.js
react/features/base/dialog/components/Dialog.web.js
react/features/base/dialog/components/StatelessDialog.web.js
react/features/base/dialog/constants.js
react/features/conference/components/Conference.native.js
react/features/feedback/components/FeedbackButton.web.js

This is one batch of PropTypes conversion  changes - post react 16 upgrade. I'm trying to figure out how we want to do all the details prior to doing one large PR that updates all of the places.

ref: define state and property types

---

react/features/base/react/components/native/Container.js
react/features/conference/components/Conference.native.js
react/features/toolbox/components/ToolbarButton.native.js
react/features/toolbox/components/Toolbox.native.js

Adds more accessibility labels required for mobile automated testing.
Required for https://github.com/jitsi/jitsi-meet-torture/pull/106

feat: add more accessibility labels

---

css/_toolbars.scss
react/features/toolbox/components/StatelessToolbarButton.js
react/features/toolbox/components/ToolbarButton.web.js

Rounded corners on the first and last buttons. Size of the hangup button
on hover.

fix(aot): Toolbar styles

---

app.js
css/_aui_reset.scss
css/_base.scss
css/_utils.scss
css/main.scss
css/modals/_dialog.scss
index.html
package-lock.json
package.json
react/features/device-selection/popup.js
static/deviceSelectionPopup.html
webpack.config.js

Finishes removing aui from the build by bringing in the used css. Also resolves an issue where css can load after javascript executes by loading css earlier.
Built on top of https://github.com/jitsi/jitsi-meet/pull/2200, which removes aui javascript and should be merged in first. Test failures will be expected until that PR is merged in.

Remove @atlassian/aui

---

react/features/app/actions.js
react/features/base/lib-jitsi-meet/functions.js
react/features/base/util/helpers.js
react/features/base/util/loadScript.native.js
react/features/base/util/loadScript.web.js
react/features/base/util/randomUtil.js
react/features/base/util/timeoutPromise.js

I chose 8 seconds pretty arbitrarily, let's pick a value which seems reasonable.
Tip for testing: use the builtin network conditioner in iOS and set packet-loss to 100%.

[RN] Add a timeout for loading the configuration

---

android/build.gradle

Small Android build fixes

---

react/features/base/i18n/i18next.js

All language assets will need to be bundled.

[RN] Disable the XHR backend on mobile

---

logging_config.js
package.json

related to https://github.com/jitsi/lib-jitsi-meet/pull/679 (will need to update the lib-jitsi-meet dep once that one gets merged before this can go in)

change TPC logs to info by default

---

lang/main.json
react/features/app-settings/actionTypes.js
react/features/app-settings/actions.js
react/features/app-settings/components/AbstractAppSettings.js
react/features/app-settings/components/AppSettings.native.js
react/features/app-settings/components/FormRow.native.js
react/features/app-settings/components/index.js
react/features/app-settings/components/styles.js
react/features/app-settings/index.js
react/features/app-settings/reducer.js
react/features/app/actions.js
react/features/app/components/AbstractApp.js
react/features/base/lib-jitsi-meet/native/Storage.js
react/features/base/profile/actionTypes.js
react/features/base/profile/actions.js
react/features/base/profile/functions.js
react/features/base/profile/index.js
react/features/base/profile/middleware.js
react/features/base/profile/reducer.js
react/features/base/redux/functions.js
react/features/base/redux/index.js
react/features/base/redux/middleware.js
react/features/base/redux/persisterconfig.json
react/features/base/redux/readme.md
react/features/welcome/components/AbstractWelcomePage.js
react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/styles.js

Please note: this is not a PR to be merged, the purpose is to use the codebase to start discussions about
- Avatars
- Persisted storage
Auto tests may fail

[RN] Add app-settings feature

---

react/features/app/components/AbstractApp.js

Fixes an issue where persisted local participant name and email was overwritten on the web

Fix local participant details on web

---

android/sdk/src/main/java/org/jitsi/meet/sdk/AndroidSettingsModule.java
react/features/mobile/permissions/middleware.js

The documentation states this is possible, so make sure we handle such errors.
Ref:
https://developer.android.com/reference/android/provider/Settings.html#ACTION_APPLICATION_DETAILS_SETTINGS

[Android] Fix crash if settings activity cannot be opened

---

logging_config.js
react/features/base/logging/reducer.js

The RN logging config needs to stay in sync with the logging_config.js

fix(RN logging): sync with logging_config.js

---

config.js
package-lock.json
package.json
react/features/base/lib-jitsi-meet/index.js
react/features/base/lib-jitsi-meet/native/polyfills-browser.js
react/features/conference/functions.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/690

fix(lib-jitsi-meet): RTCBrowserType -> browser.

---

react/features/invite/components/InviteDialog.web.js

If config.enableUserRolesBasedOnToken is true, only let moderators
and non-guests modify the password. Otherwise, only let moderators
edit the password.
Manually tested these case only:
- With falsy enableUserRolesBasedOnToken, moderators can add/remove a password, and another moderator can add/remove a password
- With falsy enableUserRolesBasedOnToken, moderators can add/remove a password, and a non-moderator cannot
- With truthy enableUserRolesBasedOnToken, authenticated moderators can add/remove a password, and a guest moderator cannot
- With truthy enableUserRolesBasedOnToken, authenticated moderators can add/remove a password, and another authenticated moderator can add/remove a password.
- With truthy enableUserRolesBasedOnToken, authenticated moderators can add/remove a password, …

fix(password): do not let guests edit password when roles are enabled

---

react/features/base/aspect-ratio/actions.js
react/features/base/conference/middleware.js

Fixes I need to make as part of PiP, but not strictly related to PiP.

Pre PiP fixes

---

modules/UI/side_pannels/chat/Replacement.js

This should resolve https://github.com/jitsi/jitsi-meet/issues/2397.

fix(chat): return formatted body to show smileys

---

config.js
package-lock.json
package.json
react/features/base/tracks/functions.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/711

feat(ss_framerate): Add config option for min/max frame rate.

---

react/features/invite/components/info-dialog/InfoDialog.web.js

This gets around the issue of a cdn page being opened.

fix(dial-in): specify url root for more numbers link

---

react/features/invite/components/dial-in-summary/DialInSummary.web.js

Looks like this guy snuck into the commit.

fix(dial-in): remove console.warn used for debugging

---

package-lock.json
package.json

The purpose is to enable the config.gatherStats parameter.

chore(lib-jitsi-meet): Update version.

---

package-lock.json
package.json

depends on https://github.com/jitsi/lib-jitsi-meet/pull/716

chore(package.json): Update lib-jitsi-meet.

---

react/features/base/lib-jitsi-meet/native/polyfills-browser.js

Fix setTimeout polyfill

---

package-lock.json
package.json

Implements the promised based getStats. Enables them for Safari and FF.

Updates lib-jitsi-meet to d4b78721.

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java

java.lang.RuntimeException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:102)
at com.rnimmersive.RNImmersiveModule.emitImmersiveStateChangeEvent(RNImmersiveModule.java:74)
at org.jitsi.meet.sdk.JitsiMeetView.onWindowFocusChanged(JitsiMeetView.java:504)
at android.view.View.dispatchWindowFocusChanged(View.java:10257)
at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1193)
at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1197)
at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1197)
at …

[Android] Fix RuntimeException in RNImmersiveModule

---

react/features/base/util/uri.js
react/features/unsupported-browser/components/UnsupportedMobileBrowser.js

Do not include the protocol part in the intent URL.

feat(UnsupportedMobileBrowser): do not include protocol in the intent

---

README.md

doc: Add dev server steps

---

CONTRIBUTING.md

Fix Typo in CONTRIBUTING.md

---

react/features/analytics/AnalyticsEvents.js
react/features/invite/components/AddPeopleDialog.web.js

Analytics for opening the dialog, closing the dialog, the
count of invites sent, and the count of invites errored.

feat(invite): add basic analytics for AddPeople dialog

---

config.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/730

feat: enableTcc, enableRemb, minParticipants.

---

react/features/invite/components/InfoDialogButton.web.js
react/features/toolbox/components/AbstractToolbarButton.js
react/features/toolbox/components/OverflowMenuButton.web.js
react/features/toolbox/components/OverflowMenuItem.web.js
react/features/toolbox/components/OverflowMenuProfileItem.web.js
react/features/toolbox/components/ToolbarButtonV2.web.js
react/features/toolbox/components/ToolboxFilmstrip.web.js
react/features/toolbox/components/ToolboxV2.web.js
react/features/toolbox/components/buttons/AudioMuteButton.web.js
react/features/toolbox/components/buttons/HangupButton.web.js
react/features/toolbox/components/buttons/VideoMuteButton.web.js

To be merged with https://github.com/jitsi/jitsi-meet-torture/pull/159.

ref(toolbar): add accessibility labels for torture tests

---

react/features/welcome/components/PagedList.android.js
react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/styles.js

Updates the hint box on the welcome screen:
- Text aligned center
- Disappearing hint box on first launch fixed (Android)

Hintbox fixes

---

conference.js
config.js
package-lock.json
package.json
react/features/conference/components/Conference.native.js
react/features/connection-indicator/index.js
react/features/connection-indicator/middleware.js
react/features/testing/actionTypes.js
react/features/testing/actions.js
react/features/testing/components/AbstractTestHint.js
react/features/testing/components/TestConnectionInfo.js
react/features/testing/components/TestHint.android.js
react/features/testing/components/TestHint.ios.js
react/features/testing/components/index.js
react/features/testing/index.js
react/features/testing/middleware.js
react/features/testing/reducer.js

Required for:
https://github.com/jitsi/jitsi-meet-torture/pull/167

Hybrid tests

---

ios/jitsi-meet.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

Looks like it's a good idea to check it in: https://stackoverflow.com/a/49564624

[iOS] Add new file created by Xcode 9.3

---

css/_variables.scss
css/modals/feedback/_feedback.scss
lang/main.json
react/features/feedback/components/FeedbackDialog.web.js

- Green stars
- Label for feedback box
- Adjust margins/padding

feat(feedback): tweak styling

---

package-lock.json
package.json

Issues with tooltips not getting repositioned to display on
screen have been addressed.

chore(deps): update @atlaskit/tooltip to 9.1.1

---

react/features/base/media/middleware.js
react/features/base/media/reducer.js
react/features/base/profile/functions.js
react/features/base/profile/middleware.js

This PR contains 2 commits:
1. Semantic changes based on post-merge feedback
2. Fix an issue that the introduction of the getPropertyValue caused (no welcome screen video when startWithVideoMuted is true)

Profile settings changes

---

ios/app/src/Info.plist
ios/sdk/src/AppInfo.m
react/features/app/functions.native.js
react/features/app/middleware.js
react/features/calendar-sync/actionTypes.js
react/features/calendar-sync/actions.js
react/features/calendar-sync/components/ConferenceNotification.native.js
react/features/calendar-sync/components/MeetingList.native.js
react/features/calendar-sync/components/index.js
react/features/calendar-sync/middleware.js
react/features/calendar-sync/reducer.js
react/features/mobile/callkit/middleware.js
react/features/share-room/middleware.js
react/features/welcome/components/PagedList.ios.js

This is the iOS part of the solution to avoid blocking other tasks, Android may come later if necessary.

Detect calendar plist

---

react/features/base/conference/middleware.js
react/features/base/react/components/native/NavigateSectionList.js
react/features/base/tracks/actions.js
react/features/base/util/uri.js
react/features/calendar-sync/components/MeetingList.native.js
react/features/calendar-sync/middleware.js
react/features/recent-list/components/RecentList.native.js

Issue: The app crashes when some characters (e.g. comma) is present in the room name, entered in the room field on the welcome screen or loaded from the calendar list.
Commit 1: Fix issue
Commit 2: Improve calendar list to avoid showing unnormalised URIs
Note: The applied RegExp may need review and further expansion.

Calendar sync crash

---

package-lock.json
package.json

Fixes custom callstats script param name.

Updates lib-jitsi-meet to 3077772.

---

ios/Podfile.lock
package-lock.json
package.json

See description in PR: https://github.com/jitsi/react-native-calendar-events/pull/1

Update calendar lib

---

Makefile
README.md

Running webpack-dev-server is not enough, so add a helper which takes are of
doing the needful.

misc: add helper make dev command

---

modules/UI/UI.js

Avoid branching on the same condition and remove unneeded showToolbar call on
filmstrip only mode.

feat(UI): simplify code

---

android/app/src/main/java/org/jitsi/meet/MainActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/InviteSearchController.java
android/sdk/src/main/java/org/jitsi/meet/sdk/InviteSearchModule.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetViewAdapter.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetViewListener.java
ios/sdk/sdk.xcodeproj/project.pbxproj
ios/sdk/src/InviteSearch.h
ios/sdk/src/InviteSearch.m
ios/sdk/src/JitsiMeet.h
ios/sdk/src/JitsiMeetView.h
ios/sdk/src/JitsiMeetView.m
ios/sdk/src/JitsiMeetViewDelegate.h
react/features/app/components/App.native.js
react/features/invite/components/AddPeopleDialog.web.js
react/features/invite/components/InviteButton.native.js
react/features/invite/functions.js
react/features/mobile/invite-search/actionTypes.js
react/features/mobile/invite-search/actions.js
react/features/mobile/invite-search/index.js
react/features/mobile/invite-search/middleware.js
react/features/mobile/invite-search/reducer.js
react/features/toolbox/components/Toolbox.native.js

* Button conditionally shown based on if the feature is enabled and available
* Hooks for launching the invite UI (delegates to the native layer)
* Hooks for using the search and dial out checks from the native layer (calls back into JS)
* Hooks for handling sending invites and passing any failures back to the native layer
* Android and iOS handling for those hooks
This PR is WIP rebasing mobile-core/invite/original on master!

[WIP]  Adds support for inviting participants during a call on mobile

---

react/features/base/media/components/native/VideoTransform.js

This PR makes the move threshold in the PnZ feature more dynamic

Add dynamic move threshold to pnz touch detection

---

css/modals/device-selection/_device-selection.scss
lang/main.json
modules/UI/UI.js
modules/UI/side_pannels/settings/SettingsMenu.js
modules/UI/util/UIUtil.js
react/features/device-selection/components/DeviceSelectionDialogBase.js
react/features/settings/functions.js
react/features/settings/index.js
react/features/toolbox/components/Toolbox.web.js

- Change copy
- Add labels to dropdowns
- Adjust color and positioning

feat(device-selection): design tweaks

---

lang/languages.json

They do not appear among options otherwise.

Updated available languages list

---

ios/app/src/ViewController.m
ios/sdk/src/invite/AddPeopleController.m
ios/sdk/src/invite/AddPeopleControllerDelegate.h
ios/sdk/src/invite/Invite.m
ios/sdk/src/invite/InviteController.m
react/features/invite/middleware.native.js

Mobile invite fixes

---

doc/api.md
modules/API/API.js
modules/API/external/external_api.js
react/features/invite/actions.js
react/features/invite/components/AddPeopleDialog.web.js
react/features/invite/functions.js
react/features/invite/middleware.native.js

Add invites to iframe API

---

connection.js
react/features/authentication/actions.js
react/features/authentication/middleware.js
react/features/base/connection/actions.native.js
react/features/base/connection/reducer.js
react/features/mobile/external-api/middleware.js

See commit msgs for more details

Adjust api events

---

package-lock.json
package.json

https://github.com/jitsi/lib-jitsi-meet/pull/740

chore(package.json): Update lib-jitsi-meet version.

---

android/app/src/main/java/org/jitsi/meet/MainActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/invite/AddPeopleController.java
android/sdk/src/main/java/org/jitsi/meet/sdk/invite/AddPeopleControllerListener.java
android/sdk/src/main/java/org/jitsi/meet/sdk/invite/InviteController.java
ios/app/src/ViewController.h
ios/app/src/ViewController.m
ios/sdk/src/JitsiMeetView.h
ios/sdk/src/JitsiMeetView.m
ios/sdk/src/invite/AddPeopleController+Private.h
ios/sdk/src/invite/AddPeopleController.h
ios/sdk/src/invite/AddPeopleController.m
ios/sdk/src/invite/AddPeopleControllerDelegate.h
ios/sdk/src/invite/Invite.m
ios/sdk/src/invite/InviteController+Private.h
ios/sdk/src/invite/InviteController.h
ios/sdk/src/invite/InviteController.m
ios/sdk/src/invite/InviteControllerDelegate.h
react/features/invite/components/InviteButton.native.js

This warnings can generate compilation errors in apps that are swift only and consuming this SDK

Fix nullability warnings from invite

---

android/sdk/src/main/java/org/jitsi/meet/sdk/ExternalAPIModule.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
react/features/base/react/components/native/styles.js
react/features/welcome/components/VideoSwitch.js
react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/styles.js

- Makes the welcome screen header taller (now aligned to Android GUI guideline suggestion instead of iOS)
- Makes the audio-video switch touchable for easier use (also separates the component, making the welcome screen render mess slightly smaller)

Welcome screen updates

---

react/features/mobile/audio-mode/middleware.js

Fixes an issue where there is no audio on iOS devices when connecting to a password locked room.

[RN] Fix ios audio issue with locked rooms

---

react/features/conference/components/Conference.native.js
react/features/toolbox/reducer.js

Show it if we are the only participant, and hide it the moment someone else
joins the conference.

[RN] Show / hide the toolbox based on the participant count

---

lang/main.json
react/features/base/participants/functions.js
react/features/base/participants/middleware.js
react/features/invite/components/info-dialog/InfoDialog.web.js
react/features/invite/functions.js
react/features/room-lock/actions.js
react/features/room-lock/components/RoomLockButton.js
react/features/room-lock/components/RoomLockPrompt.native.js

Extends the lock button functionality on mobile by unlocking the room if the room is locked and the button is pressed.

[RN] Add unlock room function to mobile

---

css/_toolbars.scss
lang/main.json
react/features/toolbox/components/web/OverflowMenuLiveStreamingItem.js
react/features/toolbox/components/web/Toolbox.js

Waiting on design confirmation that this change looks okay.

feat(toolbar): add beta tag to live streaming button

---

ios/sdk/src/picture-in-picture/PiPViewCoordinator.swift

Implement a delegate of PiPViewCoordinator to notify when user exits Picture in Picture mode

[iOS] Add a PiPViewCoordinatorDelegate

---

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioModeModule.java

The API to gather these was introduced in API level 26.

[Android] Add support for USB headset detection

---

react/features/base/known-domains/reducer.js
react/features/settings/components/native/FormRow.js
react/features/settings/components/native/FormSectionHeader.js
react/features/settings/components/native/SettingsView.js
react/features/welcome/components/SideBarItem.js
react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/WelcomePageSideBar.native.js

These are unsorted tiny changes based on @virtuacoplenny 's feedback for the WelcomeScreen facelift, that popped up after merging that change.
The changes are so small that I couldn't split them up to meaningful commits, but I'm happy to do that if need be.

[RN] WelcomeScreen post-merge changes

---

package-lock.json
package.json

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/748/commits

chore(lib-jitsi-meet): Update.

---

react/features/base/styles/functions.js

The following import chain is braking the bundle
AOT->base/toolbox->base/styles->base/react->base/i18n

fix(aot): JS error

---

lang/languages.json

Please add Greek to available languages, in order to start translating @ Poodle.

Add Greek to languages

---

config.js
react/features/base/config/functions.js

don't merge until https://github.com/jitsi/lib-jitsi-meet/pull/756 is in

document layer suspension config and add to whitelist

---

react/features/calendar-sync/middleware.js

With this change, calendar tab only shows the first occasion of a recurring meeting

[RN] Make the calendar list distinct

---

package-lock.json
package.json

~waiting for some deploy stuff to get cleared up first~ Deploy is done so this can be merged in now.

chore(deps): update lib to e7b81910 for layer suspension

---

react/features/mobile/callkit/middleware.js

See each individual commit's description.

[iOS]: Fix several CallKit issues

---

react/features/mobile/callkit/middleware.js

Your truly introduced this regression in
8c7a3f16b10d7e5b2b27f353f838e9446164fe75, alas.
The audio only mode is used to set the CallKit call type. This affects the
behavior on the recent calls entries (calls are marked either as audio or video
calls).
Sync both at the start and for transitions. The previous code was working by
chance (in a way): when the CallKit UI is presented the local video is muted,
which triggers a SET_VIDEO_MUTED action, at which point the audio-only mode was
checked for. Now we are more explicit and act on SET_AUDIO_MUTED.

[iOS] Fix setting call type in CallKit

---

resources/prosody-plugins/mod_muc_call.lua
resources/prosody-plugins/mod_muc_poltergeist.lua

The original presence stanza generation code for a poltergeist
has been re-factored and simplified a bit. Every time a
poltergeist presence is updated we first check that the poltergeist
still exists.

Preventing expired notification for poltergeist that have left.

---

react/features/connection-indicator/components/ConnectionIndicator.js

old values: 0-39% -> red, 40-69% -> yellow, 70%+ -> green
new values: 0-9% -> red, 10-29% -> yellow, 30%+ -> green

change the levels for each gsm bar color

---

ios/Podfile.lock

Syntax changed slightly with an update to CocoaPods.

[iOS] Update Podfile.lock

---

resources/prosody-plugins/mod_muc_call.lua
resources/prosody-plugins/mod_muc_poltergeist.lua
resources/prosody-plugins/poltergeist.lib.lua

~~Please don't merge yet. I need to add some documentation and try using the re-factor'ed code to fix some lingering call flow bugs to see if it's worth it.~~
~~Just letting you know that this is in the works and seeking initial feedback.~~
I've addressed comments from the previous commits and have squashed into one refactor commit. I've double checked my tab chars and adjusted my editor settings, but please check again.

Poltergeist refactor

---

css/_atlaskit_overrides.scss
css/_chat.scss
css/_filmstrip.scss
css/_side_toolbar_container.scss
css/_toolbars.scss
css/_vertical_filmstrip_overrides.scss
css/main.scss
css/modals/invite/_info.scss
modules/UI/UI.js
react/features/filmstrip/components/web/Filmstrip.js

Very likely I broke something subtle and I'm prepared to fix it.

ref(toolbar): remove use-new-toolbox class

---

package-lock.json
package.json

Detects msid changes and signals them, part of fixing start A/V muted using Firefox.

Syncs with latest lib-jitsi-meet (98acf13).

---

conference.js
doc/api.md
modules/API/API.js
modules/API/external/external_api.js

Ping @hristoterezov 
Need Help.

Added emailChange listener to API

---

lang/main.json
react/features/recording/actionTypes.js
react/features/recording/actions.js
react/features/recording/components/LiveStream/AbstractLiveStreamButton.js
react/features/recording/components/LiveStream/AbstractStartLiveStreamDialog.js
react/features/recording/components/LiveStream/AbstractStopLiveStreamDialog.js
react/features/recording/components/LiveStream/AbstractStreamKeyForm.js
react/features/recording/components/LiveStream/LiveStreamButton.native.js
react/features/recording/components/LiveStream/LiveStreamButton.web.js
react/features/recording/components/LiveStream/StartLiveStreamDialog.native.js
react/features/recording/components/LiveStream/StartLiveStreamDialog.web.js
react/features/recording/components/LiveStream/StopLiveStreamDialog.native.js
react/features/recording/components/LiveStream/StopLiveStreamDialog.web.js
react/features/recording/components/LiveStream/StreamKeyForm.native.js
react/features/recording/components/LiveStream/StreamKeyForm.web.js
react/features/recording/components/LiveStream/index.js
react/features/recording/components/LiveStream/styles.js
react/features/recording/components/index.js
react/features/recording/constants.js
react/features/recording/googleApi.js
react/features/recording/middleware.js
react/features/recording/reducer.js
react/features/toolbox/components/native/OverflowMenu.js
react/features/toolbox/components/web/Toolbox.js

Note: Google sign-in is not supported on mobile yet, waiting for later decision, but some of the abstraction around it are already prepared in the abstract classes.

[RN] Implement streaming on mobile

---

.travis.yml
ios/travis-ci/build-ipa.sh

Required for https://github.com/jitsi/jitsi-meet/pull/3329

Travis add 'pod update'

---

android/build.gradle
index.android.js
logging_config.js
package-lock.json
package.json
react/features/always-on-top/AudioMuteButton.js
react/features/always-on-top/VideoMuteButton.js
react/features/app/components/App.native.js
react/features/base/conference/functions.js
react/features/base/conference/middleware.js
react/features/base/lib-jitsi-meet/functions.js
react/features/base/lib-jitsi-meet/native/RTCPeerConnection.js
react/features/base/lib-jitsi-meet/native/polyfills-browser.js
react/features/base/logging/reducer.js
react/features/base/media/components/native/VideoTrack.js
react/features/base/media/components/native/VideoTransform.js
react/features/base/media/components/native/styles.js
react/features/base/tracks/functions.js
react/features/base/util/uri.js
react/features/mobile/audio-mode/middleware.js
react/features/mobile/picture-in-picture/actions.js
react/features/share-room/middleware.js
react/index.native.js

This started out as performance work, however I haven't been able to measure its impact because the Android Studio profiler seems to have a bug which causes a crash on the app being profiled, oh well!
At any rate, here are the pros and cons:
Pros:
- Newer JSC means support for new JS features natively
- Uniform JS support across platforms
- No more polyfills specific to Android
Cons:
- Not part of official react-native
- Requires bumping SDK to 21

[Android] Update JSC version

---

config.js
lang/main.json
package-lock.json
package.json
react/features/base/config/functions.js
react/features/base/lib-jitsi-meet/index.js
react/features/connection-indicator/components/ConnectionIndicator.js
react/features/connection-indicator/statsEmitter.js
react/features/connection-stats/components/ConnectionStatsTable.js

feat: Displays the E2E RTT in the connection stats table.

---

ios/Podfile.lock
package-lock.json
package.json

Includes a fix for not running expensive operations on the main thread.

[RN] Update calendar-events dependency

---

conference.js

This makes the logs more readable.

Print a nicer log message on participant join/part

---

lang/main.json
react/features/base/util/uri.js
react/features/calendar-sync/actions.js
react/features/calendar-sync/functions.any.js
react/features/calendar-sync/web/googleCalendar.js
react/features/calendar-sync/web/microsoftCalendar.js
react/features/google-api/actions.js
react/features/google-api/googleApi.js
react/features/invite/components/info-dialog/InfoDialog.web.js
react/features/invite/functions.js
react/features/share-room/actionTypes.js
react/features/share-room/actions.js
react/features/share-room/middleware.js

Share text generation between calendar-sync and the share-room feature.

Implements calendar entries edit.

---

ios/Podfile.lock
package-lock.json
package.json

Fixes a crash on Android. Upstream PR: https://github.com/wmcmahan/react-native-calendar-events/pull/186

[RN] Update react-native-calendar-events

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/org/jitsi/meet/MainApplication.java
package-lock.json
package.json

LeakCanary is a memory leak detection library which will run only in Debug mode.

[Android] Add LeakCanary

---

doc/manual-install.md

the abbreviation in full
and a link to wikipedia

What is BOSH

---

android/app/src/main/java/org/jitsi/meet/MainActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivityInterface.java
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactActivityLifecycleCallbacks.java
ios/Podfile
ios/Podfile.lock
package-lock.json
package.json
react/features/base/lib-jitsi-meet/native/polyfills-webrtc.js
react/features/welcome/components/WelcomePage.native.js

Depends on https://github.com/jitsi/react-native-webrtc/pull/39

[RN] Drop the react-native-permissions dependency

---

lang/main.json
modules/UI/UI.js

Maybe kickMessage needs changing.

fix(notification): change title for kick notification

---

lang/main.json
react/features/app/components/App.native.js
react/features/app/components/App.web.js
react/features/base/app/components/BaseApp.js
react/features/base/dialog/components/DialogContainer.js
react/features/base/dialog/components/DialogContent.native.js
react/features/base/dialog/components/index.js
react/features/base/dialog/components/styles.js
react/features/base/react/components/NavigateSectionList.js
react/features/base/react/components/native/NavigateSectionListItem.js
react/features/base/react/components/native/styles.js
react/features/calendar-sync/actions.any.js
react/features/calendar-sync/actions.native.js
react/features/calendar-sync/actions.web.js
react/features/calendar-sync/components/BaseCalendarList.js
react/features/calendar-sync/components/ConferenceNotification.native.js
react/features/calendar-sync/components/UpdateCalendarEventDialog.native.js
react/features/calendar-sync/components/index.js
react/features/calendar-sync/functions.any.js
react/features/calendar-sync/functions.native.js
react/features/conference/components/Conference.native.js
react/features/conference/components/Conference.web.js
react/features/invite/functions.js
react/features/welcome/components/WelcomePage.web.js

@damencho: Since Yana told me that there will be a follow up change on web to have a similar confirmation dialog, I left some web parts untouched that I would have normally refactored. Can you please check how the secondaryAction works in the NavigateSectionList and try to see if that could fit to web too? I really don't like the react components being pushed into the displayableItem in BaseCalendarList, because I intended that object to be pure data (perhaps the name is misleading though). But of course, if that's the only way to do it on web, I'm fine with it!

[RN] Add calendar invite

---

modules/UI/UI.js
modules/UI/videolayout/Filmstrip.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/video-layout/middleware.web.js

Re-implementation of https://github.com/jitsi/jitsi-meet/pull/1926.

feat(filmstrip): reactify the filmstrip toggle button

---

css/_atlaskit_overrides.scss
css/modals/_dialog.scss
package-lock.json
package.json
react/features/base/dialog/components/DialogWithTabs.web.js
react/features/desktop-picker/components/DesktopPicker.js
react/features/device-selection/components/AudioInputPreview.js
react/features/welcome/components/WelcomePage.web.js

Dropdown-menu needs to be updated to prevent an infinite loop when opening a dropdown menu in a tab component within a modal.

Update atlaskit dropdown-menu and tabs

---

react/features/device-selection/components/DeviceSelection.js
react/features/device-selection/functions.js
react/features/settings/DeviceSelectionPopup.js

See: https://github.com/jitsi/lib-jitsi-meet/pull/818

feat(permissions): adjust to changes in permissions checking

---

package.json
react/features/base/participants/functions.js
webpack.config.js

It was moved to js-utils, so make use of it.

feat(Participant): reuse avatar URL generation logic

---

react/features/recording/components/LiveStream/GoogleSigninForm.native.js

It doesn't seem to work properly.

[iOS] Don't show google signin button on iOS <= 10

---

package-lock.json
package.json

Updates LJM to fix grey overlay with "user is having connectivity issues" caused by remote track overwrite.

deps: update LJM to fix grey overlay

---

react/features/google-api/googleApi.native.js

This commit fixes the stream display name on mobile

[RN] Fix YouTube channel name list

---

package-lock.json
package.json

Updated to latest node-sass to support node version 10

updated node-sass version for node 10

---

react/features/welcome/components/LocalVideoTrackUnderlay.native.js

Remove caching of calculated styles, thereby removing
componentWillReceiveProps, by passing in base styles
and passed in styles when rendering.

ref(local-video): merge styles at render

---

package-lock.json
package.json

Introduces the sdpSemantics configuration option.

deps: update lib-jitsi-meet

---

app.js
package-lock.json
package.json

AFAICT this is not used anywhere / by anyone. Can you PTAL @virtuacoplenny ?

deps: remove no longer used autosize

---

modules/UI/etherpad/Etherpad.js

showControls instead of showControns

Fix typo which made etherpad module unusable

---

android/README.md
android/app/build.gradle
android/build.gradle
android/gradle.properties
android/scripts/publish-android-jsc.sh
android/scripts/publish-react-native.sh
android/sdk/build.gradle

Update building instructions and add helper scripts to publish artifacts (for RN and JSC) to Maven.

Update Android build

---

.github/stale.yml

https://probot.github.io/apps/stale/

misc: add stale bot to close stalled issues and PRs

---

react/features/calendar-sync/functions.any.js

This PR is to avoid the calendar to threat static jitsi URLs (such as https://www.google.com/url?q=https://meet.jit.si/static/dialInInfo.html?room%3DSquareWerewolvesUniteThoughtfully&sa=D&usg=AOvVaw0-C-oublfrzxznXooKRWEr) as a meeting link.

Exclude static jitsi links from calendar fetch

---

modules/UI/UI.js
modules/UI/shared_video/SharedVideoThumb.js
modules/UI/videolayout/LocalVideo.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js

Will require torture test updates: https://github.com/jitsi/jitsi-meet-torture/pull/216

feat(tile-view): double click to pin

---

ios/app/app.xcodeproj/project.pbxproj

Also update the bundle ID since we don't release with that anyway.

ios: update development team

---

android/README.md

Add instructions to enable 32bit mode for react-native.
See https://github.com/facebook/react-native/issues/2814#issuecomment-141417494

Added notes to enable 32bit mode for react-native

---

Makefile
config.js
package-lock.json
package.json
react/features/analytics/functions.js
react/features/analytics/handlers/AbstractHandler.js
react/features/analytics/handlers/AmplitudeHandler.js
react/features/analytics/handlers/GoogleAnalyticsHandler.js
react/features/base/config/reducer.js
react/features/base/lib-jitsi-meet/functions.js
webpack.config.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/847

feat(Amplitude): Integration.

---

ios/README.md

Mention the availability of CocoaPods.

ios: update SDK installation instructions

---

doc/manual-install.md

Seems like the JVB and JiCoFo does not workd on latest JAVA versions
Works perfectly with JAVA 8
Ref #3543

Specifying JAVA Version 8

---

react/features/base/dialog/components/native/BaseDialog.js
react/features/base/dialog/components/native/InputDialog.js

This fixes a bug around the new input dialog value passing

[RN] Fix input dialog value bug

---

react/features/base/dialog/components/native/BottomSheet.js
react/features/base/react/components/native/BackButton.js
react/features/base/react/components/native/HeaderLabel.js
react/features/base/react/components/native/Modal.js
react/features/base/react/components/native/index.js
react/features/settings/components/native/SettingsView.js
react/features/settings/components/native/styles.js

This is a preparing PR for the chat functionality, but is not closely related. It's here to make the chat PR smaller.

[RN] Header and Modal component refactor

---

conference.js
modules/UI/UI.js
react/features/base/conference/actions.js
react/features/base/participants/actions.js
react/features/base/participants/functions.js
react/features/display-name/actions.js

Some things that were still in the back of my head after the last 2 PRs

Displayname improvements

---

.github/ISSUE_TEMPLATE/2-help.md

No table will be created otherwise and the issue template fails :-/

misc: fixup  MD format

---

.gitignore

Ignoring files that VSCode generates on editing Java files

Add VSCode files to gitignore

---

android/sdk/src/main/java/org/jitsi/meet/sdk/PictureInPictureModule.java
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactPackageAdapter.java
ios/sdk/src/JitsiMeetView.m
ios/sdk/src/dropbox/Dropbox.m
react/features/recording/components/LiveStream/native/GoogleSigninForm.js

Run into these while working on the new SDK API.

Misc Android / iOS fixes

---

android/app/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/dropbox/Dropbox.java
ios/app/app.xcodeproj/project.pbxproj
ios/sdk/src/Info.plist
react/features/recording/components/Recording/native/StartRecordingDialog.js
react/features/toolbox/components/native/OverflowMenu.js

Please look at the commit messages.

Dropbox fixes

---

android/gradle.properties
ios/app/src/Info.plist

This marks our switch to CalVer: http://calver.org/
Major: year
Minor: release number
Patch: build (in case we need to retry)

rn: set version to 19.0.0

---

resources/prosody-plugins/token/util.lib.lua

Opened to fix prosody modules to accept wildcards in 'sub' claims of the incoming token, not just wildcards in the 'room' claim of the token

supports a '*' in the sub claim to allow access to any room

---

package-lock.json
package.json
react/features/base/lib-jitsi-meet/native/polyfills-browser.js

Requires: https://github.com/jitsi/lib-jitsi-meet/pull/864

Better callstats

---

react/features/invite/actions.js
react/features/invite/components/dial-in-summary/DialInSummary.web.js
react/features/invite/functions.js

Include the conference URL when looking up Dial In numbers, makes consistent with the conference ID request

adds conference to lookup of dial in numbers

---

react/features/base/util/uri.js
react/features/deep-linking/functions.js

rn: finally fix Android deep-linking

---

ios/sdk/src/AudioMode.m

When we are in the default state (ie, not in a meeting) we shouldn't override
the AVAudioSession category and mode. It's a singleton and we might be bothering
other components of the host app which use it.

ios: don't override AVAudioSession category and mode in default state

---

react/features/invite/functions.js

changed to .ajax from .post to allow content type to be set

invite post to use application/JSON

---

react/features/mobile/call-integration/middleware.js

The conference disconnection process is asynchronous which means there's no guarantee that there will be CONFERENCE_LEFT event for the old conference, before the next conference is joined. Because of that we can end up with two simultaneous calls on the native side which is not always supported. End the call on CONFERENCE_WILL_LEAVE to fix this corner case.

fix(mobile/call-integration): cleanup if leave takes too long

---

modules/API/API.js
modules/API/external/external_api.js
react/features/feedback/components/FeedbackDialog.web.js

Adds a new event fired when Jitsi Meet shows the feedback prompt.

feat(external API): add feedbackPromptDisplayed event

---

doc/faq.md
doc/quick-install.md

**Requirement:**
The *Advanced Configuration* section of quick-install.md can benefit from having a few additional pointers for first-timers.
In addition to the above, the forums at https://community.jitsi.org/c/install-config can benefit from a having a quick go-to list of common issues
**Resolution:**
Added a new faq.md and a hyperlink to it where appropriate in quick-install.md

Added links related to NAT config in a new FAQ doc

---

css/deep-linking/_mobile.scss
css/modals/invite/_info.scss

Tested FF, Chrome, Safari and mobile Chrome.

Fixes toll free position.

---

doc/integrations.md

Google, Microsoft and Dropbox for now.

Adds integrations doc.

---

react/features/base/dialog/components/native/ConfirmDialog.js
react/features/base/dialog/components/web/StatelessDialog.js
react/features/base/dialog/constants.js
react/features/desktop-picker/components/DesktopPicker.js
react/features/feedback/components/FeedbackDialog.web.js
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.js
react/features/keyboard-shortcuts/components/KeyboardShortcutsDialog.web.js
react/features/local-recording/components/LocalRecordingInfoDialog.js
react/features/overlay/components/AbstractPageReloadOverlay.js
react/features/overlay/components/OverlayFrame.native.js
react/features/overlay/components/OverlayFrame.web.js
react/features/overlay/components/PageReloadOverlay.native.js
react/features/overlay/components/PageReloadOverlay.web.js
react/features/overlay/components/styles.js
react/features/recording/components/LiveStream/native/StartLiveStreamDialog.js
react/features/recording/components/LiveStream/web/StartLiveStreamDialog.js
react/features/recording/components/LiveStream/web/StopLiveStreamDialog.js
react/features/recording/components/Recording/web/StartRecordingDialog.js
react/features/recording/components/Recording/web/StopRecordingDialog.js
react/features/remote-control/components/RemoteControlAuthorizationDialog.js
react/features/remote-video-menu/components/web/KickRemoteParticipantDialog.js
react/features/remote-video-menu/components/web/MuteRemoteParticipantDialog.js
react/features/speaker-stats/components/SpeakerStats.js
react/features/video-quality/components/VideoQualityDialog.web.js

This PR replaces the red screen on mobile with a standard dialog

[RN] Replace red screen with dialog

---

Makefile
android/sdk/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
android/sdk/src/main/java/org/jitsi/meet/sdk/analytics/AmplitudeModule.java
ios/Podfile
ios/Podfile.lock
ios/sdk/sdk.xcodeproj/project.pbxproj
ios/sdk/src/analytics/AmplitudeModule.m
package-lock.json
package.json
react/features/analytics/functions.js
react/features/analytics/handlers/AmplitudeHandler.js
react/features/analytics/handlers/amplitude/Amplitude.native.js
react/features/analytics/handlers/amplitude/Amplitude.web.js
react/features/analytics/handlers/amplitude/index.js
react/features/analytics/handlers/index.js
react/features/analytics/middleware.js
react/features/base/lib-jitsi-meet/functions.js
webpack.config.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/861

feat(amplitude): Mobile.

---

css/_variables.scss
css/deep-linking/_mobile.scss
css/modals/invite/_info.scss
doc/sipgw-config.md
interface_config.js
lang/main.json
react/features/calendar-sync/components/CalendarList.web.js

* Removes unused ADD_PEOPLE_APP_NAME
* Moves deep-link header background and logo size as variables.
* Fixes more numbers page space in the header.
* Fixes left padding on deep-linking mobile page.

Adds provider name to fix welcomepage text.

---

ios/app/app.xcodeproj/project.pbxproj

Signing wouldn't work, disabling it and enabling it again created these changes.
Oh well!

ios: xcode project change shenanigans

---

android/sdk/src/main/AndroidManifest.xml
android/sdk/src/main/java/org/jitsi/meet/sdk/AmplitudeModule.java
android/sdk/src/main/java/org/jitsi/meet/sdk/DropboxModule.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java

And some extra Android improvements.

android: add JitsiMeetActivity.launch helper methods

---

README.md

1.	Deleted pronoun ‘You”
2.	Deleted empty phrase ‘the need for’ and repetition ‘yourself’
3.	Changed to active voice It allows users to -> Users can
4.	Deleted unnecessary adjective quite which cause hedging.
5.	Debian-based systems -> system. Deleted pronoun
6.	Cannot understand the sentence  
To make the project you must force it to take the sources as 'npm update' will not do it.
Hopefully means
To make the project you must force it to take the sources as 'npm update':
7.	Another confusing sentence to understand
So now after changes in local `lib-jitsi-meet` repository you can rebuild it with `npm run install` and your `jitsi-meet` repository will use that modified library.
Hopefully means
After changes in local `lib-jitsi-meet` repository, you can rebuild it with `npm run install` and …

Edited README.md for better readability

---

ios/fastlane/Fastfile

https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up

ios: make sure Fastlane can update the provisioning profile

---

doc/api.md

Based on https://github.com/jitsi/jitsi-meet/pull/4002 in order to update the devices handling examples as well.

docs(api.md): Comply with our coding style.

---

react/features/notifications/actionTypes.js
react/features/notifications/components/index.native.js
react/features/notifications/components/index.web.js
react/features/notifications/components/native/Notification.js
react/features/notifications/components/native/NotificationsContainer.js
react/features/notifications/components/native/index.js
react/features/notifications/components/native/styles.js
react/features/notifications/components/web/Notification.js
react/features/notifications/components/web/NotificationsContainer.js
react/features/notifications/components/web/index.js
react/features/notifications/constants.js
react/features/notifications/functions.js
react/features/notifications/index.js
react/features/notifications/reducer.js

A side-track improvement that came out of my raised hand development. No functional change.

Reorg notifications feature files

---

react/features/conference/functions.js

https://github.com/jitsi/lib-jitsi-meet/pull/835 must land first.

misc: don't show a warning on Safari with VP8

---

android/build.gradle
android/scripts/release-sdk.sh
android/sdk/build.gradle

- don't hardcode defaults in gradle files
- allow for uploading also to HTTP URLs
- support HTTP authentication when publishing

android: improve SDK release script

---

interface_config.js
react/features/video-layout/actionTypes.js
react/features/video-layout/actions.js
react/features/video-layout/middleware.web.js
react/features/video-layout/reducer.js
react/features/video-layout/subscriber.js

Meant to make this a draft PR.

feat(screenshare): add auto pin of latest screen share

---

react/features/video-layout/subscriber.js

fix(screenshare): properly gate autopin behavior behind flag check

---

conference.js
modules/devices/mediaDeviceHelper.js
package-lock.json
package.json

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/888

fix(device-selection): Default device change.

---

react/features/conference/functions.js

This reverts commit 9625be1db3f69ac31fbc073fd970c737be3ccf38.

Revert "misc: don't show a warning on Safari with VP8"

---

react/features/video-layout/reducer.js

fix(follow-me): remove duplicate default state

---

package-lock.json
package.json

Fix mobile iOS issues

---

ios/sdk/src/callkit/JMCallKitEmitter.swift

Replace the Swift array with an Objective-C one, since it's going to store
Objective-C objects and not Swift objects (or Swift objects which inherit from
NSObject, which is equivalent).
This avoids the need for JMCallKitEventListenerWrapper entirely, since an
NSArray can store NSObjectProtocol objects, unlike a Swift array, which prompted
the creation of the wrapper in the first place.

ios: simplify code for handling CallKit listeners

---

doc/manual-install.md

Fix NAT documentation

---

package-lock.json
package.json
react/features/chat/components/AbstractChatMessage.js
react/features/chat/components/native/Chat.js
react/features/chat/components/native/ChatInputBar.js
react/features/chat/components/native/ChatMessage.js
react/features/chat/components/native/MessageContainer.js
react/features/chat/components/native/styles.js
react/features/chat/functions.js
react/features/chat/reducer.js

This fixes an issue on Samsung phones with Samsung keyboard

[RN] Fix Samsung keyboard issue on the Chat screen

---

react/features/device-selection/components/DeviceSelection.js

The issue is if you quickly click Devices and then another tab, we may leave open tracks (video light stays on even when you are video muted).
Thanks @virtuacoplenny for the proposed solutions, I chose this one as simpler, wdyt?

Disposes the tracks in component was unmounted while creating those.

---

react/features/base/dialog/components/native/BottomSheet.js
react/features/base/dialog/components/native/styles.js
react/features/base/react/components/native/SlidingView.js

Out goes Modal, in goes SlidingView. Also made some necessary adjustments to SlidingView.

Refactor BottomSheet

---

package-lock.json
package.json

Minor update. Includes a fix for this Android bug: https://github.com/facebook/react-native/issues/24382

deps: react-native@0.59.5

---

android/app/build.gradle
android/app/proguard-rules.pro
android/app/src/main/java/org/jitsi/meet/GoogleServicesHelper.java
android/app/src/main/java/org/jitsi/meet/MainActivity.java
android/build.gradle
android/sdk/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/AppInfoModule.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
react/features/analytics/handlers/AmplitudeHandler.js
react/features/analytics/handlers/GoogleAnalyticsHandler.js
react/features/analytics/handlers/amplitude/Amplitude.native.js
react/features/base/config/functions.any.js
react/features/base/config/functions.native.js
react/features/base/config/functions.web.js
react/features/base/config/reducer.js
react/features/google-api/googleApi.native.js

A libre build will exclude the following:
- Analytics modules
- Google Play services GMS
- Crashlytics
- Firebase

android: add the ability to make a "libre" build

---

conference.js
lang/main.json
modules/devices/mediaDeviceHelper.js
modules/translation/translation.js
react/features/base/devices/actionTypes.js
react/features/base/devices/actions.js
react/features/base/devices/middleware.js
react/features/device-selection/actions.js
react/features/notifications/components/AbstractNotification.js
react/features/notifications/components/web/Notification.js

Adds notifications shown when a new device (not already selected as preferred) is plugged. Giving an option to the user to use it.

Notify for new device

---

css/_chat.scss
css/_variables.scss
lang/main.json
react/features/chat/components/web/Chat.js
react/features/chat/components/web/ChatInput.js
react/features/chat/components/web/ChatMessage.js

ref(chat): change some css

---

css/_chat.scss
react/features/chat/components/AbstractChatMessage.js
react/features/chat/components/web/Chat.js
react/features/chat/components/web/ChatMessage.js
react/features/chat/components/web/ChatMessageGroup.js

Built on top of https://github.com/jitsi/jitsi-meet/pull/4167, which needs to go in first.

feat(chat): on web, group messages by sender

---

ios/Podfile.lock
package-lock.json
package.json

https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0598

deps: react-native@0.59.8

---

css/_chat.scss
react/features/chat/components/AbstractChatMessage.js
react/features/chat/components/AbstractMessageContainer.js
react/features/chat/components/native/ChatMessage.js
react/features/chat/components/native/ChatMessageGroup.js
react/features/chat/components/native/MessageContainer.js
react/features/chat/components/native/styles.js
react/features/chat/components/web/Chat.js
react/features/chat/components/web/ChatMessage.js
react/features/chat/components/web/ChatMessageGroup.js
react/features/chat/components/web/MessageContainer.js

ref(chat): on native, show messages as grouped by sender

---

resources/prosody-plugins/mod_auth_token.lua
resources/prosody-plugins/mod_muc_poltergeist.lua

use optional prefix in poltergeist room lookup

updates bosh to support optional prefix

---

ios/sdk/src/callkit/JMCallKitEmitter.swift
ios/sdk/src/callkit/JMCallKitProxy.swift

This reverts commit 603d16178859953a5ee7c88c6172a88d2e22d87f.

Revert "ios: remove no longer needed code"

---

react/features/conference/components/native/Conference.js

When in a conference, try to enter PiP when pressing the back button. If this is not possible (because it's unsupported, not enabled, etc.) fall back to the previous behavior of simply hanging up.

android: enter PiP mode when pressing back button

---

css/_videolayout_default.scss
css/filmstrip/_tile_view_overrides.scss
modules/UI/videolayout/Filmstrip.js

I gave up and added javascript to make sure non-square images remain round and don't stretch.

fix(avatar): dynamically size avatar in dynamically sizable filmstrip

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java
ios/sdk/src/JitsiMeetConferenceOptions.h
ios/sdk/src/JitsiMeetConferenceOptions.m
react/features/base/conference/actions.js
react/features/base/conference/functions.js
react/features/base/conference/middleware.js
react/features/base/config/functions.any.js
react/features/conference/components/native/NavigationBar.js

Dear reviewer, see each individual commit for details.

rn: add ability to set the conference subject

---

ios/sdk/sdk.xcodeproj/project.pbxproj
ios/sdk/src/JitsiMeetView.m
ios/sdk/src/RNRootView.h
ios/sdk/src/RNRootView.m
react/index.native.js

They may contain sensitive information.

rn: avoid logging initial props in release builds

---

conference.js
modules/API/API.js
package-lock.json
package.json

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/906

Iframe API conference left fixes

---

conference.js
package-lock.json
package.json

Relies on https://github.com/jitsi/lib-jitsi-meet/pull/909 being merged and the package.json being updated afterwards.

fix(recording): do not prompt hidden participants for name

---

css/_videolayout_default.scss
react/features/large-video/components/LargeVideoBackground.web.js

fix(large-video): make blurred background fit whole screen

---

package-lock.json
package.json

Update LJM to 25ca5cbd2a93150e74f029075bc7ac734ed97a2f

Bump LJM version to increase frozen video timeout

---

modules/UI/shared_video/SharedVideoThumb.js
modules/UI/videolayout/LocalVideo.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js

Undoes the logic added in:
ebcde745ef34bd3d45a2d884825fdc48cfa16839
Requires https://github.com/jitsi/jitsi-meet-torture/pull/242

fix(tile-view): back to single click to pin

---

conference.js
package-lock.json
package.json
react/features/analytics/AnalyticsEvents.js
react/features/base/conference/middleware.js
react/features/base/lib-jitsi-meet/functions.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/919

feat(reload): on offer / answer error.

---

package-lock.json
package.json

Updates LJM to c0af82a215d0893f1999df299cfdfcbc9ce9e72a

fix: update LJM to fix reload on hangup

---

package-lock.json
package.json

Update LJM to 9bcc2a26cc94683b8ed302418695a331b450df97 in order to bring
in the analytics update which will add a property indicating how much
time has passed since the last successful XMPP request came through.

feat(analytics): time since last success in connection dropped

---

conference.js
modules/UI/UI.js
modules/UI/videolayout/VideoLayout.js
react/features/base/tracks/middleware.js
react/features/large-video/index.js
react/features/large-video/middleware.js
react/features/large-video/subscriber.js

Now switching the onstage participant and sending the select participant event should be always tied together.

Move switch large video logic to react

---

react/features/base/react/components/native/NavigateSectionListItem.js
react/features/base/react/components/native/styles.js

Brings back the button for generating meeting URLs for calendar events.

fix: bring back the add meeting URL button

---

react/features/base/color-scheme/defaultScheme.js

rn: update default color scheme

---

ios/Podfile.lock
package-lock.json
package.json

deps: update react-native-webrtc

---

lang/main.json
react/features/base/dialog/components/native/InputDialog.js
react/features/base/dialog/components/native/styles.js
react/features/room-lock/components/PasswordRequiredPrompt.native.js

This now also propagates the previous pwd value

feat: add room lock pwd error message

---

android/app/proguard-rules.pro
android/scripts/run-packager.sh
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
package-lock.json
package.json

See the commit messages for details.

android: custom initialization of the WebRTC module 

---

modules/UI/UI.js
react/features/conference/components/web/Conference.js
react/features/welcome/components/WelcomePage.web.js

Hi,
I just noticed that setting `APP_NAME` has no effect on the welcome page. This change fixes that issue.

fix welcome page title

---

react/features/base/color-scheme/defaultScheme.js
react/features/conference/components/native/Conference.js
react/features/conference/components/native/NavigationBar.js
react/features/conference/components/native/styles.js
react/features/toolbox/components/native/Toolbox.js
react/features/toolbox/components/native/styles.js
react/features/toolbox/constants.js
react/features/toolbox/index.js

New toolbar style

---

package-lock.json
package.json
react/features/base/tracks/functions.js
react/features/base/user-interaction/actionTypes.js
react/features/base/user-interaction/middleware.js
react/features/base/user-interaction/reducer.js

Follow up to #4429. Relies on https://github.com/jitsi/lib-jitsi-meet/pull/935.

Ref logic around detecting user interaction

---

react/features/base/toolbox/components/BetaTag.js
react/features/base/toolbox/components/index.js
react/features/blur/components/VideoBlurButton.js
react/features/recording/components/LiveStream/web/LiveStreamButton.js

fix(blur): add beta label to toolbar button

---

package-lock.json
package.json

Bumps LJM to include https://github.com/jitsi/lib-jitsi-meet/pull/951

Update LJM to get analytics fixes

---

lang/main.json
modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/SmallVideo.js
react/features/base/avatar/components/Avatar.js
react/features/base/lastn/middleware.js
react/features/base/participants/components/ParticipantView.native.js
react/features/base/participants/functions.js
react/features/filmstrip/components/native/Thumbnail.js

It's an evolution of audio-only mode, where we also allow for receiving a remote
screen-share.
Diving deeper: this basically sets last N to 1 or 0 depending on the
availability of a screen-share.

audio-only: implement initial "low bandwidth mode"

---

conference.js
doc/api.md
modules/API/API.js
modules/API/external/external_api.js
react/features/external-api/middleware.js

Feature/enable dominant speaker changed event in API

---

lang/main.json

fix(deep-linking): add back description copy

---

package-lock.json
package.json

Upstream PR: https://github.com/wmcmahan/react-native-calendar-events/pull/268

android: fix crash when parsing calendar events

---

react/features/conference/components/native/Conference.js
react/features/filmstrip/functions.native.js
react/features/toolbox/functions.native.js

There is more, see each commit's message.

 rn,filmstrip: ignore the 'visible' parameter on mobile

---

react/features/video-layout/subscriber.js

Any overrides set on interfaceConfig are not
applied on module load. As such, call to get
the value of the auto pin setting, providing
time for the bootstrapping to set overrides.
Otherwise iframe api users cannot override
the setting.

fix(pinning): dynamically check auto-pin setting

---

android/sdk/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
android/settings.gradle
ios/Podfile
ios/Podfile.lock
package-lock.json
package.json
react/features/analytics/AnalyticsEvents.js
react/features/analytics/middleware.js
react/features/base/net-info/NetworkInfoService.native.js
react/features/base/net-info/NetworkInfoService.web.js
react/features/base/net-info/actionTypes.js
react/features/base/net-info/actions.js
react/features/base/net-info/constants.js
react/features/base/net-info/events.js
react/features/base/net-info/index.js
react/features/base/net-info/logger.js
react/features/base/net-info/middleware.js
react/features/base/net-info/reducer.js
react/features/base/net-info/types.js

Will emit new 'network.info' action with the online/offline status and extra details for native like the network type and 'isConnectionExpensive' flag.

feat: report analytics for the network connection

---

package-lock.json
package.json

This updates ljm to the latest commit that includes https://github.com/jitsi/lib-jitsi-meet/pull/970.

deps: lib-jitsi-meet@latest

---

package-lock.json
package.json

chore(deps): update LJM to 00920c0f655a74c757c7fef2cdbd053ae4d1f485

---

package-lock.json
package.json

It was referencing LJM from a PR branch instead of the master.

chore(deps): update LJM to dda16f607ed190a0664d643d511cc87f9bfceaf1

---

package-lock.json
package.json

Uses sendBeacon to send xmpp presence unavailable on unloading the window(leaving the conference).

chore(deps): update LJM to a61941fc9a1927daedc1c9446e4036702964b38a

---

resources/prosody-plugins/mod_filter_iq_rayo.lua

Adds option to limit number of outgoing calls per user.

Updates rayo filter to add user token info to dial messages.

---

react/features/base/config/reducer.js
react/features/base/react/Platform.web.js

It crashes like hell. See:
https://bugs.chromium.org/p/webrtc/issues/detail?id=11002

rn: disable H.264 on iOS 10 devices

---

package-lock.json
package.json

Fixes iOS crashes when restarting the AudioUnit in case of interruption.

deps: react-native-webrtc@latest

---

conference.js
lang/main.json
package-lock.json
package.json
react/features/base/conference/actions.js
react/features/chat/components/AbstractChatMessage.js
react/features/chat/components/native/ChatMessage.js
react/features/chat/components/web/ChatMessage.js
react/features/chat/middleware.js

Follow up commit for https://github.com/jitsi/lib-jitsi-meet/commit/f9808adb8eb523bae3318f9f8ef49b544651485f
...with some refactor too

Fix chat error message

---

react/features/base/color-scheme/ColorSchemeRegistry.js
react/features/base/color-scheme/defaultScheme.js
react/features/base/dialog/components/native/styles.js
react/features/chat/components/AbstractChatMessage.js
react/features/chat/components/AbstractMessageRecipient.js
react/features/chat/components/native/Chat.js
react/features/chat/components/native/ChatMessage.js
react/features/chat/components/native/ChatMessageGroup.js
react/features/chat/components/native/MessageRecipient.js
react/features/chat/components/native/styles.js
react/features/chat/components/web/ChatMessage.js
react/features/chat/components/web/MessageContainer.js
react/features/chat/components/web/MessageRecipient.js
react/features/chat/constants.js
react/features/chat/middleware.js

Update chat colors and layout based on brand guidelines.

feat: add chat color scheming

---

css/_mini_toolbox.scss
css/_toolbars.scss
css/main.scss

fix: fix filmstrip-only toolbar

---

css/_chat.scss
css/_variables.scss
react/features/chat/components/web/Chat.js
react/features/chat/components/web/ChatMessage.js

ui: web chat facelift

---

conference.js
config.js
doc/api.md
modules/API/external/external_api.js
package-lock.json
package.json
react/features/base/conference/actions.js
react/features/base/config/configWhitelist.js
react/features/base/settings/middleware.js
react/features/base/util/uri.js

Need updating with lib-jitsi-meet from https://github.com/jitsi/lib-jitsi-meet/pull/1004

Adds an option to set email through iframe API init and to stats.

---

ios/Podfile.lock
package-lock.json
package.json

Fixes an Android crash on craptacular devices.

deps: react-native-webrtc@1.75.2

---

modules/transport/PostMessageTransportBackend.js
modules/transport/index.js

It has been around bor > 2.5 years already.

fix(transport): remove legacy code

---

lang/main.json
react/features/base/testing/components/TestConnectionInfo.js
react/features/chat/components/AbstractMessageContainer.js
react/features/chat/components/native/ChatInputBar.js
react/features/chat/components/native/MessageContainer.js
react/features/chat/components/native/styles.js
react/features/chat/components/web/MessageContainer.js

Contains 2 commits:
- The first one is an unrelated small fix, but it kept happening for me while working on the chat
- The second one is some general chat UX improvement.
Screenshot:

Chat fixes

---

react/features/conference/components/web/Subject.js

refs: https://github.com/jitsi/jitsi-meet/issues/4871

subject: hide participant count for 1-1 calls

---

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioDeviceHandlerConnectionService.java

It has been our default for a while.

android: fallbacck to speaker in ConnectionService handler

---

react/features/authentication/components/LoginDialog.native.js
react/features/authentication/components/styles.js
react/features/base/color-scheme/defaultScheme.js

Also removed some no longer used styles.

auth: fix rendering error and progress messages

---

css/_avatar.scss
css/_mixins.scss
css/_variables.scss
package-lock.json
package.json
react/features/base/avatar/components/Avatar.js
react/features/base/avatar/components/native/StatelessAvatar.js
react/features/base/avatar/components/native/styles.js
react/features/base/avatar/components/web/StatelessAvatar.js
react/features/base/react/components/native/AvatarListItem.js
react/features/invite/components/add-people-dialog/native/AddPeopleDialog.js
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.js

Add support for avatar status badge (presence)

---

lang/main.json

rn,welcome: update join button text

---

conference.js
package-lock.json
package.json

- Notify the external API when presenter is unmuted for the first time.
- Update lib-jitsi-meet

fix(presenter-mode): notify external API when presenter is unmuted for the first time

---

android/sdk/src/main/java/org/jitsi/meet/sdk/RNConnectionService.java

Pixel C devices have been seen crashing here, oh well.

android: handle exception when unregistering account

---

react/features/app/middleware.js
react/features/base/conference/middleware.js

Move call to reloadNow() on CONNECTION_FAILED to the ./features/app/middleware to avoid importing higher order feature from the lower level one.

ref: remove features/base/conference -> /app cycle

---

debian/jitsi-meet-prosody.postinst
debian/jitsi-meet-prosody.postrm
debian/jitsi-meet-tokens.postrm
debian/jitsi-meet-web-config.postrm
doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example

Not sure which one to merge first, I think tests that test the debian package deployment will fail till we have all 3 components jitsi-meet, jicofo and jvb changes merged.
https://github.com/jitsi/jitsi-videobridge/pull/1009
https://github.com/jitsi/jicofo/pull/413

Migrate to using mucs for jvb

---

ios/Podfile.lock
package-lock.json
package.json

Fixes datachannels not working.

deps: react-native-webrtc@1.75.3

---

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioDeviceHandlerConnectionService.java

This shouldn't be needed, as ConnectionService should take care of it, but we
suspect some devices don't do it since we got reports of people not hearing
users, and the problem went away when CS was disabled.

android: unmute microphone on the ConnectionService handler

---

conference.js

A few duct tape fixes for async issues around the presenter mode.

Fix async issues around presenter handling

---

resources/prosody-plugins/mod_muc_poltergeist.lua
resources/prosody-plugins/mod_muc_size.lua
resources/prosody-plugins/util.lib.lua

adds missing runner variable from async to async_handler_wrapper
removes redundant have_async definition in wrap_async_run, defined at top of module

fixes async_handler_wrapper

---

static/recommendedBrowsers.html

Remove Firefox until it is fully supported and the warning is the UI is removed.

Removes firefox from the list of recommended browsers.

---

react/features/base/tracks/loadEffects.native.js

The resolved promise is expected to return an array.

rn,tracks: fix loadEffects

---

react/features/stream-effects/blur/JitsiStreamBlurEffect.js

Increase the constant for background blur that is passed to the function which applies the blur effect.

fix(blur): Increase the background blur value

---

conference.js
interface_config.js
react/features/base/config/configWhitelist.js
react/features/stream-effects/screenshot-capture/ScreenshotCaptureEffect.js

This will let us enable/disable the feature based on environment/deployment.

fix(screenshot-capture): Move the flag for enabling/disabling the feature to config.js

---

react/features/chrome-extension-banner/components/ChromeExtensionBanner.web.js
react/features/chrome-extension-banner/logger.js

Prevent chrome extension banner from spanning the console when disabled

---

package-lock.json
package.json

Use RN 0.61.5 + a custom patch (submitted upstream) for fixing a crash in JSI.

deps: react-native@custom-patched

---

connection.js

We want to be able to do something similar: https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/Participant.java#L224
So we can disable muting of those participants: 
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java#L2299

Adds a disco feature to distinguish jibri participants.

---

react/features/chrome-extension-banner/components/ChromeExtensionBanner.web.js

Log success of retrieving chrome extension banner configs

---

conference.js
modules/UI/UI.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js
react/features/filmstrip/components/web/StatusBar.js
react/features/filmstrip/components/web/StatusIndicators.js
react/features/filmstrip/components/web/index.js
react/features/notifications/middleware.js
react/features/remote-video-menu/components/web/RemoteVideoMenuTriggerButton.js

Moved all moderator functionality to react to optimize the number of
status bar updates.

fix(thumbnail): Optimize status bar moderator icon

---

index.html

Pass room name to IE page

---

react/features/analytics/AnalyticsEvents.js
react/features/analytics/functions.js
react/features/base/environment/utils.js
react/features/chrome-extension-banner/components/ChromeExtensionBanner.web.js

@saghul @damencho @hristoterezov

Add analytics to chrome extension banner

---

android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java

android: disable HW accelerated decoding on Samsung

---

doc/manual-install.md

Added port 10000 to the network drawing.
Corrected provided nginx example and added IPv6 binding to it.
Removed renaming jitsi-meet, which was a confusing addition since most people won't run multiple jitsi-meet instances.
Added missing step to determine build number of the video bridge.
Reworked the `sip-communicator.properties` example into executable bash commands.
Removed information about architectures in jifoco as the example referred to jifoco 1.0, but current is 1.1 which does not use them. Updated information to match 1.1 format.
Instead of restarting nginx via invoke-rc.d, use nginx itself to verify and reload its config.
Added information why the Videobridge forwards are required, clarified that the webserver port does not need to be routed to the Videobridge.
Small typo/name …

Update and improve manual install doc

---

package-lock.json
package.json
resources/prosody-plugins/mod_auth_token.lua
resources/prosody-plugins/mod_smacks.lua
resources/prosody-plugins/mod_websocket_smacks.patch

Adds parts that have to be changed in Prosody 0.11 in order for the stream resume added in [this PR] to work correctly.
[this PR]:https://github.com/jitsi/lib-jitsi-meet/pull/1034

Pieces for the XMPP stream resume

---

interface_config.js
react/features/app/actions.js

feat(close) Add promotional close page

---

modules/UI/videolayout/VideoLayout.js
package-lock.json
package.json

Apart from the commit in this PR I will also want to add LJM update commit to include this one:
https://github.com/jitsi/lib-jitsi-meet/pull/1040

Disco info fixes

---

package-lock.json
package.json

Updates lib-jitsi-meet to e3533220023cb3f5c727ac5b27dc18552acef5c9

desp: update LJM to bring in fix for a crash on BOSH item-not-found

---

doc/faq.md

Broken link, I presume this one was meant.

Correct link regarding FAQ NAT install

---

interface_config.js
react/features/remote-video-menu/components/web/KickButton.js

Hide kick button for guests

---

lang/languages-it.json

I added Afrikaans missing string

ITALIAN translation - added last missing string

---

README.md

Fix oxymoron in README.md

---

conference.js
package-lock.json
package.json
react/features/stream-effects/audio-mixer/AudioMixerEffect.js

DEPENDS ON https://github.com/jitsi/lib-jitsi-meet/pull/1039.
The AudioMixerEffect uses the newly added AudioMixer from https://github.com/jitsi/lib-jitsi-meet/pull/1039 to mix together a system audio stream and a local audio stream if present.

Add AudioMixerEffect for system audio sharing

---

debian/jitsi-meet-turnserver.postinst
doc/debian/jitsi-meet/jitsi-meet.example

This PR fixes both https://github.com/jitsi/jitsi-meet/issues/5209 and https://github.com/jitsi/jitsi-meet/issues/5000

fix broken nginx ipv6 listeners

---

lang/main-sv.json

Fix "toggleCamera" description. switch instead of turn off/on

Update main-sv.json: toggleCamera description fix

---

lang/main-es.json
lang/main-esUS.json

I realized that the change for Mute Everyone Else doesn't have the spanish dialogues, I added it and also some another typos.
Signed-off-by: Esteban Badilla A <ebadilla10@gmail.com>

fix: Fixes and adding some translations to spanish

---

conference.js
react/features/base/config/configWhitelist.js
react/features/base/lib-jitsi-meet/functions.any.js
react/features/base/participants/middleware.js
react/features/base/participants/preloadImage.web.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/5446

Fix disable third party requests

---

doc/quick-install.md

Update commands provided to reload and check the status of videobridge

jitsi-videobridge -> jitsi-videobridge2

---

react/features/welcome/components/AbstractWelcomePage.js
react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/styles.js

rn,welcome-page: use random room name generator

---

debian/jitsi-meet-prosody.postinst

Fixes: https://github.com/jitsi/jitsi-meet/issues/5473

debian: fix creating internal MUC

---

.github/workflows/ci.yml

It should help catch bugs such as bundle bloat easier.

ci: build the frontend in GH actions

---

react/features/conference/components/web/Conference.js

Fixes #5480
Signed-off-by: Ruben Kerkhof <ruben@rubenkerkhof.com>

Add room name to browser tab title

---

config.js
react/features/base/config/configWhitelist.js
react/features/base/config/extraConfigWhitelist.js
react/features/recording/middleware.js

- manage recording audio notifications through config
@saghul @damencho

feat(notifications): Manage audio notifications

---

react/features/invite/components/add-people-dialog/native/AddPeopleDialog.js
react/features/invite/components/add-people-dialog/native/styles.js

rn,invite: fix bottom padding on Anddroid

---

lang/main.json
react/features/app/components/AbstractApp.js
react/features/app/components/App.native.js
react/features/base/color-scheme/defaultScheme.js
react/features/base/modal/actionTypes.js
react/features/base/modal/actions.js
react/features/base/modal/components/JitsiModal.js
react/features/base/modal/components/index.native.js
react/features/base/modal/components/index.web.js
react/features/base/modal/components/styles.js
react/features/base/modal/index.js
react/features/base/modal/reducer.js
react/features/chat/components/native/Chat.js
react/features/chat/components/native/ChatButton.js
react/features/chat/components/native/ChatInputBar.js
react/features/chat/constants.js
react/features/chat/reducer.js
react/features/help/components/HelpView.js
react/features/help/components/index.js
react/features/help/constants.js
react/features/help/index.js
react/features/welcome/components/WelcomePageSideBar.native.js

feat: help centre

---

lang/main.json
package-lock.json
package.json
react/features/desktop-picker/components/DesktopPicker.js
react/features/desktop-picker/components/DesktopPickerPane.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/1061

Add support for audio screen sharing on electron

---

react/features/conference/components/web/Conference.js

Re-do of
https://github.com/jitsi/jitsi-meet/commit/86ebfe8dad5ea198dca8c5eaddda1ce30ac3fba3

conference: add room name to browser title

---

lang/main-de.json
lang/main-es.json
lang/main-fr.json
lang/main-it.json

Hello,
We added some translations for the mobile apps :)

Add translation fr, de, es, it for mobile app

---

lang/main-de.json

This commit fixes a few translation errors, especially in the `kickParticipantTitle`.

Fix German translation

---

modules/UI/videolayout/LargeVideoManager.js

So turn 'hover in %s 1a5cd940' into 'hover in 1a5cd940'

console.log shows verbatim %s

---

lang/main.json
react/features/recording/components/LiveStream/constants.js
react/features/recording/components/LiveStream/native/StreamKeyForm.js
react/features/recording/components/LiveStream/native/styles.js
react/features/recording/components/LiveStream/web/StreamKeyForm.js

feat(live-streaming): Add T&C.

---

conference.js
package-lock.json
package.json

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/1080

Project HPS, first pass

---

lang/main-fr.json

Hello,
"Activer/désactiver la caméra" = "Activating/deactivating the camera"
It's fix :)

Fix french

---

lang/main-ja.json

fix issue #5741
"秒" means second.

Fix japanese mistranslation

---

lang/main.json
react/features/app/components/App.web.js
react/features/old-client-notification/components/OldElectronAPPNotificationDescription.js
react/features/old-client-notification/components/index.js
react/features/old-client-notification/functions.js
react/features/old-client-notification/index.js
react/features/old-client-notification/middleware.js

Detects if Jitsi Meet is running in old jitsi-meet-electron app and
warns the user for scurity issues.

feat(old-electron-app-notification): Implement

---

react/features/mobile/picture-in-picture/components/PictureInPictureButton.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/6008

pip: disable PiP on Android < 26

---

interface_config.js
react/features/base/environment/environment.js

This reverts commit 4824c8714aeb35bfa4bd373dbbada018e49dc0e2.

Revert "feat(browser-support): Add safari to list of optimal browsers"

---

conference.js

Fixes https://github.com/jitsi/jitsi-meet-electron/issues/248

bugfix(remote-control): Remote control not working on linux

---

lang/main.json
react/features/base/participants/middleware.js
react/features/e2ee/components/E2EEDialog.js

Refs: https://github.com/jitsi/lib-jitsi-meet/pull/1108

e2ee: show warning if not all participants support E2EE

---

react/features/base/dialog/components/native/BaseDialog.js

fix(dialog): fix on-screen keyboard overlapping dialog boxes

---

react/features/local-recording/recording/flac/FlacAdapter.js
react/features/stream-effects/blur/JitsiStreamBlurEffect.js
react/features/stream-effects/presenter/JitsiStreamPresenterEffect.js
react/features/stream-effects/screenshot-capture/ScreenshotCaptureEffect.js

misc: set worker names

---

package-lock.json
package.json

GH Actions now runs the linter.

misc: drop the pre-commit hook

---

lang/main-es.json

Some of the wording that smelled to Google translate 👃 😃

Small fixes in the Spanish translation

---

react/features/base/flags/constants.js
react/features/chat/components/native/ChatButton.js
react/features/conference/components/native/LonelyMeetingExperience.js
react/features/conference/components/native/NavigationBar.js
react/features/invite/actions.native.js
react/features/invite/components/add-people-dialog/native/InviteButton.js
react/features/recording/components/LiveStream/native/LiveStreamButton.js
react/features/recording/components/Recording/native/RecordButton.js
react/features/room-lock/components/RoomLockButton.js
react/features/toolbox/components/native/OverflowMenu.js
react/features/toolbox/components/native/Toolbox.js

- Invite funcionality (altogether)
- Recording
- Live streaming
- Meeting name
- Meeting password

rn,flags: add more feature flags to toggle specific behavior

---

lang/languages.json

Add Thailand (th) translation

---

lang/main-nl.json

As it says in the title: Adds the missing Dutch translation for "toolbar.muteEveryone".

Adds Dutch translation for "toolbar.muteEveryone"

---

react/features/base/i18n/BuiltinLanguages.native.js

Add Slovak translation to BuiltinLanguages
Follow up to #5523

Enable Slovak translation.

---

lang/main-de.json

There are two missing translations for german.

added missing translations

---

react/features/base/i18n/languageDetector.native.js

If we have a regional variant, prefer that.

rn,lang: fix language detection to take region into account

---

react/features/base/flags/constants.js
react/features/toolbox/components/native/RaiseHandButton.js

- Added feature flag 'raise-hand.enabled' to enable/disable 'Raise Hand' feature for Android/iOS.

feature flag to show/hide 'Raise Hand' button

---

react/features/prejoin/functions.js
react/features/toolbox/components/AudioMuteButton.js
react/features/toolbox/components/VideoMuteButton.js

Avoid importing components, which are not yet implemented on mobile.

prejoin: fixup mobile

---

ios/app/src/AppDelegate.m
ios/app/src/ViewController.h
ios/app/src/ViewController.m

Fixes: https://github.com/jitsi/jitsi-meet/issues/6665

ios: try to leave the meeting when the app is terminating

---

package-lock.json
package.json

update react-emoji-render to v1.2.4

---

.npmrc

adds a .npmrc file to create/update the package-lock.json file regardless
of a developers local settings.

dev: add npmrc with package-lock set to true

---

package-lock.json

Fixes up this PR: https://github.com/jitsi/jitsi-meet/pull/6674/files

fix: package.lock version mismatch

---

lang/main-de.json
lang/main-enGB.json
lang/main-ja.json
lang/main-nl.json
lang/main.json
react/features/deep-linking/components/DeepLinkingMobilePage.web.js

improve "open in app" page

---

react/features/base/environment/environment.js
react/features/deep-linking/components/DeepLinkingMobilePage.web.js
react/features/deep-linking/functions.js

Currently Chrome, Edgium and Firefox are supported on Android
Only Safari is supported on iOS

feat(browser-support): show option to join via browser on supported mobile browsers

---

react/features/base/i18n/BuiltinLanguages.native.js

Turkish language added for native react

Turkish Language support added

---

lang/main-es.json
lang/main-esUS.json

 Update spanish translation

---

css/modals/invite/_info.scss
css/modals/invite/_invite_more.scss
css/modals/security/_security.scss
react/features/conference/components/web/InviteMore.js

Takes care of https://github.com/jitsi/jitsi-meet/issues/6804 and also fixes a possible overflow in the `InviteMore` button from the header

fix(SecurityDialog): fix button overflow

---

package-lock.json
package.json

https://github.com/jitsi/lib-jitsi-meet/commit/c94f6a570f69ebfe18de6c1549cc76370c791468

chore(deps): update lib-jitsi-meet

---

lang/main-de.json

Added some missing translation to the german translation in the json fields:
* addPeople
* security
* toolbar

Update main-de.json to add some missing fields

---

react/features/conference/components/web/Conference.js
react/features/conference/components/web/Labels.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/6880

labels: dont disable all labels when VIDEO_QUALITY_LABEL_DISABLED is set

---

react/features/subtitles/components/AbstractClosedCaptionButton.js
react/features/subtitles/components/ClosedCaptionButton.native.js

feat(subtitles): Disable for guests.

---

modules/API/API.js
modules/API/external/external_api.js

external_api: add start/stop recording commands

---

package-lock.json
package.json
react/features/stream-effects/rnnoise/index.js
webpack.config.js

Depends on https://github.com/jitsi/rnnoise-wasm/pull/2

rnnoise: simplify initialization

---

lang/main-tr.json

Missing translations added ( security ,lobby,lonelymeetingexperience etc.)
Some wrong translations fixed.

update: fixed missing and wrong translated words

---

config.js
react/features/base/config/configWhitelist.js

Remove obsolete options.

---

react/features/authentication/components/LoginDialog.native.js

rn: fixup LoginDialog

---

lang/main-ptBR.json

I created the "lobby" section in json (ptBR) file and translated all sentences.
One minor word correction at installExtensionText  label previous translation.

lobby section translated to portuguese (BR)

---

react/features/base/premeeting/components/web/InputField.js
react/features/lobby/components/AbstractLobbyScreen.js
react/features/lobby/components/web/LobbyScreen.js

This PR fixes the missing function error when lobby is enabled but prejoin is not

fix: lobby screen broken with prejoin disabled

---

react/features/security/components/security-dialog/SecurityDialog.js

fix(e2ee): hide if not supported.

---

react/features/base/devices/functions.js
react/features/device-selection/middleware.js

(prejoin): fix mobile

---

interface_config.js

fix(jitsi-logo): URL

---

interface_config.js

ref(interfaceConfig): Order alphabetically.

---

doc/README.md

Point to the Handbook repo, so users can figure out where to submit PRs now.

Point to the Handbook repo

---

react/features/base/react/components/web/Watermarks.js

fix: welcome page logo not being displayed

---

react/features/subtitles/components/AbstractClosedCaptionButton.js

fix: Fixes showing cc button when jwt is not used.

---

debian/jitsi-meet-web-config.postinst

debian: fix postinst command

---

interface_config.js

interface_config: bring back config trailer

---

interface_config.js
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.js

feat(AddPeopleDialog): Enable contact invitation based on config

---

react/features/youtube-player/components/native/YoutubeLargeVideo.js
react/features/youtube-player/middleware.js

rn: refactors the YoutubeLargeVideo to be class component

---

interface_config.js

docs: fix typo in interface_config.js

---

modules/API/API.js
modules/API/external/external_api.js

Adding isSharingScreen() to external API

Adding isSharingScreen() to external API

---

config.js

Just some typo fixes in config.js.

docs: improve English in config.js

---

SECURITY.md

doc: add H1 to SECURITY.md

---

package-lock.json
package.json

deps: update css-loader and clean-css (npm audit)

---

package-lock.json
package.json

Revert: clean-css update due to broken paths.

---

react/features/toolbox/components/web/Toolbox.js

toolbox: fix missing key prop

---

css/_prejoin-dialog.scss
css/_premeeting-screens.scss

Just moved some CSS around so the selectors are not as specific & fixed the width of the buttons.

fix(prejoin): dialout popup buttons

---

doc/debian/jitsi-meet-turn/turnserver.conf

turn: update default coturn configuration

---

Makefile
package-lock.json
package.json

Fix the incorrect paths (was a breaking change in version 4) by using the
`--skip-rebase` cli option.

deps: update clean-css (reland)

---

ios/Podfile.lock
package-lock.json
package.json

deps: react-native-webrtc@1.84.0

---

android/app/src/main/res/xml/network_security_config.xml

Adds ability for Android app to accept user CA root trusts

added configuration for user CA root trust (closes #7220)

---

config.js
package-lock.json
package.json

This is useful for testing insertable streams related issues.
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/1238

config: add flag to disable the E2EE support

---

package-lock.json
package.json

chore(deps): update lib-jitsi-meet to latest

---

resources/update-ljm.sh

misc: add script to update LJM to the latest commit

---

css/modals/security/_security.scss

Addresses https://github.com/jitsi/jitsi-meet/issues/7283

fix(SecurityDialog): Fix password action spacing

---

react/features/analytics/functions.js

analytics: avoid error log when there are no handlers

---

resources/prosody-plugins/mod_muc_lobby_rooms.lua

Add hook for creating lobby before participants join

---

package-lock.json
package.json

Updates LJM to ff1813cbb2e7d36f1cc0bbc2b8baa0a16c6346a4

deps: update LJM to bring in new audio levels and e2ee tweaks

---

css/_premeeting-screens.scss
react/features/base/premeeting/components/web/Preview.js

This was reported here: https://github.com/jitsi/jitsi-meet/issues/7296

fix(prejoin): Align avatar image on small screens

---

react/features/base/flags/constants.js
react/features/youtube-player/components/VideoShareButton.js

Adds options to enable/disable video share button(share a youtube video button) inside overflow menu

Adds option to show/hide video share button

---

conference.js

fix(disconnect) Fix quick disconnect errors

---

react/features/base/testing/components/TestConnectionInfo.js

feat: add test hint for grant moderator availability

---

css/_chat.scss
css/_toolbars.scss
css/_videolayout_default.scss
modules/UI/videolayout/LargeVideoManager.js
react/features/chat/actions.js
react/features/chat/components/web/Chat.js
react/features/chat/constants.js
react/features/conference/components/web/Conference.js
react/features/conference/components/web/index.js
react/features/large-video/components/LargeVideo.web.js
react/features/toolbox/components/web/Toolbox.js
react/features/toolbox/functions.web.js

Relates to https://github.com/jitsi/jitsi-meet/pull/5124

feat(chat): Make chat push content to the side in large view

---

css/modals/settings/_settings.scss
lang/main.json
react/features/settings/actions.js
react/features/settings/components/web/MoreTab.js
react/features/settings/components/web/SettingsDialog.js
react/features/settings/functions.js

feat(prejoin): Add settings options for prejoin page

---

react/features/conference/components/native/Conference.js
react/features/conference/components/native/styles.js
react/features/display-name/components/native/DisplayNameLabel.js
react/features/display-name/components/native/styles.js
react/features/filmstrip/components/native/Thumbnail.js
react/features/filmstrip/components/native/styles.js

Mobile tile view improvements

---

ios/app/app.xcodeproj/project.pbxproj
ios/fastlane/Fastfile

-Use Fastlane to get them from Apple after processing, them upload them.
Also make sure WebRTC dSYMs are included when uploading.

ios: fix uploading dSYMs to Crashlytics

---

react/features/analytics/functions.js
react/features/chat/actions.any.js
react/features/chat/actions.native.js
react/features/chat/actions.web.js
react/features/settings/actions.js

Fix modile

---

android/gradle.properties
ios/app/src/Info.plist
ios/app/watchos/app/Info.plist
ios/app/watchos/extension/Info.plist
ios/sdk/src/Info.plist

rn: update versions

---

react/features/security/components/security-dialog/SecurityDialog.js

security-dialog: restore digit-only password functionality

---

react/features/app/components/App.native.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/7373

rn: fix overriding user-selected server URL

---

react/features/base/config/configWhitelist.js

config: add roomPasswordNumberOfDigits to whitelist

---

css/buttons/copy.scss
css/main.scss
css/modals/invite/_invite_more.scss
react/features/base/buttons/CopyButton.js
react/features/invite/components/add-people-dialog/web/CopyMeetingLinkSection.js

ui: create reusable copy button

---

react/features/stream-effects/blur/JitsiStreamBlurEffect.js

Resolve a potential leak. Terminate the blur web worker when the effect is disabled.

feat(blur): terminate blur web worker when disabled

---

config.js

https://github.com/jitsi/jitsi-meet/issues/7376

Add remark about focus username

---

react/features/prejoin/components/Prejoin.js
react/features/prejoin/components/PrejoinApp.js
static/prejoin.html

fix(prejoin) fix libs path

---

react/features/analytics/functions.js

analytics: add app name to permanent properties

---

modules/API/external/external_api.js
package-lock.json
package.json

Depends on https://github.com/jitsi/js-utils/pull/39

external_api: filter postis events origin

---

lang/languages.json

Fixing missing kabyle language in the main file.

Fix - adding missing kabyle language.

---

babel.config.js
config.js
jest.config.js
package-lock.json
package.json
react/features/app/reducers.any.js
react/features/base/lastn/functions.js
react/features/base/lastn/functions.test.js
react/features/base/lastn/middleware.js
react/features/base/lastn/reducer.js

Adds 'lastNLimits' config value which allows to define last N value per number of participants.
See config.js for more details.

feat(config): add last N limit mapping

---

lang/main-es.json
lang/main-esUS.json

Fix typo in Spanish languages.

misc: fix typo

---

react/features/toolbox/components/web/Toolbox.js

The dots menu was removed in small resolutions (including web mobile) this PR
makes the exception for mobile.

Restore dots menu on mobile

---

config.js
package-lock.json
package.json

feat(video-quality): Impose max-bitrates on video sender based on videoQuality settings

---

react/features/prejoin/components/Prejoin.js
react/features/toolbox/functions.web.js

feat(prejoin): Hide invite link

---

resources/prosody-plugins/token/util.lib.lua

FEAT: jwt pubkey cache inside object

---

lang/main-cs.json

Fixing just a few typos in the Czech translation.

Fixing some typos in Czech translation

---

android/scripts/run-packager-helper.command
android/scripts/run-packager.sh
ios/scripts/run-packager-helper.command
ios/scripts/run-packager.sh

rn: always reset the transform cache when starting the packager

---

css/_variables.scss
css/_welcome_page.scss
interface_config.js
react/features/base/react/components/web/Watermarks.js
react/features/welcome/components/WelcomePage.web.js

feat(Watermarks): Add deafault logo prop.

---

static/prejoin.html

fix(prejoin) fix css loading path

---

doc/debian/jitsi-meet/jitsi-meet.example
doc/example-config-files/jitsi.example.com.example
doc/example-config-files/multidomain/jitsi.example.com.multidomain.example

This boosts the Pagespeed ranking from low 30s to high 70s and shaves (in my tests) around 2s from the loading time.

Improve compressions + add expire headers

---

static/prejoin.html

fix(prejoin) remove version parameter

---

.gitignore
css/_prejoin.scss
lang/main.json
react/features/prejoin/components/Prejoin.js

feat(prejoin) show error when trying to join and name is required

---

react/features/base/conference/middleware.js

fix(subject): set to ' ' after settings change.

---

react/features/base/premeeting/components/web/ActionButton.js
react/features/prejoin/components/Prejoin.js

misc: Add test ids for prejoin buttons

---

config.js
package-lock.json
package.json
react/features/rtcstats/middleware.js

Use rtcstats with keep-alive / rtcstats enabled config

---

Makefile

fix(close3): Add close3.js

---

config.js
react/features/base/config/configWhitelist.js
react/features/base/premeeting/components/web/CopyMeetingUrl.js

Resolves #7501
Automatically copy invite URL after creating a room

FEAT: Automatically copy invite URL after creating a room

---

debian/jitsi-meet-tokens.postinst

jitsi-meet-tokens.postinst: fix tests

---

config.js
package-lock.json
package.json
react/features/base/config/configWhitelist.js

Update lib-jitsi-meet and add the RED option to config.js.

---

react/features/base/config/configWhitelist.js

feat: Whitelist option to hide lobby button.

---

react/features/deep-linking/functions.js

feat(vpaas) disable deeplinking page

---

config.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/7665

config: fix missing comma

---

modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js
react/features/base/avatar/components/Avatar.js
react/features/filmstrip/components/native/ScreenShareIndicator.js
react/features/filmstrip/components/native/Thumbnail.js
react/features/filmstrip/components/web/ScreenShareIndicator.js
react/features/filmstrip/components/web/StatusIndicators.js

Introduce screen-sharing indicator

---

package-lock.json
package.json

The amplitude-js dependency required a major bump.

deps: run npm audit fix

---

modules/API/API.js
modules/API/external/external_api.js
react/features/base/conference/actionTypes.js
react/features/base/conference/actions.js
react/features/base/conference/constants.js
react/features/base/conference/middleware.js
react/features/base/conference/reducer.js
react/features/base/config/configWhitelist.js
react/features/video-quality/actionTypes.js
react/features/video-quality/actions.js
react/features/video-quality/components/OverflowMenuVideoQualityItem.web.js
react/features/video-quality/components/VideoQualitySlider.web.js
react/features/video-quality/constants.js
react/features/video-quality/functions.js
react/features/video-quality/index.js
react/features/video-quality/middleware.js
react/features/video-quality/reducer.js
react/features/video-quality/selector.js

feat(video-quality): add iframe event and getter.

---

resources/prosody-plugins/mod_token_verification.lua

When returning the error and showing to user not allowed screen we were not completely halting the prejoin operation when token verification fails on room join and the token is valid in general.

fix: Updates docs and verification to halt joining process.

---

modules/API/API.js
modules/API/external/external_api.js
react/features/large-video/actions.js

feat(external_api): Add cmd for selecting a user to be displayed in large video

---

.gitignore
config.js
modules/API/API.js
modules/API/external/external_api.js
react/features/base/config/configWhitelist.js
react/features/base/logging/ExternalApiLogTransport.js
react/features/base/logging/middleware.js

feat(logging) expose event for intercepting logs

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivityDelegate.java

The RN Permissions module calls this in a non-UI thread. What we observe is a
crash in ViewGroup.dispatchCancelPendingInputEvents, which is called on the
calling (ie, non-UI) thread. This doesn't look very safe, so try to avoid a
crash by pretending the permission was denied.

android: fix crash when requesting permissions

---

react/features/embed-meeting/components/EmbedMeetingDialog.js

fix(embed) fix embed meeting code

---

modules/API/external/external_api.js

feat(iFrame): add a method for getting the participants info

---

react/features/embed-meeting/components/EmbedMeetingDialog.js

Remove [legacy attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Attributes)

Remove legacy attribute

---

lang/main-nl.json

I noticed a small error in my merged pull request, and provide a fix.

lang: fix Dutch dialog.kickTitle

---

package-lock.json
package.json

fix(android,calendar) avoid crash

---

modules/API/API.js
modules/API/external/external_api.js
modules/UI/util/UIUtil.js
modules/UI/videolayout/LargeVideoManager.js
react/features/large-video/actions.js

feat(iFrame): Add a method for resizing large video container from iFrame

---

config.js

fix(config) remove no longer valid option

---

ios/app/src/Info.plist

fix(ios) add local network usage description for iOS 14

---

react/features/base/react/components/web/Watermarks.js
react/features/dynamic-branding/actionTypes.js
react/features/dynamic-branding/actions.js
react/features/dynamic-branding/reducer.js

* Display of the logo has been reworked (simplified).
* The logo will not be displayed if the call to `branding` endpoint fails (for vpaas meetings).
* Add more docs.

fix(branding): Fix dynamic logo display

---

ios/app/src/Info.plist

fix(ios,version) versions must match

---

config.js
package-lock.json
package.json

feat(stats): Add the ability to enable callStats for certain % of confs

---

resources/prosody-plugins/mod_filter_iq_rayo.lua

feat: Throttle out call attempts to the max number per minute

---

modules/UI/videolayout/LargeVideoManager.js

Distinguish between preferred and calculated width/height value.

fix(LargeVideoManager): large video resizing

---

modules/devices/mediaDeviceHelper.js

fix(mediaDeviceHelper): fix typo in dispatch

---

react/features/app/actions.js

fix(vpaas) fix vpaas redirect

---

react/features/invite/components/add-people-dialog/web/AddPeopleDialog.js
react/features/toolbox/components/web/Toolbox.js

fix(vpaas) hide embed meeting for vpaas users

---

react/features/analytics/functions.js
react/features/analytics/handlers/AmplitudeHandler.js
react/features/rtcstats/functions.js
react/features/rtcstats/middleware.js

Check every commit message for a description.

Miscellaneous analytics fixes

---

modules/API/API.js
modules/API/external/external_api.js

feat(iFrame): Add method for pinning a participant on stage view

---

lang/main-de.json

Fixed a small typo in German translation.

Fixed typo in German translation

---

package-lock.json

chore(deps) run npm audit fix
