conference.js
package-lock.json
package.json
react/features/base/conference/actions.js

The confID is domain.com/RoomName or domain.com/tenant/RoomName, adds the tenant if any and also keeps the room name case.
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/934

Passes confID when initializing JitsiConference.

---

react/features/base/tracks/actions.js

This only shows up if we cannot prompt again, like when turning permissions off
in the Settings app in iOS.

rn: fix not showing a prompt when permissions have been denied

---

react/features/toolbox/components/native/Toolbox.js
react/features/toolbox/components/native/styles.js

The rendering of these buttons were refactored previously, we just didn't have time to test it properly on smaller devices. Now that it's tested, we can remove the size calculation code

feat: use css to place the toolbox buttons

---

react/features/conference/components/native/Labels.js

Navbar off:
Navbar on:
Note 1: It felt more natural for me to place the labels under the gradient, because then they won't collide with a longer room name
Note 2: There is an unrelated landscape mode bug that I'll address in another PR

feat: always show labels

---

react/features/chat/components/web/MessageContainer.js
react/features/chat/middleware.js

Steps to reproduce:
1. Proceed into a conference.
2. Wait for the toolbar to disappear.
3. Press "c" to open chat.
Result: The layout is moved up.
I don't know the exact cause, admittedly. It has something to do with autoscrolling to the bottom of the chat so I made it scroll a little less. Another workaround would be use position:fixed on the toolbar and chat panel.
Bugged state:

fix(chat): workaround for chat scroll causing layout misalignment

---

debian/rules

This maps the tow letter languages as enGB to the country file for en.
Copies countries-en.json as countries-enGB.json.

Maps available locales for countries to the doubled languages.

---

react/features/base/config/reducer.js

It was added for
https://github.com/jitsi/jitsi-meet/commit/3ea2f005787c9f49c48febaeed9dc0340fe0a01b
over 2 years ago. That's long enough!

config: remove old backwards compatibility shim

---

lang/main.json
react/features/toolbox/components/web/Toolbox.js

@saghul, does this give you the change you want?
I think keyboard shortcuts could also be moved out. There might end up being some duplication of function calls between toolbox and keyboard shortcuts but a greater separation of concerns achieved. Let me know if you want that for a follow up commit which would happen within the next year, I promise.

feat(shortcuts): add shortcut for opening video quality modal

---

react/features/base/conference/middleware.js

When a participant is pinned in the UI we then proceed to mark it as selected on
the JVB. This will make the participant part of the last N set and will receive
the highest (or configured highest) video quality.
Pinning a participant at the JVB level just makes sure it will be part of the
last N set.
Since only one participant can be pinned in the UI, there is no point in pinning
it at the JVB level, since selecting it already achieved the same result.

conference: don't pin participants on the JVB 

---

react/features/filmstrip/middleware.js

The filmstrip is currently only hidden when PiP mode is entered. There is no
real reason not to leave the large view as it was.

rn,filmstrip: don't unpin participant when hiding filmstrip

---

doc/api.md
modules/API/API.js
package-lock.json
package.json
react/features/external-api/middleware.js
react/features/feedback/actionTypes.js
react/features/feedback/actions.js
react/features/feedback/reducer.js

Compared to firing the event on submission because
the submission ajax will not be completed at that
time..
Relies on https://github.com/jitsi/lib-jitsi-meet/pull/952 being merged first.

ref(feedback): emit api feedback submitted on completion

---

lang/main.json
react/features/base/i18n/i18next.js
react/features/overlay/components/web/UserMediaPermissionsFilmstripOnlyOverlay.js
react/features/overlay/components/web/UserMediaPermissionsOverlay.js

i18next.options are initialized before interfaceConfig overwrites are processed which leads to wrong translations.

Removes resolveAppName postprocess we do not need.

---

react/features/deep-linking/components/DeepLinkingMobilePage.web.js

There is no need to display the native app name as
raw html.

fix(deep-linking): do not accept native app name as raw html

---

lang/main.json
react/features/conference/functions.js

This prevents inserting any user overridden APP_NAME
values into html. A new translation key is being used
to immediately stop non-english languages from using the
problematic string.
Also tweaked the copy to remove the "eer" and fix
some grammar.

fix(suboptimal-browser): remove inserting of app name in notification

---

react/features/video-layout/subscriber.js

The store's remote tracks get cleared
and re-added when switching in and out
of p2p, which can cause pinning thrashing.
Avoid that with a debounce.

fix(pinning): debounce autopin subscriber

---

conference.js

In case of hitting errors like max participant limit reached and when clicking hangup, the attempt to leave room second time results error and reload screen.

Leaves room only when it is already joined.

---

package-lock.json
package.json
react/features/base/avatar/components/Avatar.js
webpack.config.js

They are in Stage 3 and are already dependencies or the React Native preset.
References:
https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining
https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator

deps: add babel plugins for optional chaining and nullish coalescing 

---

android/sdk/src/main/java/org/jitsi/meet/sdk/BaseReactView.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivityDelegate.java
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java

This is the main one:
https://github.com/facebook/react-native/blob/df4e67fe75d781d1eb264128cadf079989542755/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L512
Why this happens is a mystery wrapped in an enigma.

android: attempt to fix assertion errors in ReactInstanceManager

---

.travis.yml

Adds wait time suggested by Travis support in order to see the last error logged.

travis: wait 10 seconds after script to catch the error logged

---

lang/main.json
react/features/connection-stats/components/ConnectionStatsTable.js

There is no point in translating this.
https://community.jitsi.org/t/translation-mistake-for-the-turn-server-label/19483

Removes i18n strings for p2p and turn.

---

react/features/welcome/components/WelcomePageSideBar.native.js

It need not always exist, since it's created asynchronousluy on app
initiualization. Make sure we are ready for it.
I've seen backtraces because of this.

rn,welcome: fix accessing local participant

---

modules/API/external/external_api.js

We now have the ability to select the video element for specific participants. I'm tweaking the jitsi-meet-electron app for my use case. I need to open Always On Top windows for specific participants, so the current _getLargeVideo() wont suffice.
I made a post about this in the Developers section on the Jitsi Community Forum, but it got blocked by Akismet.

Get participant specific video element

---

conference.js
modules/UI/UI.js
react/features/base/conference/middleware.js

This change lets the display name prompt open on mobile too for the predefined circumstances

feat: make display name prompt platform independent

---

android/scripts/release-sdk.sh

In
https://github.com/jitsi/jitsi-meet/commit/b53a034aafe3ae2b82de038442657fd63018ae95#diff-0339cf92cc68bc5981fe6df601316c1c
I removed this, because RN has updated the builtin JSC version. On the next
release, however, RN introduced a new JS interpreter (Hermes) so JSC is now a RN
dependency. Thus, add the magic spells to publish the AARs to Maven.

android: update SDK release script to publish JSC artifacts

---

webpack.config.js

With the new bundle size checking, the webpack config consists of many configs exported, so the proxy logic needs to go through all of them in order to work fine

fix: webpack proxy fix

---

lang/main.json
react/features/welcome/components/WelcomePage.web.js

As described in #312 adding umlauts into a meeting name results in being redirected to a 404 page. The easiest way to fix this is to prevent people to submit the form while having invalid characters in the meeting name.

Fix #312 by adding HTML5 validation pattern

---

react/features/base/dialog/components/web/AbstractDialogTab.js
react/features/base/dialog/components/web/DialogWithTabs.js
react/features/base/dialog/components/web/StatelessDialog.js
react/features/base/logging/functions.js
react/features/base/media/components/AbstractAudio.js
react/features/base/media/components/Audio.native.js
react/features/base/media/components/Audio.web.js
react/features/base/media/components/Video.native.js
react/features/base/media/components/Video.web.js
react/features/base/media/components/web/Video.js
react/features/device-selection/components/AudioInputPreview.js
react/features/device-selection/components/AudioOutputPreview.js
react/features/device-selection/components/DeviceSelection.js
react/features/device-selection/components/DeviceSelector.web.js
react/features/device-selection/components/VideoInputPreview.js
react/features/settings/components/web/DeviceSelectionPopup.js
webpack.config.js

Due to some broad imports the ```device_selection_popup_bundle.min.js``` bundle basically contained the entire application (2.4Mb). With this change it goes down to ~650k.
**Before:**
336K - alwaysontop.min.js
5.8K - analytics-ga.js
3.1K - analytics-ga.min.js
2.7M - app.bundle.min.js
**2.4M - device_selection_popup_bundle.min.js**
464K - dial_in_info_bundle.min.js
2.3K - do_external_connect.min.js
26K - external_api.min.js
2.7K - external_connect.js
3.9K - flacEncodeWorker.min.js
661K - lib-jitsi-meet.min.js
356K - libflac4-1.3.2.min.js
883K - video-blur-effect.min.js
**After:**
336K - alwaysontop.min.js
5.8K - analytics-ga.js
3.1K - analytics-ga.min.js
2.6M - app.bundle.min.js
**647K - device_selection_popup_bundle.min.js**
464K - dial_in_info_bundle.min.js
2.3K - …

ref: reduce device popup bundle size

---

modules/UI/videolayout/SmallVideo.js

This PR slightly refactors the display mode logging logic. While debugging a broken call I've noticed this state being printed in the JS console logs:
```json
{
"isAudioOnly": false,
"tileViewEnabled": true,
"isVideoPlayable": false,
"hasVideo": true,
"connectionStatus": "active",
"mutedWhileDisconnected": false,
"wasVideoPlayed": false,
"videoStream": true,
"isVideoMuted": false,
"videoStreamMuted": false
}
```
Looking at how the `isVideoPlayable` flag is computed in SmallVideo.js the above state is impossible: `isVideoPlayable` is computed as `videoStream && !isVideoMuted && !videoStreamMuted`, so, in this particular case, it owed to be `true`; yet, it is computed as `false`.
In this PR I'm not attempting to fix the issue because I don't know how it's possible to end-up in this …

ref: Tweak logging logic for thumbnail display mode and tile view.

---

react/features/large-video/middleware.js

Bring back the workaround introduced in afd2aea7
but removed in 21dcc41d. On conference join,
several other actions have already been fired
that try to set the large video participant
and select the participant on the bridge.
The problem is there is no conference during
these actions so the select participant
never fires. Then subsequent actions do not
fire select participant because the large
video participant has not changed.

fix(large-video): bring back workaround for selecting on conference join

---

css/_base.scss
react/features/base/icons/components/Icon.js

Attempts to fix the issue where third party svgs might not expect css setting color. For example, and the only case I know about, atlaskit checkbox hides its checkmark svg using color.

fix(icons): scope white svgs to Icon components

---

ios/sdk/src/JitsiMeetLogger.m

The subsystem is set to the bundle ID and the category to "JitsiMeetSDK".

ios: set logger subsystem and category

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivityDelegate.java

If the Activity is put into the background before the ReactContext is created we
get an NPE here. While the window might be short, it's thechnically possible to
hit this, as our Crashlytics reports show.

android: fix NPE when handling onHostPause

---

android/sdk/src/main/java/org/jitsi/meet/sdk/net/NAT64AddrInfoModule.java

Use 'ipv4only.arpa' well known host defined in RFC7050 instead of 'nat64.jitsi.net' as suggested by Jonathan Lennox.

ref(NAT64AddrInfoModule): use 'ipv4only.arpa' well known host

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java

If action is null (observed on some old devices) we'll get an exception.
Reversing the check fixes it since Actions.XXX is statically defined.

android: make check more resilient

---

react/features/follow-me/middleware.js

In https://github.com/jitsi/jitsi-meet/pull/4715/commits/c10657771136d03a47100883f6d8fd9552a94df1 initialized was removed from the etherpad feature state, and if it is not initialized it will be just undefined which is handled in the check for toggling on follow me.
@saghul ;)

Fixes showing etherpad in follow-me mode.

---

android/scripts/release-sdk.sh

Skip the first character, since it's now like ^123456.0.0

android: fix SDK release script for new dependency syntax

---

doc/manual-install.md

Just a small change to the manual installation to make it a little more clear. Adds a cd command to go to jitsi.example.meet before running npm install and make

doc(install): adds cd command to jitsi-meet installation

---

package-lock.json
package.json
react/features/base/util/strings.native.js
react/features/base/util/strings.web.js
react/features/base/util/uri.js

It crashes on Android. Well, on the JSC version React Native uses on Android.
While we could use this fallback only on Android, we have decided to use it
everywhere for consistency.

uri: avoid using String.prototype.normalize

---

react/features/conference/components/web/Subject.js

As the _participants count_ button looks weird without any text preceding it, the conference name was added as a fallback to subject.

Add conference name as fallback for subject

---

ios/scripts/release-sdk.sh

This makes it possible to compile the SDK with Xcode 10 and 11. The problem is
that the Google SDK (used for sign-in) is compiled with Xcode 11. This avoids
the issue.

ios: disable bitcode when building the SDK for a release

---

modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/VideoContainer.js
modules/UI/videolayout/VideoLayout.js

Steps to reproduce the issue:
1) Join a call from 3 tabs - A, B, C
2) A - starts screen sharing and is audio muted, B - only video muted, C - audio and video muted
3) C swtiches to tile view.
4) Wait until B becomes dominant speaker.
5) C returns back to stage view. The large video's height is 0.

fix(large-video): missing video.

---

react/features/deep-linking/components/DeepLinkingMobilePage.web.js

Instead let the mobile OS take care of opening the URL
in the appropriate application. Without target _blank,
iOS 13.2.2 on Chrome will open about:blank and immediately
close the tab instead of opening the store.

fix(mobile-landing): do not attempt opening download link in new window

---

modules/UI/videolayout/VideoContainer.js

In addition to the issue with the avatar position described in https://github.com/jitsi/jitsi-meet/pull/4862, the same issue applies for the position of the status message and remote connection status message.

fix(remote-status-message): position

---

doc/debian/jitsi-meet/jitsi-meet.example

Fixes nginx match rule, containing wrong chars.

---

react/features/base/conference/functions.js
react/features/base/util/uri.js
react/features/recent-list/functions.native.js

Handles both encoded and non encoded room names

feat: safe decodeURIComponent

---

css/_videolayout_default.scss
modules/UI/videolayout/VideoContainer.js

The vertical alignment was being set with javascript.
Recent changes might make the setting of alignment exit
early due to height 0 video. As position can be set
declaratively with css, use css to set position.
Steps to Reproduce bug:
1. User A start a new meeting.
2. User A video mute.
3. User B join the meeting.
Result: User B sees User A's avatar on stage but at the top of the page because top position was not set.

fix(large-video): center dominant speaker avatar using css

---

css/_chat.scss

fix(chat): wrap long text

---

css/_chat.scss

fix(chat): preserve intentional linebreaks in message display

---

conference.js
react/features/analytics/middleware.js
react/features/base/conference/middleware.js
react/features/base/media/actions.js
react/features/base/media/constants.js
react/features/base/media/middleware.js
react/features/base/tracks/functions.js
react/features/base/tracks/middleware.js
react/features/stream-effects/presenter/JitsiStreamPresenterEffect.js
react/features/stream-effects/presenter/TimeWorker.js
react/features/stream-effects/presenter/index.js
react/features/toolbox/components/VideoMuteButton.js

- Adds the ability to share video as a Pip when screenshare is in progress.
- Local video is controlled only by the camera button when screenshare is in progress.
- The resolution for the presenter camera is calculated based on the resolution of the desktop share that is in progress.
- A new media type "presenter" has been added and the newly created video track is added to the redux store. No new presenter APIs have been added.
- This PR has changes only for the presenter mode, the crop effect and renaming of the tensor flow related bundle changes will be in separate PR

Feature: Presenter mode

---

android/build.gradle

It can now be automated in a CI environment as follows:
yes | sdkmanager --licenses

android: remove old code for accepting SDK license

---

conference.js

- Presenter mode is off by default when screensharing is started.
- The user can continue to turn camera on/off while screensharing is in progress to enable or disable presenter mode.
- When screensharing is turned off, we revert the video to the state it was before screensharing was turned on.

feat(presenter): Modify the default behavior for presenter mode.

---

android/sdk/src/main/java/org/jitsi/meet/sdk/ConnectionService.java
android/sdk/src/main/java/org/jitsi/meet/sdk/RNConnectionService.java
react/features/mobile/call-integration/middleware.js

Some Samsung devices will fail to fully engage ConnectionService if no SIM card
was ever installed on the device. We could check for it, but it would require
the CALL_PHONE permission, which is not something we want to do, so fallback to
not using ConnectionService.

android: handle ConnectionService failures more resiliently

---

conference.js
package-lock.json
package.json
react/features/base/tracks/functions.js
react/features/base/tracks/middleware.js

- Reuse the existing JitsiLocalTrack for the presenter video on presenter unmute.
- Dispatch a new UIEvent PRESENTER_MUTED when the JitsiLocalTrack mute handler emits a TRACK_MUTE_CHANGED event after muting/unmuting the presenter track.
- handle device selection changes properly when screenshare is in progress.
- dispatch setVideoMuted only for camera/presenter track and not for desktop tracks.

fix: Reuse the existing JitsiLocalTrack on presenter unmute

---

react/features/room-lock/middleware.js

This addresses a bug, in which submitting a password
through the iframe api no longer closes RoomLockPrompt,
by explicitly closing prompts for a lock or password.
Note that I am not familiar with the various conference instances that can exist in redux. I am unsure if there is a guarantee that conference join is the correct place to ensure the prompt dismissals. As such, this PR is a workaround as far as I know, but maybe someone knowledgeable can say it's the fix.

fix(lock): ensure lock prompt is closed on password submit

---

conference.js

Firefox doesn't return the width/height of the desktop stream that is returned by getDisplayMedia.
The canvas for presenter mode cannot be created if the application window size cannot be determined. Therefore, add a workaround by applying constraints on the existing MediaStreamTrack.

fix: Workaround on FF for getting the resolution of the desktop track

---

package-lock.json
package.json
react/features/stream-effects/blur/JitsiStreamBlurEffect.js
react/features/stream-effects/blur/index.js

- Update to bodyPix 2.0
- Change settings for personSegmentation to improve performance.
- Earlier multiple instances were running in parallel because it was taking longer than the default 50 ms on some of the slower machines making it completely unusable.
- We are now waiting for the person segmentation to be complete before calling it again when the TimerWorker handler is invoked.
- By doing this, the cpu and memory consumption when blur feature is turned on have come down drastically.

fix(blur): update to bodyPix 2.0

---

react/features/base/connection/actions.native.js

Do not return anything from JitsiConnection.connect, because it's not a promise and returns void. Doing so is confusing to the reader.

ref(base/connection/actions.native): JitsiConnection.connect returns void

---

android/sdk/src/main/java/org/jitsi/meet/sdk/AmplitudeModule.java

Use ANDROID_ID:
https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID

android: add a consistent device ID in Amplitude

---

conference.js
css/_subject.scss
doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
package-lock.json
package.json
react/features/base/conference/actionTypes.js
react/features/base/conference/actions.js
react/features/base/conference/functions.js
react/features/base/conference/reducer.js
react/features/conference/components/ConferenceTimer.js
react/features/conference/components/native/ConferenceTimerDisplay.js
react/features/conference/components/native/NavigationBar.js
react/features/conference/components/native/index.js
react/features/conference/components/native/styles.js
react/features/conference/components/web/ConferenceTimerDisplay.js
react/features/conference/components/web/Subject.js
react/features/conference/components/web/index.js
resources/prosody-plugins/mod_conference_duration.lua
resources/prosody-plugins/mod_conference_duration_component.lua

This PR adds a timer that starts after the first participant joined the meeting. The timer represents the duration of the meeting formatted using dateUtil function. Timer should show under the meeting subject.
Web screenshot :
Mobile screenshot :

Add conference timer

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
resources/prosody-plugins/mod_conference_duration.lua

Using underscore in the address results:
```
lua5.1: /usr/lib/prosody/util/openssl.lua:109: attempt to concatenate a nil value
stack traceback:
/usr/lib/prosody/util/openssl.lua:109: in function 'add_sRVName'
/usr/lib/prosody/util/openssl.lua:133: in function 'from_prosody'
/usr/bin/prosodyctl:739: in function 'config'
/usr/bin/prosodyctl:836: in function </usr/bin/prosodyctl:829>
(tail call): ?
/usr/bin/prosodyctl:1523: in main chunk
[C]: ?
```
when installing jitsi-meet-prosody package and breaks jitsi-meet new installations.
The error was that `idna_to_ascii` return nil in the code:`ia5string("_" .. service .. "." .. idna_to_ascii(host))`.

Fixes conference duration config to use valid IDNA.

---

package-lock.json
package.json

Fixes an issue with not loading sounds on iOS when the bundle name contains
spaces.
See:
https://github.com/jitsi/react-native-sound/commit/3fe5480fce935e888d5089d94a191c7c7e3aa190

deps: react-native-sound@latest

---

react/features/base/media/middleware.js

When ensureTrack is set to true a track will be created with the given media
type. 'presenter' is not supported on RN.

rn,media: avoid creating presenter tracks

---

config.js
connection.js
connection_optimization/do_external_connect.js
doc/debian/jitsi-meet/jitsi-meet.example
doc/example-config-files/multidomain/config.js.multidomain.example
doc/example-config-files/multidomain/jitsi.example.com.multidomain.example
react/features/analytics/functions.js
react/features/base/connection/actions.native.js

Config.js will allow to specify both BOSH and Websocket URLs(even at the same time). In such case the web app will prefer Websocket over BOSH. The reason is that it appears to be more stable and a bit faster on web, while on mobile Websocket is dropped too quickly(killed by the OS) on network changes.

feat(config.js): add 'websocket' config option

---

webpack.config.js

Without changing the 'Host' header, a standalone instance we use for
jitsi dev work will generate:
config.websocket = 'wss://localhost:8080/xmpp-websocket'
This was fine with BOSH, but a Websocket will not connect.
With this change it will be(based on the default devServerProxyTarget):
config.websocket = 'wss://alpha.jitsi.net/xmpp-websocket'

fix(webpack.config.js): specify Host header in the  webpack  proxy pass

---

resources/prosody-plugins/mod_auth_token.lua

When using SASL anonymous to create a anonymous domain while using JWT tokens to authenticate on the main domain I found that jitisi`s custom mod_auth_token defines an anonymous mechanism but fails to set the required temporary username for SASL anonymous to work. Setting the temporary username allows to configure a secure domain (https://github.com/jitsi/jicofo#secure-domain) with JWT token authentication.

Set SASL username when using anonymous mechanism with auth_token

---

react/features/notifications/functions.js
react/features/presence-status/functions.js

Protect ourselves against interfaceConfig being undeclared. typeof
interfaceConfig will return "undefined", but that's different than having some
window.interfaceConfig = undefined, even though the valus is the same. The
former will give a ReferenceError.

notifications,presence-status: check if interfaceConfig is declared

---

package-lock.json
package.json

@tensorflow-models/body-pix@2.0.4 requires tfjs version to be higher than 1.3.1
This PR fixes the below warnings seen on npm install
npm WARN @tensorflow-models/body-pix@2.0.4 requires a peer of @tensorflow/tfjs-converter@^1.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN @tensorflow-models/body-pix@2.0.4 requires a peer of @tensorflow/tfjs-core@^1.3.1 but none is installed. You must install peer dependencies yourself.

deps(blur): Bump tfjs to 1.5.1

---

react/features/base/connection/actions.native.js

When the location URL contains a nonstandard port, it won't be included in
URL.hostname, but it will in URL.host.

rn,connection: fix autogenerated BOSH address

---

conference.js
react/features/base/tracks/functions.js

Resize the desktop MediaStreamTrack to 720p using applyConstraints for the following cases
- When the track height cannot be determined (firefox doesn't seem to return the track settings.
- Determine if the window is in portrait/landscape mode and resize only the dimension which is bigger than 1280/720. The other side resizes to preserve the aspect ratio.
- Add more 4:3 resolutions to pick from when the camera stream is obtained.
When the presenter is turned on, we start sending full 30 fps which can be very cpu intensive if the shared desktop window is very big.

fix(presenter): resize desktop track to 720p when presenter starts

---

android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java

In 49e3b03885bd0c00fcd9b64c2f4d6b77ad68b62a we turned on SW encoders / decoders
on account of some devices having broken HW *encoders* and also our desire for
using simulcast.
Well, the astute reader may have noticed that only *encoding* was mentioned.
Indeed, we should be able to keep using the HW decoder just fine.

android: turn on HW video decoder

---

react/features/filmstrip/components/web/Filmstrip.js

The filmstrip div was covering the large video and was preventing the controller mouse events to reach to be captured.

fix(remote-control): mouse events

---

modules/UI/UI.js
modules/UI/etherpad/Etherpad.js
modules/UI/shared_video/SharedVideo.js
modules/UI/videolayout/Filmstrip.js
modules/UI/videolayout/VideoContainer.js
modules/UI/videolayout/VideoLayout.js
react/features/filmstrip/functions.web.js
react/features/video-layout/middleware.web.js

Since the verical filmstrip doesn't set its width explicitly anymore,
calculating the available area for the large video based on the
filmstrip width retrieved from the HTML element was wrong
in the cases when the rendering and cleanup of the filmstrip hasn't
finish yet. For example when switching from tile view to stage view.

fix(large-video): Resize calculations.

---

react/features/base/config/configWhitelist.js
react/features/feedback/actions.js

This PR adds a config.js value to let the deployment decide how often we want the app to ask the user for feedback (defaults to 100, 100 = always, 0 = feedback disabled)

allow setting the feedback percentage

---

react/features/recent-list/functions.web.js

Checked the code of react.native part, there's no issue by using safeDecodeURIComponent.
So fixed it in same way.

fixed the encoded tiltle issue in chinese

---

react/features/base/tracks/functions.js

Trying to start USB camera (especially Logitech Brio) with non-standard 4:3 resolutions like 320x240, 800x600, etc. doesn't seem to be working. The getUserMedia is successful but the stream returned by the browser is distorted.

fix(presenter): go back to using standard resolutions for presenter

---

react/features/base/dialog/functions.js
react/features/mobile/full-screen/middleware.js

This has the side effect of showing the bottom navbar when the toolbox is open,
which is a nice thing since back is accessible.

full-screen: fix not re-entering full-screen after dialog is shown

---

conference.js
react/features/screenshot-capture/actions.js

This effect doesn't modify the media stream, so its safe to start/stop effect and not apply it on the JitsiLocalTrack. This way we can make sure that this effect is not switched out when presenter effect is applied.

fix(screenshot-capture): Do not switch streams at the conference level.

---

package-lock.json
package.json

To get a workaround in for wired desktop
screensharing in spot in electron 8. With
the change, no "exact" is used in gum
constraints while attempting to get the
wired screensharing device, as that
triggers overconstrainederror.

chore(deps): update lib to 47c2bc6

---

android/app/src/main/java/org/jitsi/meet/MainActivity.java

It's the source of uncountable problems for which we don't have a good
solution, since they are caused by buggy implementations of self-managed
connection services by manufacturers.

android: disable ConnectionService for the Jitsi Meet app

---

react/features/screenshot-capture/actions.js
react/features/screenshot-capture/logger.js
react/features/stream-effects/screenshot-capture/ScreenshotCaptureEffect.js

The effect was being re-initialized on each toggle, so a guard was needed for that.
Removed extraneous interface method that is no longer called due to us only using the start/stop effect methods, but moved the stream type check in the start method.

fix(screenshot-capture): Prevent effect initialization on each toggle

---

modules/UI/videolayout/VideoContainer.js
react/features/large-video/components/LargeVideoBackground.web.js
react/features/stream-effects/presenter/JitsiStreamPresenterEffect.js

It appears that if we try to draw into a hidden canvas that is attached to the DOM tree there's memory leak on electron 7.
Electron issue: https://github.com/electron/electron/issues/22417

Fix electron 7 memory leak

---

react/features/filmstrip/components/web/Toolbar.js
react/features/toolbox/components/web/Toolbox.js

Regresssion from bd8a7edbd2f9e3058b67d39fdc1c78156902f995.
When the toolbar buttons are overridden with URL parameters, our computed set of
buttons will be wrong. Thus, compute it every time and check for the
differences.

fix(optimise): cope with URL interface config overrides

---

resources/prosody-plugins/mod_speakerstats_component.lua

If the dominant speaker leaves their object will be gone from the mapping.

ssperakerstats: prevent access of nil object

---

conference.js
react/features/base/devices/functions.js
react/features/base/devices/reducer.js

Logs the device list when is updated in the reducer and removes
"button enabled" logging which used to dump the device list, but
in a useless way(Object[Object]).
Makes an attempt to log currently selected device, but because of
multiple possible paths it's impossible to find one reliable spot to log
selected device. One has to rely on device list and the GUM call logged
to figure things out.

ref(log): debug device list and selected devices

---

package-lock.json
react/features/filmstrip/subscriber.web.js
react/features/video-layout/functions.js

Yesterday I was playing a game of Magic: The Gathering with my brother and the tile-view layout is perfect for this. The recording, however, included tons of margin, which made following the game remotely bad.
Upon inspection it turns out there was an off-by-1 calculation error for the tile sizes: the loccal participant must not be accounted for in the recorder case, because it's not rendered! This fixes that.

Fix tile-view sizes for the recorder

---

package-lock.json
package.json

Updates lib-jitsi-meet to 567ba72675b1bfd5931e7d4936a4e53ebb4ef5f2 in
order to fix "not connected" error when jiconop is enabled.

deps: update LJM to fix ATTACHED state not connected

---

package-lock.json
package.json

Updates lib-jitsi-meet to aadfce2283cad4de3cb58c2eed8e14d2ce62c465 in order to fix "not connected" error when jiconop is enabled.

deps: update LJM to fix Strophe.attach not handled correctly

---

doc/manual-install.md

Jitsi Meet electron won't work against servers without this config bit
EDIT: Also added information about JVB binding on 443/4443 and a config bit to prevent a race condition where JVB starts before nginx.

Add nginx config for the electron version in manual install doc

---

doc/quick-install.md

We ran into https://github.com/jitsi/jitsi-meet/issues/2780
Adding the domain to `/etc/hosts` as suggested by a comment in this ticket seems to solve this, and https://www.scaleway.com/en/docs/setting-up-jitsi-meet-videoconferencing-on-debian-stretch/ also suggests doing this as a first step.
As such, here is a pull request to add this step to the quick install doc :-)
Have a good day

doc (quick install): Add the domain to /etc/hosts

---

modules/API/external/external_api.js

Starting from version 74, firefox need to be explicitly allowed to capture the screen from an iframe for screensharing. This new Feature-Policy is called "display-capture".
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/display-capture

fix(external_api): Fix screensharing for firefox 74

---

android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java

We see tons of crashes on Samsung and Huawei devices. It's really not worth the
headache anymore.
> “When defeat comes, accept it as a signal that your plans are not sound, rebuild those plans, and set sail once more toward your coveted goal.”
― Napoleon Hill,

android: revert back to SW decoding

---

config.js

Prevent possible json parse errors when the configuration values are
commented or commented out.

Add trailing commas and 'end' entry for peacy JSON

---

doc/quick-install.md

- removed paragraph about old Debian Wheezy, the link is broken, and Wheezy doesn't even get security updates anymore, so seems unlikely anyone would do a new install with it.
- clarified that Let's Encrypt script uses only the HTTP challenge.
- added links to a few things that newbies might want to look up (nginx, apache, jetty, SIP, FQDN, Let's Encrypt, etc.
- added some basic debugging starting points, based on my experience
- some minor grammatical tweaks
- other minor tweaks

Various improvements to quick-install document

---

lang/main-fr.json

"toggle camera" is to switch front to rear or rear to front.
The french translation said "on/off camera", it's not exactly that

Correct bad translation

---

interface_config.js

Worldwide users will profit from the change to auto-detect the browser language and to startup the interface with their language.

Change language detection to "true"

---

doc/manual-install.md

Added clarifications that user needs updated npm and node versions on some versions of Linux: e.g Ubuntu 18.04 has node v8.10 and npm v3.5

Added details to jitsi-meet deployment

---

react/features/welcome/components/AbstractWelcomePage.js
react/features/welcome/components/WelcomePage.web.js

Fix for #5447 
Tested in Chrome with calendar not configured and RECENT_LIST_ENABLED: false

Hide tabs if nothing to show

---

resources/prosody-plugins/mod_muc_max_occupants.lua

In a typical Jitsi Meet setup, this plugin can be used to limit the number of occupants in a meeting room, while ignoring "utility" users. Such a configuration could be:
muc_max_occupants = 2
muc_access_whitelist = {
"focus@auth.meet.jitsi";
}
It would be expected that this configuration allows two users to attend the meeting room, but in practice only one is allowed, because the whitelist is not honoured.
This commit fixes it by actually updating the `user` and `domain` variables being checked. After this change, the scenario above works just fine.

Fix mod_muc_max_occupants to properly ignore whitelisted users

---

lang/main.json

Changes the wording from this:
To this:

feat: better room lock prompt

---

react/features/base/toolbox/components/AbstractButton.js
react/features/base/toolbox/components/ToolboxItem.web.js
react/features/toolbox/components/web/ToolbarButton.js

Fixes https://github.com/jitsi/jitsi-meet/issues/4541
This focuses on the buttons/toggles along the bottom of the app.
Uses the ARIA authoring practices as a base, marks the buttons as
`role=button`
`tabIndex=0` (to make them reachable via TAB)
`aria-pressed` (to mark it as a toggle and expose its state)
more info: https://www.w3.org/TR/wai-aria-practices-1.1/examples/button/button.html
Handles onKeyDown to trigger on ENTER (like a <button> does)
Handles onKeyUp to trigger on SPACE (like a <button> does)
The latter here means ignoring PTT whilst the user has an interactive button focused. PTT remains to work when anything else is focused.

Improve accessibility of Buttons in Webapp

---

react/features/recording/components/LiveStream/web/StreamKeyForm.js

The target parameter from window.open was missing which was causing
reload in electron.

fix(livestreaming): window.open params

---

config.js

Some cameras may not be able to satisfy it and gUM will fail.
Refs: https://github.com/jitsi/lib-jitsi-meet/pull/1066

config: remove aspect ratio constraint from config example

---

doc/debian/jitsi-meet/jitsi-meet.conf

Fixes #5649
nginx presents the client's list of ALPN protocols as $ssl_preread_alpn_protocols, a comma-separated string. Use regular expressions to match each item in the list, rather than the exact value of the entire list at once.

Use regexes to match ALPN protocols

---

doc/development.md

[Low Priority]
Adds a note to the web development docs on how to solve a security issue when running the server locally in the newest versions of Chrome.

Update docs with privacy error in Chrome

---

doc/debian/jitsi-meet/jitsi-meet.conf

[PR 5216](https://github.com/jitsi/jitsi-meet/pull/5216) fixes #5209 for an installation without jitsi-meet-turnserver. However jitsi-meet-turnserver.postinst enables the doc/debian/jitsi-meet/jitsi-meet.conf nginx module, which overwrites the external nginx listening port. This PR adds the missing IPv6 listener in this nginx module.

add missing IPv6 listener to nginx jitsi module

---

react/features/invite/components/dial-in-summary/web/NumbersList.js

Related to #5697.
I know that converting to upper case fixes the issue in #5697. But I haven't tested if PR builds and/or does not error, or if the linter passes. (How to run the linter?) I tried to build this but `make` does not work for me because the `libs` dir is created too late. (And I assume for now it's my mistake and not a broken Makefile).
```
./node_modules/.bin/webpack -p
rm -fr libs
cp \
build/app.bundle.min.js \
build/app.bundle.min.map \
build/do_external_connect.min.js \
build/do_external_connect.min.map \
build/external_api.min.js \
build/external_api.min.map \
build/flacEncodeWorker.min.js \
build/flacEncodeWorker.min.map \
build/device_selection_popup_bundle.min.js \
build/device_selection_popup_bundle.min.map \
build/dial_in_info_bundle.min.js \ …
```

Pass upper case country codes to i18n-iso-countries

---

css/_audio-preview.css
css/_video-preview.css
react/features/overlay/functions.js
react/features/settings/actionTypes.js
react/features/settings/components/web/audio/AudioSettingsHeader.js
react/features/settings/components/web/audio/MicrophoneEntry.js
react/features/toolbox/components/web/AudioSettingsButton.js
react/features/toolbox/components/web/VideoSettingsButton.js

@saghul Thanks for the quick MR on removing the unneeded option. Had no clue we want to use the buttons all the time. :(
I have addressed almost all the comments from https://github.com/jitsi/jitsi-meet/pull/5481, except https://github.com/jitsi/jitsi-meet/pull/5481#discussion_r401698459.
Here is the explanation: 
* That action is needed because I'm using _object shorthand form_ (https://react-redux.js.org/using-react-redux/connect-mapdispatch#two-forms-of-mapdispatchtoprops) for actions. This way the components don't need to know about logic outside or have access to `dispatch`. They are easier to maintain and to understand. Ideally I think all react components should be as _dumb_ as possible. But if anybody has strong opinions on this we can talk.
As a side note I have a question, which …

fix(prejoin_page): Enable settings buttons on permission grant & CSS fixes

---

doc/debian/jitsi-meet/jitsi-meet.example

The provided nginx configs do not enable gzip by default, nor do they enable caching of the content.  This pull request enables both gzip and content caching, via the expires header.
As the content has a version string appended, it should be safe to cache the content for longer periods of time, though the etag field should cover content changes as well.  I'm flexible on the content caching part of this, if people have strong opinions there.
However, the gzip option changes the main page load from 4.6MB of content to 2.0MB of content - which makes a difference on low bandwidth connections, for minimal server CPU.  The compression applies for meeting resources as well, and I see no downsides for enabling compression in the default configuration.
I've not added Apache config changes, as …

Add gzip and expires to nginx server config.

---

modules/UI/videolayout/VideoContainer.js

In preparation for the lib-jitsi-meet PR for Safari support, isSafariWithWebrtc() will no longer be available

fix(safari): Update the check for Safari

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java

In the Android SDK, the setServerURL option is erroneously ignored. The meeting's serverURL always defaults to https://meet.jit.si because the serverURL is not parceled.
I've verified that this fixes the issue with custom serverURL values.

fix: Parcel the serverURL in the Android SDK (#5504)

---

react/features/base/dialog/components/native/BottomSheet.js
react/features/base/toolbox/components/ToolboxItem.native.js
react/features/toolbox/components/native/Toolbox.js

This pull request adds various commits to fix issues mentioned in #5817 .
* The buttons are buttons.
* Toggled on buttons are selected.
* The toolbox is a tool bar.
* The bottom sheet is a menu.
Things still unsolved:
* Hints are not yet assigned. Looks like they are the same as the visible label when not toggled in most cases, so don't actually add any value for screen reader users. I might drop this.
* The thing that is the area where one clicks to close is not yet a button and has no label. I haven't found that particular component yet.
* Same goes for the unlabeled area before the video element in the swiping order.
These changes are untested, since I cannot actually build for react native or test on a device at the moment. I am leaving this open for edits by maintainers so you can …

React Native accessibility fixes

---

lang/main-de.json

Fix key for german translation. But apparently, this is off in many other translation files, too (sorry, sparse time).
CLA already signed.
```bash
$rgrep suboptimalExperienceDescription lang -l                                             git:(de_i18n|) 
lang/main-kab.json
lang/main-it.json
lang/main-tr.json
lang/main-af.json
lang/main-enGB.json
lang/main-km.json
lang/main-az.json
lang/main-nb.json
lang/main-ja.json
lang/main-nl.json
lang/main-cs.json
lang/main-et.json
lang/main-fi.json
lang/main-sv.json
lang/main-vi.json
lang/main-hr.json
lang/main-da.json
lang/main-eo.json
lang/main-hy.json
lang/main-sl.json
```

i18n: german, fix translation key.

---

lang/languages-es.json

Using right word to describe Japanese in Spanish

Using "Japonés" instead of "Jopones"

---

doc/README.md
doc/example-config-files/scalable/jicofo_config.scalable.example
doc/example-config-files/scalable/jicofo_sip-communicator.properties.scalable.example
doc/example-config-files/scalable/meet.example.com.cfg.lua.scalable.example
doc/example-config-files/scalable/prosody.cfg.lua.scalable.example
doc/example-config-files/scalable/videobridge_config.scalable.example
doc/example-config-files/scalable/videobridge_sip-communicator.properties.scalable.example
doc/manual-install.md
doc/scalable-installation.md

This documents a 1-n installation of one jitsi-meet server with several load balanced videobridges.

Document a scalable installation with multiple videobridges

---

react/features/unsupported-browser/components/browserLinks.js
static/recommendedBrowsers.html

This should be self-explaining: I noted the browser links in jitsi meet are http. Obviously these days all upstream URLs for browsers support or default to HTTPS.

Update browser links to HTTPS

---

Makefile

This change also places `robots.txt` in the archive created when creating a source package with `make source-package`.

Also ship robots.txt in the source package

---

react/features/base/toolbox/components/AbstractButton.js
react/features/base/toolbox/components/ToolboxItem.web.js
react/features/toolbox/components/web/ToolbarButton.js

Reverts jitsi/jitsi-meet#5432. It looks like this needs a little bit more work, so that it doesn't break PTT. A possible solution could be to add an option to enable accessibility mode with a shortcut key?

Revert "Improve accessibility of Buttons in Webapp"

---

lang/languages-es.json
lang/languages-esUS.json

Adding Spanish translations of Hebrew literal for **_es_** (Spanish) and **_esUS_** (Spanish (Latin America)) that have not been translated yet.
https://www.rae.es/drae2001/hebreo

Adding Spanish translation of "Hebrew" literal

---

lang/main-es.json

The literal of the button in "Manage Call Quality" in Spanish says "Insert your name here" instead of "done" (probably due to a C&P).
This change uses the same literal that was proposed in [Spanish (Latin American)](https://github.com/jitsi/jitsi-meet/blob/5c39a2f6a6e59b2c4f9c40715ee31d2791915f9d/lang/main-esUS.json#L177): "Listo". 
It sounds fine in both variants of Spanish language.

Fixing wrong text at key "done" in main-es.json

---

modules/UI/videolayout/SmallVideo.js
react/features/large-video/components/LargeVideo.web.js

The playsInline attribute needs to be set to true for video to be rendered on Safari on iOS

fix(safari): set playsInline attribute to true on the video element

---

package-lock.json
package.json

Changelog:
101fecbb Thu Apr 16 11:23:58 2020 +0200 Philipp Hancke: e2ee: decode static black frame for decryption errors (#1098)
c3fd3431 Thu Apr 16 13:09:18 2020 +0200 Philipp Hancke: e2ee: remove encodedFrameType workaround (#1099)
git log --no-merges --reverse --pretty="%h %ad %an: %s" 70a3298914f3905297e4e9dcc200b95e9b7a73e9..c3fd3431a66556de7b2ec7632f9f6d75b64aad0a

deps: bump lib-jitsi-meet

---

doc/development.md

The development doc mentions `beta.meet.jit.si` as the default dev backend however the webpack config default to the alpha intead:
```
const devServerProxyTarget
= process.env.WEBPACK_DEV_SERVER_PROXY_TARGET || 'https://alpha.jitsi.net';
```

fix dev server backend default in development doc

---

css/_avatar.scss
react/features/base/avatar/components/web/StatelessAvatar.js

Reason: On Safari the foreign object is not scaled correctly.

fix(avatar): use text instead of foreign object.

---

resources/prosody-plugins/mod_conference_duration_component.lua

It's starting at 1 hour because os.time(os.date("!*t") returns the wrong
time depending on system timezone. os.time() already returns the number
of seconds since epoch in UTC so just use that.
Fixes #5595

Conference timer should start counting at 0

---

modules/UI/videolayout/RemoteVideo.js

Replaces the .oncanplay listener with addEventListener('canplay', ...).
This is needed because third party libraries (for example callstats)
are brutally overriding the .oncanplay property and replacing our
listener.

fix(RemoteVideo): .oncanplay -> addEventListener

---

react/features/base/i18n/languageDetector.native.js

The Android app fail to detect locale for some languages with country code like pt_BR or zh_TW. The application expects the language to be without underscore (ptBR or zhTW).

fix locale detect error on mobile apps (android and ios)

---

doc/quick-install.md

This command uses the technique recommended below that will always work. (See "Safest Solution (#3)") 
https://askubuntu.com/questions/185268/permission-denied-etc-apt-sources-list

Fix the command to update jitsi-stable.list

---

conference.js
doc/api.md
modules/API/API.js
modules/API/external/external_api.js
react/features/base/participants/actionTypes.js
react/features/external-api/middleware.js

Added participantRoleChanged event to the external API.
The event is fired when the conference participant role changes. This was done to facilitate the use of the password command - which can only be invoked if the participant is the moderator.

Add participantRoleChanged event to external API

---

react/features/base/participants/middleware.js

getLocalParticipant returns a participant object stored in Redux, not a
JitsiParticipant object.

participants: fix accessing the local participant ID

---

conference.js
config.js
package-lock.json
package.json
react/features/base/config/configWhitelist.js
react/features/base/lib-jitsi-meet/functions.any.js
react/features/overlay/components/AbstractPageReloadOverlay.js

The reason for that it's currently causing issues with signaling when
Octo is enabled. Also when we do an "ICE restart"(which is not a real
ICE restart), the client maintains the TCC sequence number counter, but
the bridge resets it. The bridge sends media packets with TCC sequence
numbers starting from 0.
The 'enableIceRestart' config option can be used to force it, but it's
not recommended.
FIXME: update LJM before merging

ref: disable ICE restart by default

---

doc/quick-install.md

Some OS have greater values thant the one you propose.
They must not be lower.
I propose to update the doc and let user check their own values and update only if needed.

Update Doc regarding systemd/system.conf default values

---

resources/prosody-plugins/token/util.lib.lua

When using jitsi-meet with jwt, and jwt in invalid format, 
I get an error **/jitsi-meet/resources/prosody-plugins/token/util.lib.lua:258: Expected value but found invalid token at character 1**. So the purpose of this minor fix is ​​to catch the error, and return early without causing the frontend to hang.

change cjson to cjson.safe and catch error from decode function

---

react/features/base/i18n/customNavigatorDetector.js
react/features/base/i18n/languageDetector.web.js

* Fix detection order, use browser language before config language.
* Use a custom navigator detector to return names in the format "enUS" instead of "en-US".
I've already sign the CLA

fix: Fixed browser language detect (close #5987)

---

Makefile

We don't support it, so make sure targets run serially.
Fixe: https://github.com/jitsi/jitsi-meet/issues/6647

build: fix using parallell make

---

ios/sdk/src/picture-in-picture/PiPViewCoordinator.swift

The dynamic size of it was causing trouble. Fix it by setting a fixed PiP window
size (150px) which makes it consisstent with what we have on Android.
Fixes: https://github.com/jitsi/jitsi-meet/issues/6562

ios: fix PiP window sshowing conference controls

---

react/features/deep-linking/components/DeepLinkingMobilePage.web.js

The ocnfig is not overridden early enough.
Fixes: https://github.com/jitsi/jitsi-meet/issues/6489

deep-linking: fix generating links for external API

---

css/_prejoin.scss
react/features/prejoin/components/Prejoin.js
react/features/prejoin/components/buttons/ActionButton.js
react/features/prejoin/components/preview/ParticipantName.js
react/features/prejoin/functions.js

* The prejoin page always displays the 'join without audio' option.
* The join button will be disabled if there is no input.
* Fix some CSS for the case when the user is not anonymous.

fix(prejoin_page): Always show 'join without audio' & add disabled button

---

webpack.config.js

I was testing some translations but `make dev` kept serving me outdated files.

webpack-server-dev: don't proxy /lang/

---

react/features/deep-linking/components/DeepLinkingMobilePage.web.js

This update opens links in the full body of the window so deeplinks will work on iOS Safari when using the external API in an iFrame.

Fixed using deeplinks using external API

---

package-lock.json
package.json

fix(Firefox): Enable RTX support on Firefox
E2EE fixes/improvements
fix(screenshare): Add google conference flag only when simulcast is on
fix(video-quality): Apply pending video constraints on p2p originator

chore(deps): Update lib-jitsi-meet

---

react/features/deep-linking/components/DeepLinkingMobilePage.web.js

This breaks the mobile deeplinking page
This reverts commit 532dadb245c749f93e3c9ded8e66f17196ced15b.

Revert "external_api: fixed using deeplinks"

---

lang/main-de.json

The former translation contained a typo and incorrect grammar.

Fix passwordLabel translation

---

react/features/deep-linking/components/DeepLinkingMobilePage.web.js

Set `target='_top'` inside anchor.
Courtesy of #6700 by @msalmasi
Follow-up to: #6784
1. Open https://localhost:8080/test
2. Make sure `target='_top'` is applied to the button and the link
3. Make sure `target='_top'` is not appended as a plain text

Retry "external_api: fixed using deeplinks"

---

debian/control

Since `debian/rules` uses nodejs:
```
LANGUAGES := $(shell node -p "Object.keys(require('./lang/languages.json')).join(' ')")
```

debian/control: add missing build dependency on nodejs

---

lang/readme.md

It looks like i18n updates are done manually editing files there. http://translate.jitsi.org is not there anymore.

Update lang readme to match reality

---

debian/jitsi-meet-turnserver.postinst
doc/debian/jitsi-meet-turn/turnserver.conf

- adds the resolved ipv6 and ipv4 to external-ip if found
fixes #6165

jitsi-meet-turn: fix getting an external ip in IPv6 enabled networks

---

react/features/base/i18n/BuiltinLanguages.native.js

Translations were already added in a previous commit, but we still need to change BuiltinLanguages.native.js so that mobile apps have the lang available.

lang: enable support for romanian lang

---

config.js

We are not actively testing it and it currently crashes Chrome 83+ when insertable streams are used.

config: don't enable H.264 by default on P2P

---

react/features/room-lock/components/RoomLockPrompt.native.js

Prompt when trying to join a locked meeting.
Prompt when adding a password to a meeting without one.
The latter used to be the same as the former, which is incorrect.

rn: fixup room lock prompt messsage

---

react/features/base/jwt/middleware.js
resources/prosody-plugins/mod_muc_allowners.lua

When a user joins such room or subdomain in order to be a moderator needs to provide a valid jwt token for that room.

Moderated rooms or subdomains

---

conference.js
css/_audio-preview.css
react/features/base/devices/actions.js
react/features/base/devices/functions.js
react/features/toolbox/components/web/AudioSettingsButton.js

Pass the real deviceId to gUM instead of 'default' for Chrome to return the correct media stream.
Update userSelectedAudioOutputDeviceId and userSelectedAudioOutputDeviceLabel when a new speaker is selected from the audio settings popup menu.
Disable audio settings pop-up on Firefox as changing mics isn't currently supported.

Fix audio device selection

---

modules/UI/videolayout/LocalVideo.js
react/features/base/media/components/web/Video.js
react/features/device-selection/components/VideoInputPreview.js
react/features/settings/components/web/video/VideoSettingsContent.js

> playinline attr needs to be set to true to stop local video from playing in full screen mode in Safari on iOS.
> This applies to the local video thumbnail and the camera previews from the device selection menu and video preview button.

fix(UI): add playsinline attr for video element

---

react/features/base/conference/middleware.js

There are occasions when role to moderator can change a little bit after joining the room, and initial try to set subject will silently be ignored if not moderator.

fix: Fixes setting subject from url.

---

react/features/base/conference/actions.js
react/features/base/conference/middleware.js

After https://github.com/jitsi/jitsi-meet/commit/929622b27c3a407b42cf18fdc9ac9713bc076010 we observed a regression in an 8x8 backend service. Upon closer examination, I noticed than an extra unneeded update was being sent when no subject is specified, this should fix that.

Fixup subject update

---

conference.js
css/_settings-button.scss
react/features/base/media/functions.js
react/features/base/settings/functions.web.js
react/features/base/tracks/actions.js
react/features/base/tracks/functions.js
react/features/base/tracks/middleware.js
react/features/prejoin/actionTypes.js
react/features/prejoin/actions.js
react/features/prejoin/components/Prejoin.js
react/features/prejoin/functions.js
react/features/prejoin/middleware.js
react/features/prejoin/reducer.js
react/features/toolbox/components/AudioMuteButton.js
react/features/toolbox/components/VideoMuteButton.js
react/features/toolbox/components/web/VideoSettingsButton.js
react/features/toolbox/functions.web.js

On @saghul 's suggestion:
The audio & video prejoin tracks are no longer stored in _'features/prejoin'_ but in '_features/base/tracks_'. This simplifies the logic by having single points of failure and leverages code reuse.

fix(prejoin): Store prejoin tracks in 'features/base/tracks'

---

debian/jitsi-meet-web-config.postinst

Without this line the certificate will be rejected by all versions of Chrome since v59 (May 2017).
Also bumped up the self signed cert duration: as an intranet system admin pushing out new self signed certs as a group policy to all users every single year is simply too much.

Added ssl options for SubjectAlternativeName (SAN) Closes #5547

---

react/features/base/conference/constants.js

720 is requested by default for the local video stream
and when using the quality slider the resolution would
be increased to 1080.
Note that this will limit the receive quality to 720 as well,
because both send and receive constraints are changed at
the same time when the quality slider is used.

ref(constants): use 720 for the high quality level

---

css/_labels.scss
react/features/conference/components/web/Conference.js

The tooltip of the CircularLabel components were not visible in tile view because filmstrip was rendered on top of them, so the hover event didn't kick in

fix: label tooltips are not visible in tile view

---

css/modals/invite/_invite_more.scss
css/modals/security/_security.scss
react/features/e2ee/components/E2EESection.js
react/features/invite/actionTypes.js
react/features/invite/actions.any.js
react/features/invite/components/add-people-dialog/web/InviteContactsForm.js
react/features/invite/middleware.web.js
react/features/lobby/components/web/LobbySection.js
react/features/security/components/security-dialog/SecurityDialog.js

- Disables the invite buttons while invites are ongoing
- Adds a keyboard shortcut (Enter) to send out invites
- Closes AddPeopleDialog upon successful invites sent
- Fixes the SecurityDialog closing when trying to set E2EE key via Enter shortcut
- Removes superfluous separator from SecurityDialog

fix(AddPeopleDialog): Improve contact invite form

---

css/_welcome_page.scss

fix: layout of the insecure room name warning icon

---

react/features/conference/components/web/Conference.js

Stacking the `toolbar` and the `lobby screen` will prevent opening audio/video options for the lobby.
This fixes the problem by not rendering the toolbar if the `lobby screen` is visible.

fix: Show audio/video options on lobby screen

---

react/features/settings/components/web/audio/AudioSettingsContent.js
react/features/settings/functions.js

Right now, on the audio settings popup, only the levels for the microphone in use are shown.
This fixes the problem so the levels for all the microphones will be displayed.

fix(settings): Always show mic audio levels

---

conference.js
react/features/base/tracks/functions.js

When on prejoin screen, if the device list changes (devices are added or removed),
the newly created tracks do not properly replace the old ones, resulting in
errors after joining the meeting and trying to change the devices.
This change fixes the problem.

fix(prejoin): Replace the stored audio/video tracks when device list changes

---

interface_config.js

Documenting for per #7170, but it would be nice to either rename this option to `AVAILABLE_BUTTONS`, or create a mechanism to move some buttons out of the way into the <kbd>More actions</kbd> menu.

TOOLBAR_BUTTONS clarifications

---

react/features/toolbox/components/web/AudioSettingsButton.js
react/features/toolbox/components/web/VideoSettingsButton.js

Mobile devices do not support capture from multiple cameras/mics at a time.

fix: disable audio/video settings popup on mobile browsers

---

resources/prosody-plugins/mod_muc_size.lua

When you are using mod_muc_size plugin, and trying to get room info (/root api url) you get the following error, when didn't add subdomain to the GET parameters:
http.server                                                         error       Traceback[httpserver]: /usr/lib/prosody/util/async.lua:137: /prosody-plugins/mod_muc_size.lua:141: attempt to concatenate local 'subdomain' (a nil value)
Similar to the room_size handler, add the subdomain existence condition.

prosody muc_size plugin, room get info error fix

---

debian/jitsi-meet-web-config.postinst

The wrong quotes error:
req: Error on line 354 of config file "/dev/fd/63"
Error Loading extension section SAN
140403719438784:error:0E06C069:configuration file routines:NCONF_get_section:no conf:../crypto/conf/conf_lib.c:245:
Having the ip and specifying dns:
Error Loading extension section SAN
140127168778688:error:220A4076:X509 V3 routines:a2i_GENERAL_NAME:bad ip address:../crypto/x509v3/v3_alt.c:457:value=jitsi.example.com
140127168778688:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:../crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=DNS:localhost,DNS:jitsi.example.com,IP:jitsi.example.com

fix: Fixes generating self-signed certificate.

---

connection.js
react/features/prejoin/actionTypes.js
react/features/prejoin/actions.js
react/features/prejoin/components/Prejoin.js
react/features/prejoin/functions.js
react/features/prejoin/reducer.js

A user should not be forced to enter a display name if the lobby is not enabled for the room.

fix(prejoin): Make display name mandatory only for lobby

---

lang/main-tr.json

non valid turkish language file causes language change to turkish impossible, neither default language as tr works. removed comma end of json array, tested with unstable installation

fixed non valid json turkish language file

---

config.js
debian/jitsi-meet-turnserver.postinst
doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
doc/debian/jitsi-meet-turn/turnserver.conf
doc/debian/jitsi-meet/jitsi-meet.conf

See https://github.com/jitsi/jitsi-meet/pull/5714#issuecomment-615491997
This change moves STUN/TURN to the IANA-assigned ports, 3478 and 5349 (TLS)

Move STUN/TURN to IANA-assigned ports - 3478 and 5349 (TLS)

---

resources/prosody-plugins/mod_muc_poltergeist.lua

This PR fixes https://github.com/jitsi/jitsi-meet/issues/7250  and Add avatar to user context so it is picked by the web interface
Here a screenshot with the working version
This is my first contribution here, I did sign the CLA

Add avatar to poltergeist user presence

---

css/_premeeting-screens.scss
index.html
react/features/base/app/components/BaseApp.js
react/features/base/premeeting/components/web/PreMeetingScreen.js
react/features/base/premeeting/components/web/Preview.js
react/features/base/tracks/functions.js
react/features/base/tracks/middleware.js
react/features/prejoin/components/Prejoin.js
react/features/prejoin/components/PrejoinApp.js
react/features/prejoin/middleware.js
react/index.web.js
static/prejoin.html

Added capability for rendering different app screens from the same app.bundle.
Exposed Prejoin screen to allow reuse of its video preview and device selection capabilies

feat(prejoin) expose prejoin page

---

config.js
react/features/base/config/configWhitelist.js

The maxaveragebitrate parameter to be used by Opus can be configured
through the new opusMaxAvgBitrate config option. Values are restricted
by Opus to integers between 6000 to 510000. Works for non-p2p only.
Depends on https://github.com/jitsi/jicofo/pull/551 and https://github.com/jitsi/lib-jitsi-meet/pull/1219

config: Add option to set preferred audio bitrate.

---

lang/main.json
package.json
react/features/connection-indicator/components/web/ConnectionIndicator.js
react/features/connection-stats/components/ConnectionStatsTable.js

Adds the max enabled resolution in a parenthesis right next to the resolution stat
I'm marking this as a draft PR because we may want to change the UI before merging this.

feat: Exposes the max enabled resolution in the connection stats popover.

---

react/features/base/flags/constants.js
react/features/conference/components/native/NavigationBar.js

This PR will add a "conference-timer.enabled" flag that will allow to show / hide the conference timer

add feature flag to enable / disable conference timer

---

react/features/conference/components/native/LonelyMeetingExperience.js

Showing the modal earlier is weird because it will be closed as soon as we
connect. Also, we don't know if we are going to be alone until we join.

rn,conference: show lonely experience only after joining

---

react/features/conference/middleware.js

Part of [1] replaces a `setPreferredVideoQuality` call with a
`setMaxReceiverVideoQuality` call. The change was part of a bigger
changeset that adds logic that tries to adjust the max based on reduced
ui turned on or off and allow to set prefered through the config.
However, by calling `setMaxReceiverVideoQuality` instead of
`setPreferredVideoQuality`, the new feature overrides the lower
resolution requested by tile-view earlier in some occasions.
This PR reverts back to using `setPreferredVideoQuality` instead of
`setMaxReceiverVideoQuality` as this achieves the same result without
overwriting the max set by the tile-view.
[1]: https://github.com/jitsi/jitsi-meet/commit/7d513738d2179b68a8b21233d2bc9e93d3da05ab

fix: Avoid overwriting the max resolution requested by the tile-view.

---

css/_base.scss
css/filmstrip/_tile_view.scss
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/native/TileView.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/subscriber.web.js

First part of a two-part feature that makes chat push the content to the side rather than display over it. The large-view implementation is underway.

feat(chat): Make chat push content to the side in tile view

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java
android/sdk/src/main/java/org/jitsi/meet/sdk/PictureInPictureModule.java
react/features/mobile/picture-in-picture/components/PictureInPictureButton.js

Despite running Android 8.1, they don't support Picture-in-Picture.

android: disable PiP on Android Go devices

---

react/features/remote-video-menu/components/AbstractGrantModeratorButton.js

Use the same moderator semantics when adding items into the remote video menu as when showing/hiding the items themselves.

fix: use consistent moderator semantics

---

config.js
react/features/base/config/configWhitelist.js

Must match the lib-jitsi-meet counterpart.
Fixes: https://github.com/jitsi/jitsi-meet/issues/7384

config: fix opusMaxAverageBitrate option name

---

react/features/chat/components/native/Chat.js

create TOGGLE_CHAT action when chat modal is closed to correctly update chat isOpen state

fix: no new msg notifications after opening chat modal  [NATIVE]

---

modules/API/API.js
modules/API/external/external_api.js

Adds `enableLobby` command to the IFrame API that enables lobby for the conference when executed.
Example execution:
`api.executeCommand('toggleLobby', true);`

Toggle lobby via IFrame API command

---

resources/prosody-plugins/mod_websocket_session_event.patch

It's to be used in docker-jitsi-meet to patch older Prosody versions until this change becomes available.

add mod_websocket patch for session event

---

modules/UI/shared_video/SharedVideo.js
modules/UI/videolayout/SmallVideo.js
react/features/base/lastn/middleware.js
react/features/conference/components/web/InviteMore.js
react/features/follow-me/middleware.js
react/features/follow-me/subscriber.js
react/features/remote-video-menu/components/native/PinButton.js
react/features/toolbox/components/web/Toolbox.js
react/features/video-layout/actions.js
react/features/video-layout/components/TileViewButton.js
react/features/video-layout/functions.js
react/features/video-layout/middleware.any.js
react/features/video-layout/middleware.web.js
react/features/video-layout/reducer.js
react/features/video-layout/subscriber.js
react/features/youtube-player/components/_.web.js
react/features/youtube-player/components/index.js
react/features/youtube-player/components/native/index.js
react/features/youtube-player/constants.js
react/features/youtube-player/functions.js
react/features/youtube-player/index.js
react/features/youtube-player/middleware.js

This PR implements auto tile view based on the following logic:
- Tile view now has an "undefined" state, that means that the user hasn't requested any views in particular. In this case we use auto switching based on a few rules (see `video-layout/functions.js`)
- Once the user has selected one, we try to respect that, however we still auto-switch to tile view on screen share or Etherpad editing (is that still a thing btw?)
- Auto switching respects the previously selected state when the cause for auto switch is over
- We don't persist the tile view setting anymore to promote auto switching

feat: auto tile view

---

conference.js

We found few instances in callstats where we couldn't find a corresponding SS stopped event for a SS started event.
Turns out we do not send the event when there is no video to switch to after the share is stopped.

fix: Send SS stopped analytics event when SS was started in video muted state

---

config.js
react/features/base/config/configWhitelist.js
react/features/video-quality/middleware.js

Add a config option with the default value of 4, which will cap the max recv video quality to SD if there's more participants in the conference while in the tile view mode.

feat(video quality): add maxFullResolutionParticipants

---

interface_config.js
react/features/deep-linking/components/DeepLinkingDesktopPage.web.js
react/features/deep-linking/components/DeepLinkingMobilePage.web.js

This adds the ability to configure hiding the logo on the deep linking page.
HIDE_DEEP_LINKING_LOGO defaults to false in the config.
The implementation also defaults to showing the logo if HIDE_DEEP_LINKING_LOGO is missing from the config.

Add config to hide logo-deep-linking on deeplinking page

---

android/app/src/main/java/org/jitsi/meet/MainActivity.java

When exiting PiP with by pressing the X the onPictureInPictureModeChanged method
is called. Since onResume is called a while after, in case the maximize button
is called, it's not easy to know if the user pressed the X button, and that was
the cause for exiting PiP.
So, in order to avoid show the user they are still in the meeting, bring the
activity to the foregound so they can hangup.

android: bring back activity to the foreground when exiting PiP

---

connection.js
react/features/base/connection/actions.native.js
react/features/base/jwt/logger.js
react/features/base/jwt/middleware.js

Does not skip passing jwt even when malformed to allow getting the error, terminating the connection and showing the warning. We were not passing jwt when malformed and were successfully joining a conference for deployments where no token is allowed.

fix: Fixes uncaught exception on malformed jwt.

---

conference.js
package-lock.json
package.json

In cases where there is no room like pre-join and lobby screen we still want to be able to debug xmpp messages.
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/1284

ref: Moves xmpp logs to be accessed from connection.

---

conference.js
react/features/app/actions.js
webpack.config.js

Create a separate chunk for the close3 page in order to enable it to dictate the `readyToCloseFlow` at will, if the appropriate flag is set in interfaceConfig.

feat(close3): Move readyToClose flow to the close page

---

config.js
react/features/base/conference/functions.js
react/features/video-quality/constants.js
react/features/video-quality/functions.js
react/features/video-quality/index.js
react/features/video-quality/middleware.js
react/features/video-quality/reducer.js
react/features/video-quality/selector.js

Allows to adjust thresholds which control the video quality level
in the thumbnail view.
Changes the default behavior to request the SD (360p) resolution only
when the thumbnails are at least 360 pixels tall and the height of
720 is required for the high quality level.
The thresholds can be configured with the 'videoQuality.minHeightForQualityLvl'
config property. Check the description in the config.js for more details.

feat: configurable quality levels per video thumbnail height

---

react/features/base/devices/middleware.js
react/features/base/settings/middleware.js
react/features/device-selection/functions.js

Prejoin screen ignores ifame API parameters

---

react/features/app/actions.js
react/features/app/middlewares.any.js
react/features/base/react/components/web/Watermarks.js
react/features/billing-counter/actionTypes.js
react/features/billing-counter/actions.js
react/features/billing-counter/constants.js
react/features/billing-counter/functions.js
react/features/billing-counter/logger.js
react/features/billing-counter/middleware.js
react/features/chrome-extension-banner/components/ChromeExtensionBanner.web.js
react/features/recording/components/Recording/StartRecordingDialogContent.js

* Sends a counter request on every meeting join on vpaas meetings.
* Removes the extension banner for vpaas meetings.
* Removes default logo for vpaas meetings.
* Changes the recording icon for vpaas meetings.
* Redirects to / after the meeting ends for vpaas meetings.

feat(vpaas): Add endpoint counter & remove branding for vpaas meetings

---

debian/jitsi-meet-tokens.postinst

`jitsi-meet-tokens` does not check correctly the package status during the installation. It search for `--plugin_paths` which is never exists on the new usual installation and skips the `if` block.
I think searching for an enabled token auth line is a better way to check this.
* if there is no enabled token line then this is the first installation and needs a config change
* if there is an enabled token line then `jitsi-meet-tokens` was installed before

jitsi-meet-tokens: fixed the first installation check

---

debian/control

_I sent [a similar pull request](https://github.com/jitsi/jitsi-meet/pull/7616) before but it was closed because of the dublicated commits. Sorry for that. I prepared a clean pull request for the same issue._
`jitsi-meet-tokens` has a missing dependency. `luajwtjitsi` could not be installed if git does not exist.
This is the output during the installation:
```
Installing https://luarocks.org/luajwtjitsi-1.3-7.rockspec
Error: 'git' program not found. Make sure Git is installed and is available in your PATH (or you may want to edit the 'variables.GIT' value in file '/etc/luarocks/config.lua')
Failed to install luajwtjitsi - try installing it manually
```

jitsi-meet-tokens: added git to the dependency list (2)

---

debian/control

I closed [the old pull request](https://github.com/jitsi/jitsi-meet/pull/7607) which has a conflict issue.
`jitsi-meet-tokens` is trying to install `luacrypto` which depends on `libssl1.0-dev` but `jitsi-meet-tokens` also depends on `libssl-dev` which is compiled against `openssl1.1` on Debian Buster. Therefore  it's impossible to install `jitsi-meet-tokens` on Debian Buster if it doesn't accept `libssl1.0-dev` as an alternative to `libssl-dev`

jitsi-meet-tokens: added libssl1.0-dev to the dependencies as an alternative

---

debian/jitsi-meet-tokens.postrm

`token_verification` is enabled while removing `jitsi-meet-tokens' but the opposite is required. This commit fixes this issue.

jitsi-meet-tokens: disable token_verification while removing

---

debian/jitsi-meet-tokens.postrm

`plugin_paths` is disabled while removing `jitsi-meet-tokens` but this line is enabled by default and not activated during the `jitsi-meet-tokens` installation. And this will cause errors if there are other enabled modules.
Therefore no need to disable `plugin_paths` while removing the package.

jitsi-meet-tokens: keep plugin_paths while removing

---

debian/jitsi-meet-tokens.postinst

The postinst script is searching for `--modules_enabled = { "token_verification" }`. But there is no such a line on the standard config file. This is from a typical config file
```
modules_enabled = {
"muc_meeting_id";
"muc_domain_mapper";
-- "token_verification";
}
```
I added a `sed` command for this format.
Please, don't add the `g flag` to `sed`.

jitsi-meet-tokens: enable token_verification during installation

---

react/features/app/reducers.any.js
react/features/dynamic-branding/index.js

Import 'dynamic-branding' reducer on all platforms to have the default state initialized.

fix(RN): crash on undefined state['features/dynamic-branding']

---

react/features/mobile/call-integration/middleware.js

When you join a conference that needs an authenticated moderator, as a guest, Jitsi Meet will continuously try and connect to the meeting every 5 seconds.
For every retry, on iOS, a new CallKit call is created, causing the call to loose audio, and loose control over the call.
This fixes that, by only creating a call on CallKit, if one has'nt already been created.

Fix CallKit integration on iOS for conferences requiring moderator

---

ios/Podfile.lock
package-lock.json
package.json
react/features/mobile/polyfills/browser.js

Ever since facebook/react-native#23674 landed it has
been possible to run timers in the background, assuming your app is allowed to
run in the background already, as is our case. So, stop using the library on
iOS, which will avoid creating needless background tasks.

ios: stop using react-native-background-timer

---

webpack.config.js

app.bundle.js before: 3851549 after: 4506493.
The culprit for the bloat was Olm. It feature-detects the environment in order
to pick a suitable random byte generator, and alas Webpack includes the None
crypto pollyfill. This is due to the existence of the "node" block in our
Webpack configuration file.
The solution is to provide empty modules to make bundling work, as we did
already for the fs module, since we know they are not used at runtime.

fix(build) reduce bundle size by about 700K

---

modules/UI/videolayout/LargeVideoManager.js

Deduct the chat window width from large-video width only once if we keep toggling between stage view and grid view while the chat window is open.

fix(UI): Re-compute large-video width only once if the chat window is open.

---

modules/API/external/external_api.js
react/features/large-video/actions.any.js
react/features/large-video/actions.web.js

Get the existing HTMLVideoElement for large video instead of creating a new video element for capturing the screenshot.
This should prevent the video player from getting displayed on mobile Safari.

fix(iframe): Use largeVideo video element for screenshot.

---

package-lock.json
package.json
react/features/base/react/components/native/Linkify.js
react/features/base/react/components/web/Linkify.js

Decode URLs using punycode when rendering, so when http://ebаy.com is sent
we render http://xn--eby-7cd.com/ instead.
Ref: https://github.com/tasti/react-linkify/issues/84

fix(chat) prevent homograph attacks

---

android/app/build.gradle
ios/Podfile
ios/Podfile.lock

Looks like the "Firebase Analytics" dependency is needed when migrating to the
new Firebase Crashlytics SDK. We are only interested in the "latest iversion
crash-free users" stat, which seems to require this. The documentartion is
somewhat confusing though.

fix(crashlytics) add missing dependency

---

react/features/base/tracks/middleware.js

This fixes the issue where the local preview appears muted when presenter camera is turned on and then off while screenshare is in progress.

fix(presenter): Do not change the video mute state on presenter mute.

---

static/close.js

There's a typo in line number 14, "meessage" should be "message".

Typo: In static/close.js 

---

app.js

If the WASM code could not be loaded, fail to initialize if and remove it from
globals so the E2EE option becomes unavailable, since it will be non-functional.

fix(e2ee) handle Olm initialization error

---

react/features/video-quality/components/OverflowMenuVideoQualityItem.web.js
react/features/video-quality/components/VideoQualitySlider.web.js
react/features/video-quality/constants.js
react/features/video-quality/functions.js
react/features/video-quality/middleware.js
react/features/video-quality/reducer.js

Change the preferredVideoQuality and maxReceiverVideoQuality values to Ultra HD resolution. The requested resolution can be as high as 4K to facilitate VPaaS customers to configure and request 4K. Currently, it is capped at 720p.
With the recent changes made to SenderVideoConstraints, the send resolution will never exceed the value configured in the video constraints from config.js settings since we now calculate how much the original stream has to be scaled down to in order to derive the new stream instead of directly applying constraints with the new resolution. The scaleResolutionDownBy factor cannot be less than 1 - https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/TraceablePeerConnection.js#L2314 and therefore the sender video resolution will always max out at the value …

fix(video-quality): Add the ability to receive Ultra HD resolutions

---

app.js
css/_base.scss
package-lock.json
package.json
webpack.config.js

Preserve accessibility when navigating via keyboard but hide the focus border when clicking on buttons in the conference. This uses a polyfill for the :focus-visible selector since it does not yet have full browser support.
Tested this via Chrome (Beta) and Firefox on Windows

fix: Show focus indicator only when navigating via keyboard

---

modules/UI/videolayout/VideoLayout.js

If a failure occurs while we are still setting up the UI it's possible the local
thumbnail is still null, and none of the code assumes it may be null, so skip
it.

fix(VideoLayout) make thumbnail iteration more resilient

---

package-lock.json
package.json

The URL polyfill we were using didn't support taking a URL object in the
constructor, the updated one does.

fix(rejoin) fix adding track parameters to rejoin URL

---

modules/UI/videolayout/LargeVideoManager.js

Since the external API now sets preferredWidth/preferredHeight for resizing the large video, we don't need to add chat width to the computed window width when the chat window is closed.

fix(UI): Do not re-compute the container width when chat window is closed

---

react/features/stream-effects/presenter/JitsiStreamPresenterEffect.js

...so that the text is more readable in the presenter mode. Chrome by
default uses 'detail' for screen sharing. I went with the 'text' here,
because the docs[1] say "may take advantage of encoder tools that
optimize for text rendering." - whether that's good specifically for
the presenter mode I don't know. It looked good for me when tested
on Chrome.
https://www.w3.org/TR/mst-content-hint/
PLEASE TEST THIS WITH jitsi-meet I was cherry picking from a branched fork which is not exactly the same.

feat(presenter): apply 'text' contentHint

---

resources/prosody-plugins/mod_speakerstats_component.lua

In some situation `mod_speakerstats_component.lua` gives the following errors. I tried to reproduce the error in my test environment but no success... I only see this errors on my production server after a prolonged high load.
I couldn't find the root cause but the commit fixes the symptons. Sometimes there is no `speakerStats` for the existing room or no room at the occupant leave time.
When checked the community forum, it seems that this problem isn't new.
https://community.jitsi.org/t/duration-time-not-showing/41206/35
```
Oct 01 06:01:59 c2s555e1f6ba990 error   Traceback[c2s]: ...itsi-meet/prosody-plugins/mod_speakerstats_component.lua:193: attempt to index field 'speakerStats' (a nil value)
stack traceback:
...itsi-meet/prosody-plugins/mod_speakerstats_component.lua:193: in function …
```

fix: speakerstats_component, attempt to index (a nil value)

---

modules/API/API.js
modules/API/external/external_api.js

Add methods for start/stop recording in addition to the commands that we already have.
The existing youtube options could have been renamed and made more generic but leaving them in for backward compatibility.

feat(iFrame): Add recording options for RTMP streaming.

---

css/_prejoin.scss
css/_premeeting-screens.scss

This can be tested by turning off both the mic and the camera on the prejoin screen. 
The content should not move anymore.

fix(prejoin): Fix moving content when device status bar is toggled

---

react/features/large-video/actions.web.js

Participants that join video muted do not have video tracks attached. Fixes https://github.com/jitsi/jitsi-meet/issues/7942.

fix(iFrame): captureScreenshot - check if the remote participant has a  track attached.

---

conference.js
react/features/base/media/functions.js
react/features/base/media/middleware.js

- Currently when startWithVideoMuted flag from the local storage is true we will first create the video track and then mute it which will turn on the light on the camera for a moment. This is concerning for some users! Also in the case when startWithVideoMuted is set trough the URL we don't create a video track at all. This PR will unify the implementation of handling startWithVideoMuted from the URL and localStorage and a video track won't be created at all.
- The behaviour is similar when the user is muted and there is a device change. This PR changes the implementation to delay the track creation until the moment user unmutes.

Fixes the issue with turning on the camera for a moment when muted

---

ConferenceEvents.js
conference.js
modules/API/API.js
modules/remotecontrol/RemoteControl.js
react/features/base/conference/actionTypes.js
react/features/base/conference/actions.js
react/features/base/conference/reducer.js
react/features/toolbox/components/web/Toolbox.js

There is no need for setting the availability of desktop sharing anymore. It can
now be detected on the spot.
The reson for the previous code was that way back when browser extensions were
needed, it was possible to start a conference without desktopo sharing support
and get it afterwards. This is no longer the case.

fix(conference) remove no longer needed code

---

resources/prosody-plugins/util.lib.lua

Stringify boolean values that might appear in the JWT user context in order to avoid stanza parsing error.

Stringify boolean values from jwt user context

---

conference.js
config.js
package-lock.json
package.json
react/features/stream-effects/presenter/JitsiStreamPresenterEffect.js

Do not resize the desktop share to 720p by default when the desktop track resolution is higher than 720p. This is causing blurriness when presenter is turned on.
Remove the 'detail' contentHint setting for the desktop+presenter canvas stream as it forcing chrome to send only 5 fps stream for high resolution desktop tracks.
Move the desktop resizing logic behind a config.js option - videoQuality.resizeDesktopForPresenter.

fix(screenshare): Fixes for the blurry desktop share issues.

---

webpack.config.js

This PR allows path separator of `\` in addition to `/` in jQuery's path name, enabling `make dev` server to work on Windows 10.
The issue fixed by this PR is exactly #6844. I started a fresh checkout, ran `npm install`, and then `make dev`, and encountered the following error when loading `https://localhost:8080` in Chrome:
```
translation.js:27 Uncaught ReferenceError: $ is not defined
```
The browser page remains gray and fails to load.
The same error (though likely older versions of Jitsi) is reported by different people on https://stackoverflow.com/questions/57197208/jitsi-meet-compiled-from-source-but-got-error-when-run-dev-server and https://community.jitsi.org/t/get-javascript-error-when-compiled-from-source-and-start-with-dev-server/19048 and …

Fix webpack-dev-server on Windows

---

modules/API/external/external_api.js

Bwrosers have not allowerd WebRTC on non-secure origins for a very long time
now.

feat(external_api) drop support for noSSL option

---

react/features/room-lock/components/PasswordRequiredPrompt.web.js

This will make browsers not cache results in cleartext.
Co-authored-by: Tim Dittler <t.dittler@heinlein-support.de>

fix(password) set input type to "password"

---

lang/main.json
react/features/overlay/components/web/UserMediaPermissionsOverlay.js

This message was made more generic to accomodate JaaS users.

fix(vpaas): Make user media permission message more generic

---

package-lock.json
package.json

Safari 14.1 has a bug where it returns 720p for every simulcast stream when RTCRtpSender.getParameters is called even though the stream resolutions are different.
By using the encodings config used when source was added, on every RTCRtpSender.setParameters call, we ensure that simulcast stream resolutions don't change.

fix(safari): Ensure simulcast stream resolutions don't change.

---

css/_base.scss
css/_responsive.scss
react/features/toolbox/components/web/Toolbox.js

The intent of this is to keep the 'more' menu visible even past the 500px threshold. @jespino I noticed that you explicitly added these checks in order to hide the button, was that intended, and if so, could we possibly find a better way to customise hiding the button? As we've been receiving numerous complaints about it being missing

fix(Toolbox) Maintain overflow button visible at all times

---

resources/prosody-plugins/util.lib.lua

Partially revert 895c92217a16e63e1e4652db1944957249b30f37
by removing extract_subdomain method call because for root(public) conferences it returns the name of the room and not nil as previously. 
Because of this target_subdomain will have the name of the room and you will end up checking real room testandrei@conference.domain against [testandrei]testandrei@conference.domain.

Fix validation for root rooms

---

react/features/video-layout/functions.js

Follows me and switching to tile view, still works.

feat: Skips the default tile view when jibri is loading.

---

modules/UI/UI.js

This is needed for the torture clients to determine the video type for the remote participants when testing desktop share.

fix(UI): Add method for returning the video type of remote participants.

---

react/features/base/lastn/middleware.js
react/features/large-video/actions.any.js

When trying to auto pin screenshare, always select the endpoint even though it happens to be the large video participant in redux. The auto pin screenshare logic kicks in after the track is added.  If the screenshare endpoint is not among the forwarded endpoints from the bridge, it needs to be selected again.
If limitLastN values are specified and channelLastN < limitLastN, configure channelLastN on the conference.

Select screenshare endpoint always when auto pinning

---

config.js
react/features/connection-indicator/components/web/ConnectionIndicator.js
react/features/connection-stats/components/ConnectionStatsTable.js

As per @fremzy, the "Save Logs" feature generates a json
file with a bevy of technical information about the
meeting. This log contains the server name, server IP
address, participant's IP addresses (only in p2p sessions)
e.t.c. While this may be a useful feature for the
admin-like 'moderator', it creates unnecessary exposure
when made readily available to all users in the meeting.
This commit fixes #8036 by a config.js option to enable
the link (disabled by default), thus giving the owner of
the deployment the choice of enabling it or not.

feat: Makes it possible to hide the "Save Logs" link.

---

react/features/base/participants/functions.js

While the base URL remains configurable, this patch reverts back to using
Gravatar.
We noticed high latency with libravatar and contacted them. They are in the
process of migrarting to a better infrastructure (it's a single personal server
at the moment) so we'll re-evaluate once that has happened.
As for why not leave the default and change it on the meet.jit.si installation,
we don't want to kill their server :-)

fix(avatar) revert back to defaulting to Gravatar

---

css/filmstrip/_tile_view.scss
react/features/filmstrip/actions.web.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/subscriber.web.js

- Lower the inter-tile margin to 2px
- Remove the 100px top/bottom margin when the toolbar is hidden
Alternative to https://github.com/jitsi/jitsi-meet/pull/7817 which avoids overlapping UI elements by dynamically applying the margin.
Toolbar visible:
No toolbar:

feat(tile-view) optimize for less margins

---

conference.js

...caused by bad state as a result of timing issue around the prejoin flow.
If get user media call is delayed for a while and if user joins
the conference, when it hasn't completed then confrence.js will not assign
'localAudio' and 'localVideo' variables and will create additional media
tracks on unmute operation and add them to JitsiConference via replaceTracks
operation.

fix(conference.js): 2 tracks of the same media type

---

react/features/app/middlewares.any.js
react/features/app/middlewares.web.js
react/features/app/reducers.any.js
react/features/app/reducers.web.js

Middlewares should not be loaded on mobile as there is no way to use the
functionality.

fix(remote-control) skip on mobile

---

lang/main-sv.json

Fix Swedish translation of noPassword

(fix) main-sv.json - Swedish translation of noPassword was incorrect

---

lang/main-ru.json

Should be “toggle camera” instead of “enable/disable camera”.
See PR #5909 which updated only the accessibility label.

Update toggleCamera translation in main-ru.json

---

config.js
modules/UI/UI.js
react/features/base/config/configWhitelist.js

For sites that focus on collaborative editing during meetings, add an option which, when set, will automatically open etherpad when a participant joins using a browser.
The native mobile app is unchanged.  Because it uses the entire screen for the etherpad, opening it on joining may be confusing for users.  In that case, the current behavior is maintained.

Etherpad on join

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java

This may happen due to API misuse, but also in complex applications where
activity lifetimes are not straightforward.

fix(android) avoid crashes if view is null

---

debian/jitsi-meet-web-config.postinst

jitsi-meet-web-config 1.0.4466-1 ignores selection of cert and key path.
Postinst script overrides cert-path-key and cert-path-crt with defaults.
You can reproduce like this (replace your.domain.local with your own FQDN):
```
echo -e "jitsi-videobridge2\tjitsi-videobridge/jvb-hostname\tstring\tyour.domain.local" | debconf-set-selections
echo -e "jitsi-meet-web-config\tjitsi-meet/cert-choice\tselect\tI want to use my own certificate" | debconf-set-selections
echo -e "jitsi-meet-web-config\tjitsi-meet/cert-path-key\tstring\t/etc/letsencrypt/live/your.domain.local/privkey.pem" | debconf-set-selections
echo -e "jitsi-meet-web-config\tjitsi-meet/cert-path-crt\tstring\t/etc/letsencrypt/live/your.domain.local/fullchain.pem" | debconf-set-selections
apt install jitsi-meet
grep ssl_certificate …
```

fix(jitsi-meet-web-config.postinst) allow cert and key pre-selection

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
doc/debian/jitsi-meet/jitsi-meet.example
doc/debian/jitsi-meet/jitsi-meet.example-apache
doc/example-config-files/multidomain/jitsi.example.com.multidomain.example
doc/example-config-files/multidomain/prosody.cfg.multidomain.example
doc/example-config-files/prosody.cfg.lua.example
doc/example-config-files/scalable/jicofo_config.scalable.example
doc/example-config-files/scalable/meet.example.com.cfg.lua.scalable.example
doc/example-config-files/scalable/prosody.cfg.lua.scalable.example
doc/example-config-files/scalable/videobridge_config.scalable.example

Purely cosmetic changes to the various example files contained in ./doc, to use consistent 4-spaces indentations same as the main code, plus a few other minor formatting changes here or there.
Main purpose - other than 'looks nice' - is to get rid of the occasional mix of space and tabs, as that messes with editor display.
No functional changes.

Consistent formatting/indentation of files in ./doc

---

resources/prosody-plugins/mod_token_verification.lua

This PR follows from the discussion here: https://community.jitsi.org/t/domain-validation-with-jwt-tokens/88602/6
This PR fixes issue where domain verification for JWT token fails if admin user is defined in config per host (which is the default) rather than globally. 
Without explicitly specifying `host` in the `is_admin` check, we do not properly detect focus user as admin and does not exclude the focus user from the domain check. This results in a failure during room creation.

fixed admin check for token verification

---

react/features/base/devices/functions.js

Check if adjusting audio output is supported rather than always fail on Safari for example.

fix(setAudioOutputDeviceId): check if supported

---

react/features/stream-effects/presenter/JitsiStreamPresenterEffect.js

Canvas rendering does not work as expected on Safari - the image stays
still on the first frame. Calling play() on the video tags seems to help.

fix(JitsiStreamPresenterEffect): frozen on Safari

---

react/features/settings/components/web/audio/AudioSettingsContent.js
react/features/settings/components/web/audio/MicrophoneEntry.js

It appears that at the time of this writing, creating audio tracks blocks
the browser's main thread for a long time on safari. Wasn't able to confirm
which part of track creation does the blocking exactly, but not creating
the tracks seems to help and makes the UI much more responsive.

audio output selection in safari blocks the UI

---

modules/API/API.js
modules/API/external/external_api.js
react/features/chat/middleware.js

- allow managing chat through API when chat button is not present on UI
@saghul @hristoterezov @quitrk 
Link to documentation PR: https://github.com/jitsi/handbook/pull/134

feat(external_api) set and cancel private chat through external API

---

css/_atlaskit_overrides.scss
css/_drawer.scss
css/_variables.scss
css/main.scss
css/modals/invite/_info.scss
css/modals/invite/_invite_more.scss
react/features/base/popover/components/Popover.web.js
react/features/filmstrip/constants.js
react/features/filmstrip/subscriber.web.js
react/features/invite/components/add-people-dialog/web/DialInNumber.js
react/features/remote-video-menu/components/web/RemoteVideoMenuTriggerButton.js
react/features/toolbox/actionTypes.js
react/features/toolbox/actions.web.js
react/features/toolbox/components/web/Drawer.js
react/features/toolbox/components/web/DrawerPortal.js
react/features/toolbox/components/web/OverflowMenuButton.js
react/features/toolbox/components/web/index.js
react/features/toolbox/reducer.js

* Implement opening toolbar and participant overflows as drawers when below certain width.
* Fix dial-in copy button displaying incorrectly.

feat(overflow): Add responsive drawer at small screen width.

---

package-lock.json
package.json

When an endpoint that doesn't support the preferred codec (VP9) joins a conference, all the other endpoints fallback to VP8 until the endpoint leaves the call.

feat: Add new codec selection mechanism.

---

package-lock.json
package.json
react/features/base/jitsi-local-storage/setup.web.js
react/features/billing-counter/actionTypes.js
react/features/billing-counter/actions.js
react/features/billing-counter/functions.js
react/features/billing-counter/middleware.js

Safari browser does not persist data between sessions for iframes hosted on a
different domain. In this case a mechanism of storing the billingId on the
parent localStorage was added.

fix(vpaas): Store billing id in parent lolcaStorage on Safari

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
package-lock.json
package.json
resources/prosody-plugins/mod_external_services.lua

The old mod_turncredentials.lua is left to continue working for those using old installs.
New install will start using the new module which will no longer be needed with prosody 0.12.
https://hg.prosody.im/prosody-modules/file/4841cf3fded5/mod_external_services/mod_external_services.lua
First we need to merge https://github.com/jitsi/lib-jitsi-meet/pull/1472 and then update the lib-jitsi-meet hash in this PR.

feat: Uses mod_external_services supporting urn:xmpp:extdisco:2.

---

lang/main-nl.json

Right now, the translation in the Jitsi app for the Dutch camera toggle feature says "Camera in- of uitschakelen", which translates to "Enable or disable camera", while the button toggles between the front and selfie camera. The better translation would be "Camera wisselen".

Corrected Dutch translation of toggleCamera

---

package-lock.json
package.json

RN doesn't support RTCRtpSender yet. Therefore, media is suspended on RN by changing the media direction in the SDP whenever the client receives an ideal height of 0 for sender constraints on the bridge channel.
LJM update - https://github.com/jitsi/lib-jitsi-meet/compare/3570339360763fa0911d92c5ae7c270860b6934b...be18ff34bedf38c7475fe4953074c7959000e15f.

feat: Implement aggressive layer suspension on RN.

---

debian/jitsi-meet-web-config.postinst

> If both softwares (nginx/apache) are installed, currently the user is not able to use apache as server. However, in some cases it might be necessary to do so. See #8474
This PR includes a small check for a pre-configured debconf variable `jitsi-meet/enforce_apache`. If set, the postinstallation-script uses apache, even if nginx is installed.
As it is only set via debconf (not as a requested setting on installation) this should be just a small additional option, that is only used if really necessary. Typical installations will still default to nginx, as preferred.
If this PR gets accepted, i would include the corresponding sentence on docs as a small hint, but without detailed istructions.
Greets! :)
Jonas

Allow to enforce Apache via debconf

---

config.js
css/_responsive.scss
css/filmstrip/_tile_view.scss
react/features/base/config/configWhitelist.js
react/features/filmstrip/actions.web.js
react/features/filmstrip/constants.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/subscriber.web.js
react/features/video-layout/functions.js

* Enforce fixed column number at various width breakpoints.
* Bring back the filmstrip at small sizes but hide it.
* Change default maximum columns to 7.

feat(tiles): Add responsive behaviour.

---

doc/debian/jitsi-meet/jitsi-meet.example

nginx's default mime.types file doesn't yet have a content-type mapping for wasm, so this PR includes one in the default jitsi-meet configuration file.
Otherwise you get 
```
olm.js:31 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ olm.js:31
olm.js:31 falling back to ArrayBuffer instantiation
(anonymous) @ olm.js:31
```
(and similarly for rnnoise), which means you won't use the WebAssembly-optimized implementations.

Add mime type mapping for wasm to default Debian nginx config.

---

conference.js

While on the prejoin screen, the local tracks are managed by the redux store and not conference.js, so localAudio is undefined.

fix(conference.js): crash on undefined

---

doc/debian/jitsi-meet/jitsi-meet.example-apache

Including the two proxy-configurations, which existed for nginx, but not for apache. This time i tested it myself already. 🙈 
According to the end of [this forum thread](https://community.jitsi.org/t/colibri-ws-websocket-not-working/88117) one could probably also remove the `ProxyPassReverse` lines, but this i did not test by myself yet and if they are not necessary, they won't have a bad effect anyways.

Include xmpp and colibri proxy for apache

---

android/sdk/src/main/java/org/jitsi/meet/sdk/OngoingNotification.java
android/sdk/src/main/res/values/strings.xml

Fix for https://github.com/jitsi/jitsi-meet/issues/6673.
Notification title and message can be localised by overrading string in client app (tools:override="true"). Action button text are hardcoded, which make them english-only.
Solution: move strings to res.

fix(android) add ability to localize notification actions strings

---

conference.js
package-lock.json
package.json
react/features/base/conference/actionTypes.js
react/features/base/conference/actions.js
react/features/rtcstats/middleware.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/1484
Send the conference unique identifier to the rtcstats-server in order to properly distinguish between individual sessions.

feat(rtcstats): send meeting uuid to rtcstats

---

config.js
package-lock.json
package.json

Add the ability to configure different max bitrates for VP8 and VP9.
Set max bitrate for presenter to 2500 Kbps irrespective of the configured max bitrates for video.
https://github.com/jitsi/lib-jitsi-meet/compare/479dd98...77978f0.

deps: Update latest@lib-jitsi-meet.

---

doc/debian/jitsi-meet/jitsi-meet.example-apache

I had to change the websocket URLs from http:// to ws:// to get websocket working with apache

change websocket url from http:// to ws://

---

resources/load-test/load-test-participant.js

This sets video constraints for the load-test webpage as if it were jitsi-meet receiving tile view in a reasonable window size.

Set receiver video constraint in load-test script, as-if tile view.

---

modules/API/external/external_api.js

The issue was that if you used youtube video sharing while uisng external api , the video was not auto playing in chrome.
With this fix, the reported issue #7037 will be resolved.

#7037: Issue #7037 fixed. Using youtube sharing in jitsi while using external api works

---

react/features/base/participants/preloadImage.web.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/8510
This basically reverts
https://github.com/jitsi/jitsi-meet/commit/a3fb996ff020a0984b0851981800a5e106e8a671
while retaining the same properties that prompted it's original intent, namely
avoiding sending the Referrer header.

fix(avatar) refactor preloading to avoid CORS issues

---

react/features/base/flags/constants.js
react/features/toolbox/components/HelpButton.js

Introduces a new feature flag (`help.enabled`) and uses that to determine the visibility of the 'Help' button in a call.

feat: Add feature flag for help button

---

package-lock.json
package.json

* fix(GUM-permissions): cache permissions on init.
* feat: Reuse billingId from localstorage as jitsiMeetId.
* fix(example) simplify
* feat(docs) mvoe API documentatrion to the handbook
https://github.com/jitsi/lib-jitsi-meet/compare/84357ce1a8d06c67a502709877130520aaf71592...d1f0ab4d5a691f438f7d4c7446f29273b1b8fcdc

chore(deps) lib-jitsi-meet@latest

---

resources/load-test/load-test-participant.js

Behaves now as the main client, and skips few unnecessary presences.

fix(load-test): Create local tracks and then join.

---

react/features/base/tracks/functions.js
react/features/prejoin/middleware.js

Can be reproduced by:
1. Start on the prejoin screen with camera turned off (that must be the initial state)
2. Turn the camera on and quickly join the meeting, before camera preview appears
3. It should crash with TypeError: Cannot read property 'isAudioTrack' of undefined if meeting is joined while get user media for camera is in progress.

fix: TypeError: Cannot read property 'isAudioTrack' of undefined

---

react/features/invite/components/add-people-dialog/web/DialInSection.js

Revert a change that might cause an issue in the display of dial in numbers until we have time to investigate the root cause.

Revert change to dial in numbers link

---

doc/debian/jitsi-meet/jitsi-meet.example-apache

- dropped uneccessary rewrite rule
- corrected number of trailing slashs in proxy directive
- corrected url for colibri websocket

Corrected example config for Apache

---

react/features/invite/components/add-people-dialog/web/DialInSection.js
react/features/invite/functions.js

This is a small change that hides the "more numbers" link if only one dial-in number is configured. 
It respects both supported configuration formats. The one described in the swagger spec (https://github.com/jitsi/jitsi-meet/blob/master/resources/cloud-api.swagger#L130) and the one described in the handbook (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#display-dial-in-information). 
maybe a good time to also update the handbook because the code states this format is obsolete.

Only show more numbers link if multiple numbers are available

---

react/features/base/i18n/customNavigatorDetector.js

For `navigator.languages` Chrome returns `['es']` but Safari returns `['es-es']` resulting in `eses` format which does not exists.
This PR normalizes the format:
```
en-US => enUS
en-gb => enGB
es-es => es
```
fixes #8261

Normalize language format

---

debian/jitsi-meet-prosody.postinst
debian/jitsi-meet-prosody.postrm
debian/jitsi-meet-tokens.postinst
debian/jitsi-meet-turnserver.postinst
debian/jitsi-meet-web-config.postinst
debian/jitsi-meet-web-config.postrm

((users doubleclick a host name and paste result in the installer)
how to reproduce ? install in a clean instance and add a space before the host name
Result:
https://community.jitsi.org/t/installation-problem-on-ubuntu-20-04-2-lts/94776

handles spaces around hostname

---

conference.js
react/features/base/conference/actions.js
react/features/prejoin/middleware.js

Do not add the muted audio tracks to peerconnection until the user unmutes the first time. This applies to startSilent, startWithAudioMuted and startAudioMuted/startVideoMuted config.js settings.

fix(tracks): Do not signal muted audio tracks.

---

react/features/base/flags/constants.js
react/features/conference/components/native/Conference.js
react/features/mobile/full-screen/middleware.js

Add a new mobile _Feature Flag_ called "fullscreen.enabled" (default value = true) which allows to disable the immersive mode, where the device's status bar and navigation bar (Android) are hidden.
Tested on LG G6 (Android 9.0) and iPhone 7 (iOS 14.4)
In reference to https://github.com/jitsi/jitsi-meet/issues/2771#issuecomment-788714328

Add fullscreen.enabled flag for mobile platforms

---

conference.js
modules/util/TaskQueue.js

Add try catch when executing the task in TaskQueue. This should prevent the queue for being blocked if the task throws an exception.
Add more logging around TaskQueue in order to be able to debug reports for blocked queue. 
Add more logging around useVideoStream in order to be able to debug reports of video unmute not executing.
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/1514

fix(useVideoStream): error handling & add logs.

---

modules/UI/videolayout/RemoteVideo.js

For the video to play on Safari mobile browser, the playsInline attribute needs to be set to true. Set the mute attribute as well which was accidentally removed in code refactor.

fix(UI): Add playsinline attribute for remote video.

---

react/features/stream-effects/virtual-background/JitsiStreamBackgroundEffect.js

THis will reuse the previously cached image and obey the base href.
Ref:
https://stackoverflow.com/questions/6241716/is-there-a-difference-between-new-image-and-document-createelementimg

fix(virtual-background) use a DOM element for storing the image

---

package-lock.json
package.json

Fixes a harmless but confusing error in postis processing when using the
Bitwarden Chrome extension, for example.

chore(deps) bump js-utils to 1.0.6

---

react/features/stream-effects/virtual-background/JitsiStreamBackgroundEffect.js

When we use a CDN the images come from an origin different than the site so
unless we mark them for CORS the canvas where they are painted will be tainted.
Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

fix(virtual-background) fix tainted canvas when using the CDN

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java

Check whether context is that of an Activity before launching the Jitsi Conference Activity. If context is not an activity context, apply flag `FLAG_ACTIVITY_NEW_TASK` to the Jitsi Activity Intent to ensure activity can launch without error.
This scenario would manifest when a user attempts to launch the Jitsi Actvity from a Widget... for example.
https://developer.android.com/about/versions/pie/android-9.0-changes-all#fant-required

Apply flags when launching activity from non-activity context

---

config.js
react/features/base/config/configWhitelist.js
react/features/base/participants/middleware.js

This PR adds an option `disableJoinLeaveSounds` to `config.py`, which can be set to `true` to disable the join/leave sounds (which I and my students found distracting in a large class meeting).  
I couldn't find a way to turn off the sounds with the current configuration options, short of replacing the WAV files with silence.  But if this kind of option already exists, or if there is a cleaner way to do this, I'd be interested to know :)

add option for disabling join/leave sounds

---

modules/API/API.js
modules/API/external/external_api.js
react/features/recording/middleware.js

A little while ago I created a similar pull request but after a bit of thought I realized I could improve it further. This pull request features an event emitted to external api when the recording status changes, but it also includes the errors (which previous pull request didn't).
If there are any improvements to be made, please do tell.

feat(iFrame): Emit event when recording status changes, including errors

---

package-lock.json
package.json
react/features/mobile/polyfills/browser.js

Promise.allSettled is supported from RN 0.63 onwards and is not supported on the current version, use a polyfill for that shims Promise.allSettled if its unavailable or noncompliant.
Co-authored-by: Saúl Ibarra Corretgé <saghul@jitsi.org>

feat(rn,polyfill): Add a polyfill for Promise.allSettled.

---

react/features/large-video/actions.any.js

Set higher preference for screenshare over dominant speaker when trying to elect a participant for large-video. This prevents the dominant speaker from taking over the stage when a user toggles tile view on and off while a screenshare is in progress.

fix(large-video): Always pin screenshare to large-video if it exists.

---

lang/main-fr.json
lang/main-frCA.json

change "cryptage" to "chiffrement"
cf: [chiffrer.info](https://chiffrer.info)

Fix french wording e2ee

---

react/features/toolbox/components/native/styles.js

fix(Toolbar, rn): Button overflow in landscape orientation

---

react/features/mobile/full-screen/middleware.js

Change required to account for immersive mode changes on Android, for example when a permission dialog pops up, which calls the `_setFullScreen` function. Without this change, the Jitsi conference returns to fullscreen even if the corresponding feature flag `FULLSCREEN_ENABLED` is set to false.

Add fullscreen.enabled flag for mobile platforms (correction)

---

react/features/toolbox/components/web/Toolbox.js

In https://github.com/jitsi/jitsi-meet/pull/8673 we inadvertently removed the
backwards compatibility code which would show the security button when the
"info" button is configured in interface_config. The security button replaced
the info button.

fix(toolbar) restore security button backwards compat

---

react/features/invite/functions.js

fix(sip-invite) do not send query params on sip invite request

---

react/features/toolbox/components/web/Toolbox.js

Fixed autohide not working in certain scenarios.
Problem was that `_onTabIn` event handler from components/web/Toolbox was writing the visible value directly in store through `setToolboxVisible(true)` action, without doing the extra processing done by `showToolbox` action - like setting the hideToolbar timeout.
When switching to other tab, waiting for more than like 5 seconds, when going back in the meeting tab following flow was happening:
Notice `hideToolba`r being called, which sets visible false in store, but immediately after, the `_onTabIn` event setting visible back to true, but without setting the auto-hide timeout. So from this moment on, the toolbar is always visible.
After the fix:
Notice the _onTabIn calling the correct action, `showToolbox`, which sets the auto-hide timeout …

fix(toolbox): Fix toolbox not auto-hiding.

---

resources/prosody-plugins/token/util.lib.lua

Add the possibility to use a JWT token that will have for the room field a regex. 
This is backward compatible with the existing solution.

Verify room name using regex in JWT

---

react/features/toolbox/components/web/Toolbox.js

Show the audio share button only when its supported. For example, mobile browsers do not support getDisplayMedia yet.

fix(audio-share): Show button only when supported by browser.

---

conference.js

Resizing of the desktop track on Firefox is not needed anymore since the browser now reports the correct resolution of the desktop track after the fix here - https://github.com/jitsi/lib-jitsi-meet/commit/ada0f5e537b8e8102cc99cf8982236e4aa6223d9.
Fixes https://github.com/jitsi/jitsi-meet/issues/8519

fix(presenter): Do not resize the desktop track on FF by default.

---

react/features/toolbox/components/web/Toolbox.js

Now toolbox is only kept visible when mouse is over the invite or toolbox buttons area.

fix(toolbox): hide toolbox when mouse outside toolbox area

---

config.js
react/features/base/config/configWhitelist.js
react/features/base/lastn/actionTypes.js
react/features/base/lastn/actions.js
react/features/base/lastn/functions.js
react/features/base/lastn/index.js
react/features/base/lastn/middleware.js
react/features/base/lastn/reducer.js
react/features/video-quality/components/VideoQualitySlider.web.js
react/features/video-quality/constants.js

Provides a way for the lastN value to be controlled through the UI. When startLastN is present, conference starts with a last-n value of startLastN and channelLastN value will be used when the quality level is selected using 'Manage Video Quality' slider. HD => channelLastN, SD => channelLastN/2, LD => channelLastN/4.

feat(last-n): Implement startLastN and make last-n configurable through UI.

---

modules/API/external/external_api.js

Fixes #9098
This PR fixes a misspelled command provided by the IFrame API

fixed misspelled api command

---

config.js
react/features/video-menu/components/native/RemoteVideoMenu.js
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.js

Add config.js option `remoteVideoMenu.disableGrantModerator` to be able to disable the '**Grant moderator**' button.
(in addition to `disableKick` and `disableRemoteMute`)
CLA already signed, see https://github.com/jitsi/lib-jitsi-meet/pull/1156

Add: remoteVideoMenu.disableGrantModerator option

---

react/features/base/media/components/web/Video.js

This can be reproduced on the prejoin screen by rapidly opening/closing the camera selection button.
Unhandled rejection triggers lots of unnecessary "global error handler" callbacks.

fix(Video.js): prevent DOMException: The play() request was interrupted by a new load request

---

react/features/video-layout/subscriber.js

Unpin the screenshare when the screensharing participant leaves. Switch to tile view if no other participant was pinned before screenshare was auto-pinned, pin the previously pinned participant otherwise.

fix(video-layout): Fix video-layout when a SS participant leaves.

---

react/features/base/lastn/middleware.js
react/features/large-video/actions.any.js
react/features/video-layout/actionTypes.js
react/features/video-layout/actions.js
react/features/video-layout/reducer.js
react/features/video-quality/middleware.js
react/features/video-quality/subscriber.js

The client now listens for changes to lastN, selectedEndpoints and maxReceiverVideoQuality in redux to trigger sending a bridge message in the new format. This fixes an issue where the stage view <-> tile view changes prompts two receiver constraints message to be sent, first with the maxHeight update and then with the selected endpoints update.

fix(quality-control): Send the new receiver constraints on state changes.

---

resources/prosody-plugins/mod_auth_jitsi-annonymous.lua
resources/prosody-plugins/mod_auth_token.lua
resources/prosody-plugins/mod_av_moderation.lua
resources/prosody-plugins/mod_jitsi_session.lua
resources/prosody-plugins/mod_muc_lobby_rooms.lua
resources/prosody-plugins/mod_muc_poltergeist.lua

Add 2 new modules:
jitsi_session: extracts URL parameters from BOSH or WS sessions and attaches
them to the session
auth_jitsi-annonymous: anonymous authentication with custom session
resumpotion for randomly generated usernames
Co-authored-by: Saúl Ibarra Corretgé <saghul@jitsi.org>

feat: jitsi_session: extracts URL parameters from BOSH or WS into session

---

config.js

`config.js` referenced `interface_config.js` for adding the local recording button to TOOLBAR_BUTTONS.
Follow this path and interface_config.js would tell you TOOLBAR_BUTTONS has been moved to config.js and points you back there. Thus, remove the reference in comment.

remove reference to interface_config.js (in comment)

---

package.json
react/features/base/util/react-focus-lock-wrapper.js

fix(FocusLock): Stop stealing focus when embedded

---

lang/main.json
react/features/settings/components/web/audio/AudioSettingsContent.js

Also fixes an issue where starting Chrome 90 air pods no longer have the "Default -" prefix and the default entry looks like a buggy duplicated one.

feat: more user friendly default device label

---

resources/prosody-plugins/token/util.lib.lua

This fixes an issue with mixed-case tokens being rejected. Use case is the JWT generated by jitsi-slack.
ref: https://github.com/jitsi/jitsi-meet/commit/572b99b208c2bd9f7419cdcad0c1bef093510bc6#diff-58c70604df5bb70fa08b6fff9[…]fff76ed613b6b6dd7424c33a520c0e5

lowercase to fix tokens with uppercase letters (e.g., slack JWTs)

---

conference.js
react/features/base/jwt/middleware.js
react/features/feedback/actions.js
react/features/feedback/functions.js
react/features/feedback/logger.js

I've changed the end of meeting promise resolves for room disconnect and send feedback from Promise.all to chained promises because I still need information from the room on sending the feedback metadata to JaaS endpoint, and with Promise.all, some of the information is purged on room disconnected before I get to store it for sending metadata.

Send feedback metadata to JaaS feedback endpoint

---

debian/jitsi-meet-prosody.postinst
doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
resources/prosody-plugins/mod_limits_exception.lua

In case limited those connection will be whitelisted and unlimited. Updates existing configurations to make sure prosody update will not break it by limiting too much.
Uses 28c16c93d79a version of the module: https://modules.prosody.im/mod_limits_exception.html
Will be available in prosody 0.12.

feat: Adds new module to unlimit jicofo and jvb connections.

---

react/features/participants-pane/components/MeetingParticipantList.js
react/features/participants-pane/functions.js

Hide invite button in new Participants Panel if invite feature is disabled in config.
This follows conversation with @damencho on https://community.jitsi.org/t/disabling-all-invite-functions/82035/33?u=shawn

Hide invite button in participant panel if disabled in config

---

resources/prosody-plugins/token/util.lib.lua

fix: tokens will have 'alg' header checked before assuming pubic key content at URL matches token algorithm

fix: prosody: token alg is checked before public key is used

---

react/features/base/participants/middleware.js

Previously gravatars (external resources) were preloaded even if
disableThirdPartyRequests was set to true in the config, as the
config may be empty at the time of preloading.
Closes: #5670

fix(participants) no preload gravatars if disableThirdPartyRequests

---

react/features/chat/middleware.js

Previously was always true even when closing
Deals with [https://github.com/jitsi/jitsi-meet/issues/9262](https://github.com/jitsi/jitsi-meet/issues/9262)
The close chat action that replaced the toggle always fired the chatUpdated with isOpen as true, meaning it was unusable to detect if chat was open or not.
Apologies if I've missed something here, I don't have the environment to run this and try it out.

fix: CLOSE_CHAT calls notifyChatUpdated with the isOpen flag set to false instead of true

---

css/modals/device-selection/_device-selection.scss
react/features/device-selection/components/DeviceSelection.js
react/features/device-selection/functions.js

Prevents creation of multiple video tracks when opening the settings dialog on iOS Safari.
The new dialog would look like:

fix(DeviceSelection): Remove video from mobile Safari

---

config.js
react/features/filmstrip/functions.web.js

JaaS customer wants remote videos to always be disabled for 1-1 calls.
We already have a config flag, disable1On1Mode, which was used for this exact behaviour, with the exception being that whenever the toolbox is shown on mouse movement / local participant is pinned, the remote video would also be shown regardless of having the above flag set to false.
In order to avoid adding another flag just to prevent this behaviour, I thought it would be better if users would simply make use of the existing disable1On1Mode and explicitly set it to null rather than false, in order to have the remote videos be always hidden

feat(api) allow always hiding remote videos for 1-1 calls

---

react/features/toolbox/components/web/Toolbox.js

fix(toolbox) fix for #9380

---

static/prejoin.html

(fix): Do not allow external css customization for static prejoin

---

android/sdk/src/main/java/org/jitsi/meet/sdk/LocaleDetector.java
react/features/base/i18n/languageDetector.native.js

LocaleDetector should consider the language script tag.
* For the language tag format of iOS, please refers the following link:
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html
* For the language tag format of Android, please refers the following link:
https://developer.android.com/reference/java/util/Locale#toLanguageTag()

fix(i18n): LocaleDetector should consider the language tag

---

config.js

Found via https://github.com/jitsi/jitsi-meet/issues/1016 .
I can also craft a PR that includes the commented out setting directly after etherpad_base with a comment about its usage. Just ping me and I'll adjust.
Signed the CLA already.

in config, mention useRoomAsSharedDocumentName

---

css/filmstrip/_tile_view.scss

The spans had a larger height than intended due to the default `display: inline`, causing scrollbars in Firefox. This, together with the css changes introduced in the pagination PRs, sorts out https://github.com/jitsi/jitsi-meet/issues/8586

fix(Filmstrip): Fix scrollbars around filmstrip

---

react/features/base/avatar/components/web/StatelessAvatar.js

- translate uses interfaceConfig object which does not exist in AOT context

fix(aot): Remove dependency to translate from StatelessAvatar.js

---

react/features/invite/components/add-people-dialog/web/InviteContactsForm.js
react/features/notifications/components/web/Notification.js

- fix issue on error notification on invite contacts

fix(support-url): Hide contact support button when SUPPORT_URL is empty

---

css/_variables.scss
css/filmstrip/_tile_view.scss
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/constants.js

feat(Filmstrip): Collapse filmstrip to avoid toolbar overlap on mobile

---

css/modals/virtual-background/_virtual-background.scss

fix(virtual-background): Refactor CSS to accommodate smaller screens

---

ios/Podfile.lock
package-lock.json
package.json

In version 1.15 the storage backend was rewritten, which hopefully allows us to
fix this crash on Android:
Caused by java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/org.jitsi.meet/databases/RKStorage
at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1160)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:159)
at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:146) …

fix(deps,rn) bump @react-native-async-storage/async-storage

---

react/features/prejoin/middleware.js

It is not 100% clear to me when it happens, but I think it could happen
in some race condition where a track is unmuted when it's being disposed
or something around those lines.
The fact is that any muted tracks are disposed by replaceLocalTrack(track.jitsiTrack, null) and they should not be used anymore.
Supposedly fixes a crash:
Failed to add local track to conference Track has been already disposed

fix(prejoin): disposed track was added to the conference

---

logging_config.js

It huurts performance on mobile. It can still be enabled by setting the level to
debug / trace.

fix(logging) reduce overly vebose logging

---

react/features/toolbox/components/web/Toolbox.js

`onMouseEnter` seems to trigger on mobile, marking the toolbar as "always hovered", therefore the toolbar never hides due to the condition in `react > features > toolbox > actions.web > hideToolbox`

fix(Toolbar): Fix toolbar not hiding on mobile

---

react/features/filmstrip/components/web/Filmstrip.js

Resolves the issue with the client telling JVB to send video for hidden rows. 
Receiving videos for hidden participants is unnecessary. Also when lastN is set to lower limit enabling the video for a hidden participant would mean that the video of a visible participant may need to be turned off.

fix(Filmstrip): Send only visible endpoints to jvb

---

conference.js
react/features/base/conference/actions.js
react/features/base/conference/functions.js
react/features/conference/functions.web.js
react/features/prejoin/components/PrejoinApp.js

Some options were missing on the mobile side, notably calltsts
enableDisplayNameInStats and enableEmailInStats. Now the same logic will be used
in web and mobile.

fix(conference) unify conference options

---

resources/prosody-plugins/mod_av_moderation_component.lua

When you enable and then disable av-moderation just the audio moderation is disabled and video moderation disabling is not signalled to moderated clients.

fix: Fix av moderation enable-disable sequence.

---

modules/API/external/external_api.js
react/features/mobile/watchos/middleware.js

[`typeof` will always return a string value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#description), no matter the input\*. Specifically, it never returns `undefined`, but instead the string value `"undefined"`.
This means the affected switch branch is unreachable in its current state. This PR fixes the comparison.
\* There is one [exception](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#errors) which doesn't apply here, because it would throw a `ReferenceError` and would still not be handled by this branch.

Fix typeof Comparison to undefined

---

react/features/filmstrip/components/native/Filmstrip.js
react/features/filmstrip/functions.native.js

When there are only 2 participants in a call, don't show the remote thumbnail,
unless the `disable1On1Mode` config option is set or the local participant pin
themselves.

feat(rn,filmstrip) add 1on1 mode

---

package-lock.json
package.json
react/features/av-moderation/actions.js
react/features/av-moderation/reducer.js

When participants panel is open and we approve a participant to unmute, the notification was not hidden as we were not correctly updating the state. We were expecting a participant object, but an id of the participant was used.

fix(av-moderation): Fixes approving and dismissing the notification.

---

resources/prosody-plugins/mod_limits_exception.lua

It is failing on prosody 0.11.4 with mod_limits_exception.lua:29: attempt to call method 'set_stanza_size_limit' (a nil value).

fix: Adds a null check in mod_limits_exceptions.

---

lang/main-es.json

Just a small update that adds the missing definition for main-es.json for "enterDisplayNameToJoin".

Added ES description for enterDisplayNameToJoin

---

react/features/base/flags/constants.js
react/features/toolbox/components/native/ScreenSharingAndroidButton.js

Added ANDROID_SCREENSHARING_ENABLED flag fix #9435

feat(toolbox) added android screen share flag

---

css/_base.scss
react/features/base/icons/components/Icon.js
react/features/participants-pane/components/web/ParticipantItem.js
react/features/participants-pane/components/web/styled.js
react/features/participants-pane/constants.js
react/features/participants-pane/functions.js

fix(moderation) display green mic icon only for active speaker

---

conference.js
react/features/base/conference/actions.js
react/features/base/participants/actionTypes.js
react/features/base/participants/actions.js
react/features/base/participants/reducer.js
react/features/filmstrip/actionTypes.js
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/components/web/ThumbnailWrapper.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/reducer.js
react/features/filmstrip/subscriber.web.js
react/features/video-quality/subscriber.js

The participants are ordered alphabetically and the endpoints with screenshares and dominant speakers (in that order) are bumped to the top of the list.

feat(Filmstrip): Reorder the visible participants in the filmstrip.

---

ios/sdk/src/AudioMode.m
react/features/mobile/audio-mode/components/styles.js

In WebRTC M92 the RTCAudioSession lock changed from a recursive one to a regular
mutex one, so make sure we don't attempt to lock it  while already holding the
lock.

fix(ios) fix deadlock when selecting audio device 

---

css/_participants-pane.scss
react/features/base/participants/functions.js
react/features/participants-pane/components/web/styled.js
react/features/participants-pane/constants.js

fix(moderation) highlight dominant speaker

---

patches/react-native+0.61.5-jitsi.2.patch

React Native links timers to the display, so they cannot run when the display is
not running. Builtin timers already take being in the background into account,
but not the proximity sensor.
Credits: https://github.com/react-native-webrtc/react-native-callkeep/issues/143
Fixes: https://github.com/jitsi/jitsi-meet/issues/9619

fix(ios) fix conference failing when proximity sensor is near

---

react/features/participants-pane/components/FooterContextMenu.js
react/features/participants-pane/components/web/styled.js

fix(moderation) fix ui styles for advanced moderation context menu

---

config.js

Fixes bug where, if notification whitelist is used with AV moderation, the prompts would not appear.

fix(config): add av-moderation notifications to config whitelist

---

conference.js
react/features/prejoin/middleware.js

On mobile Safari, when a user joins both audio and video muted, browser doesn't playout the remote audio because of a webkit bug. As a workaround, always add the audio track to peerconnection and then mute the track if needed.
This also fixes the issue where unmuting microphone doesn't work sometimes.

fix(tracks) Fix mobile safari issue with startMuted.

---

modules/API/API.js
modules/API/external/external_api.js

- EventEmmitter treats 'error' as a special case and throws error.

fix(external-api): Avoid naming event 'error'

---

react/features/base/responsive-ui/actions.js
react/features/filmstrip/components/web/Thumbnail.js
react/features/filmstrip/constants.js

Right now filmstrip displays self view in landscape mode.
With these changes the aspect ratio of the self view will be maintained
so on portrait mode the thumbnail will be displayed vertically.
Of course this makes sense only on mobile web.

feat(responsive-ui): Keep aspect ratio for filmstrip self view on mobile web

---

resources/prosody-plugins/mod_muc_max_occupants.lua

Dynamically limit the number of participants in a room

---

react/features/mobile/polyfills/browser.js

We need to re-override now() to avoid a recursion error. Also I missed the
default export.

fix(rn,polyfills) fix Performance polyfill

---

resources/prosody-plugins/mod_muc_census.lua

add handler for `/room-census` that returns JSON in this form:
```
{
"room_census": [
{
"room_name": "<muc name>",
"participants": <# participants>,
"created_time": <unix timestamp>,
},
...
]
}
```

new prosody module to report census of all rooms

---

react/features/device-selection/components/DeviceSelection.js
react/features/device-selection/functions.js

Creating a preview of the same audio/video track kills the tracks that is already being shared in the conference. Therefore, disable camera/mic selection in the settings dialog while the user is in the call. The devices are selectable from the prejoin screen settings dialog.

fix(settings) Disable mic/camera selection on mobile safari.

---

config.js
react/features/app/middlewares.any.js
react/features/app/reducers.any.js
react/features/base/config/configWhitelist.js
react/features/base/util/helpers.js
react/features/speaker-stats/actionTypes.js
react/features/speaker-stats/actions.js
react/features/speaker-stats/components/SpeakerStats.js
react/features/speaker-stats/constants.js
react/features/speaker-stats/functions.js
react/features/speaker-stats/middleware.js
react/features/speaker-stats/reducer.js

This is an implementation of #9742
Speaker stats participants are now reordered after each retrieval if the setting is configured, else it works the same as before.

Additional setting to order participants in speaker stats

---

modules/API/API.js
modules/API/external/external_api.js

Participant volume is now stored in redux. Includes a command to set participant volume via iframe api.

feat(external_api): Control participant volume

---

config.js
react/features/base/participants/functions.js
react/features/base/participants/reducer.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/components/web/ThumbnailWrapper.js
react/features/filmstrip/functions.any.js
react/features/filmstrip/middleware.web.js
react/features/participants-pane/components/web/MeetingParticipantContextMenu.js
react/features/participants-pane/components/web/MeetingParticipantItem.js

Match the order in the participants pane with that of the order in the filmstrip. Also move the participants with raised hand to the top of the list.
Move enableThumbnailReordering flag to testing section.

Thumbnail reordering and participant pane enhancements.

---

lang/main-de.json

fix(lang): update German translation

---

conference.js

This PR tries to get rid of `localAudio` and `localVideo` fields in conference.js

Use redux for local tracks instead of conference.js

---

react/features/base/config/configWhitelist.js

Whitelists it, so we can run tests by setting it to false.

feat: Whitelists enableUnifiedOnChrome.

---

react/features/base/connection/actionTypes.js
react/features/base/popover/components/Popover.web.js
react/features/base/responsive-ui/actionTypes.js
react/features/base/responsive-ui/actions.js
react/features/base/responsive-ui/reducer.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/functions.web.js
react/features/toolbox/actions.web.js
react/features/toolbox/components/web/Toolbox.js
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.js
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.js

- on ipads, long touch open dialog now opens the context menu to the left of the thumbnail as expected
- on ipads, now we close context menus on tap out
- fix case when participant context menu's height > tileview videos' height causing scroll on videos pane
- keep toolbox open while the overflow menu is shown
- keep remote participant video thumbnail in filmstrip visible even if toolbox is hidden, if context menu is opened
- fix case in which toolbox could be completely disabled

fix(context-menus) Fix participant context menus/toolbar overflow menu

---

config.js
connection.js
react/features/analytics/functions.js
react/features/base/connection/actions.native.js

Enables XMPP WebSocket on mobile.
It would be good to land https://github.com/jitsi/lib-jitsi-meet/pull/1303 before merging this PR.

feat: enable XMPP WebSocket on mobile

---

react/features/device-selection/components/DeviceSelection.js

This fixes an issue on mobile Safari when audio is lost after the user opens the device selection menu.

fix(device-selection) Do not create preview when mic selection is disabled

---

android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java

It has to be an application context.

android: fix initializing soloader from Activity context

---

react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.js

Jibri was hitting a problem where it reloads and in certain cases (remote user is screensharing) we hit this participant undefined, which stops reload and stops recording.
It is still not obvious why we try to render this on leaving the conference and for a participant that is not in the conference ... this re-render should not happen as this component should be removed from its parent when the participant is not existing.

fix: Fixes undefined error causing to stop reloads.

---

config.js
css/_subject.scss
react/features/base/config/configWhitelist.js
react/features/base/config/reducer.js
react/features/conference/components/constants.js
react/features/conference/components/functions.js
react/features/conference/components/web/ConferenceInfo.js
react/features/conference/components/web/ConferenceInfoContainer.js
react/features/conference/components/web/ParticipantsCount.js
react/features/conference/components/web/SubjectText.js
react/features/conference/components/web/index.js
react/features/local-recording/components/LocalRecordingLabel.web.js
react/features/recording/components/AbstractRecordingLabel.js

Now REC label behaves as before when always visible is disabled

feat(conference-info-header) Make conference info header configurable.

---

css/filmstrip/_vertical_filmstrip_overrides.scss
react/features/filmstrip/components/web/Thumbnail.js
react/features/filmstrip/constants.js

fix(responsive-ui): Shrink self view when in portrait mode on mobile web

---

conference.js
react/features/base/tracks/actions.js
react/features/base/tracks/middleware.js
react/features/video-menu/actions.any.js

Stop everyone's video now also stops screensharing for the moderator that did the action, not just video

fix(av-moderation) Fix stop everyone's video

---

react/features/mobile/audio-mode/components/AudioRoutePickerDialog.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/9996
On iOS 15 Bluetooth devices are reported twice for some reason, one with the
normal type "Bluetooth" but another type without a know (to me) type, and the
uid ends in "-reference".
While we send those unkwno devices to JS, we were not filtering them properly.
This patch skips them altogether.

fix(ios) fix black screen when using Bluetooth in iOS 15

---

react/features/base/tracks/actions.js

In iOS 15 we observe that not creating the audio track early may result in not
getting audio after unmuting for the first time.
Creating the audio track early means the first unmute doesn't need to add the
track to the conference, resulting in a much faster operation.
Note that creating the track early doesn't mean we will start unmuted, the track
will be muted.

fix(ios) create audio track early

---

react/features/base/tracks/middleware.js

When video moderation starts, stop screensharing and ignore if video was on when sharing started

fix(av-moderation) Stop screensharing and video on moderation start

---

config.js
react/features/app/middlewares.web.js
react/features/base/config/configWhitelist.js
react/features/dynamic-branding/functions.js
react/features/dynamic-branding/middleware.js
react/features/dynamic-branding/reducer.js
react/features/feedback/actions.js
react/features/large-video/components/LargeVideo.web.js
react/features/reactions/functions.any.js
react/features/virtual-background/components/UploadImageButton.js
react/features/virtual-background/components/VirtualBackgroundDialog.js
react/features/virtual-background/constants.js

If branding images are available will replace the default ones.
This pr does a few more things:
1. Moves the request for fetching dynamic branding to its own middleware. Now the request executes on APP_WILL_MOUNT so we can fetch the dynamic branding data before joining the conference.
2. Moves the `Add background` button to its own component. 
3. Adds a config option to disable the `Add background` image button.

feat(dynamic-branding): Add branding option for virtual backgrounds

---

resources/prosody-plugins/mod_polls.lua
resources/prosody-plugins/token/util.lib.lua

error   Traceback[c2s]: /usr/lib/prosody/util/format.lua:59: invalid option '%b' to 'format'
stack traceback:
mod_polls.lua:25: attempt to index local 'data' (a nil value)
stack traceback:

fix: Fixes errors in prosody about string formatting and nil values.

---

react/features/base/lastn/middleware.js
react/features/filmstrip/components/web/Thumbnail.js
react/features/video-quality/subscriber.js

The receiver video constraints that are actually sent to the bridge are logged in LJM and need not be logged in the application.

fix(logging) Remove logs that are very chatty.

---

patches/react-native+0.61.5-jitsi.2.patch

Bacckport
https://github.com/facebook/react-native/commit/748aa137472d6080427f74bb686c795b925c7d43
Fixes:
~~~
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x129708 __exceptionPreprocess
1  libobjc.A.dylib                0x287a8 objc_exception_throw
2  CoreFoundation                 0x19b9c8 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1a7a20 -[__NSPlaceholderDictionary initWithCapacity:].cold.1
4  CoreFoundation                 0x164c0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
5  CoreFoundation                 0x8de0 +[NSDictionary dictionaryWithObjects:forKeys:count:]
6  JitsiMeetSDK                   0x5704b4 -[RCTWebSocketModule webSocket:didFailWithError:] + 168 (RCTWebSocketModule.m:168)
7 …

fix(ios) fix crash on WebSocket errors

---

modules/API/API.js
modules/API/external/external_api.js
react/features/external-api/middleware.js

Signals that the bridge channel is open. It may take a few ms to get established
after the conference join, so applications might be interested in using it once
ready.

feat(external-api) add data-channel-open event

---

resources/prosody-plugins/mod_av_moderation_component.lua

There is no point of having messages like:
{
"room": "myroom@conference.mydomain.com",
"type": "av_moderation",
"mediaType": "audio",
"removed": true,
"approved": true
}

feat: Simplify av moderation participant approve/remove message.

---

react/features/base/conference/actions.js

Since iOS 15 we really need the audio stream to exist, so make sure we don't
destroy it even when "everyone starts muted" is set, we'll just mute it.
Fixes: https://github.com/jitsi/jitsi-meet/issues/10053

fix(rn,conference) fix unmute when "everyone starts muted" is set

---

ios/Podfile.lock
package-lock.json
package.json

chore(deps): update react-native-webrtc@1.92.2

---

react/features/invite/components/dial-in-summary/web/NumbersList.js

Some countries have multiple names listed in i18n-iso-countries, like US -> ['United States of America', 'USA'].

fix: Fixes displaying country names which has multiple names listed.

---

react/features/reactions/middleware.js

Reactions will be sent if webhookProxyUrl is set in config.js

fix(reactions) Remove vpaas check for reactions webhook

---

conference.js

This fixes an issue where Safari users cannot hear remote audio if they join audio/video muted. The browser throws the following error when the application tries to execute play on the audio element: 'NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.' This started happening in Safari 15.

fix(tracks) Always add audio track on Safari.

---

react/features/authentication/components/native/LoginDialog.js
react/features/invite/components/add-people-dialog/native/AddPeopleDialog.js
react/features/settings/components/native/SettingsView.js
react/features/welcome/components/WelcomePage.native.js

See:
https://reactnative.dev/blog/2021/09/01/preparing-your-app-for-iOS-15-and-android-12#quicktype-bar

fix(ios) disable QuickType bar on iOS15 when not using autocorrect

---

css/_polls.scss

On Firefox the create button is not visible.
Having a poll with long question/options breaks the UI.
Before:
After:

fix(Polls): Fix polls pane on Firefox

---

resources/prosody-plugins/mod_speakerstats_component.lua

Calculate total dominant speaker time if the speaker is dominant and has no previous speaker time. Now when a user joins and the current dominant speaker has not been dominant before the new joiner will get the correct speaker time of the dominant speaker.

fix(speaker-stats): calculate total dominant speaker time

---

modules/devices/mediaDeviceHelper.js

This is a follow up fix for PR #10237 which avoids the double prompts for Firefox users, but still shows the old device in the settings menu.
When a Firefox user selects a different device via the gUM() prompt when joining a call, these new devices get stored as the new user selected device to be shown consistently in the settings menu.

fix(conference): store user selected device from Firefox prompt

---

css/_connection-info.scss
css/_popover.scss
css/_popup_menu.scss
react/features/base/components/context-menu/ContextMenu.js
react/features/base/popover/components/Popover.web.js
react/features/connection-indicator/components/web/ConnectionIndicator.js
react/features/filmstrip/components/web/Thumbnail.js
react/features/participants-pane/components/web/MeetingParticipantContextMenu.js
react/features/video-layout/components/TileViewButton.js
react/features/video-menu/components/web/FlipLocalVideoButton.js
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.js
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.js
react/features/video-menu/components/web/VideoMenuButton.js

Clicking on an item when the popup drawer is displayed would keep it open.
Now clicking on any item should automatically close the drawer.
Popup was also refactored and no longer uses refs.

fix(Drawer): Close drawer on item click

---

conference.js

Steps to reproduce:
1. Start a meeting with 2 or 3 tabs open.
2. Start screen sharing.
3. Now very quickly: turn the screen sharing off and the camera on.
The app will end up in partially broken state where toggling camera will popup a notification "incompatible effect instance" each time.

Fix "incompatible effect instance" notification when trying to turn the camera on

---

modules/UI/videolayout/VideoContainer.js

This fixes an issue on Safari 15 (and newer versions) where black video is rendered sometimes whenever a new stream is attached to the large video container.

fix(large-video) Call play() whenever a new stream is attached to large-video

---

react/features/analytics/AnalyticsEvents.js
react/features/calendar-sync/components/AddMeetingUrlButton.web.js
react/features/calendar-sync/components/CalendarList.web.js
react/features/calendar-sync/components/CalendarListContent.native.js
react/features/calendar-sync/components/CalendarListContent.web.js
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.js
react/features/recent-list/components/AbstractRecentList.js
react/features/video-menu/components/AbstractMuteVideoButton.js

Fixed analytics where event names had duplicated words (eg. calendar.calendar.selected.selected)
Group reaction buttons analytics into one event
Removed unused code

fix(analytics) Fix analytics event names

---

react/.eslintrc.js

Fixes: Warning: React version not specified in eslint-plugin-react settings.

fix(lint) remove warning in eslint-plugin-react

---

react/features/speaker-stats/components/SpeakerStatsSearch.js

fix(speaker-stats): Fix stats search position on narrow screens

---

css/_atlaskit_overrides.scss
css/premeeting/_premeeting-screens.scss

fix(responsive-ui): Make modal full screen & fix prejoin layout on mobile landscape

---

react/features/participants-pane/components/native/MeetingParticipantItem.js
react/features/participants-pane/components/native/ParticipantItem.js
react/features/participants-pane/components/native/styles.js

Make name container limited width and add text-overflow ellipsis
Show raised hand status live in participants pane

fix(rn, participants-pane) Show raised hand indicator

---

android/app/src/main/java/org/jitsi/meet/MainActivity.java
android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastEvent.java
android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
ios/app/src/ViewController.m
ios/sdk/src/JitsiMeetViewDelegate.h
lang/main.json
react/features/base/color-scheme/defaultScheme.js
react/features/base/media/middleware.js
react/features/mobile/external-api/actionTypes.js
react/features/mobile/external-api/actions.js
react/features/mobile/external-api/middleware.js
react/features/overlay/components/native/LoadConfigOverlay.js
react/features/overlay/components/native/styles.js
react/features/welcome/components/BlankPage.native.js
react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/styles.js

This event is the event host applications need to listen to for knowing when to
dispose the SDK from now on.
Since the introduction of breakout rooms it's possible that we navigate from one
meeting to another, so there will be several conference join / terminations.
In addition, local track destruction is now moved to SET_ROOM when there is no
room, aka, we are going back to the welcome page or to the black page.

feat(rn,sdk) introduce a "ready to close" event

---

react/features/video-layout/components/TileViewButton.js

`setOverflowMenuVisible` doesn't exist on mobile.

fix(TileViewButton) fix on mobile

---

react/features/breakout-rooms/actionTypes.js
react/features/breakout-rooms/actions.js
react/features/breakout-rooms/components/web/RoomContextMenu.js
react/features/breakout-rooms/components/web/RoomList.js
react/features/breakout-rooms/reducer.js

Don't show more menu on the main room
Fix join room on mobile web
When moving to room reset breakout rooms state to avoid showing incorrect data before the response from prosody is received

fix(breakout-rooms) Improve breakout rooms

---

resources/prosody-plugins/mod_muc_breakout_rooms.lua

Breakout rooms are just reserved UUIDs, they need not exist as actual MUCs,
until a participant joins. Thus, take this into account when checking if a
participant is in a room.

fix(breakout-rooms) fix checking if a user is in a room

---

conference.js
config.js
interface_config.js
modules/UI/videolayout/LargeVideoManager.js
react/features/base/config/configWhitelist.js
react/features/base/config/reducer.js
react/features/base/participants/functions.js
react/features/base/participants/reducer.js
react/features/external-api/middleware.js
react/features/external-api/subscriber.js
react/features/filmstrip/components/web/Thumbnail.js
react/features/toolbox/components/web/ProfileButton.js

We need the client to be able to change 'Fellow Jitster' default remote display name and 'me' default local display name
1. Removed DEFAULT_LOCAL_DISPLAY_NAME and DEFAULT_REMOTE_DISPLAY_NAME from interfaceConfig.
2. Added defaultLocalDisplayName and defaultRemoteDisplayName to config.
3. Removed conference methods: getDisplayName, getLocalDisplayName and getParticipantDisplayName.

feat(config) added defaultRemoteDisplayName to config.js

---

react/features/participants-pane/components/web/MeetingParticipantContextMenu.js

Added a fix to enable stopping the video from the participant list and dismissing the meeting participant context menu (noticed that keeping the participant list open and sharing again would leave the context menu in a funny enabled state without the possibility of actually displaying the portal).

fix(share-video): stop video from the participant list

---

conference.js
lang/main.json
react/features/base/conference/actions.js
react/features/base/media/actionTypes.js
react/features/base/media/actions.js
react/features/base/media/functions.js
react/features/base/media/middleware.js
react/features/base/media/reducer.js
react/features/talk-while-muted/middleware.js
react/features/toolbox/components/AudioMuteButton.js
react/features/toolbox/functions.any.js
react/features/toolbox/functions.native.js
react/features/toolbox/functions.web.js

Jicofo sends a presence when the audio/video sender limit is reaced in the conference. The client can then proceed to disable the audio and video mute buttons when this occurs.

feat(conference) Implement audio/video mute disable when sender limit is reached.

---

config.js
react/features/base/config/configWhitelist.js
react/features/filmstrip/components/web/Thumbnail.js

Allows disabling the enlargement (`objectFit: cover`) of thumbnails using a config option called `disableTileEnlargement`.
Closes #10358

feat(tile-view): allow disabling thumbnail enlargement

---

react/features/conference/components/native/NavigationBar.js

`startTimestamp` is not a boolean, so make sure we return one.

fix(rn,navbar) fix invalid boolean check

---

css/modals/settings/_settings.scss
lang/main.json
react/features/av-moderation/middleware.js
react/features/base/conference/actionTypes.js
react/features/base/conference/actions.js
react/features/base/conference/reducer.js
react/features/base/devices/middleware.js
react/features/base/participants/middleware.js
react/features/base/settings/actionTypes.js
react/features/base/settings/actions.js
react/features/no-audio-signal/middleware.js
react/features/notifications/components/AbstractNotification.js
react/features/notifications/components/web/Notification.js
react/features/participants-pane/components/web/FooterContextMenu.js
react/features/reactions/constants.js
react/features/reactions/middleware.js
react/features/reactions/subscriber.js
react/features/recording/actions.any.js
react/features/settings/actions.js
react/features/settings/components/AbstractSettingsView.js
react/features/settings/components/web/ModeratorTab.js
react/features/settings/components/web/MoreTab.js
react/features/settings/components/web/SettingsDialog.js
react/features/settings/components/web/SoundsTab.js
react/features/settings/constants.js
react/features/settings/functions.js
react/features/talk-while-muted/middleware.js

add "Mute reaction sounds for everyone" option for moderator in settings
- used commands to send info to back-end and listen for incoming commands
pull out moderator settings from "More" settings tab and added "Moderator" tab in settings
add option in the footer menu for Participants pane to go to moderator settings
add option for moderator to disable all reaction sounds the reaction sounds notification
increase the time for first sound notification by 2 seconds so a user has more time to disable sounds
refactor "customActionNameKey" and "customActionHandler" to be an array instead of a single value
added unit tests fixes here https://github.com/jitsi/jitsi-meet-torture/pull/459

feat: (moderate-reaction-sounds) enable moderator to mute reaction sounds

---

modules/API/API.js
react/features/recording/actions.any.js
react/features/recording/functions.js

Added time to live param for the `recordingLinkAvailable` event.

feat(external-api): enhance recordingLinkAvailable to provide ttl info

---

resources/prosody-plugins/mod_jitsi_session.lua

rooms are created in prosody in their urlencoded form, eg täst
becomes t%c3%a4st@conference.jitsi.example.org
As local params = formdecode(query) contains an urldecode, we
need to reencode the room name so that the room can be found in
prosody.
Closes: #10525

fix(breakout,av-moderation): support non-ascii tenant and room names

---

react/features/participants-pane/components/web/ClearableInput.js

When the search input is focused the it is resized because of the border.

fix(participants-list): Avoid ui moving on input focus

---

react/features/participants-pane/components/web/MeetingParticipantContextMenu.js

Close the menu after sending a participant to a breakout room, that will detach
the context menu from the current participant and it will work properly when
they join back.

fix(breakout-rooms) fix non-functional context menu

---

react/features/base/conference/actions.js

Issue was that APP is not defined at this place on mobile,
thus this raising ReferenceError which caused the waitForOwner to break
Closes: #10211

fix(rn) join conference if started by moderator

---

package-lock.json
package.json

- fix(rn,remote-video-menu) fix import after refactor
- feat(breakout-rooms) add breakout-rooms
- fix(build) fix make dev with facial recognition worker
- fix(config) fix incorrect option name and whitelist it
- feat(video-quality): Always prioritize SS in tile view.
- fix(lang) update french translation
- fix(lang) update German translation
- fix(lang) update Arabic translation
- fix(lang) update Occitan translation
- fix(lang) update Russian translation
- fix(prejoin) Fix prejoin app
- fix(rn,welcome-page) don't create video track unnecessarily
- fix(Avatar): Display correctly any emoji/special character in a avatar initials
- fix(rn,sdk) remove deprecated color scheme prop
- fix(rn,sdk) drop deprecated option …

update ljm 1639041974

---

react/features/base/tracks/middleware.js

Don't just clear the storage for them, local tracks must be disposed, in order
for RN capturer to be freed for example.

fix(tracks) fix disposing of local tracks

---

react/features/speaker-stats/actionTypes.js
react/features/speaker-stats/actions.any.js
react/features/speaker-stats/components/web/SpeakerStats.js
react/features/speaker-stats/components/web/SpeakerStatsSearch.js
react/features/speaker-stats/reducer.js

Prevent closing speaker stats from dismissing when Enter key is pressed in the text field and reset search criteria when speaker stats component is unmounted.

fix(speaker-stats): prevent search from closing when enter pressed and from keeping previous state

---

lang/main-nl.json

Adds Dutch translations for the performance settings strings. I don't speak Dutch, but the customer who provided these does so I suppose they are correct!

Add dutch translations for performance settings strings

---

config.js

The default values stated in the commented lines in config file are both true for hideConferenceSubject and hideConferenceTimer. Actually they are false.

Fix default values for hideConferenceSubject/-Timer

---

react/features/notifications/actions.js

Ref: https://github.com/jitsi/jitsi-meet/issues/10610
Wrong arrays were being populated in `showParticipant*Notification` functions, resulting in join notifications never getting triggered.

fix: participant join notifications

---

css/filmstrip/_tile_view.scss
react/features/filmstrip/components/web/Thumbnail.js

clean-up overriden css for tileview video tags
Before:
After

fix(tile-view) fix screensharing size in self view

---

react/features/breakout-rooms/actions.js
react/features/external-api/middleware.js

Moving to breakout room and back in main room do not fire videoConferenceLeft events.
And the videoConferenceJoined was reporting wrong conference name on join.

fix: Fixes emitting conference left event in iframeAPI.

---

config.js
react/features/base/config/constants.js
react/features/base/config/functions.any.js
react/features/base/config/index.js
react/features/base/tracks/functions.js
react/features/video-quality/subscriber.js

Adjust the `setReceiverConstraints` method to ensure formats are not being mixed and the new sources format is only used when the `sourceNameSignaling` feature flag is enabled. 
Related PR: https://github.com/jitsi/lib-jitsi-meet/pull/1813

feat: Update video receiver constraints to use source names

---

config.js
modules/API/API.js
modules/API/external/external_api.js
react/features/base/conference/actionTypes.js
react/features/base/conference/actions.js
react/features/base/conference/functions.js
react/features/base/conference/middleware.any.js
react/features/base/conference/reducer.js
react/features/base/config/configWhitelist.js

Extended the external API to support setting a local subject from all participants (regardless of the role).

feat(external-api): add local subject command

---

react/features/speaker-stats/components/AbstractSpeakerStatsList.js
react/features/speaker-stats/constants.js

Fix the responsiveness of facial expressions in speaker stats. Show only 4 expressions when client width is less than 750px.
Before
Now

fix(speaker-stats): responsiveness of facial expressions

---

css/_base.scss
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/web/Thumbnail.js
react/features/filmstrip/constants.js
react/features/filmstrip/functions.web.js

disableTileEnlargement config now uses old behavior (small tiles, not just small video in the tiles)
Update Firefox scrollbar style to match WebKit
Show more rows when height allows it instead of stretching a fixed number of rows, but make sure we always try to fill the whole viewport
Added constraints for how narrow portrait tiles can be and how wide landscape tiles can be
The video should cover the whole tile in tile view unless disableTileEnlargement is set or video is portrait
Added min height in px for tiles

fix(thumbnail) Update tile resizing constraints

---

doc/debian/jitsi-meet-turn/turnserver.conf

fix: Add ipv6 networks to coturn's deny list.

---

lang/main-fr.json

CLA already signed in this [PR](https://github.com/jitsi/jitsi-meet/pull/8728#issuecomment-790589534)
this PR does not add or change any message, it only set an uniform format:
- remove trailing whitespaces
- set the ':' separating key and value to a unique form (no space between key and ':' and one space between ':' and value)
- set key order to be the same between International english and localized version
- set an identical indentation for the the file.
Note that I have left the original indentation (2 characters) as it is, while the indent for the international english is 4.
Maybe it was intentional as french is a bit more verbose than english ? or maybe it was for 'historical reasons' ? I don't know so I left it. But I could change to 4 very easily. It would make for a huge diff …

fix(lang) make fr language file format consistent

---

react/features/participants-pane/components/web/MeetingParticipants.js

Fix for search value to no be cleared after participants pane is closed

fix(participants-pane) search value to not be cleared when closing pane

---

react/features/toolbox/components/native/ScreenSharingButton.js
react/features/toolbox/components/web/ShareDesktopButton.js
react/features/toolbox/components/web/Toolbox.js
react/features/toolbox/functions.native.js
react/features/toolbox/functions.web.js

Also, ignore the toggle screenshare shortcut when the video sender limit is reached.

fix(toolbox) Disable screensharing button on mobile for video sender limit

---

react/features/base/media/components/native/Audio.js

Upstream now skips the callback, so we need to provide one.

fix(rn,audio) fix playback after API change

---

react/features/toolbox/constants.js

allows chat button to be displayed when there should be enough space for it

fix(thresholds) adjust thresholds for smaller width integrations

---

react/features/video-menu/components/web/LocalVideoMenuTriggerButton.js

**Issue being addressed:**
When `disableLocalVideoFlip=true` three-dot menu in thumbnail is completely hidden even though the "Hide self view" item is still relevant.
Related community post: https://community.jitsi.org/t/couple-of-issues-with-hide-self-view/108960/12?u=shawn

fix: still show menu to toggle self view if disableLocalVideoFlip

---

css/_audio-preview.scss
react/features/base/config/functions.web.js
react/features/settings/components/web/audio/AudioSettingsContent.js
react/features/settings/components/web/audio/AudioSettingsPopup.js
react/features/settings/components/web/audio/MicrophoneEntry.js

On a custom deployment of Jitsi Meet with audio levels disabled, audio level meters are displayed in the settings popup but they do not light up. This confuses the users when they try to test the microphones and don't see any response.
This PR updates the MicrophoneEntry component to check whether audio levels are enabled before listening to changes and displaying the meter of each microphone device.
**config.disableAudioLevels=false** :
**config.disableAudioLevels=true** :

fix(MicrophoneEntry): Hide meter when audio levels are disabled

---

react/features/overlay/components/AbstractPageReloadOverlay.js
react/features/overlay/overlays.web.js

When there is no reload reason defined, try to extract something from the errors that caused it.

feat: Updates reload reason.

---

Makefile

Before:
~~~
$ make deploy-css
./node_modules/.bin/sass css/main.scss css/all.bundle.css && \
./node_modules/.bin/cleancss --skip-rebase css/all.bundle.css > css/all.css ; \
rm css/all.bundle.css
Error: Can't find stylesheet to import.
╷
78 │ @import 'filmstrip/vertical_filmstrip_overrides2';
│         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
css/main.scss 78:9  root stylesheet
$
(exitcode is 0)
~~~
After:
~~~
$ make deploy-css
./node_modules/.bin/sass css/main.scss css/all.bundle.css && \
./node_modules/.bin/cleancss --skip-rebase css/all.bundle.css > css/all.css && \
rm css/all.bundle.css
Error: Can't find stylesheet to import.
╷
78 │ @import 'filmstrip/vertical_filmstrip_overrides2';
│         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
css/main.scss 78:9  root stylesheet
make: *** …

fix(build) exit with error if any CSS step fails

---

react/features/base/label/components/ExpandedLabel.native.js
react/features/base/label/components/Label.native.js
react/features/base/label/components/styles.js
react/features/conference/components/native/AlwaysOnLabels.js
react/features/conference/components/native/Conference.js
react/features/conference/components/native/ExpandedLabelPopup.js
react/features/conference/components/native/Labels.js
react/features/conference/components/native/RaisedHandsCountExpandedLabel.js
react/features/conference/components/native/RaisedHandsCountLabel.js
react/features/conference/components/native/TitleBar.js
react/features/conference/components/native/constants.js
react/features/conference/components/native/styles.js
react/features/mobile/audio-mode/components/AudioDeviceToggleButton.js
react/features/recording/components/native/RecordingExpandedLabel.js
react/features/recording/components/native/RecordingLabel.js
react/features/recording/components/native/styles.js

Only display the Picture-in-Picture button when the feature is available
Moved conference timer before title
Created new always-on container for labels
Moved recording labels to always-on
Updated expanded label to support new always-on labels
Added raised hands counter label
Added speaker - earpiece toggle button
Lifted state up

feat(title-bar, rn) Updated title bar native

---

react/features/participants-pane/functions.js

- fixes:  https://github.com/jitsi/jitsi-meet/issues/10609

fix(raised-hand) Preserve raised hand order for active speaker

---

react/features/base/participants/reducer.js

Joining a room while hand is raised causes the local raised hand total to be wrong.
This is because when the local participant id changes, the old id is not cleared from the raisedHandQueue.
(CLA is signed.)

fix(breakout-rooms) joining room with hand raised bug

---

react/features/video-menu/components/web/VolumeSlider.js

Volume slider currently takes the width of the popup menu on remove video. This is a problem in the case of non-moderator users when chat feature is disabled -- there are no other menu items to push out the width and slider ends up unusably small.
See: https://community.jitsi.org/t/squashed-volume-slider-for-non-moderator-if-chat-disabled/110275?u=shawn
This PR addresses this by ensuring volume slider has a minimum width.

fix: volume slider min width so not squashed when lonely

---

lang/main-ja.json

"Log住所in" is "Log-MailingAddress-in" in Japanese. So fix it.

Fix Japanese translations

---

lang/main-ja.json

There is a discrepancy between the meaning of English and the meaning of Japanese about "lookGood".
"lookGood" represents a good condition.
However, "マイクが正常に動作していないようです" represents a bad condition in Japanese.
In Japanese, "マイクは正常に動作しています" represents a good condition.

lang: fix(lang) update Japanese translation

---

react/features/base/conference/actions.js

Dispatching the authStatusChanged action in base/conference (in addition to conference.js for web clients).

fix(rn, conference): dispatch authStatusChanged in base/conference

---

react/features/base/i18n/i18next.js

[0] introduced sorted language keys, but we had the assumption that the
first one meant to indicate the default language.
Break that assumption and be explicit about English being the default
language.
[0]: https://github.com/jitsi/jitsi-meet/commit/7fe319d965e4514c96a8eac2b7f520e974b47515

fix(lang) fix default language selection

---

conference.js
react/features/base/participants/actionTypes.js
react/features/base/participants/actions.js
react/features/base/participants/constants.js
react/features/base/participants/middleware.js

Add LOCAL_PARTICIPANT_AUDIO_LEVEL_CHANGED action and lower hand when the audio level is higher than a given value instead of lowering when the local participant becomes the dominant speaker.

fix(raised-hand): lower raised hand by local audio level changes when participant is dominant

---

react/features/base/config/functions.any.js
react/features/display-name/components/web/DominantSpeakerName.js
react/features/filmstrip/components/web/ThumbnailBottomIndicators.js

Hid the dominant speaker name when using `hideDisplayName` config.

fix(config): use hide display name flag for dominant speaker

---

react/features/mobile/navigation/screenOptions.js

I checked other popular apps like Twitter and their drawers take more screen state. With my font size not even "Help center" was visible.

fix(rn,settings-drawer) allow for more width

---

react/features/mobile/navigation/middleware.js

The CONFERENCE_WILL_LEAVE reducer in base/conference wipes the state so
we cannot rely on the old room value.
We may want to revisit this in the future.

fix(rn,navigation) fix navigating back to the welcome page

---

conference.js
config.js

This is no longer supported as per the w3c spec for getDisplayMedia.

fix(media) Deprecate startScreenSharing config option for web browsers.

---

react/features/app/getRouteToRender.web.js

When welcome page disabled, random room name is appended to URL -- this is problematic if a url param was provided, in which cases the appended value simply becomes part of the param and the cycle repeats infinitely.
Ref: https://community.jitsi.org/t/infinite-redirects-when-enablewelcomepage-false-and-landing-page-has-url-param/110547
Note: also dropped the `endsWith('/')` check because `URL.pathname` already normalised to `/` when path not provided.

fix: broken redirect for url with params when welcome page disable

---

package-lock.json
package.json

This has 2 benefits:
a) it no longer needs to be built at install time, thus making builds faster
before:
real	0m46.865s
user	1m3.938s
sys	0m22.478s
after:
real	0m27.828s
user	0m25.582s
sys	0m21.699s
b) integrity errors go away since they are not computed over a locally
generated tarball

feat(build) use lib-jitsi-meet release tarballs

---

react/features/participants-pane/components/web/FooterContextMenu.js
react/features/settings/functions.js

**Issue:**
When moderator tab is hidden (remove from `interfaceConfig.SETTINGS_SECTIONS`), the "... more moderation controls" option still opens the Settings modal and lands on Device tab. This can be confusing to users, and the option serves no purpose.
**Fix:**
We attempt to address this by removing the option from the menu when "moderator" is not listed in `interfaceConfig.SETTINGS_SECTIONS`.

fix: hide "more moderation controls" option if moderator settings tab disabled

---

config.js
react/features/base/config/configWhitelist.js
react/features/conference/components/web/Conference.js
react/features/toolbox/components/web/Toolbox.js

This introduces a new `hideDominantSpeakerBadge` config var which hides the dominant speaker badge that floats above the toolbar. This offers users an option to not have the badge cover screenshare which still retaining names in the video thumbnails.
Ref: https://community.jitsi.org/t/screen-sharing-display-name/110658

feat: config to hide dominant speaker badge

---

react/features/base/util/isInsecureRoomName.js

fix(util) never mark UUID room names as insecure

---

debian/jitsi-meet-prosody.postinst

Fixes an issue where on clean install we see:
WARNING: [25] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#622: [MucClient id=shard hostname=localhost] error connecting
org.jivesoftware.smack.SmackException$SmackWrappedException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

fix: Restarts jvb after prosody on initial install.

---

react/features/filmstrip/components/web/Thumbnail.js
react/features/video-layout/functions.js

feat(tileView): Display 3 participants in 1 row

---

conference.js

When Jibri counts the participants in the meeting other Jibris should
not be accounted for.

fix(app) fix member count to filter out hidden participants

---

resources/load-test/package-lock.json

Fixes
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

fix(load-test) update package-lock.json to npm8

---

react/features/breakout-rooms/actions.js
react/features/breakout-rooms/functions.js

This change is needed for the external api, as the current UI doesn't allow removing a room that has participants in it.

fix(breakout-rooms) close room before removing it

---

react/features/participants-pane/components/web/FooterContextMenu.js
react/features/participants-pane/components/web/MeetingParticipantItem.js
react/features/participants-pane/components/web/MeetingParticipantItems.js
react/features/participants-pane/components/web/MeetingParticipants.js
react/features/video-menu/components/web/ParticipantContextMenu.js

When the local participant is a moderator and is in a breakout room hide the following:
- advanced moderation
- Ask to Unmute
- Grant Moderator

fix(breakout-rooms) Hide non-working options inside breakout rooms

---

react/features/base/dialog/components/native/styles.js
react/features/base/ui/Tokens.js
react/features/chat/components/native/ChatInputBar.js
react/features/chat/components/native/styles.js
react/features/invite/components/add-people-dialog/native/styles.js
react/features/invite/components/dial-in-summary/native/styles.js
react/features/lobby/components/native/LobbyModeSwitch.js
react/features/lobby/components/native/styles.js
react/features/mobile/navigation/components/chat/components/ChatAndPollsNavigationContainer.js
react/features/mobile/navigation/screenOptions.js
react/features/polls/components/native/PollAnswer.js
react/features/polls/components/native/PollCreate.js
react/features/polls/components/native/PollResults.js
react/features/polls/components/native/PollsList.js
react/features/polls/components/native/styles.js
react/features/recording/components/LiveStream/native/StreamKeyForm.js
react/features/recording/components/LiveStream/native/styles.js
react/features/recording/components/Recording/StartRecordingDialogContent.js
react/features/recording/components/Recording/styles.native.js
react/features/recording/components/Recording/styles.web.js
react/features/security/components/security-dialog/native/SecurityDialog.js
react/features/security/components/security-dialog/native/styles.js
react/features/speaker-stats/components/native/styles.js

Polls recording
https://user-images.githubusercontent.com/26413496/154498154-ec86b44f-6c57-4a9b-9c6b-bd6cce3d396f.mp4

Mobile UI polish

---

resources/prosody-plugins/token/util.lib.lua

fix for issue [10970](https://github.com/jitsi/jitsi-meet/issues/10970)
jwt token verification will return proper reponse when jwt token passed in auth_token is invalid - no dot separator.

fix: issue #10970

---

react/features/speaker-stats/components/web/SpeakerStats.js
react/features/speaker-stats/components/web/SpeakerStatsList.js

Fix separator line when the list of participants overflows and remove footer space
Before
After

fix(speaker-stats): labels spearator line fixed and remove footer space

---

modules/UI/videolayout/LargeVideoManager.js
react/features/base/lib-jitsi-meet/index.js
react/features/base/tracks/actions.js
react/features/connection-indicator/components/web/ConnectionIndicator.js
react/features/connection-indicator/components/web/ConnectionIndicatorContent.js
react/features/connection-indicator/components/web/ConnectionIndicatorIcon.js
react/features/connection-indicator/functions.js
react/features/filmstrip/functions.web.js

Start listening to the `TRACK_STREAMING_STATUS_CHANGED` event introduced in https://github.com/jitsi/lib-jitsi-meet/pull/1855. This implementation still assumes only one video track per participant. 
High level objectives:
- Handle the `init` and `dispose` logic for `TrackStreamingStatus` when a connection icon is rendered. This is an optimization to help the performance in large conferences.
- Replace the participant connection status logic with track streaming status throughout the code base. Ensure backwards compatibility when the feature flag is disabled and feature parity when enabled.
- Add `streamingStatus` property to the Track data model in the redux store and add code to update this new property.

feat(multi-stream-support) Support track streaming status

---

react/features/filmstrip/components/native/Filmstrip.js

This applies to android only, where we don't separate the local
thumbnail.
In portrait mode the local thumbnail needs to be on the right, aka the
last one. In landscape mode it needs to be on top, aka the first.

fix(rn,filmstrip) fix local participant location

---

react/features/display-name/components/native/DisplayNameLabel.js
react/features/display-name/components/native/styles.js
react/features/filmstrip/components/native/Thumbnail.js
react/features/filmstrip/components/native/styles.js

fix(thumbnails, rn) Hide empty indicators container on native

---

config.js
css/_subject.scss
css/_videolayout_default.scss
css/filmstrip/_vertical_filmstrip.scss
css/premeeting/_premeeting-screens.scss
modules/UI/videolayout/LargeVideoManager.js
react/features/base/config/configWhitelist.js
react/features/filmstrip/actionTypes.js
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/components/web/Thumbnail.js
react/features/filmstrip/components/web/ThumbnailWrapper.js
react/features/filmstrip/components/web/styles.js
react/features/filmstrip/constants.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/reducer.js
react/features/filmstrip/subscriber.web.js
react/features/large-video/components/LargeVideo.web.js
react/features/video-layout/functions.js
react/features/video-layout/middleware.web.js

Make conference info and toolbar appear on top of the filmstrip
After a breakpoint, filmstrip pushes over the stage view instead of appearing on top
On user resize make tiles wider; after a breakpoint show grid view in the filmstrip
On filmstrip visibility toggle animate stage view resize

feat(filmstrip) Make filmstrip user resizable

---

react/features/video-menu/components/web/ParticipantContextMenu.js

There's a bug if you set someone's volume to 0, next time you open the video menu the slider is set to 1. That's because 0 is considered a falsy value and will default to 1.

Fix initial volume value if value is 0

---

ios/scripts/release-sdk.sh

Currently the iOS SDK isn't compiled for Apple Silicon on the simulator, which results in various Rosetta related glitches when running an app on M1 based machines. This PR removes `VALID_ARCHS` on the SDK build script as the standard architectures for both the Simulator and devices are now included in `WebRTC.xcframework` (which I assume was the limiting factor before).
I followed the build [instructions](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#building-it-yourself) (removing the `VALID_ARCHS` matching this PR) to make a build with Xcode 13.2 and tested the output xcframework on an M1 in a simple project everything worked great. The contents of the `Info.plist` is below to show what is built without `VALID_ARCHS`.
Let me know if you have any questions or would …

Add support to the iOS SDK for the Simulator on M1

---

config.js
react/features/base/config/configWhitelist.js
react/features/base/config/reducer.js
react/features/breakout-rooms/functions.js
react/features/participants-pane/components/breakout-rooms/components/native/BreakoutRoomContextMenu.js
react/features/participants-pane/components/breakout-rooms/components/web/RoomList.js
react/features/participants-pane/components/native/ParticipantsPane.js
react/features/participants-pane/components/web/ParticipantsPane.js

Add `hideJoinRoomButton` and move `hideAddRoomButton` under the common key (backwards compatibility included).

feat(external-api): expose config for breakout rooms

---

react/features/filmstrip/actions.web.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/constants.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/subscriber.web.js

Re-calculate tile sizes after config loaded
Make local tile always respect the ratio in interface_config
Merge calculate size for vertical view functions into one function

fix(filmstrip) Fix resizable filmstrip

---

react/features/video-quality/subscriber.js

...when new participant joins.
Repro steps:
1. With p2p disabled and source name signaling enabled.
2. Start a call with 2 tabs.
3. Reload the 2nd tab.
4. The receiver constraints should be updated when the 2nd
user rejoins. They were not updated, because
getTrackSourceNameByMediaTypeAndParticipant doesn't have
the track yet at the time when visibleRemoteParticipants
are updated. This is fixed by also checking on
the remote tracks state.

fix(receiver constraints): source name not found

---

package-lock.json

If you open participants pane and then click on the overflow button, the inline dialog is displayed at the wrong position.
If we resolve `@popperjs/core` to `2.6.0` `2.11.2`, this bug will be fixed.

fix(popper): resolve @atlaskit/popper to an unbuggy version

---

css/premeeting/_premeeting-screens.scss

Please see https://github.com/jitsi/jitsi-meet/issues/11027
@saghul I did some tests trying various responsive scenarios and propose to follow 16:9 aspect ratio values, so if there is a breakpoint on 420px then the width breakpoint should be on 720px (HD width).
But that means it requires changing the size of the join panel because the margin is too big if the width is 721px:
To avoid that I changed the default panel margin to give more space for video:
Full size:
If you have any other suggestions please let me know!

fix(premeeting): Improve pre-meeting responsiveness for screens less 1000px

---

react/features/authentication/components/native/LoginDialog.js
react/features/authentication/components/native/WaitForOwnerDialog.js
react/features/authentication/middleware.native.js

1) Fix not being able to show multiple dialogs at once in iOS
2) Fix cancelling the login dialog when XMPP auth is enabled without
guest support

fix(rn,dialogs,auth) fix not showing authentication dialogs

---

modules/UI/videolayout/LargeVideoManager.js
react/features/display-name/components/web/DominantSpeakerName.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/functions.web.js
react/features/large-video/components/LargeVideo.web.js
react/features/toolbox/components/web/Toolbox.js

Move label to LargeVideo so that's it's centered in the view instead of the whole screen
Move vertical filmstrip max-width calculation to a function and use it to set the large video width

fix(dominant-label) Fix dominant speaker stage view label

---

conference.js

Make the behavior consistent with enabling camera when the user is audio-only mode. Also fixes an issue where the screenshare preview doesn't appear if it is enabled while the user is in audio-only mode.
Follow-up PR for https://github.com/jitsi/jitsi-meet/pull/11033

fix(conference) Disable audio-only mode when user switches to screenshare

---

config.js
modules/API/external/external_api.js
react/features/base/config/configWhitelist.js
react/features/base/util/uri.js

- jwt from API overwrites any jwt sent as queryparam
- defaultLanguage from configOverwrite converts to `lang` query param

fix(language) Add lang API option

---

resources/install-letsencrypt-cert.sh

This introduces a variable which holds the path to the detected `certbot`
binary and reuses that to fix the inconsistency which arose from looking for
`certbot` but then later using the hardcoded path `/usr/bin/certbot` in
invocations. This broke snap installations of certbot.
See issue #11072 for my defect report.

Addressing issue #11072 (hardcoded certbot)

---

README.md

Fixed the broken link to the handbook for the self-hosting installation guide.

Fix broken link in README.md to the handbook

---

css/premeeting/_prejoin-dialog.scss
react/features/prejoin/components/dialogs/CallingDialog.js

Convert Sass to JSS in `CallingDialog` component.

refactor(prejoin) use jss instead of sass in CallingDialog

---

config.js

The example notification array in config.js misses notify.hostAskedUnmute. When uncommenting the array, the user expects all notifications to work. I added the missing notification.

Add missing notify.hostAskedUnmute

---

react/features/filmstrip/actions.web.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/functions.any.js
react/features/filmstrip/functions.native.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/subscriber.web.js

When all the participants are displayed without scroll the reordering of the thumbnails is stopped.

Don't reorder small meetings

---

resources/prosody-plugins/muc_owner_allow_kick-0.12.patch

provides a patch to re-enable support for kicking muc owners in the latest prosody release 0.12

feature: patch for muc_owner_allow_kick in prosody 0.12

---

react/features/base/premeeting/components/web/ConnectionStatus.js

Hooks must be called before any early returns.

fix(premeeting): call hooks before any conditional block in ConnectionStatus

---

ios/Podfile.lock
package-lock.json
package.json

Reverts jitsi/jitsi-meet#11091
We are waiting for Apple to respond to a submission error about private API usage. All listed private APIs are actually WebRTC APIs we’ve been using for years… oh well.

Revert "deps(rn) react-native-webrtc@1.98.0"

---

react/features/base/premeeting/components/web/ConnectionStatus.js

`720` value is not defined in the `theme.breakpoints`.

fix(premeeting): fix undefined breakpoint in media query

---

react/features/video-quality/subscriber.js

Only calculate for Large Video on the web (otherwise native breaks)
Take preferred max into calculations

fix(video-constraints) Fix calculations

---

react/features/unsupported-browser/components/DefaultUnsupportedDesktopBrowser.js

Reason:
- This is easier overridable than then embedded react page
- Consistenty between IE and other unsupported browsers

feat: Use same recommendedBrowsers page for IE and browsers marked in interface_config.js

---

ios/fastlane/Fastfile

Avoids conflicts when a build is rejected by Apple since Fastlane cannot
detect it.

fix(ios,build) use epoch seconds for build number

---

react/features/recording/actions.any.js
react/features/recording/components/Recording/AbstractHighlightButton.js
react/features/recording/constants.js

Fix incorrect handling of error case when highlighting moments
Allow users to start recording when trying to highlight while recording not started

fix(highlight) display option to start recording

---

resources/prosody-plugins/mod_muc_password_whitelist.lua

Publishes the mod_muc_password_whitelist prosody module.
This module allows certain listed domains to bypass the muc password setting.  Intended for components like jibri

task: mod_muc_password_whitelist prosody module

---

react/features/display-name/components/web/DominantSpeakerName.js

The Dominant speaker name badge was overlaping the shared video
controls  (audio level, play/pause, etc).

fix(shared-video): Can't click controls

---

css/premeeting/_prejoin.scss

`'prejoin-preview-dropdown-btn'` and `'prejoin-preview-dropdown-icon'` classes are already converted to JSS in `DropdownButton` component.

refactor(premeeting): remove redundant styles from prejoin.scss

---

react/features/chat/components/web/Chat.js

Fixes: on iOS web the chat input would move from the bottom when the keyboard was open

fix(chat) Fix iOS web chat

---

doc/debian/jitsi-meet/jitsi-meet.example

Incorporate https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/
into the example nginx config

conf(nginx) add keepalive via upstream groups

---

css/404.scss

Changed the font-size and color of the h2 element of the 404 error page so that it can look more vibrant and stand out.
Old look:
New look:

Increase the visibility of 404 error message

---

css/_base.scss
css/_chat.scss
css/_mixins.scss
css/_participants-pane.scss
css/_subject.scss
css/_toolbars.scss
css/_videolayout_default.scss
css/filmstrip/_tile_view.scss
css/premeeting/_premeeting-screens.scss
react/features/conference/components/web/Conference.js
react/features/notifications/components/web/NotificationsContainer.js
react/features/participants-pane/components/web/ParticipantsPane.js
react/features/participants-pane/functions.js

Move `Chat` component one level up, to be placed next to the `ParticipantsPane` and `div#videoconference_page` in `Conference` component.

refactor: move chat component outside of videoconference_page

---

react/features/lobby/actions.native.js

We need to make sure to hide it explicitly so the Redux state is in sync
with reality.

fix(rn,lobby) fix lobby not showing up on subsequent tries

---

react/features/base/components/context-menu/ContextMenu.js

Fixes issue where the menu would disappear on dominant speaker change

fix(context-menu) Don't overwrite hidden prop

---

react/features/filmstrip/middleware.web.js
react/features/filmstrip/subscriber.web.js

Recalculate after new dimensions are in the store. This is needed because the dimensions are now taken from the store and not as params to the setDimensions function
Fixes issue where on participant pane toggle the tiles would not recalculate correctly

fix(thumbnails) Fix recalculate tile dimensions on client resize

---

.github/workflows/ci.yml

Print the git diff output in the step which fails.

fix(ci) make the "dirty git tree" CI failure clearer

---

react/features/large-video/actions.any.js

Fixes an issue where a non-screenshare participants cannot be pinned on stage with filmstrip on stage feature disabled.

fix(large-video) Show the pinned participant on large-video when stage filmstrip is disabled.

---

react/features/recording/components/Recording/styles.native.js
react/features/recording/functions.js

Use stacked buttons
Before
After
Fix get sessionId on mobile

Fixes for highlights mobile

---

react/features/polls/components/web/PollCreate.js

On enter, input value doesn't get duplicated and added to the next input.
We only add a new option input, if we are on the last option input.
Fix for https://github.com/jitsi/brave-tracker/issues/78

feat(polls/web) fixed issue with duplicating value to next input on keypress
