jitsi/jitsi-meet

package-lock.json
package.json

deps: lib-jitsi-meet support rtcstats p2p meta

---

android/gradle.properties

fix(android) increase gradle JVM heap size

---

react/features/base/lib-jitsi-meet/functions.native.js

fix(rn,config) increase config load timeout to 10 seconds

---

android/app/build.gradle

fix(android) excludes hermes related libs from the apk

---

react/features/connection-indicator/components/web/ConnectionIndicator.js

fix: Prevents an error makes the code more defensive.

---

android/build.gradle
android/scripts/release-sdk.sh

Fix android sdk building error

---

config.js
debian/jitsi-meet-turnserver.postinst
package-lock.json
package.json
react/features/base/config/configWhitelist.js
resources/update-ljm.sh

Always attempt to discover the configured STUN/TURN servers.
Ref: https://github.com/jitsi/lib-jitsi-meet/pull/1350

fix(config) drop useStunTurn

---

react/features/conference/functions.any.js
react/features/conference/functions.native.js
react/features/conference/functions.web.js

fix(native) add missing function

---

react/features/video-quality/middleware.js

fix(video-quality-dialog): Initial value.

---

package-lock.json
package.json
webpack.config.js

Fixed by patching react-native:
https://github.com/jitsi/react-native/commit/e7ee500660cb975d9037b42d29ea8c04bb5355f9
(backport from upstream)

fix(ios) fix not rendering images on iOS 14

---

static/prejoin.html

fix(prejoin) allow libs loaded in prejoin.html to be cached

---

android/build.gradle

chore(android) update gradle plugin to version 4.0.2

---

package-lock.json
package.json
react/features/prejoin/actions.js

https://github.com/jitsi/lib-jitsi-meet/pull/1368

feat(prejoin): handle disabled precall test.

---

ios/Podfile.lock
package-lock.json
package.json

Fix rn deps update

---

react/features/conference/functions.web.js

fix(prejoin) guard case for locationUrl being falsy in prejoin screen

---

react/features/base/participants/preloadImage.web.js

Use fetch(), which gives us better control over headers.

fix(avatars) refactor preloading

---

package-lock.json
package.json

chore(deps) update Olm to 3.2.1

---

index.html
react/index.web.js

fix(pwa) bypass loading in electron. ensure same origin with registrator

---

static/pwa/registrator.js

fix(pwa) remove window.load event handler for pwa registrator

---

debian/jitsi-meet-web.install
index.html
react/index.web.js

fix(pwa) move logic for registering pwa worker

---

conference.js
react/features/base/conference/actions.js
react/features/base/conference/constants.js
react/features/base/conference/functions.js
react/features/base/participants/middleware.js
react/features/base/participants/reducer.js
react/features/base/settings/actionTypes.js
react/features/base/settings/actions.js
react/features/base/settings/reducer.js

Through several avatar work iterations it's no longer used.

fix(avatar) remove participant's "avatarID"

---

modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js

fix(thumbnail): cleanup unused hover properties.

---

index.html

Looks like the base it's still applied, so use a full URL.

fix(pwa) fix PWA worker script origin

---

android/gradle.properties

https://github.com/jitsi/jitsi-meet/issues/7911#issuecomment-714323255

fix(android) fix runtime WebRTC issue

---

package-lock.json
package.json

fix(xmpp): Update previd value when trying to resume connection.

---

conference.js
modules/UI/UI.js
modules/UI/shared_video/SharedVideoThumb.js
modules/UI/videolayout/LocalVideo.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js
react/features/base/tracks/middleware.js
react/features/filmstrip/components/web/StatusIndicators.js

ref(StatusIndicators): Use video muted from redux.

---

package-lock.json
package.json

chore(deps) lib-jitsi-meet@latest.

fix(screenshare): bring back 'x-google-flag:conference' flag in remote desc for SS.

---

react/features/base/lib-jitsi-meet/middleware.js

fix: Add more details to args passed to the GlobalOnErrorHandler.

---

modules/UI/UI.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js
react/features/filmstrip/components/web/StatusIndicators.js
react/features/remote-video-menu/components/web/RemoteVideoMenuTriggerButton.js

ref(StatusIndicators): Use audio muted from redux.

---

modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js
react/features/filmstrip/components/web/StatusIndicators.js

ref(StatusIndicators): isScreenSharing -> redux.

---

lang/main-ptBR.json

Add security section on translation file main-ptBR.json

Add missing strings on main-ptBR.json

---

conference.js
modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
react/features/base/conference/functions.js
react/features/connection-indicator/components/web/ConnectionIndicator.js

ref(thumbnail): use connectionStatus from redux.

---

react/features/base/jwt/functions.js
react/features/base/settings/middleware.js
react/features/prejoin/actionTypes.js
react/features/prejoin/actions.js

* The prejoin display name is pre-filled with the name from the jwt.

feat(prejoin): Add name from jwt to prejoin screen

---

modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js
react/features/base/participants/actions.js
react/features/base/participants/functions.js
react/features/base/participants/middleware.js
react/features/base/participants/reducer.js

ref(thumbnail): mutedWhileDisconnected -> redux

---

.github/ISSUE_TEMPLATE/2-feature-request.md

…if they are reported as a feature request, of course.

Automatically assign feature-request tag to issues

---

resources/prosody-plugins/token/util.lib.lua

See also https://community.jitsi.org/t/jwt-token-issuer/82527

allow wildcard in token issuer verification

---

react/features/base/connection/functions.js

fix(jaas) fix double slash for branded invite urls

---

react/features/calendar-sync/components/CalendarList.web.js

fix(CalendarList): calendar.svg path.

---

css/_responsive.scss
css/_variables.scss

* Fix layout
* Change background color & show image

fix(welcome_page): Fix mobile version

---

conference.js

ref(presenter): refactor the desktop resize logic for presenter.

---

css/modals/video-quality/_video-quality.scss
lang/main.json
react/features/base/media/middleware.js
react/features/video-quality/components/VideoQualitySlider.web.js

It has been `true` for a very long time.

feat(BrowserCapabilities) drop supportsVideo

---

react/features/base/premeeting/components/web/CopyMeetingUrl.js

fix(vpaas) fix invite url flicker for jaas users

---

react/features/base/util/uri.js

This fixes the issue described in #7900

Replace special chars in roomName before constructing url

---

react/features/remote-video-menu/components/AbstractMuteEveryoneDialog.js
react/features/remote-video-menu/components/AbstractMuteEveryoneElseButton.js
react/features/remote-video-menu/components/native/MuteEveryoneDialog.js
react/features/remote-video-menu/components/native/MuteEveryoneElseButton.js
react/features/remote-video-menu/components/native/RemoteVideoMenu.js
react/features/remote-video-menu/components/native/index.js
react/features/remote-video-menu/components/web/MuteEveryoneDialog.js
react/features/remote-video-menu/components/web/MuteEveryoneElseButton.js
react/features/remote-video-menu/components/web/RemoteVideoMenuTriggerButton.js
react/features/remote-video-menu/components/web/index.js
react/features/toolbox/components/MuteEveryoneButton.js
react/features/toolbox/components/native/OverflowMenu.js
react/features/toolbox/components/web/Toolbox.js

adds mute everyone

---

css/_welcome_page.scss

On large screens the welcome card was too wide. Added max-width according to design.

fix(welcome_page): Add max width to welcome card

---

config.js
doc/example-config-files/config.js.example
doc/example-config-files/multidomain/config.js.multidomain.example
modules/UI/UI.js
react/features/base/config/configWhitelist.js
react/features/chat/middleware.js

We stopped providing a way to set them, so don't render them either.
Also cleanup some leftover config options.

fix(chat) stop using nicknames

---

package-lock.json
package.json

fix(screenshare): do not reconfigure encodings for simulcast SS

---

react/features/base/connection/functions.js

fix(jaas) replace only the first slash in a pathname

---

config.js
package-lock.json
package.json
react/features/base/participants/functions.js
react/features/base/participants/middleware.js
react/features/lobby/middleware.js

Also, default to libravatar.
Closes: https://github.com/jitsi/jitsi-meet/issues/4927

feat(avatar) add ability to customize Gravatar base URL

---

lang/languages.json

Include "Latvian" in the list

---

resources/prosody-plugins/util.lib.lua

Make jwt accept boolean values for features

---

react/features/base/participants/actions.js

fix(connection-status): action

---

package-lock.json
package.json

fix(TPC): Do not scale down desktop track in p2p/non-simulcast cases.

---

android/sdk/src/main/AndroidManifest.xml

fix(android) disables the RNWebViewFileProvider

---

android/sdk/src/main/java/org/jitsi/meet/sdk/AudioDeviceHandlerGeneric.java
android/sdk/src/main/java/org/jitsi/meet/sdk/AudioModeModule.java

Android fix volume after focus loss

---

android/gradle.properties
ios/app/src/Info.plist
ios/app/watchos/app/Info.plist
ios/app/watchos/extension/Info.plist
ios/sdk/src/Info.plist

chore(rn) raise SDK and app versions

---

react/features/base/config/configWhitelist.js

ref: Remove unused option from whitelist.

---

config.js
react/features/base/config/configWhitelist.js

feat: Remove the min-participants config.

---

react/features/base/conference/actionTypes.js
react/features/base/conference/reducer.js

cleanup: Remove unused code.

---

config.js

cleanup: Remove obsolete config option.

---

config.js
react/features/base/config/configWhitelist.js

cleanup: Remove the startBitrate option.

---

package-lock.json
package.json

fix(tracks): Do not add a second audio track.

---

config.js

ref: Remove openBridgeChannel.

---

config.js

Remove conference-wide RTX/REMB/TCC/opus-red options.

---

config.js

doc: Add docs for enableLipSync.

---

config.js
react/features/base/config/configWhitelist.js
react/features/conference/components/native/NavigationBar.js
react/features/conference/components/web/Subject.js

feat(ConferenceTimer): Add config option to hide.

---

config.js
package-lock.json
package.json
react/features/base/config/configWhitelist.js

Helps with testing turn relay cases.

feat: Add option to force pc to use turn relay candidates.

---

lang/main.json
modules/UI/UI.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/VideoContainer.js
modules/UI/videolayout/VideoLayout.js
react/features/base/testing/functions.js
react/features/base/testing/middleware.js
react/features/base/tracks/actionTypes.js
react/features/base/tracks/actions.js
react/features/base/tracks/reducer.js
react/features/large-video/actionTypes.js
react/features/large-video/actions.web.js
react/features/large-video/reducer.js
react/features/toolbox/components/web/Toolbox.js

Used for some tests in torture.

feat: Exposes a method for checking is remote track received and played.

---

react/features/analytics/functions.js
react/features/base/util/uri.js

feat(analytics): Add tenant.

---

package-lock.json
package.json

fix: Fixes VP9 support on Chrome.

---

modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoContainer.js
modules/UI/videolayout/VideoLayout.js
react/features/base/participants/actions.js
react/features/base/participants/functions.js
react/features/base/participants/middleware.js
react/features/base/participants/reducer.js

fix(video):Always show avatar if video is inactive

---

ios/Podfile.lock
package-lock.json
package.json

chore(deps) update react-native-webview

---

ios/app/src/AppDelegate.m
ios/sdk/sdk.xcodeproj/project.pbxproj

Weird timing issue in appDidFinishLaunching, make sure we store the
launchOptions before we touch any view code.

fix(ios) fix joining a meeting when the app was closed

---

package-lock.json
package.json

* fix: Skip sending multiple times disco-info to jicofo.
* build(deps): bump ini from 1.3.5 to 1.3.7
https://github.com/jitsi/lib-jitsi-meet/compare/9f65e8fab3635ff2e05a5dcff7cc16b33215b6be...8bb653f1d6d450f4d17f56eb6bd4c353138f6829

chore(deps) lib-jitsi-meet@latest

---

resources/update-ljm.sh

fix(script) add commits list to update LJM message

---

modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/SmallVideo.js
react/features/analytics/AnalyticsEvents.js

feat(analytics): Adds metric for SS issues.

---

lang/main.json
react/features/recording/components/Recording/StartRecordingDialogContent.js

fix(jaas) update recording label and hide option for jaas users

---

css/filmstrip/_tile_view.scss
css/filmstrip/_tile_view_overrides.scss
react/features/filmstrip/actions.web.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/subscriber.web.js

fix(tile-view) reduce margins, take 2

---

lang/main-de.json

Fix the German translation for disabling lobby dialog.

lang: update German translation

---

resources/install-letsencrypt-cert.sh

Hello,
I added a systemd component in the letsencrypt installer script.
With best regards
Sebastian

add systemd to letsencrypt installer

---

lang/main-zhCN.json

fix(lang) update zhCN translation

---

react/features/base/participants/functions.js
react/features/base/participants/middleware.js

fix: Show phone icon for jigasi participants.

---

android/gradle.properties
ios/app/src/Info.plist
ios/app/watchos/app/Info.plist
ios/app/watchos/extension/Info.plist

chore(android,ios) raise versions

---

ios/Podfile.lock
ios/app/app.xcodeproj/project.pbxproj
package-lock.json
package.json
react/features/base/dialog/components/native/styles.js
react/features/toolbox/components/native/OverflowMenu.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/8347

Fix iOS 11

---

react/features/filmstrip/components/web/Filmstrip.js

fix(filmstrip) fix button not considering interface config settings

---

lang/languages-oc.json
lang/main-oc.json

Hello,
a small PR to update the Occitan language.
Best regards

i18n: update Occitan language

---

config.js
react/features/base/config/configWhitelist.js
react/features/video-layout/functions.js

feat(jaas) allow tile view to be disabled

---

debian/jitsi-meet-prosody.postinst
doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
resources/prosody-plugins/mod_client_proxy.lua
resources/prosody-plugins/mod_roster_command.lua
resources/prosody-plugins/mod_roster_command.patch

Remove the "focus" external component, use client_proxy instead.

---

conference.js
config.js
react/features/base/config/configWhitelist.js

feat(external_api) allow initial gUM requests to be disabled

---

config.js
react/features/base/config/configWhitelist.js
react/features/local-recording/middleware.js
react/features/no-audio-signal/middleware.js
react/features/noise-detection/middleware.js
react/features/notifications/actions.js
react/features/recording/actions.any.js
react/features/talk-while-muted/middleware.js
react/features/transcribing/actions.js

feat(external_api) allow notifications to be configured

---

css/_base.scss
css/_chat.scss
css/_responsive.scss
react/features/chat/components/AbstractChat.js
react/features/chat/components/web/Chat.js
react/features/chat/components/web/ChatDialog.js
react/features/chat/components/web/ChatDialogHeader.js
react/features/chat/constants.js
react/features/toolbox/functions.web.js

* Fix toolbox buttons not displaying properly when chat is open.
* Open chat in fullscreen dialog past custom thresholds when mobile/desktop toolbox would become unusable due to chat
* Remove mobile chat check when displaying toolbox

feat(chat): Improve responsiveness.

---

android/sdk/build.gradle
ios/Podfile.lock
package-lock.json
package.json

Fixes: https://github.com/jitsi/jitsi-meet/issues/8353

fix(libre-build) skip spurious Firebase and GCM dependencies

---

modules/API/API.js
modules/API/external/external_api.js
react/features/base/tracks/middleware.js
react/features/base/tracks/subscriber.js

@quitrk @hristoterezov @saghul 
Documentation update PR: https://github.com/jitsi/handbook/pull/135/files

feat(external_api) add command and event listener for CS

---

react/features/welcome/components/WelcomePage.native.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/8307

fix(rn) stop room name generator when field is focused

---

debian/jitsi-meet-prosody.postinst

make sure extra plugin paths are enabled

---

conference.js
modules/UI/UI.js
modules/UI/shared_video/SharedVideoThumb.js
modules/UI/videolayout/Filmstrip.js
modules/UI/videolayout/LocalVideo.js
modules/UI/videolayout/RemoteVideo.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoLayout.js
react/features/audio-level-indicator/components/AudioLevelIndicator.js
react/features/base/conference/middleware.any.js
react/features/base/media/components/web/AudioTrack.js
react/features/base/media/components/web/Video.js
react/features/filmstrip/components/web/Thumbnail.js
react/features/filmstrip/components/web/index.js
react/features/filmstrip/functions.web.js
react/features/remote-video-menu/components/web/RemoteVideoMenuTriggerButton.js
react/features/video-layout/middleware.web.js

ref(Thumbnail): Create React component.

---

react/features/invite/functions.js

fix(jaas) disable directory integration

---

react/features/toolbox/components/web/Toolbox.js

fix(menu) do not display overflow menu button if no items

---

conference.js
config.js
react/features/base/config/configWhitelist.js

feat(external_api) allow shortcuts to be disabled

---

react/features/base/settings/reducer.js

fix(settings) remove legacy compatibility code

---

modules/API/API.js
react/features/chat/middleware.js

@hristoterezov @quitrk @saghul @damencho 
Link to documentation update: https://github.com/jitsi/handbook/pull/136/files

feat(external-api) set `privateMessage` flag on `incoming-message`

---

css/filmstrip/_tile_view_overrides.scss

Reverts a8b2e6ffb338fc9dc83f0c4a8213482064bff96d

fix(tile-view) avoid covering the logo

---

debian/jitsi-meet-prosody.postinst

fix: Fix broken postinst reported by @wsldankers.

---

ios/Podfile.lock
package-lock.json
package.json

Stats timestamps were incorrectly formatted, fixed upstream.
Fixes: https://github.com/jitsi/jitsi-meet/issues/8367

fix(rn,stats) fix incorrect bitrate calculation on mobile

---

css/_subject.scss
react/features/conference/components/web/Subject.js

fix(subject) remove gradient if no info in topbar

---

android/build.gradle

Android update native

---

debian/jitsi-meet-prosody.postinst
debian/jitsi-meet-prosody.templates

debian: Do not read jicofosecret.

---

react/features/base/flags/constants.js
react/features/filmstrip/functions.native.js
react/features/notifications/actions.js
react/features/toolbox/functions.native.js
react/features/video-layout/functions.js

feat(mobile) adds more feature flags

---

package-lock.json
package.json

Support processing stats in the spec-compliant format.

chore(deps) react-native-callstats@3.70.1

---

package-lock.json
package.json

https://github.com/jitsi/lib-jitsi-meet/compare/831716c1601da259905e58a9db23ebdcea3f1ad8...3570339360763fa0911d92c5ae7c270860b6934b.

deps(ljm): Restore local connection status.

---

lang/main-tr.json

There were some issues with Turkish translations, so I fixed them with this PR.

Fixed Turkish translation issues

---

react/features/base/media/functions.js

quick typo fix in the docs -audio to video

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
doc/example-config-files/multidomain/prosody.cfg.multidomain.example
doc/example-config-files/prosody.cfg.lua.example
doc/example-config-files/scalable/meet.example.com.cfg.lua.scalable.example

fix: Use internal_hashed everywhere.

---

react/features/base/config/configWhitelist.js

feat(external_api) allow dropbox option to be overwritten

---

README.md

fix(docs) add JaaS link to README

---

react/features/filmstrip/actionTypes.js
react/features/filmstrip/actions.native.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/reducer.js

fix(Filmstrip): Prevent Toolbox from being shown indefinitely when hovering filmstrip

---

react/features/recent-list/functions.web.js

https://github.com/jitsi/jitsi-meet/issues/8481

fix(recents-list): Order recents by last used

---

react/features/base/testing/functions.js

fix(test): Make sure test doesn't error out.

---

react/features/base/flags/constants.js
react/features/mobile/audio-mode/middleware.js

feat(mobile) adds ability to disable sound

---

webpack.config.js

feat(dev) bind to 0.0.0.0 on the dev server by default

---

android/gradle.properties
ios/sdk/src/Info.plist
resources/update-mobile-sdk-version.sh
resources/update-mobile-version.sh

Update sdk version + scripts

---

resources/load-test/load-test-participant.js

Improve load-test script.

---

react/features/base/testing/functions.js

fix(tests): Add more checks so that test don't error out.

---

debian/jitsi-meet-web-config.postinst

added module proxy_wstunnel for apache2

add module proxy_wstunnel

---

react/features/remote-video-menu/components/web/RemoteVideoMenuTriggerButton.js

fix(AudioSlider): removed when volume is 0

---

react/features/embed-meeting/components/EmbedMeetingDialog.js

feat(embed-meeting) add autoplay permission to iframe sample

---

modules/API/API.js
modules/API/external/external_api.js

Added api command for kicking a participant.
Link to handbook PR: https://github.com/jitsi/handbook/pull/153
@quitrk @saghul @hristoterezov

feat (external_api) add command for kick participant

---

css/_labels.scss
css/_popover.scss
css/_transcription-subtitles.scss
css/_variables.scss
css/_videolayout_default.scss
css/filmstrip/_horizontal_filmstrip.scss
css/filmstrip/_tile_view.scss
css/filmstrip/_tile_view_overrides.scss
css/modals/invite/_invite_more.scss
css/modals/video-quality/_video-quality.scss
react/features/conference/components/web/InviteMore.js

Depends on https://github.com/8x8Cloud/jitsi-meet-branding/pull/189

fix(popups): covered by labels.

---

resources/load-test/load-test-participant.js

When audio mutes will mute the track. Also fixes previous change where we do not add any of the tracks to the room.

fix(load-test): Always create local audio track.

---

modules/API/API.js
react/features/chat/actionTypes.js
react/features/chat/actions.any.js
react/features/chat/actions.native.js
react/features/chat/actions.web.js
react/features/chat/components/AbstractChat.js
react/features/chat/components/AbstractChatPrivacyDialog.js
react/features/chat/components/PrivateMessageButton.js
react/features/chat/components/native/Chat.js
react/features/chat/components/native/ChatButton.js
react/features/chat/components/web/Chat.js
react/features/chat/components/web/ChatDialogHeader.js
react/features/chat/middleware.js
react/features/chat/reducer.js
react/features/remote-video-menu/components/web/PrivateMessageMenuButton.js

feat refactors the chat flow so it has open and close functions

---

react/features/lobby/components/native/EnableLobbyModeDialog.js

fix(rn,lobby) make sure the enable dialog follows the theme color

---

react/features/stream-effects/blur/index.js

fix(blur) fix model paths

---

config.js
package-lock.json
package.json

* feat: Use the new bridge signaling format.
jitsi/lib-jitsi-meet@c534f74...beaff3d
*feat: Add 'useNewBandwidthAllocationStrategy' to config.js.

feat(qualityController): Use the new bridge signaling format.

---

ios/sdk/src/ExternalAPI.h
ios/sdk/src/ExternalAPI.m
ios/sdk/src/JitsiMeetView.h
ios/sdk/src/JitsiMeetView.m

chore(ios) remove warnings on JitsiMeetView

---

react/features/stream-effects/blur/index.js

Check model response status and catch errors.

---

css/_atlaskit_overrides.scss
css/_chat.scss
css/_responsive.scss
lang/main.json
react/features/base/dialog/components/web/StatelessDialog.js
react/features/base/environment/utils.js
react/features/base/icons/svg/index.js
react/features/base/icons/svg/paper-plane.svg
react/features/chat/components/web/Chat.js
react/features/chat/components/web/ChatDialog.js
react/features/chat/components/web/ChatInput.js
react/features/chat/components/web/ChatTouchmoveHack.js
react/features/chat/components/web/DisplayNameForm.js
react/features/chat/components/web/KeyboardAvoider.js
react/features/chat/components/web/TouchmoveHack.js

* Add buttons to send messages/set nickname.
* Redesign message/nickname inputs.
* Pin messages to the input.
* Add keyboard avoider for Safari.
* Make chat content scrollable on mobile.

feat(Chat) Improve responsive behaviour further.

---

conference.js
css/overlay/_overlay.scss
package-lock.json
package.json
react/features/base/tracks/actions.js
react/features/base/tracks/functions.js
react/features/overlay/actionTypes.js
react/features/overlay/actions.js
react/features/overlay/components/web/AbstractSlowGUMOverlay.js
react/features/overlay/components/web/SlowGUMOverlay.js
react/features/overlay/components/web/index.js
react/features/overlay/overlays.web.js
react/features/overlay/reducer.js

Show an overlay with a spinner when slow gUM is fired

fix(gum) add event handling for SLOW_GET_USER_MEDIA

---

react/features/lobby/middleware.js
react/features/prejoin/functions.js

feat(sip): Added auto-knocking for sip gateway if lobby is enabled

---

react/features/dynamic-branding/reducer.js
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.js
react/features/invite/components/add-people-dialog/web/DialInSection.js
react/features/invite/functions.js
react/features/no-audio-signal/components/DialInLink.js
react/features/prejoin/actions.js

Added possibility to override the default DID number page url through branding data.
@saghul @hristoterezov

(feature) - Add support for custom DID numbers page url

---

react/features/base/buttons/CopyButton.js
react/features/base/util/helpers.js

improved copy text helper function

---

.eslintignore

fix(lint-run-command)

---

package-lock.json
package.json

We use TFLite now so this is unused.

chore(deps) remove Tensorflow

---

package-lock.json
package.json

Fixes: https://github.com/jitsi/jitsi-meet/issues/8683

fix(deps) bump lodash

---

react/features/blur/components/VideoBlurButton.js

fix(disable blur) disable blur button if camera is off.

---

modules/API/external/external_api.js
react/features/base/premeeting/components/web/CopyMeetingUrl.js

feat(external_api): allow clipboard-write

---

react/features/remote-video-menu/actions.js

This fixes an issue discussed here: https://github.com/jitsi/jitsi-meet/commit/23bb824731034155e0fde409d3878523bdd1fddd#r47574797 @hristoterezov @damencho

Use logger instead of console

---

android/gradle.properties
ios/sdk/src/Info.plist

bumps mobile sdkVersion to 3.2.0

---

lang/main-de.json

There was a missing translation in main-de.json

Netsyno/dimitar delchev/missing translation

---

react/features/base/buttons/CopyButton.js
react/features/base/premeeting/components/web/CopyMeetingUrl.js
react/features/base/util/helpers.js
react/features/invite/components/add-people-dialog/web/LiveStreamSection.js

fix(copyText): in iframe for chrome<85

---

react/features/invite/components/add-people-dialog/web/LiveStreamSection.js

fix(live-stream-section): Use await for copyText

---

package-lock.json
package.json
react/features/base/util/helpers.js

It does a more elaborate way of textarea copying, hopefully it's more reliable.

fix(copyText) use a helper library

---

.github/workflows/ci.yml
package-lock.json

fix(deps) sync package-lock

---

react/features/base/tracks/actions.js

The error object changed its shape through time, adapt to the change.

fix(rn,tracks) fix not showing alert when permission is not granted

---

ios/app/JitsiMeetBroadcast Extension/DarwinNotificationCenter.h
ios/app/JitsiMeetBroadcast Extension/DarwinNotificationCenter.m
ios/app/JitsiMeetBroadcast Extension/Info.plist
ios/app/JitsiMeetBroadcast Extension/JitsiMeetBroadcast Extension.entitlements
ios/app/JitsiMeetBroadcast Extension/SampleHandler.h
ios/app/JitsiMeetBroadcast Extension/SampleHandler.m
ios/app/JitsiMeetBroadcast Extension/SampleUploader.h
ios/app/JitsiMeetBroadcast Extension/SampleUploader.m
ios/app/JitsiMeetBroadcast Extension/SocketConnection.h
ios/app/JitsiMeetBroadcast Extension/SocketConnection.m
ios/app/app.xcodeproj/project.pbxproj
ios/app/src/Info.plist
ios/sdk/sdk.xcodeproj/project.pbxproj
ios/sdk/src/JitsiMeet.m
ios/sdk/src/ScheenshareEventEmiter.h
ios/sdk/src/ScheenshareEventEmiter.m
package-lock.json
package.json
react/features/mobile/picture-in-picture/functions.js
react/features/toolbox/components/native/ScreenSharingAndroidButton.js
react/features/toolbox/components/native/ScreenSharingButton.js
react/features/toolbox/components/native/ScreenSharingIosButton.js

feat(iOS): screensharing support

---

ios/fastlane/Fastfile

fix(ios) the broadcast extension'd bundle ID must match the app's

---

react/features/filmstrip/subscriber.web.js

fix(responsive): Fix tiles not recomputing when jumping between screen sizes

---

modules/UI/videolayout/VideoContainer.js
react/features/base/environment/environment.js
react/features/base/jitsi-local-storage/setup.web.js
react/features/settings/components/web/audio/AudioSettingsContent.js

feat(browser-support): Add support for WKWebview based browsers.

---

config.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/8749

fix(config) fix syntax error in commented code

---

config.js
react/features/base/config/configWhitelist.js
react/features/base/jitsi-local-storage/setup.web.js

feat(config): Add useHostPageLocalStorage

---

resources/prosody-plugins/mod_muc_allowners.lua

We were filtering only self presences, now it filters and the presences to the other participants.

feat: Fixes filtering not needed presences.

---

config.js
interface_config.js
modules/API/API.js
modules/API/external/external_api.js
react/features/base/config/actionTypes.js
react/features/base/config/actions.js
react/features/base/config/configWhitelist.js
react/features/base/config/constants.js
react/features/base/config/functions.any.js
react/features/base/config/functions.web.js
react/features/base/config/reducer.js
react/features/conference/components/web/InviteMore.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/prejoin/components/Prejoin.js
react/features/recording/components/LiveStream/web/LiveStreamButton.js
react/features/recording/components/Recording/web/RecordButton.js
react/features/remote-video-menu/components/web/PrivateMessageMenuButton.js
react/features/toolbox/components/web/Toolbox.js
react/features/toolbox/functions.web.js

Added API command for overwriting whitelisted configs in real time.
@quitrk @hristoterezov @saghul @gimre @vp8x8 @damencho @muscat1

(external_api) Add command for overwriting a whitelisted config value

---

react/features/base/jwt/functions.js
react/features/base/settings/middleware.js

fix(prejoin): Don't overwrite display name with ''

---

react/features/base/color-scheme/defaultScheme.js
react/features/base/styles/components/styles/ColorPalette.js
react/features/base/toolbox/components/_.web.js
react/features/base/toolbox/components/index.js
react/features/base/toolbox/components/web/OverflowMenuItem.js
react/features/base/toolbox/components/web/ToolboxButtonWithIcon.js
react/features/base/toolbox/components/web/ToolboxItem.js
react/features/base/toolbox/components/web/index.js
react/features/conference/components/native/Conference.js
react/features/conference/components/native/styles.js
react/features/display-name/components/native/styles.js
react/features/toolbox/components/native/Toolbox.js
react/features/toolbox/components/native/styles.js

feat(toolbox): Redesign mobile toolbox

---

react/features/chat/components/PrivateMessageButton.js

fix(chat) hides send private chat button when enable.chat flag is false.

---

css/_toolbars.scss
react/features/toolbox/components/web/Toolbox.js
react/features/toolbox/functions.web.js

fix(toolbox): Restructure items order for desktop & mobile

---

package-lock.json
package.json
react/features/stream-effects/audio-mixer/AudioMixerEffect.js

Depends on [pr](https://github.com/jitsi/lib-jitsi-meet/pull/1522)

fix(screenshare): Fix audio screen share muted state

---

react/features/billing-counter/constants.js

fix(vpaas) send jitsiMeetId instead of billingId

---

css/_toolbars.scss

fix(toolbox): Fix buttons size in minified mode

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetOngoingConferenceService.java
android/sdk/src/main/java/org/jitsi/meet/sdk/OngoingNotification.java

feat(android): adds timer to OngoingNotification

---

react/features/base/dialog/components/native/styles.js

fix(rn,bottomsheet) limit width

---

ios/app/src/AppDelegate.m
ios/ci/build-ipa.sh
ios/ci/setup-certificates.sh
ios/sdk/src/JitsiMeetView.m
ios/sdk/src/callkit/JMCallKitEmitter.swift
ios/sdk/src/picture-in-picture/PiPViewCoordinator.swift
ios/travis-ci/build-ipa.sh
modules/API/external/external_api.js
modules/UI/authentication/AuthHandler.js
modules/UI/shared_video/SharedVideo.js
modules/UI/util/UIUtil.js
modules/UI/videolayout/SmallVideo.js
modules/UI/videolayout/VideoContainer.js
modules/UI/videolayout/VideoLayout.js

Found via `codespell -q 3 -S ./lang`

fix(misc) typos

---

ios/Podfile.lock
package-lock.json
package.json

chore(deps) update react-native-webrtc to 1.89.1

---

package-lock.json
package.json

Fix script for downloading bitcode.

chore(deps) update react-native-webrtc

---

react/features/base/react/components/web/InlineDialogFailure.js
react/features/base/react/components/web/MultiSelectAutocomplete.js
react/features/invite/components/add-people-dialog/web/InviteContactsForm.js

fix(jaas) hide support link in invite error for jaas users

---

resources/load-test/load-test-participant.js

In loadtest, make localAudio non-const.

---

css/_atlaskit_overrides.scss
css/_chat.scss
css/modals/invite/_invite_more.scss
react/features/chat/components/AbstractChat.js
react/features/chat/constants.js

* Adjust chat font size.
* Adjust invite more button and text size.
* Remove useless constant.

fix(Chat): Fix modals displaying improperly due to chat.

---

react/features/base/conference/middleware.any.js
react/features/base/jwt/constants.js
react/features/base/jwt/functions.js
react/features/base/jwt/index.js

Logs the jwt errors both from xmpp and from a client-side validation.

feat(jwt) log jwt validation errors

---

react/features/base/conference/actions.js

fix(startMuted): Fix unmute on mobile when it is muted by Jicofo on join.

---

android/sdk/build.gradle
android/settings.gradle

fix(android) remove leftover package

---

react/features/e2ee/middleware.js

Fix typo in middleware.js

---

resources/load-test/load-test-participant.js

Fixes the case where audio track was not added due to jicofo muting clients.

fix(load-test): Fixes unmuting loadtest client.

---

css/_base.scss
css/_popup_menu.scss

fix(menu): Pop menu icons & background

---

modules/API/API.js
modules/API/external/external_api.js

Added command for setting tile view on/off
@saghul

feat (external-api) Add command for setting tile view mode

---

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastAction.java
android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastEvent.java
android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java
android/sdk/src/main/java/org/jitsi/meet/sdk/ExternalAPIModule.java
ios/app/src/ViewController.m
ios/sdk/src/ExternalAPI.h
ios/sdk/src/ExternalAPI.m
ios/sdk/src/JitsiMeetView.h
ios/sdk/src/JitsiMeetView.m
ios/sdk/src/JitsiMeetViewDelegate.h
react/features/mobile/external-api/middleware.js

feat(external_api): add videoMuted event and action

---

config.js
modules/UI/UI.js
react/features/base/config/configWhitelist.js
react/features/base/util/helpers.js
react/features/conference/components/web/Conference.js
react/features/large-video/components/LargeVideo.web.js

@saghul @quitrk @gimre @damencho @hristoterezov 
We can now set the background alpha through a config value.

(feat) Set background transparency levels.

---

interface_config.js

fix(interfaceConfig) mark as deprecated

---

lang/main-nl.json

Added new Dutch translations.
@ahreurink

lang: Added Dutch translations to main-nl.json

---

react/features/video-layout/components/TileViewButton.js
react/features/video-layout/functions.js

feat(tile-view) allow to toggle tile view while alone

---

package-lock.json
package.json
react/features/mobile/polyfills/browser.js

Promise.allSettled is supported from RN 0.63 onwards and is not supported on the current version, use a polyfill for that shims Promise.allSettled if its unavailable or noncompliant.

feat(rn,polyfill): Add a polyfill for Promise.allSettled.

---

css/modals/virtual-background/_virtual-background.scss
lang/main.json
react/features/stream-effects/virtual-background/JitsiStreamBackgroundEffect.js
react/features/virtual-background/actions.js
react/features/virtual-background/components/VirtualBackgroundDialog.js
react/features/virtual-background/functions.js

feat(upload background image): Upload virtual background image.

---

modules/API/API.js
modules/API/external/external_api.js
react/features/base/tracks/functions.js
react/features/toolbox/components/web/ToggleCameraButton.js

feat(external_api): Add command for toggling camera on mobile web

---

modules/API/API.js
modules/API/external/external_api.js

feat(external_api): Add command for toggling localFlipX

---

react/features/base/dialog/components/native/InputDialog.js

feat(rn): makes InputDialog textInput autoFocus

---

react/features/virtual-background/components/VirtualBackgroundDialog.js
react/features/virtual-background/functions.js

fix(virtual-background): Fixes: #8892 Upload virtual background on firefox. 

---

css/_lobby.scss
react/features/lobby/components/web/KnockingParticipantList.js

This should also solve https://github.com/jitsi/jitsi-meet/issues/8894

fix(lobby): Knocking participants list for small widths

---

react/features/remote-control/actions.js

https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event

Fix: used deprecated onmousewheel event

---

config.js

fix: Correct some missing comas in config.js.

---

css/modals/virtual-background/_virtual-background.scss
react/features/virtual-background/components/VirtualBackgroundDialog.js

fix(virtual-background): Hide scrollbar on loading action.

---

lang/main.json
react/features/invite/actions.any.js
react/features/invite/components/add-people-dialog/AbstractAddPeopleDialog.js
react/features/invite/components/add-people-dialog/web/InviteContactsForm.js
react/features/invite/constants.js
react/features/invite/functions.js

feat(sipcall) implement sip invite

---

lang/languages.json

fix: Adds Portuguese to listed languages

---

react/features/base/modal/components/JitsiModal.js

fix(ios-keyboard) 

---

react/features/base/premeeting/components/web/PreMeetingScreen.js
react/features/virtual-background/components/VideoBackgroundButton.js

Premeeting virtual background

---

ios/app/src/AppDelegate.m
react/features/base/flags/constants.js
react/features/toolbox/components/native/ScreenSharingIosButton.js

feat(ios): adds ios screensharing enabled flag

---

react/features/stream-effects/virtual-background/vendor/README.md

Fixes: https://github.com/jitsi/jitsi-meet/issues/8792

fix(virtual-backgrounds) add segmentation model license information

---

conference.js

This feature will be used by sip-jibri to join locked rooms.

feat: Adds an option to preset in localstorage key for locked rooms.

---

lang/languages-oc.json

Adds two more entries to the languages list

i18n update for Occitan

---

react/features/invite/actions.any.js
react/features/invite/functions.js

fix(sip-invite) fix sip invite jwt not being sent correctly

---

android/gradle.properties
ios/app/broadcast-extension/Info.plist
ios/app/src/Info.plist
ios/app/watchos/app/Info.plist
ios/app/watchos/extension/Info.plist
ios/sdk/src/Info.plist

chore(rn,versions) bump SDK and apps versions

---

css/modals/settings/_settings.scss

fix(settings): Make language dropdown wider

---

debian/jitsi-meet-web.install

fix(debian) don't include package{-lock}.json files

---

css/modals/virtual-background/_virtual-background.scss
lang/main.json
react/features/stream-effects/virtual-background/JitsiStreamBackgroundEffect.js
react/features/virtual-background/actionTypes.js
react/features/virtual-background/actions.js
react/features/virtual-background/components/VirtualBackgroundDialog.js
react/features/virtual-background/reducer.js

feat(blur-background): Add a second blur option.

---

ios/sdk/src/JitsiMeetViewDelegate.h

bugfix(ios): fixes typo on JitsiMeetViewDelegate

---

package-lock.json
package.json
react/features/rtcstats/RTCStats.js
react/features/rtcstats/middleware.js

feat(rtcstats): switch to rtcstats v3 protocol

---

ios/fastlane/Fastfile

Fastlane shenanigans

---

css/modals/invite/_invite_more.scss
react/features/invite/components/add-people-dialog/web/InviteByEmailSection.js

fix(mailto) fix mailto links not working on Brave ios

---

config.js

Add missing enforcePreferredCodec, bitrates for H264 and fix an issue with missing comma.

fix(config): Add missing config.js settings.

---

react/features/base/config/reducer.js

fix(rn,config) update to new configuration for codec selection

---

react/features/video-layout/subscriber.js

fix(video-layout): Unpin SS when the screensharing participant leaves.

---

ios/app/broadcast-extension/SampleUploader.m
package-lock.json
package.json

Fixes: https://github.com/jitsi/jitsi-meet/issues/9012

fix(ios) detect orientation when screen sharing

---

css/_mini_toolbox.scss
webpack.config.js

- fix aot not being debug-able locally in jitsi-meet-electron app

fix(aot): fix aot buttons size

---

react/features/invite/actions.any.js
react/features/invite/functions.js

feat(sip-invite) add room password for sip invite requests

---

react/features/billing-counter/functions.js

fix(jaas) fix recorder and sip gateways not detecting vpaas meetings

---

react/features/invite/actions.any.js
react/features/invite/components/add-people-dialog/AbstractAddPeopleDialog.js
react/features/invite/components/add-people-dialog/web/InviteContactsForm.js
react/features/lobby/components/native/KnockingParticipantList.js
react/features/lobby/components/web/KnockingParticipantList.js
react/features/lobby/constants.js

fix(sip-invite) add minor fixes to sip invite flow

---

package-lock.json
package.json

fix(android) fix screen rotation when screen-sharing

---

package-lock.json
package.json

fix(android): catch exception thrown when media projection is stopped

---

react/features/invite/functions.js

fix(sip-invite) remove hash params

---

modules/API/API.js
modules/UI/UI.js
modules/UI/util/MessageHandler.js

module(UI): removed unused methods

---

css/_mini_toolbox.scss
css/_variables.scss
react/features/always-on-top/Toolbar.js

The screenshot above also contains changes from:
https://github.com/jitsi/jitsi-meet-electron-utils/pull/109

feat(aot): improve AOT UI/UX

---

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java
ios/sdk/sdk.xcodeproj/project.pbxproj
ios/sdk/src/ExternalAPI.h
ios/sdk/src/ExternalAPI.m
ios/sdk/src/JitsiMeetView.h
ios/sdk/src/JitsiMeetView.m
ios/sdk/src/ScheenshareEventEmiter.m
react/features/base/conference/middleware.native.js
react/features/base/tracks/actions.js
react/features/mobile/external-api/middleware.js
react/features/toolbox/components/native/ScreenSharingAndroidButton.js
react/features/toolbox/components/web/Toolbox.js

fix(ios) fix leaving the meeting when screen-sharing

---

react/features/base/conference/middleware.web.js
react/features/base/environment/environment.js
react/features/screen-share/functions.js

fix(screenshare): remove redundant event / only show on supported env

---

ios/sdk/src/JitsiMeetConferenceOptions.h
ios/sdk/src/JitsiMeetConferenceOptions.m

The implemented options are the call handle and UUID.

feat(ios) add ability to set CallKit options for incoming calls

---

package-lock.json
package.json
patches/react-native+0.61.5-jitsi.2.patch

fix(ios) fix building with Xcode 12.5

---

patches/react-native+0.61.5-jitsi.2.patch

fix(patch) remove unneeded hunks from RN patch

---

android/gradle.properties
ios/app/broadcast-extension/Info.plist
ios/app/src/Info.plist
ios/app/watchos/app/Info.plist
ios/app/watchos/extension/Info.plist
ios/sdk/src/Info.plist

chore(rn,versions) set mobile app and SDK versions

---

package-lock.json
package.json

Includes a MST.getSettings implementation, necessary for dropping "old
getUserMedia flow".

deps(rn) updatereact-native-webrtc

---

conference.js
react/features/base/tracks/middleware.js
react/features/base/tracks/subscriber.js

- small refactor to trigger `notifyVideoMutedStatusChanged` correctly when participant is presenting
@hristoterezov

fix (external-api): fix notify video mute changed when presenting

---

react/features/conference/components/native/NavigationBar.js
react/features/conference/components/native/styles.js

fix(rn, Labels): Place picture-in-picture button on the left

---

react/features/base/jwt/constants.js
react/features/base/jwt/functions.js

- add some missing meet features

fix(jwt-validation): validate `kid` value only for JaaS

---

react/features/invite/functions.js

fix: Fixes welcome page add calendar link. Fixes #9132

---

css/_premeeting-screens.scss
react/features/base/premeeting/components/web/PreMeetingScreen.js

It looks particularly odd, specially when any virtual background is activated.

fix(premeeting) drop gradient

---

react/features/invite/functions.js

fix(sip-invite) fix baseurl case sensitive replacement

---

css/_atlaskit_overrides.scss

fix(dialogs-style): Remove box shadow from header and footer

---

react/features/filmstrip/components/web/Thumbnail.js

fix(Thumbnail): Display mode typo.

---

react/features/video-layout/middleware.web.js

fix(participants-pane): Resize video layout when closing or opening

---

webpack.config.js

Better bundle analyzer

---

CONTRIBUTING.md

Added Avoiding bundle bloat section

docs: Update contributing file

---

react/features/conference/components/native/Conference.js

fix(RN, Toolbox): Show full participant thumbnails in tile view

---

react/features/base/participants/functions.js
react/features/participants-pane/components/ParticipantItem.js

fix(participants-pane): Use selector for displaying names

---

react/features/toolbox/components/DownloadButton.js
react/features/toolbox/components/HelpButton.js

fix(deploymentUrls): Disable help and download apps buttons for JaaS

---

react/features/invite/actions.any.js
react/features/invite/components/add-people-dialog/AbstractAddPeopleDialog.js
react/features/invite/components/add-people-dialog/native/AddPeopleDialog.js
react/features/invite/components/add-people-dialog/web/InviteContactsForm.js
react/features/invite/constants.js
react/features/invite/functions.js

fix(invite) fix notifications for phone invites

---

config.js

Add "inviteDomain" property to "dynamicBrandingUrl" property.
The CLA is signed by the company I working in (APITECH, Lyon in France).

(doc)- Add "inviteDomain"

---

react/features/toolbox/components/MuteEveryoneButton.js
react/features/toolbox/components/MuteEveryonesVideoButton.js

fix(toolbox) fix displaying mute everyone buttons for non-moderators

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
package-lock.json
package.json
resources/prosody-plugins/mod_av_moderation.lua
resources/prosody-plugins/mod_av_moderation_component.lua
resources/prosody-plugins/mod_muc_poltergeist.lua
resources/prosody-plugins/util.lib.lua

There is duplication of code in mod_av_moderation.lua, about parsing the URL params. That will be addressed in the next PR.

AV moderation

---

resources/prosody-plugins/mod_reservations.lua

This is a port of [Jicofo's reservation system](https://github.com/jitsi/jicofo/blob/master/doc/reservation.md) to a prosody module following conversation with @damencho in this thread: https://community.jitsi.org/t/gatekeeping-room-creation-from-prosody-module/89720
The flow turned out slightly more complex than I anticipated, so hopefully the following diagram helps clarify the design:

Reservations plugin

---

react/features/base/config/functions.web.js
react/features/participants-pane/components/MeetingParticipantContextMenu.js
react/features/toolbox/components/web/Toolbox.js

fix(participants-pane): Use selector for displaying chat context item

---

react/features/base/flags/constants.js
react/features/security/components/security-dialog/SecurityDialogButton.js
react/features/security/components/security-dialog/native/SecurityDialog.js

feat(native-security) added flag for controlling security options button visibility

---

lang/main-tr.json

"Kamerayı aç / kapat" means "Turn On / Off Camera" and it is not true case.
"Toggle camera" means "Kamerayı değiştir" in Turkish.

fix(lang) Update Turkish Translation

---

lang/main-it.json
lang/main-te.json
lang/main.json
react/features/participants-pane/components/InviteButton.js

fix(participants-pane) enable translation of invite button

---

lang/main-de.json

Requires #9225 to translate the invite button

fix(lang) update German translation for participants pane

---

react/features/participants-pane/components/LobbyParticipantItem.js
react/features/participants-pane/components/ParticipantItem.js

Fixes https://github.com/jitsi/jitsi-meet/issues/9211

fix(participants): Knocking participant name in participants list

---

.github/workflows/ci.yml
package-lock.json

Sync package-lock.json

---

package-lock.json
package.json

Fixes: https://github.com/jitsi/jitsi-meet/issues/8380

chore(deps) uppdate amplitude-js

---

css/modals/virtual-background/_virtual-background.scss
react/features/virtual-background/components/VirtualBackgroundDialog.js
react/features/virtual-background/components/VirtualBackgroundPreview.js

fix(virtual-background): Responsive virtual background dialog.

---

css/modals/virtual-background/_virtual-background.scss

fix(virtual-background): Fix delete virtual background icon position.

---

react/features/invite/functions.js

this will be added in a subsequent commit to the dial in page

fix(sip) remove sip text from invite

---

react/features/dynamic-branding/functions.js
react/features/dynamic-branding/reducer.js
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.js

fix(vpaas): Avoid url blipping on invite dialog

---

react/features/analytics/AnalyticsEvents.js
react/features/base/media/components/web/AudioTrack.js

feat(AudioTrack): retries for play()

---

react/features/base/media/components/web/AudioTrack.js

fix(AudioTrack): _play promise chain

---

react/features/toolbox/components/native/ScreenSharingAndroidButton.js
react/features/toolbox/components/native/ScreenSharingButton.js
react/features/toolbox/components/native/ScreenSharingIosButton.js

task(rn): hide screen share button when audioOnly mode

---

react/features/authentication/components/web/LoginDialog.js
react/features/authentication/components/web/WaitForOwnerDialog.js
react/features/base/dialog/components/web/ModalHeader.js
react/features/base/dialog/components/web/StatelessDialog.js

fix(authentication): removed cancel event from overlay effect

---

css/modals/virtual-background/_virtual-background.scss
lang/main.json
react/features/app/middlewares.web.js
react/features/stream-effects/virtual-background/JitsiStreamBackgroundEffect.js
react/features/stream-effects/virtual-background/index.js
react/features/toolbox/components/web/Toolbox.js
react/features/virtual-background/components/VirtualBackgroundDialog.js
react/features/virtual-background/components/VirtualBackgroundPreview.js
react/features/virtual-background/constants.js
react/features/virtual-background/functions.js
react/features/virtual-background/middleware.js
react/features/virtual-background/reducer.js

feat(virtual-background): Desktop share as virtual background

---

react/features/mobile/external-api/middleware.js

fix(ScreenShare) remove listener for native events when app unmounts

---

resources/prosody-plugins/token/util.lib.lua

Allow both regex and normal check for the room name

---

android/gradle.properties
ios/sdk/src/Info.plist

chore(rn,versions): set mobile SDK versions

---

config.js

fix(config): Add config for enabling unified-plan support on chromium.

---

css/modals/virtual-background/_virtual-background.scss

fix(virtual-background): Responsive virtual background preview.

---

conference.js
react/features/feedback/actions.js

fix(feedback): don't wait for feedback submission on leave meeting

---

lang/main-zhTW.json

* Fixed the proper semantic of zhTW language

i18n: zhTW: new translation

---

react/features/deep-linking/functions.js

fix(vpaas) enable deeplinking

---

config.js
react/features/base/config/configWhitelist.js
react/features/filmstrip/subscriber.web.js

feat(api) allow filmstrip autohide to be configurable

---

lang/languages.json

fix: `Thailand` to `Thai` in languages.json

---

react/features/base/toolbox/components/AbstractButton.js

fix(rn): adds check for blur function on currentTarget

---

react/features/base/participants/components/ParticipantView.native.js
react/features/shared-video/components/native/SharedVideoDialog.js
react/features/shared-video/components/native/YoutubeLargeVideo.js
react/features/shared-video/components/web/SharedVideo.js
react/features/shared-video/components/web/SharedVideoDialog.js
react/features/shared-video/middleware.any.js

fix(share-video) fix backwards compatibility issue

---

react/features/authentication/components/web/WaitForOwnerDialog.js

fix(authentication) resolved #9385 issue

---

conference.js
modules/UI/authentication/AuthHandler.js
react/features/base/conference/actions.js
react/features/base/config/functions.native.js
react/features/base/config/functions.web.js
react/features/base/flags/constants.js

feat(replace-participant): Add replaceParticipant feature-flag

---

lang/main.json
react/features/stream-effects/virtual-background/index.js
react/features/virtual-background/actions.js

fix(wasm-support): WebAssembly browser support.

---

lang/main-ptBR.json

- Adding new translations for ptBr

i18n: ptBR: new translation

---

react/features/virtual-background/components/VirtualBackgroundDialog.js
react/features/virtual-background/components/VirtualBackgroundPreview.js

fix(VirtualBackgroundDialog): SS on electron.

---

react/features/base/premeeting/components/web/PreMeetingScreen.js
react/features/lobby/components/AbstractLobbyScreen.js
react/features/lobby/components/web/LobbyScreen.js

fix(lobby) disable invite from lobby screen fix #9209

---

modules/keyboardshortcut/keyboardshortcut.js

fix(keyboardshortcut) spacebar release mutes participant

---

react/features/recording/actionTypes.js
react/features/recording/actions.any.js
react/features/recording/components/Recording/AbstractStartRecordingDialog.js
react/features/recording/functions.js
react/features/recording/reducer.js

fix(vpaas): Don't show recording link to initiator if saving on dropbox

---

css/filmstrip/_horizontal_filmstrip.scss
css/filmstrip/_tile_view.scss
css/filmstrip/_vertical_filmstrip.scss
package-lock.json
package.json
react/features/base/media/components/web/AudioTrack.js
react/features/base/media/components/web/index.js
react/features/filmstrip/actionTypes.js
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/web/AudioTracksContainer.js
react/features/filmstrip/components/web/Filmstrip.js
react/features/filmstrip/components/web/Thumbnail.js
react/features/filmstrip/components/web/ThumbnailWrapper.js
react/features/filmstrip/constants.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/reducer.js
react/features/filmstrip/subscriber.web.js
react/features/large-video/actions.any.js
react/features/large-video/middleware.js
react/features/toolbox/components/web/Toolbox.js
react/features/video-layout/actionTypes.js
react/features/video-layout/actions.js
react/features/video-layout/functions.js
react/features/video-layout/reducer.js
react/features/video-layout/subscriber.js
react/features/video-quality/constants.js
react/features/video-quality/subscriber.js

feat(Filmstrip): Pagination.

---

react/features/chat/components/web/ChatCounter.js

fix(chat) removed unread msgs counter on chat open

---

react/features/device-selection/functions.js

fix(external-api): update settings on api device change

---

lang/main-ptBR.json

Adding some more interface translation from main.json, specifically, the participants button, participants pane and virtual background selection dialog window.

Changes to the Brazilian Portuguese translation

---

css/_connection-status.scss
css/_mixins.scss
css/_prejoin.scss
css/_premeeting-screens.scss
css/modals/virtual-background/_virtual-background.scss
react/features/base/responsive-ui/constants.js
react/features/settings/components/web/audio/AudioSettingsPopup.js
react/features/settings/components/web/video/VideoSettingsPopup.js

fix(css) fix various layout issues on small screen sizes

---

react/features/base/config/configWhitelist.js

fix(config) - Exposed preferredCodec

---

react/features/base/participants/functions.js
react/features/base/participants/reducer.js
react/features/conference/components/web/Conference.js
react/features/conference/components/web/ConferenceInfo.js
react/features/e2ee/actionTypes.js
react/features/e2ee/components/AbstractE2EELabel.js
react/features/e2ee/components/E2EESection.js
react/features/e2ee/middleware.js
react/features/e2ee/reducer.js
react/features/participants-pane/components/MeetingParticipantList.js

Stores everyoneSupportsE2EE and everyoneEnabledE2EE to minimize looping through participants list.

feat: Introduces new states for e2ee feature.

---

react/features/av-moderation/functions.js

fix(av-moderation) added optional chaining for moderation enabling

---

modules/API/API.js
modules/API/external/external_api.js

feat(api) expose follow me method

---

config.js

feat: Enable unified plan support for p2p chrome calls.

---

react/features/filmstrip/components/web/ThumbnailWrapper.js

fix(tile-view): when iAmRecorder=true.

---

react/features/stream-effects/virtual-background/JitsiStreamBackgroundEffect.js
react/features/virtual-background/components/VirtualBackgroundDialog.js
react/features/virtual-background/components/VirtualBackgroundPreview.js

fix(virtual-background): Fix mirror behavior for remote participants.

---

react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/WelcomePageSideBar.native.js

fix(settings): imports that break mobile.

---

resources/prosody-plugins/mod_av_moderation_component.lua

fix(av-moderation): Fixes sending wrong whitelist in json.

---

lang/main.json
react/features/shared-video/components/web/AbstractVideoManager.js
react/features/shared-video/components/web/SharedVideoDialog.js
react/features/shared-video/components/web/VideoManager.js
react/features/shared-video/components/web/YoutubeVideoManager.js
react/features/shared-video/functions.js

fix(share-youtube-video): Validate youtube url.

---

lang/main-de.json

Added a missing german translation

Added missing german translation

---

lang/main-zhTW.json

Update Traditional Chinese translation

---

react/features/billing-counter/constants.js
react/features/jaas/actions.web.js

fix(jaas) fix jaas customer details endpoint

---

css/_welcome_page.scss

fix(css) moved to the left moderation text

---

react/features/invite/components/add-people-dialog/web/InviteContactsForm.js

fix(jaas) always hide chrome banner

---

android/gradle.properties
ios/sdk/src/Info.plist

chore(rn): set mobile SDK versions

---

react/features/jaas/middleware.web.js

fix*(jaas) redirect to plan limit page on connection failed

---

react/features/jaas/middleware.web.js

Cherry-pick

---

resources/prosody-plugins/mod_speakerstats_component.lua

fix: Fix speakerstats reports.

---

react/features/external-api/subscriber.js

fix(AOT): participant selection.

---

react/features/stream-effects/virtual-background/JitsiStreamBackgroundEffect.js
react/features/virtual-background/components/VirtualBackgroundDialog.js

fix(virtual-background): Add logs on virtual background actions.

---

react/features/chrome-extension-banner/components/ChromeExtensionBanner.web.js

fix(jaas) hide chrome banner regardless of jwt

---

connection.js
react/features/billing-counter/functions.js
react/features/chrome-extension-banner/components/ChromeExtensionBanner.web.js
react/features/invite/components/add-people-dialog/web/InviteContactsForm.js

fix(jaas) fix vpaas condition

---

react/features/deep-linking/functions.js

fix(jaas) do not deeplink jaas users on default 8x8 app scheme

---

config.js

Add 'participants-pane' option

Update toolbarButtons list

---

modules/API/API.js
modules/API/external/external_api.js
react/features/always-on-top/AlwaysOnTop.js
react/features/base/avatar/components/Avatar.js
react/features/base/avatar/components/web/StatelessAvatar.js
react/features/base/avatar/functions.js
react/features/dynamic-branding/reducer.js

feat(branding): Add custom avatar backgrounds

---

config.js
css/_subject.scss
react/features/base/config/configWhitelist.js
react/features/conference/components/web/ConferenceInfo.js

https://user-images.githubusercontent.com/11474153/126170310-6ddd9584-fecb-4d1f-b88f-f0a989f1db21.mov

fix(recording-label) Make REC label visible at all times

---

config.js
css/_subject.scss
react/features/base/config/configWhitelist.js
react/features/conference/components/web/ConferenceInfo.js

fix(recording-label) Make REC label visible at all times (#9578)

---

react/features/base/util/uri.js

This PR normalises the tenant part of the URL. For example, the following URL
https://jitsi-meet.example.com/something@example.com/something@example.com
is converted to
https://jitsi-meet.example.com/somethingexample.com/somethingexample.com
whereas before it was converted to
https://jitsi-meet.example.com/something@example.com/somethingexample.com
i.e. the tenant part was not normalised

fix: Normalize the tenant part of the URL.

---

config.js
css/_reactions-menu.scss
react/features/base/flags/constants.js
react/features/toolbox/components/native/OverflowMenu.js
react/features/toolbox/components/native/RaiseHandButton.js
react/features/toolbox/components/native/Toolbox.js
react/features/toolbox/components/web/RaiseHandButton.js
react/features/toolbox/components/web/Toolbox.js

fix(reactions) Moved reactions behind feature flag

---

react/features/toolbox/components/web/ShareDesktopButton.js

fix(ShareDesktopButton): getParticipants reference

---

react/features/toolbox/components/web/Toolbox.js
react/features/toolbox/constants.js

fix(toolbar-buttons) Attempt fix Meet in integration

---

react/features/base/config/constants.js
react/features/toolbox/components/web/ToggleCameraButton.js
react/features/toolbox/components/web/Toolbox.js

fix(toolbox) add back toggle camera button

---

react/features/base/config/constants.js
react/features/toolbox/components/web/ToggleCameraButton.js
react/features/toolbox/components/web/Toolbox.js
react/features/toolbox/constants.js

Release 5152 hf

---

react/features/toolbox/components/web/ShareDesktopButton.js

fix(ShareDesktopButton): typo.

---

react/features/video-menu/actions.any.js

feat(participants-pane) removed getIsParticipantAudioMuted

---

lang/main.json
react/features/recording/components/Recording/AbstractStartRecordingDialog.js

fix(dropbox-recording) Prevent start recording when no dropbox token

---

android/sdk/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
android/settings.gradle
react/features/participants-pane/components/native/MeetingParticipantList.js
react/features/toolbox/components/native/OverflowMenu.js
react/features/toolbox/components/native/Toolbox.js
react/features/toolbox/functions.native.js
react/features/video-menu/components/native/VolumeSlider.js

1.  Fixed react native community slider to work on both android and ios
2. Removed InviteButton from native menus
3. Fixed buttons spacing in native OverflowMenu
4. Participant context menu details are shown only for remote participants

feat(participants-pane) updates

---

ios/sdk/src/JitsiMeet.h
ios/sdk/src/JitsiMeet.m
ios/sdk/src/JitsiMeetView.m

support for instantiating & destroying the rn bridge

---

ios/sdk/src/JitsiMeet.m

fix interface

---

react/features/participants-pane/components/native/LobbyParticipantList.js
react/features/participants-pane/components/native/ParticipantsPane.js
react/features/participants-pane/components/native/styles.js
react/features/participants-pane/components/web/LobbyParticipantList.js

1. Fixed admitMultiple action for mobile
2. Added token color for button
3. Hide Admit all button if less than 2 knocking participants

fix(participants-pane) admitMultiple action on mobile

---

ios/sdk/src/JitsiMeet.h
ios/sdk/src/JitsiMeet.m

fix(jaas) support for destroying & reinitializing the react native bridge

---

react/features/device-selection/functions.js

fix(external-api): persist audio output device

---

lang/main.json
react/features/participants-pane/components/native/ParticipantsPane.js
react/features/participants-pane/components/native/styles.js

Replaced header with JitsiModal standard header

feat(participants-pane) changed to standard header

---

config.js

fix(config.js) commented out enableReactions

---

ios/Podfile.lock
package-lock.json
package.json

deps(rn) update WebRTC to M92

---

react/features/toolbox/components/native/OverflowMenu.js
react/features/toolbox/components/web/Toolbox.js

1. Updated order for menu items on mobile and desktop
2. Added dividers for mobile overflow menu

feat(toolbox) updated menu items order, dividers for mobile

---

react/features/base/tracks/actions.js

fix(notifications) Fix hiding audio/video lost notification

---

react/features/conference/components/web/ConferenceInfo.js

This is only a quick fix, a big refactor on the conference info labels is coming up.

fix(recording-label) fix recording label behavior

---

react/features/video-quality/subscriber.js

The concept of "visible participants" is not yet implemented.

fix(rn,video-quality) fix not selecting any endpoint on mobile

---

logging_config.js

Plan is to make the Strophe logs more restrictive.
Revert "fix(logging) reduce overly vebose logging"
This reverts commit 09af88088ded3ab5e8343f6ebedeffc8d752f95f.

fix(logging): Set the log level to debug again.

---

resources/prosody-plugins/mod_limits_exception.lua

https://github.com/jitsi/jitsi-meet/blob/c5c4449fbcdfc26b372539aeeabb3fcc882ad131/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L24

feat: Rises the stanza limit for unlimited jids (jicofo).

---

lang/main-pt.json

update portuguese translation

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java
config.js
ios/sdk/src/JitsiMeetConferenceOptions.h
ios/sdk/src/JitsiMeetConferenceOptions.m

task(mobile): add configOverride to ConferenceOptions

---

react/features/notifications/components/web/NotificationButton.js
react/features/notifications/components/web/NotificationWithParticipants.js
react/features/participants-pane/components/AskToUnmuteButton.js
react/features/participants-pane/components/FooterContextMenu.js
react/features/participants-pane/components/ParticipantQuickAction.js
react/features/participants-pane/components/web/MeetingParticipantItem.js
react/features/participants-pane/components/web/ParticipantItem.js

feat(av-moderation) id and aria-label updates for av-moderation test

---

react/features/stream-effects/audio-mixer/AudioMixerEffect.js
react/features/toolbox/components/web/ShareDesktopButton.js

fix(screen-share): never mute audio screen share track

---

config.js
react/features/base/config/configWhitelist.js

feat(callstats) Add `callStatsConfigParams` config

---

react/features/polls/components/native/PollsList.js

fix(rn): import React from react package

---

react/features/filmstrip/components/web/Thumbnail.js
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.js
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.js

fix(video-menu) fixed thumbnail menu position for horizontal filmstrip view

---

react/features/welcome/components/WelcomePageSideBar.native.js
react/features/welcome/components/styles.js

This happens when I have the Arabic language (an rtl one) in my system settings.
https://user-images.githubusercontent.com/40805353/128845460-fb2d66f5-2f84-47a3-ae5a-40a63369e71c.mp4

Fix `sideBar` not appearing on rtl languages.

---

react/features/base/conference/functions.js
react/features/base/config/functions.native.js

Fixes an error `Cannot convert undefined or null to object` on load.

fix: Fixes an error with configuration without analytics.

---

react/features/shared-video/components/AbstractSharedVideoDialog.js

fix(share-video) fix links not being trimmed

---

react/features/base/participants/functions.js
react/features/base/participants/reducer.js
react/features/lobby/components/AbstractKnockingParticipantList.js
react/features/lobby/functions.js
react/features/participants-pane/components/native/LobbyParticipantList.js
react/features/participants-pane/components/native/MeetingParticipantList.js
react/features/participants-pane/components/web/LobbyParticipantList.js
react/features/participants-pane/components/web/MeetingParticipantList.js

fix(participants) sort participants alphabetically

---

react/features/participants-pane/components/ParticipantsPaneButton.js

fix(participants-pane) fixed participants pane button toggled state

---

css/_lobby.scss

Empty list with border is showing 2px dot.

fix: Fixes dot shown left of logo.

---

react/features/participants-pane/components/web/ParticipantItem.js
react/features/participants-pane/components/web/styled.js

fix(moderation) hide status icons on hover

---

config.js
react/features/base/config/functions.any.js

feat(xmpp) remove clientNode config option

---

css/_e2ee.scss
lang/main.json
react/features/e2ee/components/E2EESection.js
react/features/e2ee/functions.js

Fixes for https://github.com/jitsi/jitsi-meet/issues/9659

E2EE section fixes

---

connection.js
react/features/jaas/actions.any.js
react/features/jaas/actions.web.js
react/features/jaas/functions.js
react/features/jaas/middleware.web.js

fix(jaas) do not redirect to plan limit page on auth errors

---

android/gradle.properties
ios/app/broadcast-extension/Info.plist
ios/app/src/Info.plist
ios/app/watchos/app/Info.plist
ios/app/watchos/extension/Info.plist
ios/sdk/src/Info.plist

chore(rn,versions) bump app and sdk versions

---

android/sdk/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
android/settings.gradle
ios/Podfile
ios/Podfile.lock
ios/sdk/sdk.xcodeproj/project.pbxproj
package-lock.json
package.json
react/features/analytics/handlers/AmplitudeHandler.js
react/features/analytics/handlers/amplitude/index.js
react/features/analytics/handlers/amplitude/lib.native.js
react/features/analytics/handlers/amplitude/lib.web.js

Amplitude has gone back to having a separate package for RN, so switch to it.

fix(rn,amplitude) update Amplitude SDK on RN

---

css/_drawer.scss

fix(drawer-menu) Allow scroll on drawer menu items

---

react/features/base/participants/middleware.js
react/features/participants-pane/components/FooterContextMenu.js
react/features/participants-pane/components/web/MeetingParticipantContextMenu.js
react/features/participants-pane/components/web/MeetingParticipantItem.js
react/features/participants-pane/components/web/ParticipantsPane.js
react/features/participants-pane/functions.js
resources/prosody-plugins/mod_av_moderation_component.lua

Enables it for alone call, p2p call and even when everyone is a moderator.

AV moderation updates

---

index.html

Fixes: https://github.com/jitsi/jitsi-meet/issues/9712

fix(iframe) don't register service worker when in an iframe

---

react/features/base/devices/middleware.js
react/features/notifications/actions.js

fix(notifications) Add timeout for video/audio lost notifs

---

react/features/authentication/components/web/LoginDialog.js
react/features/authentication/components/web/WaitForOwnerDialog.js

fix(authentication) fixed cancel on authentication dialogs

---

react/features/filmstrip/actions.any.js
react/features/filmstrip/actions.native.js
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/native/Thumbnail.js
react/features/filmstrip/functions.any.js
react/features/filmstrip/functions.native.js
react/features/filmstrip/functions.web.js
react/features/filmstrip/middleware.native.js
react/features/filmstrip/middleware.web.js
react/features/filmstrip/reducer.js
react/features/filmstrip/subscriber.any.js
react/features/filmstrip/subscriber.native.js
react/features/filmstrip/subscriber.web.js

fix(TileView): not showing all participants.

---

config.js
react/features/base/config/configWhitelist.js
react/features/base/config/constants.js
react/features/base/premeeting/components/web/PreMeetingScreen.js
react/features/prejoin/components/PrejoinThirdParty.js

fix(pre-meeting) Hide invite button for JaaS

---

modules/API/API.js
modules/API/external/external_api.js
react/features/overlay/middleware.js

feat(errors) Expose errors through Iframe API

---

react/features/base/flags/constants.js
react/features/toolbox/components/native/OverflowMenu.js

fix(rn) enable reactions by default

---

react/features/chat/components/web/ChatMessage.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/9661

fix(chat) avoid emojifying URLs

---

react/features/base/config/configWhitelist.js

fix(config) add enableReactions to whitelist

---

react/features/base/conference/middleware.any.js
react/features/base/responsive-ui/actions.js
react/features/filmstrip/actions.any.js
react/features/filmstrip/actions.native.js
react/features/filmstrip/actions.web.js
react/features/filmstrip/components/native/Filmstrip.js
react/features/filmstrip/components/native/Thumbnail.js
react/features/filmstrip/components/native/TileView.js
react/features/filmstrip/components/native/styles.js
react/features/filmstrip/components/web/ThumbnailWrapper.js
react/features/filmstrip/constants.js
react/features/filmstrip/functions.native.js
react/features/filmstrip/middleware.native.js
react/features/filmstrip/reducer.js
react/features/filmstrip/subscriber.native.js
react/features/invite/functions.js
react/features/video-menu/components/native/RemoteVideoMenu.js
react/features/video-menu/components/native/SharedVideoMenu.js
react/features/video-quality/subscriber.js

feat(filmstrip-pagination): mobile support.

---

react/features/participants-pane/components/web/MeetingParticipantList.js

fix(toolbar-buttons) Hide/show invite button based on toolbarButtons

---

ios/Podfile.lock
package-lock.json
package.json

Fixes several Android crashes.

chore(rn,deps) react-native-webrtc@1.92.1

---

modules/API/constants.js
react/features/base/participants/middleware.js
react/features/chat/middleware.js
react/features/reactions/components/web/ReactionsMenu.js
react/features/reactions/constants.js
react/features/reactions/functions.any.js
react/features/reactions/middleware.js
react/features/toolbox/components/native/OverflowMenu.js
react/features/toolbox/components/native/Toolbox.js
react/features/toolbox/components/web/Toolbox.js

Also disabled reactions on native because of an issue with iOS that causes the data channel to be disabled even if there are multiple participants in the conference

fix(reactions) Fix reactions bugs

---

package-lock.json
package.json
react/features/dropbox/actions.js
react/features/dropbox/functions.native.js
react/features/dropbox/functions.web.js
react/features/dropbox/reducer.js
react/features/recording/components/Recording/AbstractStartRecordingDialog.js

chore(dropbox-web) Accommodate short-lived access token

---

react/features/toolbox/components/web/Toolbox.js

fix(toolbox) fix warning due to missing key prop

---

react/features/filmstrip/components/native/Thumbnail.js

fix(rn,humbnail) add key prop to array items

---

react/features/video-layout/functions.js

interfaceConfig does not exist.

fix(video-layout) fix getMaxColumnCount on mobile

---

react/features/notifications/middleware.js

fix(notifications) skip participant joined notifications before we join

---

react/features/base/lastn/middleware.js
react/features/base/logging/reducer.js
react/features/mobile/external-api/middleware.js

This combined yielded ~20% speed improvement on my device.

Improve join performance on mobile

---

react/features/participants-pane/actions.native.js
react/features/participants-pane/components/native/LobbyParticipantList.js
react/features/participants-pane/components/native/MeetingParticipantItem.js
react/features/participants-pane/components/native/MeetingParticipantList.js
react/features/participants-pane/components/native/ParticipantsPane.js

- Fix onPress action for remote meeting participants.
- Use FlatList for the meeting participant.
- Use the order participant order implemented for the filmstrip for ParticipantPane.

fix(ParticipantPane-mobile): Optimize.

---

ios/Podfile
ios/Podfile.lock
ios/app/app.xcodeproj/project.pbxproj
ios/sdk/src/dropbox/Dropbox.m

task(iOS): update dropbox authentication to PKCE flow

---

lang/main.json
react/features/notifications/actions.js
react/features/notifications/constants.js

Refine join notifications for large meetings

---

react/features/base/config/configWhitelist.js

chore(config): Whitelist `disableRecordAudioNotification` config

---

android/sdk/build.gradle
android/settings.gradle

fix(android): renames amplitudereactnative project

---

android/gradle.properties

task(android): updates sdk version

---

react/features/rtcstats/RTCStats.js
react/features/rtcstats/functions.js
react/features/rtcstats/middleware.js

feat(rtcstats): send dominant speaker stats

---

css/premeeting/_prejoin-third-party.scss

fix(prejoin) Fix buttons positioning for 3rd party

---

config.js
package-lock.json
package.json

fix(config) Add more info about enableLayerSuspension option.

---

android/sdk/build.gradle
android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java
android/settings.gradle
ios/Podfile
ios/Podfile.lock
package-lock.json
package.json
react/features/mobile/polyfills/browser.js

Implements: https://developer.mozilla.org/en-US/docs/Web/API/Performance
Ref: https://github.com/oblador/react-native-performance

feat(rn) add polyfill for the performance API

---

config.js
interface_config.js
react/features/base/config/configWhitelist.js
react/features/base/config/reducer.js
react/features/connection-indicator/components/AbstractConnectionIndicator.js
react/features/connection-indicator/components/web/ConnectionIndicator.js
react/features/filmstrip/components/web/Thumbnail.js

feat(config): Add connection indicators flags.

---

config.js

Added missing user join notifications keys in config.
Fix to https://github.com/jitsi/jitsi-meet/issues/9825

fix(notifications): Added user join notification keys

---

config.js
react/features/base/config/configWhitelist.js
react/features/chat/components/web/ChatInput.js
react/features/chat/functions.js

This is an implementation of Add configuration to disable chat emoticons (smileys) #9889

Add configuration to disable chat emoticons

---

react/features/invite/components/add-people-dialog/native/AddPeopleDialog.js
react/features/shared-video/components/native/SharedVideoDialog.js

fix(rn,shared-video) fix placehoolder text color to be visible

---

react/features/base/popover/components/Popover.web.js
react/features/toolbox/actions.web.js
react/features/toolbox/functions.web.js
react/features/video-menu/components/web/LocalVideoMenuTriggerButton.js
react/features/video-menu/components/web/RemoteVideoMenuTriggerButton.js

- hide toolbars only when in tile view
- fix community issue: https://github.com/jitsi/jitsi-meet/issues/9818

fix(context-menu) Hide toolbars when participant context menu opened

---

android/sdk/src/main/java/org/jitsi/meet/sdk/NotificationChannels.java
android/sdk/src/main/java/org/jitsi/meet/sdk/OngoingNotification.java

task(android): expose channels ids

---

android/sdk/src/main/java/org/jitsi/meet/sdk/DropboxModule.java
react/features/dropbox/actions.js
react/features/dropbox/functions.native.js

fix(rn): disable pip while authorising dropbox

---

lang/main.json
react/features/conference/components/native/LonelyMeetingExperience.js
react/features/shared-video/components/AbstractSharedVideoDialog.js
react/features/shared-video/components/native/SharedVideoDialog.js
react/features/shared-video/components/web/SharedVideoDialog.js
react/features/shared-video/constants.js

See each individual commit for details.

Shared video fixes

---

react/features/conference/components/native/NavigationBar.js
react/features/conference/components/native/styles.js

feat(rn,conference) show invite button on the top navbar

---

conference.js
react/features/base/conference/actions.js

fix(conference.js): add tracks to the conference

---

react/features/toolbox/components/web/Toolbox.js

fix(toolbox) fix crash

---

react/features/filmstrip/middleware.native.js

fix(filmstrip) Fix filmstrip on RN when thumbnail reordering is disabled.

---

react/features/filmstrip/components/web/Filmstrip.js

fix(Filmstrip): scroll

---

lang/main.json
react/features/av-moderation/actions.js
react/features/participants-pane/components/web/MeetingParticipantItem.js

When the user is allowed audio but not video display Allow Video button instead of Ask to Unmute

fix(av-moderation) Display Allow Video instead of Ask to Unmute

---

react/features/video-menu/components/AbstractMuteEveryoneDialog.js
react/features/video-menu/components/AbstractMuteEveryonesVideoDialog.js

Mute everyone else no longer disables moderation

fix(av-moderation) - Mute/ stop video except no longer change moderation status

---

react/features/participants-pane/components/web/LobbyParticipantItem.js

It got accidentally removed in:
https://github.com/jitsi/jitsi-meet/commit/1dc8bfa63124a868c36bfa12077132204801454b#diff-ef66b8ab7c899b16d6c1102b3c812aa45509f95e11267cbfdbd0674143e94575

fix(participants-pane) bring back lobby reject button

---

react/features/base/participants/middleware.js

fix(rn) add default value when retrieving e2ee redux state

---

lang/main-oc.json

Update occitan locale

---

css/_chat.scss

Based on this suggestion https://github.com/jitsi/jitsi-meet/issues/9958

fix(chat): Hide scroll bar on chat input

---

config.js
interface_config.js
react/features/base/config/configWhitelist.js
react/features/base/config/reducer.js
react/features/toolbox/actionTypes.js
react/features/toolbox/actions.any.js
react/features/toolbox/actions.native.js
react/features/toolbox/actions.web.js
react/features/toolbox/constants.js
react/features/toolbox/functions.native.js
react/features/toolbox/functions.web.js
react/features/toolbox/reducer.js

- Deprecate `INITIAL_TOOLBAR_TIMEOUT`, `TOOLBAR_ALWAYS_VISIBLE`, `TOOLBAR_TIMEOUT`

fix(toolbar) Fix toolbar always visible; refactors

---

react/features/speaker-stats/actions.js
react/features/speaker-stats/components/SpeakerStats.js
react/features/speaker-stats/functions.js
react/features/speaker-stats/reducer.js

Fixes search bugs when removing characters.

Speaker stats search fix #9751

---

lang/main-fr.json

Update french translation for the participants pane actions.

fix(lang) update french translation

---

react/features/participants-pane/components/native/MeetingParticipantItem.js
react/features/participants-pane/components/native/ParticipantItem.js
react/features/participants-pane/components/web/MeetingParticipantContextMenu.js
react/features/participants-pane/components/web/MeetingParticipantItem.js
react/features/participants-pane/components/web/ParticipantItem.js

Hide moderator label on disasbleModeratorIndicator
- On disasbleModeratorIndicator config hide moderator label from participants pane
Add Ask to Unmute button to mobile web

fix(av-moderation) Improve advanced moderation

---

android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java

fix(android) removes unnecessary parcel processing

---

lang/main-oc.json

It's now 100% :D 
Happy to have caught up.
Looking forward to using the next release.

i18n update Occitan

---

android/app/src/main/AndroidManifest.xml
android/gradle.properties

fix(android) disables uncompressed native libs usage

---

react/features/invite/components/add-people-dialog/web/InviteContactsForm.js

fix(invite) fix video rooms not being displayed in invite search

---

react/features/speaker-stats/components/SpeakerStats.js
react/features/speaker-stats/functions.js
react/features/speaker-stats/reducer.js

Fix speaker stats search dependency and remove duplicate logic.

Fix speaker stats search dependency and remove duplicate logic #9751

---

package-lock.json
package.json

feat(rtcstats): remove SDP transmission

---

conference.js
react/features/prejoin/actionTypes.js
react/features/prejoin/actions.js
react/features/prejoin/middleware.js
react/features/prejoin/reducer.js

Prejoin screen issues

---

react/features/lobby/components/AbstractLobbyScreen.js

fix: Fixes #9869 Lobby and wrong password case.

---

android/sdk/src/main/java/org/jitsi/meet/sdk/NotificationChannels.java
android/sdk/src/main/java/org/jitsi/meet/sdk/OngoingNotification.java
android/sdk/src/main/res/values/strings.xml

feat(android) extract notification channel name

---

react/features/participants-pane/components/ParticipantQuickAction.js
react/features/participants-pane/components/web/MeetingParticipantItem.js
react/features/video-menu/components/AbstractMuteEveryoneDialog.js
react/features/video-menu/components/AbstractMuteEveryonesVideoDialog.js
react/features/video-menu/components/web/MuteEveryoneDialog.js
react/features/video-menu/components/web/MuteEveryonesVideoDialog.js

Show av moderation toggles on mute all / stop everyone's video dialogs only if moderation is supported
Show Ask to Unmute only for moderators and if moderation is supported

fix(av-moderation) Check for moderation support

---

react/features/transcribing/functions.js

fix: Skips setting language for transcriptions if not enabled.

---

react/features/participants-pane/components/ParticipantQuickAction.js
react/features/participants-pane/components/web/MeetingParticipantItem.js
react/features/video-menu/components/web/MuteVideoButton.js

Show Mute button instead of always showing Ask to Unmute
Added aria-label

fix(av-moderation) Show Mute button when participant is unmuted

---

resources/prosody-plugins/mod_auth_token.lua
resources/prosody-plugins/util.lib.lua

call module that checks the jwt against the access service

---

android/gradle.properties

chore(versions) bump Android SDK version

---

debian/jitsi-meet-prosody.postinst

fix: Fixes upgrading component to muc prosody config.

---

react/features/video-quality/components/Slider.js

fix(Slider): Fix slider appearance on Firefox

---

css/_polls.scss
lang/main.json
react/features/base/util/hooks.js
react/features/polls/components/AbstractPollAnswer.js
react/features/polls/components/AbstractPollResults.js
react/features/polls/components/web/PollAnswer.js
react/features/polls/components/web/PollResults.js

feat(Polls): Display creator name for polls

---

modules/API/API.js
modules/API/external/external_api.js
react/features/recording/actions.any.js

feat(external-api): Add recording download link available event (#10229)

---

lang/main-fr.json

I have sgned the CLA with this [PR](https://github.com/jitsi/jitsi-meet/pull/8728#issuecomment-790589534)

(Lang) update french translation

---

resources/prosody-plugins/mod_polls.lua

trigger events for poll created and answered

---

resources/prosody-plugins/mod_polls.lua

feat(polls) fix spacing and send answer identifier

---

lang/main-ca.json

Lobby functionality has not been localized yet to Catalan. This add catalan localization for lobby functionality

fix(lang): adding lobby transalations to Catalan

---

lang/main-pt.json

Shorten text size for better viewing
**Before**
**After**

Fix portuguese translation of "highestQuality"

---

conference.js
react/features/base/tracks/middleware.js

Update to latest lib-jitsi-meet

fix(tracks) Use duration from JitsiTrack

---

react/features/base/participants/reducer.js

fix(raise-hand): Remove participant left from raised hand queue

---

resources/prosody-plugins/mod_muc_lobby_rooms.lua

feat: Filters moderators presence in lobby room.

---

package-lock.json
package.json
react/features/connection-indicator/components/web/ConnectionIndicator.js

Eslint8 followup

---

modules/UI/util/MessageHandler.js

chore(tech-debt) remove dead code

---

modules/devices/mediaDeviceHelper.js
react/features/prejoin/actions.js

Fix safari audio issues.

---

react/features/dynamic-branding/actions.js
react/features/dynamic-branding/functions.any.js
react/features/dynamic-branding/functions.web.js
react/features/dynamic-branding/index.js
react/features/dynamic-branding/middleware.web.js
react/features/feedback/actions.js
react/features/invite/components/add-people-dialog/web/AddPeopleDialog.js
react/features/reactions/functions.any.js
react/features/screenshot-capture/ScreenshotCaptureSummary.js

fix(dynamic-branding) Fix bogus mUI dependency on mobile

---

react/features/toolbox/components/web/Toolbox.js

fix(toolbox): enable fullscreen button on mobile browsers

---

package-lock.json
package.json

chore(deps): update rtcstats 9.0.1

---

react/features/toolbox/components/web/Toolbox.js

fix(notify-button-clicked) Fix crash on mobile browsers

---

react/features/facial-recognition/resources/README.md

Add licence info about facial models in the resources folder.

add(facial-expressions): licence info about facial models 

---

package-lock.json
package.json

Reverts changes added with previous ljm update and limits the scope of
this update to commits contained on the ljm release branch

chore(deps) lib-jitsi-meet@latest(release)

---

react/features/video-menu/components/native/RemoteVideoMenu.js

fix(rn,remote-video-menu) fix import after refactor

---

Makefile
config.js
react/features/base/config/configWhitelist.js

Fixup face dev

---

react/features/video-quality/subscriber.js

feat(video-quality): Always prioritize SS in tile view.

---

lang/main-oc.json

I signed the thing that will automatically pop up after my Pull Request ^^

More strings translated into Occitan

---

react/features/prejoin/components/PrejoinApp.js

fix(prejoin) Fix prejoin app

---

react/features/base/settings/middleware.js
react/features/welcome/components/WelcomePage.native.js

We are no longer rendering it, so skip creating it altogether and make sure it's
destroyed on meeting end.

fix(rn,welcome-page) don't create video track unnecessarily

---

react/features/base/ui/Tokens.js
react/features/base/ui/components/BaseTheme.native.js
react/features/base/ui/components/updateTheme.js

feat(ui) updateTheme helper for mobile client branding

---

config.js

https://github.com/jitsi/jitsi-meet/blob/f51e65d12946ff33b31f5c42db00a83819f0829d/react/features/rtcstats/functions.js#L22

fix: Updates the default value of rtcstatsEnabled to match the code.

---

react/features/filmstrip/components/web/Thumbnail.js

fix(filmstrip) remove border from filmstrip

---

android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastEvent.java

fix(android) fixes error in BroadcastEvent

---

resources/prosody-plugins/mod_muc_breakout_rooms.lua

Fixup breakout rooms

---

lang/main-ca.json

Adding transalations for Catalan:
- Participans Pane:
- Toolbar 
- Video Thmbnail

lang: adding translations for Catalan

---

resources/load-test/load-test-participant.js

feat(load-test): Unmute video.

---

lang/main-de.json

fix(lang) update German translation

---

ios/Podfile.lock
package-lock.json
package.json

chore(rn,deps) react-native-webrtc@1.94.0

---

react/features/base/config/configWhitelist.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/10326

fix(config) add transcribingEnabled to whitelist

---

react/features/base/ui/Tokens.js
react/features/conference/components/native/Conference.js
react/features/conference/components/native/styles.js
react/features/invite/components/add-people-dialog/native/InviteButton.js
react/features/toolbox/components/native/styles.js

1. Updated icons.
2. Updated width and height for button icons.
3. Updated background color for navigation bar and toolbox.

feat(conference) UI updates for mobile navigation bar

---

package.json
react/features/base/tracks/reducer.js
react/features/remote-control/constants.js
react/features/speaker-stats/components/web/SpeakerStats.js
react/features/virtual-background/actions.js

Tame eslint

---

react/features/rtcstats/RTCStats.js
react/features/rtcstats/middleware.js

feat(rtcstats): send facial expressions to rtcstats-server

---

resources/prosody-plugins/mod_muc_breakout_rooms.lua

Fix not being able to create / remove breakout rooms when the moderator is
inside a breakout room.

fix(breakout-rooms) fix operations when inside a breakout room

---

react/features/welcome/components/settings/components/SettingsView.js

It;';s not implemented on iOS.

fix(rn,settings) only show "disable call integration" on Android

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example

feat: Enables muc rate limit for lobby and breakout muc components.

---

config.js
react/features/base/conference/middleware.any.js
react/features/base/config/configWhitelist.js
react/features/external-api/middleware.js
react/index.web.js

Depends on https://github.com/jitsi/lib-jitsi-meet/pull/1803

Disable-beforeunload

---

conference.js
react/features/breakout-rooms/actions.js
react/features/lobby/components/web/LobbySection.js
react/features/recording/components/LiveStream/AbstractLiveStreamButton.js
react/features/recording/components/Recording/AbstractRecordButton.js
react/features/security/components/security-dialog/native/SecurityDialog.js
react/features/video-layout/middleware.web.js

More breakout rooms fixes

---

react/features/lobby/middleware.js

fix: Fixes correct state in lobby screen on wrong password.

---

react/features/base/avatar/components/web/StatelessAvatar.js
react/features/base/avatar/constants.js
react/features/base/avatar/functions.js
react/features/base/avatar/index.js
react/features/base/participants/functions.js
react/features/base/participants/preloadImage.web.js

In cross origin issolated mode we need to explicitly add crossOrigin
attribute for all resources that are loaded with CORS headers

Gravatar CORS

---

resources/prosody-plugins/mod_muc_breakout_rooms.lua

fix(breakout-rooms) fix when using tenants

---

react/features/base/participants/reducer.js

fix(participants) fix unpinning when switching conferences

---

lang/main-oc.json

fix(lang) update Occitan translation

---

react/features/large-video/actions.any.js
react/features/large-video/middleware.js

Fixes: https://github.com/jitsi/jitsi-meet/issues/8109

fix(therpad) fix Etherpad closing when dominant speaker changes

---

react/features/dropbox/functions.web.js
static/oauth.html

Fix-dropbox-oauth

---

react/features/base/flags/constants.js
react/features/speaker-stats/components/AbstractSpeakerStatsList.js
react/features/speaker-stats/components/native/SpeakerStatsButton.js
react/features/speaker-stats/components/native/SpeakerStatsItem.js
react/features/speaker-stats/components/native/SpeakerStatsList.js
react/features/speaker-stats/components/web/SpeakerStatsItem.js
react/features/speaker-stats/constants.js
react/features/toolbox/components/web/Toolbox.js

fix auto refresh of speaker stats on mobile and web
minor refactoring

feat: (speaker-stats) fix refresh and minor refactoring

---

react/features/breakout-rooms/actions.js
react/features/mobile/external-api/middleware.js

Just like on web, we wait for the current room to be left in order to avoid all
kinds of problems.

fix(rn,breakout-rooms) wait for the room to be left

---

lang/main-fr.json

additional messages missing from recent changes +
fix: spellnig error
fix:  incertain translation.
CLA signed with this [PR](https://github.com/jitsi/jitsi-meet/pull/8728#issuecomment-790589534)

fix(lang) update french translation + fix 2 existing translations

---

conference.js

Not all code paths return a Promise, make sure it does.

fix(breakout-rooms) mark function as async

---

lang/main.json
react/features/breakout-rooms/actions.js

feat(breakout-rooms) add notification when joining rooms

---

react/features/breakout-rooms/actions.js

We need to wait for it before we start joining.

fix(breakout-rooms) fix not waiting to leave the room

---

modules/API/API.js
react/features/recording/actions.any.js
react/features/recording/functions.js

Include ttl enhancement in the next release.

feat(external-api): enhance recordingLinkAvailable to provide ttl info

---

conference.js
react/features/base/conference/actions.js
react/features/base/media/middleware.js
react/features/base/media/reducer.js
react/features/toolbox/functions.any.js
react/features/toolbox/functions.native.js
react/features/toolbox/functions.web.js

This fixes an issue where the user muted by focus is able to unmute themselves even when the sender limit has been reached.

fix(media) dispatch the unmute blocked action irrepective of the muted state.

---

react/features/facial-recognition/actions.js
react/features/facial-recognition/facialExpressionsWorker.js
react/features/facial-recognition/middleware.js

Load the facial expression worker code as a blob and then use its URL for creating the worker.

fix(facial-expressions): load worker as a blob

---

config.js
react/features/base/config/configWhitelist.js
react/features/base/config/reducer.js
react/features/prejoin/components/DropdownButton.js
react/features/prejoin/components/Prejoin.js
react/features/prejoin/components/PrejoinApp.js
react/features/prejoin/functions.js
react/features/settings/functions.js

- fix line height issue on extra join options buttons
- small refactor

feat(prejoin) Add possibility to hide extra join options buttons

---

lang/main-sv.json

Correction of missing letter in translation and order of translations in "polls".

(fix) update main-sv.json

---

lang/main.json
react/features/stream-effects/virtual-background/index.js

If another try is made, show an error notification instead of failing with an
exception.

fix(virtual-backgrounds) fix error if we failed to load the model

---

conference.js
modules/API/API.js
react/features/recording/components/Recording/AbstractStartRecordingDialog.js
react/features/recording/components/Recording/AbstractStopRecordingDialog.js
react/features/screenshot-capture/ScreenshotCaptureSummary.js
react/features/screenshot-capture/constants.js
react/features/screenshot-capture/functions.js

Add participants jid list to request
Enable screenshot capture only when recording is also on

fix(screenshot-capture) Update screenshot capture feature

---

react/features/base/tracks/middleware.js

fix(breakout-rooms) cleanup remote tracks when a conference is left

---

react/features/recording/components/Recording/AbstractStartRecordingDialog.js
react/features/recording/components/Recording/AbstractStopRecordingDialog.js
react/features/recording/components/Recording/web/StartRecordingDialog.js
react/features/recording/components/Recording/web/StopRecordingDialog.js

fix(screenshot-capture) Use feature on web only

---

android/app/proguard-rules.pro

Fixes: https://github.com/jitsi/jitsi-meet/issues/10182

fix(android) fix NoClassDefFoundError for Landroid/graphics/ColorSpace

---

react/features/app/middlewares.web.js
react/features/notifications/middleware.any.js
react/features/notifications/middleware.native.js
react/features/notifications/middleware.web.js

fix(notifications) Create web middleware

---

lang/main-ca.json

Adding translations for Virtual Background functionality in  Catalan

lang(virtual-background:)  Catalan

---

react/features/base/modal/components/JitsiKeyboardAvoidingView.js
react/features/base/modal/components/JitsiScreen.js
react/features/chat/components/native/Chat.js

1. Fixed JitsiKeyboardAvoidingView not working on some android devices

feat(chat) keyboard covering input on android fix

---

react/features/base/tracks/middleware.js

fix(breakout-rooms) cleanup local tracks when a conference is left.

---

react/features/base/media/middleware.js
react/features/toolbox/components/AudioMuteButton.js
react/features/toolbox/components/VideoMuteButton.js

Ignore keyboard shortcuts when the buttons are disabled

---

react/features/breakout-rooms/components/native/CollapsibleRoom.js

fix(rn,breakout-rooms) fix not rendering display names

---

react/features/filmstrip/components/native/Filmstrip.js
react/features/filmstrip/components/native/TileView.js
react/features/filmstrip/components/web/Filmstrip.js

Fix issue where the last participant is shown as inactive when the self-view is hidden

fix(disableSelfView) Fix issue with remote participant video

---

react/features/breakout-rooms/actions.js

fix(rn,breakout-rooms) create desired local tracks when joining rooms

---

conference.js
react/features/breakout-rooms/actions.js

Only audio and video are considered. Screen sharing won't be preserved.

fix(breakout-rooms) ensure we use the same media types when joining

---

lang/main.json
react/features/base/media/middleware.js
react/features/toolbox/components/web/ShareDesktopButton.js

feat(media) Disable desktopshare when the video sender limit is reached.

---

react/features/base/media/middleware.js

Importing the entire feature triggers web UI imports.

fix(rn) fix broken mobile build

---

react/features/polls/components/AbstractPollResults.js

Percentage was previously calculated based on number of voters

fix(Polls): Calculate vote percentage based on total number of votes

---

config.js
css/modals/settings/_settings.scss
react/features/base/config/configWhitelist.js
react/features/settings/components/web/ProfileTab.js
react/features/settings/functions.js

feat(profile-settings): Hide email field under profile settings

---

config.js

fix(config.js) Added missing participant left notification key.

---

resources/prosody-plugins/mod_muc_breakout_rooms.lua

By the time the timer is fired the room maybe recreated (destroyed and created again) and we do not want to destroy it again. The timer was keeping a reference to the old room and is destroying it without notifying the future occupants(jicofo).
Drop save, as we do not need it before destroying, check lobby.

fix: Fixes destroying main room when breakout rooms are enabled.

---

lang/main-es.json

Fixing wrong use of the verb toggle.

minor main-es.json fix

---

resources/prosody-plugins/mod_muc_breakout_rooms.lua

fix(breakout-rooms): Adds a check for missing room.

---

doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example
react/features/polls/actionTypes.js
react/features/polls/actions.js
react/features/polls/reducer.js
react/features/polls/subscriber.js

fix(breakout-rooms): Fix polls usage.

---

config.js
react/features/base/avatar/components/AbstractStatelessAvatar.js
react/features/base/avatar/components/Avatar.js
react/features/base/avatar/components/native/StatelessAvatar.js
react/features/base/avatar/components/web/StatelessAvatar.js
react/features/base/avatar/functions.js
react/features/base/participants/actions.js
react/features/base/participants/functions.js
react/features/base/participants/middleware.js
react/features/base/participants/preloadImage.native.js
react/features/base/participants/preloadImage.web.js
react/features/lobby/middleware.js

Cors-avatars

---

react/features/filmstrip/components/native/TileView.js

fix(rn, tileview) Add SafeAreaView to Tile View

---

config.js
react/features/base/config/configWhitelist.js
react/features/filmstrip/components/web/Thumbnail.js
react/features/filmstrip/components/web/ThumbnailBottomIndicators.js

When passed as true, will hide the participant display name from the bottom indicators.

feat(config): add flag to hide the participant display name

---

react/features/facial-recognition/actionTypes.js
react/features/facial-recognition/actions.js
react/features/facial-recognition/constants.js
react/features/facial-recognition/functions.js
react/features/facial-recognition/middleware.js
react/features/facial-recognition/reducer.js

Send facial expressions to endpoint.

feat(facial-expressions): send facial expressions to webhook endpoint

---

react/features/breakout-rooms/components/native/CollapsibleRoom.js
react/features/breakout-rooms/components/web/CollapsibleRoom.js
react/features/breakout-rooms/components/web/RoomList.js
react/features/participants-pane/components/native/MeetingParticipantList.js
react/features/participants-pane/components/native/ParticipantsPane.js
react/features/participants-pane/components/web/MeetingParticipantItem.js
react/features/participants-pane/components/web/MeetingParticipants.js
react/features/participants-pane/components/web/ParticipantsPane.js
react/features/participants-pane/functions.js

fix(participants-pane) Make search work with breakout rooms

---

react/features/base/buttons/CopyButton.js

fix(base) fixed text going out of share meeting container

---

resources/prosody-plugins/mod_muc_lobby_rooms.lua

fix: Generates correct join error for lobby. 

---

react/features/base/participants/middleware.js
react/features/connection-indicator/components/web/ConnectionIndicatorContent.js

fix: Fixes showing user region.

---

react/features/breakout-rooms/constants.js
react/features/breakout-rooms/middleware.js
react/features/chat/actionTypes.js
react/features/chat/actions.any.js
react/features/chat/middleware.js
react/features/chat/reducer.js

Breakout messages

---

lang/main-ru.json

Another one missed Russian localization contribution

fix(lang) updated Russian translation

---

lang/main-nl.json

Added Dutch translations for the participants pane and for the Chat and Polls window and tabs.

Add Dutch translations Participants Pane and Chat/Polls

---

react/features/base/tracks/middleware.js

https://community.jitsi.org/t/unstable-version-only-cam-and-mic-muted-in-secure-domain/109270/13

fix: Fixes muted state for moderators when login (secure-domain).

---

react/features/always-on-top/HangupButton.js

fix(aot) Let jitsi-meet-electron-sdk do the close

---

lang/main-fr.json

Hello, I fixed a typo by replacing "réouvrir" with "Rouvrir"

French typo fix

---

react/features/polls/subscriber.js

fix(polls) use medium timeout for poll notifications

---

android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java

fix(rn,android) adjust changed package names

---

package-lock.json
package.json
react/features/welcome/components/settings/components/styles.js

1. Updated react-native-paper to 4.11.1
2. Fixed styles

update react-native-paper to 4.11.1

---

react/features/participants-pane/components/web/LobbyParticipants.js

feat(participants-pane) hide admit all if knocking part < 2

---

react/features/breakout-rooms/components/native/styles.js
react/features/conference/components/native/styles.js
react/features/filmstrip/components/native/Thumbnail.js
react/features/participants-pane/components/native/styles.js

1. Fixed long press on participant thumbnails
2. Center screen header close button vertically
3. Updated height, line height for add breakout room/invite buttons and their labels

mobile UI style updates

---

react/features/jaas/actionTypes.js
react/features/jaas/middleware.web.js

Console log settings error.

---

android/app/src/main/res/values/styles.xml

fix(android) disables windows preview

---

react/features/app/components/AbstractApp.js
react/features/app/components/App.native.js
react/features/prejoin/components/PrejoinApp.js

fix(rn) await for the promise in the _init object

---

react/features/filmstrip/components/web/Filmstrip.js

fix(filmstrip) don't display filmstrip toggle in Jibri

---

lang/main-pl.json

Lang: Typo in lang pl

---

css/modals/virtual-background/_virtual-background.scss
react/features/virtual-background/components/VirtualBackgroundDialog.js

fix(virtual-background): Prevent buttons repositioning on click action.

---

modules/API/API.js
react/features/shared-video/components/AbstractSharedVideoDialog.js
react/features/shared-video/functions.js

fix(iframeAPI): startShareVideo command.

---

.github/workflows/ci.yml
package.json
resources/lang-sort.sh

ci: ensure that lang files stay sorted

---

modules/API/API.js
react/features/recording/components/Recording/web/StopRecordingDialog.js

fix(screen-capture): disable

---

react/features/base/participants/middleware.js
react/features/polls/components/native/PollItem.js
react/features/polls/components/native/PollsList.js
react/features/polls/components/web/PollsList.js
react/features/polls/components/web/PollsPane.js
react/features/video-menu/components/AbstractGrantModeratorButton.js
react/features/video-menu/components/AbstractKickButton.js
react/features/video-menu/components/AbstractMuteEveryoneElseButton.js
react/features/video-menu/components/AbstractMuteEveryoneElsesVideoButton.js
react/features/video-menu/components/AbstractMuteVideoButton.js

The Metro bundler gets confused and the result of such import statements
is `undefined`.

fix(rn,build) fix use of "bare" relative path

---

.github/workflows/ci.yml
package-lock.json
package.json
webpack.config.js

Audit fix 8

---

android/build.gradle
package-lock.json
package.json

fix(android) drop jcenter

---

css/modals/_dialog.scss
lang/main.json
react/features/shared-video/components/native/SharedVideoDialog.js
react/features/shared-video/components/web/SharedVideoDialog.js

feat(shared-video): show  invalid URL error.

---

react/features/notifications/components/web/Notification.js

feat(notification-button-testid): Add testid to notification buttons.

---

package-lock.json
package.json
resources/update-ljm.sh

update ljm 1643213975

---

react/features/notifications/components/web/Notification.js

Fixes https://community.jitsi.org/t/browserwarning-popup-shows-object/110397/1

fix(notifications): support html descriptions

---

react/features/jaas/middleware.web.js

fix(iAmRecorder): middleware bug

---

lang/main.json
react/features/filmstrip/components/native/Thumbnail.js
react/features/participants-pane/actions.native.js
react/features/toolbox/components/native/ToggleSelfViewButton.js
react/features/video-menu/actions.native.js
react/features/video-menu/components/native/LocalVideoMenu.js
react/features/video-menu/components/native/index.js

Added toggle button in the overflow menu
Created video menu with connection info and self-view toggle buttons for local participant

feat(disableSelfView) Toggle self view on native

---

react/features/authentication/components/native/LoginDialog.js
react/features/authentication/components/web/LoginDialog.js
react/features/authentication/middleware.native.js
react/features/authentication/middleware.web.js

fix: Fixes #10796 authentication in conference.

---

package-lock.json
package.json
react/features/calendar-sync/web/microsoftCalendar.js

chore(deps) microsoft-graph-client@3.0.1

---

react/features/app/components/App.native.js

feat(app) fix navigation from external link

---

react/features/calendar-sync/components/CalendarList.native.js
react/features/mobile/navigation/components/welcome/components/WelcomePageTabs.js
react/features/recent-list/components/RecentList.native.js
react/features/welcome/components/WelcomePage.native.js

https://user-images.githubusercontent.com/26413496/151344131-ca410e7d-cc4a-4b4c-94c7-5707723713ae.mp4
Useful for devices that use an external keyboard.

feat(welcome) blur room name input onListContainerPress

---

modules/API/API.js
react/features/external-api/middleware.js

Enhanced the `videoConferenceJoined` event with a breakoutRoom flag.

feat(external-api) notify conference joined with room type flag

---

react/features/facial-recognition/actions.js
react/features/facial-recognition/constants.js
react/features/facial-recognition/facialExpressionsWorker.js
react/features/facial-recognition/functions.js

Set window screen size in worker with the value from main thread;
Refactor worker and add constants for message types;

fix(facial-expressions): set screen size in worker and add constants for worker message types

---

react/features/base/dialog/components/native/InputDialog.js
react/features/base/dialog/components/native/styles.js
react/features/display-name/components/native/DisplayNamePrompt.js
react/features/room-lock/components/PasswordRequiredPrompt.native.js
react/features/shared-video/components/native/SharedVideoDialog.js

feat(dialog) new native InputDialog

---

modules/API/API.js
modules/API/external/external_api.js

Added commands for add, remove, join, close, send participant to room and auto assign rooms + function for listing breakout rooms.

feat(external-api) expose breakout room actions to api

---

react/features/authentication/components/native/LoginDialog.js
react/features/base/dialog/components/native/InputDialog.js
react/features/base/dialog/components/native/styles.js

1. New LoginDialog
2. Removed unneeded check for title from InputDialog

feat(dialog) updated LoginDialog

---

package-lock.json
package.json

fix(ProxyConnection) set signaling layer by @saghul in #1862
fix: Fixes version while building. by @damencho in #1866
feat(multi-stream-support)Add support for multiple local and remote tracks/mediaType. by @jallamsetty1 in #1861
fix: Add private message handler for breakout_rooms by @steve-vsee in #1867
fix(JingleSessionPC) Do not force track removal at pc level on user leave. by @jallamsetty1 in #1869
feat(multi-stream-support) Handle SDP munging for multiple local/remote streams per ep. by @jallamsetty1 in #1868

chore(deps) lib-jitsi-meet@latest.

---

lang/main-nl.json

fix(lang) update Dutch translation

---

patches/react-native-dialog+9.2.0.patch

The new native dialog have a slightly not visible text color for the description.

feat(dialog) change description text color

---

react/features/authentication/components/native/LoginDialog.js
react/features/base/dialog/components/native/ConfirmDialog.js
react/features/base/dialog/components/native/InputDialog.js
react/features/base/react/components/native/styles.js
react/features/mobile/navigation/screenOptions.js
react/features/security/components/security-dialog/native/SecurityDialog.js
react/features/welcome/components/WelcomePage.native.js
react/features/welcome/components/styles.js

1. iOS screens have now a Close text button instead of a Close icon
2. InputDialogs have now a Cancel button
3. Fixes Welcome screen content too close to the margin

feat(dialog) refinaments

---

react/features/base/dialog/components/native/ConfirmDialog.js

Fixed ConfirmDialog broken translations

fix(dialog) fixed translations

---

react/features/base/components/context-menu/ContextMenu.js

Fixes issue where items are not visible in the context menu

fix(context-menu) Add max height

---

conference.js
config.js
package-lock.json
package.json
react/features/base/conference/actions.js
react/features/base/jwt/middleware.js
react/features/base/media/actions.js
react/features/base/media/middleware.js
react/features/follow-me/middleware.js

Hides the participant that has this flag in jwt from the recorder. A hidden meeting moderator.
Makes sure follows me works and no tracks are being added.

feat: Handles hidden-from-recorder from jwt.

---

react/features/mobile/navigation/screenOptions.js
react/features/welcome/components/native/settings/components/FormSectionAccordion.js
react/features/welcome/components/native/settings/components/SettingsView.js
react/features/welcome/components/native/settings/components/styles.js

1. Changed drawer background color
2. Setting view ui updates

feat(welcome) updated mobile ui styles

---

ios/Podfile
ios/Podfile.lock
ios/app/app.xcodeproj/project.pbxproj
ios/sdk/sdk.xcodeproj/project.pbxproj

Also update native dependencies.

fix(ios) make sure arm64 sim is not excluded

---

ios/Podfile.lock
package-lock.json
package.json

chore(deps) react-native-webrtc@1.94.2
